### ISSUE TITLE
预训练阶段的算力要求

### ISSUE THREAD

**Issue by 27182812** [ymcui/Chinese-LLaMA-Alpaca#1]
很棒的工作，请问可以告知预训练阶段采用的是什么样的配置，以及预训练时间吗？

**Comment by secain** [comment]
附问：预训练阶段的代码会开源吗

**Comment by airaria** [comment]
> 



> 附问：预训练阶段的代码会开源吗

预训练的代码基本与Transformers库里的run_clm.py的代码一致，仅针对我们的训练环境做了些改动，以及增加了LoRA model的搭建部分，所以建议直接参考原版run_clm.py。

**Comment by guotong1988** [comment]
分布式训练 是 数据并行 还是 模型并行？

**Comment by airaria** [comment]
> 分布式训练 是 数据并行 还是 模型并行？

See #4

**Comment by EasyLuck** [comment]
> > 很棒的工作，请问可以告知预训练阶段采用的是什么样的配置，以及预训练时间吗？
> 
> 在LoRA预训练阶段，用16张A100卡batch_size=1024大约6h可以训练1K步。其他算力的情况可以自行估算。

什么叫LORA预训练，不应该是lora finetune吗
