### ISSUE TITLE
再请教一下您对预训练阶段所起作用的见解

### ISSUE THREAD

**Issue by songbaiTalk** [ymcui/Chinese-LLaMA-Alpaca#10]
我通过lora方式进行fine-tune llama的时候发现，如果我给一些事实性的样本进行fine-tune，模型并不会学到事实，您是否认为事实性的学习发生于预训练阶段而SFT仅能做对齐提高模型的理解表达能力，不能增加事实知识（亦或是lora仅在attention层嵌入adapter导致无法新增事实性的内容）？

**Comment by ymcui** [comment]
1、我们增加预训练阶段的主要目的是适配新增中文词表的词向量学习，以进一步提升基本的中文语义能力。
2、事实性学习发生在pre-train还是fine-tune阶段目前无从得知。你可以类比传统基于NLU的预训练模型（例如BERT）在finetune阶段是可以学习更多事实性知识的（但不能否认大部分基础知识是pre-train阶段学习得到的），所以你说的问题有可能是因为SFT不充分等因素导致。
3、LoRA adapter部分相比原版增加了更多可调参数，你可以对比原版和我们的相应部分：
- 原版：https://github.com/tloen/alpaca-lora/blob/main/export_state_dict_checkpoint.py#L31
- 我们：https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/export_state_dict_checkpoint.py#L51
但至于是不是这部分参数不足以学习到事实知识还需要更深入细致的研究。
