### ISSUE TITLE
答案和输出示例的答案差距有点大

### ISSUE THREAD

**Issue by hcl242** [ymcui/Chinese-LLaMA-Alpaca#101]
![image](https://user-images.githubusercontent.com/56509012/230819032-e9ea97be-76eb-407b-8616-e9ab88d5015d.png)
我的启动命令与参数是这样的:main.exe -m ggml-model-q4_0.bin --color -ins -c 2048 --temp 1 -n 256 --repeat_penalty 1 --color -f alpaca.txt 
请问下是我的参数有什么问题吗？

**Comment by ymcui** [comment]
这个是7B还是13B的模型？

**Comment by hcl242** [comment]
> 你好 这是13B的模型

**Comment by hcl242** [comment]
> 这个是7B还是13B的模型？
你好 这是13B的模型 alpaca 13b

**Comment by airaria** [comment]
用这组参数 “--temp 0.2 -n 512 --repeat_penalty 1.3”试试？

**Comment by ymcui** [comment]
结果比较奇怪，我用了你设置的参数，输出是正常的，见以下结果（随机运行两次）。
第一次：
```
> 请你帮我写一封签证申请信
尊敬的签证官，

我写信是为了向您申请一份签证，以便能够前往您所属的国家访问我的朋友和家人。我是一位专业的工程师，有丰富经验和知识，可以在您国家工作期间。我是诚实守法的人，并且已经支付了我所有应付的费用和税款。我相信我可以成为您国家的一名有价值的公民，并能为您国家的发展做出积极的贡献。

我非常感谢您对此申请的考虑，我保证我遵守所有程序，并提供所有相关材料。谢谢您的时间和关注。

此致
敬礼
```
第二次：
```
尊敬的签证官，

我是一名来自中国的学生，我申请前往美国留学。我会在美国的大学学习，并在美国工作，学习专业知识。我希望能够在您的国家获得访问许可，以充分体验美国的文化和教育机会。

在此之前，我已提交了所有必要的文件和信息，并已通过必要的考试和评估，我被认为是能够适应美国学习和工作环境的学生。

谢谢您的时间，我期待着您的审批，并有幸访问您的国家。

此致
敬礼
(签名)
```

你的`alpaca.txt`文件内容是什么呢？

**Comment by ymcui** [comment]
另外，可以校验一下sha256。
```
d0e1b9279bd9be606073acf2fb204e616d2f7e4e833b7ff60620ebdfb8fa4e73  zh-alpaca-models/13B/ggml-model-q4_0.bin
```

**Comment by hcl242** [comment]
![image](https://user-images.githubusercontent.com/56509012/230821556-019e9196-ee10-436d-a71e-8a34f3624950.png)
目前看起来一切正常了，谢谢你们。

**Comment by hcl242** [comment]
我试了新的参数：main.exe -m zh-models/13B/ggml-model-q4_0.bin --color -ins -c 2048 --temp 0.6 -n 256 --repeat_penalty 1.3 --color -f prompts/alpaca.txt

**Comment by hcl242** [comment]
> 另外，可以校验一下sha256。
> 
> ```
> d0e1b9279bd9be606073acf2fb204e616d2f7e4e833b7ff60620ebdfb8fa4e73  zh-alpaca-models/13B/ggml-model-q4_0.bin
> ```

谢谢

**Comment by hcl242** [comment]
> 用这组参数 “--temp 0.2 -n 512 --repeat_penalty 1.3”试试？

谢谢
