### ISSUE TITLE
怎么暴露成api啊 通过界面请求

### ISSUE THREAD

**Issue by controZheng** [ymcui/Chinese-LLaMA-Alpaca#102]
请问一下怎么封装一个api  通过界面访问进行对话

**Comment by Mabbs** [comment]
参见 https://github.com/oobabooga/text-generation-webui

**Comment by xiaoxixiao** [comment]
> 这个windows使用大概率会报错MicroMamba挂钩未找到，我需要更好地方式

**Comment by LiemLin** [comment]
python server.py --listen --api
