### ISSUE TITLE
本地部署经过量化的模型貌似无法理解中文Prompt?

### ISSUE THREAD

**Issue by LainNya** [ymcui/Chinese-LLaMA-Alpaca#11]
你好，我在推理时遇到了问题,在尝试输入中文Prompt时，模型给出的输出经常是答非所问,但输入英文Prompt就正常输出了,请问是什么问题?我启动模型的命令是完全按照Steps3输入的。而且模型的回复也不是中文的？
![image](https://user-images.githubusercontent.com/18028414/228740767-241e2351-c4b7-4b74-8583-28300f9e5a91.png)

**Comment by airaria** [comment]
从回复内容和风格看，似乎不是我们这一版模型。因为合并过程中涉及的的权重文件比较多，请确认下中间转换过程用的权重是否弄混淆了？

**Comment by LainNya** [comment]
我的操作如下
1.把原版llama转换成HF格式
2.从谷歌网盘下载了Chinese-Alpaca-7B的Lora
3.对中文词表扩充,  llama_model的路径为原版转换后的模型, tokenizer的路径为Chinese-Alpaca-7B的路径
4.合并权重 base_model为第三步扩充后的模型,lora_model为Chinese-Alpaca-7B的路径
我觉得我操作应该没有混淆吧 :(

**Comment by ymcui** [comment]
> 我的操作如下
> 1.把原版llama转换成HF格式
> 2.从谷歌网盘下载了Chinese-Alpaca-7B的Lora
> 3.对中文词表扩充, llama_model的路径为原版转换后的模型, tokenizer的路径为Chinese-Alpaca-7B的路径
> 4.合并权重 base_model为第三步扩充后的模型,lora_model为Chinese-Alpaca-7B的路径
> 我觉得我操作应该没有混淆吧 :( 我的朋友尝试了下也得出了这样的结果

可以把`./main`运行后马上输出出来的log贴一下吗（到提示符`>`之前）？

**Comment by airaria** [comment]
> 你好，我在推理时遇到了问题,在尝试输入中文Prompt时，模型给出的输出经常是答非所问,但输入英文Prompt就正常输出了,请问是什么问题?我启动模型的命令是完全按照Steps3输入的。而且模型的回复也不是中文的？
> ![image](https://user-images.githubusercontent.com/18028414/228740767-241e2351-c4b7-4b74-8583-28300f9e5a91.png)

可以检查一下几个中间文件的SHA256 是否一致：
adapter_model.bin: 0d9b6ed8e4a7d1ae590a16c89a452a488d66ff07e45487972f61c2b6e46e36de
合并后的consolidated.00.pth:  fbfccc91183169842aac8d093379f0a449b5a26c5ee7a298baf0d556f1499b90

**Comment by LainNya** [comment]
> > 我的操作如下
> > 1.把原版llama转换成HF格式
> > 2.从谷歌网盘下载了Chinese-Alpaca-7B的Lora
> > 3.对中文词表扩充, llama_model的路径为原版转换后的模型, tokenizer的路径为Chinese-Alpaca-7B的路径
> > 4.合并权重 base_model为第三步扩充后的模型,lora_model为Chinese-Alpaca-7B的路径
> > 我觉得我操作应该没有混淆吧 :( 我的朋友尝试了下也得出了这样的结果
> 
> 可以把运行后马上输出出来的log贴一下吗（到提示符之前）？`./main``>`

![image](https://user-images.githubusercontent.com/18028414/228769563-d33fa7ed-2a3a-43a7-811d-9be6ceed1a54.png)
这是我的log日志

**Comment by LainNya** [comment]
> > 你好，我在推理时遇到了问题,在尝试输入中文Prompt时，模型给出的输出经常是答非所问,但输入英文Prompt就正常输出了,请问是什么问题?我启动模型的命令是完全按照Steps3输入的。而且模型的回复也不是中文的？
> > ![image](https://user-images.githubusercontent.com/18028414/228740767-241e2351-c4b7-4b74-8583-28300f9e5a91.png)
> 
> 可以检查一下几个中间文件的SHA256 是否一致： adapter_model.bin: 0d9b6ed8e4a7d1ae590a16c89a452a488d66ff07e45487972f61c2b6e46e36de 合并后的consolidated.00.pth: fbfccc91183169842aac8d093379f0a449b5a26c5ee7a298baf0d556f1499b90

貌似我的consolidated.00.pth与你的不一致

**Comment by LainNya** [comment]
最新的export_state_dict_checkpoint.py生成的consolidated.00.pth sha256一致了，可以正常中文推理了:D

**Comment by LainNya** [comment]
> 最新的export_state_dict_checkpoint.py生成的consolidated.00.pth sha256一致了，可以正常中文推理了:D

抱歉，我结束的太早了，貌似还是不能正常?

**Comment by LainNya** [comment]
![image](https://user-images.githubusercontent.com/18028414/228844869-d78884db-9b12-47ef-96f5-3f3e1732cd0e.png)
这是我的量化后模型的sha256 f19503385fb3ab92ec96f2b6a2d733f07e368c836ba7a1d575699159156ac0e6

**Comment by airaria** [comment]
如果consolidated.00.pth的sha256一致，

> ![image](https://user-images.githubusercontent.com/18028414/228844869-d78884db-9b12-47ef-96f5-3f3e1732cd0e.png) 这是我的量化后模型的sha256 f19503385fb3ab92ec96f2b6a2d733f07e368c836ba7a1d575699159156ac0e6
> 
> 合并后的全量模型权重的SHA256 ![image](https://user-images.githubusercontent.com/18028414/228846204-4c176596-e472-45c2-9732-04e3c7ee8e03.png)

我q4量化后模型的sha256的和你是一致的

**Comment by LainNya** [comment]
那请问我这是什么问题呢?我现在完全不回答我的问题
![image](https://user-images.githubusercontent.com/18028414/228848813-54e27736-4981-424d-87e9-a42f2cdb7735.png)

**Comment by airaria** [comment]
> 那请问我这是什么问题呢?我现在完全不回答我的问题
> ![image](https://user-images.githubusercontent.com/18028414/228848813-54e27736-4981-424d-87e9-a42f2cdb7735.png)

你试试用lamma.cpp加载原版lamma看有没有问题

**Comment by codica** [comment]
我也是类似问题，会不会跟这个有关，protobuf版本太低了，因为安装过程要求只能使用3.20.x
<img width="710" alt="Screenshot 2023-03-31 at 08 25 33" src="https://user-images.githubusercontent.com/6890296/228992935-72401107-4977-4b52-a54c-97b133ffed44.png">

**Comment by LainNya** [comment]
> 我也是类似问题，会不会跟这个有关，protobuf版本太低了，因为安装过程要求只能使用3.20.x <img alt="Screenshot 2023-03-31 at 08 25 33" width="710" src="https://user-images.githubusercontent.com/6890296/228992935-72401107-4977-4b52-a54c-97b133ffed44.png">

低版本也会导致这个问题吗？我的是3.19
0

**Comment by LainNya** [comment]
![image](https://user-images.githubusercontent.com/18028414/229009106-2766dd91-a8dd-4b69-9256-593c4e382fcb.png)
尝试打印了下main.exe获取的值，貌似中文就没获取到，我的cpp基础很差，不知道怎么更改.
应该是在这行
![image](https://user-images.githubusercontent.com/18028414/229009330-5bffe4f3-7307-4ce1-8852-cb28316cfa57.png)

**Comment by LainNya** [comment]
大概就是这个原因，我将关闭这个提问

**Comment by airaria** [comment]
@LainNya #20 这个或许对你有帮助。

**Comment by boholder** [comment]
https://github.com/ggerganov/llama.cpp/issues/646
llama.cpp 项目下对应的讨论，总之先用git-bash或WSL吧。

 @ymcui 打扰下，方便把这个知识加进README吗？

**Comment by ymcui** [comment]
> [ggerganov/llama.cpp#646](https://github.com/ggerganov/llama.cpp/issues/646) llama.cpp 项目下对应的讨论，总之先用git-bash或WSL吧。
> 
> @ymcui 打扰下，方便把这个知识加进README吗？

感谢提供信息，我先把这个issue PIN起来，后续加到合适的位置。

**Comment by hyperzlib** [comment]
看看readline之后有没有编码转换？CMD和PowerShell默认是GBK（CP936）编码，而Linux Shell默认是UTF-8，可能是这个问题。

**Comment by nanmu42** [comment]
也许可以放到项目的Wiki里，再在README里加个到Wiki的链接。

**Comment by sgcwddhr** [comment]
为什么我在git bash中也不支持中文prompt。有大佬能看看吗？
![1680604452647](https://user-images.githubusercontent.com/128665355/229765906-233da356-1a6b-4b67-9500-dabe9a69fc76.jpg)

**Comment by sgcwddhr** [comment]
> > @LainNya #20 这个或许对你有帮助。
> 
> 我也已经发现这个问题了，Windows 平台下cmd和poweshell有问题，但我在git bash内执行就没问题了

我在git bash 中也不支持中文，什么原因
![1680604605304](https://user-images.githubusercontent.com/128665355/229766496-afa759de-37e4-490a-ad78-39113c6b2a79.jpg)

**Comment by ymcui** [comment]
> 我改了一下实现, 现在可以支持中文输入了, 配置开箱即用: https://github.com/josStorer/llama.cpp-unicode-windows
> 
> 用`_getwch`手动实现了unicode兼容的getline, 目前实现了输入, 退格, 左右移动光标, 以及回车, 足够常规使用 (不确定是不是最佳的解决方案, 但能解决问题)
> 
> ![O%BKDC3SM}TZQ8ZKQBPG4FE](https://user-images.githubusercontent.com/13366013/229809279-ebeb5edc-f4bb-430c-867d-246bb9741807.jpg)

感谢，已添加到README中。

**Comment by boholder** [comment]
> 我改了一下实现, 现在可以支持中文输入了, 配置开箱即用: https://github.com/josStorer/llama.cpp-unicode-windows

Nice work!

原llama.cpp 项目中已合并了 https://github.com/ggerganov/llama.cpp/pull/420
解决了输入问题但没解决输出问题：
> it is currently not possible to insert or display utf-8 characters at moment.
https://github.com/ggerganov/llama.cpp/issues/646#issuecomment-1498017664

我不确定你是否方便提个pr，让原llama.cpp也支持输出UTF-8（和对UTF-8的修改）？...

**Comment by josStorer** [comment]
@boholder 我的改动不是跨平台的, 并且并不是完全兼容getline, 对于一些依赖命令行输入输出的API服务有兼容问题, 所以我觉得不适合提到官方仓库, 适合直接作为命令行体验

**Comment by boholder** [comment]
> @boholder 我的改动不是跨平台的, 并且并不是完全兼容getline, 对于一些依赖命令行输入输出的API服务有兼容问题, 所以我觉得不适合提到官方仓库, 适合直接作为命令行体验
> 
> 我在原项目问题下也提了我的解决方案, 我想仓库维护者也看到了

原来是这样，不好意思我没了解情况。。再次谢谢你提供了解决方案。

**Comment by josStorer** [comment]
@boholder 我目前正在针对指令模式把llama做成api服务, 这个方案可以配合应用落地, 并且能够使用中文

https://github.com/josStorer/selfhostedAI 现在已经可用, 但是我还没更新使用说明

这里是一个应用API调用的示例
![64J_YRL$9TRUDH0PQWG8{8](https://user-images.githubusercontent.com/13366013/230273331-2aa1192f-bb9d-49e7-b422-d906244670e8.jpg)

**Comment by ZetaSp** [comment]
是否考虑换用python版的llama.cpp？
python输出或许可以解决cpp版的中文支持问题

**Comment by wwwwwuxueyu** [comment]
> @boholder 我目前正在针对指令模式把llama做成api服务, 这个方案可以配合应用落地, 并且能够使用中文
> 
> https://github.com/josStorer/selfhostedAI 现在已经可用, 但是我还没更新使用说明
> 
> 这里是一个应用API调用的示例 ![64J_YRL$9TRUDH0PQWG8{8](https://user-images.githubusercontent.com/13366013/230273331-2aa1192f-bb9d-49e7-b422-d906244670e8.jpg)

我想请问一下 可以支持llamacpp 结合的chinesellamaaplaca模型吗？

**Comment by josStorer** [comment]
@wwwwwuxueyu 截图里用的就是这个仓库的中文模型效果
