### ISSUE TITLE
使用hf版本做生成的时候，generate用什么参数合适呢？

### ISSUE THREAD

**Issue by chenhk-chn** [ymcui/Chinese-LLaMA-Alpaca#110]
我尝试使用了默认参数来做generate，但是似乎会有很多重复。请问这个用什么样的参数比较好呢？
```
prompt = ‘你好，请介绍你自己\n’
data = tokenizer(prompt, return_tensors="pt", add_special_tokens=False).input_ids.cuda()
outputs_ids = model.generate(data, max_length=512)
outputs = tokenizer.decode(outputs_ids[0], skip_special_tokens=True)
```

一个例子：
'你好，请介绍你自己\n 主持人：你好，我是主持人，请简单介绍一下自己。\n 嘉宾：我是某知名的主持人，曾经主持过很多节目，包括《快乐大本营》、《超级女声》、《中国好声音》等。\n 主持人：你好，我是某知名的主持人，曾经主持过很多节目，包括《快乐大本营》、《超级女声》、《中国好声音》等。 主持人：你好，我是某知名的主持人，曾经主持过很多节目，包括《快乐大本营》、《超级女声》、《中国好声音》等。 主持人：你好，我是某知名的主持人，曾经主持过很多节目，包括《快乐大本营》、《超级女声》、《中国好声音》等。 主持人：你好，我是某知名的主持人，曾经主持过很多节目，包括《快乐大本营》、《超级女声》、《中国好声音》等。 主持人：你好，我是某知名的主持人，曾经主持过很多节目，包括《快乐大本营》、《超级女声》、《中国好声音》等'

**Comment by airaria** [comment]
你忘记加Alpaca的prompt了

**Comment by chenhk-chn** [comment]
是这样的prompt 吗？
`
data = tokenizer('<s> Below is an instruction that describes a task. Write a response that appropriately completes the request.\n### Instruction:\n你好，请介绍你自己\n\n### Response:\n', return_tensors="pt", add_special_tokens=False).input_ids.cuda()
outputs_ids = model.generate(data, max_new_tokens=50)
outputs = tokenizer.decode(outputs_ids[0], skip_special_tokens=True)
`
以上的输出会是这样。
`outputs
'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n### Instruction:\n你好，请介绍你自己\n\n### Response:\n我是一名AI语言模型，可以回答各种问题，并提供有用的信息。 我很高兴认识你，有什么可以帮助你的吗？， 是？，'
`

**Comment by airaria** [comment]
> 是这样的prompt 吗？
> `data = tokenizer('<s> Below is an instruction that describes a task. Write a response that appropriately completes the request.\n### Instruction:\n你好，请介绍你自己\n\n### Response:\n', return_tensors="pt", add_special_tokens=False).input_ids.cuda() outputs_ids = model.generate(data, max_new_tokens=50) outputs = tokenizer.decode(outputs_ids[0], skip_special_tokens=True)`
> 以上的输出会是这样。
> `outputs 'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n### Instruction:\n你好，请介绍你自己\n\n### Response:\n我是一名AI语言模型，可以回答各种问题，并提供有用的信息。 我很高兴认识你，有什么可以帮助你的吗？， 是？，' `

差不多是这样，不需要前面的<s>:
'Below is an instruction that describes a task. Write a response that appropriately completes the request.\n### Instruction:\n{instruction}\n\n### Response: '
