### ISSUE TITLE
可否出用huggingface调用api的官方教程

### ISSUE THREAD

**Issue by zhouj8553** [ymcui/Chinese-LLaMA-Alpaca#111]
我用huggingface直接生成的文本虽然是合理的，但普遍非常短，我也没有发现更改generator里的什么超参数可以生成稍长一些的文本。我想知道这是llama.cpp和我生成代码的差异产生的吗？我在issues区域发现这是一个还挺普遍的现象。

**Comment by chenhk-chn** [comment]
可以求一份hf做生成的参数参考呢？我使用hf生成的文本会出现很多重复。

**Comment by airaria** [comment]
我们会近期给出一个inference的简单脚本供参考。

**Comment by airaria** [comment]
已更新[Transformers原生推理脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/inference_hf.py)和[使用说明](https://github.com/ymcui/Chinese-LLaMA-Alpaca#使用transformers推理)，欢迎参考

**Comment by airaria** [comment]
> 

确实是Transformers和llama.cpp有差异；推理脚本已经尽量接近llama.cpp的效果
