### ISSUE TITLE
python 要装哪个版本呢？

### ISSUE THREAD

**Issue by wa2003** [ymcui/Chinese-LLaMA-Alpaca#112]
python我装的是3.6.8，结果装下面的都报错，说是没有匹配的版本，是不是python版本太低了？
pip install git+https://github.com/huggingface/transformers
pip install sentencepiece
pip install peft

**Comment by ymcui** [comment]
Python 3.10试一下

**Comment by wa2003** [comment]
> 

3.10的版本好使，解决了
