### ISSUE TITLE
合并后输出信息不正确

### ISSUE THREAD

**Issue by candowu** [ymcui/Chinese-LLaMA-Alpaca#116]
1.从huggingface下载lora权重
2.合并为hf版本，脚本如下：
python scripts/merge_llama_with_chinese_lora_to_hf.py \
    --base_model decapoda-research/llama-13b-hf \
    --lora_model ziqingyang/chinese-alpaca-lora-13b \
    --output_dir chinese-alpaca-lora-13b
3.使用Alpaca-lora工程提供的方法测试，不加载lora权重，输入结果如下：
![111](https://user-images.githubusercontent.com/4629043/231027713-332c8785-71e6-4b5f-8d18-48dfc3f0ce9a.png)

**Comment by candowu** [comment]
![企业微信截图_1681175294254](https://user-images.githubusercontent.com/4629043/231029690-ef67cca9-db37-4afc-8ab2-8b2c02348523.png)

**Comment by airaria** [comment]
看起来是没有在遇到<\s>后终止输出。

**Comment by zyds** [comment]
> generate方法里加上参数`eos_token_id = tokenizer.eos_token_id`呢

非常感谢！加上这个参数后，我这边就一切正常了！
