### ISSUE TITLE
合并后没有量化的全量中文llama模型应该怎么推理？用原始的llama推理代码一直报词表数量无法整除

### ISSUE THREAD

**Issue by FastBCSD** [ymcui/Chinese-LLaMA-Alpaca#118]
AssertionError: 49953 is not divisible by 2
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 2276862 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2276861) of binary: /home/platform/anaconda3/envs/hcs/bin/python
Traceback (most recent call last):

**Comment by Shannen3206** [comment]
同问
