### ISSUE TITLE
全量模型(.pth)转huggingface参数模型遇到的问题和解决方法

### ISSUE THREAD

**Issue by LeonG7** [ymcui/Chinese-LLaMA-Alpaca#12]
### 问题
在step3结束后得到了.pth版本的文件consolidated.00.pth，想使用huggingface加载方式来调用模型，所以要把.pth格式转为bin格式。但是转的时候报错了
```
python convert_llama_weights_to_hf.py \   
--input_dir /xxx/llama_alpaca_zh_HIT \  # .pth文件保存位置
--model_size 7B \
--output_dir your/output/path
```

`FileNotFoundError: [Errno 2] No such file or directory: '/xxx/llama_alpaca_zh_HIT/7B/params.json'`
以及这个错误
`FileNotFoundError: [Errno 2] No such file or directory: '/xxx/llama_alpaca_zh_HIT/tokenizer.model'`
### 解决方法
只需在**llama_alpaca_zh_HIT**文件夹中新建一个名为7B的文件夹，将**params.json**和**consolidated.00.pth**都存入进去，然后将step2中得到的llama+中文词表模型的**tokenizer.model**文件存入**llama_alpaca_zh_HIT**文件夹就可以正常导出为huggingface格式的参数模型。后续的调用就不需要使用[llama.cpp工具](https://github.com/ggerganov/llama.cpp)了。

### 参考调用方法
https://github.com/LC1332/Chinese-alpaca-lora/blob/main/notebook/evaluation_code.ipynb
不需要lora合并 PeftModel.from_pretrained 这一步，直接加载使用就行了。

**Comment by airaria** [comment]
We have added a new script [merge_llama_with_chinese_lora_to_hf.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_llama_with_chinese_lora_to_hf.py) for merging lora weight and base model to huggingface format
