### ISSUE TITLE
合并7B模型时报错

### ISSUE THREAD

**Issue by wa2003** [ymcui/Chinese-LLaMA-Alpaca#121]
![image](https://user-images.githubusercontent.com/11847871/231114875-d326dc06-2d50-4085-9242-622418bf70d6.png)

**Comment by ymcui** [comment]
这种自动被kill的多半是内存不够导致的

**Comment by wa2003** [comment]
3090的显卡，24G内存，7B的llama模型参数合并时过不去，咋这么吃显存？
![image](https://user-images.githubusercontent.com/11847871/231132101-78bf5809-fd19-41b7-9942-70ba3884dbe3.png)

**Comment by airaria** [comment]
不使用CUDA，只用内存，能正常合并吗？
同时建议尝试更新accelerate等库，以及使用--offload_dir参数，以降低内存消耗

**Comment by airaria** [comment]
> 不使用CUDA，只用内存，能正常合并吗？ 开关参数怎么设置呢？ 内存是 120G的，应该够了吧

CUDA_VISIBLE_DEVICES= python merge_llama_with_chinese_lora.py ......

**Comment by runzhi214** [comment]
> 

参考Vicuna、Koala和Alpaca的合并LLaMa-7B数据，大约需要30 GB of CPU RAM
