### ISSUE TITLE
按照说明文档来配合的，效果特别差劲，原因是什么呢？

### ISSUE THREAD

**Issue by listwebit** [ymcui/Chinese-LLaMA-Alpaca#122]
我按照：https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/notebooks/convert_and_quantize_chinese_llama.ipynb
上面配置安装的，但是很多问题都是答非所问，不知道什么原因：
![2023-04-11 17-30-07屏幕截图](https://user-images.githubusercontent.com/5664241/231119591-efb15b88-d978-432d-ac7a-4ad9829b8700.png)
![2023-04-11 17-33-22屏幕截图](https://user-images.githubusercontent.com/5664241/231119602-67b4d1e3-1c26-4b77-80ae-670a75fb070b.png)

**Comment by ymcui** [comment]
1. 加-ins试试交互式
2. 看似llama.cpp不是最新版，可以git pull最新版重新编译一下 make clean && make

**Comment by Sped0n** [comment]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/70063177/231192727-850c55d5-4e9e-45e6-85a0-f1479b264396.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/70063177/231193835-4e2d1699-ea30-4990-b6ea-54739ed21f7e.png">

遇到了类似的问题，7B和13B都是一样乱回答，`llama.cpp`为`master-2663d2c`分支。

**Comment by airaria** [comment]
不要用 -p参数，用-ins 交互式方式启动试试

**Comment by Sped0n** [comment]
交互方式貌似没有改观

<img width="756" alt="image" src="https://user-images.githubusercontent.com/70063177/231201960-3dab793b-4ec0-4dae-9cc1-e5bd155fecaa.png">

<img width="680" alt="image" src="https://user-images.githubusercontent.com/70063177/231202343-39c7f44e-b362-407a-9845-4a54320b1de2.png">

**Comment by airaria** [comment]
我调试发现可能和peft版本有关。可否安装peft==0.2.0试试？

**Comment by airaria** [comment]
另外，请拉取最新的项目代码，重新跑合并脚本试试。

**Comment by Sped0n** [comment]
> 可能和peft版本有关。可否安装peft==0.2.0试试？

我看了一下确实是peft的版本出现了问题，谢谢指导

![IMG_9141](https://user-images.githubusercontent.com/70063177/231239943-cf0cdba5-0535-4942-8bba-291a4a10dbb9.jpg)

貌似是租的服务器那边用了一个更新比较慢的国内源，peft最新版本就`0.1.0`，去pypi上手动搞个wheel装完再一路走下来就没事了

![IMG_9142](https://user-images.githubusercontent.com/70063177/231240388-e7f78ab2-f680-45a8-88c2-7622d9c3254a.jpg)

**Comment by wantsor** [comment]
我的peft版本是正确的0.2.0， 但是合并出来一塌糊涂， 我用的是m1 mac专用的tensorflow-meta ，是不是这个版本会有问题呀[](url)

**Comment by Sped0n** [comment]
> 我的peft版本是正确的0.2.0， 但是合并出来一塌糊涂， 我用的是m1 mac专用的tensorflow-meta ，是不是这个版本会有问题呀

我合并的时候并没有用到tensorflow
