### ISSUE TITLE
请问如何使用GPU部署呢

### ISSUE THREAD

**Issue by Chenhuaqi6** [ymcui/Chinese-LLaMA-Alpaca#124]

**Comment by airaria** [comment]
我们会近期给出一个inference的简单脚本供参考。

**Comment by baoluo777** [comment]
目前使用的是llama.app来运行模型，这是llama.app的介绍：
The main goal is to run the model using 4-bit quantization on a MacBook

Plain C/C++ implementation without dependencies
Apple silicon first-class citizen - optimized via ARM NEON and Accelerate framework
AVX2 support for x86 architectures
Mixed F16 / F32 precision
4-bit quantization support
Runs on the CPU

可以看到这里强调了是在CPU上运行.

如果要在gpu上运行，我找到一个工程：
https://github.com/FMInference/FlexGen

**Comment by airaria** [comment]
已更新[Transformers原生推理脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/inference_hf.py)和[使用说明](https://github.com/ymcui/Chinese-LLaMA-Alpaca#使用transformers推理)，欢迎参考

**Comment by ykk648** [comment]
已测试成功
