### ISSUE TITLE
您好，请问一下，decapoda-research发布的权重可以应用到本项目吗

### ISSUE THREAD

**Issue by another1s** [ymcui/Chinese-LLaMA-Alpaca#125]
如题，在huggingface上找到两个一个Nyanko7的另一个decapoda的llama权重。但是下载了后者。。。。
使用convert_llama_weights_to_hf的时候才发现根本不适用，后面才看到“本项目不对使用第三方（非Facebook官方）权重的合规性和正确性负责，例如HuggingFace模型库中的decapoda-research/llama-7b-hf（use at your own risk）。”
那么现在有没有脚本可以支持decapoda这个版本的权重呢？

**Comment by ymcui** [comment]
建议你查看一下我们的Colab notebook（https://colab.research.google.com/drive/1Eak6azD3MLeb-YsfbP8UZC8wrL1ddIMI?usp=sharing）或者`notebook/`文件夹下的ipynb文件就有答案了。

**Comment by raodong** [comment]
huggingface上的 decapoda-research/llama-7b-hf 里面已经是hf格式的，不需要convert to hf这一步，直接从合并权重这一步开始就可以
