### ISSUE TITLE
关于放置哪个tokenizer.model到zh-models目录下

### ISSUE THREAD

**Issue by camelweiming** [ymcui/Chinese-LLaMA-Alpaca#126]
根据需要转换的模型类型（LLaMA或Alpaca），将下载的LoRA模型压缩包中的tokenizer.model文件放入zh-models目录下，将[合并模型](https://github.com/ymcui/Chinese-LLaMA-Alpaca#%E5%90%88%E5%B9%B6%E6%A8%A1%E5%9E%8B)中最后一步获取的模型文件consolidated.*.pth和配置文件params.json放入zh-models/7B目录下。

请教一下，为什么不放合并模型下面那个tokenizer.model呢？

**Comment by ymcui** [comment]
嗯，这个是一个历史遗留问题，感谢提醒。
你diff一下可以看出来，这两个文件是一样，放哪个都行。稍后会更新一下README。
