### ISSUE TITLE
作者可以提供一下解码参数吗，或者看看我这个参数有没有大的问题，我这个效果比官方的要差一点，但不是太多

### ISSUE THREAD

**Issue by FastBCSD** [ymcui/Chinese-LLaMA-Alpaca#127]
with torch.no_grad():
        generated = model.generate(inputs=batch["input_ids"],
                                    do_sample=True, #use_cache=True,
                                    #repetition_penalty=1.3,
                                    max_new_tokens=500,
                                    #temperature=0.2,
                                    #top_p=0.95,
                                    #top_k=40,
                                    return_dict_in_generate=True,
                                    output_attentions=False,
                                    output_hidden_states=False,
                                    output_scores=True)

**Comment by airaria** [comment]
你可以先尝试一下这组参数`temperature=0.7, top_p=0.95, do_sample=True, num_beams=1, eos_token_id = tokenizer.eos_token_id`。
我们稍后会给出inference脚本供参考

**Comment by airaria** [comment]
[inference脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/inference_hf.py)已更新。
