### ISSUE TITLE
可不可以在云盘放一个13B的文件呢？

### ISSUE THREAD

**Issue by camelweiming** [ymcui/Chinese-LLaMA-Alpaca#129]
首先感谢作者，根据你的教程已经成功运行了7B版本。

我看到网盘有一个7B的文件，可不可以加一个13B的呢？

我在想能不能做一个服务，定期更新文件，这样大家就不用每次都那么麻烦去转换，把使用的门槛降低，这样不是很好吗？

**Comment by ymcui** [comment]
不太清楚你说的网盘具体指的是哪个链接。我们现在给出的只有LoRA权重（百度网盘、Google Drive、HuggingFace模型库）。

**Comment by ymcui** [comment]
> 这样大家就不用每次都那么麻烦去转换，把使用的门槛降低，这样不是很好吗？

这个问题我们已经阐述过理由了，并不是为了让大家瞎忙活，具体见[FAQ#1](https://github.com/ymcui/Chinese-LLaMA-Alpaca#问题1为什么不能放出完整版本权重)
