### ISSUE TITLE
这个问题为啥无法回答

### ISSUE THREAD

**Issue by lucasjinreal** [ymcui/Chinese-LLaMA-Alpaca#132]
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/21303438/231341159-389e622f-1c42-46cf-98ad-f7fd6f2c50c5.png">

**Comment by ymcui** [comment]
你提的那些答不出来也正常。
另外你说样例里的问题，我们都是单独测的（不包含任何上下文历史）。
已知有上下文的情况下，后续的提问是会受到影响的。
