### ISSUE TITLE
7B模型跑出来了，答非所问啊，问题出在哪里？

### ISSUE THREAD

**Issue by wa2003** [ymcui/Chinese-LLaMA-Alpaca#134]
![image](https://user-images.githubusercontent.com/11847871/231364593-f315a0e0-6c49-4d8d-908f-8520de0bd504.png)

**Comment by wa2003** [comment]
我用的是原始的llama+扩展中文词表 的弄的，看来是不行，再用alpaca试试

**Comment by ymcui** [comment]
llama是没有用指令数据训练的

**Comment by zyxdm** [comment]
> ![image](https://user-images.githubusercontent.com/11847871/231364593-f315a0e0-6c49-4d8d-908f-8520de0bd504.png)

请问你这个问题解决了么？

**Comment by ShawnNew** [comment]
![image](https://user-images.githubusercontent.com/21559339/236988480-906e523c-b8db-4d6b-afbd-19a21175cc76.png)
llama+lora同样在胡言乱语，请问如何评判模型的准确度和效果呢？

**Comment by airaria** [comment]
> ![image](https://user-images.githubusercontent.com/21559339/236988480-906e523c-b8db-4d6b-afbd-19a21175cc76.png)
> llama+lora同样在胡言乱语，请问如何评判模型的准确度和效果呢？

问答使用alpaca，不要用llama
