### ISSUE TITLE
请问怎么使用提示达到对话模式的效果呢

### ISSUE THREAD

**Issue by zay95** [ymcui/Chinese-LLaMA-Alpaca#135]
采用的13B f16模型，采用对话模式得到的回答是正常的，但是采用-p 提示参数同样的文本，在非对话模式结果很差

**Comment by zay95** [comment]
谢谢，那请问有 可以不是续写的、对单个问题输入输出的接口吗？

**Comment by ymcui** [comment]
不太清楚，具体建议你去llama.cpp项目里找找有没有相应接口

**Comment by zay95** [comment]
好的，谢谢
