### ISSUE TITLE
为什么增量预训练后的模型的tokenizer比微调后少一个pad呢

### ISSUE THREAD

**Issue by Porraio** [ymcui/Chinese-LLaMA-Alpaca#138]
预训练的时候，数据不是也需要pad吗。用的是哪个pad呢。

**Comment by airaria** [comment]
预训练的时候没有用pad，参考https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm.py

**Comment by Porraio** [comment]
> 预训练的时候没有用pad，参考https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm.py

嗯，懂了，是把整个都packing到一起，切分，就不浪费在pad上了，run_clm里似乎没加入eos_token，请问是否预训练的时候，数据输入是下面这样的呢：`<s>`, `token1`, `token2`,` <\s>`,`<s>`, `new_token1`, `new_token2,` <\s>`一直到最大长度？
