### ISSUE TITLE
mac 什么配置可以跑呢 下面是我的配置

### ISSUE THREAD

**Issue by kong11213613** [ymcui/Chinese-LLaMA-Alpaca#140]
Mac的MacBook Pro
2.8 GHz 四核Intel Core i7
Intel Iris Plus Graphics 655 1536 MB
16 GB 2133 MHz LPDDR3

**Comment by airaria** [comment]
q4量化版本的7B和13B模型是可以跑的；但建议合并与量化代码在更大内存（32G）的机器上执行

**Comment by kong11213613** [comment]
可以用已经合并好的吗

**Comment by airaria** [comment]
> 可以用已经合并好的吗

合并好的非量化版本的权重也至少13G了，16G的内存有点吃力；
所以建议还是要做量化。

**Comment by kong11213613** [comment]
好的，感谢 早点休息
