### ISSUE TITLE
合并为hf格式，继续微调，生成的模型里面无tokenizer_config.json

### ISSUE THREAD

**Issue by lianzhaoy** [ymcui/Chinese-LLaMA-Alpaca#142]
1、将原版llama-13b与chinese-alpaca-lora-13b通过merge_llama_with_chinese_lora_to_hf.py合并为chinese-alpaca-13b后，
2、使用自己的数据继续微调，生成lora
3、生成的lora里面并没有tokenizer_config.json，导致将chinese-alpaca-13b与生成的lora经过merge_llama_with_chinese_lora.py生成.pth文件时报错

这是什么原因呢？

**Comment by airaria** [comment]
没太明白你的意思。
Transformers在默认配置下保存lora时是不保存tokenizer相关文件的；如果是因为缺少tokenizer_config.json，直接从发布的lora包里复制一份即可。

**Comment by lianzhaoy** [comment]
我从发布的lora里面复制试一下  感谢！

**Comment by yuanzhiyong1999** [comment]
> 
您好，我合并之后想继续微调，我用Transformers库中的LlamaForCausalLM.from_pretrained方法加载的时候，提醒我没有config.json，请问您是怎么解决的呢？还是说不用Transformers的库，用其他代码进行微调呢？
