### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by ttzHome** [ymcui/Chinese-LLaMA-Alpaca#143]
用命令：
!python merge_llama_with_chinese_lora_to_hf.py \
    --base_model '/model/llama-7b-hf' \
    --lora_model '/model/chinese-alpaca-lora-7b' \
    --output_dir '/model/merge-7b-hf'
成功合并
!python merge_llama_with_chinese_lora_to_hf.py \
    --base_model '/model/llama-13b-hf' \
    --lora_model '/model/chinese-alpaca-lora-13b' \
    --output_dir '/model/merge-13b-hf'
合并失败，这是为什么呢？

报错：
OSError: Unable to load weights from pytorch checkpoint file for 
'/model/llama-13b-hf/pytorch_model-00000-of-00041.bin' at 
'/model/llama-13b-hf/pytorch_model-00000-of-00041.bin'. If you tried 
to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by airaria** [comment]
因为报错和llama-13b-hf权重有关，是不是原版llama转成hf格式后的文件有问题？或者内存不足？

**Comment by ttzHome** [comment]
> 因为报错和llama-13b-hf权重有关，是不是原版llama转成hf格式后的文件有问题？或者内存不足？

我知道啦，模型传错了，我把这个issue删了，感谢
