### ISSUE TITLE
ValueError when using Transformers

### ISSUE THREAD

**Issue by Zalberth** [ymcui/Chinese-LLaMA-Alpaca#148]
In MacOS 64GB M2Max, deployed with Transformers, when I first input the content and click return, error occured like this:
```
Loading checkpoint shards: 100%|
Vocab of the base model: 49954
Vocab of the tokenizer: 49954
Input:1
Traceback (most recent call last):
  File "/Users/zha/Desktop/my_ai_lab/Chinese-LLaMA-Alpaca-main/scripts/inference_hf.py", line 104, in <module>
    generation_output = model.generate(
  File "/Users/zh/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/zh/Desktop/my_ai_lab/transformers/src/transformers/generation/utils.py", line 1231, in generate
    self._validate_model_kwargs(model_kwargs.copy())
  File "/Users/zh/Desktop/my_ai_lab/transformers/src/transformers/generation/utils.py", line 1109, in _validate_model_kwargs
    raise ValueError(
ValueError: The following `model_kwargs` are not used by the model: ['repeat_penalty'] (note: typos in the generate arguments will also show up in this list)
```

**Comment by airaria** [comment]
> In MacOS 64GB M2Max, deployed with Transformers, when I first input the content and click return, error occured like this:
> 
> ```
> Loading checkpoint shards: 100%|
> Vocab of the base model: 49954
> Vocab of the tokenizer: 49954
> Input:1
> Traceback (most recent call last):
>   File "/Users/zha/Desktop/my_ai_lab/Chinese-LLaMA-Alpaca-main/scripts/inference_hf.py", line 104, in <module>
>     generation_output = model.generate(
>   File "/Users/zh/anaconda3/envs/chatglm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/Users/zh/Desktop/my_ai_lab/transformers/src/transformers/generation/utils.py", line 1231, in generate
>     self._validate_model_kwargs(model_kwargs.copy())
>   File "/Users/zh/Desktop/my_ai_lab/transformers/src/transformers/generation/utils.py", line 1109, in _validate_model_kwargs
>     raise ValueError(
> ValueError: The following `model_kwargs` are not used by the model: ['repeat_penalty'] (note: typos in the generate arguments will also show up in this list)
> ```

The bug has been fixed. Please pull the newest code

**Comment by Zalberth** [comment]
Thanks, new commit works.
