### ISSUE TITLE
OSError:  does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by yyqin1991** [ymcui/Chinese-LLaMA-Alpaca#149]
合并模型生成的alpaca-combined 内没有config.json文件

**Comment by ymcui** [comment]
再提供一些详细信息吧，你是运行哪个脚本出现的错误？提供一下相对完整的错误log（或者后几十行）

**Comment by caigaojiang** [comment]
> 再提供一些详细信息吧，你是运行哪个脚本出现的错误？提供一下相对完整的错误log（或者后几十行）。转成HuggingFace格式的会生成config.json。

我也是，使用Transformers推理，在执行这一个步骤：CUDA_VISIBLE_DEVICES={device_id} python scripts/inference_hf.py \
    --base_model path_to_merged_llama_or_alpaca_hf_dir \
    --with_prompt \
    --interactive

得到如下报错

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /ossfs/workspace/Chinese-LLaMA-Alpaca/scripts/inference_hf.py:56 in <module>                     │
│                                                                                                  │
│    53 │   │   │   args.tokenizer_path = args.base_model                                          │
│    54 │   tokenizer = LlamaTokenizer.from_pretrained(args.tokenizer_path)                        │
│    55 │                                                                                          │
│ ❱  56 │   base_model = LlamaForCausalLM.from_pretrained(                                         │
│    57 │   │   args.base_model,                                                                   │
│    58 │   │   load_in_8bit=False,                                                                │
│    59 │   │   torch_dtype=load_type,                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py:2269 in from_pretrained    │
│                                                                                                  │
│   2266 │   │   # Load config if we don't provide a configuration                                 │
│   2267 │   │   if not isinstance(config, PretrainedConfig):                                      │
│   2268 │   │   │   config_path = config if config is not None else pretrained_model_name_or_pat  │
│ ❱ 2269 │   │   │   config, model_kwargs = cls.config_class.from_pretrained(                      │
│   2270 │   │   │   │   config_path,                                                              │
│   2271 │   │   │   │   cache_dir=cache_dir,                                                      │
│   2272 │   │   │   │   return_unused_kwargs=True,                                                │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py:546 in                │
│ from_pretrained                                                                                  │
│                                                                                                  │
│   543 │   │   assert config.output_attentions == True                                            │
│   544 │   │   assert unused_kwargs == {"foo": False}                                             │
│   545 │   │   ```"""                                                                             │
│ ❱ 546 │   │   config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwarg   │
│   547 │   │   if "model_type" in config_dict and hasattr(cls, "model_type") and config_dict["m   │
│   548 │   │   │   logger.warning(                                                                │
│   549 │   │   │   │   f"You are using a model of type {config_dict['model_type']} to instantia   │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py:573 in                │
│ get_config_dict                                                                                  │
│                                                                                                  │
│   570 │   │   """                                                                                │
│   571 │   │   original_kwargs = copy.deepcopy(kwargs)                                            │
│   572 │   │   # Get config dict associated with the base config file                             │
│ ❱ 573 │   │   config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwar   │
│   574 │   │   if "_commit_hash" in config_dict:                                                  │
│   575 │   │   │   original_kwargs["_commit_hash"] = config_dict["_commit_hash"]                  │
│   576                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py:628 in                │
│ _get_config_dict                                                                                 │
│                                                                                                  │
│   625 │   │   │                                                                                  │
│   626 │   │   │   try:                                                                           │
│   627 │   │   │   │   # Load from local folder or from cache or download from model Hub and ca   │
│ ❱ 628 │   │   │   │   resolved_config_file = cached_file(                                        │
│   629 │   │   │   │   │   pretrained_model_name_or_path,                                         │
│   630 │   │   │   │   │   configuration_file,                                                    │
│   631 │   │   │   │   │   cache_dir=cache_dir,                                                   │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/transformers/utils/hub.py:380 in cached_file              │
│                                                                                                  │
│    377 │   │   resolved_file = os.path.join(os.path.join(path_or_repo_id, subfolder), filename)  │
│    378 │   │   if not os.path.isfile(resolved_file):                                             │
│    379 │   │   │   if _raise_exceptions_for_missing_entries:                                     │
│ ❱  380 │   │   │   │   raise EnvironmentError(                                                   │
│    381 │   │   │   │   │   f"{path_or_repo_id} does not appear to have a file named {full_filen  │
│    382 │   │   │   │   │   f"'https://huggingface.co/{path_or_repo_id}/{revision}' for availabl  │
│    383 │   │   │   │   )                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: merge_model does not appear to have a file named config.json. Checkout 'https://huggingface.co/merge_model/None' for available
files.

**Comment by ymcui** [comment]
> > 再提供一些详细信息吧，你是运行哪个脚本出现的错误？提供一下相对完整的错误log（或者后几十行）。转成HuggingFace格式的会生成config.json。
> 
> 
> 
> 我也是，使用Transformers推理，在执行这一个步骤：CUDA_VISIBLE_DEVICES={device_id} python scripts/inference_hf.py \
> 
>     --base_model path_to_merged_llama_or_alpaca_hf_dir \
> 
>     --with_prompt \
> 
>     --interactive
> 
> 
> 
> 得到如下报错
> 
> 
> 
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> 
> │ /ossfs/workspace/Chinese-LLaMA-Alpaca/scripts/inference_hf.py:56 in <module>                     │
> 
> │                                                                                                  │
> 
> │    53 │   │   │   args.tokenizer_path = args.base_model                                          │
> 
> │    54 │   tokenizer = LlamaTokenizer.from_pretrained(args.tokenizer_path)                        │
> 
> │    55 │                                                                                          │
> 
> │ ❱  56 │   base_model = LlamaForCausalLM.from_pretrained(                                         │
> 
> │    57 │   │   args.base_model,                                                                   │
> 
> │    58 │   │   load_in_8bit=False,                                                                │
> 
> │    59 │   │   torch_dtype=load_type,                                                             │
> 
> │                                                                                                  │
> 
> │ /opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py:2269 in from_pretrained    │
> 
> │                                                                                                  │
> 
> │   2266 │   │   # Load config if we don't provide a configuration                                 │
> 
> │   2267 │   │   if not isinstance(config, PretrainedConfig):                                      │
> 
> │   2268 │   │   │   config_path = config if config is not None else pretrained_model_name_or_pat  │
> 
> │ ❱ 2269 │   │   │   config, model_kwargs = cls.config_class.from_pretrained(                      │
> 
> │   2270 │   │   │   │   config_path,                                                              │
> 
> │   2271 │   │   │   │   cache_dir=cache_dir,                                                      │
> 
> │   2272 │   │   │   │   return_unused_kwargs=True,                                                │
> 
> │                                                                                                  │
> 
> │ /opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py:546 in                │
> 
> │ from_pretrained                                                                                  │
> 
> │                                                                                                  │
> 
> │   543 │   │   assert config.output_attentions == True                                            │
> 
> │   544 │   │   assert unused_kwargs == {"foo": False}                                             │
> 
> │   545 │   │   ```"""                                                                             │
> 
> │ ❱ 546 │   │   config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwarg   │
> 
> │   547 │   │   if "model_type" in config_dict and hasattr(cls, "model_type") and config_dict["m   │
> 
> │   548 │   │   │   logger.warning(                                                                │
> 
> │   549 │   │   │   │   f"You are using a model of type {config_dict['model_type']} to instantia   │
> 
> │                                                                                                  │
> 
> │ /opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py:573 in                │
> 
> │ get_config_dict                                                                                  │
> 
> │                                                                                                  │
> 
> │   570 │   │   """                                                                                │
> 
> │   571 │   │   original_kwargs = copy.deepcopy(kwargs)                                            │
> 
> │   572 │   │   # Get config dict associated with the base config file                             │
> 
> │ ❱ 573 │   │   config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwar   │
> 
> │   574 │   │   if "_commit_hash" in config_dict:                                                  │
> 
> │   575 │   │   │   original_kwargs["_commit_hash"] = config_dict["_commit_hash"]                  │
> 
> │   576                                                                                            │
> 
> │                                                                                                  │
> 
> │ /opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py:628 in                │
> 
> │ _get_config_dict                                                                                 │
> 
> │                                                                                                  │
> 
> │   625 │   │   │                                                                                  │
> 
> │   626 │   │   │   try:                                                                           │
> 
> │   627 │   │   │   │   # Load from local folder or from cache or download from model Hub and ca   │
> 
> │ ❱ 628 │   │   │   │   resolved_config_file = cached_file(                                        │
> 
> │   629 │   │   │   │   │   pretrained_model_name_or_path,                                         │
> 
> │   630 │   │   │   │   │   configuration_file,                                                    │
> 
> │   631 │   │   │   │   │   cache_dir=cache_dir,                                                   │
> 
> │                                                                                                  │
> 
> │ /opt/conda/lib/python3.8/site-packages/transformers/utils/hub.py:380 in cached_file              │
> 
> │                                                                                                  │
> 
> │    377 │   │   resolved_file = os.path.join(os.path.join(path_or_repo_id, subfolder), filename)  │
> 
> │    378 │   │   if not os.path.isfile(resolved_file):                                             │
> 
> │    379 │   │   │   if _raise_exceptions_for_missing_entries:                                     │
> 
> │ ❱  380 │   │   │   │   raise EnvironmentError(                                                   │
> 
> │    381 │   │   │   │   │   f"{path_or_repo_id} does not appear to have a file named {full_filen  │
> 
> │    382 │   │   │   │   │   f"'https://huggingface.co/{path_or_repo_id}/{revision}' for availabl  │
> 
> │    383 │   │   │   │   )                                                                         │
> 
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> 
> OSError: merge_model does not appear to have a file named config.json. Checkout 'https://huggingface.co/merge_model/None' for available
> 
> files.

--base_model 指向灯目录下有什么文件？方便的话ls之后发一下

**Comment by caigaojiang** [comment]
> > > 再提供一些详细信息吧，你是运行哪个脚本出现的错误？提供一下相对完整的错误log（或者后几十行）。转成HuggingFace格式的会生成config.json。
> > 
> > 
> > 我也是，使用Transformers推理，在执行这一个步骤：CUDA_VISIBLE_DEVICES={device_id} python scripts/inference_hf.py \
> > ```
> > --base_model path_to_merged_llama_or_alpaca_hf_dir \
> > 
> > --with_prompt \
> > 
> > --interactive
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 得到如下报错
> > OSError: merge_model does not appear to have a file named config.json. Checkout 'https://huggingface.co/merge_model/None' for available
> > files.
> 
> --base_model 指向的目录下有什么文件？方便的话ls之后发一下

您好，base model文件夹有如下文件：

consolidated.00.pth 
params.json  
special_tokens_map.json  
tokenizer_config.json  
tokenizer.model

**Comment by ymcui** [comment]
> > > > 再提供一些详细信息吧，你是运行哪个脚本出现的错误？提供一下相对完整的错误log（或者后几十行）。转成HuggingFace格式的会生成config.json。
> > > 
> > > 
> > > 我也是，使用Transformers推理，在执行这一个步骤：CUDA_VISIBLE_DEVICES={device_id} python scripts/inference_hf.py \
> > > ```
> > > --base_model path_to_merged_llama_or_alpaca_hf_dir \
> > > 
> > > --with_prompt \
> > > 
> > > --interactive
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 得到如下报错
> > > OSError: merge_model does not appear to have a file named config.json. Checkout 'https://huggingface.co/merge_model/None' for available
> > > files.
> > 
> > 
> > --base_model 指向的目录下有什么文件？方便的话ls之后发一下
> 
> 您好，base model文件夹有如下文件：
> 
> consolidated.00.pth params.json special_tokens_map.json tokenizer_config.json tokenizer.model

😂 这些文件是PyTorch（`.pth`格式的），是不能被HuggingFace-transformers加载的。你需要把这个文件转成HuggingFace格式的才能继续使用。
- 具体可以参考[这一步](https://github.com/ymcui/Chinese-LLaMA-Alpaca#step-1-将原版llama模型转换为hf格式)进行转换
- 后续如果只需要用HuggingFace-transformers加载的话，可以使用`merge_llama_with_chinese_lora_to_hf.py`进行转换，而不是`merge_llama_with_chinese_lora.py`。

**Comment by JINGJING0-0** [comment]
可以把 hf_dir 里面的文件复制粘贴到merged后的文件夹里

**Comment by caigaojiang** [comment]
> > > > > 再提供一些详细信息吧，你是运行哪个脚本出现的错误？提供一下相对完整的错误log（或者后几十行）。转成HuggingFace格式的会生成config.json。
> > > > 
> > > > 
> > > > 我也是，使用Transformers推理，在执行这一个步骤：CUDA_VISIBLE_DEVICES={device_id} python scripts/inference_hf.py \
> > > > ```
> > > > --base_model path_to_merged_llama_or_alpaca_hf_dir \
> > > > 
> > > > --with_prompt \
> > > > 
> > > > --interactive
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 得到如下报错
> > > > OSError: merge_model does not appear to have a file named config.json. Checkout 'https://huggingface.co/merge_model/None' for available
> > > > files.
> > > 
> > > 
> > > --base_model 指向的目录下有什么文件？方便的话ls之后发一下
> > 
> > 
> > 您好，base model文件夹有如下文件：
> > consolidated.00.pth params.json special_tokens_map.json tokenizer_config.json tokenizer.model
> 
> 😂 这些文件是PyTorch（`.pth`格式的），是不能被HuggingFace-transformers加载的。你需要把这个文件转成HuggingFace格式的才能继续使用。
> 
> * 具体可以参考[这一步](https://github.com/ymcui/Chinese-LLaMA-Alpaca#step-1-%E5%B0%86%E5%8E%9F%E7%89%88llama%E6%A8%A1%E5%9E%8B%E8%BD%AC%E6%8D%A2%E4%B8%BAhf%E6%A0%BC%E5%BC%8F)进行转换
> * 后续如果只需要用HuggingFace-transformers加载的话，可以使用`merge_llama_with_chinese_lora_to_hf.py`进行转换，而不是`merge_llama_with_chinese_lora.py`。


问题: 
加载后input输入hello 尝试交互，但是产生报错。

描述: 
我按照您的方式重新合并成了huggingface格式的，加载后显示：
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.27s/it]
Vocab of the base model: 49954
Vocab of the tokenizer: 49954
Input: Hello

报错信息: 
/opt/conda/lib/python3.8/site-packages/transformers/generation/utils.py:1219: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /ossfs/workspace/Chinese-LLaMA-Alpaca/scripts/inference_hf.py:104 in <module>                    │
│                                                                                                  │
│   101 │   │   │   │   else:                                                                      │
│   102 │   │   │   │   │   input_text = raw_input_text                                            │
│   103 │   │   │   │   inputs = tokenizer(input_text,return_tensors="pt")  #add_special_tokens=   │
│ ❱ 104 │   │   │   │   generation_output = model.generate(                                        │
│   105 │   │   │   │   │   input_ids = inputs["input_ids"].to(device),                            │
│   106 │   │   │   │   │   attention_mask = inputs['attention_mask'].to(device),                  │
│   107 │   │   │   │   │   eos_token_id=tokenizer.eos_token_id,                                   │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/torch/utils/_contextlib.py:115 in decorate_context        │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/transformers/generation/utils.py:1231 in generate         │
│                                                                                                  │
│   1228 │   │   generation_config = copy.deepcopy(generation_config)                              │
│   1229 │   │   model_kwargs = generation_config.update(**kwargs)  # All unused kwargs must be m  │
│   1230 │   │   generation_config.validate()                                                      │
│ ❱ 1231 │   │   self._validate_model_kwargs(model_kwargs.copy())                                  │
│   1232 │   │                                                                                     │
│   1233 │   │   # 2. Set generation parameters if not already defined                             │
│   1234 │   │   logits_processor = logits_processor if logits_processor is not None else LogitsP  │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/transformers/generation/utils.py:1109 in                  │
│ _validate_model_kwargs                                                                           │
│                                                                                                  │
│   1106 │   │   │   │   unused_model_args.append(key)                                             │
│   1107 │   │                                                                                     │
│   1108 │   │   if unused_model_args:                                                             │
│ ❱ 1109 │   │   │   raise ValueError(                                                             │
│   1110 │   │   │   │   f"The following `model_kwargs` are not used by the model: {unused_model_  │
│   1111 │   │   │   │   " generate arguments will also show up in this list)"                     │
│   1112 │   │   │   )                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: The following `model_kwargs` are not used by the model: ['repeat_penalty'] (note: typos in the generate arguments will also
show up in this list)

**Comment by airaria** [comment]
> > > > > > 再提供一些详细信息吧，你是运行哪个脚本出现的错误？提供一下相对完整的错误log（或者后几十行）。转成HuggingFace格式的会生成config.json。
> > > > > 
> > > > > 
> > > > > 我也是，使用Transformers推理，在执行这一个步骤：CUDA_VISIBLE_DEVICES={device_id} python scripts/inference_hf.py \
> > > > > ```
> > > > > --base_model path_to_merged_llama_or_alpaca_hf_dir \
> > > > > 
> > > > > --with_prompt \
> > > > > 
> > > > > --interactive
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 得到如下报错
> > > > > OSError: merge_model does not appear to have a file named config.json. Checkout 'https://huggingface.co/merge_model/None' for available
> > > > > files.
> > > > 
> > > > 
> > > > --base_model 指向的目录下有什么文件？方便的话ls之后发一下
> > > 
> > > 
> > > 您好，base model文件夹有如下文件：
> > > consolidated.00.pth params.json special_tokens_map.json tokenizer_config.json tokenizer.model
> > 
> > 
> > 😂 这些文件是PyTorch（`.pth`格式的），是不能被HuggingFace-transformers加载的。你需要把这个文件转成HuggingFace格式的才能继续使用。
> > 
> > * 具体可以参考[这一步](https://github.com/ymcui/Chinese-LLaMA-Alpaca#step-1-%E5%B0%86%E5%8E%9F%E7%89%88llama%E6%A8%A1%E5%9E%8B%E8%BD%AC%E6%8D%A2%E4%B8%BAhf%E6%A0%BC%E5%BC%8F)进行转换
> > * 后续如果只需要用HuggingFace-transformers加载的话，可以使用`merge_llama_with_chinese_lora_to_hf.py`进行转换，而不是`merge_llama_with_chinese_lora.py`。
> 
> 问题: 加载后input输入hello 尝试交互，但是产生报错。
> 
> 描述: 我按照您的方式重新合并成了huggingface格式的，加载后显示： Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00, 2.27s/it] Vocab of the base model: 49954 Vocab of the tokenizer: 49954 Input: Hello
> 
> 报错信息: /opt/conda/lib/python3.8/site-packages/transformers/generation/utils.py:1219: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation) warnings.warn( ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮ │ /ossfs/workspace/Chinese-LLaMA-Alpaca/scripts/inference_hf.py:104 in │ │ │ │ 101 │ │ │ │ else: │ │ 102 │ │ │ │ │ input_text = raw_input_text │ │ 103 │ │ │ │ inputs = tokenizer(input_text,return_tensors="pt") #add_special_tokens= │ │ ❱ 104 │ │ │ │ generation_output = model.generate( │ │ 105 │ │ │ │ │ input_ids = inputs["input_ids"].to(device), │ │ 106 │ │ │ │ │ attention_mask = inputs['attention_mask'].to(device), │ │ 107 │ │ │ │ │ eos_token_id=tokenizer.eos_token_id, │ │ │ │ /opt/conda/lib/python3.8/site-packages/torch/utils/_contextlib.py:115 in decorate_context │ │ │ │ 112 │ @functools.wraps(func) │ │ 113 │ def decorate_context(*args, **kwargs): │ │ 114 │ │ with ctx_factory(): │ │ ❱ 115 │ │ │ return func(*args, **kwargs) │ │ 116 │ │ │ 117 │ return decorate_context │ │ 118 │ │ │ │ /opt/conda/lib/python3.8/site-packages/transformers/generation/utils.py:1231 in generate │ │ │ │ 1228 │ │ generation_config = copy.deepcopy(generation_config) │ │ 1229 │ │ model_kwargs = generation_config.update(**kwargs) # All unused kwargs must be m │ │ 1230 │ │ generation_config.validate() │ │ ❱ 1231 │ │ self._validate_model_kwargs(model_kwargs.copy()) │ │ 1232 │ │ │ │ 1233 │ │ # 2. Set generation parameters if not already defined │ │ 1234 │ │ logits_processor = logits_processor if logits_processor is not None else LogitsP │ │ │ │ /opt/conda/lib/python3.8/site-packages/transformers/generation/utils.py:1109 in │ │ _validate_model_kwargs │ │ │ │ 1106 │ │ │ │ unused_model_args.append(key) │ │ 1107 │ │ │ │ 1108 │ │ if unused_model_args: │ │ ❱ 1109 │ │ │ raise ValueError( │ │ 1110 │ │ │ │ f"The following `model_kwargs` are not used by the model: {unused_model_ │ │ 1111 │ │ │ │ " generate arguments will also show up in this list)" │ │ 1112 │ │ │ ) │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯ ValueError: The following `model_kwargs` are not used by the model: ['repeat_penalty'] (note: typos in the generate arguments will also show up in this list)

这个bug已修复，请下载最新的inference_hf.py

**Comment by Ukimafunado152036** [comment]
您好，我使用mamba预训练模型也出现了类似的报错：
Traceback (most recent call last):
  File "/data/student2/mamba-main/mamba-main/test1.py", line 4, in <module>
    tokenizer=AutoTokenizer.from_pretrained("./state-spaces/mamba-370m-hf")
  File "/home/student2/enter/envs/mamba/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 794, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/home/student2/enter/envs/mamba/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1138, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/student2/enter/envs/mamba/lib/python3.10/site-packages/transformers/configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/student2/enter/envs/mamba/lib/python3.10/site-packages/transformers/configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/student2/enter/envs/mamba/lib/python3.10/site-packages/transformers/utils/hub.py", line 369, in cached_file
    raise EnvironmentError(
OSError: ./state-spaces/mamba-370m-hf does not appear to have a file named config.json. Checkout 'https://huggingface.co/./state-spaces/mamba-370m-hf/tree/None' for available files.

求助各位前辈
