### ISSUE TITLE
词表扩充 + 预训练代码

### ISSUE THREAD

**Issue by ZeyuTeng96** [ymcui/Chinese-LLaMA-Alpaca#150]
您好，请问后续会开源词表扩充和预训练代码嘛？

**Comment by rayguo01** [comment]
同问，可以大体介绍下如何词表扩充么？

**Comment by airaria** [comment]
可以先看这个 #128 
如果还不清楚的话，请耐心等待一下，我们后续会提供一个词表合并的例子供参考

**Comment by airaria** [comment]
预训练代码实在没什么改动，参考Transformers里的[run_clm.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm.py)就行

**Comment by tkone2018** [comment]
@ZeyuTeng96 我也在纠结预训练

**Comment by airaria** [comment]
> > > 预训练代码实在没什么改动，参考Transformers里的[run_clm.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm.py)就行
> > 
> > 
> > 但是如果扩充了词表，那么tokenizer的path肯定是要进行变化，意思是把.bin文件和新的tokenizer_config啥的文件放在一个文件夹下，用model_name_and_path参数传进run_clm.py?
> 
> 我也想问这个问题

是的

**Comment by ZeyuTeng96** [comment]
> > > > 预训练代码实在没什么改动，参考Transformers里的[run_clm.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm.py)就行
> > > 
> > > 
> > > 但是如果扩充了词表，那么tokenizer的path肯定是要进行变化，意思是把.bin文件和新的tokenizer_config啥的文件放在一个文件夹下，用model_name_and_path参数传进run_clm.py?
> > 
> > 
> > 我也想问这个问题
> 
> 是的

大佬，这个问题呢？https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/183 @airaria
