### ISSUE TITLE
合并模型出错：AttributeError: 'LlamaForCausalLM' object has no attribute 'merge_and_unload'

### ISSUE THREAD

**Issue by thiner** [ymcui/Chinese-LLaMA-Alpaca#153]
在没有GPU的服务器上转换模型时出错，错误信息如下：

> AttributeError: 'LlamaForCausalLM' object has no attribute 'merge_and_unload'
运行的命令：
```python
python3 scripts/merge_llama_with_chinese_lora.py \
--base_model decapoda-research/llama-7b-hf \  #这是从HF上下载的权重文件
--lora_model ziqingyang/chinese-alpaca-lora-7b
```
这是什么原因导致的？

**Comment by controZheng** [comment]
> 在没有GPU的服务器上转换模型时出错，错误信息如下：
> 
> > AttributeError: 'LlamaForCausalLM' object has no attribute 'merge_and_unload'
> > 运行的命令：
> 
> ```python
> python3 scripts/merge_llama_with_chinese_lora.py \
> --base_model decapoda-research/llama-7b-hf \  #这是从HF上下载的权重文件
> --lora_model ziqingyang/chinese-alpaca-lora-7b
> ```
> 
> 这是什么原因导致的？

使用最新版本的transformers

**Comment by thiner** [comment]
我使用
`pip install git+https://github.com/huggingface/transformers`
安装的最新版transformer。但还是同样的错误。

**Comment by airaria** [comment]
peft版本多少？

**Comment by thiner** [comment]
peft Version: 0.3.0.dev0

**Comment by niupi21** [comment]
是peft Version: 0.3.0.dev0的原因，我也遇到了。卸载，安装0.2.0解决。
pip uninstall peft
pip install peft==0.2.0

**Comment by thiner** [comment]
> 是peft Version: 0.3.0.dev0的原因，我也遇到了。卸载，安装0.2.0解决。 pip uninstall peft pip install peft==0.2.0 看了项目代码，作者专门写peft 版本>0.2.0调用'merge_and_unload'，然鹅，Version: 0.3.0.dev0中没有这个方法。

果然，peft降级到0.2.0就好了。多谢大侠相助！

**Comment by huangxd-** [comment]
pip install git+https://github.com/huggingface/peft.git
更新到最新报包

**Comment by yangp725** [comment]
> 

我降到peft=0.2.0依然不行，请问你torch、transformers、peft分别是什么版本呀

**Comment by yzy-jumphigh** [comment]
seems merge_and_upload() is removed for LlamaForCausalLM after peft0.2

Intead, the PeftModel.from_pretrained did the merge already, no needs to call merge_and_upload() anymore.

**Comment by CHNRyan** [comment]
我将peft降为0.2.0并没有解决问题，相反，我将其升至了最高版本（0.6.2），解决了问题
