### ISSUE TITLE
LLaMA is now in HuggingFace's main branch.\nPlease reinstall it: pip uninstall transformers && pip install git+https://github.com/huggingface/transformers.git

### ISSUE THREAD

**Issue by controZheng** [ymcui/Chinese-LLaMA-Alpaca#154]
merge_llama_with_chinese_lora_to_hf里面 assert (
    "LlamaTokenizer" in transformers._import_structure["models.llama"]
), "LLaMA is now in HuggingFace's main branch.\nPlease reinstall it: pip uninstall transformers && pip install git+https://github.com/huggingface/transformers.git"可以去掉吗  我安装最新的transformers也会报这个错 但是去掉就能转换了

**Comment by ymcui** [comment]
感谢告知，稍后我们更新一下脚本。

**Comment by airaria** [comment]
> merge_llama_with_chinese_lora_to_hf里面 assert (
> "LlamaTokenizer" in transformers._import_structure["models.llama"]
> ), "LLaMA is now in HuggingFace's main branch.\nPlease reinstall it: pip uninstall transformers && pip install git+[https://github.com/huggingface/transformers.git"可以去掉吗](https://github.com/huggingface/transformers.git%22%E5%8F%AF%E4%BB%A5%E5%8E%BB%E6%8E%89%E5%90%97) 我安装最新的transformers也会报这个错 但是去掉就能转换了

我安装了最新的Transformers，但这个assert并不会报错啊
