### ISSUE TITLE
将原版LLaMA模型转换为HuggingFace格式

### ISSUE THREAD

**Issue by yyqin1991** [ymcui/Chinese-LLaMA-Alpaca#155]
将原版LLaMA模型转换为HuggingFace格式.如果原版LLaMA模型权限还在审批，能够用decapoda-research/llama-7b-hf替代？

**Comment by ymcui** [comment]
见https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/125

**Comment by thiner** [comment]
可以的，我刚刚这么做成功了。 #153
