### ISSUE TITLE
使用text-generation-webui搭建界面，回答内容有点混乱

### ISSUE THREAD

**Issue by yyqin1991** [ymcui/Chinese-LLaMA-Alpaca#156]
# 将HuggingFace格式的llama-7B模型文件放到models文件夹下
ls models/llama-7b-hf
pytorch_model-00001-of-00002.bin pytorch_model-00002-of-00002.bin config.json pytorch_model.bin.index.json generation_config.json

在这一步的时候，由于没有HuggingFace格式的llama-7B模型文件，将原版LLaMA模型（HF格式）扩充中文词表，合并LoRA权重生成的全量模型替代了，
![image](https://user-images.githubusercontent.com/10411323/232001167-f78a9265-be87-44d3-a8ab-1f7de5343dcb.png)
输出结果有点混乱

**Comment by iMountTai** [comment]
您好，首先不建议使用chinese-llama做推理，因为没有经过指令微调；其次，单句话的生成推理，需加prompt，如：
```
below is an instruction rthat destribes a task.
write a response that appropriately conpletes the request.
### Instruction:
我得了流感，请帮我写一封请假条
### Response:

```
供参考~
