### ISSUE TITLE
使用text-generation-webui运行13B时出错

### ISSUE THREAD

**Issue by Caishy** [ymcui/Chinese-LLaMA-Alpaca#157]
执行如下指令
```python
python server.py --model llama-13b-hf --lora chinese-alpaca-lora-13b --listen-host 192.168.0.91 --cpu
``` 

运行后报如下错误：
```python
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
bin /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cpu.so
/usr/local/lib/python3.8/dist-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading llama-13b-hf...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████| 41/41 [01:23<00:00,  2.04s/it]
Loaded the model in 84.41 seconds.
Adding the LoRA chinese-alpaca-lora-13b to the model...
Traceback (most recent call last):
  File "server.py", line 473, in <module>
    add_lora_to_model(shared.args.lora)
  File "/home/text-generation-webui/modules/LoRA.py", line 29, in add_lora_to_model
    shared.model = PeftModel.from_pretrained(shared.model, Path(f"{shared.args.lora_dir}/{lora_name}"), **params)
  File "/usr/local/lib/python3.8/dist-packages/peft/peft_model.py", line 161, in from_pretrained
    model = set_peft_model_state_dict(model, adapters_weights)
  File "/usr/local/lib/python3.8/dist-packages/peft/utils/save_and_load.py", line 74, in set_peft_model_state_dict
    model.load_state_dict(peft_model_state_dict, strict=False)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
        size mismatch for base_model.model.model.embed_tokens.weight: copying a param with shape torch.Size([49954, 5120]) from checkpoint, the shape in current model is torch.Size([32000, 5120]).
        size mismatch for base_model.model.lm_head.weight: copying a param with shape torch.Size([49954, 5120]) from checkpoint, the shape in current model is torch.Size([32000, 5120]).
```

**Comment by iMountTai** [comment]
有复制lora的tokenizer到llama-13b-hf文件夹下吗？建议严格按照[使用text-generation-webui搭建界面](https://github.com/ymcui/Chinese-LLaMA-Alpaca#%E4%BD%BF%E7%94%A8text-generation-webui%E6%90%AD%E5%BB%BA%E7%95%8C%E9%9D%A2)进行部署

**Comment by xpeng** [comment]
我也遇到错误，在按部署文档复制了相关文件后，执行：
`python server.py --listen --model decapoda-research_llama-13b-hf --lora chinese_llama_lora_13b`

加载模型正常，但是在输入后，generate的时候报错：
```
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Loading decapoda-research_llama-13b-hf...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 41/41 [00:25<00:00,  1.62it/s]
Loaded the model in 26.99 seconds.
Adding the LoRA chinese_llama_lora_13b to the model...
Running on local URL:  http://0.0.0.0:30000

To create a public link, set `share=True` in `launch()`.
/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py:1219: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
Traceback (most recent call last):
  File "/mnt/data/llm/text-generation-webui/modules/callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/mnt/data/llm/text-generation-webui/modules/text_generation.py", line 245, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/peft/peft_model.py", line 580, in generate
    return self.base_model.generate(**kwargs)
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
    outputs = self(
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/peft/tuners/lora.py", line 512, in forward
    output = self.lora_B(self.lora_A(self.lora_dropout(x))).to(expected_dtype) * self.scaling
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Float but found Half
Output generated in 1.28 seconds (0.00 tokens/s, 0 tokens, context 2, seed 1666874107)
```

**Comment by airaria** [comment]
> 我也遇到错误，在按部署文档复制了相关文件后，执行： `python server.py --listen --model decapoda-research_llama-13b-hf --lora chinese_llama_lora_13b`
> 
> 加载模型正常，但是在输入后，generate的时候报错：
> 
> ```
> CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
> CUDA SETUP: Highest compute capability among GPUs detected: 8.6
> CUDA SETUP: Detected CUDA version 117
> CUDA SETUP: Loading binary /home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
> Loading decapoda-research_llama-13b-hf...
> Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 41/41 [00:25<00:00,  1.62it/s]
> Loaded the model in 26.99 seconds.
> Adding the LoRA chinese_llama_lora_13b to the model...
> Running on local URL:  http://0.0.0.0:30000
> 
> To create a public link, set `share=True` in `launch()`.
> /home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py:1219: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
>   warnings.warn(
> Traceback (most recent call last):
>   File "/mnt/data/llm/text-generation-webui/modules/callbacks.py", line 66, in gentask
>     ret = self.mfunc(callback=_callback, **self.kwargs)
>   File "/mnt/data/llm/text-generation-webui/modules/text_generation.py", line 245, in generate_with_callback
>     shared.model.generate(**kwargs)
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/peft/peft_model.py", line 580, in generate
>     return self.base_model.generate(**kwargs)
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
>     return self.sample(
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2524, in sample
>     outputs = self(
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
>     output = old_forward(*args, **kwargs)
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
>     outputs = self.model(
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
>     layer_outputs = decoder_layer(
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
>     hidden_states, self_attn_weights, present_key_value = self.self_attn(
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 196, in forward
>     query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/peft/tuners/lora.py", line 512, in forward
>     output = self.lora_B(self.lora_A(self.lora_dropout(x))).to(expected_dtype) * self.scaling
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/yulei/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
>     return F.linear(input, self.weight, self.bias)
> RuntimeError: expected scalar type Float but found Half
> Output generated in 1.28 seconds (0.00 tokens/s, 0 tokens, context 2, seed 1666874107)
> ```
> 
> 另外，测试了CPU运行的情况，由于CPU浮点精度都是float32，所以就正常的。 `python server.py --listen --model decapoda-research_llama-13b-hf --lora chinese_llama_lora_13b --cpu`

这个错误和本issue不相关，如果还未解决的话可以再开一个issue讨论。

这个issue先关了。
