### ISSUE TITLE
转onnx

### ISSUE THREAD

**Issue by minghsuanwu** [ymcui/Chinese-LLaMA-Alpaca#158]
请问一下现在有什么办法把 llama 转onnx 呢

**Comment by ymcui** [comment]
不太清楚。用本项目提供的转换脚本转成pytorch格式或者huggingface之后其实和原版LLaMA就没有什么区别了（除了词表和tokenizer不一样）。建议你去查找一下原版LLaMA是否有类似的脚本进行转换。

**Comment by CUGfred** [comment]
没有使用这个工程的模型，但是可以使用optimum-cli转pth到onnx，你可以试一下

**Comment by CUGfred** [comment]
没有使用这个工程的模型，但是可以使用optimum-cli转pth到onnx，你可以试一下https://huggingface.co/nenkoru/llama-7b-onnx-merged-fp16
