### ISSUE TITLE
希望能提供30B的参数下载

### ISSUE THREAD

**Issue by forex24** [ymcui/Chinese-LLaMA-Alpaca#163]
基础模型：
- [x] LLaMA
- [x] Alpaca

问题类型：
- [x] 下载问题

### 详细描述问题

30B模型经过int4量化后可以在24G消费级显卡运行，毕竟模型越大性能越好，所以希望能提供30B模型的参数下载，谢谢

**Comment by ymcui** [comment]
感谢关注，在计划中。
