### ISSUE TITLE
7B模型回答效果与示例相差较大

### ISSUE THREAD

**Issue by lianggaoquan** [ymcui/Chinese-LLaMA-Alpaca#166]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。*

### 问前必查项目

- [x] 由于相关依赖频繁更新，请确保按照[README.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca)中的相关步骤执行
- [x] 我已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] 我已阅读README中的[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca#faq)，没有找到相似问题和解决方案
- [x] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：
- [ ] LLaMA
- [x] Alpaca

问题类型：
- [ ] 下载问题
- [ ] 模型转换和合并问题
- [ ] 模型推理问题（🤗 transformers）
- [ ] 模型量化和部署问题（llama.cpp、text-generation-webui）
- [x] 效果问题
- [ ] 其他问题

### 详细描述问题

试了很多个问题，发现7B模型的回答普遍很短，而且回答本身的质量不理想，与示例中的效果有较大差距

### 运行截图或log
<img width="936" alt="image" src="https://user-images.githubusercontent.com/26477489/232280241-4af45219-4715-4acb-82de-6580ab4b1e62.png">

（如有必要）请提供文本log或者运行截图，以便我们更好地了解问题详情。

**Comment by airaria** [comment]
测试Alpaca模型请用交互式方式启动llama.cpp，即添加参数-ins，而不是-p，两者的prompt是不一样的。
另外，建议比较效果时，使用README中提供的参数：
```
-ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.3
```
验证模型基本效果无误后，再参数调优已获得更好的效果。

**Comment by lianggaoquan** [comment]
感谢，已解决
