### ISSUE TITLE
有人量化了13B模型可以提供下载链接的吗

### ISSUE THREAD

**Issue by lianggaoquan** [ymcui/Chinese-LLaMA-Alpaca#167]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。*

### 问前必查项目

- [ ] 由于相关依赖频繁更新，请确保按照[README.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca)中的相关步骤执行
- [x] 我已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] 我已阅读README中的[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca#faq)，没有找到相似问题和解决方案
- [ ] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：
- [ ] LLaMA
- [x] Alpaca

问题类型：
- [x] 下载问题
- [ ] 模型转换和合并问题
- [ ] 模型推理问题（🤗 transformers）
- [ ] 模型量化和部署问题（llama.cpp、text-generation-webui）
- [ ] 效果问题
- [ ] 其他问题

### 详细描述问题

因为免费版colab的RAM和磁盘空间对于13B模型的处理远远不够，多次尝试也无法成功，huggingface也没有13B的下载，有人愿意分享下量化好的13B模型吗，感谢~

### 运行截图或log

（如有必要）请提供文本log或者运行截图，以便我们更好地了解问题详情。

**Comment by ymcui** [comment]
尝试过选择TPU也随机不出35G内存的机器吗？

**Comment by lianggaoquan** [comment]
> 

可以随机出35G的，但RAM够了，磁盘空间反而不足（总共仅107G，可用一直在87G左右），无法继续量化。不然就是两个都不够

**Comment by cash-wei-plantern** [comment]
我有，怎么联系...?

**Comment by lianggaoquan** [comment]
> 我有，怎么联系...?

您好，请问可以发送到lianggaoquan@gmail.com吗？感谢～

**Comment by 7801943** [comment]
> 

能麻烦也给我一个吗，谢谢，7801943@qq.com

**Comment by guyuexue** [comment]
> 我有，怎么联系...?


麻烦能发我一份吗, zes4321@163.com  非常感谢

**Comment by Leawnn** [comment]
> 我有，怎么联系...?

能麻烦也发我一份吗，非常感谢。Leawnn@163.com

**Comment by nw3000** [comment]
> 我有，怎么联系...?

能麻烦也共享一份吗，非常感谢。 nannwwang@gmail.com

**Comment by fiona-aa** [comment]
能否也发我一份，非常感谢！！！！fanyin824@163.com

**Comment by fiona-aa** [comment]
> 我有，怎么联系...?

可以发我一份吗，非常感谢！！！！fanyin824@163.com

**Comment by chis2j4** [comment]
能麻烦也共享一份吗，非常感谢。 odw6dkb5@duck.com

**Comment by ehion** [comment]
@cash-wei-plantern 能麻烦也共享一份吗，非常感谢。 8846790@qq.com

**Comment by yunyuyilian** [comment]
> 我有，怎么联系...?
麻烦能共享一份嘛，非常感谢！mitchell0528.gu@gmail.com

**Comment by Hchunyuan** [comment]
> 我有，怎么联系...?

麻烦能发我一份吗,非常感谢, 1787382074@qq.com

**Comment by ycy3675001** [comment]
辛苦能共享一份吗？非常感谢，352089546@qq.com

**Comment by ycy3675001** [comment]
> 我有，怎么联系...?

辛苦能共享一份吗？352089546@qq.com

**Comment by cndeng** [comment]
能麻烦也共享一份吗，非常感谢。 [cndeng@foxmail.com](mailto:cndeng@foxmail.com)

**Comment by qping2018** [comment]
> 我有，怎么联系...?

能麻烦提供一份吗，感谢！ 1513034803@qq.com

**Comment by minlik** [comment]
我上传了一份 https://huggingface.co/minlik/chinese-alpaca-13b-quantized

**Comment by Linzeyin** [comment]
> 我上传了一份 https://huggingface.co/minlik/chinese-alpaca-13b-quantized

好人一生平安🙏

**Comment by biotech7** [comment]
好人一生有福！

**Comment by prettyboyweiwei** [comment]
@minlik 请问这个 13B 是普通版还是 plus 版？

**Comment by minlik** [comment]
> @minlik 请问这个 13B 是普通版还是 plus 版？

普通版
