### ISSUE TITLE
请问交互方式可用，使用text-generation-webui运行时出错，权重张量的形状不匹配怎么解决？

### ISSUE THREAD

**Issue by RichardD22** [ymcui/Chinese-LLaMA-Alpaca#168]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。*

### 问前必查项目

- [x] 由于相关依赖频繁更新，请确保按照[README.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca)中的相关步骤执行
- [x] 我已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] 我已阅读README中的[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca#faq)，没有找到相似问题和解决方案
- [x] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：
- [ ] LLaMA
- [x] Alpaca

问题类型：
- [ ] 下载问题
- [ ] 模型转换和合并问题
- [ ] 模型推理问题（🤗 transformers）
- [x] 模型量化和部署问题（llama.cpp、text-generation-webui）
- [ ] 效果问题
- [ ] 其他问题

### 详细描述问题

请尽量具体地描述您遇到的问题。这将有助于我们更快速地定位问题所在。
交互方式可用，使用text-generation-webui运行时出错，权重张量的形状不匹配怎么解决？

modules/LoRA.py已经修改为：
        shared.model.resize_token_embeddings(len(shared.tokenizer))
        shared.model = PeftModel.from_pretrained(shared.model, Path(f"/opt/work/text-generation-webui/loras/chinese_alpaca_lora_7b"), **params)

### 运行截图或log
交互方式可用
CUDA_VISIBLE_DEVICES=GPU python scripts/inference_hf.py --base_model /opt/work/text-generation-webui/models/llama-7b-hf/ --lora_model /opt/work/text-generation-webui/loras/chinese_alpaca_lora_7b/ --with_prompt --interactive
Loading checkpoint shards: 100%|███████████████████████████████████| 2/2 [00:07<00:00,  3.70s/it]
Vocab of the base model: 32000
Vocab of the tokenizer: 49954
Resize model embeddings to fit tokenizer
loading peft model
Input:hi
Response:  Hello! How can I help you?

webui方式报错
python server.py --model llama-7b-hf --lora chinese-alpaca-lora-7b
Loading llama-7b-hf...
Loading checkpoint shards: 100%|███████████████████████████████████| 2/2 [00:07<00:00,  3.70s/it]
Loaded the model in 17.77 seconds.
Applying the following LoRAs to llama-7b-hf: chinese-alpaca-lora-7b
Traceback (most recent call last):
  File "/opt/work/text-generation-webui/server.py", line 871, in <module>
    add_lora_to_model([shared.args.lora])
  File "/opt/work/text-generation-webui/modules/LoRA.py", line 41, in add_lora_to_model
    shared.model = PeftModel.from_pretrained(shared.model, Path(f"/opt/work/text-generation-webui/loras/chinese_alpaca_lora_7b"), **params)
  File "/home/ubuntu/miniconda3/envs/chatglm/lib/python3.10/site-packages/peft/peft_model.py", line 161, in from_pretrained
    model = set_peft_model_state_dict(model, adapters_weights)
  File "/home/ubuntu/miniconda3/envs/chatglm/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 74, in set_peft_model_state_dict
    model.load_state_dict(peft_model_state_dict, strict=False)
  File "/home/ubuntu/miniconda3/envs/chatglm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
        size mismatch for base_model.model.model.embed_tokens.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([32000, 4096]).
        size mismatch for base_model.model.lm_head.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([32000, 4096]).

（如有必要）请提供文本log或者运行截图，以便我们更好地了解问题详情。

**Comment by iMountTai** [comment]
有使用lora权重的tokenizer替换hf权重的tokenizer吗？

**Comment by RichardD22** [comment]
了解，解决了，谢谢大牛🙏
