### ISSUE TITLE
🔥能否提供训练自定义数据的教程和代码

### ISSUE THREAD

**Issue by yfq512** [ymcui/Chinese-LLaMA-Alpaca#172]
* 感谢作者的分享，可以看到从原始的llama训练得到支持中文的模型，其过程还是比较复杂的，希望可以出个详细的训练教程。
* 此外更希望提供一个教程，可以在你的中文模型基础上，针对某个领域的数据（如医疗、法律等）进行训练，从而得到在这个领域更专业的“专属”模型

**Comment by shiningxy** [comment]
本项目目前的重点似乎放在了进过指令精挑细选的Chinese-Alpaca-7B & 13B模型的推理与部署，辛苦大佬，后续是否有给出指令微调的示例训练代码 :heart: 

文档中给出了基于OpenAI Key生成行业json数据的代码，其逻辑于AgentGPT类似，但数据质量完全依仗gpt3.5的性能。

- [ ] 是否可以复现Common Crawl的逻辑，获取类似于[cMedQA](https://www.cluebenchmarks.com/dataSet_search_modify.html?keywords=cMedQA)行业数据。

- [ ] 并根据QA任务、纠错任务等生成相应的json数据格式。

- [ ] 针对不同格式的数据，设计一个DataLoader，将数据传输给本项目指令精调后的alpaca模型，对模型进行扩展或增强。

**Comment by airaria** [comment]
非常感谢各位的关注。
我们目前的主要精力确实并没有放在领域精调上，不过后续也会做这方面的考虑
此外，我们对领域数据集也并不熟悉，如果有合适的公开领域数据集，也欢迎推荐给我们。我们会考虑以此为例子提供一套精调流程。

**Comment by airaria** [comment]
目前发布了预训练代码，欢迎参考。

**Comment by aimetrics** [comment]
@airaria 您好，指令精调数据里，关于「中英翻译数据」和「pCLUE数据」的采样+规则筛选后的数据可以开放吗？
另外，想咨询了解下选取这两个数据集是出于什么考虑？

谢谢！

**Comment by airaria** [comment]
> @airaria 您好，指令精调数据里，关于「中英翻译数据」和「pCLUE数据」的采样+规则筛选后的数据可以开放吗？ 另外，想咨询了解下选取这两个数据集是出于什么考虑？
> 
> 谢谢！

#104
