### ISSUE TITLE
扩充后的词表，总共有多少条？

### ISSUE THREAD

**Issue by mellivoraPKU** [ymcui/Chinese-LLaMA-Alpaca#173]
扩充后的词表，总共有多少条？

**Comment by ymcui** [comment]
[https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/训练细节#准备工作词表扩充](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/训练细节#准备工作词表扩充)
