### ISSUE TITLE
请问text-generation-webui的方式里第4步怎么修改

### ISSUE THREAD

**Issue by crab4747** [ymcui/Chinese-LLaMA-Alpaca#175]
### 问前必查项目

- [x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

问题类型：

- [x] 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）

### 详细描述问题

哥哥们，这一步具体怎么修改？

![image](https://user-images.githubusercontent.com/57392414/232704570-2ecfb8ad-c8cf-4dcc-b8fb-8f3970709aef.png)

### 运行截图或log

![image](https://user-images.githubusercontent.com/57392414/232704848-aa544a0e-9225-422d-891c-c48b71cf241a.png)

**Comment by iMountTai** [comment]
由于repo在不断更新，所以第四步具体行数有一定的出入，从截图来看，需要修改的地方为第40行

**Comment by zzcgithub** [comment]
同问，在webui里面使用是在 shared.model = PeftModel.from_pretrained(shared.model, Path(f"{shared.args.lora_dir}/{lora_names[0]}"), **params) 前面添加一行shared.model.resize_token_embeddings(len(shared.tokenizer))？

       用transformer-infer的模式是成功的， 用webui就失败了。 求大佬看看～

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/13117136/232794498-32404736-e3ee-4951-9ca9-2223f8f4e25f.png">

**Comment by iMountTai** [comment]
> 同问，在webui里面使用是在 shared.model = PeftModel.from_pretrained(shared.model, Path(f"{shared.args.lora_dir}/{lora_names[0]}"), **params) 前面添加一行shared.model.resize_token_embeddings(len(shared.tokenizer))？
> 
> ```
>    用transformer-infer的模式是成功的， 用webui就失败了。 求大佬看看～
> ```
> 
> <img alt="image" width="1226" src="https://user-images.githubusercontent.com/13117136/232794498-32404736-e3ee-4951-9ca9-2223f8f4e25f.png">

运行的命令及相关依赖的版本麻烦说一下，还有机器型号（mac, linux,windows）

**Comment by crab4747** [comment]
> 由于repo在不断更新，所以第四步具体行数有一定的出入，从截图来看，需要修改的地方为第40行

谢谢哥

**Comment by crab4747** [comment]
> 由于repo在不断更新，所以第四步具体行数有一定的出入，从截图来看，需要修改的地方为第40行

大佬！text-generation-webui的方式我部署成功了，但是在浏览器里，用127.0.0.1:7860能正常打开，换成ip的192.168.x.x:7860就空白，您知道为什么吗？

**Comment by zzcgithub** [comment]
> > 同问，在webui里面使用是在 shared.model = PeftModel.from_pretrained(shared.model, Path(f"{shared.args.lora_dir}/{lora_names[0]}"), **params) 前面添加一行shared.model.resize_token_embeddings(len(shared.tokenizer))？
> > ```
> >    用transformer-infer的模式是成功的， 用webui就失败了。 求大佬看看～
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="image" width="1226" src="https://user-images.githubusercontent.com/13117136/232794498-32404736-e3ee-4951-9ca9-2223f8f4e25f.png">
> 
> 运行的命令及相关依赖的版本麻烦说一下，还有机器型号（mac, linux,windows）

机器：linux
python版本：3.10.9
accelerate                    0.18.0
peft                          0.2.0
sentencepiece                 0.1.98
transformers                  4.28.1
llama-cpp-python              0.1.26
text-generation-webui版本: commitID b0c762ceba040
执行命令：python server.py --model llama-7b-hf --lora chinese-alpaca-lora-7b --verbose --gpu-memory 10 \
--listen-host 0.0.0.0 --listen-port 8555 --share --listen

执行命令后可以正常启动，使用generate报错

**Comment by crab4747** [comment]
> 由于repo在不断更新，所以第四步具体行数有一定的出入，从截图来看，需要修改的地方为第40行

大佬，我部署好了，但是怎么不说中文嘞？用llama.cpp部署的时候回答的是中文。
![image](https://user-images.githubusercontent.com/57392414/232981235-52f662e9-74e3-4990-b0d1-ecd2f9207e87.png)
![961c99c56ed70daffbae860be918607](https://user-images.githubusercontent.com/57392414/232981340-66315f01-4558-4596-90e4-055da33c1d70.png)

**Comment by zzcgithub** [comment]
咋close 这个issue了..

**Comment by crab4747** [comment]
> 咋close 这个issue了..

额，不好意思，我再打开……

**Comment by zzcgithub** [comment]
#178  和这个issue一样

**Comment by iMountTai** [comment]
@zzcgithub 请先使用--cpu参数查看生成内容是否正常

**Comment by zzcgithub** [comment]
--cpu可以。

从其他代码库issue看到的，初步怀疑是Float32没有生效导致的

**Comment by iMountTai** [comment]
如果cpu可以，说明模型本身是没问题的，而且transformers inference在gpu上也是跑通的，可能是webui适配GPU的问题
你可以先用cpu跑合并后的模型，这个速度会快一点

**Comment by leonlee723** [comment]
我无论加不加--cpu启动text-generation-webui都是以下错误，要怎么解决呢？感谢
Traceback (most recent call last):
  File "/home/lile3080/AI/text-generation-webui-main/server.py", line 44, in <module>
    from modules import chat, shared, training, ui
  File "/home/lile3080/AI/text-generation-webui-main/modules/training.py", line 17, in <module>
    from modules.evaluate import calculate_perplexity, generate_markdown_table, save_past_evaluations
  File "/home/lile3080/AI/text-generation-webui-main/modules/evaluate.py", line 13, in <module>
    from server import get_model_specific_settings, update_model_parameters
  File "/home/lile3080/AI/text-generation-webui-main/server.py", line 46, in <module>
    from modules.LoRA import add_lora_to_model
  File "/home/lile3080/AI/text-generation-webui-main/modules/LoRA.py", line 41
    shared.model.resize_token_embeddings(len(shared.tokenizer))
TabError: inconsistent use of tabs and spaces in indentation
