### ISSUE TITLE
35G的RAM就可以转换13B的模型，指的是GPU的内存还是机器的内存？

### ISSUE THREAD

**Issue by oldTomatoCN** [ymcui/Chinese-LLaMA-Alpaca#176]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。提问时删除上面这两行。请只保留符合的选项，删掉其他。*

### 问前必查项目

- [ x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x ] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：

- [ ] LLaMA
- [ x] Alpaca

问题类型：
- [ ] 下载问题
- [x ] 模型转换和合并问题
- [ ] 模型推理问题（🤗 transformers）
- [ ] 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
- [ ] 效果问题
- [ ] 其他问题

### 详细描述问题

*请尽量具体地描述您遇到的问题。这将有助于我们更快速地定位问题所在。*
35G的RAM就可以转换13B的模型，指的是GPU的内存还是机器的内存？

### 运行截图或log

*（如有必要）请提供文本log或者运行截图，以便我们更好地了解问题详情。*

**Comment by iMountTai** [comment]
内存
