### ISSUE TITLE
使用Transformer推理报错RuntimeError: Trying to create tensor with negative dimension -1: [-1, 4096]

### ISSUE THREAD

**Issue by heiyuhao** [ymcui/Chinese-LLaMA-Alpaca#179]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。提问时删除上面这两行。请只保留符合的选项，删掉其他。*

### 问前必查项目

- [x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：

- [ ] LLaMA
- [x ] Alpaca

问题类型：
- [ ] 下载问题
- [ ] 模型转换和合并问题
- [x] 模型推理问题（🤗 transformers）
- [x] 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
- [ ] 效果问题
- [ ] 其他问题

### 详细描述问题

采用合并模型并量化4bit后，用transformer推理，执行报错。
我的模型目录结构如下：

(base) hy@hy-YangTianP880-07ICL:~/codespace/llama.cpp/zh-models/7B$ ll
total 31525808
drwxrwxr-x 2 hy hy        4096  4月 19 10:40 ./
drwxrwxr-x 3 hy hy        4096  4月 19 10:15 ../
-rw-rw-r-- 1 hy hy         101  4月 19 10:05 config.json
-rw-rw-r-- 1 hy hy 13771083975  4月 19 10:05 consolidated.00.pth
-rw-rw-r-- 1 hy hy 13772213056  4月 19 10:20 ggml-model-f16.bin
-rw-rw-r-- 1 hy hy  4305023808  4月 19 10:25 ggml-model-q4_0.bin
-rw-rw-r-- 1 hy hy         101  4月 19 10:05 params.json
-rw-rw-r-- 1 hy hy   433288887  4月 19 10:37 pytorch_model.bin
-rw-rw-r-- 1 hy hy          96  4月 19 10:00 special_tokens_map.json
-rw-rw-r-- 1 hy hy         727  4月 19 10:00 tokenizer_config.json

### 运行截图或log

CUDA_VISIBLE_DEVICES=0 python scripts/inference_hf.py     --base_model /home/hy/codespace/llama.cpp/zh-models/7B    --with_prompt     --interactive

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes
and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/hy/anaconda3/envs/space/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
CUDA SETUP: CUDA runtime path found: /home/hy/anaconda3/envs/space/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/hy/anaconda3/envs/space/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/hy/codespace/Chinese-LLaMA-Alpaca/scripts/inference_hf.py:56 in <module>             │
│                                                                                                  │
│    53 │   │   │   args.tokenizer_path = args.base_model                                          │
│    54 │   tokenizer = LlamaTokenizer.from_pretrained(args.tokenizer_path)                        │
│    55 │                                                                                          │
│ ❱  56 │   base_model = LlamaForCausalLM.from_pretrained(                                         │
│    57 │   │   args.base_model,                                                                   │
│    58 │   │   load_in_8bit=False,                                                                │
│    59 │   │   torch_dtype=load_type,                                                             │
│                                                                                                  │
│ /home/hy/anaconda3/envs/space/lib/python3.10/site-packages/transformers/modeling_utils.py: │
│ 2629 in from_pretrained                                                                          │
│                                                                                                  │
│   2626 │   │   │   init_contexts.append(init_empty_weights())                                    │
│   2627 │   │                                                                                     │
│   2628 │   │   with ContextManagers(init_contexts):                                              │
│ ❱ 2629 │   │   │   model = cls(config, *model_args, **model_kwargs)                              │
│   2630 │   │                                                                                     │
│   2631 │   │   # Check first if we are `from_pt`                                                 │
│   2632 │   │   if use_keep_in_fp32_modules:                                                      │
│                                                                                                  │
│ /home/hy/anaconda3/envs/space/lib/python3.10/site-packages/transformers/models/llama/model │
│ ing_llama.py:614 in __init__                                                                     │
│                                                                                                  │
│   611 class LlamaForCausalLM(LlamaPreTrainedModel):                                              │
│   612 │   def __init__(self, config):                                                            │
│   613 │   │   super().__init__(config)                                                           │
│ ❱ 614 │   │   self.model = LlamaModel(config)                                                    │
│   615 │   │                                                                                      │
│   616 │   │   self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)        │
│   617                                                                                            │
│                                                                                                  │
│ /home/hy/anaconda3/envs/space/lib/python3.10/site-packages/transformers/models/llama/model │
│ ing_llama.py:444 in __init__                                                                     │
│                                                                                                  │
│   441 │   │   self.padding_idx = config.pad_token_id                                             │
│   442 │   │   self.vocab_size = config.vocab_size                                                │
│   443 │   │                                                                                      │
│ ❱ 444 │   │   self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.pad   │
│   445 │   │   self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num   │
│   446 │   │   self.norm = LlamaRMSNorm(config.hidden_size, eps=config.rms_norm_eps)              │
│   447                                                                                            │
│                                                                                                  │
│ /home/hy/anaconda3/envs/space/lib/python3.10/site-packages/torch/nn/modules/sparse.py:141  │
│ in __init__                                                                                      │
│                                                                                                  │
│   138 │   │   self.norm_type = norm_type                                                         │
│   139 │   │   self.scale_grad_by_freq = scale_grad_by_freq                                       │
│   140 │   │   if _weight is None:                                                                │
│ ❱ 141 │   │   │   self.weight = Parameter(torch.empty((num_embeddings, embedding_dim), **facto   │
│   142 │   │   │   self.reset_parameters()                                                        │
│   143 │   │   else:                                                                              │
│   144 │   │   │   assert list(_weight.shape) == [num_embeddings, embedding_dim], \               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Trying to create tensor with negative dimension -1: [-1, 4096]

**Comment by ymcui** [comment]
huggingface无法加载ggml格式文件，不论fp16还是q4的都不可以。
