### ISSUE TITLE
DefaultCPUAllocator: can't allocate memory

### ISSUE THREAD

**Issue by gdchaochao** [ymcui/Chinese-LLaMA-Alpaca#18]
在“合并LoRA权重，生成全量模型权重”这一步里面遇到了上面的问题。但是这里提示的内存需要只是几百MB，就无法分配。比较不解，感觉不太像是资源问题。可以告诉我，你使用的机器或者建议的机器配置吗？
![image](https://user-images.githubusercontent.com/3916495/229067379-787bee11-d168-4cd1-a268-e140052f48eb.png)
另外我尝试改cpu为cuda去做这个事情，结果还是报错：
![image](https://user-images.githubusercontent.com/3916495/229067647-4a788bee-6714-4445-b326-cdb32ace5a25.png)
![image](https://user-images.githubusercontent.com/3916495/229067803-11f93f4c-13b2-4861-983d-bd40e9000e72.png)

**Comment by airaria** [comment]
因为LLaMA的半精度权重就有13GB，所以也至少要有13G的内存。
我这边运行实测，最高占用了15GB内存

**Comment by gdchaochao** [comment]
> 

感谢airaria，确实是内存不足的问题。16GB的机器很可能是跑不起来的，所以看起来内存的话还是32GB或者更高会是保险的。
