### ISSUE TITLE
使用text-generation-webui部署的，怎样让它回答中文呢？

### ISSUE THREAD

**Issue by crab4747** [ymcui/Chinese-LLaMA-Alpaca#180]
### 问前必查项目

- [x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

问题类型：

- [x] 效果问题

### 详细描述问题

使用text-generation-webui部署了，但是回答的没有中文，该怎么办呢？

### 运行截图或log
![image](https://user-images.githubusercontent.com/57392414/232985901-899424ce-66b5-4d14-a3a2-80ee4db871a4.png)

用llama.cbb部署的时候是可以回答中文的：
![961c99c56ed70daffbae860be918607](https://user-images.githubusercontent.com/57392414/232986084-0f9983fa-5a02-4c4a-b7a6-fd2104ece3c8.png)

**Comment by iMountTai** [comment]
建议使用cpu模式直接运行合并后的chinese-alpaca-7b，另外，我这边都是直接回复的中文，不管是generate模式还是chat模式，还请参照我们的教程[使用text generation webui搭建界面](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E4%BD%BF%E7%94%A8text-generation-webui%E6%90%AD%E5%BB%BA%E7%95%8C%E9%9D%A2)对比是否有偏差，谢谢您对本repo的关注。

**Comment by maximaldog** [comment]
我也有同样的问题，直接启动使用GPU，无论如何对话都是英文，但是加上--cpu参数后，使用cpu是正常回复中文的，但是cpu太慢了，在text-generation-webui找不到类似的issue，希望这个问题能解决

**Comment by iMountTai** [comment]
如果cpu可以正常回复中文，说明模型本身是没有问题的，其他加载问题或者参数设置还请到原repo下询问，谢谢~

**Comment by iMountTai** [comment]
> 我也有同样的问题，直接启动使用GPU，无论如何对话都是英文，但是加上--cpu参数后，使用cpu是正常回复中文的，但是cpu太慢了，在text-generation-webui找不到类似的issue，希望这个问题能解决

建议直接加载合并后的模型

**Comment by crab4747** [comment]
。。。我已经放弃这个工具了，我现在用https://github.com/josStorer/selfhostedAI这个项目，它把llama.cpp做成了接口，然后自己写个前端聊天框调fetch接口，效果很不错。

**Comment by iMountTai** [comment]
> 。。。我已经放弃这个工具了，我现在用https://github.com/josStorer/selfhostedAI 这个项目，它把llama.cpp做成了接口，然后自己写个前端聊天框调fetch接口，效果很不错。

不好意思给您带来了不便，webui也是支持llama.cpp的[Using llama.cpp in the web UI](https://github.com/oobabooga/text-generation-webui/wiki/llama.cpp-models#using-llamacpp-in-the-web-ui)

**Comment by crab4747** [comment]
> > 。。。我已经放弃这个工具了，我现在用https://github.com/josStorer/selfhostedAI 这个项目，它把llama.cpp做成了接口，然后自己写个前端聊天框调fetch接口，效果很不错。
> 
> 不好意思给您带来了不便，webui也是支持llama.cpp的[Using llama.cpp in the web UI](https://github.com/oobabooga/text-generation-webui/wiki/llama.cpp-models#using-llamacpp-in-the-web-ui)

这个好！很方便
![image](https://user-images.githubusercontent.com/57392414/233518470-b8ba8532-6fbb-4981-9eeb-96460ddceb21.png)

**Comment by crab4747** [comment]
![image](https://user-images.githubusercontent.com/57392414/233529125-5456f365-b14f-4c50-a976-af3d4315771a.png)
请问这个You的头像能变吗？大红点好难看
