### ISSUE TITLE
如何在中文 Alpaca 模型的基础上，训练自己的 lora 模型呢？

### ISSUE THREAD

**Issue by Lufffya** [ymcui/Chinese-LLaMA-Alpaca#182]

**Comment by ymcui** [comment]
https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/146#issuecomment-1507119602

**Comment by Lufffya** [comment]
@ymcui 目前是还没有开源从原版直接预训练的中文 llama 吗，因为只看到了有LoRA的下载链接

**Comment by airaria** [comment]
> @ymcui 目前是还没有开源从原版直接预训练的中文 llama 吗，因为只看到了有LoRA的下载链接

我们暂时只有利用LoRA预训练的权重，没有全量参数中文预训练的模型。

**Comment by Lufffya** [comment]
@airaria 
![image](https://user-images.githubusercontent.com/49063302/233043827-836554ed-14f5-4ec0-a2fb-15f220d2d009.png)

所以目前这两部的训练都是训练中文的 LoRA 模型吗，没有修改原来 llama 权重

**Comment by Lufffya** [comment]
> 扩充和训练后的embedding和lm head的权重也包括在发布的lora权重里了，所以lora权重才会那么大（～800M）

@airaria 哦哦，所以说你们指的预训练和指令精调都是在LoRA中做的适配咯，并没有对原版的 llama 模型做修改，
而在推理的时候需要代码手动的根据LoRA中的对应模型配置去修改原版 llama embedding 词库的大小吗

**Comment by briup1** [comment]
@airaria 请问你这里提到的lm head是指？ 这部分预训练的代码有计划开源吗？
![image](https://user-images.githubusercontent.com/14970237/233317571-b37e02b1-cbed-423e-9361-c49203cf9e3a.png)
