### ISSUE TITLE
关于使用hf run_clm对llama进行预训练的疑问

### ISSUE THREAD

**Issue by ZeyuTeng96** [ymcui/Chinese-LLaMA-Alpaca#183]
### 问前必查项目

- [x ] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x ] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x ] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：

- [x ] LLaMA

问题类型：
- [x ] 其他问题

### 详细描述问题
大佬好，我这里也想使用hf的run_clm对llama模型进行继续预训练。其中，预训练的无标注文本为.txt的文件，每行都是一个文本或者一个自然段。

但是，run_clm的脚本里会在把每行的文本做tokenize后，进行一个group_text的操作，默认至1024的长度。这样会导致，每行的文本如果不够1024的长度的话，会把下一行的文本和当前的文本进行一个拼接，是这么理解吗？

如果按照这种拼接方式，是不是不太合理啊？我如果每行都是独立的文本，我并不需要根据上一个文本的结束来预测新的文本的开头，这样的预训练是不是不太合理？

还是说我的.txt文件准备错误了，不应该这么准备数据呢？

**Comment by ZeyuTeng96** [comment]
大佬，能帮忙解答下吗 @ymcui @airaria

**Comment by airaria** [comment]
每一行的开头会prepend一个`<s>`起始符，所以是根据上一个文本的结束来预测新的文本的开头起始符
我们也这么做的，感觉问题不大，因为绝大多数位置还是以预测下一个token为主；极少数的地方才是预测新的文本的开头

**Comment by ZeyuTeng96** [comment]
> 

但是run_clm.py的代码里是没有设计‘prepend一个<s>起始符’的操作的，这块的设计是大佬们自己加的吗？ @airaria

**Comment by ZeyuTeng96** [comment]
> > 
> 
> 但是run_clm.py的代码里是没有设计 ‘prepend一个 bos 起始符’ 的操作的，这块的设计是大佬们自己加的吗？ @airaria

**Comment by airaria** [comment]
是由tokenizer自动加的

**Comment by ZeyuTeng96** [comment]
> 是由tokenizer自动加的

```
from transformers import AutoModelForCausalLM, AutoTokenizer

checkpoint = "bigscience/bloomz-7b1-mt"

tokenizer = AutoTokenizer.from_pretrained(checkpoint)

tokenizer(' = Valkyria Chronicles III = \n') 的结果是：
{'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}

tokenizer('<s> = Valkyria Chronicles III = \n</s>')的结果是：
{'input_ids': [1, 564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
```
我感觉tokenizer并没有自动加那

**Comment by ZeyuTeng96** [comment]
> > 是由tokenizer自动加的
> 
> ```
> from transformers import AutoModelForCausalLM, AutoTokenizer
> 
> checkpoint = "bigscience/bloomz-7b1-mt"
> 
> tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> 
> tokenizer(' = Valkyria Chronicles III = \n') 的结果是：
> {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> 
> tokenizer('<s> = Valkyria Chronicles III = \n</s>')的结果是：
> {'input_ids': [1, 564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
> ```
> 
> 我感觉tokenizer并没有自动加那，第一个tokenize的结果就是训练集的输入，请问大佬怎么确认tokenizer有没有prepend bos呢？

**Comment by ZeyuTeng96** [comment]
> 是由tokenizer自动加的

大佬能否加个vx，向您请教下，我的vx id是 zeyuteng

**Comment by ZeyuTeng96** [comment]
大佬，是我这边tokenizer使用错了嘛？ @airaria

**Comment by airaria** [comment]
> > 是由tokenizer自动加的
> 
> ```
> from transformers import AutoModelForCausalLM, AutoTokenizer
> 
> checkpoint = "bigscience/bloomz-7b1-mt"
> 
> tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> 
> tokenizer(' = Valkyria Chronicles III = \n') 的结果是：
> {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> 
> tokenizer('<s> = Valkyria Chronicles III = \n</s>')的结果是：
> {'input_ids': [1, 564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
> ```
> 
> 我感觉tokenizer并没有自动加那，第一个tokenize的结果就是训练集的输入

你这是bloom的tokenizer，不是llama的。
不用预训练模型的toeknzier对special token的处理方式都略有不同。

**Comment by ZeyuTeng96** [comment]
> > > 是由tokenizer自动加的
> > 
> > 
> > ```
> > from transformers import AutoModelForCausalLM, AutoTokenizer
> > 
> > checkpoint = "bigscience/bloomz-7b1-mt"
> > 
> > tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> > 
> > tokenizer(' = Valkyria Chronicles III = \n') 的结果是：
> > {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > 
> > tokenizer('<s> = Valkyria Chronicles III = \n</s>')的结果是：
> > {'input_ids': [1, 564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我感觉tokenizer并没有自动加那，第一个tokenize的结果就是训练集的输入
> 
> 你这是bloom的tokenizer，不是llama的。 不用预训练模型的toeknzier对special token的处理方式都略有不同。

大佬，能否贴一个llama的示例结果，我看看

**Comment by ZeyuTeng96** [comment]
> > > 是由tokenizer自动加的
> > 
> > 
> > ```
> > from transformers import AutoModelForCausalLM, AutoTokenizer
> > 
> > checkpoint = "bigscience/bloomz-7b1-mt"
> > 
> > tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> > 
> > tokenizer(' = Valkyria Chronicles III = \n') 的结果是：
> > {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > 
> > tokenizer('<s> = Valkyria Chronicles III = \n</s>')的结果是：
> > {'input_ids': [1, 564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我感觉tokenizer并没有自动加那，第一个tokenize的结果就是训练集的输入
> 
> 你这是bloom的tokenizer，不是llama的。 不用预训练模型的toeknzier对special token的处理方式都略有不同。

大佬，我这里也测试了一下官方的调用示例，即gpt2和wiki_text的示例，也不存在prepend eos的情况，能否麻烦大佬贴一个llama的示例

**Comment by ZeyuTeng96** [comment]
> > > 是由tokenizer自动加的
> > 
> > 
> > ```
> > from transformers import AutoModelForCausalLM, AutoTokenizer
> > 
> > checkpoint = "bigscience/bloomz-7b1-mt"
> > 
> > tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> > 
> > tokenizer(' = Valkyria Chronicles III = \n') 的结果是：
> > {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > 
> > tokenizer('<s> = Valkyria Chronicles III = \n</s>')的结果是：
> > {'input_ids': [1, 564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我感觉tokenizer并没有自动加那，第一个tokenize的结果就是训练集的输入
> 
> 你这是bloom的tokenizer，不是llama的。 不用预训练模型的toeknzier对special token的处理方式都略有不同。

大佬，我这里也测试了一下官方的调用示例，即gpt2和wiki_text的示例，也不存在prepend eos的情况，能否麻烦大佬贴一个llama的示例

**Comment by yanghb2020** [comment]
> > > > 是由tokenizer自动加的
> > > 
> > > 
> > > ```
> > > from transformers import AutoModelForCausalLM, AutoTokenizer
> > > 
> > > checkpoint = "bigscience/bloomz-7b1-mt"
> > > 
> > > tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> > > 
> > > tokenizer(' = Valkyria Chronicles III = \n') 的结果是：
> > > {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > > 
> > > tokenizer('<s> = Valkyria Chronicles III = \n</s>')的结果是：
> > > {'input_ids': [1, 564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我感觉tokenizer并没有自动加那，第一个tokenize的结果就是训练集的输入
> > 
> > 
> > 你这是bloom的tokenizer，不是llama的。 不用预训练模型的toeknzier对special token的处理方式都略有不同。
> 
> 大佬，我这里也测试了一下官方的调用示例，即gpt2和wiki_text的示例，也不存在prepend eos的情况，能否麻烦大佬贴一个llama的示例

你需要 tokenizer.add_bos_token=True

**Comment by ZeyuTeng96** [comment]
> > > > > 是由tokenizer自动加的
> > > > 
> > > > 
> > > > ```
> > > > from transformers import AutoModelForCausalLM, AutoTokenizer
> > > > 
> > > > checkpoint = "bigscience/bloomz-7b1-mt"
> > > > 
> > > > tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> > > > 
> > > > tokenizer(' = Valkyria Chronicles III = \n') 的结果是：
> > > > {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > > > 
> > > > tokenizer('<s> = Valkyria Chronicles III = \n</s>')的结果是：
> > > > {'input_ids': [1, 564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 我感觉tokenizer并没有自动加那，第一个tokenize的结果就是训练集的输入
> > > 
> > > 
> > > 你这是bloom的tokenizer，不是llama的。 不用预训练模型的toeknzier对special token的处理方式都略有不同。
> > 
> > 
> > 大佬，我这里也测试了一下官方的调用示例，即gpt2和wiki_text的示例，也不存在prepend eos的情况，能否麻烦大佬贴一个llama的示例
> 
> 你需要 tokenizer.add_bos_token=True

问您一下，那为什么官方脚本不提供这个设置呢？

**Comment by ZeyuTeng96** [comment]
> > > > > 是由tokenizer自动加的
> > > > 
> > > > 
> > > > ```
> > > > from transformers import AutoModelForCausalLM, AutoTokenizer
> > > > 
> > > > checkpoint = "bigscience/bloomz-7b1-mt"
> > > > 
> > > > tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> > > > 
> > > > tokenizer(' = Valkyria Chronicles III = \n') 的结果是：
> > > > {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > > > 
> > > > tokenizer('<s> = Valkyria Chronicles III = \n</s>')的结果是：
> > > > {'input_ids': [1, 564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 我感觉tokenizer并没有自动加那，第一个tokenize的结果就是训练集的输入
> > > 
> > > 
> > > 你这是bloom的tokenizer，不是llama的。 不用预训练模型的toeknzier对special token的处理方式都略有不同。
> > 
> > 
> > 大佬，我这里也测试了一下官方的调用示例，即gpt2和wiki_text的示例，也不存在prepend eos的情况，能否麻烦大佬贴一个llama的示例
> 
> 你需要 tokenizer.add_bos_token=True

大佬，能否加您vx，向您请教一下

**Comment by ZeyuTeng96** [comment]
> > > > > 是由tokenizer自动加的
> > > > 
> > > > 
> > > > ```
> > > > from transformers import AutoModelForCausalLM, AutoTokenizer
> > > > 
> > > > checkpoint = "bigscience/bloomz-7b1-mt"
> > > > 
> > > > tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> > > > 
> > > > tokenizer(' = Valkyria Chronicles III = \n') 的结果是：
> > > > {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > > > 
> > > > tokenizer('<s> = Valkyria Chronicles III = \n</s>')的结果是：
> > > > {'input_ids': [1, 564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 我感觉tokenizer并没有自动加那，第一个tokenize的结果就是训练集的输入
> > > 
> > > 
> > > 你这是bloom的tokenizer，不是llama的。 不用预训练模型的toeknzier对special token的处理方式都略有不同。
> > 
> > 
> > 大佬，我这里也测试了一下官方的调用示例，即gpt2和wiki_text的示例，也不存在prepend eos的情况，能否麻烦大佬贴一个llama的示例
> 
> 你需要 tokenizer.add_bos_token=True

大佬，我这里测试了加上这行和不加这行，tokenization出来的结果一样哇，这是咋回事：
```
from transformers import AutoModelForCausalLM, AutoTokenizer

checkpoint = "bigscience/bloomz-7b1-mt"

tokenizer = AutoTokenizer.from_pretrained(checkpoint)

tokenizer.add_bos_token = True

tokenizer(' = Valkyria Chronicles III = \n')

结果为：
{'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
```

不加的话：
```
from transformers import AutoModelForCausalLM, AutoTokenizer

checkpoint = "bigscience/bloomz-7b1-mt"

tokenizer = AutoTokenizer.from_pretrained(checkpoint)

tokenizer(' = Valkyria Chronicles III = \n')

结果为：
{'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
```

**Comment by ZeyuTeng96** [comment]
> > > > > > 是由tokenizer自动加的
> > > > > 
> > > > > 
> > > > > ```
> > > > > from transformers import AutoModelForCausalLM, AutoTokenizer
> > > > > 
> > > > > checkpoint = "bigscience/bloomz-7b1-mt"
> > > > > 
> > > > > tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> > > > > 
> > > > > tokenizer(' = Valkyria Chronicles III = \n') 的结果是：
> > > > > {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > > > > 
> > > > > tokenizer('<s> = Valkyria Chronicles III = \n</s>')的结果是：
> > > > > {'input_ids': [1, 564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 我感觉tokenizer并没有自动加那，第一个tokenize的结果就是训练集的输入
> > > > 
> > > > 
> > > > 你这是bloom的tokenizer，不是llama的。 不用预训练模型的toeknzier对special token的处理方式都略有不同。
> > > 
> > > 
> > > 大佬，我这里也测试了一下官方的调用示例，即gpt2和wiki_text的示例，也不存在prepend eos的情况，能否麻烦大佬贴一个llama的示例
> > 
> > 
> > 你需要 tokenizer.add_bos_token=True
> 
> 大佬，我这里测试了加上这行和不加这行，tokenization出来的结果一样哇，这是咋回事：
> 
> ```
> from transformers import AutoModelForCausalLM, AutoTokenizer
> 
> checkpoint = "bigscience/bloomz-7b1-mt"
> 
> tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> 
> tokenizer.add_bos_token = True
> 
> tokenizer(' = Valkyria Chronicles III = \n')
> 
> 结果为：
> {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> ```
> 
> 不加的话：
> 
> ```
> from transformers import AutoModelForCausalLM, AutoTokenizer
> 
> checkpoint = "bigscience/bloomz-7b1-mt"
> 
> tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> 
> tokenizer(' = Valkyria Chronicles III = \n')
> 
> 结果为：
> {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> ```

貌似这个方法，只适用于gpt2，bloom的tokenizer是没有这个函数的，而且gpt2加了这个函数，tokenization的结果也还是和不加一样的

**Comment by yanghb2020** [comment]
> > > > > > > 是由tokenizer自动加的
> > > > > > 
> > > > > > 
> > > > > > ```
> > > > > > from transformers import AutoModelForCausalLM, AutoTokenizer
> > > > > > 
> > > > > > checkpoint = "bigscience/bloomz-7b1-mt"
> > > > > > 
> > > > > > tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> > > > > > 
> > > > > > tokenizer(' = Valkyria Chronicles III = \n') 的结果是：
> > > > > > {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > > > > > 
> > > > > > tokenizer('<s> = Valkyria Chronicles III = \n</s>')的结果是：
> > > > > > {'input_ids': [1, 564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 我感觉tokenizer并没有自动加那，第一个tokenize的结果就是训练集的输入
> > > > > 
> > > > > 
> > > > > 你这是bloom的tokenizer，不是llama的。 不用预训练模型的toeknzier对special token的处理方式都略有不同。
> > > > 
> > > > 
> > > > 大佬，我这里也测试了一下官方的调用示例，即gpt2和wiki_text的示例，也不存在prepend eos的情况，能否麻烦大佬贴一个llama的示例
> > > 
> > > 
> > > 你需要 tokenizer.add_bos_token=True
> > 
> > 
> > 大佬，我这里测试了加上这行和不加这行，tokenization出来的结果一样哇，这是咋回事：
> > ```
> > from transformers import AutoModelForCausalLM, AutoTokenizer
> > 
> > checkpoint = "bigscience/bloomz-7b1-mt"
> > 
> > tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> > 
> > tokenizer.add_bos_token = True
> > 
> > tokenizer(' = Valkyria Chronicles III = \n')
> > 
> > 结果为：
> > {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不加的话：
> > ```
> > from transformers import AutoModelForCausalLM, AutoTokenizer
> > 
> > checkpoint = "bigscience/bloomz-7b1-mt"
> > 
> > tokenizer = AutoTokenizer.from_pretrained(checkpoint)
> > 
> > tokenizer(' = Valkyria Chronicles III = \n')
> > 
> > 结果为：
> > {'input_ids': [564, 6019, 11738, 2846, 73160, 28554, 10493, 564, 5306], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}
> > ```
> 
> 貌似这个方法，只适用于gpt2，bloom的tokenizer是没有这个函数的，而且gpt2加了这个函数，tokenization的结果也还是和不加一样的

用LlamaTokenizer

**Comment by char-con** [comment]
您好，请问您的想法现在进行得怎样了
