### ISSUE TITLE
词表扩充后具体怎么使用？

### ISSUE THREAD

**Issue by mellivoraPKU** [ymcui/Chinese-LLaMA-Alpaca#186]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。提问时删除上面这两行。请只保留符合的选项，删掉其他。*

### 问前必查项目

- [ ] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：

- [x] LLaMA
- [ ] Alpaca

问题类型：
- [ ] 下载问题
- [x] 模型转换和合并问题
- [ ] 模型推理问题（🤗 transformers）
- [ ] 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
- [ ] 效果问题
- [ ] 其他问题

### 详细描述问题
llama-7b,根据[词表扩充](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E8%AE%AD%E7%BB%83%E7%BB%86%E8%8A%82#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C%E8%AF%8D%E8%A1%A8%E6%89%A9%E5%85%85)，进行词表扩充后，merged_tokenizer_hf文件夹下生成三个文件。
special_tokens_map.json  tokenizer_config.json  tokenizer.model

然后可以用这三个文件直接替换llama-7b-hf中的相应文件吗？我这样操作后，报错提示
 Assertion `srcIndex < srcSelectDimSize` failed.
我将config.json中的vocab_size进行了相应的修改也还是报同样的错。
llama-7b-hf是我基于你们的”手动模型合并与转换”从llama原始权重转的。

我看到你们词表扩充的说明里，词表扩充后需要预训练，我的报错是这个原因吗？

### 运行截图或log

*（如有必要）请提供文本log或者运行截图，以便我们更好地了解问题详情。*
![image](https://user-images.githubusercontent.com/11794872/233262915-8d993734-1b12-4fa0-869e-b4bde58ec426.png)

**Comment by han508** [comment]
请问解决了吗，我也遇到了想用的问题

**Comment by airaria** [comment]
请提供更详细的报错信息（用什么参数、运行什么代码的错误）

**Comment by airaria** [comment]
另外，用LlamaTokenizer加载merged_tokenizer_hf后，请打印一下合并后的词表的长度。

**Comment by dadabin** [comment]
这个报错事需要更新词向量表重新保存模型

**Comment by han508** [comment]
维度对不上了吧

**Comment by iMountTai** [comment]
> 这个报错事需要更新词向量表重新保存模型，我有个疑问是扩充词表之后，会对之前的预训练出来的checkpoint文件使用会不会有影响，能基于扩充的词表进行fine-tune 吗

扩充词表后，原来存在的token的toekn_id是没有改变的，因此不会影响原来的checkpoint

**Comment by lyccyl1** [comment]
U may should resize the embedding layer that  the size is right.
