### ISSUE TITLE
使用LoRA进行训练时，可训练参数规模较小。

### ISSUE THREAD

**Issue by yang9112** [ymcui/Chinese-LLaMA-Alpaca#189]
### 问前必查项目

- [x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：

- [ ] LLaMA
- [x] Alpaca

问题类型：
- [ ] 下载问题
- [ ] 模型转换和合并问题
- [ ] 模型推理问题（🤗 transformers）
- [ ] 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
- [ ] 效果问题
- [x] 其他问题

### 详细描述问题

使用LORA进行训练，关于trainable params 是如何达到6%+的呢？

我使用如下参数进行训练，可训练参数只有0.06%
```
peft_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM, inference_mode=False,
    target_modules=['q_proj', 'v_proj'],
    r=8,
    lora_alpha=32, lora_dropout=0.1,
)
```

### 运行截图或log

trainable params: 4194304 || all params: 6889689088 || trainable%: 0.060877986603275876

<img width="538" alt="image" src="https://user-images.githubusercontent.com/6162257/233337766-a7e5df57-677b-4aa4-a1f0-456a5f777d34.png">

**Comment by iMountTai** [comment]
load_in_8bit=True?

**Comment by yang9112** [comment]
> load_in_8bit=True?

Maybe the gradient of embbeding&lm_head  should be set to True；

**Comment by yang9112** [comment]
> 请问这个问题解决了吗？可训练参数比例跟论文里面写的好像差的比较多

解决了，是需要将最后一层lm_head，以及embeding层加入训练。

**Comment by iMountTai** [comment]
> > 请问这个问题解决了吗？可训练参数比例跟论文里面写的好像差的比较多
> 
> 解决了，是需要将最后一层lm_head，以及embeding层加入训练。
请问您是加载的全量模型还是int8？

**Comment by iMountTai** [comment]
> > 请问这个问题解决了吗？可训练参数比例跟论文里面写的好像差的比较多
> 
> 解决了，是需要将最后一层lm_head，以及embeding层加入训练。

请问您是加载的全量模型微调还是int8微调？

**Comment by Oliver-whsun** [comment]
> > 请问这个问题解决了吗？可训练参数比例跟论文里面写的好像差的比较多
> 
> 解决了，是需要将最后一层lm_head，以及embeding层加入训练。

您方便透露一下微调需要的硬件条件吗？

**Comment by yang9112** [comment]
> > > 请问这个问题解决了吗？可训练参数比例跟论文里面写的好像差的比较多
> > 
> > 
> > 解决了，是需要将最后一层lm_head，以及embeding层加入训练。
> 
> 您方便透露一下微调需要的硬件条件吗？

微调的话，7B的模型一块V100就够了（主要显存够就行），或者可以用deepspeed的stage3模式可以降低显存需求。
deepspeed的话2块V100，100万数据大概需要100小时左右。
