### ISSUE TITLE
请问直接运行合并后的chinese-alpaca-7b？提示找不到config.json

### ISSUE THREAD

**Issue by sanbuphy** [ymcui/Chinese-LLaMA-Alpaca#190]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。提问时删除上面这两行。请只保留符合的选项，删掉其他。*

### 问前必查项目

- [x ] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x ] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：

- [ ] LLaMA
- [x ] Alpaca

问题类型：
- [ ] 下载问题
- [ ] 模型转换和合并问题
- [ x] 模型推理问题（🤗 transformers）
- [ ] 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
- [ ] 效果问题
- [ ] 其他问题

### 详细描述问题

*请尽量具体地描述您遇到的问题。这将有助于我们更快速地定位问题所在。*

### 运行截图或log

*（如有必要）请提供文本log或者运行截图，以便我们更好地了解问题详情。*
我根据这个文档，直接运行 合并后的，把合并后的模型cp到models下但是跑不起来
https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E4%BD%BF%E7%94%A8text-generation-webui%E6%90%AD%E5%BB%BA%E7%95%8C%E9%9D%A2
![image](https://user-images.githubusercontent.com/96160062/233344819-2e51e1cb-7b7f-4d84-a439-7c14c4f627cf.png)

**Comment by zillaer** [comment]
我这也是

`Traceback (most recent call last):
File “/var/lib/xray/fireshot/xray-1/soft/local/anaconda3/envs/py3.10.9/lib/python3.10/site-packages/transformers/configuration_utils.py”, line 658, in _get_config_dict
config_dict = cls._dict_from_json_file(resolved_config_file)
File “/var/lib/xray/fireshot/xray-1/soft/local/anaconda3/envs/py3.10.9/lib/python3.10/site-packages/transformers/configuration_utils.py”, line 745, in _dict_from_json_file
text = reader.read()
File “/var/lib/xray/fireshot/xray-1/soft/local/anaconda3/envs/py3.10.9/lib/python3.10/codecs.py”, line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: ‘utf-8’ codec can’t decode byte 0x80 in position 128: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File “/var/lib/xray/fireshot/xray-1/soft/text-generation-webui/server.py”, line 100, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name)
File “/var/lib/xray/fireshot/xray-1/soft/text-generation-webui/modules/models.py”, line 186, in load_model
model = LoaderClass.from_pretrained(checkpoint, **params)
File “/var/lib/xray/fireshot/xray-1/soft/local/anaconda3/envs/py3.10.9/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py”, line 441, in from_pretrained
config, kwargs = AutoConfig.from_pretrained(
File “/var/lib/xray/fireshot/xray-1/soft/local/anaconda3/envs/py3.10.9/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py”, line 916, in from_pretrained
config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
File “/var/lib/xray/fireshot/xray-1/soft/local/anaconda3/envs/py3.10.9/lib/python3.10/site-packages/transformers/configuration_utils.py”, line 573, in get_config_dict
config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
File “/var/lib/xray/fireshot/xray-1/soft/local/anaconda3/envs/py3.10.9/lib/python3.10/site-packages/transformers/configuration_utils.py”, line 661, in _get_config_dict
raise EnvironmentError(
OSError: It looks like the config file at ‘…/local/model/models–minlik–chinese-alpaca-7b-merged/snapshots/5bcba5281f57febd95bf4751a46a59e30f3fd5bc/pytorch_model-00001-of-00002.bin’ is not a valid JSON file.`

**Comment by sanbuphy** [comment]
> 我这也是
> 
> ```
> File “/var/lib/xray/fireshot/xray-1/soft/local/anaconda3/envs/py3.10.9/lib/python3.10/site-packages/transformers/configuration_utils.py”, line 658, in _get_config_dict
> config_dict = cls._dict_from_json_file(resolved_config_file)
> File “/var/lib/xray/fireshot/xray-1/soft/local/anaconda3/envs/py3.10.9/lib/python3.10/site-packages/transformers/configuration_utils.py”, line 745, in _dict_from_json_file
> text = reader.read()
> File “/var/lib/xray/fireshot/xray-1/soft/local/anaconda3/envs/py3.10.9/lib/python3.10/codecs.py”, line 322, in decode
> (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: ‘utf-8’ codec can’t decode byte 0x80 in position 128: invalid start byte
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File “/var/lib/xray/fireshot/xray-1/soft/text-generation-webui/server.py”, line 100, in load_model_wrapper
> shared.model, shared.tokenizer = load_model(shared.model_name)
> File “/var/lib/xray/fireshot/xray-1/soft/text-generation-webui/modules/models.py”, line 186, in load_model
> model = LoaderClass.from_pretrained(checkpoint, **params)
> File “/var/lib/xray/fireshot/xray-1/soft/local/anaconda3/envs/py3.10.9/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py”, line 441, in from_pretrained
> config, kwargs = AutoConfig.from_pretrained(
> File “/var/lib/xray/fireshot/xray-1/soft/local/anaconda3/envs/py3.10.9/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py”, line 916, in from_pretrained
> config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
> File “/var/lib/xray/fireshot/xray-1/soft/local/anaconda3/envs/py3.10.9/lib/python3.10/site-packages/transformers/configuration_utils.py”, line 573, in get_config_dict
> config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
> File “/var/lib/xray/fireshot/xray-1/soft/local/anaconda3/envs/py3.10.9/lib/python3.10/site-packages/transformers/configuration_utils.py”, line 661, in _get_config_dict
> raise EnvironmentError(
> OSError: It looks like the config file at ‘…/local/model/models–minlik–chinese-alpaca-7b-merged/snapshots/5bcba5281f57febd95bf4751a46a59e30f3fd5bc/pytorch_model-00001-of-00002.bin’ is not a valid JSON file.```
> ```

https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/33

**Comment by onkyoworm** [comment]
出现同样的问题
1、第一个路径报错很奇怪，明明都已经去掉符号了为什么还有这个错误
2、config.json 这个文件全局搜索后发现只有在 step1 生成的结果里面出现，但根据 [指引](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E6%89%8B%E5%8A%A8%E6%A8%A1%E5%9E%8B%E5%90%88%E5%B9%B6%E4%B8%8E%E8%BD%AC%E6%8D%A2#Model-Hub) lora_model 这个参数后面跟的是原始下载的LLaMA/Alpaca LoRA解压后文件所在目录
3、即使手动放一个错误的 config.json 文件进入 lora_model 参数中，依然回报找不到这个文件的错误

env：三个主依赖库和指引一致，win 10，python 3.10，conda

![image](https://user-images.githubusercontent.com/16128133/233408322-de0d30be-f63b-4e6c-894c-83284ad38d63.png)

**Comment by sanbuphy** [comment]
> 出现同样的问题 1、第一个路径报错很奇怪，明明都已经去掉符号了为什么还有这个错误 2、config.json 这个文件全局搜索后发现只有在 step1 生成的结果里面出现，但根据 [指引](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E6%89%8B%E5%8A%A8%E6%A8%A1%E5%9E%8B%E5%90%88%E5%B9%B6%E4%B8%8E%E8%BD%AC%E6%8D%A2#Model-Hub) lora_model 这个参数后面跟的是原始下载的LLaMA/Alpaca LoRA解压后文件所在目录 3、即使手动放一个错误的 config.json 文件进入 lora_model 参数中，依然回报找不到这个文件的错误
> 
> env：三个主依赖库和指引一致，win 10，python 3.10，conda
> 
> ![image](https://user-images.githubusercontent.com/16128133/233408322-de0d30be-f63b-4e6c-894c-83284ad38d63.png)

你是否有尝试：
将原版LLaMA模型转换为HF格式  http://www.kala.love/posts/d1febb52/?spm=wolai.workspace.0.0.14314c752FmBl5

**Comment by sanbuphy** [comment]
我自己找到了方法，请使用：merge_llama_with_chinese_lora_to_hf.py

**Comment by biaggii** [comment]
ME TOO 
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/10355830/25125caf-b402-44f9-b040-04f157f2202b)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/10355830/0dd9cf94-c337-42bd-a08b-05ba3a3126ff)

**Comment by airaria** [comment]
运行merge_llama_with_chinese_lora_to_hf.py时添加参数`--output_type huggingface` 
另外建议使用新合并脚本[merge_llama_with_chinese_lora_low_mem.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_llama_with_chinese_lora_low_mem.py)
