### ISSUE TITLE
如果想在GPU上使用llama.cpp的方式来完成Embeddings，有什么办法吗？

### ISSUE THREAD

**Issue by WonpangNew** [ymcui/Chinese-LLaMA-Alpaca#192]
### 问前必查项目

- [✓] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [✓] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [✓] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：

- [✓] LLaMA
- [✓] Alpaca

问题类型：
- [ ] 下载问题
- [ ] 模型转换和合并问题
- [ ] 模型推理问题（🤗 transformers）
- [ ] 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
- [ ] 效果问题
- [✓] 其他问题

### 详细描述问题

在GPU机器上就要llama.cpp工具运行模型失败，无法加载，报如下错误`Illegal instruction (core dumped)`。我的目的是希望基于本地模型对文本进行Embeddings，实现Q&A，有什么解决办法吗？或者有其他方式吗

**Comment by ymcui** [comment]
不是很清楚，llama.cpp的GPU支持似乎是近期才添加的，可能是属于实验性的，最好是再等等稳定了再使用。
