### ISSUE TITLE
使用新版本的transformers进行13b模型合并后，在推理时出现UnicodeDecodeError

### ISSUE THREAD

**Issue by rayguo01** [ymcui/Chinese-LLaMA-Alpaca#197]
### 问前必查项目

- [x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：

- [x] LLaMA
- [ ] Alpaca

问题类型：
- [ ] 下载问题
- [ ] 模型转换和合并问题
- [x] 模型推理问题（🤗 transformers）
- [ ] 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
- [ ] 效果问题
- [ ] 其他问题

### 详细描述问题
安装软件版本：
transformer：4.28.1
sentencepiece：0.1.98
peft：0.3.0.dev0

按“手动模型合并与转换”，将原版的13B的模型权重转换为HF格式，并完成step2，输出HuggingFace版本权重。
采用自己的中文语料对step2的模型进行微调，对生成的模型采用一个极简单代码运行推理：
=============
import time
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer

tokenizer = LlamaTokenizer.from_pretrained('./output_13b')
model = LlamaForCausalLM.from_pretrained('./output_13b') #, torch_dtype=torch.half)

single_inputs="Below is an instruction that describes a task. Write a response that appropriately completes the request.
 Instruction:
如何健身？
Response:“

batch = tokenizer(single_inputs,return_tensors="pt",padding=True)
batch = {k: v for k, v in batch.items()}
with torch.inference_mode():
    print("Start")
    t0 = time.time()
    generated = model.generate(batch["input_ids"], attention_mask=batch["attention_mask"], max_length=200,temperature=0.7,top_p=0.1,top_k=40,do_sample=True,num_beams=1)
    t1 = time.time()
    print(f"Output generated in {(t1-t0):.2f} seconds")
    for g in generated:
        print(tokenizer.decode(g))
================
推理运行时出现：UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte

请问可能是哪里的问题呢？

### 运行截图或log
![111](https://user-images.githubusercontent.com/11142405/233759353-a2082b64-0a7b-4078-b6b6-739bfb9615f4.jpg)
![222](https://user-images.githubusercontent.com/11142405/233759355-ae038a50-cc91-48e7-9c50-2216cbed0b7f.jpg)
![333](https://user-images.githubusercontent.com/11142405/233759357-aebeb9d0-69b0-4960-9f32-ebfa6123e3ed.jpg)

*（如有必要）请提供文本log或者运行截图，以便我们更好地了解问题详情。*

**Comment by iMountTai** [comment]
几个建议：
1. 训练与推理的环境是否相同，比如pytorch版本；
2. 模型保存格式，`torch.save(model,path)`或者`torch.save(model.static_dict(),path)`
3. 模型文件是否完整或者有损坏
4. 内存大小

**Comment by airaria** [comment]
可否先尝试下用纯英文的输入能否正常工作？

**Comment by rayguo01** [comment]
A100*8的环境，训练和推理是同一个环境。我重装了transformers，指定版本为4.28.1，就可以运行了。
