### ISSUE TITLE
windows模型合并assert not torch.allclose(first_weight_old, first_weight)

### ISSUE THREAD

**Issue by zyxdm** [ymcui/Chinese-LLaMA-Alpaca#198]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。提问时删除上面这两行。请只保留符合的选项，删掉其他。*

### 问前必查项目

- [x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：

- [x] LLaMA
- [ ] Alpaca

问题类型：
- [ ] 下载问题
- [x] 模型转换和合并问题
- [ ] 模型推理问题（🤗 transformers）
- [ ] 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
- [ ] 效果问题
- [ ] 其他问题

### 详细描述问题

windows下运行merge_llama_with_chinese_lora.py后，加载模型都完成，但是异常处理部分报错

### 运行截图或log
![image](https://user-images.githubusercontent.com/18589352/233764247-73e27acf-b904-4d75-bbc2-86c36a5c5dc7.png)

*（如有必要）请提供文本log或者运行截图，以便我们更好地了解问题详情。*

**Comment by ymcui** [comment]
没看到最下面报错的地方，麻烦把最后的log贴一下。
另外看到peft版本0.1.0，可能会有问题，建议0.2.0。

**Comment by zyxdm** [comment]
换了Peft库后不再报上面的错了，在save_shards那行代码处报"DefaultCPUAllocator: not enough memory"错误，电脑可用内存为不到16G，后面换设备试，感谢作者！
