### ISSUE TITLE
请求提供数据集和训练代码

### ISSUE THREAD

**Issue by MrToy** [ymcui/Chinese-LLaMA-Alpaca#2]
请问下具体使用了哪些数据集
想尝试本地复现13B、33B的效果

**Comment by nanmu42** [comment]
我只是个关注者。

作者在README里简述了训练细节。

另外也许还可以参考：https://github.com/tloen/alpaca-lora

希望对你有帮助。

**Comment by ymcui** [comment]
你好，数据相关来源请参考：[https://github.com/ymcui/Chinese-LLaMA-Alpaca#训练数据与超参](https://github.com/ymcui/Chinese-LLaMA-Alpaca#训练数据与超参)

**Comment by ehion** [comment]
@ymcui 只提供一个hf demo，扩充词表在这个项目里面并没有体现，不知道有什么意义。
