### ISSUE TITLE
使用transformers方式，GPU是否有加载量化模型的方式？

### ISSUE THREAD

**Issue by xiaozhu1106** [ymcui/Chinese-LLaMA-Alpaca#200]
### 问前必查项目

- [x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：

- [ ] LLaMA
- [x] Alpaca

问题类型：
- [ ] 下载问题
- [ ] 模型转换和合并问题
- [x] 模型推理问题（🤗 transformers）
- [ ] 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
- [ ] 效果问题
- [ ] 其他问题

### 详细描述问题

*使用transformers方式，GPU是否有加载量化模型的方式？*

**Comment by iMountTai** [comment]
可以尝试一下load_in_8bit,加载模型时使用`from_pretrained(model_name-or_path, load_in_8bit=True,device_map="auto")`

**Comment by xiaozhu1106** [comment]
> 可以尝试一下load_in_8bit,加载模型时使用`from_pretrained(model_name_or_path, load_in_8bit=True,device_map="auto")`参考代码[transformers load_in_8bit](https://huggingface.co/docs/transformers/v4.28.1/en/main_classes/quantization#load-a-large-model-in-8bit)

使用这种方式，7b的可以正常预测。13b的会报错，报错信息如下：
Traceback (most recent call last):
  File "/workspace/LLaMA/Chinese-LLaMA-Alpaca/scripts/inference_hf.py", line 105, in <module>
    generation_output = model.generate(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 2560, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
