### ISSUE TITLE
我合并+量化了 7B 和 13B 的模型提供给大家下载，并写了使用方法

### ISSUE THREAD

**Issue by johnlui** [ymcui/Chinese-LLaMA-Alpaca#204]
其实合并和量化都很简单，也很快，但是没人写文档说怎么用😂

下载仓库地址：https://huggingface.co/johnlui/chinese-alpaca-7b-and-13b-quantized

移动本仓库中的`llama-7b-hf`和`llama-13b-hf`两个文件夹，到你项目的`./models`文件下即可。该文件夹同时适用于`llama.cpp`和`text-generation-webui`。

**Comment by mcu13321** [comment]
我试了下报错
llama.cpp: loading model from models/llama-7b-hf/ggml-model-q4_0.bin
error loading model: unknown (magic, version) combination: 73726576, 206e6f69; is this really a GGML file?
llama_init_from_file: failed to load model
main: error: failed to load model 'models/llama-7b-hf/ggml-model-q4_0.bin'

**Comment by PetitPrinceb612** [comment]
感谢

**Comment by holycrypto** [comment]
谢谢大佬，可以用了。

**Comment by mcu13321** [comment]
感谢大佬

**Comment by mcu13321** [comment]
![img_v2_4c8bf3a2-557e-4a06-aac6-bca4e54ae42g](https://user-images.githubusercontent.com/12017476/234164824-0b71d660-4cd0-417a-9938-555823c5634a.jpg)
13B模型，看着不太聪明的样子

**Comment by honglvagan** [comment]
> ![img_v2_4c8bf3a2-557e-4a06-aac6-bca4e54ae42g](https://user-images.githubusercontent.com/12017476/234164824-0b71d660-4cd0-417a-9938-555823c5634a.jpg) 13B模型，看着不太聪明的样子

单看这一段,他说的一点也不错啊

**Comment by mcu13321** [comment]
> > ![img_v2_4c8bf3a2-557e-4a06-aac6-bca4e54ae42g](https://user-images.githubusercontent.com/12017476/234164824-0b71d660-4cd0-417a-9938-555823c5634a.jpg) 13B模型，看着不太聪明的样子
> 
> 单看这一段,他说的一点也不错啊

![img_v2_d1002066-4a92-4361-9965-a60dd1a0509g](https://user-images.githubusercontent.com/12017476/234165185-0d15467a-83c3-46eb-b308-dd93261ecf50.jpg)
那这个呢🤔

**Comment by ymcui** [comment]
> 

输出似乎不是很对劲，有可能模型不完整。😂

<img width="637" alt="image" src="https://user-images.githubusercontent.com/16095339/234165270-44521371-4f02-4a53-9636-fa89f8fa618a.png">

**Comment by honglvagan** [comment]
> @mcu13321 你测试的输出似乎不是很对劲，有可能模型不完整。😂
> 
> <img alt="image" width="637" src="https://user-images.githubusercontent.com/16095339/234165270-44521371-4f02-4a53-9636-fa89f8fa618a.png">

哥,会不会和运行 ./main 的参数有关?我一开始直接用示例的参数,他还是只说英文,我把参数调大他才开始说中文的,我现在用的 ./main -m models/llama-13b-hf/ggml-model-q4_0.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 1 -n 2048 -t 8 --repeat_penalty 1.3 运行

**Comment by ymcui** [comment]
> > @mcu13321 你测试的输出似乎不是很对劲，有可能模型不完整。😂
> > <img alt="image" width="637" src="https://user-images.githubusercontent.com/16095339/234165270-44521371-4f02-4a53-9636-fa89f8fa618a.png">
> 
> 哥,会不会和运行 ./main 的参数有关?我一开始直接用示例的参数,他还是只说英文,我把参数调大他才开始说中文的,我现在用的 ./main -m models/llama-13b-hf/ggml-model-q4_0.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 1 -n 2048 -t 8 --repeat_penalty 1.3 运行

我确认一下，你用的是llama还是alpaca？llama的话一般是用来做续写的，alpaca是用来指令理解（交互）的。
具体你看一下这里：[这里](https://github.com/ymcui/Chinese-LLaMA-Alpaca#我应该选什么模型)

**Comment by honglvagan** [comment]
> > > @mcu13321 你测试的输出似乎不是很对劲，有可能模型不完整。😂
> > > <img alt="image" width="637" src="https://user-images.githubusercontent.com/16095339/234165270-44521371-4f02-4a53-9636-fa89f8fa618a.png">
> > 
> > 
> > 哥,会不会和运行 ./main 的参数有关?我一开始直接用示例的参数,他还是只说英文,我把参数调大他才开始说中文的,我现在用的 ./main -m models/llama-13b-hf/ggml-model-q4_0.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 1 -n 2048 -t 8 --repeat_penalty 1.3 运行
> 
> 我确认一下，你用的是llama还是alpaca？llama的话一般是用来做续写的，alpaca是用来指令理解（交互）的。 具体你看一下这里：[这里](https://github.com/ymcui/Chinese-LLaMA-Alpaca#%E6%88%91%E5%BA%94%E8%AF%A5%E9%80%89%E4%BB%80%E4%B9%88%E6%A8%A1%E5%9E%8B)

Alpaca,我用的大哥发的文件,不过我刚发现我好像没加 -ins 参数,使用-ins参数才启动指令理解+聊天模式,我再试试

**Comment by norris9410** [comment]
> > > @mcu13321 你测试的输出似乎不是很对劲，有可能模型不完整。😂
> > > <img alt="image" width="637" src="https://user-images.githubusercontent.com/16095339/234165270-44521371-4f02-4a53-9636-fa89f8fa618a.png">
> > 
> > 
> > 哥,会不会和运行 ./main 的参数有关?我一开始直接用示例的参数,他还是只说英文,我把参数调大他才开始说中文的,我现在用的 ./main -m models/llama-13b-hf/ggml-model-q4_0.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 1 -n 2048 -t 8 --repeat_penalty 1.3 运行
> 
> 我确认一下，你用的是llama还是alpaca？llama的话一般是用来做续写的，alpaca是用来指令理解（交互）的。 具体你看一下这里：[这里](https://github.com/ymcui/Chinese-LLaMA-Alpaca#%E6%88%91%E5%BA%94%E8%AF%A5%E9%80%89%E4%BB%80%E4%B9%88%E6%A8%A1%E5%9E%8B)

你好！那比如就是“如何快速睡眠”这个中文，请问我应该用llama做好还是alpaca做？

**Comment by iMountTai** [comment]
> > > > @mcu13321 你测试的输出似乎不是很对劲，有可能模型不完整。😂
> > > > <img alt="image" width="637" src="https://user-images.githubusercontent.com/16095339/234165270-44521371-4f02-4a53-9636-fa89f8fa618a.png">
> > > 
> > > 
> > > 哥,会不会和运行 ./main 的参数有关?我一开始直接用示例的参数,他还是只说英文,我把参数调大他才开始说中文的,我现在用的 ./main -m models/llama-13b-hf/ggml-model-q4_0.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 1 -n 2048 -t 8 --repeat_penalty 1.3 运行
> > 
> > 
> > 我确认一下，你用的是llama还是alpaca？llama的话一般是用来做续写的，alpaca是用来指令理解（交互）的。 具体你看一下这里：[这里](https://github.com/ymcui/Chinese-LLaMA-Alpaca#%E6%88%91%E5%BA%94%E8%AF%A5%E9%80%89%E4%BB%80%E4%B9%88%E6%A8%A1%E5%9E%8B)
> 
> 你好！那比如就是“如何快速睡眠”这个中文，请问我应该用llama做好还是alpaca做？

alpaca

**Comment by johnlui** [comment]
> > @mcu13321 你测试的输出似乎不是很对劲，有可能模型不完整。😂
> > <img alt="image" width="637" src="https://user-images.githubusercontent.com/16095339/234165270-44521371-4f02-4a53-9636-fa89f8fa618a.png">
> 
> 这个13B的模型跟7B的相比，效果比较差。是merge的时候出了问题吗？有办法验证最终合成的模型是否有问题吗？
> 
> 我可以再重新合一下模型试试效果。

13B确实比7B效果差，不用怀疑自己，就用7B吧

**Comment by BoyuGuan** [comment]
> 

请问这是什么原因呢？根据作者的测试来看，13B应该比7B好一些才对呀。

**Comment by BoyuGuan** [comment]
> > > @mcu13321 你测试的输出似乎不是很对劲，有可能模型不完整。😂
> > > <img alt="image" width="637" src="https://user-images.githubusercontent.com/16095339/234165270-44521371-4f02-4a53-9636-fa89f8fa618a.png">
> > 
> > 
> > 这个13B的模型跟7B的相比，效果比较差。是merge的时候出了问题吗？有办法验证最终合成的模型是否有问题吗？
> > 我可以再重新合一下模型试试效果。
> 
> 13B确实比7B效果差，不用怀疑自己，就用7B吧

请问这是什么原因呢？根据作者的测试来看，13B应该比7B好一些才对呀。

**Comment by johnlui** [comment]
@mcu13321 @BoyuGuan 我前几天更新了 13b 的 config.json 文件，昨天我测试了 13B 模型，发现它的效果确实是比 7B 要好的。在润色文本场景下，Kobold-Liminal Drift 效果最佳。你们可以试试更新我仓库里 13b 文件夹下的 config.json 文件，再用 Kobold-Liminal Drift 测试一下，相信会得到一个好的结果

**Comment by BenjiKCF** [comment]
大哥 7B plus跟13b 那要個比較好?

**Comment by regaliastar** [comment]
感谢🙏

**Comment by brealisty** [comment]
> @mcu13321 @BoyuGuan 我前几天更新了 13b 的 config.json 文件，昨天我测试了 13B 模型，发现它的效果确实是比 7B 要好的。在润色文本场景下，Kobold-Liminal Drift 效果最佳。你们可以试试更新我仓库里 13b 文件夹下的 config.json 文件，再用 Kobold-Liminal Drift 测试一下，相信会得到一个好的结果
@johnlui 楼主13b，会出现惜字如金的情况，我测试的7b 4-bit的模型，输出很短，即便提示它输出长一些也不行

**Comment by wood911** [comment]
![image](https://user-images.githubusercontent.com/13845554/237007715-74daa40f-e93d-4777-b398-415abb4b2d97.png)
不同的答案跟量化模型有关，模型越大回答越详细准确

**Comment by prettyboyweiwei** [comment]
请问合并的是 Alpaca 7B plus 版吗

**Comment by prettyboyweiwei** [comment]
刚试了下应该是 7B 普通版？
![35464fb4-00d9-4d61-bff0-d8cbc4a070ca](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/17541345/47c995d7-82f2-4de0-866c-d2210ce889f2)
