### ISSUE TITLE
There appear to be 1 leaked semaphore objects to clean up at shutdown   warnings.warn('resource_tracker: There appear to be %d '

### ISSUE THREAD

**Issue by jiangminglu** [ymcui/Chinese-LLaMA-Alpaca#205]
### 问前必查项目

- [☑️ ] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [☑️ ] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ☑️] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：

- [ ] LLaMA
- [ ☑️] Alpaca

问题类型：
- [ ] 下载问题
- [ ] 模型转换和合并问题
- [ ] 模型推理问题（🤗 transformers）
- [☑️] 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
- [ ] 效果问题
- [ ] 其他问题

### 详细描述问题
运行 命令：`python3 server.py --model llama-13b-hf --lora chinese-alpaca-lora-13b --cpu` 报错：
Gradio HTTP request redirected to localhost :)
bin /Users/luffy/anaconda3/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/Users/luffy/anaconda3/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading llama-13b-hf...
Loading checkpoint shards:  67%|██████████████████████████████████████████████████████████                             | 2/3 [01:47<00:56, 56.66s/it][1]    735 killed     python3 server.py --model llama-13b-hf --lora chinese-alpaca-lora-13b --cpu
/Users/luffy/anaconda3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

### 运行截图或log
![image](https://user-images.githubusercontent.com/1673370/233945991-24132863-95e9-45ed-9476-99071a123202.png)

**Comment by airaria** [comment]
server.py是你自己的启动脚本吗？错误似乎与chinese-llama本身无关，而且相关信息太少无法定位问题。
建议到使用到的相关项目中查找解决方案。
