### ISSUE TITLE
第一步，可以直接embedding和lora一起pre-train吗？还是必须先把embedding训练了，再一起训练embedding和lora？

### ISSUE THREAD

**Issue by ttzHome** [ymcui/Chinese-LLaMA-Alpaca#208]
如题，embedding和lora一起训练，是不是loss会很大？

**Comment by ymcui** [comment]
可以一起训。最开始我们在摸索适配方案，所以有两阶段的形式。
13B的时候已经不包含一阶段了（单独训练embedding）。具体可以参考技术报告：https://arxiv.org/abs/2304.08177

**Comment by ttzHome** [comment]
> 可以一起训。最开始我们在摸索适配方案，所以有两阶段的形式。 13B的时候已经不包含一阶段了（单独训练embedding）。具体可以参考技术报告：https://arxiv.org/abs/2304.08177

请问，刚开始lora和embedding一起run_clm的时候，loss很大，降不下来，是有什么可能原因哇？

**Comment by airaria** [comment]
> > 可以一起训。最开始我们在摸索适配方案，所以有两阶段的形式。 13B的时候已经不包含一阶段了（单独训练embedding）。具体可以参考技术报告：https://arxiv.org/abs/2304.08177
> 
> 请问，刚开始lora和embedding一起run_clm的时候，loss很大，降不下来，是有什么可能原因哇？

loss是多少？LM head是否参与了训练？

**Comment by ttzHome** [comment]
> > > 可以一起训。最开始我们在摸索适配方案，所以有两阶段的形式。 13B的时候已经不包含一阶段了（单独训练embedding）。具体可以参考技术报告：https://arxiv.org/abs/2304.08177
> > 
> > 
> > 请问，刚开始lora和embedding一起run_clm的时候，loss很大，降不下来，是有什么可能原因哇？
> 
> loss是多少？LM head是否参与了训练？




> > > 可以一起训。最开始我们在摸索适配方案，所以有两阶段的形式。 13B的时候已经不包含一阶段了（单独训练embedding）。具体可以参考技术报告：https://arxiv.org/abs/2304.08177
> > 
> > 
> > 请问，刚开始lora和embedding一起run_clm的时候，loss很大，降不下来，是有什么可能原因哇？
> 
> loss是多少？LM head是否参与了训练？

lm head是不是预测层，就是模型最后一层？是的话那就加了，loss为14左右

> > > 可以一起训。最开始我们在摸索适配方案，所以有两阶段的形式。 13B的时候已经不包含一阶段了（单独训练embedding）。具体可以参考技术报告：https://arxiv.org/abs/2304.08177
> > 
> > 
> > 请问，刚开始lora和embedding一起run_clm的时候，loss很大，降不下来，是有什么可能原因哇？
> 
> loss是多少？LM head是否参与了训练？

lm head是不是预测层，就是模型最后一层？是的话那就加了，loss为14左右

**Comment by airaria** [comment]
> lm head是不是预测层，就是模型最后一层？是的话那就加了，loss为14左右

那相当大了，基本和随机猜差不多
请确认超参是否合理，以及确认模型是否更新了embedding和lm head的参数

**Comment by AceCHQ** [comment]
请问在13b的训练第一阶段的训练脚本可以分享吗？

**Comment by airaria** [comment]
> 请问在13b的训练第一阶段的训练脚本可以分享吗？

https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/预训练脚本

13b没有使用预训练阶段1
