### ISSUE TITLE
关于合并后的完整权重模型能否进行finetune

### ISSUE THREAD

**Issue by fanxiangshangfen** [ymcui/Chinese-LLaMA-Alpaca#21]
您好，按照您的步骤生成了全量模型权重，并转化为huggingface版本权重。我想请问能否在全量模型权重的基础上进行进一步的finetune。我尝试加载权重进行训练，但是训练时报错。是不是因为转化的huggingface的权重没法用来继续训练？

CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /opt/conda/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
Training Alpaca-LoRA model with params:
base_model: /mnt/hf/luruixuan/Chinese-LLaMA-Alpaca/chinese-alpaca-lora-7b_complete_hf
data_path: data/alpaca_train_shuf_0330.json
output_dir: ./Chinese-LLaMA-Alpaca/chinese-alpaca-lora-7b/lora-alpaca_fp16_batch64
batch_size: 64
micro_batch_size: 1
num_epochs: 3
learning_rate: 0.0001
cutoff_len: 1300
val_set_size: 0
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: ['q_proj', 'v_proj']
train_on_inputs: True
group_by_length: True
wandb_project: 
wandb_run_name: 
wandb_watch: 
wandb_log_model: 
resume_from_checkpoint: None

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.93s/it]
Downloading and preparing dataset json/default to /home/jovyan/.cache/huggingface/datasets/json/default-3d44ff85e8e2e508/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51...
Downloading data files: 100%|███████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 10255.02it/s]
Extracting data files: 100%|███████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.70it/s]
Dataset json downloaded and prepared to /home/jovyan/.cache/huggingface/datasets/json/default-3d44ff85e8e2e508/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51. Subsequent calls will reuse this data.
100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 687.93it/s]
trainable params: 4194304 || all params: 6889689088 || trainable%: 0.060877986603275876
  0%|                                                                                           | 0/1875 [00:00<?, ?it/s]Traceback (most recent call last):
  File "finetune_lora.py", line 293, in <module>
    fire.Fire(train)
  File "/opt/conda/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.7/site-packages/fire/core.py", line 480, in _Fire
    target=component.__name__)
  File "/opt/conda/lib/python3.7/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "finetune_lora.py", line 260, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 1643, in train
    ignore_keys_for_eval=ignore_keys_for_eval,
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 1906, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 2652, in training_step
    loss = self.compute_loss(model, inputs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/trainer.py", line 2684, in compute_loss
    outputs = model(**inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/peft-0.3.0.dev0-py3.7.egg/peft/peft_model.py", line 537, in forward
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/transformers/models/llama/modeling_llama.py", line 709, in forward
    shift_logits = shift_logits.view(-1, self.config.vocab_size)
RuntimeError: shape '[-1, 32000]' is invalid for input of size 65090062

**Comment by ZenXir** [comment]
遇到了相同问题 正在看huggingface 官网 model文档 有哪位大佬知道 给讲解下吧

**Comment by ZenXir** [comment]
在 prepare for traning 前 resize_token_embeddings 就可以训练了
如果有其它方式 大佬们多交流说说
```
vocab_size = len(tokenizer.get_vocab())
print("Tokenizer的词表数量为：", vocab_size)
model.resize_token_embeddings(vocab_size)
```

**Comment by airaria** [comment]
我们没有做过合并后的完整权重重新进行finetune的实验，不过从理论上讲应该没有问题。

从错误信息看，可能要注意的是config.json中的词表大小是否与模型的embedding大小一致。如果不一致（比如config.json中仍然是32000，而模型大小是49953），可以手动修改config.json中的相关配置参数。

**Comment by CrazyBoyM** [comment]
这里是对扩充词表后的的"chinese-llama"权重进行二次训练吗？

**Comment by fanxiangshangfen** [comment]
> 在准备训练之前 resize_token_embeddings 就可以训练了 如果有其他方式 大佬们多交流说说
> 
> ```
> vocab_size = len(tokenizer.get_vocab())
> print("Tokenizer的词表数量为：", vocab_size)
> model.resize_token_embeddings(vocab_size)
> ```

没错确实是vocab 的问题，我已经按照这个方法更改了可以跑通。感谢解答

**Comment by Zombiessss** [comment]
> 

现在不用显示更改vocab大小就能跑了，是你们重新适配过了吗

**Comment by Zombiessss** [comment]
> 我们没有做过合并后的完整权重重新进行finetune的实验，不过从理论上讲应该没有问题。
> 
> 从错误信息看，可能要注意的是config.json中的词表大小是否与模型的embedding大小一致。如果不一致（比如config.json中仍然是32000，而模型embedding大小是49953），可以手动修改config.json中的相关配置参数。

现在不用显示更改vocab大小就能跑了，是你们重新适配过了吗
