### ISSUE TITLE
可以整理一下项目的依赖的情况吗？

### ISSUE THREAD

**Issue by candowu** [ymcui/Chinese-LLaMA-Alpaca#211]
如题

**Comment by ymcui** [comment]
比如？

**Comment by ymcui** [comment]
模型转换这里有写需要的前置安装：[https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/手动模型合并与转换](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/手动模型合并与转换)

**Comment by candowu** [comment]
感谢回复！是不是放个requirements.txt到项目里面。

transformer 4.28.1 执行 scripts/merge_llama_with_chinese_lora_to_hf.py  报错：
Traceback (most recent call last):
  File "/data/candowu/Chinese-LLaMA-Alpaca-2.2/scripts/merge_llama_with_chinese_lora_to_hf.py", line 24, in <module>
    assert (
AssertionError: LLaMA is now in HuggingFace's main branch.

命令执行结果如下：
>>> import transformers
>>> transformers._import_structure["models.llama"]
['LLAMA_PRETRAINED_CONFIG_ARCHIVE_MAP', 'LlamaConfig', 'LlamaTokenizerFast', 'LlamaForCausalLM', 'LlamaForSequenceClassification', 'LlamaModel', 'LlamaPreTrainedModel']

帮忙看看这是什么问题，记得之前合并过，没有这个报错。

**Comment by ymcui** [comment]
注释掉24-26行assert试一下
