### ISSUE TITLE
预测字符的速度与文档中宣称的不一致

### ISSUE THREAD

**Issue by YulongXia** [ymcui/Chinese-LLaMA-Alpaca#215]
### 问前必查项目

- [ ] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ ] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

### 选择问题类型

基础模型：

- [ ] LLaMA
- [x] Alpaca

问题类型：
- [ ] 下载问题
- [ ] 模型转换和合并问题
- [ ] 模型推理问题（🤗 transformers）
- [ ] 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
- [x] 效果问题
- [ ] 其他问题

### 详细描述问题
CPU是Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
我使用llama.cpp使用q4_0参数量化了llama-7b和chinese_alpaca_lora-7b，在测试时的推理速度，开4线程，速度是299ms/token, 如下图
![image](https://user-images.githubusercontent.com/41560825/234814141-7d502f45-ac62-4cff-a52d-585e83685e9d.png)
达不到这里所说的速度，请问时怎么回事
![image](https://user-images.githubusercontent.com/41560825/234814610-05fe6dd2-4b7e-456d-bc3e-0482cf916263.png)
![image](https://user-images.githubusercontent.com/41560825/234814692-03633bf3-fe51-402b-a455-2c065193c538.png)

### 运行截图或log
$ ./main -m 7B-zh-models/7B/ggml-model-q4_0.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.3 -t 4
main: seed = 1682586033
llama.cpp: loading model from 7B-zh-models/7B/ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 49954
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =  59.11 KB
llama_model_load_internal: mem required  = 5896.99 MB (+ 1026.00 MB per state)
llama_init_from_file: kv self size  = 1024.00 MB

system_info: n_threads = 4 / 56 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
main: interactive mode on.
Reverse prompt: '### Instruction:

'
sampling: temp = 0.200000, top_k = 40, top_p = 0.950000, repeat_last_n = 64, repeat_penalty = 1.300000
generate: n_ctx = 2048, n_batch = 512, n_predict = 256, n_keep = 21

== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - If you want to submit another line, end your input in '\'.

 Below is an instruction that describes a task. Write a response that appropriately completes the request.
> 请介绍一下北京
北京是中国的首都，也是一个历史悠久、文化底蕴深厚的城市。它拥有许多著名的景点和历史建筑，如故宫博物院、天安门广场、颐和园等。此外，北京还是中国最大的城市之一，有着丰富的商业活动和现代化的发展趋势。
> ^C

llama_print_timings:        load time =  8234.30 ms
llama_print_timings:      sample time =    97.49 ms /    60 runs   (    1.62 ms per run)
llama_print_timings: prompt eval time = 12867.45 ms /    43 tokens (  299.24 ms per token)
llama_print_timings:        eval time = 23143.38 ms /    60 runs   (  385.72 ms per run)
llama_print_timings:       total time = 56133.66 ms

**Comment by ymcui** [comment]
你仔细看一下，那上面写的测试配置是M1 Max。本身量化计算就依赖一些CPU的算子。llama.cpp是针对Apple Silicon优化过的。

**Comment by YulongXia** [comment]
其实也我也注意到测试环境是M1 Max，但我没想到会差这么多

**Comment by ymcui** [comment]
> 其实也我也注意到测试环境是M1 Max，但我没想到会差这么多

😂 这我们就控制不了了，你可以尝试增加-t参数到物理核心临近上限值。

**Comment by YulongXia** [comment]
好的，多谢

**Comment by YulongXia** [comment]
llama_print_timings: load time = 8234.30 ms
llama_print_timings: sample time = 97.49 ms / 60 runs ( 1.62 ms per run)
llama_print_timings: prompt eval time = 12867.45 ms / 43 tokens ( 299.24 ms per token)
llama_print_timings: eval time = 23143.38 ms / 60 runs ( 385.72 ms per run)
llama_print_timings: total time = 56133.66 ms
@ymcui 您好，我想问一下，prompt eval time和eval time这俩时间分别指什么时间？

**Comment by ymcui** [comment]
```
    int32_t n_sample = 0; // number of tokens sampled
    int32_t n_eval   = 0; // number of eval calls
    int32_t n_p_eval = 0; // number of tokens in eval calls for the prompt (with batch size > 1)
```
https://github.com/ggerganov/llama.cpp/blob/b9fd7eee57df101d4a3e3eabc9fd6c2cb13c9ca1/llama.cpp#L214

根据源代码，看似一个是计算prompt处理时间，另一个是eval（输出）时间。不过eval time的单位是runs，所以可能和batch size有关。具体的还请自行去llama.cpp查找相关信息。
