### ISSUE TITLE
关于输出答案的速度和正确性的问题

### ISSUE THREAD

**Issue by wyzhhhh** [ymcui/Chinese-LLaMA-Alpaca#217]
问题如下：

1.我是使用llama.cpp部署的，但是发现生成答案的速度很慢，有看到说是因为llama.cpp无法调用GPU，想请问该如何加快回答速度呢？
2.在输入promt时，如果使用输入法输入中文则会出现乱码，但是使用复制粘贴则可以正常输出答案，这是什么原因呢？
3.输出的答案有时是中文有时是英文，有时中英结合是什么原因呢？该如何解决。

### 必查项目

- [√ ] 问题类型：**（只保留你要问的）**
  - 效果问题
  - 其他问题
- [ ] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ ] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案

**Comment by ymcui** [comment]
1）现在llama.cpp支持gpu了，具体你可以去llama.cpp项目里看看。如果还是用cpu的话，-t参数可以增加线程（但不要超过机器上限）
2）建议你贴一些log出来，如果是windows下的问题，你看一下[FAQ](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题#问题6windows下模型无法理解中文生成速度很慢等问题)
3）同上，你贴一些例子出来，否则很难判断。
