### ISSUE TITLE
合并和转化后的模型能否在不同架构的处理器上混用？

### ISSUE THREAD

**Issue by PJ-568** [ymcui/Chinese-LLaMA-Alpaca#221]
### 问题

*合并和转化后的模型能否在不同架构的处理器上混用？性能等是否会受影响？*
（确实，我应该发在llama.cpp的issue）

### 实验

（更新）我已经成功在Termux(armv8)内运行在AMD处理器合并转换后的Chinese-Alpaca-7B-q4_1。性能还说的过去，效果似乎相对较差（？）。
![Screenshot_20230428_152607](https://user-images.githubusercontent.com/63788100/235084053-4f589910-4813-48b3-8023-c530a6288037.jpg)

### 涉及项目

- Alpaca 模型；
- 模型量化和部署问题（llama.cpp）
  - 效果问题
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。

**Comment by ymcui** [comment]
这个是llama.cpp框架决定的，正常情况下效果不会和桌面机有太大差别。
你可以按同一套参数在桌面机上进行测试对比。
