### ISSUE TITLE
关于prompt生成

### ISSUE THREAD

**Issue by zixuxu000** [ymcui/Chinese-LLaMA-Alpaca#226]
crawl_prompt最后生成的内容只包含input和output两个部分，请问instruction是以什么标准从input里分割出来的？

**Comment by ymcui** [comment]
我们在训练的时候把instruction+input合并为模型输入了，所以爬取脚本中的input就是对应我们的模型输入。

**Comment by zixuxu000** [comment]
> 我们在训练的时候把instruction+input合并为模型输入了，所以爬取脚本中的input就是对应我们的模型输入。

感谢回复，我知道这一点，
在用chatgpt生成原始数据时，只有input一个内容
但是你们提供的json,经过清洗的数据包含instruction和input两部分，请问是以什么样的标准分割的呢？
