### ISSUE TITLE
用text generation webui，但输入内容和输出内容一样，没有干活

### ISSUE THREAD

**Issue by heiheiheibj** [ymcui/Chinese-LLaMA-Alpaca#229]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。提问时删除上面这两行。请只保留符合的选项，删掉其他。*

### 详细描述问题

用text generation webui，输入内容后点生成按钮，右边的结果栏的内容，和输入的内容一样。

### 运行截图或log
![微信截图_20230430232007](https://user-images.githubusercontent.com/6910198/235361596-77412652-a6e1-4a47-9411-7e4d18987579.png)

### 必查项目

- [ ] 哪个模型的问题： Alpaca **（只保留你要问的）**
- [ ] 问题类型：**（只保留你要问的）**
  - 效果问题

**Comment by airaria** [comment]
指令需要放在模版里, 见 #156

**Comment by heiheiheibj** [comment]
我按这个回复中的DEMO写，还是一样原样输出。
麻烦指点一下，非常感谢
![微信截图_20230430235100](https://user-images.githubusercontent.com/6910198/235362947-2d06e733-3405-4ea0-9a02-0dd1ecb01072.png)

**Comment by iMountTai** [comment]
应该是还没有生成输出，可以看一下终端是否有报错或其他输出提示

**Comment by heiheiheibj** [comment]
感谢，是模型问题，重下个就好了
回答让我乐坏了
![微信图片_20230502232859](https://user-images.githubusercontent.com/6910198/235713200-20c7fa0c-ab59-40f5-b5cd-b410e84cae2e.png)
