### ISSUE TITLE
模型生成后无法加载：tensor 'tok_embeddings.weight' has wrong size in model file

### ISSUE THREAD

**Issue by lin-lai** [ymcui/Chinese-LLaMA-Alpaca#23]
这是提示错误，tensor 'tok_embeddings.weight' has wrong size in model file。
我检查了生成全量模型权重pth的sha256，和给出的sha256一致。
lora模型是alpaca
运行环境：win10,python3.10
llamacpp项目为最新版
llama模型为7B

这是完整的错误信息：
![图片](https://user-images.githubusercontent.com/71369414/229273577-4c934594-c9a8-4ee1-a050-9f616f2f9f57.png)

**Comment by airaria** [comment]
词表大小显示的还是32000。建议确认一下量化那一步用的到tokenizer（zh-models/tokenizer.model)是否是Chinese-alpaca模型对应的tokenizer?
```
llama.cpp/zh-models/
   - 7B/
     - consolidated.00.pth
     - params.json
   - tokenizer.model
```

**Comment by lin-lai** [comment]
感谢感谢，成功运行出来了，就是tokenizer.model的问题，我没替换掉

**Comment by agilests** [comment]
![image](https://user-images.githubusercontent.com/9177953/229350661-a749ed05-11de-4427-94d1-c441e530d155.png)
![image](https://user-images.githubusercontent.com/9177953/229350760-20333c90-84db-43a6-aa1a-04067cbd411f.png)
我已经替换了tokenizer.model. 此表大小看上去也是对的. 还是同样的错误.

**Comment by airaria** [comment]
> ![image](https://user-images.githubusercontent.com/9177953/229350661-a749ed05-11de-4427-94d1-c441e530d155.png)
> ![image](https://user-images.githubusercontent.com/9177953/229350760-20333c90-84db-43a6-aa1a-04067cbd411f.png)
> 我已经替换了tokenizer.model. 此表大小看上去也是对的. 还是同样的错误.

加载的是Alpaca吗？Alpaca的词表大小是49954
