### ISSUE TITLE
请问支持多卡训练吗

### ISSUE THREAD

**Issue by YSLLYW** [ymcui/Chinese-LLaMA-Alpaca#231]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。提问时删除上面这两行。请只保留符合的选项，删掉其他。*

### 详细描述问题

*请尽量具体地描述您遇到的问题。这将有助于我们更快速地定位问题所在。*

### 运行截图或log

*（如有必要）请提供文本log或者运行截图，以便我们更好地了解问题详情。*

### 必查项目

- [ ] 哪个模型的问题：LLaMA / Alpaca **（只保留你要问的）**
- [ ] 问题类型：**（只保留你要问的）**
  - 下载问题
  - 模型转换和合并
  - 模型推理问题（🤗 transformers）
  - 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
  - 效果问题
  - 其他问题
- [ ] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ ] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by iMountTai** [comment]
单机多卡或者多机多卡都支持的

**Comment by wangjvjie** [comment]
> 单机多卡或者多机多卡都支持的

我训练的时候为什么只用了第一张卡呢，我有两张卡，并且torch的gpu数量也是正常的2

**Comment by zzx16045223** [comment]
> 单机多卡或者多机多卡都支持的

请问这个怎么用？
这是我的预训练脚本
lr=2e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/zzx/Chinese-LLaMA-Alpaca/model/merge_chinese_alpaca_plus_13b
chinese_tokenizer_path=/zzx/Chinese-LLaMA-Alpaca/model/merge_chinese_alpaca_plus_13b
dataset_dir=/zzx/Chinese-LLaMA-Alpaca/data
data_cache=/zzx/Chinese-LLaMA-Alpaca/data/data_tmp
per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=10  # 默认100
gradient_accumulation_steps=1
output_dir=/zzx/Chinese-LLaMA-Alpaca/output

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 8 run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --seed $RANDOM \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 500 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --block_size 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --ddp_find_unused_parameters False



会出现这个错误
ARNING:torch.distributed.elastic.multiprocessing.api:Sending process 62525 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 62526 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 62528 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 62529 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 62530 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 62532 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 2 (pid: 62527) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File
