### ISSUE TITLE
很棒的项目，成功应用了，但是当我输入比较长的问题的时候，会报错说”内存不足“？

### ISSUE THREAD

**Issue by garvinzhang** [ymcui/Chinese-LLaMA-Alpaca#236]
![445081683170212_ pic_hd](https://user-images.githubusercontent.com/110436710/236106391-e6bfccbf-c70d-4283-b8b4-2f4e5eb8fd52.jpg)
<img width="717" alt="image" src="https://user-images.githubusercontent.com/110436710/236106432-f3c2b181-c130-44aa-982f-ade0f63486ff.png">

ggml_new_tensor_impl: not enough space in the context's memory pool (needed 819409712, available 805306368)

[1]    52017 segmentation fault  ./main -m zh-models/7B/ggml-model-q4_0.bin --color -f prompts/alpaca.txt -ins

**Comment by ymcui** [comment]
看到你现在的`n_batch=512`，batch size 可以调小一些，其实对速度没有什么影响。
以下是llama.cpp官方的解释：
```
-   `-b N, --batch_size N`: Set the batch size for prompt processing (default: 512). This large batch size benefits users who have BLAS installed and enabled it during the build. If you don't have BLAS enabled ("BLAS=0"), you can use a smaller number, such as 8, to see the prompt progress as it's evaluated in some situations.
```

**Comment by garvinzhang** [comment]
> 看到你现在的`n_batch=512`，batch size 可以调小一些，其实对速度没有什么影响。 以下是llama.cpp官方的解释：
> 
> ```
> `-b N, --batch_size N`: Set the batch size for prompt processing (default: 512).  
> This large batch size benefits users who have BLAS installed and enabled it during the build. 
> If you don't have BLAS enabled ("BLAS=0"), you can use a smaller number, such as 8, 
> to see the prompt progress as it's evaluated in some situations.
> ```

哇，非常感谢！！！现在可以了。想不到这么快就有回复了！！！
