### ISSUE TITLE
How to train 20k Chinese Tokenizer by myself?

### ISSUE THREAD

**Issue by AceCHQ** [ymcui/Chinese-LLaMA-Alpaca#237]
Thank you for using the Issue submission template. Please follow the steps below to provide relevant information. We will prioritize issues with relatively complete information. Your cooperation is appreciated.

*Hint: Fill in the [ ] with an x to mark it as checked. Delete any option that is not related to this issue.

### Describe the issue in detail

Hello, I want to train the 20k Chinese Tokenizer by myself. Can you tell me how to train with SentencePiece and which data should I use? Thank you 

### Provide a screenshot or log of the issue

*(If necessary) Please provide a text log or screenshot to help us better understand the issue details.*

**Comment by airaria** [comment]
You can use any public Chinese corpus (Chinese Wiki, WudaoCorpus, etc.) or for training the tokenizer.

The detailed usages and the instructions for training a SentencePiece tokenizer can be found at https://github.com/google/sentencepiece
