### ISSUE TITLE
期待解答！感谢！ 调低batch 参数之后，对话容易“中断、不连续”？而且回车多次后会有不相关的对话出现？。调低batch的原因见issue：236. 

### ISSUE THREAD

**Issue by garvinzhang** [ymcui/Chinese-LLaMA-Alpaca#238]
调低batch参数的原因：https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/236

对话中断、不连续：
<img width="730" alt="image" src="https://user-images.githubusercontent.com/110436710/236115930-fdd1780f-117e-4db7-9de7-891173ca7da9.png">

不相关的对话出现：“祝贺新冠疫苗接种工作顺利。。。。”
<img width="730" alt="image" src="https://user-images.githubusercontent.com/110436710/236116009-90165419-fe8e-49b1-b5e1-076d7ce8c569.png">

最后：这种问题的出现可能是训练数据集导致的吗？
![image](https://user-images.githubusercontent.com/110436710/236116266-00d7b1ec-d10c-4893-a916-5da101c12ce9.png)

input是空，output却是有值的？因此，我直接回车会导致出现这样的无关对话？
期待解答，感谢！

**Comment by garvinzhang** [comment]
https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/data/alpaca_data_zh_51k.json
训练的数据集好像是这个？

**Comment by ymcui** [comment]
合理怀疑是你的输入中包含回车导致的。
需要注意，输入文本如果需要换行， 是需要用`\`符号进行分割的。
```
 - If you want to submit another line, end your input in '\'.
```
