### ISSUE TITLE
请问run_clm_pt_with_peft中lm_datasets的目录结构是什么～？

### ISSUE THREAD

**Issue by Wisteria98** [ymcui/Chinese-LLaMA-Alpaca#239]
请问run_clm_pt_with_peft中lm_datasets的目录结构是什么～？
想自己训练一下，我直接使用alpaca_data_zh_51k.json类似的文件放在data中，但是运行显示：
'list' object has no attribute 'train_test_split'

**Comment by airaria** [comment]
这是预训练脚本，所以是使用纯文本文件，而不是alpaca的json格式。
目录下包含一个或多个纯文本文件，以txt结尾，类似这样：
```bash
lm_datasets\
  001.txt
  002.txt
  003.txt 
...
```

**Comment by Wisteria98** [comment]
> 这是预训练脚本，所以是使用纯文本文件，而不是alpaca的json格式。 目录下包含一个或多个纯文本文件，以txt结尾，类似这样：
> 
> ```shell
> lm_datasets\
>   001.txt
>   002.txt
>   003.txt 
> ...
> ```

谢谢答复～还想请问一下两个问题如果是希望训练特定领域模型，是不是

**Comment by Wisteria98** [comment]
> 这是预训练脚本，所以是使用纯文本文件，而不是alpaca的json格式。 目录下包含一个或多个纯文本文件，以txt结尾，类似这样：
> 
> ```shell
> lm_datasets\
>   001.txt
>   002.txt
>   003.txt 
> ...
> ```

谢谢答复～还想请问一下两个问题如果是希望训练特定领域模型

**Comment by Wisteria98** [comment]
> 这是预训练脚本，所以是使用纯文本文件，而不是alpaca的json格式。 目录下包含一个或多个纯文本文件，以txt结尾，类似这样：
> 
> ```shell
> lm_datasets\
>   001.txt
>   002.txt
>   003.txt 
> ...
> ```

谢谢答复～还想请问一下两个问题
1. 如果是希望训练特定领域模型，是不是可以通过预训练的方式就可以得到微调的模型～？指令精调这一步不一定需要对吧？
2. 请问lm_datasets里面txt的文件也是遵循这种结构吧～？感谢🙏
 {
    "instruction": "",
    "input": "",
    "output": ""
  }

**Comment by airaria** [comment]
预训练和精调是分开的。
如果只想在中文上做指令模型，除非觉得Chinese-LLaMA训练还不充分，一般来说不需要预训练了

1. 如果你希望得到的模型还是和alpaca一样，可以响应人类指令，那么需要指令精调。预训练这一步反而是不需要的。
2. txt文件内容是**纯文本**，一行是一句话或一个段落都可以，不包含任何格式（本身也不是用于做指令精调的），就是普通的文本。

**Comment by Wisteria98** [comment]
> 预训练和精调是分开的。 如果只想在中文上做指令模型，除非觉得Chinese-LLaMA训练还不充分，一般来说不需要预训练了
> 
> 1. 如果你希望得到的模型还是和alpaca一样，可以响应人类指令，那么必须指令精调。
> 2. txt文件内容是**纯文本**，一行是一句话或一个段落都可以，不包含任何格式（本身也不是用于做指令精调的），就是普通的文本。

您太给力了！请问精调部分该如何构建数据集～？我看您文章里面写的是参考[Stanford Alpaca](https://github.com/tatsu-lab/stanford_alpaca)对照finetune部分代码，文件目录应该是如下：
├── 7B
│   ├── checklist.chk
│   ├── consolidated.00.pth
│   └── params.json
├── tokenizer.model
└── tokenizer_checklist.chk
但是我用融合后的模型没用tokenizer_checklist.chk，请问合这个有影响吗～？

**Comment by airaria** [comment]
> > 预训练和精调是分开的。 如果只想在中文上做指令模型，除非觉得Chinese-LLaMA训练还不充分，一般来说不需要预训练了
> > 
> > 1. 如果你希望得到的模型还是和alpaca一样，可以响应人类指令，那么必须指令精调。
> > 2. txt文件内容是**纯文本**，一行是一句话或一个段落都可以，不包含任何格式（本身也不是用于做指令精调的），就是普通的文本。
> 
> 您太给力了！请问精调部分该如何构建数据集～？我看您文章里面写的是参考[Stanford Alpaca](https://github.com/tatsu-lab/stanford_alpaca)对照finetune部分代码，文件目录应该是如下： ├── 7B │ ├── checklist.chk │ ├── consolidated.00.pth │ └── params.json ├── tokenizer.model └── tokenizer_checklist.chk 但是我用融合后的模型没用tokenizer_checklist.chk，请问合这个有影响吗～？

没有tokenizer_checklist.chk不影响

**Comment by zzisbeauty** [comment]
我有个问题请教一下老师：如果我使用了HF格式的中文Alpaca/Alpaca-Plus+中文Alpaca的tokenizer（49954）进行预训练，我是该准备指令数据还是txt数据，我在wiki-预训练脚本中看到追加训练是支持在指令模型上继续训练的，但是我没搞懂在这样的指令模型基础上准备txt数据继续追加训练是否合理。  如果合理，是不是就意味着，即使我在指令模型上做了追加训练后，依然再可以继续在预训练的基础上继续执行进一步的指令微调。    期待得到老师的答复，感恩。

**Comment by ymcui** [comment]
如果在Alpaca系列模型上继续预训练，那么可能会丢失Alpaca模型原有的一些指令跟随和聊天能力。有条件的还是建议在Alpaca继续做指令精调，而不是增量预训练。因为你的提问与本issue关联度较低，如有其他问题，请新建issue。 @zzisbeauty

**Comment by zzisbeauty** [comment]
> 

感恩老师。 我已经清楚了。我确实打算只采用追加数据进行SFT，没打算在指令模型上进行再训练。只是看到了wiki-预训练脚本这个页面的表格中有支持这个模型，就觉得这个训练方式很奇怪就来请教一下。因此通过老师的答复我知道只是表格中列出来了，但是是不建议这样这样子做的。

- 另外想说的是：wiki中的 alpaca 的plus 和 Chinese Plus 这两个plus让我产生了深深的疑惑。我在参考wiki进行复现的时候，这俩plus我一时没有搞清楚。 其实Chinese-LLaMa这个Plus可以取消，因为仅有一个基于120G的语料的Chinese-LLaMa是被使用的，它也标注一个plus是没必要的，否则wiki里出现的plus 实在是会和alpaca plus 造成误解。

**Comment by zzisbeauty** [comment]
感恩老师的回答。



我在项目中提了一个新的issue的问题。这个问题好像不是代码的问题。是运行配置的问题。是我太菜了，但是我一时没办法解决。我希望能得到老师的帮助，能让我先快速的运行起来。我之后还会再去仔细学习。


感恩老师，期待得到老师的帮助与答复。

                       
原始邮件
                       
                     

发件人："Yiming Cui"< ***@***.*** &gt;;

发件时间：2023/8/28 16:58

收件人："ymcui/Chinese-LLaMA-Alpaca"< ***@***.*** &gt;;

抄送人："zzisbeauty"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

主题：Re: [ymcui/Chinese-LLaMA-Alpaca] 请问run_clm_pt_with_peft中lm_datasets的目录结构是什么～？ (Issue #239)




 
如果在Alpaca系列模型上继续预训练，那么可能会丢失Alpaca模型原有的一些指令跟随和聊天能力。有条件的还是建议在Alpaca继续做指令精调，而不是增量预训练。因为你的提问与本issue关联度较低，如有其他问题，请新建issue。 @zzisbeauty
