### ISSUE TITLE
后续会规划做python语言的API调用方式吗？

### ISSUE THREAD

**Issue by garvinzhang** [ymcui/Chinese-LLaMA-Alpaca#241]
目前好像只能通过在控制台终端执行
`./main -m zh-models/7B/ggml-model-q4_0.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.3`进入会话模式。

如果我想用python搭建一个服务，如何用python语言调用输入输出的接口模型呢？

**Comment by ymcui** [comment]
建议你参考其他llama API化的项目（github自行查找）。
我们的模型合并转换之后，原则上与原版llama没什么区别了（除了词表大小不一样）。

**Comment by honglvagan** [comment]
兄,你用的是 7b plus 吗?能不能..?
