### ISSUE TITLE
请问该中文模型如何在https://github.com/cocktailpeanut/dalai加载使用呢

### ISSUE THREAD

**Issue by caopeng000** [ymcui/Chinese-LLaMA-Alpaca#25]

**Comment by iMountTai** [comment]
最新代码已支持webui,建议参考[使用text-generation-webui搭建界面](https://github.com/ymcui/Chinese-LLaMA-Alpaca#%E4%BD%BF%E7%94%A8text-generation-webui%E6%90%AD%E5%BB%BA%E7%95%8C%E9%9D%A2)方式加载模型使用
