### ISSUE TITLE
Alpaca-Plus-7B 成功运行，但多轮对话中对话机器人未能按已有上下文进行问答

### ISSUE THREAD

**Issue by TianYangCai** [ymcui/Chinese-LLaMA-Alpaca#250]
- [x] 哪个模型的问题：Chinese-Alpaca-Plus-7B
- [x] 问题类型：
  - 效果问题
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案

### 问题概述
已按照教程完成如下步骤：
1. 转换官方LLaMa 7B模型为hf格式
2. 合并LLaMa_hf 、Alpaca Plus 、 LLaMa plus模型
3. 成功运行inference_hf.py

按照README.md实例进行如下图所示问答，对话机器人未能展现出上下文问答能力。请问可能是哪一个环节出错了？
<img width="1162" alt="截屏2023-05-05 19 30 24" src="https://user-images.githubusercontent.com/38423835/236448338-e8a94cb7-5cd5-4d9d-8edc-e49e7c9a05fe.png">
<img width="1153" alt="截屏2023-05-05 19 37 02" src="https://user-images.githubusercontent.com/38423835/236448366-be07ca88-a4f4-478a-a4f5-c6a3772de01e.png">

**Comment by iMountTai** [comment]
--interactive以交互方式启动，以便进行多次单轮问答（病变不是llama.cpp中的上下文对话）[transformers推理](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E4%BD%BF%E7%94%A8Transformers%E6%8E%A8%E7%90%86)

**Comment by airaria** [comment]
inference_hf.py不能做多轮对话。要体验多轮对话的话请用llama.cpp或llama chat

**Comment by kongbohu** [comment]
> --interactive以交互方式启动，以便进行多次单轮问答（病变不是llama.cpp中的上下文对话）[transformers推理](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E4%BD%BF%E7%94%A8Transformers%E6%8E%A8%E7%90%86)

借地请教一下，训练“多轮”会话时数据格式是怎样的？是下面的1）还是2）？
还是说没有“多轮会话”，每个样本数据只有一轮会话？（我看Alpaca相关训练的代码里，好像就只是针对的一轮会话）

1）Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
AAAAAA
### Response:
BBBBBB
### Instruction:
CCCCC
### Response:
DDDDD

2）Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
AAAAAA
### Response:
BBBBBB
Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
CCCCC
### Response:
DDDDD

**Comment by TianYangCai** [comment]
已经实现使用llama.cpp运行Alpaca-Plus-7B，具备多轮对话能力。最后再请教一下，有没有大佬实现通过gpu推理运算llama.cpp的，目前看下来教程中只支持cpu的方式。
