### ISSUE TITLE
文中几个模型的疑问。

### ISSUE THREAD

**Issue by g558800** [ymcui/Chinese-LLaMA-Alpaca#251]
以文中所说的模型为例提个问，Chinese-LLaMA-Plus-7B ，Chinese-Alpaca-Plus-7B，原版LLaMA模型，这三种模型是什么关系？我的理解是Chinese-LLaMA-Plus-7B+训练差量=Chinese-Alpaca-Plus-7B，不知理解是否对路，而且又跟原版LLaMA模型是什么关系呢？

**Comment by airaria** [comment]
原版LLaMA + Chinese-LLaMA-Plus-LoRA-7B = Chinese-LLaMA-Plus-7B
Chinese-LLaMA-Plus-7B +  Chinese-Alpaca-Plus-LoRA-7B  = Chinese-Alpaca-Plus-7B

**Comment by g558800** [comment]
谢谢。对比了15分钟，最后发现还是要自助合并最终模型。
