### ISSUE TITLE
关于预训练脚本

### ISSUE THREAD

**Issue by extrame** [ymcui/Chinese-LLaMA-Alpaca#252]
请教一下，目前的预训练脚本，我看是通过text模式加载的通用中文语料，是因为只做中文化的原因么？

那我要是想做领域问答的lora模型，是不是不能用text，要把语料处理成instruction，input，output分栏模式，再用json或者csv去load？

**Comment by airaria** [comment]
> 请教一下，目前的预训练脚本，我看是通过text模式加载的通用中文语料，是因为只做中文化的原因么？
>

利用脚本加载什么语言的语言都可以。既然是为了给LLaMA增加中文能力，所以预训练时当然用中文语料。

> 那我要是想做领域问答的lora模型，是不是不能用text，要把语料处理成instruction，input，output分栏模式，再用json或者csv去load？

用datasets可以load json格式，datasets.load_dataset中指定json格式即可。不过加载后还需你自己处理一下指令数据格式

**Comment by extrame** [comment]
第一个问题，我是想问为什么Chinese-LLaMA-Alpaca训练用的语料并没有按问答形式组织？是不是因为只做中文化，所以问答逻辑不重要？

第二个关于JSON这个也是想问语料的准备，我是想问是不是如果我想做领域问答，是不是就不能按Chinese-LLaMA-Alpaca的逻辑喂通用语料，而应该严格按问答形式准备，以便生成模型具备更好的问答能力？

**Comment by airaria** [comment]
> 第一个问题，我是想问为什么Chinese-LLaMA-Alpaca训练用的语料并没有按问答形式组织？是不是因为只做中文化，所以问答逻辑不重要？

预训练数据用的是自由格式的文本，不需要按问答形式组织。只有SFT的数据需要按问答形式组织。


> 第二个关于JSON这个也是想问语料的准备，我是想问是不是如果我想做领域问答，是不是就不能按Chinese-LLaMA-Alpaca的逻辑喂通用语料，而应该严格按问答形式准备，以便生成模型具备更好的问答能力？

逻辑同上，做问答应该严格按问答形式准备。

**Comment by extrame** [comment]
好的，谢谢
