### ISSUE TITLE
关于中文预训练阶段的Loss情况咨询

### ISSUE THREAD

**Issue by Haijunlv** [ymcui/Chinese-LLaMA-Alpaca#256]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。提问时删除上面这两行。请只保留符合的选项，删掉其他。*

### 详细描述问题

*请尽量具体地描述您遇到的问题。这将有助于我们更快速地定位问题所在。*

请教下Chinese-LLaMA-7B, Chinese-LLaMA-Plus-7B, Chinese-LLaMA-13B 在pretrain阶段最终达到的loss大概是多少？
我们参考Chinese-LLaMA-7B的流程，做了stage2的全量微调预训练，最终训练loss在1.95左右，预训练语料规模在200G左右。
不太确定这个loss是不是符合预期？  
比如如下语料
`"中国文化和旅游部3日发布消息称，今年“五一”假期，文化和旅游行业复苏势头强劲，全国假日市场平稳有序，全国国内旅游出游合计2.74亿人次，超过2019年同期水平。多家在线旅游平台发布的“五一”出游报告也显示，此次假期多项数据同比暴增，甚至创下“五一”历史峰值。“中国公共假期带来后疫情时代旅游热潮”，美国哥伦比亚广播公司称，中国旅游业完全抓住本轮商机，为本国经济注入新活力的同时，还提振消费者的信心。彭博社在题为“中国五一假期正经历旅游业大复苏”的文章中称，经过三年的新冠疫情，中国消费群体积攒了强劲的购买力，此番中国旅游业的繁荣正受到国际密切关注。《华尔街日报》称，中国经济回暖对今年全球经济增长显得举足轻重，随着天气变暖，这一势头有望延续。"`

### 运行截图或log

*（如有必要）请提供文本log或者运行截图，以便我们更好地了解问题详情。*

### 必查项目

- [ x ] 哪个模型的问题：LLaMA  **（只保留你要问的）**
- [ x ] 问题类型：**（只保留你要问的）**
  - 其他问题
- [x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by alanxmay** [comment]
你好，我也有类似的问题，请教下你的loss起始值是多少呢？我是从8.0开始下降

**Comment by Haijunlv** [comment]
> 你好，我也有类似的问题，请教下你的loss起始值是多少呢？我是从8.0开始下降

我的也是， loss从8下降到1.95。

**Comment by GGGGGGXY** [comment]
我自己在继续训练的时候是从3开始下降到1.9左右开始缓慢下降了

**Comment by airaria** [comment]
这个loss正常，而且已经比较低了。

**Comment by airaria** [comment]
> 我自己在继续训练的时候是从3开始下降到1.9左右开始缓慢下降了

继续训练的话从3左右开始比较符合预期。

**Comment by Haijunlv** [comment]
> > 我自己在继续训练的时候是从3开始下降到1.9左右开始缓慢下降了
> 
> 继续训练的话从3左右开始比较符合预期。

loss起点3这个再请教下。
我们复现的继续训练没有走stage1, 直接上stage2, 一起训练embedding和全量权重。 
在训练前我用英文语料过了下，loss起点在2左右，大致判断中文词表及中文embedding的加入并没影响到模型对英文的理解。
然后直接上stage2， 在中文语料上继续训练，此时的Loss起点是8。  
这个loss起点 您觉得有问题吗？

考虑到chinese llama-13B 也是直接上stage2, 想再确认下13B在stage2上的loss起点是多少？

**Comment by GGGGGGXY** [comment]
> > > 我自己在继续训练的时候是从3开始下降到1.9左右开始缓慢下降了
> > 
> > 
> > 继续训练的话从3左右开始比较符合预期。
> 
> loss起点3这个再请教下。 我们复现的继续训练没有走stage1, 直接上stage2, 一起训练embedding和全量权重。 在训练前我用英文语料过了下，loss起点在2左右，大致判断中文词表及中文embedding的加入并没影响到模型对英文的理解。 然后直接上stage2， 在中文语料上继续训练，此时的Loss起点是8。 这个loss起点 您觉得有问题吗？
> 
> 考虑到chinese llama-13B 也是直接上stage2, 想再确认下13B在stage2上的loss起点是多少？

stage1或者stage2对loss不会有影响，  如果在中文上是从8开始的话是有问题的，你可以在训练开始前先走一遍推理，确保模型权重是没问题的再试试，  如果loss还有问题很有可能是数据的问题导致的

**Comment by yang9112** [comment]
请问stage1进行预训练的话，使用的是哪一个版本的预训练代码？是这个吗？run_clm_pt_with_peft.py

**Comment by airaria** [comment]
> 请问stage1进行预训练的话，使用的是哪一个版本的预训练代码？是这个吗？run_clm_pt_with_peft.py

需要基于run_clm_pt_with_peft.py修改，删掉peft相关代码，同时设置仅embedding层（或再包含lm_head）可训练。

**Comment by Haijunlv** [comment]
> > > > 我自己在继续训练的时候是从3开始下降到1.9左右开始缓慢下降了
> > > 
> > > 
> > > 继续训练的话从3左右开始比较符合预期。
> > 
> > 
> > loss起点3这个再请教下。 我们复现的继续训练没有走stage1, 直接上stage2, 一起训练embedding和全量权重。 在训练前我用英文语料过了下，loss起点在2左右，大致判断中文词表及中文embedding的加入并没影响到模型对英文的理解。 然后直接上stage2， 在中文语料上继续训练，此时的Loss起点是8。 这个loss起点 您觉得有问题吗？
> > 考虑到chinese llama-13B 也是直接上stage2, 想再确认下13B在stage2上的loss起点是多少？
> 
> stage1或者stage2对loss不会有影响， 如果在中文上是从8开始的话是有问题的，你可以在训练开始前先走一遍推理，确保模型权重是没问题的再试试， 如果loss还有问题很有可能是数据的问题导致的

再请教下，我参照论文对embedding的处理方案， 
1. 在原来的英文 input embedding上concat了支持中文的随机初始化的embedding。 
2. 在原来的英文 output embedding上为了支持原来的英文预测结果尽量准，concat了支持中文的全零初始化的embedding。

按照这样的embedding支持逻辑，直接在原始llama-7b的结构上修改支持中文后，权重加载后，
1、对一条英文语句的loss是2.0， 证明支持中文后没有影响到英文的预测能力。
2、再对一条中文wiki2019的数据预测， loss是8.8。  说明支持中文后初始状态下没有任何中文预测能力。
所以我感觉在这个处理逻辑下loss是8.8是合理的。 所以怎么样的处理才能让初始的中文模型能在loss 3左右呢?

**Comment by yuemengrui** [comment]
> 请问stage1进行预训练的话，使用的是哪一个版本的预训练代码？是这个吗？run_clm_pt_with_peft.py

你好，请问您stage1训练成功了吗？我这边总是跑不起来，也没有什么详细的报错，WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 47156 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 47157 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 47160 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 47161 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 47155) of binary: /opt/conda/bin/python

**Comment by yang9112** [comment]
> 

看不出问题，我用的deepspeed可以跑。

**Comment by iMountTai** [comment]
> > 请问stage1进行预训练的话，使用的是哪一个版本的预训练代码？是这个吗？run_clm_pt_with_peft.py
> 
> 你好，请问您stage1训练成功了吗？我这边总是跑不起来，也没有什么详细的报错，WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 47156 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 47157 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 47160 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 47161 closing signal SIGTERM ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 47155) of binary: /opt/conda/bin/python

这个问题一般是内存不足，导致模型未完全加载进来，还请关注一下内存(非显存)的变化

**Comment by bytes-lost** [comment]
> 

请问你们最终的预训练模型生成效果如何呢？loss在1.95的情况下

**Comment by bytes-lost** [comment]
> 

@Haijunlv 
请问你们最终的预训练模型生成效果如何呢？loss在1.95的情况下

**Comment by foreverxujiahuan** [comment]
有人遇到过loss一开始就为0的情况吗

**Comment by Haijunlv** [comment]
> @Haijunlv
> 请问你们最终的预训练模型生成效果如何呢？loss在1.95的情况下

效果挺好，我们判断这个训练流程是合理的

**Comment by GengwangGitHub** [comment]
> > @Haijunlv
> > 请问你们最终的预训练模型生成效果如何呢？loss在1.95的情况下
> 
> 效果挺好，我们判断这个训练流程是合理的

请问训练的loss一直下降吗？有遇到loss下降过程中很快就涨起来的情况吗，如何处理的，谢谢

**Comment by yangjianxin1** [comment]
> > 你好，我也有类似的问题，请教下你的loss起始值是多少呢？我是从8.0开始下降
> 
> 我的也是， loss从8下降到1.95。

请教一下，你用lora增量预训练，loss从8下降到1.95这个过程是不是特别缓慢并且很久，几百步loss下降零点零零几。
因为我目前训练，遇到了这个现象，所以想请教一下 @Haijunlv @GGGGGGXY
