### ISSUE TITLE
text-generation-webui 的LoRA.py 更新了参数，原有部署教程无法使用报错

### ISSUE THREAD

**Issue by Gailun90** [ymcui/Chinese-LLaMA-Alpaca#259]
##： python3 server.py --model llama-7b-hf --lora chinese-alpaca-lora-7b --cpu
INFO:Gradio HTTP request redirected to localhost :)
bin /usr/local/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/usr/local/lib/python3.11/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
INFO:Loading llama-7b-hf...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:53<00:00, 26.61s/it]
INFO:Loaded the model in 53.70 seconds.
INFO:Applying the following LoRAs to llama-7b-hf: chinese-alpaca-lora-7b
Traceback (most recent call last):
  File "/Users/mklife/text-generation-webui/server.py", line 874, in <module>
    add_lora_to_model(shared.args.lora)
  File "/Users/mklife/text-generation-webui/modules/LoRA.py", line 43, in add_lora_to_model
    shared.model = PeftModel.from_pretrained(shared.model, Path(f"{shared.args.lora_dir}/{lora_name}"), **params)

NameError: name 'lora_name' is not defined. Did you mean: 'lora_names'?

**Comment by lzjever** [comment]
The only modification needed is to change the size of token embeddings. 
Just insert this line:
shared.model.resize_token_embeddings(len(shared. Tokenizer)) 

Do NOT replace the original line of code with the following:
shared. Model = PeftModel.from_pretrained(shared.model, Path(f"{shared.args.lora_dir}/{lora_name}"), **params)
