### ISSUE TITLE
合并完以后, 推理都有问题? 原始模型推理怎没有问题

### ISSUE THREAD

**Issue by ruanshudong** [ymcui/Chinese-LLaMA-Alpaca#260]
合并:
python ../Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py --base_model=../pyllama_data/7B_hf --lora_model=../chinese-llama-plus-lora-7b/,../chinese-alpaca-plus-lora-7b --output_type=huggingface --output_dir=merge_llama

执行推理: 
python inference_hf.py --base_model=merge_llama/ --interactive

load: merge_llama/
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.34s/it]
Vocab of the base model: 49954
Vocab of the tokenizer: 49954
Start inference with interactive mode.
Input:你是谁?
Response:  你是谁?

Input:为啥不行?
Response:  为啥不行?

Input:有问题啊?
Response:  有问题啊?

**Comment by airaria** [comment]
推理时添加--with_prompt:
```
python inference_hf.py --base_model=merge_llama/ --interactive --with_prompt
```

**Comment by ruanshudong** [comment]
嗯, 多谢, 看代码看到了
