### ISSUE TITLE
关于alpaca回答惜字如金的问题

### ISSUE THREAD

**Issue by kongbohu** [ymcui/Chinese-LLaMA-Alpaca#262]
### 详细描述问题

README中也介绍了当前alpaca模型的回答有些惜字如金，具体体验了一下确实如此
而在进行了60W条数据finetune后，结果回答得更短，我猜测原因是在于我这60W条数据都是长度在128以内的
刚刚完成了15W条512长度数据的finetune，发现回答果然更健谈了一些（虽然有些回答包含错误信息）

### Response: 三国时期是中国历史上非常重要的时期，它始于220年，结束于280年，期间经历了三国鼎立、三国割据、三国争霸等事件。下面是三国时期发生的一些重要事件：
1. 东汉灭亡：公元220年，东汉灭亡，三国时期开始。
2. 三方争霸：三国时期开始，魏国、蜀国、吴国分别占据了中国南北两面，形成了三国鼎立的局面。
3. 三国战争：三国时期，魏、蜀、吴三个政权之间的战争不断，最终导致了三国鼎立的局面。
4. 三国割据：三国时期，各个政权势力相对平衡，形成了三国割据的局面。
5. 三国争霸：三国之间的战争不断，最终导致了三国之间的长期和平和战争。
6. 三国互通：三国之间通过外交、文化、经济等交流，形成了三国互通的局面。
7. 三国文化：三国时期，各个政权文化相互交流，形成了三国文化的繁荣。
这些事件和现象在三国时期都发挥了重要的影响，是三国时期历史上的重要事件和进程。
### Response: 三国时期的重要战争有以下几个：
1. 赤壁之战：公元208年，三国战争爆发，蜀国、吴国和魏国分别在赤壁展开激烈的战斗，最终，蜀国和魏国联手击败了吴国，这场战斗最终决定了三国的局势。
2. 官渡之战：公元200年，三国时期的魏国和蜀国之间进行激烈的战争，最终，蜀国失败，魏国开始成为三国中的主要力量。
3. 夷陵之战：公元203年，三国时期的蜀国和魏国之间进行激烈的战争，最终，蜀国失败，魏国开始成为三国中的主要力量。
以上是三国时期的几个主要战争，它们在三国时期都发挥了重要的影响，是三国时期的重要事件和进程。
### Response: 近年来，野生动物保护已成为全球关注的热点话题之一。这篇文章将从野生动物的定义、保护意义以及现状等方面进行探讨。
首先，野生动物是指在自然界中存在的各种生物，包括哺乳动物、鸟类、爬行动物、两栖动物、鱼类等。野生动物在我们的日常生活中扮演着不可或缺的角色，如提供食物、维护生态平衡等。然而，由于人类的活动对其栖息地的破坏、捕杀等原因，野生动物物种数量已经不断减少，甚至濒临灭绝。
其次，野生动物保护的意义在于维护生态平衡。野生动物的存在对于维持自然界的生态平衡起着至关重要的作用。例如，一些食草动物帮助维持草原的生机，而一些食肉动物则帮助控制草原上的害虫。如果野生动物数量减少，就会导致整个生态系统的崩溃，从而影响到整个地球的生态系统。
最后，野生动物保护的现状也是非常严峻的。全球野生动物数量已经减少了约25%，其中，许多动物已经濒临灭绝，例如北极熊、大熊猫等。这种状况的主要原因是人类活动，如森林砍伐、非法狩猎等。因此，我们需要采取积极的措施来保护野生动物，包括制定相关政策、加强监管力度、加强宣传教育等。
以上是我的一份关于野生动物保护的文章，希望能够引起您的注意，我们需要共同努力，保护我们的宝贵自然资源。
### Response: 好的，以下是我更详细的介绍：
1. 野生动物：野生动物是指在自然界中存在的各种生物，包括哺乳动物、鸟类、爬行动物、两栖动物、鱼类等。
2. 野生动物保护的意义：野生动物保护的意义在于维护生态平衡。野生动物的存在对于维持自然界的生态平衡起着至关重要的作用。例如，一些食草动物帮助维持草原的生机，而一些食肉动物则帮助控制草原上的害虫。如果野生动物数量减少，就会导致整个生态系统的崩溃，从而影响到整个地球的生态系统。
3. 野生动物保护现状：全球野生动物数量已经减少了约25%，其中，许多动物已经濒临灭绝，例如北极熊、大熊猫等。这种状况的主要原因是人类活动，如森林砍伐、非法狩猎等。
4. 野生动物保护措施：我们可以采取积极的措施来保护野生动物，例如制定相关政策、加强监管力度、加强宣传教育等。具体的措施可以根据野生动物的种类和受威胁程度来确定，可以根据具体情况进行调整。
以上是我的更详细的介绍，希望可以对您有所帮助。
### Response: 近代中国的衰败，根本原因是中国文化的衰败和中国社会结构的结构性问题。
具体来说，近代中国文化的衰败，主要是由于外来文化的影响、民族意识的丧失、文化创新的缺乏等。这些问题导致了中国文化的退化，也使得中国社会缺乏创造力和创新精神，从而导致了中国社会的衰败和民族的弱化。
同时，中国社会结构的结构性问题，主要是由于中央集权的出现，以及封建的土地制度、宗法制度、家族制度、宗法文化等因素的结合，导致了中国社会的封闭和缺乏发展和进步的活力，而这些问题也对中国社会造成了长期的负面影响。
总的来说，近代中国文化的衰败和中国社会的结构性问题，是导致中国衰败的主要原因，这也是中国解决这些问题的基础。

### 必查项目

- [ X ] 哪个模型的问题： Alpaca 
- [ X ] 问题类型：
  - 其他问题
  是否可以请项目团队使用、或者偏向使用长语料对模型进行后续finetune，以提高模型回答质量？

**Comment by airaria** [comment]
是否尝试过了Plus模型？我们新发布的Alpaca-Plus 7B模型缓解了部分问题

**Comment by kongbohu** [comment]
> 是否尝试过了Plus模型？我们新发布的Alpaca-Plus 7B模型缓解了部分问题

恩，我就是用的最新的Alpaca-Plus-7B
