### ISSUE TITLE
我來自香港, 很喜歡這個項目, 請問將來會支援廣東話文字嗎?

### ISSUE THREAD

**Issue by taomanwai** [ymcui/Chinese-LLaMA-Alpaca#265]
又或者, 你們接受 廣東話文字支援相關的 PR 嗎?

BTW, 感謝!

**Comment by ymcui** [comment]
感谢对我们项目的关注。
由于我们并没有将训练文本强制转换为简体中文，所以训练语料中可能包含了一部分粤语以及繁体中文数据。
因此，模型可能会具备一小部分粤语和繁体中文的理解能力。但如果想要达到较好的效果，还需要针对性地加入更多的粤语和繁体中文数据进行训练。
虽然我们暂时没有计划在预训练阶段加入更多粤语以及繁体中文数据进行训练，但未来可能会以指令精调的形式增加对上述语言的理解能力。
