### ISSUE TITLE
评测模型生成效果不佳，是不是有什么设置错误的地方，使用transfomer加载alpaca_plus

### ISSUE THREAD

**Issue by expresschen** [ymcui/Chinese-LLaMA-Alpaca#266]
CUDA_VISIBLE_DEVICES=2 python scripts/inference_hf.py \
   --base_model  /home/fenbi/ctz/llama/meta-llama/hf-7B \
    --lora_model  ./chinese_alpaca_plus_lora_7b \
    --with_prompt \
    --interactive

===================================BUG REPORT===================================

Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.19s/it]
Vocab of the base model: 32000
Vocab of the tokenizer: 49954
Resize model embeddings to fit tokenizer
loading peft model
Start inference with instruction mode.
=====================================================================================
+ 该模式下仅支持单轮问答，无多轮对话能力。
+ 如要进行多轮对话，请使用llama.cpp或llamachat工具。
-------------------------------------------------------------------------------------
+ This mode only supports single-turn QA.
+ If you want to experience multi-turn dialogue, please use llama.cpp or llamachat.
=====================================================================================
Input:为什么苹果支付没有在中国流行？
Response:  对不起, como modelo de lenguaje estoy limitado en responder preguntas específicas sobre Apple Pay境外中国内地ino酆瘴蒴 proporcionar información útil琬蕤蕤倜鄙蹒蒨恃蛋惑臃傥岿蹒倜婀倜é倜ém衷蹒繩黏窘替衬鞘蔗动倜é倜芊朴浣暮蚕泼眩倜僖倜皑霉倜é倜倜璀倜倜倜倜倜倜倜倜渗倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜倜吞危倜倜倜特矫倜逼腮锈倜复古挥旧鲜砾咸出租抒暇坏曆安发明卦偵驯龄洗涤熨恤训苯安时装荡投资牙清新绸烟趣味驰性感香味感鹌荤际娱乐馔性感活泼气氛嗅性感心动焗性感激情性感飨淙浓厚性感痕恶劣天赋狰帅气性感氛羁性感荼猾性感骋性感质煽祯性感好玩轻微殄卦tain腱平均气温譬疗洺瘢轻受轻轻瘦熟雷平衡投天耐空气腹鞍蒸发薰粼然天临安远背天空阴穿天空霓悠天空闻天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空天空 
温馨街头眼球枥头晕椋泠碛鹉赭

Input:你好
Response:  您也是喔！

Input:为什么天空是蓝色的？
Response:  因为天空看起来像是蓝色是因为空气中尘粒子反射光线嗜大气氧气分子饱和氛飨光泽瘴光谱强度灯干扰气氛亮度光照湿度喜欢够气轻色风低空气空气氩气质亚气气气气气气气气气气气。

Input:

**Comment by DexterGuo** [comment]
遇到了跟你一样的问题，测试样例都不能复现

**Comment by expresschen** [comment]
好的，解决啦，感谢啦
