### ISSUE TITLE
合并了生成了alpaca模型, 基于这个模型, 做预训练, 然后用inference_hf,  出现错误, 可能是什么原因?还是说不能这么干?

### ISSUE THREAD

**Issue by ruanshudong** [ymcui/Chinese-LLaMA-Alpaca#267]
python inference_hf.py --base_model=merge_alpaca_plus/ --lora_model=lora-llama-7b/ --interactive --with_prompt
load: merge_alpaca_plus/
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:21<00:00, 10.60s/it]
Vocab of the base model: 49954
Vocab of the tokenizer: 72377
Resize model embeddings to fit tokenizer
loading peft model
lora-llama-7b/adapter_config.json
True
lora-llama-7b/adapter_config.json
True
Start inference with interactive mode.
Input:who are you?
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/data/LLM/llama/data/inference_hf.py:105 in <module>                                        │
│                                                                                                  │
│   102 │   │   │   │   else:                                                                      │
│   103 │   │   │   │   │   input_text = raw_input_text                                            │
│   104 │   │   │   │   inputs = tokenizer(input_text,return_tensors="pt")  #add_special_tokens=   │
│ ❱ 105 │   │   │   │   generation_output = model.generate(                                        │
│   106 │   │   │   │   │   input_ids = inputs["input_ids"].to(device),                            │
│   107 │   │   │   │   │   attention_mask = inputs['attention_mask'].to(device),                  │
│   108 │   │   │   │   │   eos_token_id=tokenizer.eos_token_id,                                   │
│                                                                                                  │
│ /home/data/anaconda3/lib/python3.10/site-packages/peft/peft_model.py:581 in generate             │
│                                                                                                  │
│   578 │   │   self.base_model.prepare_inputs_for_generation = self.prepare_inputs_for_generati   │
│   579 │   │   try:                                                                               │
│   580 │   │   │   if not isinstance(self.peft_config, PromptLearningConfig):                     │
│ ❱ 581 │   │   │   │   outputs = self.base_model.generate(**kwargs)                               │
│   582 │   │   │   else:                                                                          │
│   583 │   │   │   │   if "input_ids" not in kwargs:                                              │
│   584 │   │   │   │   │   raise ValueError("input_ids must be provided for Peft model generati   │
│                                                                                                  │
│ /home/data/anaconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py:115 in              │
│ decorate_context                                                                                 │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ /home/data/anaconda3/lib/python3.10/site-packages/transformers/generation/utils.py:1485 in       │
│ generate                                                                                         │
│                                                                                                  │
│   1482 │   │   │   )                                                                             │
│   1483 │   │   │                                                                                 │
│   1484 │   │   │   # 13. run sample                                                              │
│ ❱ 1485 │   │   │   return self.sample(                                                           │
│   1486 │   │   │   │   input_ids,                                                                │
│   1487 │   │   │   │   logits_processor=logits_processor,                                        │
│   1488 │   │   │   │   logits_warper=logits_warper,                                              │
│                                                                                                  │
│ /home/data/anaconda3/lib/python3.10/site-packages/transformers/generation/utils.py:2560 in       │
│ sample                                                                                           │
│                                                                                                  │
│   2557 │   │   │                                                                                 │
│   2558 │   │   │   # sample                                                                      │
│   2559 │   │   │   probs = nn.functional.softmax(next_token_scores, dim=-1)                      │
│ ❱ 2560 │   │   │   next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)              │
│   2561 │   │   │                                                                                 │
│   2562 │   │   │   # finished sentences should have their next token be a padding token          │
│   2563 │   │   │   if eos_token_id is not None:                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by ruanshudong** [comment]
合并出来的alpaca模型的token不对? 我单独推理这个模型貌似没问题呢?

**Comment by airaria** [comment]
`Vocab of the tokenizer: 72377` 
72377这个数比较莫名其妙，Chinese-llama和Chinese-alpaca tokenizer的大小只有49953和49954啊

**Comment by ruanshudong** [comment]
这个是我预训练增加了词条, 所以会更多

**Comment by ruanshudong** [comment]
简单的说, 在合并后的模型基础上, 再增加词条, 做预训练应该也是可行的吧?

**Comment by airaria** [comment]
> 简单的说, 在合并后的模型基础上, 再增加词条, 做预训练应该也是可行的吧?

可能和解码策略有关，#245

**Comment by ruanshudong** [comment]
我这里beams=1, 貌似不是这个问题导致的

**Comment by ruanshudong** [comment]
使用llama.cpp同样不行, 预训练过程中, 我采用了block_size=256, 这个有影响么? 我感觉按说不应该有影响啊

**Comment by ruanshudong** [comment]
会导致模型参数不同, 从而结构有区别??

**Comment by ruanshudong** [comment]
知道原因了, lora rank设置的不对导致的, 但是我改对以后, 不nan了, 但是输出还是乱码, 是不是adapter_config.json里面还有参数和预训练有关系?

**Comment by airaria** [comment]
lora_alpha?

**Comment by ruanshudong** [comment]
这个值应该是怎么设置? 在预训练的时候貌似没看到这个参数呢?

**Comment by ruanshudong** [comment]
知道了确实是lora_alpha的问题, 多谢!
