### ISSUE TITLE
无法合并由alpaca-lora训练的权重，tokenizer使用llama-7b-hf和使用chinese_llama_plus_lora_7b中复制过去的

### ISSUE THREAD

**Issue by autoexpect** [ymcui/Chinese-LLaMA-Alpaca#274]
### 详细描述问题

*无法合并由alpaca-lora训练的权重，tokenizer使用llama-7b-hf和使用chinese_llama_plus_lora_7b中复制过去的。*

### 运行截图或log

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/6939585/236842494-58ecb3f3-63a7-4022-82c2-fb6c29991a77.png">
<img width="349" alt="image" src="https://user-images.githubusercontent.com/6939585/236842585-5b17bdb0-8098-4e9e-8c7b-0d2b188c9114.png">

### 必查项目

- [ ] 哪个模型的问题：LLaMA
- [ ] 问题类型：
  - 模型转换和合并

**Comment by autoexpect** [comment]
基模型是，基于llama-7b-hf合并了chinese_alpaca_plus_lora_7b和chinese_llama_plus_lora_7b的模型llama-7b-hf-chinese。
<img width="578" alt="image" src="https://user-images.githubusercontent.com/6939585/236850136-658235c5-01c0-4841-90d3-a1ce47dce1ea.png">

要合并的模型是，使用alpaca-lora基于上面的llama-7b-hf-chinese为基础模型，搭配一个自己整理的中文数据集alpaca_data_chinese.json用Lora模式训练的权重。
```bash
python finetune.py \
--base_model '/srv/hdd/datasets/llama-7b-hf-chinese' \
--data_path './alpaca_data_chinese.json' \
--num_epochs 3 \
--val_set_size 2000 \
--output_dir './lora-alpaca'
```
最后的合并命令是
```bash
python /srv/ssd/github/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py \
--base_model /srv/hdd/datasets/llama-7b-hf-chinese \
--lora_model ./lora-alpaca \
--output_type huggingface \
--output_dir /srv/hdd/datasets/llama-7b-hf-chinese-1
```

**Comment by airaria** [comment]
adapter_config.json的内容可以发出来看一下吗

**Comment by autoexpect** [comment]
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/6939585/236852499-8c5060ea-3e00-4749-bd77-a617b3fa16d1.png">

**Comment by airaria** [comment]
报错的内容是检测到合并前后模型的权重相同，因此很有可能进行了无效合并，或LoRA权重等效为0。
目前我也没看出来问题，你可以尝试把报错的那一行assert注释掉再合并，然后手动比较合并前后模型的权重是否相同。

**Comment by autoexpect** [comment]
好的，我明天再试试，另外有一个疑问请教一下，新训练出来的Lora权重是没有tokenizer的，我是该复制llama-7b-hf中的tokenizer.model，还是复制复制llama-7b-hf-chinese中的呢？

**Comment by yuanzhiyong1999** [comment]
> 基模型是，基于llama-7b-hf合并了chinese_alpaca_plus_lora_7b和chinese_llama_plus_lora_7b的模型llama-7b-hf-chinese。 <img alt="image" width="578" src="https://user-images.githubusercontent.com/6939585/236850136-658235c5-01c0-4841-90d3-a1ce47dce1ea.png">
> 
> 要合并的模型是，使用alpaca-lora基于上面的llama-7b-hf-chinese为基础模型，搭配一个自己整理的中文数据集alpaca_data_chinese.json用Lora模式训练的权重。
> 
> ```shell
> python finetune.py \
> --base_model '/srv/hdd/datasets/llama-7b-hf-chinese' \
> --data_path './alpaca_data_chinese.json' \
> --num_epochs 3 \
> --val_set_size 2000 \
> --output_dir './lora-alpaca'
> ```
> 
> 最后的合并命令是
> 
> ```shell
> python /srv/ssd/github/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py \
> --base_model /srv/hdd/datasets/llama-7b-hf-chinese \
> --lora_model ./lora-alpaca \
> --output_type huggingface \
> --output_dir /srv/hdd/datasets/llama-7b-hf-chinese-1
> ```

我和你遇到的问题一模一样，可以交流一下

**Comment by yuanzhiyong1999** [comment]
> 基模型是，基于llama-7b-hf合并了chinese_alpaca_plus_lora_7b和chinese_llama_plus_lora_7b的模型llama-7b-hf-chinese。 <img alt="image" width="578" src="https://user-images.githubusercontent.com/6939585/236850136-658235c5-01c0-4841-90d3-a1ce47dce1ea.png">
> 
> 要合并的模型是，使用alpaca-lora基于上面的llama-7b-hf-chinese为基础模型，搭配一个自己整理的中文数据集alpaca_data_chinese.json用Lora模式训练的权重。
> 
> ```shell
> python finetune.py \
> --base_model '/srv/hdd/datasets/llama-7b-hf-chinese' \
> --data_path './alpaca_data_chinese.json' \
> --num_epochs 3 \
> --val_set_size 2000 \
> --output_dir './lora-alpaca'
> ```
> 
> 最后的合并命令是
> 
> ```shell
> python /srv/ssd/github/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py \
> --base_model /srv/hdd/datasets/llama-7b-hf-chinese \
> --lora_model ./lora-alpaca \
> --output_type huggingface \
> --output_dir /srv/hdd/datasets/llama-7b-hf-chinese-1
> ```

您好，请问解决了吗？我也遇到了同样的问题

**Comment by airaria** [comment]
降peft版本到0.2.0试试

**Comment by autoexpect** [comment]
降peft版本到0.2.0试试，也会报错：
<img width="529" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/6939585/30280752-917e-4700-bb8f-e2082e490138">
<img width="1233" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/6939585/a1aa430c-b0d2-403d-8577-d9fb85898681">
