### ISSUE TITLE
是否公开采样+规则筛选后的数据

### ISSUE THREAD

**Issue by aimetrics** [ymcui/Chinese-LLaMA-Alpaca#276]
### 详细描述问题
想基于本项目在13B LLaMA上做二次指令微调。是否可以公开采样+规则筛选后的数据集以及Self-instruction数据的1~2M数据集。
此外，想咨询，采用以上数据集是出于什么考虑？

### 运行截图或log

*（如有必要）请提供文本log或者运行截图，以便我们更好地了解问题详情。*

### 必查项目

- [ ] 哪个模型的问题：Alpaca 
- [ ] 问题类型：
  - 其他问题
- [x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by ymcui** [comment]
没有什么特殊考虑，当时不像现在有那么多指令数据可以用，所以从chatgpt获取数据是自然而然的选择。至于数据发布方面暂时没有计划。
