### ISSUE TITLE
请问预训练语料有增加代码数据的计划吗？

### ISSUE THREAD

**Issue by xinghua3632** [ymcui/Chinese-LLaMA-Alpaca#277]
按照一些研究分析，认为代码数据可以提升模型的逻辑推理能力。

**Comment by ymcui** [comment]
感谢建议。原版llama本身使用了代码数据训练，所以我们并没有加入太多代码数据。在已经经过代码训练的模型（原版llama）上继续用代码数据训练能带来多大的收益（这里特指对非代码类任务的提升）尚不清楚，还需要深入分析。

**Comment by xinghua3632** [comment]
有些代码任务用中文提问会结果会差的很远，用英文提问就能写的很准确；也可能是对中文的理解还不太够；
