### ISSUE TITLE
text-generation-webui方式运行dtype报错，效果有一些问题

### ISSUE THREAD

**Issue by brealisty** [ymcui/Chinese-LLaMA-Alpaca#280]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。提问时删除上面这两行。请只保留符合的选项，删掉其他。*

### 详细描述问题

text-generation-webui 的方式运行报错，在此项目中文找对应的issue：

`python server.py --model llama-13b-hf  --lora chinese-alpaca-lora-13b`
或者
`python server.py --model llama-7b-hf  --lora chinese-alpaca-lora-7b`

>Traceback (most recent call last):
  File "/home/byy/projects/nlp/text-generation-webui/server.py", line 874, in <module>
    add_lora_to_model(shared.args.lora)
  File "/home/byy/projects/nlp/text-generation-webui/modules/LoRA.py", line 36, in add_lora_to_model
    params['dtype'] = shared.model.dtype
AttributeError: 'LlamaCppModel' object has no attribute 'dtype'

尝试不加--lora也能运行，但是效果不佳，不知道和这个参数关系大不大，llama.cpp测试的效果也不是很突出。

### 运行截图或log

`python server.py --model llama-13b-hf`
input:
>Below is an instruction that describes a task. Write a response that appropriately completes the request.
>### Instruction:
>根据一下才料写一篇人物介绍，多写一些：wcj,男，60岁，xx公司书记，任职期间推进公司数字化建设，取得优秀成果。
>### Response:

output:
>Below is an instruction that describes a task. Write a response that appropriately completes the request.
>### Instruction:
>根据一下才料写一篇人物介绍，多写一些：wcj,男，60岁，xx公司书记，任职期间推进公司数字化建设，取得优秀成果。
>### Response:
>王成杰（WCJ）是一位男性，现年60岁的高管。他于2021年担任xx公司的总裁一职，并在任期内积极推动公司数字化建设，取得了显>著的业绩提升和业务拓展。

`./main -m ../text-generation-webui/models/llama-13b-hf/ggml-model-q4_0.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.3`
> 根据一下才料写一篇人物介绍，多写一些：wcj,男，60岁，xx公司书记，任职期间推进公司数字化建设，取得优秀成果。
姓名：王清杰（WCJ） 性别：男性  年龄：60岁   职务： xx公司的副总经理、总裁等职务

### 必查项目

- [x] 哪个模型的问题：Alpaca
- [x] 问题类型：
  - 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
  - 效果问题
- [x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by iMountTai** [comment]
llama.cpp测试建议参考本工程[llama.cpp教程](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/llama.cpp%E9%87%8F%E5%8C%96%E9%83%A8%E7%BD%B2)使用
webui通过`--lora`的方式加载模型速度比较慢，建议合并模型后再通过webui推理
