### ISSUE TITLE
Chinese-LLaMA-Plus-7B 词库问题

### ISSUE THREAD

**Issue by onlyfish79** [ymcui/Chinese-LLaMA-Alpaca#281]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。提问时删除上面这两行。请只保留符合的选项，删掉其他。*

### 详细描述问题

*请尽量具体地描述您遇到的问题。这将有助于我们更快速地定位问题所在。*

### 运行截图或log

*（如有必要）请提供文本log或者运行截图，以便我们更好地了解问题详情。*

### 必查项目

- [ ] 哪个模型的问题：Chinese-LLaMA-Plus-7B
- [ ] 问题类型：**（只保留你要问的）**

  - 其他问题
  Chinese-LLaMA-Plus-7B 训练数据：通用120G， Chinese-LLaMA-7B 训练数据：通用20G， 有两个疑问：
  1. 与原版LLaMA-7B合并后，两个模型的vocab_size 都是49953, 是否正确？
  2. 如果第一点符合预期，那么 Chinese-LLaMA-Plus-7B 比 Chinese-LLaMA-7B 优势是什么？训练数据从20G -> 120G 的作用？
  
- [ ] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ ] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by ymcui** [comment]
1、中文LLaMA的词表大小都是49953，Alpaca则是+1=49954。
2、Plus版本主要是在训练数据上进行了扩充，可以参考[release note v3.0](https://github.com/ymcui/Chinese-LLaMA-Alpaca/releases/tag/v3.0)

**Comment by onlyfish79** [comment]
明白了，谢谢。

**如果只想使用预训练的第一阶段扩充中文词向量，如下操作是否正确：**

将 merge_tokenizers.py  生成的3个文件：tokenizer.model, tokenizer_config.json, special_tokens_map.json， 替换掉原始LLaMA模型中的文件

**Comment by onlyfish79** [comment]
好的，谢谢，使用您提供的方法，不报错了。

1. 只合并词库，不使用预训练的第二阶段(增加LoRA权重）的原因：想确认一下finetune 长文本内容，增加LoRA权重是否会影响模型的“记忆能力”。
2. 再请教个问题，只将扩充词库合并到基础模型中，合并后的模型新增加了一些tokens, ，使用这个合并后的模型finetune，是否会有问题，比如是否能处理新tokens？

**Comment by airaria** [comment]
> 好的，谢谢，使用您提供的方法，不报错了。
> 
> 1. 只合并词库，不使用预训练的第二阶段(增加LoRA权重）的原因：想确认一下finetune 长文本内容，增加LoRA权重是否会影响模型的“记忆能力”。
> 2. 再请教个问题，只将扩充词库合并到基础模型中，合并后的模型新增加了一些tokens, ，使用这个合并后的模型finetune，是否会有问题，比如是否能处理新tokens？

取决于你的数据量，没有确定的结论，我也不好说，要通过实际实验来判定

**Comment by onlyfish79** [comment]
好的，非常感谢。
