### ISSUE TITLE
Ignoring llama-cpp-python: markers 'platform_system == "Windows"' don't match your environment

### ISSUE THREAD

**Issue by koaqiu** [ymcui/Chinese-LLaMA-Alpaca#283]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。提问时删除上面这两行。请只保留符合的选项，删掉其他。*

### 详细描述问题

*请尽量具体地描述您遇到的问题。这将有助于我们更快速地定位问题所在。*

### 运行截图或log

*（如有必要）请提供文本log或者运行截图，以便我们更好地了解问题详情。*

### 必查项目

- [x] 问题类型：**（只保留你要问的）**
  - 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
 
使用 https://www.autodl.com/ 的容器 会报这个错误

Ignoring llama-cpp-python: markers 'platform_system == "Windows"' don't match your environment

无论是clone代码 安装运行
还是下载他们的 工具包 都会

**Comment by iMountTai** [comment]
Ignoring像是运行日志，类似于warning，并不是error，还请贴出具体的部署方式及完整log~
