### ISSUE TITLE
peft 0.3.0 需要 torch >= 1.13.0

### ISSUE THREAD

**Issue by candowu** [ymcui/Chinese-LLaMA-Alpaca#284]
peft 0.3.0 已经release

手动模型合并与转换描述：
torch（1.12.0测试通过）⚠️ 1.13.0版本之后合并出的模型文件SHASUM会不同，请谨慎使用。

**Comment by iMountTai** [comment]
torch、transformers及peft不同版本均会影响中间模型文件的哈希值，目前暂未发现对合并模型性能的影响问题
