### ISSUE TITLE
请问能否开源指令微调的代码？

### ISSUE THREAD

**Issue by guozhiyao** [ymcui/Chinese-LLaMA-Alpaca#286]
请问能否开源指令微调时的代码呢？想知道增加了哪些可训练参数，以及一些训练细节。万分感谢。

**Comment by iMountTai** [comment]
请参考[指令精调](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E8%AE%AD%E7%BB%83%E7%BB%86%E8%8A%82#%E6%8C%87%E4%BB%A4%E7%B2%BE%E8%B0%83)

**Comment by airaria** [comment]
准备中

**Comment by Littink** [comment]
文档中写到的指令精调脚本不存在[scripts/run_clm_sft_with_peft.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/run_clm_sft_with_peft.py)

**Comment by ymcui** [comment]
> 文档中写到的指令精调脚本不存在[scripts/run_clm_sft_with_peft.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/run_clm_sft_with_peft.py)

你先别急，更新得有个过程，晚些时候再来看 😂

**Comment by Littink** [comment]
好的好的 辛苦大佬

**Comment by Littink** [comment]
> > 文档中写到的指令精调脚本不存在[scripts/run_clm_sft_with_peft.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/run_clm_sft_with_peft.py)
> 
> 你先别急，更新得有个过程，晚些时候再来看 😂

好的好的，辛苦大佬，感谢🙏

**Comment by ymcui** [comment]
还没做review，愿意尝鲜的话可以参考我们的PR（晚些时候会合并到main）：https://github.com/ymcui/Chinese-LLaMA-Alpaca/pull/322
