### ISSUE TITLE
这中文是喂了一口毒药吗？

### ISSUE THREAD

**Issue by leonunix** [ymcui/Chinese-LLaMA-Alpaca#287]
### 详细描述问题

input： 上海是怎么样的城市
ouput： 上海是怎么样的城市 , 上海龙凤论坛localhost, 南京夜网梧桐客栈, 新缓论坛qm, 浙江娱乐地图ylmap123, 深圳QM之家

这回答真是绝了。。。

### 必查项目

- [ ] 哪个模型的问题：Alpaca **（只保留你要问的）**
- [ ] 问题类型：**（只保留你要问的）**
  - 效果问题
  - 其他问题

**Comment by nlp4869** [comment]
是你自己用的有问题吧。
<img width="680" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/56213980/1f01f9f7-23d7-4c76-97d6-2f091a2aeafa">
