### ISSUE TITLE
基于合并后的chinese-alpaca-plus-7b模型继续指令精调

### ISSUE THREAD

**Issue by jiezhangGt** [ymcui/Chinese-LLaMA-Alpaca#288]
已经按照wiki教程合并得到了chinese-alpaca-plus-7b模型，得到以下文件：
`config.json`
`generation_config.json`
`pytorch_model-00001-of-00002.bin`
`pytorch_model-00002-of-00002.bin`
`pytorch_model.bin.index.json`
`special_tokens_map.json`
`tokenizer_config.json`
`tokenizer.model`

**Comment by iMountTai** [comment]
合并后得到的chinese-alpaca-plus-7b模型使用上与原版llama没有区别
