### ISSUE TITLE
peft v0.3.0dev0 commit id=13e53fc的源代码里面的setup.py的安装要求torch>=1.13.0  和本项目的torch=1.12.0冲突怎么解决捏

### ISSUE THREAD

**Issue by ccdf1137** [ymcui/Chinese-LLaMA-Alpaca#292]
peft v0.3.0dev0 commit id=13e53fc的源代码里面的setup.py的安装要求torch>=1.13.0  和本项目的torch=1.12.0冲突怎么解决捏

**Comment by airaria** [comment]
> peft v0.3.0dev0 commit id=13e53fc的源代码里面的setup.py的安装要求torch>=1.13.0 和本项目的torch=1.12.0冲突怎么解决捏

可以手动更改peft代码仓库里的setup.py，移除对torch版本的限制，将`torch>=1.13.0` 改成 `torch`

**Comment by ccdf1137** [comment]
非常感谢
