### ISSUE TITLE
合并词表报错

### ISSUE THREAD

**Issue by han508** [ymcui/Chinese-LLaMA-Alpaca#295]
合并词表时我用了redpajama的tokenizer替换了llama的tokenizer，报错：
<img width="882" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/69674181/e4547f0e-f57d-4a6d-b20c-dc5436483d9d">
请问如何解决这种报错、或者说有什么解决的思路吗

**Comment by airaria** [comment]
使用普通的tokenizer，不能使用FastTokenizer

**Comment by airaria** [comment]
不同类型的tokenizer不能合并，并且只能合并基于Sentencepiece的tokenizer
GPT2Tokenizer并不是基于Sentencepiece的，所以合并不了
