### ISSUE TITLE
请问是否支持使用繁体中文

### ISSUE THREAD

**Issue by stupidHIGH** [ymcui/Chinese-LLaMA-Alpaca#296]

**Comment by ymcui** [comment]
随便试了一下，你可以看看是否满足你的要求。

```
> 請你介紹一下香港，有什麼好玩的地方嗎？
香港有很多有趣的地方可以去玩，比如太平山、迪士尼樂園、海洋公园等等。
> 有什麼好吃的美食推薦一下嗎
在香港，你可以尝试一下港式奶茶、菠萝油、叉烧包、雞蛋仔等美食，都是香港特色美食哦！
> 如果想住一些奢華的飯店，你推薦哪幾家
在香港有很多奢華的飯店，比如四季酒店、喜來登酒店、香格里拉酒店等等。你可以根据自己的需求和预算选择合适的飯店哦！
```

**Comment by stupidHIGH** [comment]
感觉很棒，感谢！

**Comment by stupidHIGH** [comment]
> 随便试了一下，你可以看看是否满足你的要求。
> 
> ```
> > 請你介紹一下香港，有什麼好玩的地方嗎？
> 香港有很多有趣的地方可以去玩，比如太平山、迪士尼樂園、海洋公园等等。
> > 有什麼好吃的美食推薦一下嗎
> 在香港，你可以尝试一下港式奶茶、菠萝油、叉烧包、雞蛋仔等美食，都是香港特色美食哦！
> > 如果想住一些奢華的飯店，你推薦哪幾家
> 在香港有很多奢華的飯店，比如四季酒店、喜來登酒店、香格里拉酒店等等。你可以根据自己的需求和预算选择合适的飯店哦！
> ```

我试了下chinnese-alpaca-plus-7b，相同的问题回答仍然是简体中文，请问你用的哪个model可以支持繁体？

**Comment by ymcui** [comment]
Alpaca-Plus-7B、Alpaca-Plus-13B都试了一下，并非每次都是会按繁体中文来回复，随机性比较大，简体中文回复的概率比较大。训练数据中主要还是简体中文，所以可能模型更倾向于用简体中文回复。

**Comment by ymcui** [comment]
> > Alpaca-Plus-7B、Alpaca-Plus-13B都试了一下，并非每次都是会按繁体中文来回复，随机性比较大，简体中文回复的概率比较大。训练数据中主要还是简体中文，所以可能模型更倾向于用简体中文回复。
> 
> 你好 打扰了 我并非专业的AI developer.只是想简单的尝试一下。目前没有足够的资金去买性能足够的GPU训练。所以想问下如果可以直接使用别人训练出来的模型吗

@CarbonAnimal 没太理解你说的“直接使用别人训练出来的模型”的具体含义。如果只是拿去个人使用是没有什么问题的。商业使用受Facebook的许可证限制（禁止商用）。另外，你提出的问题似乎和本issue无关，如有需要可以新开一个issue。

**Comment by stupidHIGH** [comment]
> Alpaca-Plus-7B、Alpaca-Plus-13B都试了一下，并非每次都是会按繁体中文来回复，随机性比较大，简体中文回复的概率比较大。训练数据中主要还是简体中文，所以可能模型更倾向于用简体中文回复。

好的，谢谢
