### ISSUE TITLE
请问如果不使用Lora，直接微调，由于扩充词表，lm_head的size不一致，应该如何解决？

### ISSUE THREAD

**Issue by AceCHQ** [ymcui/Chinese-LLaMA-Alpaca#299]
如果不使用Lora，直接微调，由于扩充词表，lm_head的size不一致，应该如何解决？报错如下：
size mismatch for lm_head.weight: copying a param with shape torch.Size([250680, 4096]) from checkpoint, the shape in current model is torch    .Size([0, 4096]).
谢谢～

**Comment by onedreame** [comment]
请问你是怎么加载模型的？LlamaForCausalLM.from_pretrained('ziqingyang/chinese-llama-plus-lora-7b')这样么

**Comment by yuemengrui** [comment]
model.resize_token_embeddings(len(tokenizer))

**Comment by yuemengrui** [comment]
model.resize_token_embeddings(len(tokenizer)) 加上这句，我直接微调，在单机多卡跑不起来
