### ISSUE TITLE
考虑使用GitHub Release托管权重文件

### ISSUE THREAD

**Issue by nanmu42** [ymcui/Chinese-LLaMA-Alpaca#3]
作者您好，很棒的项目！

使用百度网盘下载权重文件的体验有些差了，特别是在没有会员的情况下。

我看您还上传了Google Drive，体验应该会好很多，不过还有个比较直接的方式，GitHub在发布/编辑Release时，可以上传assets，而且assets的体积可以很大：

![image](https://user-images.githubusercontent.com/8143068/228407866-17b9cd68-7fdc-4445-bcb8-1db8444a019c.png)

这是一个效果示例：https://github.com/nanmu42/tart/releases/tag/v1.0.0

也许您可以考虑像这样上传一份，这样比较直接，对wget等工具也友好。

谢谢。

**Comment by ymcui** [comment]
您好，感谢您的热心建议，会考虑下个版本的时候尝试。
目前我们新添加了HuggingFace的相关链接，希望能进一步分流，提升下载体验。
[https://github.com/ymcui/Chinese-LLaMA-Alpaca#下载地址](https://github.com/ymcui/Chinese-LLaMA-Alpaca#下载地址)

**Comment by nanmu42** [comment]
谢谢，祝你们越办越好！
