### ISSUE TITLE
请问能否公开中文词表训练以及和原始词表合并的代码以供参考呢？

### ISSUE THREAD

**Issue by hzy312** [ymcui/Chinese-LLaMA-Alpaca#30]
请问能否公开中文词表训练以及和原始词表合并的代码以供参考呢？

如果可以，十分感激！

**Comment by ymcui** [comment]
我们没有在训练词表上花费太多时间。
建议你直接去看一下sentencepiece官方目录学习如何利用已有语料训练一个词表。
剩余的就是用训练出的词表和原LLaMA词表进行去重然后合并。
