### ISSUE TITLE
stage1 微调在单机多卡上跑不起来

### ISSUE THREAD

**Issue by yuemengrui** [ymcui/Chinese-LLaMA-Alpaca#301]

**Comment by yuemengrui** [comment]
没有具体的报错信息。直接被kill了。WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 46601 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 46602 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 46603 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 46604 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 46606 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 46607 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 46608 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 4 (pid: 46605) of binary: /opt/conda/bin/python

**Comment by wangjvjie** [comment]
我也跑不起来，他只用了第一张卡，没用第二张我很疑惑

**Comment by zzx16045223** [comment]
> 没有具体的报错信息。直接被kill了。WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 46601 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 46602 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 46603 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 46604 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 46606 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 46607 closing signal SIGTERM WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 46608 closing signal SIGTERM ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 4 (pid: 46605) of binary: /opt/conda/bin/python

我也是这个问题，请问你解决了，一机多卡出现这个问题

**Comment by zhao1iang** [comment]
我也是这个问题，请问最后解决了么？
