### ISSUE TITLE
扩充词表问题

### ISSUE THREAD

**Issue by Louis-y-nlp** [ymcui/Chinese-LLaMA-Alpaca#304]
### 详细描述问题

想请教一下扩充中文词表的必要性，基于unicode编码的tokenizer理论上可以支持任意中文字符编码，那么如果不扩充中文词表，直接使用中文预料进行训练和微调，对模型效果的影响有多大？因为看到一些其他语种比如日语的工作，是没有扩充词表的。wiki里也说了“大多数相关衍生工作是直接在原版上进行pretrain/finetune的”，所以区别只是编码效率或者最终质量问题，是这样吗？

### 必查项目

- [x] 哪个模型的问题：LLaMA / Alpaca **（只保留你要问的）**
- [x] 问题类型：**（只保留你要问的）**
  - 效果问题
  - 其他问题
- [x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by airaria** [comment]
我们没有做对比实验，但至少在编码效率上优于原版LLaMA，可以参见我们的技术报告。至于模型效果问题，可以通过预训练来弥补，我们通过训练损失粗略估计认为在中文上的效果应不会明显低于原版经过同样语料训练的效果。
