### ISSUE TITLE
有关精调模板的问题

### ISSUE THREAD

**Issue by yuanzhiyong1999** [ymcui/Chinese-LLaMA-Alpaca#307]
chinese-alpaca使用原版stanford-alpaca不带input的模板，是英文的。但是语料是中文的，这样不会产生gap吗？
是否使用中文的模板会更好？还是说精调时的模板要翻译成中文呢？
chinese-alpaca使用的模板如下：
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/94682439/f6c0582d-4823-449d-a71c-cd136cacd51d)
 如果我在后续精调的时候应该采用中文还是英文的模板呢？

**Comment by ymcui** [comment]
早期尝试过中文模板，效果没有什么大的差异。所以后续就统一使用英文模板了。精调的话继续用英文模板就行了。

**Comment by yuanzhiyong1999** [comment]
感谢解答！
