### ISSUE TITLE
中英互译效果怎么样呢？

### ISSUE THREAD

**Issue by wizd** [ymcui/Chinese-LLaMA-Alpaca#31]
感谢你们的努力，中文处理获得长足进展。我有看到训练数据里面包含了翻译。请问实际应用效果如何？

**Comment by ymcui** [comment]
这部分暂时没有做定量分析。随机测了一些样例，感觉效果可以接受。
由于训练语料里也没有加太多翻译样本，如果要提升翻译质量化还是有很大进步空间的。
感兴趣的话可以自己评测一下。
