### ISSUE TITLE
多卡训练报错：RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for  argument index in method wrapper__index_select)

### ISSUE THREAD

**Issue by yuemengrui** [ymcui/Chinese-LLaMA-Alpaca#311]

**Comment by yuemengrui** [comment]
> 预训练代码有改动吗？脚本贴一下

一点改动都没有，完全照搬项目文档中的训练脚本

**Comment by yuemengrui** [comment]
> 启动命令贴一下，还有详细的log日志

python  my_train.py \
    --model_name_or_path /workspace/LLM/Models/chinese-alpaca-7b \
    --tokenizer_name_or_path /workspace/LLM/Models/chinese-alpaca-7b \
    --dataset_dir /workspace/LLM/Data/Pretrain_data/corpus \
    --data_cache_dir /workspace/LLM/Data/data_cache \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --do_train True \
    --seed 42 \
    --fp16 True \
    --num_train_epochs 5 \
    --lr_scheduler_type cosine \
    --learning_rate 2e-4 \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 100 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 1000 \
    --gradient_accumulation_steps 8 \
    --preprocessing_num_workers 8 \
    --block_size 1024 \
    --output_dir /workspace/LLM/MyTrainer/output \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --torch_dtype float16 \
加了device_map之后，出现了新的错误：ValueError: Attempting to unscale FP16 gradients.

**Comment by yuemengrui** [comment]
> 启动命令贴一下，还有详细的log日志

lr=2e-4
lora_rank=8
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.1

python run_clm_pt_with_peft.py \
    --model_name_or_path /workspace/LLM/Models/llama-13b-hf \
    --tokenizer_name_or_path /workspace/LLM/Models/llama-13b-hf \
    --dataset_dir /workspace/LLM/Data/Pretrain_data/corpus \
    --data_cache_dir /workspace/LLM/Data/data_cache \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --do_train \
    --seed 42 \
    --fp16 \
    --max_steps 1000000 \
    --lr_scheduler_type cosine \
    --learning_rate 2e-4 \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 500 \
    --gradient_accumulation_steps 4 \
    --preprocessing_num_workers 8 \
    --block_size 512 \
    --output_dir /workspace/LLM/MyTrainer/output \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16

**Comment by yuemengrui** [comment]
加了device_map之后，错误变成了ValueError: Attempting to unscale FP16 gradients.

**Comment by iMountTai** [comment]
> 加了device_map之后，错误变成了ValueError: Attempting to unscale FP16 gradients.

不需要设置device_map,启动命令中添加`CUDA_VISIBLE_DEVICES=0`试试

**Comment by yuemengrui** [comment]
不行，还是出现了错误：RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:6 and cuda:7! (when checking argument for 
argument mat2 in method wrapper_mm)
