### ISSUE TITLE
Chinese-LLaMA-Plus-13B，推理过程中报错

### ISSUE THREAD

**Issue by heshuguo** [ymcui/Chinese-LLaMA-Alpaca#312]
感谢您使用Issue提问模板，请按照以下步骤提供相关信息。我们将优先处理信息相对完整的Issue，感谢您的配合。

*提示：将[ ]中填入x，表示打对钩。提问时删除上面这两行。请只保留符合的选项，删掉其他。*

### 详细描述问题

Chinese-LLaMA-Plus-13B，推理过程中报错：

### 运行截图或log

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/19610534/f0ba6779-5df7-4c43-b3a5-8a9ba3e67e15)

**Comment by heshuguo** [comment]
忽略刚才那个图，是下面这个图
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/19610534/3a140ecc-4be7-4962-9a10-e8fa0b7d9d1b)

**Comment by iMountTai** [comment]
GPU推理还是CPU推理？

**Comment by heshuguo** [comment]
> GPU推理还是CPU推理？像是内存不足的问题

GPU，内存将近400G，应该不是内存不足的问题 @iMountTai

**Comment by iMountTai** [comment]
您好，我这边没有复现相关问题，不过因为transformers推理代码目前不支持多轮对话，所以您可以尝试llama.cpp或者webui等方式
