### ISSUE TITLE
有没有多轮对话的脚本代码

### ISSUE THREAD

**Issue by kingdomad** [ymcui/Chinese-LLaMA-Alpaca#313]
如题。或者有没有可以推荐哪个开源的代码可以借鉴一下？

**Comment by airaria** [comment]
可以参考llama.cpp 和 llamachat中的多轮对话方式

**Comment by kingdomad** [comment]
> 可以参考llama.cpp 和 llamachat中的多轮对话方式

那是C++的吧，还是想找找python的代码
