### ISSUE TITLE
多卡训练时，第0张卡被占满，导致CUDA out of memory

### ISSUE THREAD

**Issue by yuemengrui** [ymcui/Chinese-LLaMA-Alpaca#317]
<img width="555" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/24349763/0bdc4d24-a29b-4e9e-9a26-525dfed995fc">

**Comment by Ethan-yt** [comment]
+1.前几张卡占用非常大。finetune13b lora batch size只能开到4

**Comment by airaria** [comment]
多卡训练用的是deepspeed ZeRO-2 吗

**Comment by Ethan-yt** [comment]
> 多卡训练用的是deepspeed ZeRO-2 策略吗，建议使用deepspeed做多卡训练，我们也提供了deepspeed config文件，并对教程所有更新， 可以参见[预训练脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E9%A2%84%E8%AE%AD%E7%BB%83%E8%84%9A%E6%9C%AC)和[指令精调脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E6%8C%87%E4%BB%A4%E7%B2%BE%E8%B0%83%E8%84%9A%E6%9C%AC)

是按照教程的配置。
<img width="732" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/9592150/e5f2cc1c-ed43-4847-ae0a-bd59556d1c93">

**Comment by iMountTai** [comment]
> > 多卡训练用的是deepspeed ZeRO-2 策略吗，建议使用deepspeed做多卡训练，我们也提供了deepspeed config文件，并对教程所有更新， 可以参见[预训练脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E9%A2%84%E8%AE%AD%E7%BB%83%E8%84%9A%E6%9C%AC)和[指令精调脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E6%8C%87%E4%BB%A4%E7%B2%BE%E8%B0%83%E8%84%9A%E6%9C%AC)
> 
> 是按照教程的配置。 <img alt="image" width="732" src="https://user-images.githubusercontent.com/9592150/238673873-e5f2cc1c-ed43-4847-ae0a-bd59556d1c93.png">

这是训练中还是处于模型加载阶段？

**Comment by Ethan-yt** [comment]
> > > 多卡训练用的是deepspeed ZeRO-2 策略吗，建议使用deepspeed做多卡训练，我们也提供了deepspeed config文件，并对教程所有更新， 可以参见[预训练脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E9%A2%84%E8%AE%AD%E7%BB%83%E8%84%9A%E6%9C%AC)和[指令精调脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E6%8C%87%E4%BB%A4%E7%B2%BE%E8%B0%83%E8%84%9A%E6%9C%AC)
> > 
> > 
> > 是按照教程的配置。 <img alt="image" width="732" src="https://user-images.githubusercontent.com/9592150/238673873-e5f2cc1c-ed43-4847-ae0a-bd59556d1c93.png">
> 
> 这是训练中还是处于模型加载阶段？

训练中。

**Comment by Ethan-yt** [comment]
<img width="384" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/9592150/c7e687a1-6b73-422f-b801-ec2c5de3a443">
loss看起来也不太对
