### ISSUE TITLE
如何合并safetenors模型？

### ISSUE THREAD

**Issue by tangpingzhou** [ymcui/Chinese-LLaMA-Alpaca#32]
我所使用的是safetensors格式的7b-hf模型（Safe-LLaMA-HF (3-26-23)），合并脚本无法正常工作，提示仅支持*.bin、*.ckpt的模型

尝试在merge_llama_with_chinese_lora.py脚本中加入safe_serialization=True，如：
```
base_model = LlamaForCausalLM.from_pretrained( 
    BASE_MODEL, 
    load_in_8bit=False,   
    torch_dtype=torch.float16, 
    device_map={"": "cpu"}, 
    safe_serialization=True 
)     
```
也无法正常工作，请问safetenors模型如何做LoRA合并？必须先做 safetensors 2 ckpt 转换么？

**Comment by airaria** [comment]
并不太熟悉safetensors格式。
不过如果`from_pretrained`无法运行，应该是Transformers库还不支持从safetensors格式载入吧？
