### ISSUE TITLE
损失值大小

### ISSUE THREAD

**Issue by guozhiyao** [ymcui/Chinese-LLaMA-Alpaca#323]
请问下，经过训练的后的损失值大小大约是多少呢？我自己在从头pretrain 13B模型，不确定最终loss会收敛到多少，想参考下你的loss带下。

**Comment by ymcui** [comment]
这里有讨论：https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/256

**Comment by yuanzhiyong1999** [comment]
我在alpaca-plus的基础上继续精调，损失最低也在1.5左右，这是什么原因呢 有什么方法改善一下呢？

**Comment by guozhiyao** [comment]
正常应该是多少呢？


 
我在alpaca-plus的基础上继续精调，损失最低也在1.5左右，这是什么原因呢 有什么方法改善一下呢？

**Comment by airaria** [comment]
See the discussion here #264

**Comment by yuanzhiyong1999** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/94682439/b94d2f02-6c61-411b-8a81-0996dfdfe882)
损失z最低也在1.5左右，可能是什么原因呢？
我看其他的基本都会在1以内
