### ISSUE TITLE
合并完模型，生成 q8_0 文件，生成一直 输出 井号 # 是咋回事？

### ISSUE THREAD

**Issue by doublnt** [ymcui/Chinese-LLaMA-Alpaca#325]
合并完模型，生成 q8_0 文件，生成一直 输出 井号 #是咋回事？

(merge-chinese-model-env) PS D:\work\llama.cpp> .\build\bin\Release\main.exe -m .\zh-models\7B\ggml-model-q8_0.bin -p "who is su shi?"
main: build = 0 (unknown)
main: seed  = 1683901204
llama.cpp: loading model from .\zh-models\7B\ggml-model-q8_0.bin
llama_model_load_internal: format     = ggjt v2 (latest)
llama_model_load_internal: n_vocab    = 49953
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 7 (mostly Q8_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =  68.20 KB
llama_model_load_internal: mem required  = 9180.12 MB (+ 1026.00 MB per state)
llama_init_from_file: kv self size  =  256.00 MB

system_info: n_threads = 8 / 16 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 0

 who is su shi?#########################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################

**Comment by ymcui** [comment]
什么模型，怎么合并的？

**Comment by doublnt** [comment]
https://huggingface.co/decapoda-research/llama-7b-hf 这个是源模型，
命令如下：

`python .\mergellama.py  --base_model ..\models\llama-7b-hf\  --lora_model ..\models\chinese_alpaca_plus_lora_7b\ --output_type pth --output_dir .\output`

` python .\convert.py .\zh-models\7B\  `

几种量化都试过，全都是 输出 #####
`.\build\bin\Release\quantize.exe .\zh-models\7B\ggml-model-f16.bin .\zh-models\7B\ggml-model-q4_0.bin q4_0`

`.\build\bin\Release\main.exe -m zh-models/7B/ggml-model-q4_0.bin --color -p "who is su shi?"`

**Comment by doublnt** [comment]
<img width="857" alt="Screenshot 2023-05-13 091520" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/13679242/f2fa0628-18c6-435d-b7e1-bfc5b1fb692d">

**Comment by ymcui** [comment]
因为你合并的不对啊😂，Alpaca-Plus需要同时传入LLaMA-Plus-LoRA和Alpaca-Plus-LoRA合并才可以。
仔细看一下Wiki：https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/手动模型合并与转换#多lora权重合并适用于chinese-alpaca-plus

**Comment by doublnt** [comment]
我最开始就是两个一起合并的，llama 放在前面，然后 alpaca 放在后面，量化后还是 ###，我现在重新再合并一次试下， llama.cpp 我是用的最新 main 分支上重新本机带上 cuda 编译的。

**Comment by ymcui** [comment]
Alpaca建议使用交互instruction模式，另外要load对应的模板，例如：
```
./main -m zh-alpaca-models/7B/ggml-model-q4_0.bin --color -f ./prompts/alpaca.txt -ins -b 16 -c 512
```

**Comment by doublnt** [comment]
我重新两个模型合并，然后量化成 8_0 的，使用如下：
`.\build\bin\Release\main.exe -m zh-models/7B/ggml-model-q8_0.bin --color -f .\prompts\alpaca.txt -ins -b 16 -c 512`
还是一直输出的#，请问下这个可以从哪些方面排查额？

**Comment by ymcui** [comment]
以下是量化后的q8_0以及f16的SHA256，你可以对比一下。
```
ff1b113ff835516e475363b019a2c7a7c63f27abbe56c89aad3ec18c1bbf53db  ggml-model-f16.bin
0eec8927427f159397c79961a28d62d78849514a4a19033b247edd6ac3fc2cfd  ggml-model-q8_0.bin
```

**Comment by doublnt** [comment]
两个sha256 都对不上。。。难道是我的源 llama 7b hf 的就有问题？？？

**Comment by ymcui** [comment]
看你的路径应该是windows系统？也不排除是win下特定的问题，你看一下FAQ里关于win的信息。另外，你要判断一下是只有这一个模型这样还是说其他模型（比如Alpaca-7B基础版）也是这样？

**Comment by doublnt** [comment]
<img width="421" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/13679242/51da8eaf-834c-46c0-8c35-964327b623a7">
这四个都试了下，全都不行，全都是输出 ### , 我用 wsl2 试了下， 好像也是一样的效果。 llama.cpp 是最新分支 编译的。感谢您百忙中帮我解答，我再研究下，谢谢了。

**Comment by ymcui** [comment]
1、如果上述4个模型都无效，那多半是llama.cpp与你的环境不适配
2、可以将最原始的llama-7b转换为llama.cpp的ggml格式，输入一些常用的prompt试一下
3、另外可以尝试使用gitbash，有些人推荐在win下使用这个

**Comment by doublnt** [comment]
@ymcui  大佬，我搞定了，是我源llama-7b-hf 文件下载的有问题，和环境没有关系， windows11 下 powershell 能直接跑的。
十分感谢提供的解答建议。
<img width="869" alt="Screenshot 2023-05-14 232731" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/13679242/c20f3fed-d5e5-4e17-9bb9-575a53ffa0fe">
