### ISSUE TITLE
精调脚本报错

### ISSUE THREAD

**Issue by yuanzhiyong1999** [ymcui/Chinese-LLaMA-Alpaca#327]
### 详细描述问题

使用指令精调脚本报错
运行脚本如下
`pretrained_model=../../pretrained_models/chinese_llama_plus_lora_7b_hf
chinese_tokenizer_path=../../pretrained_models/chinese_alpaca_plus_lora_7b
dataset_dir=../data/sft/ft
peft_model=../../pretrained_models/chinese_alpaca_plus_lora_7b
force_resize_embeddings=True # True or False
deepspeed_config_file=ds_zero2_no_offload.json
torchrun --nnodes 1 --nproc_per_node 2 run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \`
其他参数没有改动，我也试了
`chinese_tokenizer_path=../../pretrained_models/chinese_alpaca_plus_lora_7b_hf`
还是同样的错误

其中chinese_llama_plus_lora_7b_hf是将chinese_llama_plus_lora_7b合并到llama_7b_hf得到的
### 运行截图或日志

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/94682439/6b29b7a7-e3a9-4f6b-8eec-261816462eb7)

### 必查项目（前三项只保留你要问的）

- [x] **基础模型**：LLaMA-Plus / Alpaca-Plus
- [x] **运行系统**： Linux 
- [x] **问题分类**： 模型训练与精调 
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by yuanzhiyong1999** [comment]
我将报错的两行注释掉之后
`if model.base_model.get_input_embeddings().weight.size(0)!=len(tokenizer) and training_args.do_train:
      model.base_model.resize_token_embeddings(len(tokenizer))`
爆显存了

我之前使用alpaca-lora的微调脚本时，不会爆显存，是因为deepspeed的auto调整策略不合适吗？

**Comment by iMountTai** [comment]
第一个的错误还请安装[commit id为13e53fc的Peft](https://github.com/huggingface/peft/tree/13e53fc)；
其次，alpaca-lora的脚本中，alpaca的词表大小为32000，而我们的词表大小为49554，在lora配置相同的情况下，我们的脚本所用显存明显高于alpaca-lora的脚本，建议使用更高策略的deepspeed或者更高配置的硬件

**Comment by yuanzhiyong1999** [comment]
您好，有两个问题，
1.我装了指定的peft还是同样的错误
2.之前也是使用的chinese-alpaca的词表和权重，只是微调的代码是alpcaca-lora的
3.我之前装的就是这个版本的peft，但是微调之后生成的adapter_model.bin只有4kb，我安装了0.2.0版本后解决了这个问题。如果现在装回去，可能还会出现这样的问题。
求解答！！！

**Comment by iMountTai** [comment]
1. 这个版本的peft生成的模型文件是pytorch_model.bin,不是adapter_model.bin，我不确定其他版本最后保存的是什么文件
2. 还请确定目前跑的代码及脚本是最新的，目前的代码和脚本我们已在本地和colab做了测试，均能正常运行(前提是不修改训练参数等设置)
3. 您说的安装指定的peft是同样的错误 是指OOM还是AttributeError,如果是AttributeError，peft版本可能没有正常安装，因为我测试比较新的peft版本，都会出现这个error

**Comment by yuanzhiyong1999** [comment]
我拉取了最新版本的代码，使用`pip install git+https://github.com/huggingface/peft.git@13e53fc`安装peft库之后，还是会出现这个错误
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/94682439/2741bba1-fcde-4af1-b641-841c3831aa08)

另外我是使用单机多卡，只是将脚本中的--nproc_per_node改成了2，会跟这个有关吗？

**Comment by iMountTai** [comment]
没有关系。另外，我这边一直没有复现您的问题，373行的代码和349行的代码功能是相同的，不排除是其他依赖版本不一致导致，可以先注释掉这段代码，如果出现oom的情况，还请自行调整相关参数设置

**Comment by yuanzhiyong1999** [comment]
您好，我把所有的都卸了重新装了一遍，attributeerror的错误没有了，但是还是oom。
之前使用alpaca-lora精调代码的时候，多张卡会均匀分布。但是这个使用deepspeed之后，好像是每张卡都加载同样的东西，所以显存会爆，我看了deepspeed里面batch什么的都是auto，这个手动调整的话有什么规则吗？求解答

**Comment by iMountTai** [comment]
参考[comment](https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/327#issuecomment-1546606289),同时我们的脚本设置了更新embed_tokens和lm_head，训练中会占用更多的显存，您可以设置不更新相关参数或者使用deepspeed_zero3(不保证能正常训练，可以试试)

**Comment by yuanzhiyong1999** [comment]
再次感谢您的回复，我将相关参数设置不更新之后依然有同样的问题，可能是我不熟悉deepspeed的某些机制的原因，我决定继续使用原本alpca-lora的微调代码。
谢谢！

**Comment by iMountTai** [comment]
note：alpaca_lora的代码默认load_in_8bit且没有modules_to_save设置，理论上显存占用只有全量模型的一半左右
谢谢您对我们repo的关注，周末愉快！

**Comment by yuanzhiyong1999** [comment]
感谢提醒，同祝周末愉快！
