### ISSUE TITLE
执行完 Step 2: 合并LoRA权重，生成全量模型权重，输出路径中找不到config.json，导致模型无法加载

### ISSUE THREAD

**Issue by candowu** [ymcui/Chinese-LLaMA-Alpaca#33]
does not appear to have a file named config.json.

**Comment by airaria** [comment]
请提供具体的报错信息（是Step 2报错，还是Step 2执行完了后续量化部署过程报错？Step 2执行完成后输出路径中有哪些文件？），以方便我们更准确定位问题

**Comment by wenyv** [comment]
> does not appear to have a file named config.json.

step2执行完之后输出的文件不是huggingface的格式，如果想用huggingface的框架加载的话需要把第二步输出的结果文件按照step1的方法转换成huggingface的格式，就是原README中step2后的“(可选)”

**Comment by ymcui** [comment]
> > does not appear to have a file named config.json.
> 
> step2执行完之后输出的文件是torch的原生格式，不是huggingface的格式，如果想用huggingface的框架加载的话需要把第二步输出的结果文件按照step1的方法转换成huggingface的格式，就是原README中step2后的“(可选)”

确保文件放在合适的地方了么？可以参考step 1中的文件摆放。

**Comment by wenyv** [comment]
> > > does not appear to have a file named config.json.
> > 
> > 
> > step2执行完之后输出的文件是torch的原生格式，不是huggingface的格式，如果想用huggingface的框架加载的话需要把第二步输出的结果文件按照step1的方法转换成huggingface的格式，就是原README中step2后的“(可选)”
> 
> 确保文件放在合适的地方了么？可以参考step 1中的文件摆放。

是的，我是按照step1中的方式成功导出了huggingface的文件，上面的是我给@candowu的建议 : )

**Comment by candowu** [comment]
谢谢 @wenyv
