### ISSUE TITLE
模型转换和合并:使用了merge_llama_with_chinese_lora.py合并时报错

### ISSUE THREAD

**Issue by teddyliu01** [ymcui/Chinese-LLaMA-Alpaca#331]
*提示：将[ ]中填入x，表示打对钩。提问时删除这行。只保留符合的选项。*

您好，有个问题想咨询一下：

### 详细描述问题
合并模型7b
完成第一步将原始llama转成hf格式
在第二步合并时,命令:
# python merge_llama_with_chinese_lora.py \
#     --base_model /work/models/llama/llama-7b-combine/llama-7b-hf \
#     --lora_model /work/models/llama/llama-7b-combine/chinese-llama-plus-lora-7b,
#   /work/models/llama/llama-7b-combine/chinese-alpaca-plus-lora-7b \
#     --output_type huggingface \
#     --output_dir /work/models/llama/llama-7b-combine/llama-7b-merge
错误如下：
File ~/miniconda3/envs/chinese-llama/lib/python3.10/site-packages/peft/utils/save_and_load.py:123, in set_peft_model_state_dict(model, peft_model_state_dict, adapter_name)
    120 else:
    121     raise NotImplementedError
--> 123 model.load_state_dict(peft_model_state_dict, strict=False)
    124 if isinstance(config, PromptLearningConfig):
    125     model.prompt_encoder[adapter_name].embedding.load_state_dict(
    126         {"weight": peft_model_state_dict["prompt_embeddings"]}, strict=True
    127     )

File ~/miniconda3/envs/chinese-llama/lib/python3.10/site-packages/torch/nn/modules/module.py:1671, in Module.load_state_dict(self, state_dict, strict)
   1666         error_msgs.insert(
   1667             0, 'Missing key(s) in state_dict: {}. '.format(
   1668                 ', '.join('"{}"'.format(k) for k in missing_keys)))
   1670 if len(error_msgs) > 0:
-> 1671     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   1672                        self.__class__.__name__, "\n\t".join(error_msgs)))
   1673 return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
	size mismatch for base_model.model.model.embed_tokens.modules_to_save.default.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([49953, 4096]).
	size mismatch for base_model.model.lm_head.modules_to_save.default.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([49953, 4096]).

chinese-llama-plus-lora-7b 没问题
chinese-alpaca-plus-lora-7b 报错

模型于huggingface处下载

阅读之前的问题：
https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/12
https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/281
得知模型的size确实多一位，想问一下这里应该如何处理或参照哪片文章，合并后实际的size是否是[49954, 4096]

*请尽量具体地描述您遇到的问题，**必要时给出运行命令**。这将有助于我们更快速地定位问题所在。*

**Comment by airaria** [comment]
提供一下完整的运行merge_llama_with_chinese_lora.py的输出？

**Comment by teddyliu01** [comment]
感谢回复
是这样我是先使用脚本执行，修改了权限后还是报错了，就换了notebook执行：
(chinese-llama) liuhaibo6@ZBMac-QPHQV72W2Q scripts % python merge_llama_with_chinese_lora.py \
    --base_model /Users/liuhaibo6/work/models/llama/llama-7b-combine/llama-7b-hf \
    --lora_model /Users/liuhaibo6/work/models/llama/llama-7b-combine/chinese-llama-plus-lora-7b,
 /Users/liuhaibo6/work/models/llama/llama-7b-combine/chinese-alpaca-plus-lora-7b \
    --output_type huggingface \
    --output_dir /Users/liuhaibo6/work/models/llama/llama-7b-combine/llama-7b-merge
Base model: /Users/liuhaibo6/work/models/llama/llama-7b-combine/llama-7b-hf
LoRA model(s) ['/Users/liuhaibo6/work/models/llama/llama-7b-combine/chinese-llama-plus-lora-7b']:
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.31s/it]
Peft version: 0.3.0
Loading LoRA for 7B model
Loading LoRA /Users/liuhaibo6/work/models/llama/llama-7b-combine/chinese-llama-plus-lora-7b
Extended vocabulary size to 49953
Merging with merge_and_unload...
####/Users/liuhaibo6/work/models/llama/llama-7b-combine/chinese-llama-plus-lora-7b
Saving to pth format...
Saving shard 1 of 1 into .//consolidated.00.pth
zsh: permission denied: /Users/liuhaibo6/work/models/llama/llama-7b-combine/chinese-alpaca-plus-lora-7b
(chinese-llama) liuhaibo6@ZBMac-QPHQV72W2Q scripts %

换了notebook之后：
Base model: /Users/liuhaibo6/work/models/llama/llama-7b-combine/llama-7b-hf
LoRA model(s) ['/Users/liuhaibo6/work/models/llama/llama-7b-combine/chinese-llama-plus-lora-7b', '/Users/liuhaibo6/work/models/llama/llama-7b-combine/chinese-alpaca-plus-lora-7b']:
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.78s/it]
Peft version: 0.3.0
Loading LoRA for 7B model
Loading LoRA /Users/liuhaibo6/work/models/llama/llama-7b-combine/chinese-llama-plus-lora-7b
Extended vocabulary size to 49953
Merging with merge_and_unload...
Loading LoRA /Users/liuhaibo6/work/models/llama/llama-7b-combine/chinese-alpaca-plus-lora-7b
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[9], line 44
     41 first_weight_old = first_weight.clone()
     43 if hasattr(peft.LoraModel,'merge_and_unload'):
---> 44     lora_model = PeftModel.from_pretrained(
     45         base_model,
     46         lora_model_path,
     47         device_map={"": "cpu"},
     48         torch_dtype=torch.float16,
     49     )
     50     assert torch.allclose(first_weight_old, first_weight)
     51     print(f"Merging with merge_and_unload...")

File ~/miniconda3/envs/chinese-llama/lib/python3.10/site-packages/peft/peft_model.py:181, in PeftModel.from_pretrained(cls, model, model_id, adapter_name, is_trainable, **kwargs)
    179 else:
    180     model = MODEL_TYPE_TO_PEFT_MODEL_MAPPING[config.task_type](model, config, adapter_name)
--> 181 model.load_adapter(model_id, adapter_name, **kwargs)
    182 return model

File ~/miniconda3/envs/chinese-llama/lib/python3.10/site-packages/peft/peft_model.py:376, in PeftModel.load_adapter(self, model_id, adapter_name, is_trainable, **kwargs)
    372 adapters_weights = torch.load(
    373     filename, map_location=torch.device("cuda" if torch.cuda.is_available() else "cpu")
    374 )
    375 # load the weights into the model
--> 376 set_peft_model_state_dict(self, adapters_weights, adapter_name=adapter_name)
    377 if (
    378     (getattr(self, "hf_device_map", None) is not None)
    379     and (len(set(self.hf_device_map.values()).intersection({"cpu", "disk"})) > 0)
    380     and len(self.peft_config) == 1
    381 ):
    382     device_map = kwargs.get("device_map", "auto")

File ~/miniconda3/envs/chinese-llama/lib/python3.10/site-packages/peft/utils/save_and_load.py:123, in set_peft_model_state_dict(model, peft_model_state_dict, adapter_name)
    120 else:
    121     raise NotImplementedError
--> 123 model.load_state_dict(peft_model_state_dict, strict=False)
    124 if isinstance(config, PromptLearningConfig):
    125     model.prompt_encoder[adapter_name].embedding.load_state_dict(
    126         {"weight": peft_model_state_dict["prompt_embeddings"]}, strict=True
    127     )

File ~/miniconda3/envs/chinese-llama/lib/python3.10/site-packages/torch/nn/modules/module.py:1671, in Module.load_state_dict(self, state_dict, strict)
   1666         error_msgs.insert(
   1667             0, 'Missing key(s) in state_dict: {}. '.format(
   1668                 ', '.join('"{}"'.format(k) for k in missing_keys)))
   1670 if len(error_msgs) > 0:
-> 1671     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   1672                        self.__class__.__name__, "\n\t".join(error_msgs)))
   1673 return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
	size mismatch for base_model.model.model.embed_tokens.modules_to_save.default.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([49953, 4096]).
	size mismatch for base_model.model.lm_head.modules_to_save.default.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([49953, 4096]).

**Comment by airaria** [comment]
你的notebook中在加载每个LoRA之前，是否执行了如下resize embedding的代码？
https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/ac544b577779f1b912f489edd0f151dba8ac647a/scripts/merge_llama_with_chinese_lora.py#L239-L242

**Comment by teddyliu01** [comment]
感谢回复，根据回复的代码段我打印了比对的size，tokenizer.model的版本放混了，改了之后问题解决。
