### ISSUE TITLE
size mismatch 错误

### ISSUE THREAD

**Issue by statsmind** [ymcui/Chinese-LLaMA-Alpaca#334]
这个合并的命令，llama-13b-hf 从 decapoda-research/llama-13b-hf 下载
python ~/chinese-llama-alpaca/scripts/merge_llama_with_chinese_lora.py --base_model llama-13b-hf --lora_model chinese_llama_lora_13b,chinese_alpaca_lora_13b --output_type huggingface --output_dir merged

执行命令
python generate.py --load_8bit --base_model /mnt/g/llama/merged

  File "/home/james/.conda/envs/alpaca/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 123, in set_peft_model_state_dict
    model.load_state_dict(peft_model_state_dict, strict=False)
  File "/home/james/.conda/envs/alpaca/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
	size mismatch for base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight: copying a param with shape torch.Size([16, 4096]) from checkpoint, the shape in current model is torch.Size([16, 5120]).
	size mismatch for base_model.model.model.layers.0.self_attn.q_proj.lora_B.default.weight: copying a param with shape torch.Size([4096, 16]) from checkpoint, the shape in current model is torch.Size([5120, 16]).
	size mismatch for base_model.model.model.layers.0.self_attn.k_proj.lora_A.default.weight: copying a param with shape torch.Size([16, 4096]) from checkpoint, the shape in current model is torch.Size([16, 5120]).
	size mismatch for base_model.model.model.layers.0.self_attn.k_proj.lora_B.default.weight: copying a param with shape torch.Size([4096, 16]) from checkpoint, the shape in current model is torch.Size([5120, 16]).
	size mismatch for base_model.model.model.layers.0.self_attn.v_proj.lora_A.default.weight: copying a param with shape torch.Size([16, 4096]) from checkpoint, the shape in current model is torch.Size([16, 5120]).
	size mismatch for base_model.model.model.layers.0.self_attn.v_proj.lora_B.default.weight: copying a param with shape torch.Size([4096, 16]) from checkpoint, the shape in current model is torch.Size([5120, 16]).
	size mismatch for base_model.model.model.layers.0.self_attn.o_proj.lora_A.default.weight: copying a param with shape torch.Size([16, 4096]) from checkpoint, the shape in current model is torch.Size([16, 5120]).
	size mismatch for base_model.model.model.layers.0.self_attn.o_proj.lora_B.default.weight: copying a param with shape torch.Size([4096, 16]) from checkpoint, the shape in current model is torch.Size([5120, 16]).

请问这是什么原因？

**Comment by iMountTai** [comment]
`generate.py`这不是我们的代码吧？

**Comment by statsmind** [comment]
alpaca-lora 原本的代码

**Comment by airaria** [comment]
检查一下模型权重，看起来13B和7B的权重/配置被混淆了
