### ISSUE TITLE
调用run_clm_sft_with_peft.py没有生成正确格式的模型

### ISSUE THREAD

**Issue by extrame** [ymcui/Chinese-LLaMA-Alpaca#335]
使用run_clm_sft_with_peft.py在合并的7b模型上再进行精调

运行成功，但是最后提示

Trainer.model is not a `PreTrainedModel`, only saving its state dict.

我看生成目录中文件也不是特别一致，缺config.json, generation_config.json等文件。

是需要额外运行什么命令么

**Comment by extrame** [comment]
对比了一下官方的run_clm.py, 似乎是缺少这一段？

``` python
    kwargs = {"finetuned_from": model_args.model_name_or_path, "tasks": "text-generation"}
    if data_args.dataset_name is not None:
        kwargs["dataset_tags"] = data_args.dataset_name
        if data_args.dataset_config_name is not None:
            kwargs["dataset_args"] = data_args.dataset_config_name
            kwargs["dataset"] = f"{data_args.dataset_name} {data_args.dataset_config_name}"
        else:
            kwargs["dataset"] = data_args.dataset_name

    if training_args.push_to_hub:
        trainer.push_to_hub(**kwargs)
    else:
        trainer.create_model_card(**kwargs)
```

**Comment by iMountTai** [comment]
1. 提示是INFO内容，不是error
2. 因为peft版本的原因，我们的脚本最终生成的模型文件为`pytorch_model.bin`，保存了可训练参数的权重，您可将该权重与llama-hf合并得到您精调的模型

**Comment by extrame** [comment]
好的，

几个问题哈，

1）那我是在合并之后的模型基础上微调的，是不是应该和合并后的模型再合并，而不是去和原版llama-hf合并？
2）合并还是用merge_llama_with_chinese_lora.py么

**Comment by airaria** [comment]
> 好的，
> 
> 几个问题哈，
> 
> 1）那我是在合并之后的模型基础上微调的，是不是应该和合并后的模型再合并，而不是去和原版llama-hf合并？ 2）合并还是用merge_llama_with_chinese_lora.py么

1) 对，你基于什么模型训练，就和什么模型去合并
2) 可以用merge_llama_with_chinese_lora.py，但需要准备好相关模型权重和配置文件，仿照我们发布的LoRA的内容即可。
