### ISSUE TITLE
模型训练与精调可以使用CPU来做吗？要怎么样设置？

### ISSUE THREAD

**Issue by zhuluxx** [ymcui/Chinese-LLaMA-Alpaca#346]
现有的服务器GPU内存不够，请问模型训练与精调可以使用CPU来做吗？要怎么样设置？
https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E9%A2%84%E8%AE%AD%E7%BB%83%E8%84%9A%E6%9C%AC

**Comment by ymcui** [comment]
CPU精调目前只存在理论可能，但实际上基本不可行。
llama.cpp那边似乎在考虑把CPU精调功能加入，但目前没有什么明确进展。

**Comment by zhuluxx** [comment]
> CPU精调目前只存在理论可能，但实际上基本不可行。 llama.cpp那边似乎在考虑把CPU精调功能加入，但目前没有什么明确进展。

感谢解惑！

**Comment by yaleimeng** [comment]
如果你能接受1个epoch以年为单位的话，或许有可能。
