### ISSUE TITLE
请问使用13B进行微调需要多大显存？

### ISSUE THREAD

**Issue by dhhcj** [ymcui/Chinese-LLaMA-Alpaca#347]
使用batch size 为 1在单卡 v100 训练时显示显存不够用，请问单卡需要多大的显存才能训练的动？
如果为训练使用的参数，pretrained_model 为 Chinese-LLaMA-Plus-13B，Chinese-Alpaca-Plus-13B 与本体13B合并后的模型 
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/26632100/9756e15a-c65f-4dde-b69f-7897a335d88c)

**Comment by ymcui** [comment]
V100，16G吗？那大概是不够的。8bit下单独加载模型就需要至少15G，就更别说包含其他训练需要存储的状态/梯度了。

参考：https://github.com/ymcui/Chinese-LLaMA-Alpaca#脚注及其他说明

**Comment by dhhcj** [comment]
> V100，16G吗？那大概是不够的。8bit下单独加载模型就需要至少15G，就更别说包含其他训练需要存储的状态/梯度了。
> 
> 参考：[https://github.com/ymcui/Chinese-LLaMA-Alpaca#脚注及其他说明](https://github.com/ymcui/Chinese-LLaMA-Alpaca#%E8%84%9A%E6%B3%A8%E5%8F%8A%E5%85%B6%E4%BB%96%E8%AF%B4%E6%98%8E)

32G的V100，但是还是报了显存泄露的错误，我不确定，我设置的参数有没有问题=，=

**Comment by dhhcj** [comment]
> V100，16G吗？那大概是不够的。8bit下单独加载模型就需要至少15G，就更别说包含其他训练需要存储的状态/梯度了。
> 
> 参考：[https://github.com/ymcui/Chinese-LLaMA-Alpaca#脚注及其他说明](https://github.com/ymcui/Chinese-LLaMA-Alpaca#%E8%84%9A%E6%B3%A8%E5%8F%8A%E5%85%B6%E4%BB%96%E8%AF%B4%E6%98%8E)

您给的这个链接不是显存吧，是内存和空间占用的大小吧

**Comment by ymcui** [comment]
是空间大小，但是显存也是可以通过这个表做一个粗略的估计。32G看起来应该是可以训练的，不过可能要找到合适的超参。
其余的就得自己想办法降显存占用了，可以参考transformers库的一些通用降显存的方法，或者deepspeed上zero3。

**Comment by LivinLuo1993** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/44887637/9334629d-215c-4ed1-93f7-a74f571d0b78)
默认参数上40G A100也不得行

**Comment by dhhcj** [comment]
> 我们提供的脚本中默认是训练embed_tokens和lm_head的，这两个矩阵参数量较大。如果显存不足，可以尝试不训练embed_tokens和lm_head，将SFT代码中(365~371行）
> 
> ```
>         peft_config = LoraConfig(
>             task_type=TaskType.CAUSAL_LM, 
>             target_modules=target_modules,
>             inference_mode=False, 
>             r=lora_rank, lora_alpha=lora_alpha, 
>             lora_dropout=lora_dropout,
>             modules_to_save=modules_to_save)
> ```
> 
> 的`module_to_save`赋值为`None`
> 
> ```python
>             modules_to_save=None)
> ```
> 
> 即可。

那你们是拿80G的A100训的吗？

**Comment by dhhcj** [comment]
> > 我们提供的脚本中默认是训练embed_tokens和lm_head的，这两个矩阵参数量较大。如果显存不足，可以尝试不训练embed_tokens和lm_head，将SFT代码中(365~371行）
> > ```
> >         peft_config = LoraConfig(
> >             task_type=TaskType.CAUSAL_LM, 
> >             target_modules=target_modules,
> >             inference_mode=False, 
> >             r=lora_rank, lora_alpha=lora_alpha, 
> >             lora_dropout=lora_dropout,
> >             modules_to_save=modules_to_save)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 的`module_to_save`赋值为`None`
> > ```python
> >             modules_to_save=None)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 即可。
> 
> 那你们是拿80G的A100训的吗？

改完之后报错了
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/26632100/7a3b537c-ab02-4893-b170-b61a6cdb807c)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/26632100/60d19fbe-c1dc-4948-8a30-dac73850dc78)
训练方法用的是第二种方式
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/26632100/0a010207-5fe6-4aaf-8974-771c8e03e1bd)
因为第一种方式还是报的显存不足，即便在代码中把modules_to_save 改为了None
环境应该没有问题，因为我昨天训练过7B并且也推理成功了

**Comment by zhangfan-algo** [comment]
> 默认配置的训练 需要多少显存呀
