### ISSUE TITLE
Wiki: 与LangChain进行集成文档错误

### ISSUE THREAD

**Issue by tluo-github** [ymcui/Chinese-LLaMA-Alpaca#356]
### 详细描述问题

[与LangChain进行集成文档
](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E4%B8%8ELangChain%E8%BF%9B%E8%A1%8C%E9%9B%86%E6%88%90)

--embedding_path = text2vec-large-chinese  在 google colab 中运行报错 401,需改成 --embedding_path 'GanymedeNil/text2vec-large-chinese'

### 运行截图或日志
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/5242590/256a91fb-2b0f-425a-ab48-74d3aa881fcb)

**Comment by airaria** [comment]
你好，我们这里是假设用户已经把text2vec-large-chinese下载到了本地
不过感谢提醒，我们会在文档中明确说明。

**Comment by tluo-github** [comment]
@airaria 您好，我是在 google colab 运行，目前遇见 GPU 显存 OOM, 请问一下，需要多少，已经能否提供一个 notebook 哈

**Comment by tluo-github** [comment]
我在 google colab A100 上成功运行了，以下是 notebook
https://colab.research.google.com/drive/1U8iZOP2xJ2abTbMqoVqS1z4Rk37lp1HB?usp=sharing
