### ISSUE TITLE
4核32G运行13B量化模型响应速度20s+

### ISSUE THREAD

**Issue by alanbeen** [ymcui/Chinese-LLaMA-Alpaca#357]
启动命令是这个
python3 server.py --model 13B  --cpu --listen --api --chat
需要什么样的配置才能提高运行速度

**Comment by iMountTai** [comment]
可以去掉--cpu使用GPU推理，具体操作文档还请参考[webui docs](https://github.com/oobabooga/text-generation-webui/tree/main/docs)

**Comment by yaleimeng** [comment]
大显存的高端GPU才能跑起来。。7b能在合理时间内回复就谢天谢地了。。还13b，

**Comment by alanbeen** [comment]
> 大显存的高端GPU才能跑起来。。7b能在合理时间内回复就谢天谢地了。。还13b，

你知道A10 24G显存响应速度会有多快，打算买个好些的服务器

**Comment by alanbeen** [comment]
> 可以去掉--cpu使用GPU推理，具体操作文档还请参考[webui docs](https://github.com/oobabooga/text-generation-webui/tree/main/docs)

我的是没有GPU的centos阿里云服务，你有尝试过GPU要多少跑的会快些的吗

**Comment by yaleimeng** [comment]
我使用1张24GB的3090，在7b上面推理，大部分响应在1~3秒，个别会长一点。单人使用算是能接受的范围。

**Comment by 1979435** [comment]
有没有在arm架构上跑的性价比比较高的方案

**Comment by alanbeen** [comment]
> 我使用1张24GB的3090，在7b上面推理，大部分响应在1~3秒，个别会长一点。单人使用算是能接受的范围。

13B的话正常推理会慢一半吧

**Comment by notsb** [comment]
> 

你好，24G显存可以实现微调吗？
