### ISSUE TITLE
weight must be 2-D error

### ISSUE THREAD

**Issue by hjc3613** [ymcui/Chinese-LLaMA-Alpaca#359]
### 详细描述问题

执行 run_sft.sh时，报错：
![lADPJw1WXOIi_t7NC7jND6A_4000_3000](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/37894838/f44829b7-59cd-4b8d-a9da-c74af5e0566c)

注：我用的deepspeed stage 3，配置项：
![lADPD3Ir4Ac3YyfNBgDNCAA_2048_1536](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/37894838/44dd6efb-f6f5-4173-81db-9b1cee17bc7f)

run_sft.sh脚本内容为：
![lADPKHCb1T-6iuXNBgDNCAA_2048_1536](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/37894838/bfe4e502-8fc6-4c5c-9d56-c8b75f8ed32d)
run_sft.sh与原始内容的差异在于我去掉了peft_path，让模型重新初始化，其它的基本没变动
### 必查项目（前三项只保留你要问的）

- [ √] **基础模型**：Alpaca-Plus
- [ √] **运行系统**：Linux 
- [ √] **问题分类**： 模型训练与精调 
- [ √] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ √] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ √] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by airaria** [comment]
是stage 3下才有的错误吗，stage 2能跑么？

**Comment by hjc3613** [comment]
> 是stage 3下才有的错误吗，stage 2能跑么？

stage2下没跑，因为单卡现存小，只有12G，会爆显存，一共6张12G的卡，貌似只能尝试stage3，我想在CPU下调试，但是加了--no_cuda后不起作用，依然会挪到GPU上，如果方便的话，麻烦告知一下怎么在cpu上跑？

**Comment by airaria** [comment]
合并没有问题。

没有在CPU上跑过，你可以google一下报错信息，或许能有帮助。

**Comment by hjc3613** [comment]
> 
查到一些信息：是因为用了stage3，有人跟我遇到一样的情况：https://github.com/huggingface/transformers/issues/22705，https://github.com/microsoft/DeepSpeed/issues/842，https://discuss.huggingface.co/t/deepspeed-zero3-does-not-work-with-diffusion-models-does-anyone-know-how-to-fix-this/36293，楼主如果能有解决方案的话，烦请及时告知，不胜感激。
