### ISSUE TITLE
About the model output.

### ISSUE THREAD

**Issue by Destking** [ymcui/Chinese-LLaMA-Alpaca#36]
这是我Alpaca和LLaMA合并后模型的输出结果，想问问这种输出是正常的吗？还是我可能在哪一步制造了错误？（我是在windows下用cmake编译的llama.cpp，但我想这一步应该没有影响）
![image](https://user-images.githubusercontent.com/33406125/229440701-613e9f30-8bdb-4b63-a708-c22ab363f6fd.png

**Comment by airaria** [comment]
参见置顶issue #11
