### ISSUE TITLE
请问通过run_pt.sh后得到的参数，哪个文件是参数的增量呀

### ISSUE THREAD

**Issue by sixgold993** [ymcui/Chinese-LLaMA-Alpaca#361]
<img width="344" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/38970047/7e50406f-a2eb-46b4-8701-820d1a1c4285">
目前跑完得到了pytorch_model.bin、training_args.bin。 
我想把新改动合并到启动脚本时的基线上，上面这两个文件是哪一个作为合并的对象呀。 这两个文件是什么含义呀

**Comment by airaria** [comment]
新建一个文件夹，把`pytorch_model.bin`放进去并改名`adapter_model.bin`，并补齐其他tokenizer和config文件，使得文件夹内容与我们发布的如Chinese-LLaMA-LoRA-7b一致。大致流程如下：
```bash
mkdir lora_model
cp pytorch_model.bin lora_model/adapter_model.bin
cp Chinese-LLaMA-LoRA-7b/adapter_config.json lora_model/
cp Chinese-LLaMA-LoRA-7b/*token* lora_model/
```
其中你需要修改`adapter_config.json`中的LoRA参数，以和你训练时用的参数保持一致。
之后就可以用merge_llama_with_chinese_lora.py合并了

我们之后会在wiki中更新相关流程说明。

**Comment by sixgold993** [comment]
好的，理解了，关于文件大小有一些疑问。我用的是data/pt_sample_data.txt 下的数据，这个数据看起来很小。为什么这个lora文件有1.6G这么大呀。  我的basemodel用的是（Llama原版+7B 20G的Lora 的合并）。我看之前20G的中文数据跑出来的大小才800M。

**Comment by airaria** [comment]
可能因为存下来是float32格式。你可以载入并check一下各个参数的dtype看看是不是float32

**Comment by liguodongiot** [comment]
> 新建一个文件夹，把`pytorch_model.bin`放进去并改名`adapter_model.bin`，并补齐tokenizer相关和config相关文件，使得文件夹内容与我们发布的如Chinese-LLaMA-LoRA-7b一致。大致流程如下：
> 
> ```shell
> mkdir lora_model
> cp pytorch_model.bin lora_model/adapter_model.bin
> cp Chinese-LLaMA-LoRA-7b/adapter_config.json lora_model/
> cp Chinese-LLaMA-LoRA-7b/*token* lora_model/
> ```
> 
> 其中你需要修改`adapter_config.json`中的LoRA参数，以和你训练时用的参数保持一致。 之后就可以用merge_llama_with_chinese_lora.py合并了
> 
> 我们之后会在wiki中更新相关流程说明。

@airaria 建议直接使用`model.save_pretrained(training_args.output_dir + "/lora")`保存为 adapter_config.json  和adapter_model.bin ，后续直接指定lora目录就可以了，避免拷贝。

**Comment by kevinuserdd** [comment]
> 依照方法复制了文件后合并模型报错 ![image](https://user-images.githubusercontent.com/19159781/240542263-b9c9827b-2ebe-4068-838c-095a31483485.png)

同样的错误，怎么解决的

**Comment by sszyl** [comment]
> > 依照方法复制了文件后合并模型报错 ![image](https://user-images.githubusercontent.com/19159781/240542263-b9c9827b-2ebe-4068-838c-095a31483485.png)
> 
> 同样的错误，怎么解决的

我放弃了，暂时不训embed_tokens 和 lm_head了，期待解决。

**Comment by liguodongiot** [comment]
@sszyl @kevinuserdd 

代码：
https://github.com/liguodongiot/llm-action/blob/main/chinese-llama-alpaca/merge_llama_with_chinese_lora.py

教程：
[中文LLaMA&Alpaca大语言模型词表扩充+预训练+指令精调
](https://zhuanlan.zhihu.com/p/631360711)
