### ISSUE TITLE
使用的语料

### ISSUE THREAD

**Issue by qwjaskzxl** [ymcui/Chinese-LLaMA-Alpaca#365]
请问alpaca-plus使用的语料是[nlp_chinese_corpus](https://github.com/brightmart/nlp_chinese_corpus)构造的吗？还是pclue吗

**Comment by ymcui** [comment]
你指的是指令数据吗？pCLUE在基础版和plus版都用了，但只用了很少一部分，因为有许多数据构造的都比较“机械式”。
大部分还是来自ChatGPT爬取的数据。

**Comment by qwjaskzxl** [comment]
get~那预训练语料主要是[nlp_chinese_corpus](https://github.com/brightmart/nlp_chinese_corpus)吗？不过似乎没有120g诶

**Comment by ymcui** [comment]
并不是。预训练语料主要以cc、百科、新闻等数据构成（无法提供下载），是我们推出的中文NLU系列预训练模型使用的。感兴趣可以看我们的其他repo。
