### ISSUE TITLE
--modules_to_save 改为None后报错

### ISSUE THREAD

**Issue by dhhcj** [ymcui/Chinese-LLaMA-Alpaca#367]
无论是7B还是13B，将modules_to_save 改为None后都报了错
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/26632100/a730b254-c7ca-4492-b356-4cc3e4235b42)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/26632100/ab058199-4943-4007-ad93-5508eda4e4c0)

**Comment by iMountTai** [comment]
在[这行](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/3e2f2529a4dc0d7567f46f1b2d3431a7d063588b/scripts/run_clm_sft_with_peft.py#L361)后面直接加`modules_to_none=None`试试

**Comment by iMountTai** [comment]
另外尝试将gradient_checkpointing关掉试试

**Comment by dhhcj** [comment]
> 在[这行](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/3e2f2529a4dc0d7567f46f1b2d3431a7d063588b/scripts/run_clm_sft_with_peft.py#L361)后面直接加`modules_to_save=None`试试或者将gradient_checkpointing关掉 因为项目本身的需求，我们将代码进行了适配，如要求peft版本、deepspeed等，因此可能因为训练参数的改动(如可训参数设置)导致代码出现error ，还请见谅~ 😬

您好，我已经安装好你们提到的peft版本了，但是deepspeed，还有其他的库都是什么版本呀
[commit id为13e53fc的Peft](https://github.com/huggingface/peft/tree/13e53fc)

**Comment by iMountTai** [comment]
其他依赖的版本没有明确要求

**Comment by dhhcj** [comment]
> 其他依赖的版本没有明确要求

但是。。还是报错了呀，能帮忙分析下原因吗

**Comment by iMountTai** [comment]
如果设置了modules_to_save=None,就把gradien_checkpointing关闭

**Comment by dhhcj** [comment]
> 如果设置了modules_to_save=None,就把gradien_checkpointing关闭

我看了一下和我报错相同的issue，也观察了下内存，确实内存干满了，服务器才配了40g内存，请问如果像训练通13B模型需要多大的内存呀

https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/354

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/26632100/2ab57ff4-daca-473a-b5c9-541bfdd1d269)

**Comment by airaria** [comment]
> > 如果设置了modules_to_save=None,就把gradien_checkpointing关闭
> 
> 我看了一下和我报错相同的issue，也观察了下内存，确实内存干满了，服务器才配了40g内存，请问如果像训练通13B模型需要多大的内存呀
> 
> #354
> 
> ![image](https://user-images.githubusercontent.com/26632100/239172686-2ab57ff4-daca-473a-b5c9-541bfdd1d269.png)

把deepspeed的offload打开试试
