### ISSUE TITLE
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'

### ISSUE THREAD

**Issue by ccdf1137** [ymcui/Chinese-LLaMA-Alpaca#368]
我是直接 pip install DeepSpeed 的   安装的 deepspeed=0.9.2，是否是版本的问题？

**Comment by iMountTai** [comment]
环境问题，可参考[deepspeed issues](https://github.com/microsoft/DeepSpeed/issues/1846)或其他相关文档

**Comment by ccdf1137** [comment]
apt安装python3.x-dev

git clone https://github.com/microsoft/DeepSpeed.git
cd DeepSpeed
DS_BUILD_CPU_ADAM=1 DS_BUILD_AIO=1 DS_BUILD_UTILS=1 pip install -e .
成功安装
