### ISSUE TITLE
模型合并时报错，ValueError: weight is on the meta device, we need a `value` to put in on cpu.

### ISSUE THREAD

**Issue by quanzhang2020** [ymcui/Chinese-LLaMA-Alpaca#369]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/69777965/6b28fd1e-b7cd-4ca1-92d1-e073843bfab1)

**Comment by nicole828** [comment]
> ![image](https://user-images.githubusercontent.com/69777965/238917352-6b28fd1e-b7cd-4ca1-92d1-e073843bfab1.png)

请问一下，您是用原版模型进行合并的吗？
