### ISSUE TITLE
通过SentencePiece训练的tokenizer，合并没有问题，但是run_clm加载出错。

### ISSUE THREAD

**Issue by AceCHQ** [ymcui/Chinese-LLaMA-Alpaca#370]
### 详细描述问题
通过SentencePiece训练的tokenizer，合并没有问题，但是run_clm加载出错，Error如下，请问可以如何解决，感谢！！
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
 what():  CUDA error: an illegal memory access was encountered

**Comment by iMountTai** [comment]
建议贴出完整的运行脚本及训练日志
