### ISSUE TITLE
12G*4怎么运行7B的继续预训练？

### ISSUE THREAD

**Issue by huangxd-** [ymcui/Chinese-LLaMA-Alpaca#372]
求教，本人显卡比较老，k80的，12G*4，跑7B的run_pt.sh会发生OOM
请问有什么方式能在这张显卡上跑起来吗？8bit？

**Comment by airaria** [comment]
可以尝试打开Deepspeed的offload参数，或者用ZeRO-3 能不能跑，有人似乎会遇到问题 (#359)，不过你可以试一下

**Comment by huangxd-** [comment]
使用 https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/379 里的参数配置成功了
