### ISSUE TITLE
llama.cpp模型转换失败：.pth模型权重转换为ggml的FP16格式

### ISSUE THREAD

**Issue by chandlerln** [ymcui/Chinese-LLaMA-Alpaca#374]
*提示：将[ ]中填入x，表示打对钩。提问时删除这行。只保留符合的选项。*

### 详细描述问题

*请尽量具体地描述您遇到的问题，**必要时给出运行命令**。这将有助于我们更快速地定位问题所在。*

### 运行截图或日志

*请提供文本log或者运行截图，以便我们更好地了解问题详情。*

### 必查项目（前三项只保留你要问的）

- [ ] **基础模型**：LLaMA 
- [ ] **运行系统**：Linux 
- [ ] **问题分类**：模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat）
python3.9 convert.py llama_fp_video_tagsv1v2_20230427_checkpoiont
Loading model file llama_fp_video_tagsv1v2_20230427_checkpoiont/consolidated.00.pth
Traceback (most recent call last):
  File "/data02/home/linxuewen/tools/llama.cpp/convert.py", line 1168, in <module>
    main()
  File "/data02/home/linxuewen/tools/llama.cpp/convert.py", line 1148, in main
    model_plus = load_some_model(args.model)
  File "/data02/home/linxuewen/tools/llama.cpp/convert.py", line 1074, in load_some_model
    models_plus.append(lazy_load_file(path))
  File "/data02/home/linxuewen/tools/llama.cpp/convert.py", line 864, in lazy_load_file
    return lazy_load_torch_file(fp, path)
  File "/data02/home/linxuewen/tools/llama.cpp/convert.py", line 736, in lazy_load_torch_file
    model = unpickler.load()
  File "/data02/home/linxuewen/tools/llama.cpp/convert.py", line 725, in find_class
    return self.CLASSES[(module, name)]
KeyError: ('torch.nn.modules.sparse', 'Embedding')

**Comment by ymcui** [comment]
合并的具体是哪一个模型，怎么合并的？麻烦贴出具体命令。
另外，llama.cpp近期改动较大，确保pull最新代码并make clean && make

**Comment by chandlerln** [comment]
CLASSES: Dict[Any, Any] = {
        ('torch._tensor', '_rebuild_from_type_v2'): rebuild_from_type_v2,
        ('torch._utils', '_rebuild_tensor_v2'): lazy_rebuild_tensor_v2,
        ('torch', 'BFloat16Storage'): LazyStorageKind(DT_BF16),
        ('torch', 'HalfStorage'): LazyStorageKind(DT_F16),
        ('torch', 'FloatStorage'): LazyStorageKind(DT_F32),
        ('torch', 'IntStorage'): LazyStorageKind(DT_I32),
        ('torch', 'Tensor'): LazyTensor,
    }

    def find_class(self, module: str, name: str) -> Any:
	if not module.startswith('torch'):
            return super().find_class(module, name)
        return self.CLASSES[(module, name)]

看着上面的报错 是不能解析 ('torch.nn.modules.sparse', 'Embedding') ？

**Comment by chandlerln** [comment]
f



from transformers import LlamaTokenizer, LlamaForCausalLM,LlamaConfig
model = LlamaForCausalLM.from_pretrained(
            model_name_or_path,
            torch_dtype = torch.float16
        )
torch.save(model,outpath)
或者
from transformers import LlamaTokenizer, LlamaForCausalLM,LlamaConfig
model = transformers.AutoModelForCausalLM.from_pretrained(
        model_args.model_name_or_path,
        cache_dir=training_args.cache_dir,
    )
torch.save(model,outpath)
预训练后，导出的模型pth，convert.py都会失败。
报错：KeyError: ('torch.nn.modules.sparse', 'Embedding')
预训练后，是不能再用llama.cpp做转换？没法量化了么？
@ymcui

**Comment by ymcui** [comment]
没碰到过这个问题，无法给出确切回答。建议你整理一下这些过程。比如，
1）你是用什么脚本继续训练的？继续训练了哪个模型？训练脚本怎么设置的？
2）保存成pth之后，llama.cpp的convert.py脚本可以指定`--dump`参数，查看pth权重文件里的tensor大小等信息，可以自己排查一下是否有异常的地方。

**Comment by chandlerln** [comment]
1) 
训练脚本：
from transformers import LlamaTokenizer, LlamaForCausalLM,LlamaConfig
model = transformers.AutoModelForCausalLM.from_pretrained(
model_args.model_name_or_path,
cache_dir=training_args.cache_dir,
)
torch.save(model,outpath)
2)继续训练的模型：
origin7b/chinese_llama_plus_lora_7b/chinese_alpaca_plus_lora_7b 这三个merge在一起的
3)训练脚本看上面那个，其实就transformers导入+torch导出后，就不行了。
4)异常就是模型里面多了一些('torch.nn.modules.sparse', 'Embedding')这种结构，llama.cpp不支持解析
@ymcui 
或者可以提供下你们的训练脚本么？训练完还能做llama.cpp的量化部署的

**Comment by ymcui** [comment]
1）如果你不做训练，我们的模型能否正常被llama.cpp加载？
2）你给出的训练脚本实在看不出来是从哪里获取的，还是建议使用我们提供的训练脚本，其他的脚本我们无法一一协助测试。
2）我们的训练脚本在wiki中已经说明了：https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/训练细节

**Comment by chandlerln** [comment]
1)不做训练，模型可以正常llama.cpp加载 
2)谢谢，我们试试
