### ISSUE TITLE
如何用transformer加载量化后的模型

### ISSUE THREAD

**Issue by hrz394943230** [ymcui/Chinese-LLaMA-Alpaca#377]
运行convert_and_quantize_chinese_alpaca_plus之后得到ggml-model-q8_0.bin文件
用transformer进行加载
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/28583005/0d32bd7c-5d3f-450b-9fe6-b443fef28769)
结果报错
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/28583005/029e45f5-021f-4380-8b63-c0c34007e1f3)
路径中的文件目录如下
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/28583005/6ddb8852-3019-426d-9865-9a445f8472f9)
pytorch_model.bin 是我把ggml-model-q8_0.bin改的名字
请问如何修改可以运行？
通过inference_hf脚本运营也是这样，但是在convert的文件中检测是可以正常输出的
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/28583005/9d3be125-2f80-4292-a225-35bf4539700f)

**Comment by airaria** [comment]
量化后的模型没法通过transformers加载，只能用llama.cpp
如果想通过python调用，可以尝试类似llama-cpp-python之类的接口
