### ISSUE TITLE
llama.cpp编译部署后无法使用

### ISSUE THREAD

**Issue by Lyugq** [ymcui/Chinese-LLaMA-Alpaca#380]
我在使用Chinese-alpaca-plus-13B版本，按照教程合并了模型，使用llama.cpp部署后，在windows10系统上使用cmd运行案例给出的main -m指令。cmd输出了alpaca.txt中的一段英文，然后输出>让我输入。这个时候无论我输入什么，按下回车之后cmd就像卡死一样，没有任何输出。
光标一直闪烁
![无标题](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/54970881/33073c0c-4b3a-4176-b806-9b53fc5f8f2a)

**Comment by ymcui** [comment]
https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/315
