### ISSUE TITLE
多gpu运行时，一直处于datasets.arrow_dataset - Concatenating 8 shards 没反馈

### ISSUE THREAD

**Issue by DendiHust** [ymcui/Chinese-LLaMA-Alpaca#381]
### 指令微调chinese_alpaca_plus_lora_7b时，单节点多gpu运行时，数据处理之后一直处于datasets.arrow_dataset - Concatenating 8 shards 没反馈
日志如下：
`
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[2023-05-18 13:54:51,409] [INFO] [comm.py:622:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
05/18/2023 13:54:52 - WARNING - __main__ - Process rank: 2, device: cuda:2, n_gpu: 1distributed training: True, 16-bits training: True
05/18/2023 13:54:52 - WARNING - __main__ - Process rank: 1, device: cuda:1, n_gpu: 1distributed training: True, 16-bits training: True
05/18/2023 13:54:53 - WARNING - __main__ - Process rank: 3, device: cuda:3, n_gpu: 1distributed training: True, 16-bits training: True
05/18/2023 13:54:54 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: True
[INFO|configuration_utils.py:666] 2023-05-18 13:54:54,984 >> loading configuration file /home/qizhen/pre_models/ymcui/merged/Chinese-LLaMA-Plus/config.json
[INFO|configuration_utils.py:720] 2023-05-18 13:54:54,986 >> Model config LlamaConfig {
  "_name_or_path": "/home/qizhen/pre_models/ymcui/merged/Chinese-LLaMA-Plus",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 0,
  "eos_token_id": 1,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 2048,
  "max_sequence_length": 2048,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "pad_token_id": -1,
  "rms_norm_eps": 1e-06,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.28.1",
  "use_cache": true,
  "vocab_size": 49953
}

[INFO|tokenization_utils_base.py:1807] 2023-05-18 13:54:54,987 >> loading file tokenizer.model
[INFO|tokenization_utils_base.py:1807] 2023-05-18 13:54:54,987 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1807] 2023-05-18 13:54:54,987 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1807] 2023-05-18 13:54:54,987 >> loading file tokenizer_config.json
05/18/2023 13:54:55 - INFO - __main__ - training files: /home/qizhen/llm/qizhenllm/data/eval/sft_val.json
05/18/2023 13:54:55 - WARNING - root - building dataset...
05/18/2023 13:54:56 - INFO - datasets.builder - Using custom data configuration default-637dacf74c2e2d00
05/18/2023 13:54:56 - INFO - datasets.info - Loading Dataset Infos from /home/qizhen/anaconda3/envs/qizhenllm/lib/python3.8/site-packages/datasets/packaged_modules/json
05/18/2023 13:54:56 - INFO - datasets.builder - Generating dataset json (/home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
Downloading and preparing dataset json/default to /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51...
Downloading data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 2987.40it/s]
05/18/2023 13:54:56 - INFO - datasets.download.download_manager - Downloading took 0.0 min
05/18/2023 13:54:56 - INFO - datasets.download.download_manager - Checksum Computation took 0.0 min
Extracting data files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 537.46it/s]
05/18/2023 13:54:56 - INFO - datasets.builder - Generating train split
05/18/2023 13:54:56 - INFO - datasets.utils.info_utils - Unable to verify splits sizes.
Dataset json downloaded and prepared to /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51. Subsequent calls will reuse this data.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 749.12it/s]
05/18/2023 13:54:56 - INFO - datasets.arrow_dataset - Process #0 will write at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00000_of_00008.arrow
05/18/2023 13:54:56 - INFO - datasets.arrow_dataset - Process #1 will write at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00001_of_00008.arrow
05/18/2023 13:54:56 - INFO - datasets.arrow_dataset - Process #2 will write at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00002_of_00008.arrow
05/18/2023 13:54:56 - INFO - datasets.arrow_dataset - Process #3 will write at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00003_of_00008.arrow
05/18/2023 13:54:56 - INFO - datasets.arrow_dataset - Process #4 will write at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00004_of_00008.arrow
05/18/2023 13:54:56 - INFO - datasets.arrow_dataset - Process #5 will write at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00005_of_00008.arrow
05/18/2023 13:54:56 - INFO - datasets.arrow_dataset - Process #6 will write at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00006_of_00008.arrow
05/18/2023 13:54:56 - INFO - datasets.arrow_dataset - Process #7 will write at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00007_of_00008.arrow
05/18/2023 13:54:56 - INFO - datasets.arrow_dataset - Spawning 8 processes
preprocessing on dataset (num_proc=8):   0%|                                                                               | 0/5000 [00:00<?, ? examples/s]05/18/2023 13:54:59 - INFO - datasets.arrow_dataset - Caching processed dataset at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00000_of_00008.arrow
05/18/2023 13:54:59 - INFO - datasets.arrow_dataset - Caching processed dataset at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00002_of_00008.arrow
05/18/2023 13:54:59 - INFO - datasets.arrow_dataset - Caching processed dataset at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00006_of_00008.arrow
05/18/2023 13:54:59 - INFO - datasets.arrow_dataset - Caching processed dataset at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00001_of_00008.arrow
05/18/2023 13:54:59 - INFO - datasets.arrow_dataset - Caching processed dataset at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00007_of_00008.arrow
05/18/2023 13:54:59 - INFO - datasets.arrow_dataset - Caching processed dataset at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00003_of_00008.arrow
preprocessing on dataset (num_proc=8):  12%|████████▌                                                           | 625/5000 [00:03<00:22, 196.62 examples/s]05/18/2023 13:54:59 - INFO - datasets.arrow_dataset - Caching processed dataset at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00004_of_00008.arrow
05/18/2023 13:54:59 - INFO - datasets.arrow_dataset - Caching processed dataset at /home/qizhen/llm/qizhenllm/data/eval/sft_val/json/default-637dacf74c2e2d00/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-a66f7504eba719be_00005_of_00008.arrow
05/18/2023 13:54:59 - INFO - datasets.arrow_dataset - Concatenating 8 shards  
`

**Comment by AliceShen122** [comment]
请问怎么解决的啊？大佬，我也遇到这个问题了~
