### ISSUE TITLE
推理报错probability tensor contains either `inf`

### ISSUE THREAD

**Issue by 1051003502** [ymcui/Chinese-LLaMA-Alpaca#383]
### 详细描述问题

预训练loss为0，合并模型后推理报错
next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### 运行截图或日志
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/33519346/f4c46610-ab00-4fda-be28-f581a6004741)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/33519346/5bac830f-a09c-486f-9c77-6eb4e7935bea)

*请提供文本log或者运行截图，以便我们更好地了解问题详情。*

### 必查项目（前三项只保留你要问的）

- [x] **基础模型**：LLaMA-Plus
- [ ] **运行系统**： Linux 
- [x] **问题分类**：模型转换和合并 / 模型训练与精调 / 模型推理问题（🤗 transformers
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by iMountTai** [comment]
我们训练中未出现类似问题，还请参考我们的[预训练脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E9%A2%84%E8%AE%AD%E7%BB%83%E8%84%9A%E6%9C%AC)和[推理脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E4%BD%BF%E7%94%A8Transformers%E6%8E%A8%E7%90%86)
