### ISSUE TITLE
二次预训练部分提到了Pre-training Stage1 和 Stage2, 请教具体是什么意思？

### ISSUE THREAD

**Issue by mikeda100** [ymcui/Chinese-LLaMA-Alpaca#384]
文中提到了Pre-training Stage1 和 Stage2, 请教具体是什么意思？
------------------------------------------------------------------------
https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E9%A2%84%E8%AE%AD%E7%BB%83%E8%84%9A%E6%9C%AC
我们这里给出Pre-training Stage 2的训练脚本scripts/run_clm_pt_with_peft.py。 Pre-training Stage 1中模型收敛速度较慢，如果不是有特别充裕的时间和计算资源，建议跳过该阶段。
------------------------------------------------------------------------
### 必查项目（前三项只保留你要问的）

- [x] **基础模型**：LLaMA / Alpaca / LLaMA-Plus / Alpaca-Plus
- [x] **运行系统**：Linux 
- [x] **问题分类**：模型训练与精调
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by ymcui** [comment]
https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/训练细节#预训练

**Comment by mikeda100** [comment]
okay got you! Thanks a lot!
