### ISSUE TITLE
建议开放中文数据集

### ISSUE THREAD

**Issue by mikeda100** [ymcui/Chinese-LLaMA-Alpaca#385]
https://github.com/ymcui/Chinese-LLaMA-Alpaca 文中提到：
中文LLaMA模型在原版的基础上扩充了中文词表，使用了中文通用纯文本数据进行二次预训练。
请教能否开放此处所述的中文通用纯文本数据。
-------------------------------------------------------------
- [x] **基础模型**：LLaMA / Alpaca / LLaMA-Plus / Alpaca-Plus
- [x] **运行系统**：Linux 
- [x] **问题分类**：模型训练与精调
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by zhuangjiayue** [comment]
我也觉得，中文语料，中文互联网全线封闭。全互联网中文是英文的3/4，开源的差1000倍以上。如果能互通，公众号，知乎，博客园，微博，简述，小红书这些，中文的gpt类肯定很强。

**Comment by wang99711123** [comment]
我也在找中文通用纯文本数据
https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E8%AE%AD%E7%BB%83%E7%BB%86%E8%8A%82 
这里提到了一些repo，不知道能否用做参考
