### ISSUE TITLE
请问会支持 Ziya 模型吗？

### ISSUE THREAD

**Issue by SupritYoung** [ymcui/Chinese-LLaMA-Alpaca#386]
最近新出了一个 LLMs Ziya-LLaMA-13B-v1：https://huggingface.co/roygan/test

请问作者有考虑支持吗？

**Comment by ymcui** [comment]
那个也是LLaMA-based模型，不太清楚你问的是支持什么？
目前的问题看起来有点像“会支持MOSS/ChatGLM/RWKV模型吗？” 😂

**Comment by SupritYoung** [comment]
这是一个刚刚发布的基于 LLaMA 的LLM，您可以看一下这篇文章：https://www.jiqizhixin.com/articles/2023-05-17-6

**Comment by SupritYoung** [comment]
与您的工作非常相似，而且该文声称他们的模型超过了您

**Comment by ymcui** [comment]
> 这是一个刚刚发布的基于 LLaMA 的LLM，您可以看一下这篇文章：https://www.jiqizhixin.com/articles/2023-05-17-6

这个工作我看过了，不是太清楚你问的问题是希望我们支持什么呢？本质上我们的repo也是基于LLaMA的模型，和你说的工作属于同类工作。就好比去BERT项目下问“你会支持GPT吗”一样，不太清楚问题的具体含义是什么。

**Comment by SupritYoung** [comment]
明白，感谢您的耐心回复。

**Comment by LiemLin** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/58ffda4c-136a-4872-823f-5a612a6dfe70)
测了一下线上的ziya，也不太准确

**Comment by SupritYoung** [comment]
😂

**Comment by CRGBS** [comment]
還是說其實你想要把兩個專案的權重合併起來(瞎猜
