### ISSUE TITLE
预训练llama 13b报错 NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by qiancheng99** [ymcui/Chinese-LLaMA-Alpaca#387]
我用预训练脚本可以正常训练llama7B， 但是我换成llama13b的时候报错：NotImplementedError: Cannot copy out of meta tensor; no data!
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1100648) of binary: 
请问是什么问题呢？预训练脚本是否能训练13b的模型？

**Comment by airaria** [comment]
PyTorch 和 transformers版本多少？用pytorch==1.13 transformers=4.28.1试试？

**Comment by qiancheng99** [comment]
torch==1.13.1
transformers==4.28.1
还是会报这个错
