### ISSUE TITLE
响应输出特别慢

### ISSUE THREAD

**Issue by happy-zhangbo** [ymcui/Chinese-LLaMA-Alpaca#388]
*提示：将[ ]中填入x，表示打对钩。提问时删除这行。只保留符合的选项。*

### 详细描述问题
在AutoDL的V100环境下运行
但输出特别慢，

### 必查项目（前三项只保留你要问的）

- [√ ] **基础模型**：LLaMA / Alpaca / LLaMA-Plus / Alpaca-Plus
- [ √] **运行系统**： Linux 
- [√ ] **问题分类**：llama.cpp
- [√ ] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [√ ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ √] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by happy-zhangbo** [comment]
[运行截图](https://imgloc.com/i/VfwyRp)

**Comment by happy-zhangbo** [comment]
参考了https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/notebooks/convert_and_quantize_chinese_llama.ipynb这个

**Comment by ymcui** [comment]
我们并没有尝试在GPU上运行llama.cpp。
你可以看一下运行的时候是否真实占用了显存，还是说仍然是在CPU上运行的。
另外，llama.cpp如果要和cuBLAS一起使用的话，需要单独的编译方式（看cuBLAS那一节）：https://github.com/ggerganov/llama.cpp#blas-build

**Comment by happy-zhangbo** [comment]
他已经好了，虽然还是在cpu上运行，但在回答一直在重复....这可能和参数有关，
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16586613/c3717e37-ab4d-49f3-9d20-34cb678b96dd)

使用其他的[text-generation-webui](https://github.com/oobabooga/text-generation-webui)部署方式.也是在cpu上运行吗？
或者说有使用gpu的方式在本地运行嘛？

**Comment by ymcui** [comment]
1、效果方面：如果合并没什么问题的话，看到你之前gif截图应该是LLaMA模型，实际上是没用指令数据训练的。所以用`-ins`启动的话，建议使用Alpaca模型。
2、text-generation-webui支持GPU，你可以看一下相应库的一些安装步骤。
3、transformers原生支持GPU，你也可以尝试（但不支持多轮对话）：https://github.com/ymcui/Chinese-LLaMA-Alpaca#本地推理与快速部署

**Comment by happy-zhangbo** [comment]
好的 谢谢~
