### ISSUE TITLE
输出内容后面会一直重复

### ISSUE THREAD

**Issue by happy-zhangbo** [ymcui/Chinese-LLaMA-Alpaca#390]
### 详细描述问题

*请尽量具体地描述您遇到的问题，**必要时给出运行命令**。这将有助于我们更快速地定位问题所在。*

### 运行截图或日志

*请提供文本log或者运行截图，以便我们更好地了解问题详情。*
运行命令
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16586613/dd00aab9-d880-49d9-8b46-592dc8605700)
运行结果
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16586613/9fa7685c-78de-4d72-9afc-26c522442287)

### 必查项目（前三项只保留你要问的）

- [ ] **基础模型** Alpaca-Plus
- [ ] **运行系统**  Linux 
- [ ] **问题分类**：效果问题
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by happy-zhangbo** [comment]
这个是因为原版模型的问题吗？我在decapoda-research/llama-7b-hf下载模型；

**Comment by happy-zhangbo** [comment]
哦 对使用text-generation-webui。我按照[text-generation-webui](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E4%BD%BF%E7%94%A8text-generation-webui%E6%90%AD%E5%BB%BA%E7%95%8C%E9%9D%A2)这个文档部署的，是需要合并模型吗？

**Comment by iMountTai** [comment]
plus模型需要经过两步合并，还请参考[加载Chinese-Alpaca-Plus](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E4%BD%BF%E7%94%A8Transformers%E6%8E%A8%E7%90%86#%E5%8A%A0%E8%BD%BDchinese-alpaca-plus)先合并模型，然后使用webui加载

**Comment by happy-zhangbo** [comment]
> plus模型需要经过两步合并，还请参考[加载Chinese-Alpaca-Plus](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E4%BD%BF%E7%94%A8Transformers%E6%8E%A8%E7%90%86#%E5%8A%A0%E8%BD%BDchinese-alpaca-plus)先合并模型，然后使用webui加载

ohh 感谢 我试试

**Comment by happy-zhangbo** [comment]
>
不管用不用plus模型，是都需要进行合并模型嘛~

**Comment by happy-zhangbo** [comment]
> 不用plus模型，可以通过加载lora和model权重使用，但是速度不如合并权重后的速度。使用plus模型是需要合并权重的，还请参考[text-generation-webui using](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/text-generation-webui)

好的 谢谢

**Comment by Emir-Liu** [comment]
https://github.com/27182812/ChatGLM-LLaMA-chinese-insturct/issues/29#issuecomment-2339510192
