### ISSUE TITLE
预训练数据准备相关问题

### ISSUE THREAD

**Issue by wang99711123** [ymcui/Chinese-LLaMA-Alpaca#391]
首先，感谢您关于LLM技术的分享！

### 详细描述问题

我在尝试复现您的工作，按照您的提示准备数据
我下载了bq_corpus数据集，这好像是一个文本匹配任务的中文数据集
请问您是如何将其转化成clm训练所需数据（如同[样例数据](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/data/pt_sample_data.txt)） 的呢？ 还是说直接去掉label之后进行训练？

### 运行截图或日志

暂无

### 必查项目（前三项只保留你要问的）

- [x] **基础模型**：LLaMA / LLaMA-Plus
- [x] **问题分类**:  模型训练与精调 / 其他问题
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by iMountTai** [comment]
clm训练就是寻常的因果模型训练，可以根据我们开源预训练代码中的数据处理方式准备相应数据
