### ISSUE TITLE
可直接使用的 13b-plus 4bit 量化模型下载

### ISSUE THREAD

**Issue by johnlui** [ymcui/Chinese-LLaMA-Alpaca#395]
【文件格式已经更新】该文件所用的格式已经更新到 `ggjt v3 (latest)`，请将你的 llama.cpp 项目更新到最新。
---

下载仓库地址：https://huggingface.co/johnlui/chinese-alpaca-13b-plus-quantized

移动本仓库中的 `alpaca-13b-plus` 文件夹到你项目的`./models`文件下即可。该文件夹同时适用于`llama.cpp`和`text-generation-webui`。

### 使用体验

效果确实比 13b 好了不少，能写出比较长的文字了，速度没有明显变化，本模型运行时需要 9.2GB 内存，未进行格式转换和量化时需要 50GB 内存，太吓人了，速度还只有十分之一。

**Comment by binganao** [comment]
感谢您的工作，另外，可以直接对 13b-plus 4bit 直接进行 lora 训练吗

**Comment by johnlui** [comment]
@binganao 不行，用我仓库中标记的原始仓库里面的模型可以继续训练

**Comment by alei76** [comment]
反馈如下：
1、用https://github.com/abetlen/llama-cpp-python  v0.1.52  加载 报错 https://huggingface.co/johnlui/chinese-alpaca-13b-plus-quantized  报错
llama.cpp: loading model from G:/Model_DATA/BertModel/huggingface/ggml/alpaca-plus/johnlui/chinese-alpaca-13b-plus-quantized/ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v1 (pre #1405)
llama_model_load_internal: n_vocab    = 49954
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
error loading model: this format is no longer supported (see https://github.com/ggerganov/llama.cpp/pull/1305)
llama_init_from_file: failed to load model
2、用https://github.com/abetlen/llama-cpp-python  v0.1.52  加载 https://huggingface.co/HardSoft2023/chinese-alpaca-plus-lora-7b-llama.cpp-q4_0.bin 正常
llama.cpp: loading model from G:/Model_DATA/BertModel/huggingface/ggml/alpaca-plus/HardSoft2023/chinese-alpaca-plus-lora-7b-llama.cpp-q4_0.bin/ggml-model-q4_0.bin
llama_model_load_internal: format     = ggjt v2 (latest)
llama_model_load_internal: n_vocab    = 49954
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =  72.75 KB
llama_model_load_internal: mem required  = 5897.00 MB (+ 1026.00 MB per state)
using 8.119642972946167 (seconds)

一个是ggjt v1 (pre #1405)  一个是ggjt v2 (latest)，估计是llama-cpp-python兼容性的原因

**Comment by johnlui** [comment]
确实，我的还是老版本😂

**Comment by GuoChang2032** [comment]
我web-ui直接启动的时候报如下错误
启动命令：python server.py --model chinese-alpaca-13b-plus-quantized --cpu
![Snipaste_2023-05-25_14-22-06](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/24536679/b31b6210-7016-4d62-9a69-d3ba72bc9bfa)

**Comment by ttimasdf** [comment]
我做了一个GPTQ的，效果一般

**Comment by hackbuteer001** [comment]
不知道是不是langchain版本的问题？
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/53468270/14601d8a-afb4-407d-aced-a44e2943e788)

**Comment by 1anglesmith1** [comment]
> 

你直接放在zh_models/文件夹中可以直接使用吗？我也想问一下

**Comment by 1anglesmith1** [comment]
> @1anglesmith1 不可以啊。。。 不知道为啥，还没排出来问题，正在尝试自己合并下看看。。

好的，我稍后也尝试一下，你知道怎么调用llama已合并的模型的api进行问答吗？

**Comment by johnlui** [comment]
@alei76 @GuoChang2032 @pengwork @1anglesmith1 文件已经更新到最新的 v3 格式，可以正常使用了

**Comment by 1anglesmith1** [comment]
> @alei76 @GuoChang2032 @pengwork @1anglesmith1 文件已经更新到最新的 v3 格式，可以正常使用了

请问大佬，我如果想使用程序获取这个模型的api进行问答该怎么做，可以输入从本地的文件中读取问题让模型作答并返回结果。这一步您知道怎么进行吗？

**Comment by johnlui** [comment]
@1anglesmith1 https://github.com/oobabooga/text-generation-webui 这个项目有 http api

**Comment by RickyWang111** [comment]
爱了爱了，谢谢大佬！
