### ISSUE TITLE
关于训练用的数据类型bf16和float16

### ISSUE THREAD

**Issue by AceCHQ** [ymcui/Chinese-LLaMA-Alpaca#397]
### 详细描述问题

1、请问原始的LLaMA在训练时是否有指定哪个数据类型，使用float16会不会与原文无法对应，有溢出的风险。
2、看到block_size设置为512，请问是否过短，有尝试过1024的效果吗

谢谢。

**Comment by airaria** [comment]
1. Chinese-LLaMA可以使用float16配合peft进行LoRA训练，训练脚本里也默认开启了fp16
2. 暂无明确计划，或许会考虑针对个别场景采用更长的block size
