### ISSUE TITLE
如何用GPU合并Plus模型

### ISSUE THREAD

**Issue by happy-zhangbo** [ymcui/Chinese-LLaMA-Alpaca#398]
### 详细描述问题
python scripts/merge_llama_with_chinese_lora.py --base_model /root/autodl-tmp/models/decapoda-research/llama-7b-hf --lora_model /root/autodl-tmp/models/ziqingyang/chinese-llama-plus-lora-7b,/root/autodl-tmp/models/ziqingyang/chinese-alpaca-plus-lora-7b --output_type huggingface --output_dir ./merged_chinese_alpaca_plus

以上命令执行会占用CPU，有办法使用GPU嘛？

### 运行截图或日志
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16586613/6ebe6af9-15a2-497a-8204-8c08de22ebd0)

### 必查项目（前三项只保留你要问的）

- [x] **基础模型**： Alpaca-Plus
- [x] **运行系统**：Linux 
- [x] **问题分类**：模型转换和合
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by airaria** [comment]
把代码中所有的`"cpu"`和`'cpu'`替换成`"cuda:0"`试试
