### ISSUE TITLE
模型合并过程中，step2没有生成 .pth文件

### ISSUE THREAD

**Issue by georgeGao** [ymcui/Chinese-LLaMA-Alpaca#40]
模型合并过程中，step2 extended_model目录没有生成 .pth文件，生成文件为
config.json
generation_config.json
pytorch_model-00001-of-00002.bin
pytorch_model-00002-of-00002.bin
pytorch_model.bin.index.json
special_tokens_map.json
tokenizer.model
tokenizer_config.json

**Comment by ymcui** [comment]
你运行的是哪个脚本？有无报错信息？

**Comment by georgeGao** [comment]
Chinese-LLaMA-Alpaca运行的这个，没有报错

**Comment by ymcui** [comment]
> Chinese-LLaMA-Alpaca运行的这个，没有报错

不是，你要提供一下具体运行的是哪个脚本（`.py`文件）。

**Comment by georgeGao** [comment]
我是这样运行的

python scripts/extend_llama_with_zh_vocab.py --llama_model {第一步生成的文件路径} --tokenizer {下载的chinese_alpaca_lora_7b目录} --output_dir {最终生成的目录}

**Comment by georgeGao** [comment]
> > Chinese-LLaMA-Alpaca运行的这个，没有报错
> 
> 不是，你要提供一下具体运行的是哪个脚本（`.py`文件）。 你运行的是`scripts/merge_llama_with_chinese_lora.py`这个脚本吗？
看来是我搞错了，谢谢您

**Comment by georgeGao** [comment]
新pull了代码，发现
OSError: dlopen(/usr/local/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cpu.so, 6): no suitable image found.  Did find:。我是cpu 😅

**Comment by airaria** [comment]
> 新pull了代码，发现
> OSError: dlopen(/usr/local/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cpu.so, 6): no suitable image found. Did find:。我是cpu 😅

是还存在问题吗？CPU也可以运行的。

**Comment by georgeGao** [comment]
嗯，运行就报这个错。

**Comment by Zalberth** [comment]
> merge_llama_with_chinese_lora

通样的情况，没有报错，没有pth，用的merge_llama_with_chinese_lora_to_hf.py，生成的是bin，
```
python scripts/merge_llama_with_chinese_lora_to_hf.py --base_model /Users/zh/Desktop/my_ai_lab/meta-llama/hf_13B --lora_model /Users/zh/Desktop/my_ai_lab/chinese_alpaca_lora_13b --output_dir /Users/zh/Desktop/my_ai_lab/chinese-llama-alpaca-model
```
输出是：
```
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:04<00:00,  1.58s/it]
Extended vocabulary size: 49954
Peft version: 0.2.0
Merging model
```
