### ISSUE TITLE
Lora训练时节省显存删除--modules_to_save ${modules_to_save} \和--gradient_checkpointing \依旧报错

### ISSUE THREAD

**Issue by AArmageddon** [ymcui/Chinese-LLaMA-Alpaca#400]
*提示：将[ ]中填入x，表示打对钩。提问时删除这行。只保留符合的选项。*

### 详细描述问题
第二训练阶段，fine-tuning 模型的时候
Lora训练时，为了节省显存删除--modules_to_save ${modules_to_save} \和--gradient_checkpointing \依旧报错

*请尽量具体地描述您遇到的问题，**必要时给出运行命令**。这将有助于我们更快速地定位问题所在。*
<img width="319" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/108610753/46dcb2b5-1f18-4ef0-b5c0-c196b9dafcf6">

### 运行截图或日志
<img width="1067" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/108610753/17717ea1-ed07-44f7-b8be-f8f865baeae8">

### 必查项目（前三项只保留你要问的）

- [ ] **基础模型**：Alpaca-Plus
- [ ] **运行系统**： Linux 
- [ ] **问题分类**：模型训练与精调
- [ ] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案

**Comment by airaria** [comment]
请删除`--modules_to_save ${modules_to_save} \`和`--gradient_checkpointing \`两行（而不是注释掉），再试一下吧
