### ISSUE TITLE
根据run_clm_sft_with_peft.py跑出来的checkpoint里面没有adapter_config.json和adapter_model.bin

### ISSUE THREAD

**Issue by liuyukid** [ymcui/Chinese-LLaMA-Alpaca#405]
### 详细描述问题
根据run_clm_sft_with_peft.py以及LLaMa-plus-7b从头训练了一个alpaca模型，但是checkpoint中没有相应的adapter_config.json和adapter_model.bin
直接使用[merge_llama_with_chinese_lora.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_llama_with_chinese_lora.py)合并报错

### 运行截图或日志
`python ./scripts/merge_llama_with_chinese_lora.py \
    --base_model '/xxx/llama-7b-hf' \
    --lora_model '/xxx/chinese-llama-plus-lora-7b', '/xxx/chinese-alpaca-lora-7b'  \
    --output_type huggingface \
    --output_dir '/xxx/chinese-alpaca-7b'`
其中chinese-alpaca-lora-7b是我自己训练保存模型的文件夹

然后报错：
ValueError: Can't find 'adapter_config.json' at '/xxx/chinese-alpaca-lora-7b'

### 必查项目（前三项只保留你要问的）

- [x] **基础模型**：Alpaca-Plus
- [x] **运行系统**：Linux 
- [x] **问题分类**：模型转换和合并 / 模型训练与精调 
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by iMountTai** [comment]
参考 #361
