### ISSUE TITLE
进行指令精调时报 torch.cuda.OutOfMemoryError ,显存溢出

### ISSUE THREAD

**Issue by huruizhi** [ymcui/Chinese-LLaMA-Alpaca#406]
*提示：将[ ]中填入x，表示打对钩。提问时删除这行。只保留符合的选项。*

### 详细描述问题

*请尽量具体地描述您遇到的问题，**必要时给出运行命令**。这将有助于我们更快速地定位问题所在。*

### 运行截图或日志
- 单张显卡 24G 显存
<img width="870" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/20983257/62820fb4-e74e-4db2-b36c-900097e6d842">

- 命令执行时显卡监控
<img width="801" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/20983257/9686d25b-8b1d-40ce-814e-70e691a49701">

- 报错日志
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.05 GiB (GPU 0; 23.65 GiB total capacity; 20.02 GiB already allocated; 1.82 GiB free; 20.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 441809) of binary: /root/miniconda3/envs/llama/bin/python
```

- bash 脚本
```
########参数部分########
lr=1e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/data/chinese-llama/llama-7B
chinese_tokenizer_path=/data/chinese-llama/llama-7B
dataset_dir=/root/SourceCode/DL/Chinese-LLaMA-Alpaca/data
per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=100
gradient_accumulation_steps=1
output_dir=/data/chinese-llama/chinese_alpaca_plus_lora_7b_gitlab
peft_model=/data/chinese-llama/chinese_alpaca_plus_lora_7b
validation_file=/root/SourceCode/DL/Chinese-LLaMA-Alpaca/scripts/validation_file_name/vaidation.json

deepspeed_config_file=ds_zero2_no_offload.json

########启动命令########
torchrun --nnodes 1 --nproc_per_node 1 run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed $RANDOM \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 250 \
    --save_steps 500 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 1 \
    --max_seq_length 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --peft_path ${peft_model} \
    --ddp_find_unused_parameters False
```

已经删除参数 `--modules_to_save ${modules_to_save} \` 和 `--gradient_checkpointing \`

24G显存是否无法进行训练？最小需要多少显存？
 
*请提供文本log或者运行截图，以便我们更好地了解问题详情。*

### 必查项目（前三项只保留你要问的）

- [x] **基础模型**：LLaMA-Plus
- [x] **运行系统**：Linux 
- [x] **问题分类**：模型训练与精调 
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by huruizhi** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/20983257/c070489f-1ecb-4f1c-bcec-eebb6b3315ac)
这是不是意味着最小需要 28 G 的显存？

**Comment by iMountTai** [comment]
理论上打开`gradient_checkpointing `24G显存是可以训练的

**Comment by LiemLin** [comment]
@huruizhi 你的解决了吗，我把--nproc_per_node 配置为2 ，用了2颗GPU(24G)也是OOM

**Comment by huruizhi** [comment]
<img width="1532" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/20983257/6f2dd624-10bc-41e9-b63f-0b7752c9516c">
就差这么一点点。
pytorch 的原因？

**Comment by Q4n** [comment]
不要只删除参数 modules_to_save , 你还要去代码中改 modules_to_save=None, 代码中写了default选项的.

**Comment by PL2584718785** [comment]
> <img alt="image" width="1532" src="https://user-images.githubusercontent.com/20983257/240231545-6f2dd624-10bc-41e9-b63f-0b7752c9516c.png"> 就差这么一点点。 pytorch 的原因？

你好，请问解决了么 大概需要多少资源可以训练呢？

**Comment by Q4n** [comment]
> > 不要只删除参数 modules_to_save , 你还要去代码中改 modules_to_save=None, 代码中写了default选项的.
> 
> 代码中default好像是为None，请问你这边解决了么？ 多少资源可以训练默认参数配置呢？

噢确实, 上周的commit改了, 我的版本落后了, 不好意思.

我这里用的24G的显存似乎是ok的.

**Comment by huruizhi** [comment]
<img width="1036" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/20983257/83419d50-d90e-4a71-87f7-4a813a9ad7f7">
在日志里面还是有 应该还是配置或者代码哪里影响了

**Comment by huruizhi** [comment]
<img width="1035" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/20983257/d9a9e0cd-9631-481b-b504-5fc621f866cb">

**Comment by huruizhi** [comment]
> > <img alt="image" width="1532" src="https://user-images.githubusercontent.com/20983257/240231545-6f2dd624-10bc-41e9-b63f-0b7752c9516c.png"> 就差这么一点点。 pytorch 的原因？
> 
> 你好，请问解决了么 大概需要多少资源可以训练呢？

<img width="1506" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/20983257/ab796a7c-02aa-4d87-967e-77b3b5fc3a3b">
实测大概需要30G

**Comment by LiemLin** [comment]
@Q4n 

> > > 不要只删除参数 modules_to_save , 你还要去代码中改 modules_to_save=None, 代码中写了default选项的.
> > 
> > 
> > 代码中default好像是为None，请问你这边解决了么？ 多少资源可以训练默认参数配置呢？
> 
> 噢确实, 上周的commit改了, 我的版本落后了, 不好意思.
> 
> 我这里用的24G的显存炼7B的plus似乎是ok的.

HI, 我的改了modules_to_save=None还是OOM，还有别的地方需要修改吗

**Comment by xinyu1905** [comment]
貌似和训练的句子的长度有关

**Comment by jiaohuix** [comment]
@huruizhi 解决了嘛，我v100也没跑起来

**Comment by iMountTai** [comment]
加载`peft_model`是会更新embed和lm_head的，可以尝试直接微调合并后的模型，然后再调整可训参数、梯度检查、batch_size等

**Comment by wuzixiaoer** [comment]
@jiaohuix 请问您后来解决了吗，我也是单卡V100跑不起来

**Comment by jiaohuix** [comment]
@wuzixiaoer 无 哈

**Comment by coolge** [comment]
> V100

大佬多大内存的V100？

**Comment by coolge** [comment]
> @wuzixiaoer 无 哈
@jiaohuix 
大佬多大内存的V100？

**Comment by jiaohuix** [comment]
32g
&nbsp;


朱嘉辉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "shuai ***@***.***&gt;; 
发送时间: 2023年7月14日(星期五) 下午4:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ymcui/Chinese-LLaMA-Alpaca] 进行指令精调时报 torch.cuda.OutOfMemoryError ,显存溢出 (Issue #406)





  
@wuzixiaoer 无 哈
 @jiaohuix
 大佬多大内存的V100？

**Comment by coolge** [comment]
@jiaohuix  请问大佬解决这个显存溢出的问题了吗？

**Comment by coolge** [comment]
@Q4n 大佬，你用的哪个模型呀？Chinese-Alpaca 还是 Chinese-LLaMA？Chinese-Alpaca需要指定LoRA权重目录（--peft_path），这个占用的显存很大，我这边24G跑不起来

**Comment by binsson** [comment]
请问解决觉了吗？我也遇到一样的问题了
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 508.00 MiB (GPU 0; 23.65 GiB total capacity; 22.92 GiB already allocated; 182.06 MiB free; 22.95 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
