### ISSUE TITLE
灾难性遗忘

### ISSUE THREAD

**Issue by zhangatao** [ymcui/Chinese-LLaMA-Alpaca#407]
请问各位大佬，你们在用自己的数据继续训练Plus模型，得到的内容会出现模型通用能力变差的情况吗

**Comment by LiemLin** [comment]
训练步骤是什么样的

**Comment by LiemLin** [comment]
基于源llama和chinese-llama-plus-lora的合并版本再训练alpaca可能会好些

**Comment by LiemLin** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/66d88303-3fa4-44ad-8db6-39d6cd3ee615)
