### ISSUE TITLE
Can't find adapter_config.json

### ISSUE THREAD

**Issue by hjc3613** [ymcui/Chinese-LLaMA-Alpaca#409]
微调后，没有生成adaptor_config.json文件，也没有config.json文件，所以在合并时，报错了：Can't find adapter_config.json

- [√ ] **基础模型**： Alpaca-Plus
- [ √] **运行系统**： Linux 
- [ √] **问题分类**：模型转换和合并 / 模型训练与精调 /
- [ √] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ √] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ √] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by huruizhi** [comment]
我估计是步骤错误了，需要检查一下步骤

**Comment by iMountTai** [comment]
参考 #361

**Comment by hjc3613** [comment]
> 


> 参考 #361

十分感谢！

**Comment by ZengGus** [comment]
你好，请问这个解决了吗，我这边也是找不到adapter.json文件

**Comment by airaria** [comment]
[参考wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/指令精调脚本#训练后文件整理)
