### ISSUE TITLE
第一阶段：冻结transformer参数，仅训练embedding，在尽量不干扰原模型的情况下适配新增的中文词向量。

### ISSUE THREAD

**Issue by AceCHQ** [ymcui/Chinese-LLaMA-Alpaca#415]
### 详细描述问题

请教一下第一阶段仅训练embedding层，是不是训练输入的embedding层和输出的head层，其他层冻结？谢谢。

**Comment by wangjvjie** [comment]
作者回复说他们提供的脚本只是第二阶段，第一阶段是试错产物
