### ISSUE TITLE
手动合并之后，使用llama.cpp进行量化推理，模型返回的内容重复，且不同量化程度重复的程度也不同

### ISSUE THREAD

**Issue by zhiyixu** [ymcui/Chinese-LLaMA-Alpaca#417]
### 详细描述问题

使用的大模型为`LLaMA-7B`
使用的lora模型为`chinese-alpaca-plus-lora-7b`

按照合并和量化教程一路走下来，没报什么错，但是进行推理的时候返回的内容重复
其中`ggml-model-q4_0.bin` 和 `ggml-model-q5_1.bin`两种量化方式下，模型的返回内容要么是一直不停重复的中文，要么直接就是英文。

如果不进行量化直接使用`ggml-model-f16.bin`模型会正常说一些中文，但是感觉一句话里边会丢几个字， 随后又是开始重复。

### 运行截图或日志
q4_0 下的表现  
![q40](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/97584093/73a09eab-6e53-484a-807b-a7ee7519b0a7)  

q5_1 下的表现    
![q51](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/97584093/1fbb3b26-176e-456d-bf8c-45daddab2a84)  

f16 下的表现  
![or](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/97584093/224131ca-7ae1-49ca-ae90-beba7eb849d3)

### 必查项目（前三项只保留你要问的）

- [*] **基础模型**：LLaMA
- [*] **运行系统**：Windows
- [*] **问题分类**： 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat)
- [*] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [*] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [*] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

另外还有一个问题， 我之所以选择llama.cpp是奔着节省硬件去的，量化后的模型能使用python调用吗？ 我参考了一些项目比如 `llama_cpp, fastllama` 但是他们要么不支持win（issue里说的）, 要么载入量化后的模型`q4_0, q5_1`会报错说他不是一个真正的GGML模型。

**Comment by airaria** [comment]
Plus模型的合并需要两个LoRA
https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/手动模型合并与转换#多lora权重合并适用于chinese-alpaca-plus
请问是按照这个流程做的吗？

**Comment by zhiyixu** [comment]
@airaria 只合并了一个lora， 漏了一个    (￣ε(#￣)☆╰╮(￣▽￣///) ， [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) 这个确实好用，谢谢大佬
