### ISSUE TITLE
微调 chinese llama 后输出的模型如何使用？

### ISSUE THREAD

**Issue by sszyl** [ymcui/Chinese-LLaMA-Alpaca#418]
使用script/run_sft.sh 对 llama-plus微调后输出的模型如何使用？
尝试合并到 llama-plus 和 使用transformer 加载 报：Can't find 'adapter_config.json'

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/19159781/62cf1537-f081-4d9e-8971-6008c4daa9a1)

### 必查项目（前三项只保留你要问的）

- [ ] **基础模型**：LLaMA-Plus 
- [ ] **运行系统**：Linux 
- [ ] **问题分类**：模型转换和合并 / 模型训练与精调 / 模型推理问题（🤗 transformers）
- [ ] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by airaria** [comment]
参考 https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/361

**Comment by LiemLin** [comment]
@sszyl 朋友你微调用了多少GPU显存，我24G显存OOM

**Comment by sszyl** [comment]
> @sszyl 朋友你微调用了多少GPU显存，我24G显存OOM

8卡V100 32G*8

**Comment by LiemLin** [comment]
@sszyl 兄弟你这个解决了吗
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/1bb5b12f-f6f6-4066-a240-e7296aac4bd4)
我微调训练出来的有14G，方便的话加微信LiemLin666探讨一下啊

**Comment by zzx16045223** [comment]
> > @sszyl 朋友你微调用了多少GPU显存，我24G显存OOM
> 
> 8卡V100 32G*8

你好，请问一下怎么多卡微调
