### ISSUE TITLE
删除--modules_to_save ${modules_to_save} \ 不起作用

### ISSUE THREAD

**Issue by LiemLin** [ymcui/Chinese-LLaMA-Alpaca#419]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/15a24468-6171-4ded-8476-963e2d16f96d)
如何是继续微调alpaca，删除--modules_to_save ${modules_to_save} \ 不起作用，需要改peft_path下面的adapter_config.json文件，改为"modules_to_save": null

**Comment by airaria** [comment]
感谢提醒🙏
