### ISSUE TITLE
合并权重并量化后，生成速度非常慢

### ISSUE THREAD

**Issue by Trangle** [ymcui/Chinese-LLaMA-Alpaca#42]
你们也是这么慢吗？我用gpt4all还好，合并中文lora权重，并量化后，生成非常慢，是有什么没注意吗？

**Comment by ymcui** [comment]
生成速度已经在README中的GIF中显示出来了，并没有特别慢。如果你运行原版英文Alpaca速度慢，那就是llama.cpp和你的机器适配性的问题了。

**Comment by chensiyao12** [comment]
我有同样的问题，文字生成速度特别慢，我CPU型号是AMD EPYC 7352 24-Core Processor * 2内存为64G

**Comment by chensiyao12** [comment]
找到原因了，我的cpu是x86的，不支持neon
