### ISSUE TITLE
回答的问题一直重复

### ISSUE THREAD

**Issue by nicole828** [ymcui/Chinese-LLaMA-Alpaca#422]
*提示：将[ ]中填入x，表示打对钩。提问时删除这行。只保留符合的选项。*

### 详细描述问题

1.使用了如下命令进行模型合并，python ./scripts/merge_llama_with_chinese_lora.py \
--base_model  llama-7b-hf \
--lora_model chinese_llama_plus_lora_7b,chinese_alpaca_plus_lora_7b \
--output_type huggingface \
--output_dir ./merge_model_7b
2.使用如下命令：python ./scripts/gradio_demo.py \
--base_model  ./merge_model_7b 启动图形界面。
3.问题如下所示：有很多重复的内容，不知如何解决，麻烦各位志同道合的朋友们多多指教。

### 运行截图或日志

<img width="908" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/53501163/5ee8db9c-d0da-4607-8006-5161a225b978">

### 必查项目（前三项只保留你要问的）

- [ ] **基础模型**：LLaMA-Plus / Alpaca-Plus
- [ ] **运行系统**：Linux 
- [ ] **问题分类**： 模型转换和合并
- [ ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by nicole828** [comment]
在使用gradio_demo.py图形化界面时候，当调整了maximum_length后，就开始有很多重复的回答，这个值只能是128吗？gradio_demo中，predict函数中，超过128，也是同样的问题。
<img width="803" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/53501163/91648fcb-9aa1-4d8a-84c8-bb55456931f3">

**Comment by airaria** [comment]
用llama.cpp是否也存在此类问题？还是只有用gradio_demo时才有此问题？

**Comment by nicole828** [comment]
> 

llama.cpp无法输入中文，所以没有尝试

**Comment by sunyuhan19981208** [comment]
#390 
是不是和这个是一个问题

**Comment by chenxu126** [comment]
![20230603184321](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/19886457/6675d759-cada-4c0f-8dd9-5988cfaba72b)
我的也是，不过比你惨的是，它连回答都不回答，直接重复问题，请问您解决没？

**Comment by xxllp** [comment]
效果这么差，是量化后的还是没有量化的哈

**Comment by Emir-Liu** [comment]
occur the same problem,
i find the problem is caused by difference between the prompt in training process and the actual question as asked.
