### ISSUE TITLE
重新训练一个alpaca时，训练loss 和 learning rate始终为0，请问该如何解决？

### ISSUE THREAD

**Issue by Antiman-cmyk** [ymcui/Chinese-LLaMA-Alpaca#423]
*提示：将[ ]中填入x，表示打对钩。提问时删除这行。只保留符合的选项。*

### 详细描述问题
根据提供的指令精调的脚本，训练过程中出现两种情况
1. fp16下， Deepspeed 在做loss scale时候，一直减小到0
2. 关闭fp16，训练过程的loss和learning rate始终为0，没起到模型训练的作用

*请尽量具体地描述您遇到的问题，**必要时给出运行命令**。这将有助于我们更快速地定位问题所在。*

### 运行截图或日志
<img width="1366" alt="3c1800c537118af278988b2f43f6452" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/53069142/68a63bf6-dacd-4629-8896-518dc7e1b47c">

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/53069142/bd13da9a-babe-4ecc-bfb1-2569dcb5a646)

*请提供文本log或者运行截图，以便我们更好地了解问题详情。*

### 必查项目（前三项只保留你要问的）

- [x] **基础模型**：LLaMA
- [x] **运行系统**：Linux 
- [x] **问题分类**： 模型训练与精调
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by Antiman-cmyk** [comment]
@ymcui @airaria @guohao 有大佬指点一二吗

**Comment by airaria** [comment]
请详细描述问题，如给出启动命令、运行环境、变量设置等
