### ISSUE TITLE
请教下二次预训练里的数据需要进行一定的清理吗？

### ISSUE THREAD

**Issue by huangxd-** [ymcui/Chinese-LLaMA-Alpaca#426]
比如一些标点符号，分段什么的？

**Comment by ymcui** [comment]
和其他训练CLM是一致的，语料干净一些自然是更好，格式上没有特别要求。

**Comment by tkone2018** [comment]
@ymcui 你好，我想请问下第二阶段训练的数据集主要是什么样的内容，是纯文本吗，还是说里边可以体现一些比如多轮对话，以及实体抽取这种功能性的内容 ，如果可以应该是什么样的格式。还有就是咨询下第二阶段训练的话，在垂类领域需要多大的数据集才有效，谢谢，希望得到你的帮助
