### ISSUE TITLE
alpaca继续训练问题

### ISSUE THREAD

**Issue by LiemLin** [ymcui/Chinese-LLaMA-Alpaca#427]
使用llama-7b-hf和chinese-llama-plus-lora-7b合并后的模型继续训练chinese-alpaca-plus-lora-7b
抛异常GPU OOM
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/539d7b19-7fe5-4ba1-a119-2dc36b921153)

将adapter_config.json中的modules_to_save设置为null，排除 "embed_tokens"和 "lm_head"

确认了model.modules_to_save为None
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/8c48d29e-a7ee-4736-beb1-34d31dbfe829)

抛异常IndexError: list index out of range
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/d8dce768-6abe-41cb-921b-7454c055face)

这个有什么办法处理吗

**Comment by LiemLin** [comment]
adapter_config.json中的modules_to_save用原来默认"embed_tokens"和 "lm_head"，打印出来self.optimizer的值为
AdamW (
Parameter Group 0
    betas: (0.9, 0.999)
    correct_bias: True
    eps: 1e-08
    initial_lr: 0.0001
    lr: 0.0
    weight_decay: 0.0
)

modules_to_save设置为null的的话，self.optimizer的值为AdamW ()，所以抛出list index out of range

如果需要alpaca继续训练，又要减少显存的占用该怎么处理？

**Comment by PLUTOXXXX** [comment]
同问！顶

**Comment by PLUTOXXXX** [comment]
你好兄弟，如果你解决了这个问题可以告诉我一下如何解决吗，感激不尽！

**Comment by LiemLin** [comment]
@PLUTOXXXX 可以的，解决了就发出来，目前还没好的办法，等博主或哪位大神帮忙看下有没有什么办法解决

**Comment by airaria** [comment]
@LiemLin 你的配置是：基模型是llama-7b + chinese-llama-plus合并后的模型，lora是 chinese-alpaca-plus的lora，是要继续训练这个lora，是吗？

**Comment by PLUTOXXXX** [comment]
> 

> @LiemLin 你的配置是：基模型是llama-7b + chinese-llama-plus合并后的模型，lora是 chinese-alpaca-plus的lora，是要继续训练这个lora，是吗？

是的，我是四张V100 16G的显卡。继续训练alpaca-plus的lora的时候遇到和博主同样的问题。

**Comment by rogerus** [comment]
> > 
> 
> > @LiemLin 你的配置是：基模型是llama-7b + chinese-llama-plus合并后的模型，lora是 chinese-alpaca-plus的lora，是要继续训练这个lora，是吗？
> 
> 是的，我是四张V100 16G的显卡。继续训练alpaca-plus的lora的时候遇到和博主同样的问题。

我用了4 * V100 32G，也是爆显存了

**Comment by airaria** [comment]
@LiemLin 日志里可训练参数量为0，lora_trainable是否正确设置？

**Comment by LiemLin** [comment]
@airaria 根据文档的提示，lora_trainable和其他一些参数注释掉了
<img width="930" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/c6b5e1b9-0a29-440c-b7e7-c5121afc04e4">

**Comment by LiemLin** [comment]
> @LiemLin 你的配置是：基模型是llama-7b + chinese-llama-plus合并后的模型，lora是 chinese-alpaca-plus的lora，是要继续训练这个lora，是吗？

是的，是第一种情况继续训练Chinese-Alpaca模型的LoRA权重，不是第二种情况基于中文Chinese-LLaMA训练全新的指令精调LoRA权重

**Comment by LiemLin** [comment]
@airaria @PLUTOXXXX @rogerus  方便的话可以加下微信LiemLin666一起交流

**Comment by LiemLin** [comment]
@airaria @PLUTOXXXX @rogerus 用zero3配置可以训练，3块24G 显卡每张差不多占用一半显存，64G的cpu内存

**Comment by rogerus** [comment]
> @airaria @PLUTOXXXX @rogerus 用zero3配置可以训练，3块24G 显卡每张差不多占用一半显存，64G的cpu内存

前几天试成功了zero3. 大概占用了40G左右的显存，不过跟max_seq_length也有关。如果prompt太长了显存占用也会飙升。

**Comment by nxotynry55853** [comment]
先把 chinese-llama 和 chinese-alpaca 两个lora 合并上去得到一个新的模型，不传入peft_model参数，直接使用合并后的模型进行微调，就可以正常运行了。 参考： https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/646

**Comment by Mryangkaitong** [comment]
> > @airaria @PLUTOXXXX @rogerus 用zero3配置可以训练，3块24G 显卡每张差不多占用一半显存，64G的cpu内存
> 
> 前几天试成功了zero3. 大概占用了40G左右的显存，不过跟max_seq_length也有关。如果prompt太长了显存占用也会飙升。

你好，我也用zero3跑了，loss也降了，但是在inference的时候，就发现回答的response和prompt不相关，请问遇到过这种问题吗？
<img width="723" alt="截屏2023-06-27 16 59 07" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/23132307/c36c4c42-f0f6-481c-99f1-fbc74c70a30c">
