### ISSUE TITLE
请问为什么设置512为Max length

### ISSUE THREAD

**Issue by cingtiye** [ymcui/Chinese-LLaMA-Alpaca#429]
非常感谢开源这么好的工作~
我有一个疑问，就是训练的时候，为什么都将Max length设置为512而不是2048？请问有做过对比实验吗？

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/32251546/6e8472ab-63b9-476d-b346-66cbd9eb9297)

**Comment by airaria** [comment]
很简单，因为计算资源有限。
要是有足够计算资源，当然可以开得更长
