### ISSUE TITLE
如何继续fine-tuning

### ISSUE THREAD

**Issue by Ferrair** [ymcui/Chinese-LLaMA-Alpaca#43]
如题，你好，想问下如何基于你训练好的Aplace在微调下呢？

**Comment by ymcui** [comment]
使用alpaca-lora：https://github.com/tloen/alpaca-lora

**Comment by puddinord** [comment]
> 使用alpaca-lora：https://github.com/tloen/alpaca-lora

alpaca-lora项目加载的是huggingface格式的模型，我按照step1的步骤，使用convert_llama_weights_to_hf.py脚本，将step2中的权重转换成了对应格式。

输入文件夹路径如下：
- zh_model/
   - tokenizer.model
   - 7B/
         - consolidated.00.pth
         - params.json
         - special_tokens_map.json
         - tokenizer_config.json

在实际微调过程中，报错如下：

> File "/root/miniconda2/envs/alpaca-lora/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 711, in forward
    shift_logits = shift_logits.view(-1, self.config.vocab_size)
RuntimeError: shape '[-1, 32000]' is invalid for input of size 408423904
  0%|          | 0/1665 [00:04<?, ?it/s]

最后发现是转换后config.json中，vocab_size还是原来的32000，我手动改成扩充后的词表大小后可以运行了。

但我有个疑问，除了这个vocab_size，还会有其他参数未匹配吗？附上转换后的config.json

>{
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 2048,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "pad_token_id": 0,
  "rms_norm_eps": 1e-06,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.28.0.dev0",
  "use_cache": true,
  "vocab_size": 32000
}

**Comment by airaria** [comment]
> > 使用alpaca-lora：https://github.com/tloen/alpaca-lora
> 
> alpaca-lora项目加载的是huggingface格式的模型，我按照step1的步骤，使用convert_llama_weights_to_hf.py脚本，将step2中的权重转换成了对应格式。
> 
> 输入文件夹路径如下：
> 
> * zh_model/
>   
>   * tokenizer.model
>   * 7B/
>     - consolidated.00.pth
>     - params.json
>     - special_tokens_map.json
>     - tokenizer_config.json
> 
> 在实际微调过程中，报错如下：
> 
> > File "/root/miniconda2/envs/alpaca-lora/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 711, in forward
> > shift_logits = shift_logits.view(-1, self.config.vocab_size)
> > RuntimeError: shape '[-1, 32000]' is invalid for input of size 408423904
> > 0%|          | 0/1665 [00:04<?, ?it/s]
> 
> 最后发现是转换后config.json中，vocab_size还是原来的32000，我手动改成扩充后的词表大小后可以运行了。
> 
> 但我有个疑问，除了这个vocab_size，还会有其他参数未匹配吗？附上转换后的config.json
> 
> > {
> > "architectures": [
> > "LlamaForCausalLM"
> > ],
> > "bos_token_id": 1,
> > "eos_token_id": 2,
> > "hidden_act": "silu",
> > "hidden_size": 4096,
> > "initializer_range": 0.02,
> > "intermediate_size": 11008,
> > "max_position_embeddings": 2048,
> > "model_type": "llama",
> > "num_attention_heads": 32,
> > "num_hidden_layers": 32,
> > "pad_token_id": 0,
> > "rms_norm_eps": 1e-06,
> > "tie_word_embeddings": false,
> > "torch_dtype": "float16",
> > "transformers_version": "4.28.0.dev0",
> > "use_cache": true,
> > "vocab_size": 32000
> > }

其他参数没有问题。
