### ISSUE TITLE
使用CPU进行本地推理报错

### ISSUE THREAD

**Issue by haiqiang819** [ymcui/Chinese-LLaMA-Alpaca#430]
### 详细描述问题

*使用CPU进行本地推理报错*

### 运行截图或日志

<img width="1179" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/129576711/649f17eb-00bf-407e-9f45-6d6c826dd039">

### 必查项目（前三项只保留你要问的）

- [x] **运行系统**：MacOS 13.3.1 M1 Pro 16G
- [x] **问题分类**：模型推理问题（🤗 transformers）
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案

**Comment by ymcui** [comment]
看错误信息说明有一部分权重已经需要offload了，所以猜测16G内存是否够用？建议在加载过程中看一下内存变化。

p.s. mac下用llama.cpp做推理更适合。

**Comment by haiqiang819** [comment]
好的，我尝试一下。感谢回答！
