### ISSUE TITLE
请问有交流群吗，使用了Chinese-Alpaca-Plus-13B模型来推理，中文内容表现不太行

### ISSUE THREAD

**Issue by YongjiangXu** [ymcui/Chinese-LLaMA-Alpaca#435]
想问下大家有这种中文交互情况吗，我用了Chinese-Alpaca-Plus 13B的模型，但是中文交互经常重复出词，而且意思相差太大了。此外请问有交流群或其他途径交流吗，谢谢

**Comment by YongjiangXu** [comment]
我补充些信息：我是合并了两个plus 13B模型了，web中直接用model，也尝试加载和不加载lora，中文交互效果一样不太行

**Comment by alingse** [comment]
+1， 我感觉数据质量不太行。

**Comment by YongjiangXu** [comment]
> +1， 我感觉数据质量不太行。

打算补充数据，自己再做微调了，从开源项目中有个json的中文数据集，看了一眼里面质量一般。

**Comment by YongjiangXu** [comment]
除了自己搞数据集，也有挺多开源的，如：https://github.com/voidful/awesome-chatgpt-dataset

**Comment by YongjiangXu** [comment]
我重新合并了一次模型，然后在Transformers上推理，效果可以，估计是web有问题或者合并有问题，暂未找到原因。不过还是感谢开发者的贡献！谢谢
