### ISSUE TITLE
关于模型合并和部分脚步问题

### ISSUE THREAD

**Issue by kostya-sec** [ymcui/Chinese-LLaMA-Alpaca#436]
作者你好，我想请教一些问题，暂时没能在Wiki中找到解答。下面默认底模均为7b。
1，在合并多模型之后（比如模型A)如果我想在新加入一个Lora进去，可以直接用A作为底模加Lora吗？这里会不会和文档中说的先llama后alpaca有冲突？还是说我需要重新用干净的7b模型把所有Lora写进去重新合并？

2，我看到vicuna的Lora模型也是用7b训练，那我在合并的时候是否也能llama，alpaca，vicuna Lora一起合并呢？

3，关于用openai API生成的一些指令数据，这个可以用在哪？以及如果我自己找了一些资料，我该如何处理我的数据集的格式，以便后续预处理和微调？

非常感谢。

**Comment by ymcui** [comment]
1）参考：https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/404
2）lora和基模型是有对应关系的，我们训出来的lora只能用在我们公布的基模型上，如果嫁接在其他模型上效果未知。
3）指令数据就是用来做指令精调的，具体数据格式参考：https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/训练细节

**Comment by kostya-sec** [comment]
您好。关于第三点。我想尝试微调关于剧本的Lora。大部分的指令精调使用数据模板是
{
    "instruction": "",
    "input": "",
    "output": ""
  }
我的原始数据类似下面这种：
一些环境描述和背景描述。
旁白：旁白说的话1.
角色1：角色1的话1.  （角色情绪和动作）
角色2：角色2的话1. （角色情绪和动作）
xxxx

如果是这样的话，想请教一下应该怎么样处理源数据到模板数据会比较合适。非常感谢

**Comment by airaria** [comment]
> 您好。关于第三点。我想尝试微调关于剧本的Lora。大部分的指令精调使用数据模板是 { "instruction": "", "input": "", "output": "" } 我的原始数据类似下面这种： 一些环境描述和背景描述。 旁白：旁白说的话1. 角色1：角色1的话1. （角色情绪和动作） 角色2：角色2的话1. （角色情绪和动作） xxxx
> 
> 如果是这样的话，想请教一下应该怎么样处理源数据到模板数据会比较合适。非常感谢

这类似多轮对话，可以参考我们提供的gradio_demo.py中的prompt构造方式。

**Comment by kostya-sec** [comment]
> > 您好。关于第三点。我想尝试微调关于剧本的Lora。大部分的指令精调使用数据模板是 { "instruction": "", "input": "", "output": "" } 我的原始数据类似下面这种： 一些环境描述和背景描述。 旁白：旁白说的话1. 角色1：角色1的话1. （角色情绪和动作） 角色2：角色2的话1. （角色情绪和动作） xxxx
> > 如果是这样的话，想请教一下应该怎么样处理源数据到模板数据会比较合适。非常感谢
> 
> 这类似多轮对话，可以参考我们提供的gradio_demo.py中的prompt构造方式。

非常感谢。我去尝试一下
