### ISSUE TITLE
关于在privateGPT上部署回答过慢的问题

### ISSUE THREAD

**Issue by GuoChang2032** [ymcui/Chinese-LLaMA-Alpaca#439]
看作者教程中说半分钟出结果,但我实际下来,三分钟出都算很快的了,是和cpu有关吗?CPU线程数我设置为12
cpu是i7-10 16核
不过生成的结果倒是不错,比较准确,缺点就是比较慢
![Snipaste_2023-05-26_13-52-48](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/24536679/894e54c1-0977-409d-910c-9bb254e882b6)

**Comment by ymcui** [comment]
后台其实是llama.cpp，本身是对ARM NEON做了优化的。
如果你按wiki中的方法改过线程数还是这速度的话那也没办法了。

**Comment by GuoChang2032** [comment]
> 后台其实是llama.cpp，本身是对ARM NEON做了优化的。 如果你按wiki中的方法改过线程数还是这速度的话那也没办法了。

OK~了解

**Comment by lvshuchengyin** [comment]
我的mac mini有24GB内存，模型是8.25GB大小，但是用privateGPT跑起来，看活动监视器，读取了1.2TB的字节，这个是不是很不正常？还是说8.25GB的模型，实际上跑起来的时候需要更多的内存呢？实际上单独跑模型，速度很快，内存也用的不多，就是用privateGPT有问题

**Comment by GuoChang2032** [comment]
> 我的mac mini有24GB内存，模型是8.25GB大小，但是用privateGPT跑起来，花了40分钟出结果，看活动监视器，读取了1.2TB的字节，这个是不是很不正常？还是说8.25GB的模型，实际上跑起来的时候需要更多的内存呢？实际上单独跑模型，速度很快，内存也用的不多，就是用privateGPT有问题

很不正常,一般五六分钟就出结果了,而且我跑的时候没占内存和显存,只占了CPU

**Comment by tluo-github** [comment]
我也准备提这个问题，我放到服务器上运行，32核(vCPU) 128 GiB, thread 给了30，用时 3min 左右。求优化思路。能加GPU 加速吗

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/5242590/b62b0b18-8d6a-4626-ada9-20b1ce8c4fc4)

**Comment by GuoChang2032** [comment]
@tluo-github 可以加n_gpu_layers参数
` llm = LlamaCpp(model_path=model_path, n_ctx=model_n_ctx,
                           callbacks=callbacks, verbose=False, n_threads=16,n_gpu_layers=1)`

**Comment by nixjoe** [comment]
我刚才在我的2680x2 上试了一下n_threads如果太大，倒反慢，打开verbose=True 有 tokens/second的可以对比一下

**Comment by tluo-github** [comment]
@GuoChang2032 感谢，我马上试试。
@nixjoe  在 32核(vCPU) 128 GiB, thread 30 情况下的日志
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/5242590/fcd94fb5-5e0a-41e8-8f9f-533f08160e37)

**Comment by nixjoe** [comment]
看起来挺正常的呀，迭代太多了吧，我现在想知道什么CPU能最大限度发挥llama.cpp 并且性价比适中

**Comment by tluo-github** [comment]
请问一下，怎么减少迭代？
我私有化部署，直接使用7b alpaca 模型问答速度非常快。
接入本地知识库之后，一次交互3分钟，30 CPU 全部 100%使用率。

**Comment by tluo-github** [comment]
@GuoChang2032 配置如下：
```
llm = LlamaCpp(
    model_path=model_path,
    n_ctx=model_n_ctx,
    callbacks=callbacks, 
    verbose=True,
    n_threads=8,
    n_gpu_layers=30,
)
```

看效果好像没有使用到 GPU
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/5242590/97a0cb00-26c3-479a-bbe7-3c066050ad72)

**Comment by ymcui** [comment]
> @GuoChang2032 配置如下：
> 
> ```
> llm = LlamaCpp(
>     model_path=model_path,
>     n_ctx=model_n_ctx,
>     callbacks=callbacks, 
>     verbose=True,
>     n_threads=8,
>     n_gpu_layers=30,
> )
> ```
> 
> 看效果好像没有使用到 GPU ![image](https://user-images.githubusercontent.com/5242590/241201682-97a0cb00-26c3-479a-bbe7-3c066050ad72.png)

如果要使用GPU的话，需要和cuBLAS一起编译。如果没有的话参考：https://github.com/abetlen/llama-cpp-python#installation-with-openblas--cublas--clblast

**Comment by oubotong** [comment]
用了GPU加速 (参考这里的cuBLAS编译[Here](https://github.com/imartinez/privateGPT/discussions/217))后, 由于显存只有8G吗，`n_gpu_layers`设置为16不会Out of memory. 然后 `n_threads`为20， 实际测试效果仍然很慢，大概要2-3分钟。

**Comment by GuoChang2032** [comment]
> > @GuoChang2032 配置如下：
> > ```
> > llm = LlamaCpp(
> >     model_path=model_path,
> >     n_ctx=model_n_ctx,
> >     callbacks=callbacks, 
> >     verbose=True,
> >     n_threads=8,
> >     n_gpu_layers=30,
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看效果好像没有使用到 GPU ![image](https://user-images.githubusercontent.com/5242590/241201682-97a0cb00-26c3-479a-bbe7-3c066050ad72.png)
> 
> 如果要使用GPU的话，需要和cuBLAS一起编译。如果没有的话参考：https://github.com/abetlen/llama-cpp-python#installation-with-openblas--cublas--clblast

试了下好像也没用到GPU

**Comment by oubotong** [comment]
> > > @GuoChang2032 配置如下：
> > > ```
> > > llm = LlamaCpp(
> > >     model_path=model_path,
> > >     n_ctx=model_n_ctx,
> > >     callbacks=callbacks, 
> > >     verbose=True,
> > >     n_threads=8,
> > >     n_gpu_layers=30,
> > > )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 看效果好像没有使用到 GPU ![image](https://user-images.githubusercontent.com/5242590/241201682-97a0cb00-26c3-479a-bbe7-3c066050ad72.png)
> > 
> > 
> > 如果要使用GPU的话，需要和cuBLAS一起编译。如果没有的话参考：https://github.com/abetlen/llama-cpp-python#installation-with-openblas--cublas--clblast
> 
> 试了下好像也没用到GPU

`pip install llama-cpp-python`时候需要enable CUBLAS `CMAKE_ARGS="-DLLAMA_CUBLAS=on"`, 详见上一个回答，这样就能用GPU了

**Comment by GuoChang2032** [comment]
@oubotong 是这些命令么？我在install前设置了但没用（已安装cuda-toolkit）
```
set LLAMA_CUBLAS=1
set CMAKE_ARGS=-DLLAMA_CUBLAS=on
set FORCE_CMAKE=1
pip install llama-cpp-python --no-cache-dir --verbose
```

**Comment by tluo-github** [comment]
使用 GPU 加速明显，现在只需要1分钟！
在 32核(vCPU) 128 GiB T4, thread=31, n_gpu_layers=32
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/5242590/ea8642df-8091-4b27-91b4-2909286e11df)

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/5242590/5ecc3ec2-bcf7-488c-a47c-b87838413297)
