### ISSUE TITLE
预训练后效果不佳，请教过程问题

### ISSUE THREAD

**Issue by chyyf006** [ymcui/Chinese-LLaMA-Alpaca#440]
我训练的过程如下：
1、下载chinese_llama_plus_lora_7b、chinese_alpaca_plus_lora_7b，并进行合并，脚本如下：
python scripts/merge_llama_with_chinese_lora.py \
    --base_model /home/dell/project/Chinese-LLaMA-Alpaca/models/llama_hf_models \
    --lora_model /home/dell/project/Chinese-LLaMA-Alpaca/models/chinese_llama_plus_lora_7b,/home/dell/project/Chinese-LLaMA-Alpaca/models/chinese_alpaca_plus_lora_7b \
    --output_type huggingface \
    --output_dir /home/dell/project/Chinese-LLaMA-Alpaca/models/merge_llama_lora  
2、基于chinese_llama_plus_lora_7b、chinese_alpaca_plus_lora_7b合并结果进行预训练，启动run_pt.sh进行训练，相关路径配置如下：
pretrained_model=/home/dell/project/Chinese-LLaMA-Alpaca/models/merge_llama_lora
chinese_tokenizer_path=/home/dell/project/Chinese-LLaMA-Alpaca/models/merge_llama_lora
dataset_dir=/home/dell/project/Chinese-LLaMA-Alpaca/data
data_cache=/home/dell/project/Chinese-LLaMA-Alpaca/cache_data
output_dir=/home/dell/project/Chinese-LLaMA-Alpaca/models/stage2
3、训练完成后，进行结果合并，数据拷贝过程如下：
cd stage2_models
cp /home/dell/project/Chinese-LLaMA-Alpaca/models/stage2/pytorch_model.bin adapter_model.bin
cp /home/dell/project/Chinese-LLaMA-Alpaca/models/chinese_llama_plus_lora_7b/adapter_config.json .
cp /home/dell/project/Chinese-LLaMA-Alpaca/models/chinese_llama_plus_lora_7b/*token* .
合并脚本如下：
python scripts/merge_llama_with_chinese_lora.py \
    --base_model /home/dell/project/Chinese-LLaMA-Alpaca/models/merge_llama_lora \
    --lora_model /home/dell/project/Chinese-LLaMA-Alpaca/models/stage2_models \
    --output_type pth \
    --output_dir /home/dell/project/Chinese-LLaMA-Alpaca/models/merge_llama_final 
4、按照wiki的步骤，拷贝merge_llama_final结果到llama.cpp下的zh-models，并执行：
 python convert.py zh-models/7B/    
./quantize ./zh-models/7B/ggml-model-f16.bin ./zh-models/7B/ggml-model-q5_0.bin q5_0
./main -m zh-models/7B/ggml-model-q5_0.bin --color -f prompts/alpaca.txt -ins -c 51200 --temp 0 -n 2048 --repeat_penalty 1.1

情况描述：
1、我训练的数据量在1.1GB，包含了专业书籍、相关论文及专业的问答数据，以行的方式，每行一个段落，并保存txt文件，放在/home/dell/project/Chinese-LLaMA-Alpaca/data目录；
2、通过命令行启动llama.cpp后，回答的问题，与没有进行data预训练的结果基本一致；
请教问题：
1、是不是我的过程有问题？
2、针对我这种情况，需要以什么方式或者过程训练比较好？

感谢各位贡献者的无私奉献！

### 必查项目（前三项只保留你要问的）

- [x ] **基础模型**：LLaMA-Plus / Alpaca-Plus
- [x ] **运行系统**：Ubuntu 
- [x ] **问题分类**：模型训练与精调

**Comment by ymcui** [comment]
粗看了一下，有几个疑点供你参考排查：
1、最后一步启动llama.cpp之后的log可以贴一下，另外看到temp设置为0，建议0.2-0.7试一下。
2、第三步最后的目录是merge_llama_final，在第四步开始的时候你提到`拷贝merge_llama_final结果到llama.cpp下的zh-models`，这一步可以再详细一点，比如，你是把`merge_llama_final`里的所有文件复制到`zh-models`下了还是`zh-models/7B`下了？如果是`zh-models/7B`的话，它的上一层也就是`zh-models`下应该保存的是你训练完的tokenizer.model文件，这一点你可以再确认一下。

**Comment by chyyf006** [comment]
> 粗看了一下，有几个疑点供你参考排查： 1、最后一步启动llama.cpp之后的log可以贴一下，另外看到temp设置为0，建议0.2-0.7试一下。 2、第三步最后的目录是merge_llama_final，在第四步开始的时候你提到`拷贝merge_llama_final结果到llama.cpp下的zh-models`，这一步可以再详细一点，比如，你是把`merge_llama_final`里的所有文件复制到`zh-models`下了还是`zh-models/7B`下了？如果是`zh-models/7B`的话，它的上一层也就是`zh-models`下应该保存的是你训练完的tokenizer.model文件，这一点你可以再确认一下。

感谢您的回复！
1、llama.cpp的启动日志如下：
(Chinese-LLaMA-Alpaca) dell@dell-Precision-3660:~/project/Chinese-LLaMA-Alpaca/llama.cpp$ ./main -m zh-models/7B/ggml-model-q5_0.bin --color -f prompts/alpaca.txt -ins -c 51200 --temp 0 -n 2048 --repeat_penalty 1.1
main: warning: model does not support context sizes greater than 2048 tokens (51200 specified);expect poor results
main: build = 583 (7e4ea5b)
main: seed  = 1685171870
llama.cpp: loading model from zh-models/7B/ggml-model-q5_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 49953
llama_model_load_internal: n_ctx      = 51200
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 8 (mostly Q5_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.07 MB
llama_model_load_internal: mem required  = 6307.39 MB (+ 1026.00 MB per state)
.
llama_init_from_file: kv self size  = 25600.00 MB

system_info: n_threads = 12 / 24 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 | 
main: interactive mode on.
Reverse prompt: '### Instruction:

'
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.000000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 51200, n_batch = 512, n_predict = 2048, n_keep = 21


== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.

 Below is an instruction that describes a task. Write a response that appropriately completes the request.


2、zh-models目录为空情况下，把merge_llama_final下所有文件都拷贝进入zh-models，并将special_tokens_map.json、tokenizer_config.json、tokenizer.model三个文件保留在zh-models根目录下，consolidated.00.pth、params.json文件进一步拷贝到zh-models/7B目录下，结构为：
zh-models：
     -special_tokens_map.json
     -tokenizer_config.json
     -tokenizer.model
     -7B
          -consolidated.00.pth
          -params.json

以上，谢谢。

**Comment by ymcui** [comment]
第三步拷贝`adapter_config.json`之前，是否检查过该配置文件和你的run_pt.sh文件中的配置一致？
```
adapter_config.json文件，修改其中的参数，确认其中的lora_alpha, r, modules_to_save, target_modules等参数与实际训练用的参数一致。
```

**Comment by ymcui** [comment]
另外llama.cpp可以试一下续写方式：
./main -m zh-models/7B/ggml-model-q5_0.bin --color -c 51200 --temp 0 -n 2048 --repeat_penalty 1.1 -p "你的prompt"

prompt可以输入一些你训练数据里出现的内容，看看它能不能续写出类似的文本。

**Comment by chyyf006** [comment]
> 第三步拷贝`adapter_config.json`之前，是否检查过该配置文件和你的run_pt.sh文件中的配置一致？
> 
> ```
> adapter_config.json文件，修改其中的参数，确认其中的lora_alpha, r, modules_to_save, target_modules等参数与实际训练用的参数一致。
> ```
感谢您的回复！
这个我确认了跟lora相关的参数是一致的。
以上，谢谢。

**Comment by chyyf006** [comment]
> 另外llama.cpp可以试一下续写方式： ./main -m zh-models/7B/ggml-model-q5_0.bin --color -c 2048 --temp 0.5 -n 2048 --repeat_penalty 1.1 -p "你的prompt"
> 
> prompt可以输入一些你训练数据里出现的内容，看看它能不能续写出类似的文本。


我测试了一下，貌似续写的跟我文本中的内容不一致

**Comment by chyyf006** [comment]
像我这种情况（本地有文献、书籍、问题列表等材料），比较合理的做法，如建议怎么训练，先后步骤，能给一些建议吗？

**Comment by ymcui** [comment]
因为我们没有尝试在alpaca模型上继续预训练（而不是指令精调），所以不好说现在这个情况具体原因。
从你的llama.cpp的运行日志来看，最后的词表大小为49953，其实对应的是llama模型，这与第一步合并出的模型（alpaca）词表大小不一样，可能这里会有点问题。

第一步：合并出来的其实是alpaca模型，词表大小为49954
第二步：使用了run_pt.sh训练，你传进去的词表也是alpaca的，现在就是看训练出的模型的词表大小是49954还是49953。
第三步：你复制的是llama的词表（49953），**所以此处能否替换为alpaca的试一下，看看后面的步骤能否合并转换和量化？**

**Comment by ymcui** [comment]
> 像我这种情况（本地有文献、书籍、问题列表等材料），比较合理的做法，如建议怎么训练，先后步骤，能给一些建议吗？

正好是个盲点。一般来说，
- llama接着预训练，词表大小不会变
- alpaca接着指令精调，词表大小也不会变
- llama接着指令精调，词表会变，但这个也是我们训练llama -> alpaca的pipeline，应该不会有问题
- **alpaca接着预训练**：这个就没有尝试过了，不排除会因为词表大小不一致存在潜在问题。

所以最合理的推荐是选择上面三种方式根据你自己的需求选择，看最终是需要一个指令交互模型（alpaca）还是一个单纯的语言模型（llama）。
- 需要指令模型：就选择在alpaca上进行指令精调（你现在合并的模型就是），你现在的数据要改为指令的格式，具体参照wiki
- 需要语言模型：把基模型换成llama，再用你现在的数据去训练。但要注意，这样训练出的模型在llama.cpp里不适合用`-ins`指令模式
- 需要

**Comment by chyyf006** [comment]
感谢您的回复！我来按照您的思路测试一下，谢谢

**Comment by jiaohuix** [comment]
嘿，你用了多大的显存呀？

**Comment by chyyf006** [comment]
> 



> > 像我这种情况（本地有文献、书籍、问题列表等材料），比较合理的做法，如建议怎么训练，先后步骤，能给一些建议吗？
> 
> 正好是个盲点。一般来说，
> 
> * llama接着预训练，词表大小不会变
> * alpaca接着指令精调，词表大小也不会变
> * llama接着指令精调，词表会变，但这个也是我们训练llama -> alpaca的pipeline，应该不会有问题
> * **alpaca接着预训练**：这个就没有尝试过了，不排除会因为词表大小不一致存在潜在问题。
> 
> 所以最合理的推荐是选择上面三种方式根据你自己的需求选择，看最终是需要一个指令交互模型（alpaca）还是一个单纯的语言模型（llama）。
> 
> * 需要指令模型：就选择在alpaca上进行指令精调（你现在合并的模型就是），你现在的数据要改为指令的格式，具体参照wiki
> * 需要语言模型：把基模型换成llama，再用你现在的数据去训练。但要注意，这样训练出的模型在llama.cpp里不适合用`-ins`指令模式

感谢您的指点，我调整了一下思路：
1、将llama_hf_models与chinese_llama_plus_lora_7b合并，指令如下：
python scripts/merge_llama_with_chinese_lora.py \
    --base_model /home/dell/project/Chinese-LLaMA-Alpaca/models/llama_hf_models \
    --lora_model /home/dell/project/Chinese-LLaMA-Alpaca/models/chinese_llama_plus_lora_7b \
    --output_type huggingface \
    --output_dir /home/dell/project/Chinese-LLaMA-Alpaca/models/stage2/merge_llama_lora 
2、基于merge_llama_lora调用run_pt.sh执行预训练，配置如下：
pretrained_model=/home/dell/project/Chinese-LLaMA-Alpaca/models/stage2/merge_llama_lora
chinese_tokenizer_path=/home/dell/project/Chinese-LLaMA-Alpaca/models/stage2/merge_llama_lora
dataset_dir=/home/dell/project/Chinese-LLaMA-Alpaca/data
data_cache=/home/dell/project/Chinese-LLaMA-Alpaca/cache_data
output_dir=/home/dell/project/Chinese-LLaMA-Alpaca/models/stage2/finetuning
3、然后进行处理，如下：
cd stage2/tuned_final
cp /home/dell/project/Chinese-LLaMA-Alpaca/models/stage2/finetuning/pytorch_model.bin adapter_model.bin
cp /home/dell/project/Chinese-LLaMA-Alpaca/models/chinese_llama_plus_lora_7b/adapter_config.json .
cp /home/dell/project/Chinese-LLaMA-Alpaca/models/chinese_llama_plus_lora_7b/*token* .
4、将llama_hf_models与chinese_alpaca_plus_lora_7b合并，指令如下：
python scripts/merge_llama_with_chinese_lora.py \
    --base_model /home/dell/project/Chinese-LLaMA-Alpaca/models/llama_hf_models \
    --lora_model /home/dell/project/Chinese-LLaMA-Alpaca/models/chinese_alpaca_plus_lora_7b \
    --output_type huggingface \
    --output_dir /home/dell/project/Chinese-LLaMA-Alpaca/models/stage3/merge_alpaca_lora 
5、基于merge_alpaca_lora进行指令精调，调用run_sft.sh进行训练，配置如下：
pretrained_model=/home/dell/project/Chinese-LLaMA-Alpaca/models/stage3/merge_alpaca_lora
chinese_tokenizer_path=/home/dell/project/Chinese-LLaMA-Alpaca/models/stage3/merge_alpaca_lora
dataset_dir=/home/dell/project/Chinese-LLaMA-Alpaca/data
output_dir=/home/dell/project/Chinese-LLaMA-Alpaca/models/stage3/finetuning
validation_file=/home/dell/project/Chinese-LLaMA-Alpaca/scripts/prompt.json
6、然后进行处理，如下：
cd stage3/tuned_final
cp /home/dell/project/Chinese-LLaMA-Alpaca/models/stage3/finetuning/pytorch_model.bin adapter_model.bin
cp /home/dell/project/Chinese-LLaMA-Alpaca/models/chinese_alpaca_plus_lora_7b/adapter_config.json .
cp /home/dell/project/Chinese-LLaMA-Alpaca/models/chinese_alpaca_plus_lora_7b/*token* . 
7、进行合并，指令如下：
python scripts/merge_llama_with_chinese_lora.py \
    --base_model /home/dell/project/Chinese-LLaMA-Alpaca/models/llama_hf_models \
    --lora_model /home/dell/project/Chinese-LLaMA-Alpaca/models/stage2/tuned_final,/home/dell/project/Chinese-LLaMA-Alpaca/models/stage3/tuned_final \
    --output_type pth \
    --output_dir /home/dell/project/Chinese-LLaMA-Alpaca/models/final_models  

执行合并操作时报错，如下：
Peft version: 0.3.0
Loading LoRA for 7B model
Loading LoRA /home/dell/project/Chinese-LLaMA-Alpaca/models/stage2/tuned_final...
base_model vocab size: 32000
tokenizer vocab size: 49953
Extended vocabulary size to 49953
Loading LoRA weights
Merging with merge_and_unload...
Loading LoRA /home/dell/project/Chinese-LLaMA-Alpaca/models/stage3/tuned_final...
base_model vocab size: 49953
tokenizer vocab size: 49954
Extended vocabulary size to 49954
Loading LoRA weights
Traceback (most recent call last):
  File "/home/dell/project/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py", line 264, in <module>
    raise e
  File "/home/dell/project/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py", line 253, in <module>
    lora_model = PeftModel.from_pretrained(
  File "/home/dell/anaconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.9/site-packages/peft/peft_model.py", line 181, in from_pretrained
    model.load_adapter(model_id, adapter_name, **kwargs)
  File "/home/dell/anaconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.9/site-packages/peft/peft_model.py", line 376, in load_adapter
    set_peft_model_state_dict(self, adapters_weights, adapter_name=adapter_name)
  File "/home/dell/anaconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.9/site-packages/peft/utils/save_and_load.py", line 123, in set_peft_model_state_dict
    model.load_state_dict(peft_model_state_dict, strict=False)
  File "/home/dell/anaconda3/envs/Chinese-LLaMA-Alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
        size mismatch for base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight: copying a param with shape torch.Size([8, 4096]) from checkpoint, the shape in current model is torch.Size([64, 4096]).
        size mismatch for base_model.model.model.layers.0.self_attn.q_proj.lora_B.default.weight: copying a param with shape torch.Size([4096, 8]) from checkpoint, the shape in current model is torch.Size([4096, 64]).
        size mismatch for base_model.model.model.layers.0.self_attn.k_proj.lora_A.default.weight: copying a param with shape torch.Size([8, 4096]) from checkpoint, the shape in current model is torch.Size([64, 4096]).
        size mismatch for base_model.model.model.layers.0.self_attn.k_proj.lora_B.default.weight: copying a param with shape torch.Size([4096, 8]) from checkpoint, the shape in current model is torch.Size([4096, 64]).
        size mismatch for base_model.model.model.layers.0.self_attn.v_proj.lora_A.default.weight: copying a param with shape torch.Size([8, 4096]) from checkpoint, the shape in current model is torch.Size([64, 4096]).
        size mismatch for base_model.model.model.layers.0.self_attn.v_proj.lora_B.default.weight: copying a param with shape torch.Size([4096, 8]) from checkpoint, the shape in current model is torch.Size([4096, 64]).

是不是第5步需要指定peft_model参数？或者其他问题？

另，我配置一台DELL T640，内存：256，4张3090 GPU卡。

以上，谢谢。

**Comment by airaria** [comment]
1～3步基于(llama_hf+llama_plus_lora)训练了一个llama,
4～6步又基于(llama_hf+alpaca_plus_lora)训练了一个alpaca，然后合并了这两个模型？
有好几个问题：
1. 第四步合并alpaca时需要用**llama_plus_lora和alpaca_plus_lora**，但你似乎只用了一个
2. 1～3训练的模型和4～6训练的模型不能合并，这相当于两个独立的模型了。应该在1～3的模型基础上再指令精调，而不是基于(llama_hf+alpaca_plus_lora)指令精调
3. 从报错的信息看，lora配置和lora权重大小不匹配，检查`adapter_config.json`确保各lora参数与训练时一致。

**Comment by jiaohuix** [comment]
@chyyf006 lora指令精调的时候，需要多少显存额，我32g的v100怎么OOM了，单卡跑不了?

**Comment by chyyf006** [comment]
> @chyyf006 lora指令精调的时候，需要多少显存额，我32g的v100怎么OOM了，单卡跑不了?
您好，指令精调7B我这边4张3090，一般占用是18+19+20+20GB，一张V100应该不行，需要两张以上，13B我看其他训练朋友应该在4张32GBV100，可以做预训练和指令精调

**Comment by chyyf006** [comment]
> 1～3步基于(llama_hf+llama_plus_lora)训练了一个llama, 4～6步又基于(llama_hf+alpaca_plus_lora)训练了一个alpaca，然后合并了这两个模型？ 有好几个问题：
> 
> 1. 第四步合并alpaca时需要用**llama_plus_lora和alpaca_plus_lora**，但你似乎只用了一个
> 2. 1～3训练的模型和4～6训练的模型不能合并，这相当于两个独立的模型了。应该在1～3的模型基础上再指令精调，而不是基于(llama_hf+alpaca_plus_lora)指令精调
> 3. 从报错的信息看，lora配置和lora权重大小不匹配，检查`adapter_config.json`确保各lora参数与训练时一致。
感谢您的回复！
我马上试一下，谢谢。

**Comment by jiaohuix** [comment]
@chyyf006  我关注到指令精调的时候，用了lora后可训练的参数量在40%左右，这导致了显存炸了。我在预训练的时候去掉了lm_head,只保留embed_tokens可训练，参数量大概在11%左右，训练时是27g显存。我暂时没找到指令精调参数多的原因，大佬你能看下你的参数量占多少么？

![7c1bb665292b9771dd56116327d07f0](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/68314259/81be741d-6dd5-485d-bcb6-ef643ba7c0af)
![51fa8db32b5fd76881a445b0255c577](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/68314259/98d84cd0-e3e1-46a0-b648-8bc0a7a3317c)

**Comment by chyyf006** [comment]
> @chyyf006 我关注到指令精调的时候，用了lora后可训练的参数量在40%左右，这导致了显存炸了。我在预训练的时候去掉了lm_head,只保留embed_tokens可训练，参数量大概在11%左右，训练时是27g显存。我暂时没找到指令精调参数多的原因，大佬你能看下你的参数量占多少么？
> 
> ![7c1bb665292b9771dd56116327d07f0](https://user-images.githubusercontent.com/68314259/241483626-81be741d-6dd5-485d-bcb6-ef643ba7c0af.png) ![51fa8db32b5fd76881a445b0255c577](https://user-images.githubusercontent.com/68314259/241483674-98d84cd0-e3e1-46a0-b648-8bc0a7a3317c.png)

您好，我这边的参数情况如下：
run_sft.sh的情况：
![7461685254734_ pic](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/132124560/568650aa-2969-4614-913a-d9baa05c9f7d)
run_pt.sh的情况：
![7471685254810_ pic](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/132124560/eca5de58-159e-4df4-89d9-7b65b46c511a)

**Comment by chyyf006** [comment]
> > 1～3步基于(llama_hf+llama_plus_lora)训练了一个llama, 4～6步又基于(llama_hf+alpaca_plus_lora)训练了一个alpaca，然后合并了这两个模型？ 有好几个问题：
> > 
> > 1. 第四步合并alpaca时需要用**llama_plus_lora和alpaca_plus_lora**，但你似乎只用了一个
> > 2. 1～3训练的模型和4～6训练的模型不能合并，这相当于两个独立的模型了。应该在1～3的模型基础上再指令精调，而不是基于(llama_hf+alpaca_plus_lora)指令精调
> > 3. 从报错的信息看，lora配置和lora权重大小不匹配，检查`adapter_config.json`确保各lora参数与训练时一致。
> 
> 感谢您的回复！ 我马上试一下，谢谢。

感谢您的支持！
我核对了一下pt和sft的LoRA及adapter_config.json的参数，统一以后可以合并了，但是合并后的结果非常差，可能是顺序问题，我再按照您的建议：
第四步合并alpaca时需要用llama_plus_lora和alpaca_plus_lora，但你似乎只用了一个
1～3训练的模型和4～6训练的模型不能合并，这相当于两个独立的模型了。应该在1～3的模型基础上再指令精调，而不是基于(llama_hf+alpaca_plus_lora)指令精调
重新试一次，谢谢。

**Comment by jiaohuix** [comment]
@chyyf006 我按照sft的教程， 对合并“llm-lora”和“alpaca-lora”后的hf_model进行指令微调，然后根据“如果想继续训练Chinese-Alpaca模型的LoRA权重：", 删除了--lora、--trainable和--modules_to_save参数，此外，修改”chinese-alpaca-plus-lora-7b/adapter_config.json 的参数："modules_to_save":null,  结果可训练参数变成100%了，能给下大佬你的训练脚本嘛？

**Comment by chyyf006** [comment]
> @chyyf006 我按照sft的教程， 对合并“llm-lora”和“alpaca-lora”后的hf_model进行指令微调，然后根据“如果想继续训练Chinese-Alpaca模型的LoRA权重：", 删除了--lora、--trainable和--modules_to_save参数，此外，修改”chinese-alpaca-plus-lora-7b/adapter_config.json 的参数："modules_to_save":null, 结果可训练参数变成100%了，能给下大佬你的训练脚本嘛？

您好，您要去除modules_to_save="embed_tokens,lm_head"这个参数的话，需要改：
##如果机器的显存比较紧张，可以删去脚本中的--modules_to_save ${modules_to_save} , 
###即不训练embed_tokens和lm_head（这两部分参数量较大），只训练LoRA参数，以节省显存
###建议以Chinese-LLaMA权重进行初始化之后进行实验，而非从头预训练时，就不训练embed_tokens和lm_head
###其次在对应的adapter_config.json配置文件中修改，才能彻底去除
###如果执行上一步操作后程序有报错，请删除--gradient_checkpointing \再尝试

您需要看看adapter_config.json配置文件

**Comment by YongjiangXu** [comment]
> 

你好，想请教下WIKI中提到的：1.无需指定--lora_rank、--lora_alpha、--lora_dropout、--trainable和--modules_to_save参数。这个意思是直接在脚本中删去吗？
还想请教下 2.微调之后，怎么合并模型，例如 对合并“llm-lora”和“alpaca-lora”后的hf_model进行指令微调，如果微调之后得到lora权重文件，是怎么和之前的hf_model合并，是使用WIKI中手动合并模型里的单LoRA权重合并吗？
以上，谢谢。

**Comment by iMountTai** [comment]
@YongjiangXu 1. 直接删掉也行，不删掉也可以，因为在指定`peft_model`参数后，lora相关参数不再起作用
2. 可以
3. 微调后，在您**第二步合并模型的基础上**再合并微调之后得到的lora权重文件，参考WIKI中手动合并模型里的单LoRA权重合并

**Comment by YongjiangXu** [comment]
> @YongjiangXu 1. 直接删掉也行，不删掉也可以，因为在指定`peft_model`参数后，lora相关参数不再起作用 2. 可以 3. 微调后，在您**第二步合并模型的基础上**再合并微调之后得到的lora权重文件，参考WIKI中手动合并模型里的单LoRA权重合并

谢谢您

**Comment by chengyangfeng** [comment]
@YongjiangXu 你好，我的过程和你基本一致，效果不佳请问你最终有解决吗

**Comment by YongjiangXu** [comment]
> @YongjiangXu 你好，我的过程和你基本一致，效果不佳请问你最终有解决吗

你好还未解决，如有办法及时分享

**Comment by LiemLin** [comment]
@chengyangfeng @YongjiangXu  我也有训练后效果不佳的问题，方便的话可以加微信LiemLin666交流
