### ISSUE TITLE
pretrain之后得到的pytorch_mode.bin 需要用zero_to_fp32.py转换吗？

### ISSUE THREAD

**Issue by Antiman-cmyk** [ymcui/Chinese-LLaMA-Alpaca#442]
pretrain之后，instruction tuning之前，pytorch_mode.bin 需要用zero_to_fp32.py转换吗？还是instruction tuning之后转换？
因为instruction tuning 用 转换之后的fp32 finetune 一直有问题，deepspeed一直显示梯度爆栈

**Comment by airaria** [comment]
用zero2的话，不需要转换，按照[wiki里的说明](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/预训练脚本#训练后文件整理)整理一下相关文件就可以了

**Comment by Antiman-cmyk** [comment]
懂了，谢谢。

**Comment by Antiman-cmyk** [comment]
还有个问题，在pretrain之后model上继续做instruction tuning也完成了，合并pretrain model + instruction tuning lora 模型的时候，为什么出现了size mismatch的问题，而且刚好差一个。pretrain 和 tuning 用的都是相同的tokenizer。
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/53069142/2aa3bde0-8b2c-4ef6-bf3c-a0abd61aea25)
@airaria

**Comment by Antiman-cmyk** [comment]
> 还有个问题，在pretrain之后model上继续做instruction tuning也完成了，合并pretrain model + instruction tuning lora 模型的时候，为什么出现了size mismatch的问题，而且刚好差一个。pretrain 和 tuning 用的都是相同的tokenizer。 ![image](https://user-images.githubusercontent.com/53069142/241573288-2aa3bde0-8b2c-4ef6-bf3c-a0abd61aea25.png) @airaria

解决了，tokenizer容易搞混。感谢回复，先关闭这个issue了
