### ISSUE TITLE
指令精调出现eval_loss  =   nan

### ISSUE THREAD

**Issue by YongjiangXu** [ymcui/Chinese-LLaMA-Alpaca#444]
指令精调时候出现这样的结果：
***** eval metrics *****
  epoch                   =        0.0
  eval_loss               =        nan
  eval_runtime            = 4:23:32.05
  eval_samples            =     287335
  eval_samples_per_second =     18.172
  eval_steps_per_second   =     18.172
  perplexity              =        nan

第一次精调成功，不会返回nan，接着在第一次精调的模型上继续调整，就出现了这个，想请教下可以这样迭代精调吗?还是这个报错是因为我用默认的参数是不合理的？

**Comment by YongjiangXu** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/112735821/ea3f5b48-9ee3-4bac-838e-31aebc9dfeb1)

**Comment by YongjiangXu** [comment]
想请教下如果是用自己领域数据精调，是要用转换后的原版llmma和Chinese-LLaMA-Plus-7B 进行第一次合并，然后在精调脚本上对Chinese-Alpaca-Plus-7B 的LoRA权重进行调整吗？得到一个新的LoRA权重后和第一次合并后的模型再次合并吗？

**Comment by iMountTai** [comment]
第一次精调后的模型再微调时，不需要加`peft_model`参数了，或者将`peft_model`设置为第一次精调后保存的peft权重

**Comment by YongjiangXu** [comment]
> 第一次精调后的模型再微调时，不需要加`peft_model`参数了，或者将`peft_model`设置为第一次精调后保存的peft权重

谢谢您的回复。还想请教下，精调得到的 权重文件，想问下是怎么合并起来，是使用WIKI手动模型合并中的多LoRA权重合并吗，即原版llama模型和Chinese-LLaMA权重，以及我得到的 权重文件吗？谢谢

**Comment by iMountTai** [comment]
精调的Chinese-Alpaca-plus，那就应该在Chinese-Alpaca-plus的基础上合并您精调后的权重

**Comment by YongjiangXu** [comment]
> 精调的Chinese-Alpaca-plus，那就应该在Chinese-Alpaca-plus的基础上合并您精调后的权重

好的感谢您

**Comment by B15031011** [comment]
我也有这个问题，我是想在chinese-alpaca-7b的基础上进一步精调，但是val的loss一直是nan
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/19522483/2e5e149c-7366-4759-b92c-0aad390c10fd)
