### ISSUE TITLE
合并模型之后缺少config文件

### ISSUE THREAD

**Issue by sssssshf** [ymcui/Chinese-LLaMA-Alpaca#445]
*提示：将[ ]中填入x，表示打对钩。提问时删除这行。只保留符合的选项。*

 转LLaMA 到hf没问题,联合lora模型转
python scripts/merge_llama_with_chinese_lora.py \
    --base_model LLaMA_HF_13B \
    --lora_model chinese_llama_plus_lora_13b,chinese_alpaca_plus_lora_13b \
    --output_type pth \
    --output_dir merge_weights 也没有问题.
然后运行示例代码 出现错误,,提示转模型后的路径里  merge_weights里没有config文件

*请尽量具体地描述您遇到的问题，**必要时给出运行命令**。这将有助于我们更快速地定位问题所在。*
![Uploading image.png…]()

*请提供文本log或者运行截图，以便我们更好地了解问题详情。*

### 必查项目（前三项只保留你要问的）

- [Alpaca-Plus ] **基础模型**：LLaMA / Alpaca / LLaMA-Plus / Alpaca-Plus
- [ linux] **运行系统**：Windows / MacOS / Linux 
- [  模型推理问题] **问题分类**：下载问题 / 模型转换和合并 / 模型训练与精调 / 模型推理问题（🤗 transformers） / 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat） / 效果问题 / 其他问题
- [ x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by ymcui** [comment]
图挂了。另外你说的`示例代码`具体是什么代码？llama.cpp？huggingface inference？

**Comment by 455849940** [comment]
13b的合并模型之后没有config.json，跑代码在LlamaForCausalLM.from_pretrained阶段会提示缺少config.json

**Comment by airaria** [comment]
你设置的输出格式是pth，这种格式是不能被transformers加载的。
请在合并时指定 `--output_type huggingface`

**Comment by 455849940** [comment]
ok，已经发现问题了，希望可以在transformers加载的link里说明一下，之前一直没注意输出格式的问题，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ziqing ***@***.***&gt;; 
发送时间: 2023年5月31日(星期三) 下午2:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ymcui/Chinese-LLaMA-Alpaca] 合并模型之后缺少config文件 (Issue #445)





 
你设置的输出格式是pth，这种格式是不能被transformers加载的。
 请在合并时指定 --output_type huggingface
