### ISSUE TITLE
训练的alpaca 7B模型部分回答会重复

### ISSUE THREAD

**Issue by liuxiaohao-xn** [ymcui/Chinese-LLaMA-Alpaca#449]
*提示：将[ ]中填入x，表示打对钩。提问时删除这行。只保留符合的选项。*

### 详细描述问题

用llama-7b-plus模型基于train_2M_CN数据集训练alpaca-7b-plus模型，测试时，发现有的问题回答的好，有的回答会出现一直重复的问题。

### 运行截图或日志
![1685341685(1)](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/33827275/48749fdf-2a42-4b0f-a23a-7971cdc39c2b)
![1685341722(1)](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/33827275/23712c6b-c0ee-4460-a703-6347163dcb1c)

请问有什么办法可以调优吗

### 必查项目（前三项只保留你要问的）

- [x] **基础模型**： Alpaca-Plus
- [x] **运行系统**：Linux 
- [x] **问题分类**：模型推理问题（🤗 transformers） /效果问题 / 其他问题
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案

**Comment by airaria** [comment]
是否尝试过用llama.cpp，是否也有这种现象？

**Comment by liuxiaohao-xn** [comment]
> 是否尝试过用llama.cpp，是否也有这种现象？

感谢回复，目前还没有尝试，顺问下用llama.cpp进行量化后会缓解生成重复问题，这个是什么原理呢？

**Comment by airaria** [comment]
> > 是否尝试过用llama.cpp，是否也有这种现象？
> 
> 感谢回复，目前还没有尝试，顺问下用llama.cpp进行量化后会缓解生成重复问题，这个是什么原理呢？

不确定，所以希望您这边可以测试一下，以帮助我们定位问题。
