### ISSUE TITLE
关于alpaca和lora

### ISSUE THREAD

**Issue by wwwadx** [ymcui/Chinese-LLaMA-Alpaca#45]
请问lora是在哪一步做的，我看下来的理解是1. llama做了词表扩充及中文pre-trian, 2. alpaca模式进行了微调。 那么lora是在alpaca基础上做的吗，还是微调这一步没有做finetune，而是直接lora了？

**Comment by wwwadx** [comment]
大概明白了，在llama基础上的pre-train实际上是在train lora, 后面alpaca模式的finetune也是在train lora. 请教一下这个理解是否正确？还有就是lora这种delta-tuning和直接fine-tuning更新整个模型参数的效果差别大吗？感谢！

**Comment by ymcui** [comment]
1. 对
2. 我们只做过非常初步的定性分析，差别并是不特别大。但也有可能是因为训练步数不足等原因，不足以去分辨这两者的区别。

**Comment by wwwadx** [comment]
> 1. 对
> 2. 我们只做过非常初步的定性分析，差别并是不特别大。但也有可能是因为训练步数不足等原因，不足以去分辨这两者的区别。

感谢解答！

**Comment by ZenXir** [comment]
@ymcui 
pre-train 和 finetune 时的prompt是什么样的？

我是这样操作的：
1、把原Llama模型和 提供的 [中文LLaMA/Alpaca模型](选其一) 合并了
2、通过 transformers/models/llama/convert_llama_weights_to_hf.py 脚本，把合并后的模型转成 huggingface格式
3、基于huggingface格式合并后的模型 基础上 finetuning

想知道大佬的 pre-train / finetune 时的prompt是什么样的？
看是否和大佬的一样？

**Comment by airaria** [comment]
> @ymcui pre-train 和 finetune 时的prompt是什么样的？
> 
> 我是这样操作的： 1、把原Llama模型和 提供的 [中文LLaMA/Alpaca模型](%E9%80%89%E5%85%B6%E4%B8%80) 合并了 2、通过 transformers/models/llama/convert_llama_weights_to_hf.py 脚本，把合并后的模型转成 huggingface格式 3、基于huggingface格式合并后的模型 基础上 finetuning
> 
> 想知道大佬的 pre-train / finetune 时的prompt是什么样的？ 看是否和大佬的一样？

Pre-training时没有使用Prompt，用的是标准的自回归生成目标训练；
Finetune时用的prompt和Stanford Alpaca的Prompt一致，稍有变动，README中有的训练细节一节有说明

**Comment by ZenXir** [comment]
finetune 和 inference 的prompt 都是这样的吧？
因为取消了 input , 描述部分是一样，只有 Instruction 的区别，当有 input时，改成这样： f"{data_point["instruction"]}+\n+{data_point["input"]}" 即可吧？

```
    user_prompt = (
        if data_point["input"]:
            f"""Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
f"{data_point["instruction"]}+\n+{data_point["input"]}"

### Response:
"""
        else:
            f"""Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
{data_point["instruction"]}

### Response:
"""
    )
```

**Comment by airaria** [comment]
> finetune 和 inference 的prompt 都是这样的吧？ 因为取消了 input , 描述部分是一样，只有 Instruction 的区别，当有 input时，改成这样： f"{data_point["instruction"]}+\n+{data_point["input"]}" 即可吧？
> 
> ```
>     user_prompt = (
>         if data_point["input"]:
>             f"""Below is an instruction that describes a task. Write a response that appropriately completes the request.
> 
> ### Instruction:
> f"{data_point["instruction"]}+\n+{data_point["input"]}"
> 
> ### Response:
> """
>         else:
>             f"""Below is an instruction that describes a task. Write a response that appropriately completes the request.
> 
> ### Instruction:
> {data_point["instruction"]}
> 
> ### Response:
> """
>     )
> ```

是的。

**Comment by ZenXir** [comment]
> @ymcui 
> 
> 我是这样操作的： 1、把原Llama模型和 提供的 [中文LLaMA/Alpaca模型](%E9%80%89%E5%85%B6%E4%B8%80) 合并了 2、通过 transformers/models/llama/convert_llama_weights_to_hf.py 脚本，把合并后的模型转成 huggingface格式 3、基于huggingface格式合并后的模型 基础上 finetuning
> 
> 

这个finetune方法，正确不？
是不是合并后，就可以直接finetune？第二步可以省略吗？

**Comment by airaria** [comment]
> > @ymcui
> > 我是这样操作的： 1、把原Llama模型和 提供的 [中文LLaMA/Alpaca模型](%E9%80%89%E5%85%B6%E4%B8%80) 合并了 2、通过 transformers/models/llama/convert_llama_weights_to_hf.py 脚本，把合并后的模型转成 huggingface格式 3、基于huggingface格式合并后的模型 基础上 finetuning
> 
> 这个finetune方法，正确不？ 是不是合并后，就可以直接finetune？第二步可以省略吗？

看起来是合理的。
你基于原版的LLaMA的代码就省略第二步；用HF代码就需要第二步
