### ISSUE TITLE
采用 run_clm_pt_with_peft.py 训练完后，模型产生灾难性遗忘，请问如何解决？

### ISSUE THREAD

**Issue by tanghui315** [ymcui/Chinese-LLaMA-Alpaca#450]
参数：
python run_clm_pt_with_peft.py \
        --model_name_or_path /xxx \
        --tokenizer_name_or_path /xxx \
        --dataset_dir /xxx \
        --data_cache_dir /xxx \
        --validation_split_percentage 0.01 \
        --do_train \
        --seed 123 \
        --fp16 \
        --max_steps 10000 \
        --lr_scheduler_type cosine \
        --warmup_ratio 0.05 \
        --weight_decay 0.01 \
        --learning_rate 2e-4 \
        --logging_strategy steps \
        --logging_steps 10 \
        --save_strategy steps \
        --save_total_limit 10 \
        --save_steps 500 \
        --gradient_accumulation_steps 1 \
        --preprocessing_num_workers 8 \
        --block_size 512 \
        --output_dir /output/xxx \
        --overwrite_output_dir \
        --ddp_timeout 30000 \
        --logging_first_step True \
        --lora_rank 8 \
        --lora_alpha 32 \
        --trainable "q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj" \
        --lora_dropout 0.1 \
        --model_type "llama" \
        --torch_dtype float16 \

### 详细描述问题
2600条 txt 数据 ，训练完后， 合并完模型，llama.cpp 运行。 只能回答我训练数据相关的内容，这块内容回答的能打80分。
但问题是，对于模型之前的能力，几乎全忘，连“你是谁？” 这个问题都回答不了。
按道理 lora 不应该这样差， 为何这样？是我的训练参数不对？过拟合了？

**Comment by ymcui** [comment]
在什么模型上训的？

**Comment by tanghui315** [comment]
> 在什么模型上训的？

使用 merge_llama_with_chinese_lora.py  合并了 decapoda-research/llama-7b-hf ，ziqingyang/chinese-llama-plus-lora-7b,ziqingyang/chinese-alpaca-plus-lora-7b  这三个模型后得到的一个模型上面继续训的。运行参数如下：
python ./Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py \
    --base_model decapoda-research/llama-7b-hf \
    --lora_model ziqingyang/chinese-llama-plus-lora-7b,ziqingyang/chinese-alpaca-plus-lora-7b \
    --output_type huggingface \
    --output_dir alpaca-combined

**Comment by iMountTai** [comment]
微调的话应该是运行`run_clm_sft_with_peft.py`，现在相当于你用2600条 txt 数据又做了一次预训练

**Comment by tanghui315** [comment]
> 微调的话应该是运行`run_clm_sft_with_peft.py`，现在相当于你用2600条 txt 数据又做了一次预训练

我的 txt 数据是大段长文本 。没有类似 alpaca 结构。  本意是想先做一次 预训练， 然后再做微调。

**Comment by ymcui** [comment]
alpaca上继续用纯文本预训练效果会如何不好说，因为再次预训练的时候不像指令精调一样包含alpaca指令模板。
当然，你也可以通过减少预训练的轮数以及降低学习率来减少对原模型的影响。
可以大致算一下，目前这套超参会在你的小数据上迭代多少轮。如果轮数比较多可以先考虑只训1-2轮。

**Comment by tanghui315** [comment]
> alpaca上继续用纯文本预训练效果会如何不好说，因为再次预训练的时候不像指令精调一样包含alpaca指令模板。 当然，你也可以通过减少预训练的轮数以及降低学习率来减少对原模型的影响。 可以大致算一下，目前这套超参会在你的小数据上迭代多少轮。如果轮数比较多可以先考虑只训1-2轮。
好的，感谢回复，目前我跑了30轮，可能有点多了。 我降低轮数，不合并 alpaca 那个 lora ，再试一试。

**Comment by tanghui315** [comment]
> alpaca上继续用纯文本预训练效果会如何不好说，因为再次预训练的时候不像指令精调一样包含alpaca指令模板。 当然，你也可以通过减少预训练的轮数以及降低学习率来减少对原模型的影响。 可以大致算一下，目前这套超参会在你的小数据上迭代多少轮。如果轮数比较多可以先考虑只训1-2轮。

好的，感谢回复，目前我跑了30轮，可能有点多了。 我降低轮数，不合并 alpaca 那个 lora ，再试一试。

**Comment by henryGao9** [comment]
作者您好，我也出现了类似的问题，我想对某领域进行二次预训练，我操作的步骤如下(只操作过一次)：
1、使用run_clm_pt_with_peft.py脚本在单机单卡的环境下：
torchrun --nnodes 1 --nproc_per_node 1 run_clm_pt_with_peft.py 
--deepspeed ds_zero2_no_offload.json 
--model_name_or_path test_output_7B # 使用merge_llama_with_chinese_lora对原版llama的hf文件与chinese_llama_lora_7b合并后结果
--tokenizer_name_or_path chinese_llama_lora_7b 
--dataset_dir dataset-txt 
--data_cache_dir data_cache 
--validation_split_percentage 0.001 
--per_device_train_batch_size 1 
--per_device_eval_batch_size 1 
--do_train 
--seed $RANDOM 
--fp16 
--max_steps 100 
--lr_scheduler_type cosine 
--learning_rate 2e-4 
--warmup_ratio 0.05 
--weight_decay 0.01 
--logging_strategy steps 
--logging_steps 10 
--save_strategy steps 
--save_total_limit 3 
--save_steps 500 
--gradient_accumulation_steps 1 
--preprocessing_num_workers 8 
--block_size 512 
--output_dir test_pt_output 
--overwrite_output_dir 
--ddp_timeout 30000 
--logging_first_step True 
--lora_rank 8 
--lora_alpha 32 
--trainable "q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj" 
--lora_dropout 0.05 
--torch_dtype float16  
--ddp_find_unused_parameters False

2、根据手动合并文档Step 2步骤进行合并LoRA权重：
python merge_llama_with_chinese_lora.py 
--base_model original_llama_hf_7B 
--lora_model my_lora_model_7B 
--output_type pth 
--output_dir output_merge_lora_model_7B

3、参考llama.cpp量化部署文档进行模型启动。

在进行对话时，无论问什么，回答的内容都是语无伦次的内容，还请教是哪里出现了问题，再此先感谢作者。

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/62053536/b025bf43-470c-49a5-9831-9087371a5d81)

**Comment by tanghui315** [comment]
> 作者您好，我也出现了类似的问题，我想对某领域进行二次预训练，我操作的步骤如下(只操作过一次)： 1、使用run_clm_pt_with_peft.py脚本在单机单卡的环境下： torchrun --nnodes 1 --nproc_per_node 1 run_clm_pt_with_peft.py --deepspeed ds_zero2_no_offload.json --model_name_or_path test_output_7B # 使用merge_llama_with_chinese_lora对原版llama的hf文件与chinese_llama_lora_7b合并后结果 --tokenizer_name_or_path chinese_llama_lora_7b --dataset_dir dataset-txt --data_cache_dir data_cache --validation_split_percentage 0.001 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --do_train --seed $RANDOM --fp16 --max_steps 100 --lr_scheduler_type cosine --learning_rate 2e-4 --warmup_ratio 0.05 --weight_decay 0.01 --logging_strategy steps --logging_steps 10 --save_strategy steps --save_total_limit 3 --save_steps 500 --gradient_accumulation_steps 1 --preprocessing_num_workers 8 --block_size 512 --output_dir test_pt_output --overwrite_output_dir --ddp_timeout 30000 --logging_first_step True --lora_rank 8 --lora_alpha 32 --trainable "q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj" --lora_dropout 0.05 --torch_dtype float16 --ddp_find_unused_parameters False
> 
> 2、根据手动合并文档Step 2步骤进行合并LoRA权重： python merge_llama_with_chinese_lora.py --base_model original_llama_hf_7B --lora_model my_lora_model_7B --output_type pth --output_dir output_merge_lora_model_7B
> 
> 3、参考llama.cpp量化部署文档进行模型启动。
> 
> 在进行对话时，无论问什么，回答的内容都是语无伦次的内容，还请教是哪里出现了问题，再此先感谢作者。
> 
> ![image](https://user-images.githubusercontent.com/62053536/241873612-b025bf43-470c-49a5-9831-9087371a5d81.png)

你的eval_loss 和tarin_loss 是多少， 有下降吗？

**Comment by henryGao9** [comment]
> > 作者您好，我也出现了类似的问题，我想对某领域进行二次预训练，我操作的步骤如下(只操作过一次)： 1、使用run_clm_pt_with_peft.py脚本在单机单卡的环境下： torchrun --nnodes 1 --nproc_per_node 1 run_clm_pt_with_peft.py --deepspeed ds_zero2_no_offload.json --model_name_or_path test_output_7B # 使用merge_llama_with_chinese_lora对原版llama的hf文件与chinese_llama_lora_7b合并后结果 --tokenizer_name_or_path chinese_llama_lora_7b --dataset_dir dataset-txt --data_cache_dir data_cache --validation_split_percentage 0.001 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --do_train --seed $RANDOM --fp16 --max_steps 100 --lr_scheduler_type cosine --learning_rate 2e-4 --warmup_ratio 0.05 --weight_decay 0.01 --logging_strategy steps --logging_steps 10 --save_strategy steps --save_total_limit 3 --save_steps 500 --gradient_accumulation_steps 1 --preprocessing_num_workers 8 --block_size 512 --output_dir test_pt_output --overwrite_output_dir --ddp_timeout 30000 --logging_first_step True --lora_rank 8 --lora_alpha 32 --trainable "q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj" --lora_dropout 0.05 --torch_dtype float16 --ddp_find_unused_parameters False
> > 2、根据手动合并文档Step 2步骤进行合并LoRA权重： python merge_llama_with_chinese_lora.py --base_model original_llama_hf_7B --lora_model my_lora_model_7B --output_type pth --output_dir output_merge_lora_model_7B
> > 3、参考llama.cpp量化部署文档进行模型启动。
> > 在进行对话时，无论问什么，回答的内容都是语无伦次的内容，还请教是哪里出现了问题，再此先感谢作者。
> > ![image](https://user-images.githubusercontent.com/62053536/241873612-b025bf43-470c-49a5-9831-9087371a5d81.png)
> 
> 你的eval_loss 和tarin_loss 是多少， 有下降吗？

我都是按照文档操作进行一步一步学习，没有改变任何值(除修改本地dir路径外)，都是按照文档默认情况来的。

**Comment by tanghui315** [comment]
> > run_clm_pt_with_peft
> 
> 应该还是在执行run_clm_pt_with_peft预训练时出的问题，我看生成的pytorch_model.bin文件才40M，我再重新进行训练一下看看。

我训练出来有80M

**Comment by tanghui315** [comment]
> > > > run_clm_pt_with_peft
> > > 
> > > 
> > > 应该还是在执行run_clm_pt_with_peft预训练时出的问题，我看生成的pytorch_model.bin文件才40M，我再重新进行训练一下看看。
> > 
> > 
> > 我训练出来有80M
> 
> 我再次执行了一遍预训练，我txt文件有76M的大小，但我预训练的速度很快，几分钟就执行完成了，而且也没有看到任何的报错。 ![image](https://user-images.githubusercontent.com/62053536/241884804-284a7990-1b0f-41de-9874-2c85aa52085f.png)
> 
> 完全不清楚是哪里出了问题

max_steps 按照官方的来的话 100 ，非常小，训练一轮都不够。  设置大一点试试。或者不设置 max_steps , 用  num_train_epochs 代替， num_train_epochs 代表训练的轮数， 跑个10轮再试试。

**Comment by henryGao9** [comment]
> > > > > run_clm_pt_with_peft
> > > > 
> > > > 
> > > > 应该还是在执行run_clm_pt_with_peft预训练时出的问题，我看生成的pytorch_model.bin文件才40M，我再重新进行训练一下看看。
> > > 
> > > 
> > > 我训练出来有80M
> > 
> > 
> > 我再次执行了一遍预训练，我txt文件有76M的大小，但我预训练的速度很快，几分钟就执行完成了，而且也没有看到任何的报错。 ![image](https://user-images.githubusercontent.com/62053536/241884804-284a7990-1b0f-41de-9874-2c85aa52085f.png)
> > 完全不清楚是哪里出了问题
> 
> max_steps 按照官方的来的话 100 ，非常小，训练一轮都不够。 设置大一点试试。或者不设置 max_steps , 用 num_train_epochs 代替， num_train_epochs 代表训练的轮数， 跑个10轮再试试。

好的好的，非常感谢您，我也是在学习阶段，很多东西不太懂，感谢您回复我的问题，我再尝试一下。

**Comment by iMountTai** [comment]
@henryGao9 二次预训练后，合并权重应该是在**`test_output_7B`** 的基础上合并**`my_lora_model_7B`**

**Comment by henryGao9** [comment]
> @henryGao9 二次预训练后，合并权重应该是在**test_output_7B**的基础上合并**my_lora_model_7B**

感谢您，我继续尝试一下，看看问题是不是出在您二位指出的地方

**Comment by ai499** [comment]
大佬  我编译安装peft遇到了一个报错  make的时候 make: black: 没有那个文件或目录 我已经pip安装了 black和ruff 这个是什么情况 谢谢大佬

**Comment by tanghui315** [comment]
> 大佬 我编译安装peft遇到了一个报错 make的时候 make: black: 没有那个文件或目录 我已经pip安装了 black和ruff 这个是什么情况 谢谢大佬

建议你重新开一个窗口问， 而且信息量不够， 贴点日志出来，不然不好判断。

**Comment by ai499** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/33976178/553a8b85-7020-4103-8f23-da0e2b7946c0)

**Comment by tanghui315** [comment]
> @tanghui315 系统是ubuntu20 ![image](https://user-images.githubusercontent.com/33976178/242499628-1e405396-014f-4789-b0d1-83f7b50e0d3e.png)

为啥你要编译安装 peft ， 虽然文档说指定了某一个版本。 但我用最新的 版本，也没啥问题。可能存在部分的训练参数问题，但我没也用到。

**Comment by ai499** [comment]
@tanghui315 好的 谢谢大佬

**Comment by sarahyongq** [comment]
> 在什么模型上训的？
麻烦问问，run_clm_pt_with_peft.py跑起来会有
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

None of the inputs have requires_grad=True. Gradients will be None
，但是没看到给出的代码里超参有设置冻结了训练呢？是哪里有没注意到或者需要修改的地方吗？
> run_clm_pt_with_peft.py

**Comment by sarahyongq** [comment]
> > 大佬 我编译安装peft遇到了一个报错 make的时候 make: black: 没有那个文件或目录 我已经pip安装了 black和ruff 这个是什么情况 谢谢大佬
> 
> 建议你重新开一个窗口问， 而且信息量不够， 贴点日志出来，不然不好判断。

老哥，看你训练成功了，能忙我看看这个问题不？https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/547

**Comment by LiuChen19960902** [comment]
作者你好，我也是出现了灾难性遗忘的问题。
我是先把chinese-llama-plus-7b合并到elinas/llama-7b-hf-transformers-4.29得到了一个完整版的chinese-llama-7b
然后在这个完整版chinese-llama-7b的基础上开始二次预训练，预训练脚本也是直接用的run_clm_pt_with_peft.py。
我的loss下降到1.4~1.5之间就不再下降。然后我去做测试时候发现和您的问题一样，基本上只能回答垂域的问题，甚至是我问他你是谁，他都是回答的是垂域的答案，而且和“你是谁”完全不相关。

不知道您是否解决了这个问题，想和您交流一下这个问题。期待您的回复。十分感谢
