### ISSUE TITLE
基于LLAMA基础模型，预训练adapter_config怎么产生？

### ISSUE THREAD

**Issue by richardkelly2014** [ymcui/Chinese-LLaMA-Alpaca#451]
*提示：将[ ]中填入x，表示打对钩。提问时删除这行。只保留符合的选项。*

### 详细描述问题

1. 基础模型是llama-7b。
2.  tokenizer 是通过 merge_tokenizers (基础模型+中文sp）
3. 通过预训练脚本训练，训练出目录下
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/14330290/59c807b4-f6ff-4ce1-b6db-e5ff9f1e11cf)
4. [wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E9%A2%84%E8%AE%AD%E7%BB%83%E8%84%9A%E6%9C%AC#%E8%AE%AD%E7%BB%83%E5%90%8E%E6%96%87%E4%BB%B6%E6%95%B4%E7%90%86) 这里训练后文件整理，adapter_config 这个从哪里生成？

### 运行截图或日志

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/14330290/b141991c-1f26-488f-a514-4ea368e5f15e)

### 必查项目（前三项只保留你要问的）

- [x ] **基础模型**：LLaMA / Alpaca / LLaMA-Plus / Alpaca-Plus
- [ ] **运行系统**：Windows / MacOS / Linux 
- [ ] **问题分类**：下载问题 / 模型转换和合并 / 模型训练与精调 / 模型推理问题（🤗 transformers） / 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat） / 效果问题 / 其他问题
- [x ] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by ymcui** [comment]
如果你完全没有使用我们的LoRA，那你就自己去下载adapter_config.json配置文件，**并且按照自己实际训练的配置修改保存**：
- llama: https://huggingface.co/ziqingyang/chinese-llama-lora-7b
- alpaca: https://huggingface.co/ziqingyang/chinese-alpaca-lora-7b

**Comment by richardkelly2014** [comment]
> 

你指的是modules_to_save 这个参数吗？

**Comment by richardkelly2014** [comment]
tokenizer 可以用训练后的吗？

**Comment by ymcui** [comment]
> 你指的是modules_to_save 这个参数吗？

https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/预训练脚本#训练后文件整理  第五步有写，麻烦自行仔细看一下。

> tokenizer 可以用训练后的吗？

自己diff一下训练后的和之前（merge_tokenizers处理的）的文件是否一致。
