### ISSUE TITLE
帮忙看个问题，预训练之后精准训练报错

### ISSUE THREAD

**Issue by richardkelly2014** [ymcui/Chinese-LLaMA-Alpaca#453]
### 详细描述问题

1. 在预训练脚本执行完毕之后，目录下面
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/14330290/fbb4f3d2-7a40-490b-a5cd-c705519604e6)
生成了对应的adapter文件。和token信息
预训练参数
```
--model_name_or_path /root/llama/hf_model 
--tokenizer_name_or_path /root/llama/chinese_tokenizer 
--dataset_dir /root/llama/data/pt 
--data_cache_dir /root/llama/data_cache 
--validation_split_percentage 0.001 
--per_device_train_batch_size 1 
--do_train --fp16 --max_steps 100 
--lr_scheduler_type cosine 
--learning_rate 2e-4 --warmup_ratio 0.05 --weight_decay 0.01 
--logging_strategy steps --logging_steps 10 
--save_strategy steps --save_total_limit 3 --save_steps 50 
--gradient_accumulation_steps 1 --preprocessing_num_workers 8 
--block_size 512 --output_dir /root/llama/train_out 
--overwrite_output_dir --ddp_timeout 30000 --logging_first_step True --lora_rank 8 
--lora_alpha 32 --trainable q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj 
--modules_to_save embed_tokens,lm_head --lora_dropout 0.05 
--torch_dtype float16 
--gradient_checkpointing 
--ddp_find_unused_parameters False 
```

2.下一步执行 ft 脚本的时，报了个错误
这是脚本参数
```
--model_name_or_path /root/llama/hf_model 
--tokenizer_name_or_path /root/llama/train_out 
--dataset_dir /root/llama/data/ft 
--data_cache_dir /root/llama/data_cache 
--validation_split_percentage 0.001 
--per_device_train_batch_size 1 
--do_train  
--fp16 
--max_steps 100  
--lr_scheduler_type cosine  
--learning_rate 1e-4  
--warmup_ratio 0.03  
--weight_decay 0 
--logging_strategy steps 
--logging_steps 10 
--save_strategy steps  
--save_total_limit 3 
--save_steps 50 
--gradient_accumulation_steps 1 
--preprocessing_num_workers 8 
--max_seq_length 512  
--output_dir /root/llama/train_out_1 
--overwrite_output_dir 
--ddp_timeout 30000 
--logging_first_step True 
--torch_dtype float16 
--peft_path /root/llama/train_out/lora 
--gradient_checkpointing  
--ddp_find_unused_parameters False
```

### 运行截图或日志

*请提供文本log或者运行截图，以便我们更好地了解问题详情。*

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/14330290/95950a47-f304-49f1-ae08-07658141e43f)

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/14330290/8c76a9d3-51de-4434-ba1f-7029cb2a4e61)

### 必查项目（前三项只保留你要问的）

- [x] **基础模型**：LLaMA / Alpaca / LLaMA-Plus / Alpaca-Plus
- [ ] **运行系统**：Windows / MacOS / Linux 
- [ ] **问题分类**：下载问题 / 模型转换和合并 / 模型训练与精调 / 模型推理问题（🤗 transformers） / 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat） / 效果问题 / 其他问题
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by yyqi17** [comment]
预训练之后得到的special_tokens_map.json里面有[PAD]吗？

**Comment by airaria** [comment]
不是报错，正常的消息提示，不用担心。
如果实在不放心，从chinese-alpaca-lora-7b中复制所有tokenizer相关文件\*token\* 到你的/root/llama/train_out 文件夹下替换原有tokenizer

**Comment by airaria** [comment]
> 预训练之后得到的special_tokens_map.json里面有[PAD]吗？

没有

**Comment by airaria** [comment]
@richardkelly2014 你是在llama-lora的基础上训练alpaca?
目前发布的脚本里没有可以直接设置的相关选项开关，你可以手动将349-351行的代码移至375行

**Comment by richardkelly2014** [comment]
> @richardkelly2014 你是在llama-lora的基础上训练alpaca? 目前发布的脚本里没有可以直接设置的相关选项开关，你可以手动将`run_clm_sft_with_peft.py`中349-351行的代码移至375行

嗯。在在llama 基础模型上训练的。我试试你说的方案。

**Comment by richardkelly2014** [comment]
@airaria  
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/14330290/8eaa93cf-f728-4796-a57a-ad0c6cc3d516)
位置调整后，异常信息和之前差不多

**Comment by airaria** [comment]
将原349-351行的代码还是移至375行后，请在原本349-351行的地方添加:
```python
model.resize_token_embeddings(49953)
```

**Comment by richardkelly2014** [comment]
> 你做sft是基于llama的lora继续训练的对吧？
> 那合并时是要合并一个就可以了（llama + sft的lora)

嗯，sft 的peft_path 是预训练的lora目录
