### ISSUE TITLE
加入modules_to_save embed_tokens,lm_head进行指令微调之后，合并出错

### ISSUE THREAD

**Issue by huangxd-** [ymcui/Chinese-LLaMA-Alpaca#454]
报错日志：
```shell
Base model: /home/hxd/vicuna/Chinese-LLaMA-Alpaca/scripts/final_output
LoRA model(s) ['/home/hxd/vicuna/Chinese-LLaMA-Alpaca/scripts/lora_model']:
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.96s/it]
Peft version: 0.3.0.dev0
Loading LoRA for 7B model
Loading LoRA /home/hxd/vicuna/Chinese-LLaMA-Alpaca/scripts/lora_model...
base_model vocab size: 49954
tokenizer vocab size: 49954
Loading LoRA weights
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/hxd/vicuna/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py:281 in <module>   │
│                                                                                                  │
│   278 │   │   │   │   filename = hf_hub_download(repo_id=lora_model_path,filename='adapter_mod   │
│   279 │   │   │   │   lora_model_sd = torch.load(filename,map_location='cpu')                    │
│   280 │   │   │   if 'base_model.model.model.embed_tokens.weight' in lora_model_sd:              │
│ ❱ 281 │   │   │   │   assert lora_model_sd['base_model.model.model.embed_tokens.weight'].shape   │
│   282 │   │   │   │   ("The vocab size of the tokenizer does not match the vocab size of the L   │
│   283 │   │   │   │   "Did you misuse the LLaMA tokenizer with the Alpaca-LoRA weight?\n"        │
│   284 │   │   │   │   "Make sure that you use LLaMA tokenizer with the LLaMA-LoRA weight and A   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: The vocab size of the tokenizer does not match the vocab size of the LoRA weight. 
Did you misuse the LLaMA tokenizer with the Alpaca-LoRA weight?
Make sure that you use LLaMA tokenizer with the LLaMA-LoRA weight and Alpaca tokenizer with the Alpaca-LoRA weight!
```

执行步骤：
1. 下载chinese-llama-plus-lora-7b和chinese-alpaca-plus-lora-7b合并生成llama-7b-chinese-alpaca-plus
2. 根据llama-7b-chinese-alpaca-plus进行deepspeed zero3二次预训练，没有加参数modules_to_save embed_tokens,lm_head，合并生成final_output
```shell
mkdir lora_model
cp output_dir/adapter_model/* lora_model/
cp /home/hxd/vicuna/llama-7b-chinese-alpaca-plus/*token* lora_model/
python merge_llama_with_chinese_lora.py     --base_model /home/hxd/vicuna/llama-7b-chinese-alpaca-plus     --lora_model /home/hxd/vicuna/Chinese-LLaMA-Alpaca/scripts/lora_model     --output_type huggingface     --output_dir final_output
```
3. 根据final_output进行deepspeed zero3指令微调，加入参数modules_to_save embed_tokens,lm_head，合并出错，报错日志看开头
```shell
mkdir lora_model
cp output_dir/adapter_model/* lora_model/
cp /home/hxd/vicuna/Chinese-LLaMA-Alpaca/scripts/final_output/*token* lora_model/
python merge_llama_with_chinese_lora.py     --base_model /home/hxd/vicuna/Chinese-LLaMA-Alpaca/scripts/final_output     --lora_model /home/hxd/vicuna/Chinese-LLaMA-Alpaca/scripts/lora_model     --output_type huggingface     --output_dir final_output_instuction
```
不合并加载lora进行推理也出错
```shell
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
        size mismatch for base_model.model.model.embed_tokens.modules_to_save.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([49954, 4096]).
        size mismatch for base_model.model.lm_head.modules_to_save.default.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([49954, 4096]).
```

请问，是因为预训练没有加modules_to_save而指令微调加了modules_to_save的问题导致的吗？如果指令微调不加modules_to_save是不会报错的，一切正常

**Comment by airaria** [comment]
你的`adapter_config.json`里的modules_to_save的值是否为空？

**Comment by huangxd-** [comment]
> 你的`adapter_config.json`里的modules_to_save的值是否为空？

不为空
```shell
{
  "base_model_name_or_path": "/home/hxd/vicuna/Chinese-LLaMA-Alpaca/scripts/final_output",
  "bias": "none",
  "enable_lora": null,
  "fan_in_fan_out": false,
  "inference_mode": true,
  "lora_alpha": 32.0,
  "lora_dropout": 0.05,
  "merge_weights": false,
  "modules_to_save": [
    "embed_tokens",
    "lm_head"
  ],
  "peft_type": "LORA",
  "r": 8,
  "target_modules": [
    "q_proj",
    "v_proj",
    "k_proj",
    "o_proj",
    "gate_proj",
    "down_proj",
    "up_proj"
  ],
  "task_type": "CAUSAL_LM"
}
```

**Comment by airaria** [comment]
> > 你的`adapter_config.json`里的modules_to_save的值是否为空？
> 
> 不为空
> 
> ```shell
> {
>   "base_model_name_or_path": "/home/hxd/vicuna/Chinese-LLaMA-Alpaca/scripts/final_output",
>   "bias": "none",
>   "enable_lora": null,
>   "fan_in_fan_out": false,
>   "inference_mode": true,
>   "lora_alpha": 32.0,
>   "lora_dropout": 0.05,
>   "merge_weights": false,
>   "modules_to_save": [
>     "embed_tokens",
>     "lm_head"
>   ],
>   "peft_type": "LORA",
>   "r": 8,
>   "target_modules": [
>     "q_proj",
>     "v_proj",
>     "k_proj",
>     "o_proj",
>     "gate_proj",
>     "down_proj",
>     "up_proj"
>   ],
>   "task_type": "CAUSAL_LM"
> }
> ```

但实际没有训练也没有存embed_tokens和lm_head啊😂
adapter_config里把embed_tokens和lm_head这两个删掉再合并吧

**Comment by huangxd-** [comment]
> > > 你的`adapter_config.json`里的modules_to_save的值是否为空？
> > 
> > 
> > 不为空
> > ```shell
> > {
> >   "base_model_name_or_path": "/home/hxd/vicuna/Chinese-LLaMA-Alpaca/scripts/final_output",
> >   "bias": "none",
> >   "enable_lora": null,
> >   "fan_in_fan_out": false,
> >   "inference_mode": true,
> >   "lora_alpha": 32.0,
> >   "lora_dropout": 0.05,
> >   "merge_weights": false,
> >   "modules_to_save": [
> >     "embed_tokens",
> >     "lm_head"
> >   ],
> >   "peft_type": "LORA",
> >   "r": 8,
> >   "target_modules": [
> >     "q_proj",
> >     "v_proj",
> >     "k_proj",
> >     "o_proj",
> >     "gate_proj",
> >     "down_proj",
> >     "up_proj"
> >   ],
> >   "task_type": "CAUSAL_LM"
> > }
> > ```
> 
> 但实际没有训练也没有存embed_tokens和lm_head啊😂 adapter_config里把embed_tokens和lm_head这两个删掉再合并吧

指令微调的时候加了modules_to_save embed_tokens,lm_head也不会训练和保存embed_tokens和lm_head吗？只在二次预训练的时候有效？

**Comment by airaria** [comment]
从报错信息看，第三步存下来的lora权重里似乎没有lm_head?
你load一下看看，大概是这样
```python
import torch
sd = torch.load('/home/hxd/vicuna/Chinese-LLaMA-Alpaca/scripts/lora_model/adapter_model.bin',map_location='cpu')
for k,v in sd.items():
    if 'embed_tokens' in k:
        print(v.shape)
```

**Comment by huangxd-** [comment]
> ```python
> import torch
> sd = torch.load('/home/hxd/vicuna/Chinese-LLaMA-Alpaca/scripts/lora_model/adapter_model.bin',map_location='cpu')
> for k,v in sd.items():
>     if 'embed_tokens' in k:
>         print(v.shape)
> ```

输出是
torch.Size([0])

**Comment by iMountTai** [comment]
不排除是peft版本的问题，你的peft版本既不是我们推荐的版本，也不是最新版本。我们的训练代码和peft版本是强绑定的，其他版本不能保证正常运行并正确保存权重
