### ISSUE TITLE
若出现过拟合现象，如何通过减少训练参数量来减缓？

### ISSUE THREAD

**Issue by Antiman-cmyk** [ymcui/Chinese-LLaMA-Alpaca#455]
我用的是自己构造的数据集，在预训练之后的llama做instruction tuning，大概做了3k条训练集，训1000steps（=5.32epochs），最后loss只有0.03左右，想请教一下
1. 3k的数据量是否合理，是否一定得提到 M 级别的数据量
2. loss太低，怀疑是过拟合了，如果想通过减少tune的参数量来缓解，脚本中提到的module_to_save与trainable 两个参量哪些可以或者说更适合去除呢？

**Comment by airaria** [comment]
0.03的loss的确有点低得离谱了，学习率多少？尝试降低学习率；
另外在几千条数据下也可以尝试不训练embed_tokens和lm_head，即modules_to_save为None

**Comment by Antiman-cmyk** [comment]
学习率跟着模板设的1e-4。两个我都试试。

**Comment by coddderX** [comment]
@Antiman-cmyk 有进展了麻烦同步一下，我也担忧过拟合问题

**Comment by huruizhi** [comment]
1000steps  降低到500 试一下
