### ISSUE TITLE
modules_to_save 导致lora保存体积巨大

### ISSUE THREAD

**Issue by lucasjinreal** [ymcui/Chinese-LLaMA-Alpaca#456]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/21303438/3b8cc212-090e-402f-9d7d-631fe2917826)

我用另外一个库保存的lora只有17M，这些额外的modules_to_save 是否有必要？​

**Comment by ymcui** [comment]
保存了embedding和lm_head，这个大小没什么奇怪的。
如果你不需要训这两个就不用modules_to_save这个参数了。

**Comment by lucasjinreal** [comment]
@ymcui 我理解的是，既然有元模型了，这两个参数似乎有点多余，为啥不去掉呢

**Comment by ymcui** [comment]
你可以手动去掉啊😅，示例代码只是示例，并没有说一定要继续训练这两个矩阵。
Wiki里已经做过相应提示：https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/预训练脚本#节省显存小提示

**Comment by lucasjinreal** [comment]
我理解是貌似 embed_tokens,lm_head 也没有加入到 trainable里面去，加上modules_to_save 有点多余。加上modules_to_save 会训练 embed_tokens,lm_head  吗》？

**Comment by airaria** [comment]
> 我理解是貌似 embed_tokens,lm_head 也没有加入到 trainable里面去，加上modules_to_save 有点多余。加上modules_to_save 会训练 embed_tokens,lm_head 吗》？

modules_to_save里的参数会参与训练。

**Comment by lucasjinreal** [comment]
没有错，是我搞错了。

**Comment by 191220042** [comment]
您好，请问下
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/80091648/a7b2c21e-5fd3-446b-922a-5512cb5c83e0)
我发现ora训练仅仅只是把原有的数据复制了一份并没有实际训练，就是modules_to_save和原来的weight相同
