### ISSUE TITLE
运行run_clm_pt_with_peft.py中的分词命令

### ISSUE THREAD

**Issue by Excalibur4869** [ymcui/Chinese-LLaMA-Alpaca#459]
### 详细描述问题

运行run_clm_pt_with_peft.py中的分词命令处理自己的txt文件后得到很多json和arrow文件，请问哪个文件是处理后的分词文件，又该如何编译回文本形式呢

### 运行截图或日志

![1](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/93848656/45ce9a57-a234-4609-bb1d-fccc7365b242)
![2](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/93848656/6d94c275-3513-4514-8964-c6331a4f48b3)

### 必查项目（前三项只保留你要问的）

- [ ] **基础模型**：LLaMA / Alpaca / LLaMA-Plus / Alpaca-Plus
- [ ] **运行系统**：Windows / MacOS / Linux 
- [ ] **问题分类**：下载问题 / 模型转换和合并 / 模型训练与精调 / 模型推理问题（🤗 transformers） / 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat） / 效果问题 / 其他问题
- [ ] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by airaria** [comment]
这些文件建议用datasets读取，
[                processed_dataset = datasets.load_from_disk(cache_path, keep_in_memory=False)](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/642d5622bdc7fc20c99bc270bf32f06e9361bb89/scripts/run_clm_pt_with_peft.py#LL461C7-L461C7)

**Comment by Excalibur4869** [comment]
> 

这个不是只能读取到features和num_rows信息吗，如果我想看到分词后的文本信息并且想要编译回文本，该读取哪个文件呢？

**Comment by iMountTai** [comment]
load_dataset和load_from_disk本质上没有区别，只是一个是加载了原始数据集，一个加载的是tokenizer后的数据集，读取features后就可以用tokenizer在token和token_id之间转换了，可以参考tokenizer的代码实现及huggingface datasets文档
