### ISSUE TITLE
请问该模型推理时使用的是CPU还是GPU？

### ISSUE THREAD

**Issue by tangpingzhou** [ymcui/Chinese-LLaMA-Alpaca#46]
使用默认的./main中的程序运行，过程中发现GPU没有工作（包括核心和vram都没有工作），但是生成速度已然很快，虽然我在环境中配置了cuda，但是显然并没有调用，请问如何启用cuda参与推理？

**Comment by ymcui** [comment]
llama.cpp的目的就是用CPU运行量化模型，如果是GPU的话实际上直接用huggingface的接口就好。

**Comment by xiaoSUM** [comment]
> 欧我的老天，这真的很惊人！之前我使用[text-generation-webui](https://github.com/oobabooga/text-generation-webui)体验了LLaMA 7B-4bit，速度已然是很惊人了，但是GPU在疯狂工作！非常期待您关于13B模型的训练！也非常希望能看到他的web UI界面。

我按照 https://github.com/oobabooga/text-generation-webui.wiki.git报models/llamacpp-7b/ggml-model-q4_0.bin: invalid model file (bad magic [got 0x67676d66 want 0x67676a74])的错，你是怎么跑通的呀？
