### ISSUE TITLE
训练参数

### ISSUE THREAD

**Issue by richardkelly2014** [ymcui/Chinese-LLaMA-Alpaca#462]
*提示：将[ ]中填入x，表示打对钩。提问时删除这行。只保留符合的选项。*

### 详细描述问题

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/14330290/e0590652-4a23-40b9-86d0-6b79b0e9f175)
请教一下这些对应的参数是哪些？

### 运行截图或日志

*请提供文本log或者运行截图，以便我们更好地了解问题详情。*

### 必查项目（前三项只保留你要问的）

- [ ] **基础模型**：LLaMA / Alpaca / LLaMA-Plus / Alpaca-Plus
- [ ] **运行系统**：Windows / MacOS / Linux 
- [ ] **问题分类**：下载问题 / 模型转换和合并 / 模型训练与精调 / 模型推理问题（🤗 transformers） / 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat） / 效果问题 / 其他问题
- [ ] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by ymcui** [comment]
最老那一版的7B模型，具体见技术报告。

**Comment by richardkelly2014** [comment]
> 最老那一版的7B模型，具体见技术报告。

实在不好意思，具体地址有吗？在wiki里没找到

**Comment by ymcui** [comment]
> https://github.com/ymcui/Chinese-LLaMA-Alpaca#引用 

报告：https://arxiv.org/abs/2304.08177

**Comment by ymcui** [comment]
你自己对应一下吧，都是很常见超参。
另外，除非你是要从头开始训，否则表里的超参对你也没什么参考价值，和你用的训练设备数量等都要匹配才行。

**Comment by richardkelly2014** [comment]
感谢大佬
