### ISSUE TITLE
inference_hf.py 遇到输出无法停止的问题

### ISSUE THREAD

**Issue by lockmatrix** [ymcui/Chinese-LLaMA-Alpaca#463]
### 详细描述问题

*请尽量具体地描述您遇到的问题，**必要时给出运行命令**。这将有助于我们更快速地定位问题所在。*

使用 `scripts/inference_hf.py` 进行推理时遇到回答后无法停止，继续产生token直到上限的问题。
过程中提示 
```
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
```
在代码中改成了 `pad_token_id=tokenizer.eos_token_id` 后没有上述wanring，但仍然有无法停止的问题。

模型用的 https://huggingface.co/shibing624/chinese-llama-plus-13b-hf 合并的版本

想知道这是目前模型的效果，还是这个 `inference_hf.py` 哪里有问题导致的？

### 运行截图或日志

*请提供文本log或者运行截图，以便我们更好地了解问题详情。*

![1685444986431](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/1844843/46133b87-ce09-4fe1-a396-857201feef0f)

### 必查项目（前三项只保留你要问的）

- [x] **基础模型**：LLaMA-Plus
- [x] **运行系统**：Linux 
- [x] **问题分类**：模型推理问题 / 效果问题 
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by lockmatrix** [comment]
同样的模型，在 text-generation-webui chat中也都有回答无法停止的问题。

**Comment by lockmatrix** [comment]
换成了 https://huggingface.co/P01son/Linly-Chinese-LLaMA-7b-hf ，能够看到正常停止了。
目前还不清楚是13B模型的问题，还是我上面使用的那个merge的版本的问题。

**Comment by lockmatrix** [comment]
> 从例子里看，是要做指令理解（问答、写作、建议等）等任务，应该更换为chinese-alpaca，而不是chinese-llama。chinese-llama不适合做问答任务。

感谢，后面会去测 chinese-alpaca 的

**Comment by 13269279918** [comment]
我也遇到了相同的问题，在排查的时候发现tokenizer只会给句子添加<S>，而不会给句子添加</S>。不知道和这个有没有关系
