### ISSUE TITLE
关于modules_to_save和训练参数量

### ISSUE THREAD

**Issue by xiaohuoguohh** [ymcui/Chinese-LLaMA-Alpaca#466]
peft参数设置了 modules_to_save="embed_tokens,lm_head"
然后我打印了requires_grad的参数除了rola参数以为还会有一下参数参与训练更新：
base_model.model.model.embed_tokens.original_module.weight:204607488
base_model.model.model.embed_tokens.modules_to_save.default.weight:204607488
。。。
base_model.model.lm_head.original_module.weight:204607488
base_model.model.lm_head.modules_to_save.default.weight:204607488

请问original_module.weight和modules_to_save.default.weight有什么区别呢，导致model.print_trainable_parameters()看到的trainable的参数量和你们的报告不一致，参数量翻倍了

**Comment by ymcui** [comment]
你用的是我们推荐的peft版本吗？

**Comment by xiaohuoguohh** [comment]
> 

是版本问题，解决了
