### ISSUE TITLE
多轮对话结尾出现很多句号

### ISSUE THREAD

**Issue by Mewral** [ymcui/Chinese-LLaMA-Alpaca#469]
### 详细描述问题
使用chinese-alpaca-plus进行多轮对话，超过一定轮后模型回答结尾会有很多句号

### 运行截图或日志

```commandline
question: 中国的首都是哪里
answer: 中国的首都是北京。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
```

### 必查项目（前三项只保留你要问的）

- [x] **基础模型**：LLaMA / Alpaca / LLaMA-Plus / Alpaca-Plus
- [ ] **运行系统**：Windows / MacOS / Linux 
- [ ] **问题分类**：下载问题 / 模型转换和合并 / 模型训练与精调 / 模型推理问题（🤗 transformers） / 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat） / 效果问题 / 其他问题
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by airaria** [comment]
"超过一定轮后"那是多少轮？对话历史大概多长？因为我们只用了512的输入长度在中文上训练模型，如果上下文太长，模型的性能可能下降。

**Comment by Mewral** [comment]
这是我今天测试的。没有超过512
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/29936932/189fc63e-89d3-4732-a43a-086b7fab9888)

**Comment by ymcui** [comment]
建议检查SHA256，确保模型正确。从你的截图看回复不正常，大概率是模型本身有问题。

SHA256：https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md
