### ISSUE TITLE
Step 1: 将原版LLaMA模型转换为HF格式 时出现的问题。

### ISSUE THREAD

**Issue by xjDUAN184** [ymcui/Chinese-LLaMA-Alpaca#471]
我下载的llama模型有两种，一种是chinese_llama_lora_13b，检测SHA256值是正确的。一种是在网上下载的模型，检测SHA256值不正确。报错如下：

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/05fa015b-c796-40e3-98c2-6daa2e9c9893)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/6ce104de-a6e3-4079-aeda-aaddb8ee728e)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/0bbbc1d7-1c6c-4c1f-8ca8-f697ca629d67)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/14e52f01-a340-4d6e-96f9-6f1a43f617c1)

**Comment by xjDUAN184** [comment]
到底在哪里能下载原版模型啊？我的中文llama模型是在这里下载的：
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/4b5b5089-4543-4163-b593-2c9a382170dd)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/f082f1f8-feb5-4e4e-a691-99fe26c6fd1e)
原版模型只能去他的guanwang官网申请吗，申请了但是没给我回复。

**Comment by ymcui** [comment]
huggingface上有，麻烦自己找一下吧，没法明说。另外上面说的模型不是pth格式的，是huggingface的bin格式，所以不需要pth转hf格式的步骤。
