### ISSUE TITLE
关于预训练数据集的问题

### ISSUE THREAD

**Issue by Halflifefa** [ymcui/Chinese-LLaMA-Alpaca#472]
请问数据集中包含表格是如何处理的,仅是csv格式的表格适合模型学习吗?我注意到中文wiki的数据集是去除了表格的,但我想保留表格里面的重要信息.

**Comment by ymcui** [comment]
如果你要训练表格数据的话，可以仿照markdown的形式处理（类似chatgpt）。以上只是参考建议，我们并未尝试过。

**Comment by tkone2018** [comment]
@Halflifefa 你好，请问你找到了预训练表格的数据处理方案了吗，我也想训练表格内容，谢谢

**Comment by Halflifefa** [comment]
@tkone2018 我们目前也还在探索
