### ISSUE TITLE
请问预训练finetune的时候，训练速度很慢该如何解决？

### ISSUE THREAD

**Issue by sixgold993** [ymcui/Chinese-LLaMA-Alpaca#473]
<img width="414" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/38970047/492a85f8-7a9e-4a47-9a86-d33bbee14ccf">

目前用的是8张V100 并行， 参数设置的block=512， per_device_batch = 16 迭代速度是10多s每次iter非常慢。想问下可能是什么原因。

想问大佬们，如果我的数据是100w条。 训练一个epoch 我应该怎么计算training_steps？

**Comment by sixgold993** [comment]
> 

我用的是7B的，20G中文finetune的模型。我这里是600w的数据，train_batch_size_per_device = 16 ， total_gpus = 8
需要5w个step。时间需要6天。感觉好慢呀。 主要就是想确认下是否有问题。 没问题的话就的考虑一下输入的数据是不是太大了，做一个删减。

**Comment by sixgold993** [comment]
大佬问题想请教下，block_size 我变小了，速度好像也没变快。 我理解block_size调小 不是应该变快嘛？

**Comment by iMountTai** [comment]
> 大佬问题想请教下，block_size 我变小了，速度好像也没变快。 我理解block_size调小 不是应该变快嘛？

那有没有可能加载的是512的cache
