### ISSUE TITLE
Tokenizer在编码时，会加上空字符的token 29871

### ISSUE THREAD

**Issue by chenhk-chn** [ymcui/Chinese-LLaMA-Alpaca#475]
### 详细描述问题
我在使用tokenizer的时候发现如下令人迷惑的点。
```
from transformers import LlamaTokenizer
tokenizer = LlamaTokenizer.from_pretrained('models/chinese-llama-7b/')

>>> tokenizer.encode('\n', add_special_tokens=False)
[29871, 13]
>>> tokenizer.decode([13])
'\n'
>>> tokenizer.decode([29871])
''
>>> tokenizer.decode([29871, 13])
'\n'
>>> tokenizer.decode([29871, 13]) == tokenizer.decode([13])
True

>>> tokenizer.encode('哈哈哈', add_special_tokens=False)                         
[29871, 37296]
>>> tokenizer.encode('嘿嘿嘿', add_special_tokens=False)
[29871, 45040, 46816]
```
这里tokenizer会在回车符前加一个空字符的token`29871`，但是实际解码中，单token`13`也能解码出回车符。
另外对于直接输入中文，也经常会无意义地加一个`29871`，所以感到很困惑，为什么要加一个`29871`的token

```
>>> tokenizer.encode('\n ', add_special_tokens=False)
[29871, 13, 29871]
```
另外是如果是回车+空格的组合，会编码出`[29871, 13, 29871]`这样的组合，实际单独做解码，`[13, 29871]`就可以解码出回车+空格。
总之，是一个很令人困惑的点，想问问这个有什么说法吗？

### 必查项目（前三项只保留你要问的）

- [x] **基础模型**：LLaMA
- [x] **运行系统**：Linux 
- [x] **问题分类**：其他问题
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by airaria** [comment]
> 但是似乎并非所有句首都会出现？还是说这里的词和句的概念只针对英文？

字符串第一个token，或者前面一个字符是空格，被定义为句首或词首

**Comment by chenhk-chn** [comment]
```
>>> tokenizer.tokenize('你好')
['▁你好']
>>> tokenizer.encode('你好', add_special_tokens=False)
[42390]
```
那在这个情况下，`你好`前面为什么不加`29871`呢。

```
>>> tokenizer.tokenize(' 你好')
['▁', '▁你好']
>>> tokenizer.encode(' 你好', add_special_tokens=False)
[29871, 42390]
```
如果在`你好`前面加一个空格，确实出现了29871

**Comment by chenhk-chn** [comment]
我明白了。如果词表内已经有相关的词首的词，则直接解码即可。如果没有，则加一个`29871`代表这个词是词首。
```
>>> tokenizer.tokenize('hehe')
['▁he', 'he']
>>> tokenizer.encode('hehe', add_special_tokens=False)
[540, 354]
```
在`你好`这个例子中，tokenize出来的token本身就带有词首符。因此不需要额外的29871
```
>>> tokenizer.tokenize('你好你好')                                               
['▁你好', '你', '好']
>>> tokenizer.tokenize('你好')
['▁你好']
>>> tokenizer.encode('你好你好', add_special_tokens=False)
[42390, 30919, 31076]
>>> tokenizer.encode('你好', add_special_tokens=False)                           
[42390]
```
