### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by lijain** [ymcui/Chinese-LLaMA-Alpaca#476]
感谢你们的分享，可以对训练数据这块的构成详细说下？

**Comment by iMountTai** [comment]
参考[训练细节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E8%AE%AD%E7%BB%83%E7%BB%86%E8%8A%82)

**Comment by windy8856** [comment]
请问-f 指定prompt模板，提示“main: error: prompt is too long (8538 tokens, max 2044)”，怎么解决上限这个问题呢
