### ISSUE TITLE
运行gradio demo 聊天内容有格式符号

### ISSUE THREAD

**Issue by Peter-L-FANG** [ymcui/Chinese-LLaMA-Alpaca#477]
*请尽量具体地描述您遇到的问题，**必要时给出运行命令**。这将有助于我们更快速地定位问题所在。*
运行gradio demo 聊天内容有格式符号， 如下：
\<p\>hello\<\/p\>
\<p\>Hello! How can I assist you today?\<\/p\>

显示的每个问题和回答都带有\<p\>和\<\/p\>, 请问可以怎么消除。

### 运行截图或日志
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/65850906/c273f3b5-5223-4df5-b782-d62dd09dd060)

### 必查项目（前三项只保留你要问的）

- [x] **基础模型**：Alpaca-Plus
- [x] **运行系统**： Linux 
- [x] **问题分类**： 显示效果问题 / 其他问题

**Comment by airaria** [comment]
可能是与mdtex2html相关的问题，暂时可以先参考这个PR #364 中对[gradio_demo.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca/pull/364/files#diff-76ad14095a3621f31929bc450b6d1e91412bcdfe8c496479b9fe9d09b3d56d7a)的改动。我们之后会merge进main branch

**Comment by NiHaoUCAS** [comment]
升级gradio到3.33.1可以解决
