### ISSUE TITLE
chinese-alpaca-plus-7b-hf模型推理内存爆炸，GPU没有被写入数据。

### ISSUE THREAD

**Issue by xiaocode337317439** [ymcui/Chinese-LLaMA-Alpaca#478]
*模型使用.cuda()后还是会默认加载进cpu 内存的感觉，显卡内存没有增加。
model = LlamaForCausalLM.from_pretrained('shibing624/chinese-alpaca-plus-7b-hf').half().cuda()
内存会一直增加到进程被杀死，机器Linux 24G内存，显卡3090TI 24G显存。文档上说14G就够了。
我使用torch.device("cuda:0") 正常cuda:0
*

- [ ✅] **基础模型**：LLaMA / Alpaca / LLaMA-Plus / Alpaca-Plus
- [ ✅] **运行系统**：Linux 
- [  ✅] **问题分类**：模型推理问题（🤗 transformers）
- [  ✅] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [  ✅] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [  ✅] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by airaria** [comment]
参考inference_hf.py中的加载方式，使用`low_cpu_mem_usage=True`，
