### ISSUE TITLE
同样的问题，为什么有时候是 英文回答，有时候是 中文

### ISSUE THREAD

**Issue by alexhmyang** [ymcui/Chinese-LLaMA-Alpaca#48]
![image](https://user-images.githubusercontent.com/10215059/229527909-c25a8aa4-0961-446b-90ab-169e68ffe70f.png)

**Comment by airaria** [comment]
你可以测一下fp16的模型，效果会相比q4量化的好一些。

**Comment by airaria** [comment]
你启动llama.cpp的prompts用的不对。
你尝试README里的命令：
`./main -m zh-models/7B/ggml-model-q4_0.bin --color -f ./prompts/alpaca.txt -ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.3`

**Comment by alexhmyang** [comment]
> fp16

4070 显存只有12G, 运行不起来 fp16

**Comment by alexhmyang** [comment]
> 你启动llama.cpp的prompts用的不对。 你尝试README里的命令： `./main -m zh-models/7B/ggml-model-q4_0.bin --color -f ./prompts/alpaca.txt -ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.3`

alpaca 只是扩写，不能对话呀

**Comment by ymcui** [comment]
你命令行里加载的是llama.cpp里的示例prompt模板（chat-with-bob聊天）。请使用 `-f prompt/alpaca.txt`。
