### ISSUE TITLE
使用llama模型+量化cpp版本进行推理时出现的问题

### ISSUE THREAD

**Issue by xjDUAN184** [ymcui/Chinese-LLaMA-Alpaca#480]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/67a75405-de29-4e84-9c9f-66007c0f98ab)
如果设置了-ins(使用chatGPT的方式进行回答)，就回答的很不好。
使用的命令为：./main -m zh-models/13B/ggml-model-q4_0.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.3
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/b5d2a898-d438-450f-aaeb-65c948a2fa26)
如果没有设置-ins，回答的就像点样子，单还不是特别好（会有重复的）。 
使用的命令为：./main -m ./zh-models/13B/ggml-model-q4_0.bin -f ./prompts/alpaca.txt -p "*****（提出的问题）" -n 512

**Comment by ymcui** [comment]
所以你用的是什么模型？

**Comment by xjDUAN184** [comment]
就是llama.cpp量化部署
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/9d974df8-64b5-40a3-a0ca-d02d18c5e8b2)
我详细说下吧，方便大佬“诊断”，这里的步骤是：
1 将原版LLaMA模型转换为HF格式（因为这里我下载不了原版LLaMA的权重，所以就没做这一步，直接用的huggingface里现成的hf模型decapoda-research/llama-13b-hf）
2 合并LoRA权重，生成全量模型权重 （这一步主要是将第1步的hf模型与中文的权重合并，我这里下载的是zhong中文LLaMA模型Chinese-LLaMA-13B）
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/74f3e303-3ec3-450a-865c-926049c62f01)
3 克隆和编译llama.cpp （这一步主要是为了生成./main和./quantize二进制文件）
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/1aaa874e-7c94-48ba-ab73-44cc39bb270d)
4 生成量化版本模型 
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/334f86fc-d7ab-4c0c-a73b-7962c8594c00)
5 加载并启动模型
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/15bcd7fc-4e24-4836-8f00-97942bdd9e53)
用下面的命令跑出来，模型的回答就很差，不知道在说些什么
./main -m zh-models/7B/ggml-model-q4_0.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.3

**Comment by xjDUAN184** [comment]
> 所以你用的是什么模型？

就是llama.cpp量化部署
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/9d974df8-64b5-40a3-a0ca-d02d18c5e8b2)
我详细说下吧，方便大佬“诊断”，这里的步骤是：
1 将原版LLaMA模型转换为HF格式（因为这里我下载不了原版LLaMA的权重，所以就没做这一步，直接用的huggingface里现成的hf模型decapoda-research/llama-13b-hf）
2 合并LoRA权重，生成全量模型权重 （这一步主要是将第1步的hf模型与中文的权重合并，我这里下载的是zhong中文LLaMA模型Chinese-LLaMA-13B）
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/74f3e303-3ec3-450a-865c-926049c62f01)
3 克隆和编译llama.cpp （这一步主要是为了生成./main和./quantize二进制文件）
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/1aaa874e-7c94-48ba-ab73-44cc39bb270d)
4 生成量化版本模型 
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/334f86fc-d7ab-4c0c-a73b-7962c8594c00)
5 加载并启动模型
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/15bcd7fc-4e24-4836-8f00-97942bdd9e53)
用下面的命令跑出来，模型的回答就很差，不知道在说些什么
./main -m zh-models/7B/ggml-model-q4_0.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.3

**Comment by ymcui** [comment]
因为你用的是llama模型，不是alpaca模型。llama适合用`-p`启动续写模式。
参考：https://github.com/ymcui/Chinese-LLaMA-Alpaca#我应该选什么模型
另外，也建议你比对一下SHA256，确保文件完整性。
SHA256：https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/33b/SHA256.md#merged-files-consolidatedpth

**Comment by AceyKubbo** [comment]
> 因为你用的是llama模型，不是alpaca模型。llama适合用`-p`启动续写模式。 参考：[https://github.com/ymcui/Chinese-LLaMA-Alpaca#我应该选什么模型](https://github.com/ymcui/Chinese-LLaMA-Alpaca#%E6%88%91%E5%BA%94%E8%AF%A5%E9%80%89%E4%BB%80%E4%B9%88%E6%A8%A1%E5%9E%8B) 另外，也建议你比对一下SHA256，确保文件完整性。 SHA256：https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/33b/SHA256.md#merged-files-consolidatedpth

你好,我想问下llama.cpp的main.exe能正常运行起来,但是使用llama-cpp-python就无法读取到模型,会报错,是不是因为SHA256对不上导致的
```
error loading model: unknown (magic, version) combination: 67676a74, 00000003; 
```

**Comment by ymcui** [comment]
> > 因为你用的是llama模型，不是alpaca模型。llama适合用`-p`启动续写模式。 参考：[https://github.com/ymcui/Chinese-LLaMA-Alpaca#我应该选什么模型](https://github.com/ymcui/Chinese-LLaMA-Alpaca#%E6%88%91%E5%BA%94%E8%AF%A5%E9%80%89%E4%BB%80%E4%B9%88%E6%A8%A1%E5%9E%8B) 另外，也建议你比对一下SHA256，确保文件完整性。 SHA256：https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/33b/SHA256.md#merged-files-consolidatedpth
> 
> 你好,我想问下llama.cpp的main.exe能正常运行起来,但是使用llama-cpp-python就无法读取到模型,会报错,是不是因为SHA256对不上导致的
> 
> ```
> error loading model: unknown (magic, version) combination: 67676a74, 00000003; 
> ```

llama-cpp-python是基于llama.cpp的binding，所以你要看这两者是否匹配。比如llama.cpp你如果用的是最新版，而llama-cpp-python不是的话，那有可能无法加载模型，因为近期llama.cpp做过较大改动。建议你都更新到最新版调试。

**Comment by AceyKubbo** [comment]
> > > 因为你用的是llama模型，不是alpaca模型。llama适合用`-p`启动续写模式。 参考：[https://github.com/ymcui/Chinese-LLaMA-Alpaca#我应该选什么模型](https://github.com/ymcui/Chinese-LLaMA-Alpaca#%E6%88%91%E5%BA%94%E8%AF%A5%E9%80%89%E4%BB%80%E4%B9%88%E6%A8%A1%E5%9E%8B) 另外，也建议你比对一下SHA256，确保文件完整性。 SHA256：https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/33b/SHA256.md#merged-files-consolidatedpth
> > 
> > 
> > 你好,我想问下llama.cpp的main.exe能正常运行起来,但是使用llama-cpp-python就无法读取到模型,会报错,是不是因为SHA256对不上导致的
> > ```
> > error loading model: unknown (magic, version) combination: 67676a74, 00000003; 
> > ```
> 
> llama-cpp-python是基于llama.cpp的binding，所以你要看这两者是否匹配。比如llama.cpp你如果用的是最新版，而llama-cpp-python不是的话，那有可能无法加载模型，因为近期llama.cpp做过较大改动。建议你都更新到最新版调试。

感谢感谢,还真是这个问题,已经解决了,llama.cpp新版竟然不向下兼容,委实有点坑人
