### ISSUE TITLE
请问预训练不同document之间concat在一起需要使用一些special token吗，比如gpt的"<endoftext>" 之类的，谢谢

### ISSUE THREAD

**Issue by GeorgeLuImmortal** [ymcui/Chinese-LLaMA-Alpaca#481]
请问预训练不同document之间concat在一起需要使用一些special token吗，比如类似gpt的 “endoftext“  token之类的，谢谢

**Comment by iMountTai** [comment]
不需要，相对全部语料而言，单个词语、段落的切割不影响任务的整体效果

**Comment by airaria** [comment]
我们是按行处理的，没有区分不同文档。当然你说的方法你也可以尝试

**Comment by GeorgeLuImmortal** [comment]
谢谢，想请教一下预训练有加bos和eos这两个特殊token吗？
