### ISSUE TITLE
我基于Chinese-LLaMA-Plus-13B与Chinese-Alpaca-Plus-13B 合并了模型，并上传到HuggingFace。有需要的可以直接下载

### ISSUE THREAD

**Issue by yaakua** [ymcui/Chinese-LLaMA-Alpaca#482]
## 合并流程
根据[合并教程](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E6%89%8B%E5%8A%A8%E6%A8%A1%E5%9E%8B%E5%90%88%E5%B9%B6%E4%B8%8E%E8%BD%AC%E6%8D%A2#%E5%A4%9Alora%E6%9D%83%E9%87%8D%E5%90%88%E5%B9%B6%E9%80%82%E7%94%A8%E4%BA%8Echinese-alpaca-plus)当中的操作做了如下步骤
- Step 1: 将原版LLaMA模型转换为HF格式
   这里采用的原版的LLaMA模型使用的是：LLaMA_13B,转为 llama_13b_hf格式
- Step 2: 合并LoRA权重，生成全量模型权重
  这一步采用的是《多LoRA权重合并（适用于Chinese-Alpaca-Plus）》这一个步骤
 合并Chinese-Alpaca-Plus需要提供两个LoRA权重，分别为Chinese-LLaMA-Plus-13B和Chinese-Alpaca-Plus-13B 。
 执行后得到的结果文件，我在本地能跑成功，且能正常推理（单张4090显卡推理速度还不错），没有做任何量化处理。

## 下载链接
现将合并后生成的全量模型权重上传到HuggingFace：[https://huggingface.co/yangkui/Chinese-LLaMA-Alpaca-Plus-13b-merge](https://huggingface.co/yangkui/Chinese-LLaMA-Alpaca-Plus-13b-merge)

## 推理方式
我使用的是text-generation-webui方式做推理，将模型文件复制到models目录下即可，如图：
<img width="415" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/1543846/3ccfdee8-a6ed-4153-8a2c-132c2c803de0">

启动脚本参数：
--model chinese-alpaca-plus-13b-output --gpu-memory 10 --listen-port 7888 --chat --api

大家有其他问题可以直接给我留言，或者发送邮件：yaakua@126.com

**Comment by yaakua** [comment]
发个推理界面的截图
<img width="873" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/1543846/3b83831d-f970-49f4-9bc8-6e0ea2b02106">

**Comment by ymcui** [comment]
你好，方便比对一下合并为pth文件的SHA256吗？https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/33b/SHA256.md
比对了一下你上面hf版本的sha256，与我们本地端的值不一致。也可以顺便说一下transformers/torch/peft的版本

**Comment by yaakua** [comment]
> 你好，方便比对一下合并为pth文件的SHA256吗？https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/33b/SHA256.md 比对了一下你上面hf版本的sha256，与我们本地端的值不一致。也可以顺便说一下transformers/torch/peft的版本

我没有你说的那个pth文件哦

**Comment by DEV3YeHe** [comment]
感谢分享，求助两个问题
4090，13B模型用ooba自带训练会爆显存，每次都是在还剩10几步的时候爆掉。
而且推理特别慢，一分钟一句。

**Comment by yaakua** [comment]
> 

我还没做训练，推理的话我这个还是挺快的。几乎是秒出

**Comment by showtimesss** [comment]
下载后不能直接使用AutoTokenizer.from_pretrained导入吗？提示ValueError: Tokenizer class LLamaTokenizer does not exist or is not currently imported.

**Comment by qraccess** [comment]
mac m1 air上跑了，速度很慢，7B的性能还不错，不过会出现不断重复。13B性能无法忍受

<img width="841" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/3363615/62894cff-5425-4c3d-9964-b2bf7d60720e">

<img width="841" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/3363615/169f2051-fab2-4f86-921d-6b28d6582e8f">

**Comment by qraccess** [comment]
用的是 lLamaChat, 支持上传pth，它自动做量化。

**Comment by GuohongLi** [comment]
@yaakua  两个问题，这个合并的模型是fp16么？还是做过量化了。另外，单张4090显卡推理速度大概多少？我本地同样的命令跑，一秒一个字，有点慢不知道是否正常。

**Comment by yaakua** [comment]
> @yaakua 两个问题，这个合并的模型是fp16么？还是做过量化了。另外，单张4090显卡推理速度大概多少？我本地同样的命令跑，一秒一个字，有点慢不知道是否正常。

是fp16的，没有做量化。我本地用4090跑效果也是差不多1秒一个字，不太理想

**Comment by yaakua** [comment]
> 

这个应该是你的代码或者环境问题

**Comment by yaakua** [comment]
> 

最低多少不清楚，我的是128G内存、24G显存，用GPU的话对内存要求没那么高。我看实际占用也没多少G

**Comment by GuohongLi** [comment]
@yaakua --gpu-memory 10 设置为20，推理快了1倍，一秒2个左右

**Comment by XuJianzhi** [comment]
谢谢你，开源侠
