### ISSUE TITLE
Tokenizer只会添加bos标签<s>，不添加eos标签</s>

### ISSUE THREAD

**Issue by 13269279918** [ymcui/Chinese-LLaMA-Alpaca#483]
### 描述问题

**背景**1：我在原版llama-13b的基础上合并了chinese-llama-13b和chinese-alpaca-13b两个模型。后续我在合并过后的模型基础上进行了增量的预训练。预训练的文本是仙侠类网络小说
**背景**2：经过预训练之后，发现模型输出出现问题，总是会不停的输出直到达到最大长度。即使增加限制输出长度的prompt也没有用。
**问题**：我在排查的时候发现原始文本数据经过tokenize后只会在句子开头增加标签\<s\>，而不会在句子结尾增加标签\</s\>。因此我猜测是否是因为eos标签的缺失，使得模型没有学会如何结束输出？
（不清楚这是否是正常情况，特来求证）

### 运行截图

![aebcc09cda3930177c20a189bca0151](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/54931752/84521936-c6b2-4c86-b30a-f0048a803340)

### 必查项目

- [x] **基础模型**：LLaMA / Alpaca / LLaMA-Plus / Alpaca-Plus
- [x] **运行系统**：Linux 
- [x] **问题分类**：模型训练与精调 
- [x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案

**Comment by iMountTai** [comment]
可能你的大部分文本都太长了，导致eos token被截断，训练有点问题

**Comment by airaria** [comment]
另外默认的确是没加eos的，你可以通过其他方式（比如[PAD]）控制结束，或者在继续训练时使用eos

**Comment by 13269279918** [comment]
> 默认的确是没加eos的，你可以通过其他方式（比如[PAD]）控制结束，或者在继续训练时使用eos

那么请问模型输出的时候没完没了说个不停的问题，和没有eos有直接相关性吗？如果我想加eos要怎么弄呢？我是个初学者，现在能想到的就是手动在语料的最后加</S>，但是不确定是否有效？

**Comment by iMountTai** [comment]
可以试试，炼丹要有失败的准备
