### ISSUE TITLE
指令微调的模型权重保存问题

### ISSUE THREAD

**Issue by B15031011** [ymcui/Chinese-LLaMA-Alpaca#485]
指令微调结束保存模型文件时候报错，不知道是不是peft的版本问题呢？

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/19522483/9b3b0e51-ab30-458f-90f1-d494a3a3d8a5)

**Comment by B15031011** [comment]
有没有大佬解决一下？

**Comment by iMountTai** [comment]
那你的peft版本是我们推荐的版本吗？中间没保存模型吗，保存的话是否正常？

**Comment by B15031011** [comment]
> 那你的peft版本是我们推荐的版本吗？中间没保存模型吗，保存的话是否正常？
是推荐的版本，模型都存了，但是图里这些步骤没有执行感觉
<img width="967" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/19522483/8dbe9e3e-3802-4ef3-9fd7-e7eb55135b4a">

**Comment by airaria** [comment]
重新pull一下代码。
可以先按wiki手动操作，免去重新训练的麻烦
