### ISSUE TITLE
cd llama.cpp && make时make报错，ggml.c:76:23: 致命错误：stdatomic.h：没有那个文件或目录

### ISSUE THREAD

**Issue by 1anglesmith1** [ymcui/Chinese-LLaMA-Alpaca#488]
[root@hostzs llama.cpp]# make
I llama.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native
I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native
I LDFLAGS:  
I CC:       cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
I CXX:      g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

cc  -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native   -c ggml.c -o ggml.o
ggml.c:76:23: 致命错误：stdatomic.h：没有那个文件或目录
 #include <stdatomic.h>
                       ^
编译中断。
make: *** [ggml.o] 错误 1

**Comment by ymcui** [comment]
参考一下llama.cpp里的issue吧，我们也不太清楚：https://github.com/ggerganov/llama.cpp/issues/552

**Comment by 1anglesmith1** [comment]
明明是一样的clone过来直接用，为什么会报错呀

**Comment by AceyKubbo** [comment]
llama.cpp里面README已经告诉你window下要这样安装,如果你是linux或者是mac那就有可能是gcc版本不对,看issues中说至少要gcc12,祝你好运

> On Windows:

Download the latest fortran version of [w64devkit](https://github.com/skeeto/w64devkit/releases).
Extract w64devkit on your pc.
Run w64devkit.exe.
Use the cd command to reach the llama.cpp folder.
From here you can run:
make

**Comment by sacada-fish** [comment]
因为centos 自带的gcc版本过低，导致的错误。
升级gcc，命令如下：
sudo yum install centos-release-scl
sudo yum install devtoolset-9-gcc*
scl enable devtoolset-9 bash

**Comment by ktlifeng** [comment]
> 因为centos 自带的gcc版本过低，导致的错误。 升级gcc，命令如下： sudo yum install centos-release-scl sudo yum install devtoolset-9-gcc* scl enable devtoolset-9 bash

thanks, that's resolved my problem
