### ISSUE TITLE
预训练时运行run_pt.sh出现问题

### ISSUE THREAD

**Issue by xiaosayes** [ymcui/Chinese-LLaMA-Alpaca#489]
报错信息贴如下：
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/antonyxiao/llm/chinese_llama_model/chinese_llama_alpaca/Chinese-LLaMA-Alpaca/scripts/run_c │
│ lm_pt_with_peft.py:632 in <module>                                                               │
│                                                                                                  │
│   629                                                                                            │
│   630                                                                                            │
│   631 if __name__ == "__main__":                                                                 │
│ ❱ 632 │   main()                                                                                 │
│   633                                                                                            │
│                                                                                                  │
│ /home/antonyxiao/llm/chinese_llama_model/chinese_llama_alpaca/Chinese-LLaMA-Alpaca/scripts/run_c │
│ lm_pt_with_peft.py:567 in main                                                                   │
│                                                                                                  │
│   564 │   ).__get__(model, type(model))                                                          │
│   565 │                                                                                          │
│   566 │   # Initialize our Trainer                                                               │
│ ❱ 567 │   trainer = Trainer(                                                                     │
│   568 │   │   model=model,                                                                       │
│   569 │   │   args=training_args,                                                                │
│   570 │   │   train_dataset=train_dataset if training_args.do_train else None,                   │
│                                                                                                  │
│ /home/antonyxiao/llm/llama-main/transformers/src/transformers/trainer.py:344 in __init__         │
│                                                                                                  │
│    341 │   │   self.is_in_train = False                                                          │
│    342 │   │                                                                                     │
│    343 │   │   # create accelerator object                                                       │
│ ❱  344 │   │   self.accelerator = Accelerator()                                                  │
│    345 │   │                                                                                     │
│    346 │   │   # post accelerator creation setup                                                 │
│    347 │   │   if getattr(self.accelerator.state, "fsdp_plugin", None) is not None:              │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py:419 in __init__          │
│                                                                                                  │
│    416 │   │   self.native_amp = False                                                           │
│    417 │   │   err = "{mode} mixed precision requires {requirement}"                             │
│    418 │   │   if (                                                                              │
│ ❱  419 │   │   │   self.state.mixed_precision == "fp16"                                          │
│    420 │   │   │   and self.device.type != "cpu"                                                 │
│    421 │   │   │   and self.distributed_type not in (DistributedType.DEEPSPEED, DistributedType  │
│    422 │   │   ):                                                                                │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/state.py:641 in mixed_precision         │
│                                                                                                  │
│   638 │   @property                                                                              │
│   639 │   def mixed_precision(self):                                                             │
│   640 │   │   if self.distributed_type == DistributedType.DEEPSPEED:                             │
│ ❱ 641 │   │   │   config = self.deepspeed_plugin.deepspeed_config                                │
│   642 │   │   │   if config.get("fp16", {}).get("enabled", False):                               │
│   643 │   │   │   │   mixed_precision = "fp16"                                                   │
│   644 │   │   │   elif config.get("bf16", {}).get("enabled", False):                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'deepspeed_config'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 109782) of binary: /root/miniconda3/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_clm_pt_with_peft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-01_17:44:10
  host      : frontop-virtual-machine
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 109782)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by iMountTai** [comment]
贴一下运行脚本吧，日志里也没什么有价值的内容

**Comment by xiaosayes** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/65337121/e6a4e711-6ec9-42fd-974e-08b704985d54)
用的是单卡3090，前面已经成功合并了模型，接下来想结合我自己的领域数据做预训练，跑的run_pt.sh脚本，脚本内改的参数如截图所示，报错的内容如上，请问下是什么原因呢

**Comment by iMountTai** [comment]
我单卡没有复现您的问题，不确定是不是分布式训练的问题，去掉deepspeed试试

**Comment by xiaosayes** [comment]
好的，去掉了deepspeed，出现如下问题：
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/65337121/64af6efd-d11b-46a8-b34f-98fc525bd78a)
麻烦帮忙看下哈，感谢~

**Comment by iMountTai** [comment]
这个报错看着像是环境问题，没有遇到过，可以试着调试一下。deepspeed只是一个建议，并不是说去掉就能运行

**Comment by jediyoda36** [comment]
同3090，有同样问题……
