### ISSUE TITLE
怎么启动 问答 写信 写代码 等功能？用什么命令行？以及什么prompt?

### ISSUE THREAD

**Issue by alexhmyang** [ymcui/Chinese-LLaMA-Alpaca#49]
![image](https://user-images.githubusercontent.com/10215059/229528550-142500fa-67c2-4803-81b4-a9f837a96412.png)

 ./main -m ./zh-models/7B/ggml-model-q4_0.bin  -n 256 --repeat_penalty 1.0 --color -i -r "User:" -f prompts/chat-with-bob.txt

chat 貌似用以上的命令就可以（里面都是英文的例子，是否要换成中文的），但 其他的命令好像没找到

怎么启动 问答 写信 写代码 等功能？用什么命令行？以及什么prompt?

**Comment by airaria** [comment]
-f 后只能加 ./prompts/alpaca.txt
如果使用其他的prompt，效果可能会很差（因为模型不是用那些prompt训练的）

**Comment by alexhmyang** [comment]
> 怎么启动 问答 写信 写代码 等功能？用什么命令行？以及什么prompt?



> -f 后只能加 ./prompts/alpaca.txt 如果使用其他的prompt，效果可能会很差（因为模型不是用那些prompt训练的）

/alpaca.txt 只是扩写，不是 问答呀，请问怎么启动 问答 写信 写代码 等功能？用什么命令行？以及什么prompt?

**Comment by alexhmyang** [comment]
> 和你另外一个issue一样，加载`-f prompts/alpaca.txt`，不论你想用Alpaca来做什么。 至于具体使用什么prompt需要你自己试，我们也不知道机器对什么prompt理解的更好。

哦噢，不好意思，我用 colab上的例子 以为 命令行需要 换不同的 prompt, 您官网上的例子 都是 直接运行 ./main -m zh-models/7B/ggml-model-q4_0.bin --color -f ./prompts/alpaca.txt -ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.3 的么？

 我照着 您的例子 得到 以下结果，怎么看上去像 原版的， 没有屏蔽违禁词

![image](https://user-images.githubusercontent.com/10215059/229665712-e52aa044-c053-45fb-92ed-b3df4589ea06.png)
