### ISSUE TITLE
llama.cpp 使用GPU进行量化部署

### ISSUE THREAD

**Issue by xjDUAN184** [ymcui/Chinese-LLaMA-Alpaca#490]
我想请假下llama.cpp如何使用GPU进行量化部署？我看下面这张图里面是可以用GPU的。
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/8c0d191c-ac3b-41ef-869f-e2e3729e0aa7)
是在第一步这里吗？与[BLAS（或cuBLAS如果有GPU）一起编译
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/1dda352e-2e70-4ce9-9109-7cb926c44853)

**Comment by ymcui** [comment]
你截图里就有，最下面那一块，需要和cuBLAS等一起编译，后续就可以用`-ngl`参数将部分层offload到GPU了。
具体编译和使用方法去llama.cpp里看吧。

**Comment by xjDUAN184** [comment]
> 你截图里就有，最下面那一块，需要和cuBLAS等一起编译，后续就可以用`-ngl`参数将部分层offload到GPU了。 具体编译和使用方法去llama.cpp里看吧。

非常感谢大佬，懂了，这里用cuBLAS编译，然后设置-ngl参数，让一些层在GPU上跑，提升推理的速度。
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/304a1f5c-dbb8-4f26-b7e8-9314da23a34b)
这里我仍然有几个问题，希望大佬不吝赐教！
1    -ngl参数就是普通的数字吗？
2    在gpu上推理的结果不是很好，我检查了SHA256，没有问题。还有可能是哪里出问题？
3    如果说我想使用别的模型，与llama-hf相合并，使用llama.cpp做推理，是不是和llama-chinese一样？
拜谢！

**Comment by ymcui** [comment]
1、-ngl后面需要加整数参数，表示多少层offload到GPU（比如`-ngl 30`表示把30层参数offload到GPU）。这个值需要自己试探，比如加到多少层不OOM。llama.cpp会有log，你关注一下VRAM使用情况，例如：
```
llama_model_load_internal: [cublas] offloading 30 layers to GPU
llama_model_load_internal: [cublas] total VRAM used: 10047 MB
```
2、目前看你截图用的是`-p`模式，这个是续写不是“类ChatGPT”交互模式。如果要体验ChatGPT的交互模式，需要加载Alpaca模型，并且通过`-f ./prompts/alpaca.txt`指定prompt模板并使用`-ins`启动指令交互模式。
3、没太看明白。本项目的相关模型都是需要用原版llama-hf进行合并的。非本项目模型的使用方法不太清楚，建议去对应的项目提问。
