### ISSUE TITLE
多LoRA权重合并（适用于Chinese-Alpaca-Plus）时，报错got an unexpected keyword argument 'device_map'

### ISSUE THREAD

**Issue by uamyangel** [ymcui/Chinese-LLaMA-Alpaca#491]
### 运行指令
`python scripts/merge_llama_with_chinese_lora.py \
> --base_model /home/llama
llama/    llama_hf/
> --base_model /home/llama_hf \
> --lora_model /home/llama/chinese_llama_plus_lora_7b,/home/alpaca/chinese_alpaca_plus_lora_7b \
> --output_type pth \
> --output_dir /home/models`

### 运行截图或日志
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/15668052/db6eb0e6-5da6-49af-833c-c8e003da90f0)

**Comment by qa6300525** [comment]
一样的问题，我在阿里云上 和 google colab 上执行模型合并都遇到了这个问题。colab上我直接用的github上的原始代码。
<img width="934" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/10059849/0fb65025-554f-4199-8368-b62d3f91b64f">
<img width="998" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/10059849/143a89d3-3b69-4283-ad50-2fcd64177aac">
<img width="913" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/10059849/1ec5818e-30ee-4f83-b638-8140dddb5413">

**Comment by ymcui** [comment]
> 一样的问题，我在阿里云上 和 google colab 上执行模型合并都遇到了这个问题。colab上我直接用的github上的原始代码。
> <img alt="image" width="934" src="https://user-images.githubusercontent.com/10059849/243053294-0fb65025-554f-4199-8368-b62d3f91b64f.png">
> <img alt="image" width="998" src="https://user-images.githubusercontent.com/10059849/243053301-143a89d3-3b69-4283-ad50-2fcd64177aac.png">
> <img alt="image" width="913" src="https://user-images.githubusercontent.com/10059849/243053311-1ec5818e-30ee-4f83-b638-8140dddb5413.png">

你试一下colab notebook，依赖那一块已经修改为稳定版了，不安装peft的最新commit，可以跑通合并流程。
https://colab.research.google.com/drive/1axIgPoThgm-v3rglmRV9QnhVsJKHsHBj#scrollTo=_GbjsT2wRRCR

**Comment by icowan** [comment]
同样遇到此问题

**Comment by icowan** [comment]
同样遇到此问题，原因是peft版本太高了 我这是 `Peft version: 0.4.0.dev0`，只需要将版本降下来就好了

```
pip3 install peft==0.3.0
```
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/6229526/aa4e025d-9d97-4e8d-8ebf-c2b53f734ae5)
