### ISSUE TITLE
run_pt.sh gives error on peft configuration saviing step

### ISSUE THREAD

**Issue by yusufcakmakk** [ymcui/Chinese-LLaMA-Alpaca#492]
Hi, I have tried run_pt.sh with last [commit](https://github.com/ymcui/Chinese-LLaMA-Alpaca/commit/8e53c880f6af9b459f5fa503bcb1f75c0f304a6d) and it gives error like:

`Chinese-LLaMA-Alpaca/scripts/run_clm_pt_with_peft.py", line 615, in main
    unwrap_model(model).peft_config.save_pretrained(lora_path)
AttributeError: 'dict' object has no attribute 'save_pretrained'`

Why did you update it from `unwrap_model(model).peft_config['default'].save_pretrained(lora_path)` to `unwrap_model(model).peft_config.save_pretrained(lora_path)`?

**Comment by airaria** [comment]
Peft has been changed frequently. 
Which peft version did you use?
The code
```
unwrap_model(model).peft_config.save_pretrained(lora_path)
```
works with [Peft@13e53fc](https://github.com/huggingface/peft/tree/13e53fc), which is the version used in our training

**Comment by yusufcakmakk** [comment]
> Peft has been changed frequently. Which peft version did you use? The code
> 
> ```
> unwrap_model(model).peft_config.save_pretrained(lora_path)
> ```
> 
> works with [Peft@13e53fc](https://github.com/huggingface/peft/tree/13e53fc), which is the version used in our training

Yeah, you are right. It is a version issue. Thanks for noticing that.

**Comment by jby20180901** [comment]
however, i use [Peft@13e53fc](https://github.com/huggingface/peft/tree/13e53fc),,but also "save_pretrained"
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/48289399/771c367d-1fbe-472a-a421-72da9b3fd478)
it is right?

**Comment by ymcui** [comment]
> however, i use [Peft@13e53fc](https://github.com/huggingface/peft/tree/13e53fc),,but also "save_pretrained"
> ![image](https://user-images.githubusercontent.com/48289399/242820340-771c367d-1fbe-472a-a421-72da9b3fd478.png)
> it is right?

According to your log, it shows `0.4.0dev0`, which is not expected. It should be `0.3.0.dev0`.
You should uninstall the current peft and reinstall the [Peft@13e53fc](https://github.com/huggingface/peft/tree/13e53fc).
