### ISSUE TITLE
实验室只有一块3090，有什么方式可以将中文llama学习到垂直领域的知识

### ISSUE THREAD

**Issue by xiaosayes** [ymcui/Chinese-LLaMA-Alpaca#494]
实验室学生，现在实验室里只有一块3090 24G显卡，手上有一些垂直领域的问答数据，想用中文llama大模型结合领域数据做一个毕设问答系统，不过重新做全量预训练的话一块3090估计资源也不够，请问下有什么方式可以在现有环境下实现这个功能吗？谢谢

**Comment by Vancause** [comment]
It's hard to fine-tune the model.

**Comment by ymcui** [comment]
几点建议：
1、首先建议你补充一下大模型相关基础知识，网上有不少课程，这将帮助你快速了解哪些模型适合做哪些任务。比如你要做问答系统，那么用类似Alpaca的指令精调过的模型就是一个很好的起点。
2、单张卡你可以考虑LoRA等高效精调方法（7B模型），这还是得需要一些基础知识。虽然我们也提供了相关的训练脚本，但如果你没有了解LoRA是什么，那么也很难用对。
3、如果是面向垂类问答领域，那你也需要了解如何将手头的数据处理成指令类型的数据，这部分可以参考我们wiki中的训练教程。
