### ISSUE TITLE
无法保存peft_config

### ISSUE THREAD

**Issue by lyzKF** [ymcui/Chinese-LLaMA-Alpaca#495]
### 

脚本文件run_clm_pt_with_peft.py的第605行，这里提示dict没有save_pretrained这个方法
```
unwrap_model(model).peft_config.save_pretrained(lora_path)
```
这里是不是需要修改一下？

**Comment by ymcui** [comment]
你用的PEFT版本是[13e53fc](https://github.com/huggingface/peft/tree/13e53fc)这个吗？

**Comment by lyzKF** [comment]
@ymcui  PEFT的版本为peft==0.3.0

**Comment by ymcui** [comment]
> @ymcui PEFT的版本为peft==0.3.0

你安装一下上面的版本（[13e53fc](https://github.com/huggingface/peft/tree/13e53fc)）应该可以解决。我们的训练脚本只能和特定版本的peft搭配使用。
详见（最上面的重要提示）：https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/指令精调脚本

**Comment by lyzKF** [comment]
@ymcui 好的，谢谢，我试一下

**Comment by lyzKF** [comment]
@ymcui

**Comment by lyzKF** [comment]
@ymcui

**Comment by airaria** [comment]
代码已更新兼容两种保存方式。

**Comment by liyu19980601** [comment]
我的peft的版本是0.3.0
<img width="1071" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/44581509/f7dc8196-71e3-4bcf-be42-e6ba94d07619">
为什么还是有错误呢？
<img width="1689" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/44581509/d068daa8-1203-4cfe-963c-9e80dbba15d9">

**Comment by airaria** [comment]
@liyu19980601 请pull最新代码
