### ISSUE TITLE
size mismatch for base_model error when running run_sft.py

### ISSUE THREAD

**Issue by yusufcakmakk** [ymcui/Chinese-LLaMA-Alpaca#496]
Hi,

I followed the [pretraining wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/pretraining-script) and it continues to training. I want to use sft tuning with a checkpoint of the pretraining step. So I used checkpoint-xxx. I did the steps in [Prepare for merge](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/pretraining-script#prepare-for-merging) to merge llama with lora. Also, I used merge_llama_with_chinese.py to create huggingface format with the following command:
```
python merge_llama_with_chinese_lora.py \
    --base_model ./llama/llama-7b-hf-model \
    --lora_model ./llama/Chinese-LLaMA-Alpaca/scripts/llama_lora \
    --output_type huggingface \
    --output_dir ./llama/Chinese-LLaMA-Alpaca/scripts/output_dir/book-merge-hf
```

So I used this model in run_sft.sh with the following parameters:

```
lr=1e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=./llama/Chinese-LLaMA-Alpaca/scripts/output_dir/book-merge-hf
chinese_tokenizer_path=./llama/merged_tokenizer_hf
dataset_dir=./llama/alpaca_dataset
per_device_train_batch_size=32
per_device_eval_batch_size=16
training_steps=1000
gradient_accumulation_steps=16
output_dir=output_dir
peft_model=./llama/Chinese-LLaMA-Alpaca/scripts/llama_lora
validation_file=./llama/alpaca_dataset_val_tr.json

deepspeed_config_file=ds_zero2_no_offload.json
...

```

It starts to process but in Peft model loading, it gives the following error:

```
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
        size mismatch for base_model.model.model.embed_tokens.modules_to_save.default.weight: copying a param with shape torch.Size([48303, 4096]) from checkpoint, the shape in current model is torch.Size([48304, 4096]).
        size mismatch for base_model.model.lm_head.modules_to_save.default.weight: copying a param with shape torch.Size([48303, 4096]) from checkpoint, the shape in current model is torch.Size([48304, 4096]).

```

I have checked several issues that related with my issue: #361 , #431 

Trained sentencepiece tokenizer length: 20000
LLaMA-7b tokenizer length: 32000
Merged tokenizer length: 48303

```
import torch
sd = torch.load('./llama/Chinese-LLaMA-Alpaca/scripts/llama_lora/adapter_model.bin',map_location='cpu')
for k,v in sd.items():
    if 'embed_tokens' in k:
        print(v.shape)
```

Output: `torch.Size([48303, 4096])`

I have two question:

1. What is the reason for the error size mismatch?
2. Should we pretrain with tokenizer that has PAD token?

Please guide me. Thank you.

**Comment by airaria** [comment]
If you have merged LoRA into the base model, you no longer need to provide `--peft_model`  when fine-tuning.

**Comment by yusufcakmakk** [comment]
@airaria thank you 😊 It is started to train 🚀
