### ISSUE TITLE
请问论文说的第一个个训练阶段是在具体代码的什么地方体现的呢

### ISSUE THREAD

**Issue by wangjvjie** [ymcui/Chinese-LLaMA-Alpaca#497]
我在代码中读了很久，只找到了一个model.resize_token_embeddings(len(tokenizer))。并且我看所有的训练都是在一个Trainer里，所以不是很理解

**Comment by ymcui** [comment]
因为代码里没有啊。我们提供的脚本是从第二阶段开始的。第一阶段已经不推荐使用了，是早期试错阶段的产物。
https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/预训练脚本#训练步骤
