### ISSUE TITLE
求助请问window环境下cmake以后为什么无法编译出main和quantize 按照每个step操作的

### ISSUE THREAD

**Issue by WwLuo-1024** [ymcui/Chinese-LLaMA-Alpaca#50]
D:\Chinese-LLaMA_Alpaca\llama.cpp>cmake .
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.35.32216.1
-- The CXX compiler identification is MSVC 19.35.32216.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- CMAKE_SYSTEM_PROCESSOR: AMD64
-- x86 detected
-- Configuring done (11.7s)
-- Generating done (0.1s)
-- Build files have been written to: D:/Chinese-LLaMA_Alpaca/llama.cpp

**Comment by ymcui** [comment]
错误信息在哪里？从你的log里没看到报错信息

**Comment by WwLuo-1024** [comment]
确实没有直接出错误信息，但是不知道为什么也没有生成main和quantize。没有用过cmake的经验 一脸懵

**Comment by ymcui** [comment]
你可以看一下，看看是否能解决：https://github.com/ggerganov/llama.cpp/issues/103 
另外也可以在llama.cpp的issue里找找windows下部署的问题，看看有没有出现同样问题的解决方案。

**Comment by WwLuo-1024** [comment]
非常感谢 已经成功解决了！
