### ISSUE TITLE
指令精调报错

### ISSUE THREAD

**Issue by Damonproto** [ymcui/Chinese-LLaMA-Alpaca#500]
### 详细描述问题

继续精调 Chinese Alpaca Lora 运行bash run_sft.sh报错

### 参考信息

单卡3090运行

run_sft.sh配置
pretrained_model=/home/ai/alpaca-lora/Chinese_LLaMA_Plus_Merge
chinese_tokenizer_path=/home/ai/alpaca-lora/Lora/chinese_llama_plus_lora_7b
dataset_dir=/home/ai/alpaca-lora/Chinese-LLaMA-Alpaca/data
per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=100
gradient_accumulation_steps=1
output_dir=/home/ai/alpaca-lora/Fine-Tuning-Output
peft_model=/home/ai/alpaca-lora/Lora/chinese_alpaca_plus_lora_7b
validation_file=/home/ai/alpaca-lora/Chinese-LLaMA-Alpaca/data/aiai_content_qa_20230601.json

deepspeed_config_file=ds_zero2_no_offload.json

#### 依赖情况（代码类问题务必提供）

*请提供transformers, peft, torch等常规依赖库的版本：pip list \| grep*
transformers 4.30.0.dev0
peft 0.4.0.dev0
torch 1.13.1+cu117

#### 运行日志或截图

![微信图片_20230602201954](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/5035959/83295293-9702-4e57-995b-173a68b22c8b)

### 必查项目

- [ x] **基础模型**：Alpaca-Plus7B
- [ x] **运行系统**： Linux 
- [ x] **问题分类**： 模型训练与精调
- [x ] **模型正确性检查**：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行。
- [x ] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by airaria** [comment]
请使用[commit id为13e53fc的Peft](https://github.com/huggingface/peft/tree/13e53fc)

**Comment by Damonproto** [comment]
谢谢，问题解决了 @airaria @alanbeen

**Comment by iamhere1** [comment]
> 谢谢，问题解决了 @airaria @alanbeen

你好，可以分享下你是怎么解决的吗？我也遇到相同问题，更新peft版本为13e53fc的Peft, 删除--gradient_checkpointing都没效果
