### ISSUE TITLE
Chinese Plus Alpaca 继续精调疑问

### ISSUE THREAD

**Issue by Damonproto** [ymcui/Chinese-LLaMA-Alpaca#502]
我想继续训练Chinese Plus Alpaca
--model_name_or_path:  合并Chinese-LLaMA-Plus-LoRA后的Chinese-LLaMA模型
问题1： --peft_path:  这里是使用Chinese-Alpaca 还是 Chinese-Plus-Alpaca 的权重目录?
问题2： 继续精调是只用提供新的数据的 json，微调后就能得到原Chinese-Plus-Alpaca + 新数据合并的效果吗？
问题3： 训练完后得到的 New-Alpaca-Lora 合并时是使用  Chinese-LLaMA + Chinese-LLaMA-Plus-LoRA + Chinese-Alpaca-Plus-LoRA + NewAlpaca-Lora 还是 Chinese-LLaMA + Chinese-LLaMA-Plus-LoRA + NewAlpaca-Lora

*将[ ]中填入x，表示打对钩。提问时删除这行。 前三项请按自己的问题类型保留符合的选项。*

- [x ] **基础模型**：Alpaca-Plus 7B
- [x ] **运行系统**：Linux 
- [x ] **问题分类**：模型训练与精调
- [x ] **模型正确性检查**：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行。
- [ x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by iMountTai** [comment]
问题1： --peft_path Chinese-Plus-Alpaca 的权重目录
问题2： 是的
问题3： 训练完后得到的 New-Alpaca-Lora 合并时是使用 Chinese-LLaMA +  NewAlpaca-Lora

**Comment by Damonproto** [comment]
我用了一个有2124条数据的 json 继续训练 Chinese-LLaMA-Plus-LoRA，得到的模型大小只有 312MB，而原版 Chinese-LLaMA-Plus-LoRA 有 1GB，我理解上继续训练不是应该会使模型变大才对，是不是意味着我训练的模型效果变差了？
![1685930350357](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/5035959/bb8e2a51-857e-4ce1-bacb-b01e853e31de)
![1685930477326](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/5035959/666727ba-0934-47da-920b-469349d6928d)

**Comment by airaria** [comment]
大概率是没有训练embed_tokens或lm_head所以权重文件小。
加载adapter_model.bin并打印其中的key看看才知道。
