### ISSUE TITLE
推理速度太慢

### ISSUE THREAD

**Issue by McCarrtney** [ymcui/Chinese-LLaMA-Alpaca#506]
### 详细描述问题

无论是运行`inference_hf.py`还是`gradio_demo`，在使用Alpaca 13B的模型(未做量化)的时候推理速度非常慢，一个请求可能要三四十秒才能响应。在8卡A100上进行推理。有没有一些推理加速的方案？

#### 运行日志或截图

```
python scripts/gradio_demo.py \
	--base_model mypath \
        --tokenizer_path mypath \
        --gpus 0,1,2,3,4,5,6,7 \
```
统计运行时间，`model.generate`方法很多时候要50多秒：
<img width="165" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/83623643/dadd703f-d6bd-4d1a-85b5-1ae8a14e1681">

同时发现程序运行时显存占用并不高：
<img width="580" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/83623643/6adfc90f-f28e-4ea4-9734-007d217601cd">

### 必查项目

- [x] **基础模型**：Alpaca-Plus-13B
- [x] **运行系统**：Linux 
- [x] **问题分类**：模型推理问题（🤗 transformers）
- [x] **模型正确性检查**：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行。
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by iMountTai** [comment]
13B只是做推理的话用一张卡就好了，不然分配到八张卡串行推理，属实有点浪费且延长推理时间

**Comment by McCarrtney** [comment]
好的，谢谢。另外想请问一下，readme中的demo（mac m1上）的打字机模式的流式输出是如何实现的呀？我用Huggingface提供的streamer感觉最终的结果十分丑陋

**Comment by iMountTai** [comment]
可以使用[llama.cpp](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/llama.cpp%E9%87%8F%E5%8C%96%E9%83%A8%E7%BD%B2)

**Comment by sunyuhan19981208** [comment]
目前的多卡模式是model parallel的，model parallel的原理是将一个模型的层分别加载到多张卡上，所以实际上你加载到多张卡的效率还不如加载到一张卡上，后续做成tensor parallel肯定就快了
