### ISSUE TITLE
Lora模型合并前 和 合并后显存不一致

### ISSUE THREAD

**Issue by lucasjinreal** [ymcui/Chinese-LLaMA-Alpaca#508]
加载base model + lora
和 加载merge后的模型，后者总是会OOM，这可能是原因导致的呢？

合并后的模型体积貌似也没有增加，是正常的状态，那为何合并后推理会OOM

**Comment by lucasjinreal** [comment]
另外我发现如果用 `load_in_8bit` 设置为true，同时device_map 为 auto，模型输出的结果全是 eos，也就是说int8下无法推理，这是为何

**Comment by iMountTai** [comment]
不知，大佬是有魔改我们的代码吗？

**Comment by lucasjinreal** [comment]
我就改了一下 merge_and_unload 封装成了一个函数，比较奇怪，不过OOM仅仅限于我开启num_beams = 2 的时候，但是直接同事加载base模型 + lora，即便是beams是4也不会OOM，加载合并后的模型会直接再生成几个字之后OOM。

**Comment by iMountTai** [comment]
这种情况建议先运行最原始代码复现该问题，如果不能复现，则说明你的魔改有问题，如果能复现，我们也好尽快改进代码，目前没收到类似问题描述
