### ISSUE TITLE
win10的cmd输入不了中文吗？输入英文回答中文

### ISSUE THREAD

**Issue by wscsjnhboy** [ymcui/Chinese-LLaMA-Alpaca#51]
![image](https://user-images.githubusercontent.com/735855/229653360-1f6e9a80-d0b0-4e9f-88f7-3ba9e2dc04cd.png)

**Comment by ymcui** [comment]
看一下这个issue：https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/11

**Comment by wscsjnhboy** [comment]
> 

看了issue用wsl可以跑，不过配置低太卡。半天挤出一丢丢字。如下
![image](https://user-images.githubusercontent.com/735855/229750666-d51d89b8-1ae4-40db-86eb-8276646e0cdd.png)

**Comment by wscsjnhboy** [comment]
可以使用nodejs执行效率好很多，代码如下：
child_process = require('child_process')
child = child_process.spawn('D:\\proj\\llama.cpp-master\\bin\\main', [
    '-m', 'D:\\proj\\llama.cpp-master\\models\\zh-models\\7B\\ggml-model-q4_0.bin',
    '--color', '-f', 'D:\\proj\\llama.cpp-master\\prompts\\alpaca.txt', '-ins',
    '-c', '2048', '--temp', '0.2', '-n', '256', '--repeat_penalty', '1.3'])
child.stdout.pipe(process.stdout)
child.stdin.setEncoding('utf-8')
process.stdin.pipe(child.stdin)

![image](https://user-images.githubusercontent.com/735855/229761762-31578a31-b164-4bca-acf0-37e35631fda7.png)

**Comment by ymcui** [comment]
感谢提供方案，已添加到[FAQ#6](https://github.com/ymcui/Chinese-LLaMA-Alpaca#问题6windows下模型无法理解中文生成速度很慢等问题)。

**Comment by appleatiger** [comment]
https://github.com/josStorer/llama.cpp-unicode-windows   这个项目解决了windows中文输入问题

**Comment by shiningxy** [comment]
`llama.cpp`项目下没有`\bin\main`目录 @ymcui @wscsjnhboy 

llama.cpp项目版本 `git checkout 42747220b4cac548b6e3059b66b3e960b517cfa4`

`node console.js`报错

`console.js`内容为

```
child_process = require('child_process')
child = child_process.spawn('../llama.cpp/', [
'-m', '../llama.cpp/zh-models/7B/ggml-model-q4_0.bin',
'--color', '-f', '../llama.cpp/prompts/alpaca.txt', '-ins',
'-c', '2048', '--temp', '0.2', '-n', '256', '--repeat_penalty', '1.3'])
child.stdout.pipe(process.stdout)
child.stdin.setEncoding('utf-8')
process.stdin.pipe(child.stdin)
```

报错内容如下

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn ../llama.cpp/ EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn ../llama.cpp/',
  path: '../llama.cpp/',
  spawnargs: [
    '-m',
    '../llama.cpp/zh-models/7B/ggml-model-q4_0.bin',
    '--color',
    '-f',
    '../llama.cpp/prompts/alpaca.txt',
    '-ins',
    '-c',
    '2048',
    '--temp',
    '0.2',
    '-n',
    '256',
    '--repeat_penalty',
    '1.3'
  ]
}

Node.js v18.16.0
```

系统版本`Ubuntu 20.04.1`

在llama.cpp执行过`make`命令：

```
I llama.cpp build info: 
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wno-unused-function -pthread -march=native -mtune=native
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native
I LDFLAGS:  
I CC:       cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
I CXX:      g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

make: Nothing to be done for 'default'.
```

请教这可能是llama.cpp目录中缺少/bin/main/目录的缘故吗？或是其他原因导致的？

**Comment by shiningxy** [comment]
#106 此外，这个issue中 @YukinoshitaKaren 尝试了本issue中的方法，速度仍然较慢，我认为过早地Closed本issue。

**Comment by YulongXia** [comment]
我的系统是Linux debian 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64
在使用llama.cpp量化了模型，得到zh-models/7B/ggml-model-q4_0.bin

**Comment by GuoHuiChen** [comment]
经查，的确减少线程数量，有助于提高性能。增加参数： -t 4
