### ISSUE TITLE
扩充pad_id相关问题

### ISSUE THREAD

**Issue by gavin1332** [ymcui/Chinese-LLaMA-Alpaca#510]
### 详细描述问题

需求：二次预训练转指令微调过程中扩充pad_id

问题：以下几处关于pad id和词表的信息互相矛盾：

- LLaMA-Plus和Alpaca-Plus合并模型的config.json中"pad_token_id": 0，LlamaConfig打印出的pad_token_id也为0；
- [issue-453](https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/453#issuecomment-1567895100)建议通过resize_token_embeddings扩充embedding，但该方法[只能在embedding尾部扩展](https://huggingface.co/docs/transformers/main_classes/model#transformers.PreTrainedModel.resize_token_embeddings)，意味着pad_token_id=49952，词表大小为49953；
- 实际打印tokenizer.pad_token_id为49953，词表大小为49954；

1. 这三处pad id或vocabulary size大小之间的矛盾怎么理解？
2. 为什么不复用llama模型中0号id为pad id呢？

### 必查项目

*将[ ]中填入x，表示打对钩。提问时删除这行。 前三项请按自己的问题类型保留符合的选项。*

- [x] **问题分类**：模型转换和合并
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案

**Comment by airaria** [comment]
1. 添加pad id后pad_token_id=49953，词表大小49954，pad_token_id以tokenizer中的配置为准.
2. issue 453的流程和pad id的描述没有矛盾，建议再仔细看看。
3. 原版llama中0的位置对应unk，所以添加了单独的pad token而没复用0

**Comment by gavin1332** [comment]
感谢及时作答，先按照您的建议推进。暂时关闭issue，后续有新问题再开issue讨论。
