### ISSUE TITLE
关于训练预训练-第二阶段的参数设置问题，希望获得确认

### ISSUE THREAD

**Issue by csyourui** [ymcui/Chinese-LLaMA-Alpaca#511]
### 详细描述问题

在 [训练细节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E8%AE%AD%E7%BB%83%E7%BB%86%E8%8A%82) 中我注意到你们的预训练第二阶段和指令微调阶段设置的`Batch Size`分别为**1024**，**512**。按照我的理解，这意味着 `per_device_train_batch_size` 要分别设置为，1024/16=**64** 和 512/16=**32**，请问实际是这样的吗？

### 必查项目

- [x] **问题分类**：其他问题
- [x] **模型正确性检查**：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行。
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by airaria** [comment]
`per_device_train_batch_size * gradient_accumulation_steps * n_gpus = total_batch_size`

**Comment by csyourui** [comment]
thanks~
