### ISSUE TITLE
只进行某领域知识的扩充问题

### ISSUE THREAD

**Issue by henryGao9** [ymcui/Chinese-LLaMA-Alpaca#512]
### 详细描述问题
作者您好，请教一下，如果只是想对单独领域知识进行扩充回答的话，必须要先进行预训练再进行精调，还是只是需要精调不需要预训练就可以了？还有就是此项目有没有交流群提供问题交流。再次先感谢！

*请尽量具体地描述您遇到的问题，**必要时给出运行命令**。这将有助于我们更快速地定位问题所在。*

#### 依赖情况（代码类问题务必提供）

*请提供transformers, peft, torch等常规依赖库的版本：pip list \| grep*

#### 运行日志或截图

*请提供文本log、运行截图*

### 必查项目

*将[ ]中填入x，表示打对钩。提问时删除这行。 前三项请按自己的问题类型保留符合的选项。*

- [ ] **基础模型**：LLaMA / Alpaca / LLaMA-Plus / Alpaca-Plus（同时说明模型大小：7B/13B/33B）
- [ ] **运行系统**：Windows / MacOS / Linux 
- [ ] **问题分类**：下载问题 / 模型转换和合并 / 模型训练与精调 / 模型推理问题（🤗 transformers） / 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat） / 效果问题 / 其他问题
- [ ] **模型正确性检查**：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行。
- [ ] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [ ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by airaria** [comment]
预训练提供了中文能力的底座；
只是想对单独领域知识进行扩充回答的话，在Chinese-LLaMA的基础上，只精调就可以了

**Comment by henryGao9** [comment]
> 预训练提供了中文能力的底座； 只是想对单独领域知识进行扩充回答的话，在Chinese-LLaMA的基础上，只精调就可以了

感谢您的回复，那我重点在精调这一块进行研究和学习。
