### ISSUE TITLE
预训练阶段7b、13b所需要的资源及训练时间

### ISSUE THREAD

**Issue by xiaozhu1106** [ymcui/Chinese-LLaMA-Alpaca#514]
### 详细描述问题
问题一：请教一下，预训练阶段7b、13b所需要的资源及训练时间？
我看在其他issue中有提到：“在LoRA预训练阶段，用16张A100卡batch_size=1024大约6h可以训练1K步。其他算力的情况可以自行估算。“
请问，这个是指的7b还是13b呢？  
我想分别了解一下，7b和13b具体的训练资源信息：卡数、显存大小、数据量（大小或者条数）、耗时

问题二：如果想预训练最大长度1024的，资源数及训练时间有相关参考吗？

**Comment by iMountTai** [comment]
我们未做相应统计。但是预训练、微调代码已开源，可以以手头资源预估一下时间及资源需求。
