### ISSUE TITLE
让模型基于私有知识回答问题应该怎样做？

### ISSUE THREAD

**Issue by mayi203** [ymcui/Chinese-LLaMA-Alpaca#519]
我想让模型基于我的私有数据回答问题。请问应该是怎样的流程？
1. 指令精调
2. 预训练+指令精调
3. 直接外部向量库
应该是哪种最合适。私有数据大多是一些 markdown 文档。

**Comment by ymcui** [comment]
不能一概而论，你需要根据数据量和数据领域进行权衡。
通常来说数据量不多的时候，你可以考虑langchain或者privateGPT这类方式，无需对模型重新训练。
数据量多的话可能就需要训练了，具体是pt+sft还是只做sft需要自己实验。

**Comment by mayi203** [comment]
不太理解 pt ，sft 的本质区别。如果仅 sft ，模型会学到并运用我的私有知识进行回答么？

**Comment by ymcui** [comment]
哪一种都可以学习额外知识，前面已经讲过这取决于你的数据。如果你没有标注数据就只能做pretrain。

**Comment by mayi203** [comment]
感谢！我再学习一下
