### ISSUE TITLE
请问如何实现chat的形式

### ISSUE THREAD

**Issue by creamiracle** [ymcui/Chinese-LLaMA-Alpaca#52]
您好，感谢分享，想问一下如何实现连续问答呢？
是通过每次把上一次的输入和输出都加入到下一次的输入中么？
谢谢

**Comment by ymcui** [comment]
不需要的，`./main -ins`命令就是开启交互模式，可以直接像ChatGPT一样聊天，不用手动复制。

**Comment by creamiracle** [comment]
> 不需要的，`./main -ins`命令就是开启交互模式，可以直接像ChatGPT一样聊天，不用手动复制。

您好，我的意思是，如果基于一个自己微调的llama模型，怎么做成chat的形式呢，我现在每次都是用generate去生成，没办法联系上一次的回答，大概是这个意思。
谢谢

**Comment by ymcui** [comment]
我们目前的训练和测试都仅限于单轮。
只在最后Q4量化后利用llama.cpp测试过多轮能力（也可以加载FP16的ggml模型）。
