### ISSUE TITLE
fp16和bf16

### ISSUE THREAD

**Issue by jiangix-paper** [ymcui/Chinese-LLaMA-Alpaca#524]
### 详细描述问题

您好，非常棒的工作。有个问题是关于精度问题，我看vicuna在微调的时候用的是bf16和tf32，而您这边预训练是用的fp16，我理解微调和预训练应该和精度无关，请问您这边用fp16，不用bf16的原因是什么呢？如果使用fp16预训练后的模型再采用vicuna那种bf16进行微调，会有问题吗？非常感谢

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/62198809/fe471f4b-6d66-4669-8bc2-3de3f61df446)

### 参考信息
https://github.com/lm-sys/FastChat

**Comment by airaria** [comment]
对fp16比较熟悉，没有特殊原因。也比较过不同的数据类型，没有观察到显著的差异。

 > 如果使用fp16预训练后的模型再采用vicuna那种bf16进行微调，会有问题吗？

没有测试过，直觉上不会有问题。您可以尝试。

**Comment by jiangix-paper** [comment]
好的，非常感谢
