### ISSUE TITLE
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 819402384, available 805306368)

### ISSUE THREAD

**Issue by jianjian0dandan** [ymcui/Chinese-LLaMA-Alpaca#526]
使用[llama.cpp](https://github.com/ggerganov/llama.cp)的方式运行的时候，长度超过一定范围，比如：生成一个pytorch的随机向量,维度是2,5    就会报错：ggml_new_tensor_impl: not enough space in the context's memory pool (needed 819402384, available 805306368)   
小于这个长度可以运行，看电脑没有被打满，就停止了，请问要怎么做

**Comment by ymcui** [comment]
尝试减小`-b`，比如`-b 24`。

**Comment by jianjian0dandan** [comment]
可以了，多谢~
