### ISSUE TITLE
重构后的模型SHA256校验失败

### ISSUE THREAD

**Issue by Eachan35** [ymcui/Chinese-LLaMA-Alpaca#528]
### 详细描述问题

Step1,2中的SHA256全部校验过符合的，但是重构后的模型对不上。 
随后使用了Colab的指令得到的SHA256与手动的一致：77f84a38eb88cbf81706473b206fd88a6c007a3a44989d38c5c6d3868585807e 
正确的为：Chinese-Alpaca-Plus-7B | 8b8f6551d0d83f93e378622b9f8dad0bec189da6c29d8a78de493e6aee9bd35f 
请大佬帮忙看看是哪里出了问题？

### 参考信息

且运行scripts/gradio_demo.py发现输出结果与[解码示例](https://github.com/ymcui/Chinese-LLaMA-Alpaca/tree/main/examples/q8_13b-p7b-p13b/DIALOGUE.md)有较大出入
启动命令：python3 scripts/gradio_demo.py --base_model=model/chinese_alpaca_plus_7b_bin --gpus=2,3 
<img width="1015" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/45940937/3092f2f4-ca49-43de-b506-7b345f88ca26">

#### 依赖情况（代码类问题务必提供）

pip list | grep -E "transformers|peft|torch|sentencepiece"
peft                     0.3.0
sentencepiece            0.1.97
torch                    1.13.1
torchaudio               0.13.1
torchcrepe               0.0.19
transformers             4.28.1

#### 运行日志或截图
(aigc) [root@localhost Chinese-LLaMA-Alpaca]# python3 scripts/merge_llama_with_chinese_lora.py \
    --base_model decapoda-research/llama-7b-hf \
    --lora_model ziqingyang/chinese-llama-plus-lora-7b,ziqingyang/chinese-alpaca-plus-lora-7b \
    --output_type pth \
    --output_dir alpaca-combined 

>Base model: decapoda-research/llama-7b-hf
LoRA model(s) ['ziqingyang/chinese-llama-plus-lora-7b', 'ziqingyang/chinese-alpaca-plus-lora-7b']:
Downloading (…)lve/main/config.json: 100%|███████████████| 427/427 [00:00<00:00, 1.55MB/s]
Downloading (…)model.bin.index.json: 100%|███████████| 25.5k/25.5k [00:00<00:00, 5.16MB/s]
Downloading (…)l-00001-of-00033.bin: 100%|█████████████| 405M/405M [00:11<00:00, 34.8MB/s]
Downloading (…)l-00002-of-00033.bin: 100%|█████████████| 405M/405M [00:09<00:00, 43.2MB/s]
Downloading (…)l-00003-of-00033.bin: 100%|█████████████| 405M/405M [00:09<00:00, 41.2MB/s]
Downloading (…)l-00004-of-00033.bin: 100%|█████████████| 405M/405M [00:10<00:00, 39.1MB/s]
Downloading (…)l-00005-of-00033.bin: 100%|█████████████| 405M/405M [00:09<00:00, 42.9MB/s]
Downloading (…)l-00006-of-00033.bin: 100%|█████████████| 405M/405M [00:10<00:00, 38.7MB/s]
Downloading (…)l-00007-of-00033.bin: 100%|█████████████| 405M/405M [00:12<00:00, 32.3MB/s]
Downloading (…)l-00008-of-00033.bin: 100%|█████████████| 405M/405M [00:23<00:00, 17.6MB/s]
Downloading (…)l-00009-of-00033.bin: 100%|█████████████| 405M/405M [00:09<00:00, 42.2MB/s]
Downloading (…)l-00010-of-00033.bin: 100%|█████████████| 405M/405M [00:07<00:00, 55.1MB/s]
Downloading (…)l-00011-of-00033.bin: 100%|█████████████| 405M/405M [00:07<00:00, 56.5MB/s]
Downloading (…)l-00012-of-00033.bin: 100%|█████████████| 405M/405M [00:08<00:00, 45.9MB/s]
Downloading (…)l-00013-of-00033.bin: 100%|█████████████| 405M/405M [00:09<00:00, 43.2MB/s]
Downloading (…)l-00014-of-00033.bin: 100%|█████████████| 405M/405M [00:09<00:00, 44.8MB/s]
Downloading (…)l-00015-of-00033.bin: 100%|█████████████| 405M/405M [00:19<00:00, 20.5MB/s]
Downloading (…)l-00016-of-00033.bin: 100%|█████████████| 405M/405M [00:09<00:00, 44.9MB/s]
Downloading (…)l-00017-of-00033.bin: 100%|█████████████| 405M/405M [00:13<00:00, 30.7MB/s]
Downloading (…)l-00018-of-00033.bin: 100%|█████████████| 405M/405M [00:09<00:00, 41.0MB/s]
Downloading (…)l-00019-of-00033.bin: 100%|█████████████| 405M/405M [00:13<00:00, 30.8MB/s]
Downloading (…)l-00020-of-00033.bin: 100%|█████████████| 405M/405M [00:08<00:00, 46.9MB/s]
Downloading (…)l-00021-of-00033.bin: 100%|█████████████| 405M/405M [00:09<00:00, 42.4MB/s]
Downloading (…)l-00022-of-00033.bin: 100%|█████████████| 405M/405M [00:10<00:00, 40.0MB/s]
Downloading (…)l-00023-of-00033.bin: 100%|█████████████| 405M/405M [00:10<00:00, 39.1MB/s]
Downloading (…)l-00024-of-00033.bin: 100%|█████████████| 405M/405M [00:09<00:00, 41.3MB/s]
Downloading (…)l-00025-of-00033.bin: 100%|█████████████| 405M/405M [00:08<00:00, 45.9MB/s]
Downloading (…)l-00026-of-00033.bin: 100%|█████████████| 405M/405M [00:09<00:00, 41.6MB/s]
Downloading (…)l-00027-of-00033.bin: 100%|█████████████| 405M/405M [00:21<00:00, 19.1MB/s]
Downloading (…)l-00028-of-00033.bin: 100%|█████████████| 405M/405M [00:10<00:00, 40.1MB/s]
Downloading (…)l-00029-of-00033.bin: 100%|█████████████| 405M/405M [00:22<00:00, 17.7MB/s]
Downloading (…)l-00030-of-00033.bin: 100%|█████████████| 405M/405M [00:11<00:00, 34.3MB/s]
Downloading (…)l-00031-of-00033.bin: 100%|█████████████| 405M/405M [00:09<00:00, 43.4MB/s]
Downloading (…)l-00032-of-00033.bin: 100%|█████████████| 405M/405M [00:10<00:00, 39.9MB/s]
Downloading (…)l-00033-of-00033.bin: 100%|█████████████| 524M/524M [00:14<00:00, 37.0MB/s]
Downloading shards: 100%|█████████████████████████████████| 33/33 [06:41<00:00, 12.16s/it]
Loading checkpoint shards: 100%|██████████████████████████| 33/33 [00:10<00:00,  3.16it/s]
Downloading (…)neration_config.json: 100%|████████████████| 124/124 [00:00<00:00, 445kB/s]
Peft version: 0.3.0
Loading LoRA for 7B model
Loading LoRA ziqingyang/chinese-llama-plus-lora-7b...
Downloading tokenizer.model: 100%|█████████████████████| 758k/758k [00:00<00:00, 55.1MB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████████| 72.0/72.0 [00:00<00:00, 271kB/s]
Downloading (…)okenizer_config.json: 100%|████████████████| 166/166 [00:00<00:00, 605kB/s]
base_model vocab size: 32000
tokenizer vocab size: 49953
Extended vocabulary size to 49953
Loading LoRA weights
Downloading (…)/adapter_config.json: 100%|███████████████| 420/420 [00:00<00:00, 1.47MB/s]
Downloading adapter_model.bin: 100%|███████████████████| 858M/858M [00:37<00:00, 22.8MB/s]
Merging with merge_and_unload...
Loading LoRA ziqingyang/chinese-alpaca-plus-lora-7b...
Downloading tokenizer.model: 100%|█████████████████████| 758k/758k [00:00<00:00, 1.06MB/s]
Downloading (…)cial_tokens_map.json: 100%|██████████████| 96.0/96.0 [00:00<00:00, 439kB/s]
Downloading (…)okenizer_config.json: 100%|████████████████| 166/166 [00:00<00:00, 743kB/s]
base_model vocab size: 49953
tokenizer vocab size: 49954
Extended vocabulary size to 49954
Loading LoRA weights
Downloading (…)/adapter_config.json: 100%|███████████████| 423/423 [00:00<00:00, 1.39MB/s]
Downloading adapter_model.bin: 100%|█████████████████| 1.14G/1.14G [00:42<00:00, 26.5MB/s]
Merging with merge_and_unload...
Saving to pth format...
Saving shard 1 of 1 into alpaca-combined/consolidated.00.pth 

(aigc) [root@localhost Chinese-LLaMA-Alpaca]# sha256sum alpaca-combined/consolidated.00.pth 

>77f84a38eb88cbf81706473b206fd88a6c007a3a44989d38c5c6d3868585807e  alpaca-combined/consolidated.00.pth

### 必查项目

- [x] **基础模型**：Alpaca-Plus-7B
- [x] **运行系统**：Linux 
- [x] **问题分类**：模型转换和合并
- [ ] **模型正确性检查**：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行。
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by ymcui** [comment]
解码示例里给的是llama.cpp运行的结果。建议你试试llama.cpp解码的结果。
另外，SHA256是以原版llama权重为基础进行转换得到的，第三方的权重可能会因为meta信息等因素导致模型权重发生改变（实际权重可能并没有什么变化）。

**Comment by ymcui** [comment]
用llama.cpp转换为f16的ggml格式能够降低因为上述原因带来的模型差异（但也不绝对），你也可以比对一下以下sha256sum（Alpaca-Plus-7B）：
```
ff1b113ff835516e475363b019a2c7a7c63f27abbe56c89aad3ec18c1bbf53db ggml-model-f16.bin
```
