### ISSUE TITLE
合并模型的时候报错

### ISSUE THREAD

**Issue by Log4J-Ops** [ymcui/Chinese-LLaMA-Alpaca#53]
执行合并的时候报错ValueError: weight is on the meta device, we need a `value` to put in on cpu.，请问这个应该怎么更正

**Comment by whu-feiyang** [comment]
+1，同样是这个问题，看网上的教程无法解决

**Comment by williamzhu1980** [comment]
+1，合并7B没有问题，合并13B报这个错。

**Comment by caixianji** [comment]
我也遇到相同问题，各位大佬都解决了么

**Comment by quanzhang2020** [comment]
+1

**Comment by Log4J-Ops** [comment]
使用大佬最新版的colab在线版合并教程一下子就合并好了，还方便，本地总是莫名其妙的环境问题
