### ISSUE TITLE
33B和65B的中文加强版什么时候也可以开源一版呀

### ISSUE THREAD

**Issue by zhangfan-algo** [ymcui/Chinese-LLaMA-Alpaca#531]
用中文加强版的13B LLaMa 和Alpaca在自己的数据集上微调，效果还不错。很期待33B和65B开源中文加强版的到来。尤其是65B版的，在中文领域应该可以霸榜第一名，很期待博主更新一版更大参数量的中文模型

**Comment by ymcui** [comment]
感谢支持。33B基础版很快就会和大家见面。其余版本也在筹划中。

**Comment by zhangxinxin0428** [comment]
> 用中文加强版的13B LLaMa 和Alpaca在自己的数据集上微调，效果还不错。很期待33B和65B开源中文加强版的到来。尤其是65B版的，在中文领域应该可以霸榜第一名，很期待博主更新一版更大参数量的中文模型

请问楼主的数据集是通用的还是垂域的？

**Comment by AceyKubbo** [comment]
大佬能预告下33B要什么硬件条件不

**Comment by tanguofu** [comment]
可以分享 finetune33b 所需的硬件条件么？

**Comment by AceyKubbo** [comment]
> 感谢支持。33B基础版很快就会和大家见面。其余版本也在筹划中。
大佬能预告下33B要什么硬件条件不

**Comment by ymcui** [comment]
> > 感谢支持。33B基础版很快就会和大家见面。其余版本也在筹划中。
> 
> 大佬能预告下33B要什么硬件条件不

llama.cpp的4比特推理理论上需要18G左右内存（小于这个其实也可以跑起来，有offload机制）。
主要瓶颈在于前面的模型合并，峰值需要70G左右的内存。
训练方面建议考虑8比特或者4比特训练，这个量级的模型已经开始吃设备了。

**Comment by AceyKubbo** [comment]
> > > 感谢支持。33B基础版很快就会和大家见面。其余版本也在筹划中。
> > 
> > 
> > 大佬能预告下33B要什么硬件条件不
> 
> llama.cpp的4比特推理理论上需要18G左右内存（小于这个其实也可以跑起来，有offload机制）。 主要瓶颈在于前面的模型合并，峰值需要70G左右的内存。 训练方面建议考虑8比特或者4比特训练，这个量级的模型已经开始吃设备了。

感谢指点

**Comment by zhangfan-algo** [comment]
> 

老哥 期待65B 一定是最强中文语言模型

**Comment by boogunote** [comment]
> > > 感谢支持。33B基础版很快就会和大家见面。其余版本也在筹划中。
> > 
> > 
> > 大佬能预告下33B要什么硬件条件不
> 
> llama.cpp的4比特推理理论上需要18G左右内存（小于这个其实也可以跑起来，有offload机制）。 主要瓶颈在于前面的模型合并，峰值需要70G左右的内存。 训练方面建议考虑8比特或者4比特训练，这个量级的模型已经开始吃设备了。

请问一下 4bit 65B 模型合并的时候峰值内存是多少。128G内存能扛的住不。

**Comment by ymcui** [comment]
> > > > 感谢支持。33B基础版很快就会和大家见面。其余版本也在筹划中。
> > > 
> > > 
> > > 大佬能预告下33B要什么硬件条件不
> > 
> > 
> > llama.cpp的4比特推理理论上需要18G左右内存（小于这个其实也可以跑起来，有offload机制）。 主要瓶颈在于前面的模型合并，峰值需要70G左右的内存。 训练方面建议考虑8比特或者4比特训练，这个量级的模型已经开始吃设备了。
> 
> 请问一下 4bit 65B 模型合并的时候峰值内存是多少。128G内存能扛的住不。

@boogunote 65B纯权重已经120G了，加上offload的话可能勉强可以。

**Comment by jeff31415** [comment]
> 感谢支持。33B基础版很快就会和大家见面。其余版本也在筹划中。

对了，近期我也看到有一个open llama项目（复现llama，以apache-2.0协议发布权重），目前有7b和13b的权重。或许可以在此基础上训练，来获得一个真正开源的中文模型？

**Comment by zhangfan-algo** [comment]
> 

自己的数据集 不是通用的
