### ISSUE TITLE
The device_map provided does not give any device for the following parameters

### ISSUE THREAD

**Issue by sssdjj** [ymcui/Chinese-LLaMA-Alpaca#532]
合并的 chinese-alpaca-plus-13B 加载时，多卡提示 这个错误
The device_map provided does not give any device for the following parameters
还打印了一些层的参数名称

**Comment by JuneYaooo** [comment]
same here

**Comment by iMountTai** [comment]
@sssdjj @JuneYaooo 参考issue模板重新描述一下问题，就一句报错内容都不知道是什么代码出的错
