### ISSUE TITLE
关于中英文混合训练的问题

### ISSUE THREAD

**Issue by chyyf006** [ymcui/Chinese-LLaMA-Alpaca#535]
感谢项目发起者、各位贡献者、爱好者一直以来的指导！
在做垂直行业数据预训练的过程中，有大量的中英文数据，英文预计10GB，中文预计：5GB，训练过程如下：
1、LLAMA-HF与chinese_llama_plus_lora_7b合并得到[A]
2、在[A]的基础上进行数据训练，数据包括纯中文数据、纯英文数据，去掉embed_tokens、lm_head（时间太长，需要近7000小时，4张3090），同时采用多轮方式进行训练，去掉步长参数，大概接近2周的时间，得到[B]
补充：在训练结束时，loss：0.5-0.8，learning-rate：0.0002「在后面的一天多时间里，learning-rate一直是这个数值」
3、基于[A]将[B]与chinese_alpaca_plus_lora_7b进行合并，得到[C]
4、基于[C]运行llama.cpp进行问答
按照上述步骤，对最终模型使用，出现以下情况：
1、目前回答问题有中英文混答的情况，一段中文后，后面跟中文，或者直接英文回答
2、回答顺序颠倒，如训练数据中，优先级：A：初级、B：中级、C：高级，答案给的是倒序的，优先级：C：初级、B：中级、A：高级；
3、同样的数据，存在两个问题的阐述，一个问题完全正确，另一个问题无法回答或者部分错误；
4、这个训练过程不知道是不是适合我的场景，我之前用一个关键词做的中文数据，29篇文章，341K，采用上述步骤，问题及答案在ChatGPT中评分为90分，专业人士评估训练后的答案甚至比ChatGPT更为准确，只是回答措辞些许不准确，这可能跟使用7B有关，使用未训练的模型给出的答案ChatGPT只给出了10分。
请教一下，上述情况是不是与中英文混合训练有关系？采用中英文分开训练是不是能够解决上述问题？
另外，我的训练过程是否适合我的需求场景？

- [x ] **基础模型**：LLaMA-Plus  / Alpaca-Plus 7B
- [x ] **运行系统**：ubuntu
- [x ] **问题分类**： 模型训练与精调 
- [x ] **模型正确性检查**：已检查
- [x ] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by moseshu** [comment]
> 感谢项目发起者、各位贡献者、爱好者一直以来的指导！ 在做垂直行业数据预训练的过程中，有大量的中英文数据，英文预计10GB，中文预计：5GB，训练过程如下： 1、LLAMA-HF与chinese_llama_plus_lora_7b合并得到[A] 2、在[A]的基础上进行数据训练，数据包括纯中文数据、纯英文数据，去掉embed_tokens、lm_head（时间太长，需要近7000小时，4张3090），同时采用多轮方式进行训练，去掉步长参数，大概接近2周的时间，得到[B] 补充：在训练结束时，loss：0.5-0.8，learning-rate：0.0002「在后面的一天多时间里，learning-rate一直是这个数值」 3、基于[A]将[B]与chinese_alpaca_plus_lora_7b进行合并，得到[C] 4、基于[C]运行llama.cpp进行问答 按照上述步骤，对最终模型使用，出现以下情况： 1、目前回答问题有中英文混答的情况，一段中文后，后面跟中文，或者直接英文回答 2、回答顺序颠倒，如训练数据中，优先级：A：初级、B：中级、C：高级，答案给的是倒序的，优先级：C：初级、B：中级、A：高级； 3、同样的数据，存在两个问题的阐述，一个问题完全正确，另一个问题无法回答或者部分错误； 4、这个训练过程不知道是不是适合我的场景，我之前用一个关键词做的中文数据，29篇文章，341K，采用上述步骤，问题及答案在ChatGPT中评分为90分，专业人士评估训练后的答案甚至比ChatGPT更为准确，只是回答措辞些许不准确，这可能跟使用7B有关，使用未训练的模型给出的答案ChatGPT只给出了10分。 请教一下，上述情况是不是与中英文混合训练有关系？采用中英文分开训练是不是能够解决上述问题？ 另外，我的训练过程是否适合我的需求场景？
> 
> * [x ] **基础模型**：LLaMA-Plus  / Alpaca-Plus 7B
> * [x ] **运行系统**：ubuntu
> * [x ] **问题分类**： 模型训练与精调
> * [x ] **模型正确性检查**：已检查
> * [x ] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
> * [x ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
> * [x ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

我建议放在一起训练会更好点，如果分开训练，比如先训练中文，后训练英文，后来的训练会修改之前的权重，反而会让模型遗忘之前的能力，还有一点就是模型的泛化性还是不够好。需要多样化的数据来一起训练。我也遇到了你提到的问题，我是把8个任务放一起训练

**Comment by chyyf006** [comment]
> > 感谢项目发起者、各位贡献者、爱好者一直以来的指导！ 在做垂直行业数据预训练的过程中，有大量的中英文数据，英文预计10GB，中文预计：5GB，训练过程如下： 1、LLAMA-HF与chinese_llama_plus_lora_7b合并得到[A] 2、在[A]的基础上进行数据训练，数据包括纯中文数据、纯英文数据，去掉embed_tokens、lm_head（时间太长，需要近7000小时，4张3090），同时采用多轮方式进行训练，去掉步长参数，大概接近2周的时间，得到[B] 补充：在训练结束时，loss：0.5-0.8，learning-rate：0.0002「在后面的一天多时间里，learning-rate一直是这个数值」 3、基于[A]将[B]与chinese_alpaca_plus_lora_7b进行合并，得到[C] 4、基于[C]运行llama.cpp进行问答 按照上述步骤，对最终模型使用，出现以下情况： 1、目前回答问题有中英文混答的情况，一段中文后，后面跟中文，或者直接英文回答 2、回答顺序颠倒，如训练数据中，优先级：A：初级、B：中级、C：高级，答案给的是倒序的，优先级：C：初级、B：中级、A：高级； 3、同样的数据，存在两个问题的阐述，一个问题完全正确，另一个问题无法回答或者部分错误； 4、这个训练过程不知道是不是适合我的场景，我之前用一个关键词做的中文数据，29篇文章，341K，采用上述步骤，问题及答案在ChatGPT中评分为90分，专业人士评估训练后的答案甚至比ChatGPT更为准确，只是回答措辞些许不准确，这可能跟使用7B有关，使用未训练的模型给出的答案ChatGPT只给出了10分。 请教一下，上述情况是不是与中英文混合训练有关系？采用中英文分开训练是不是能够解决上述问题？ 另外，我的训练过程是否适合我的需求场景？
> > 
> > * [x ] **基础模型**：LLaMA-Plus  / Alpaca-Plus 7B
> > * [x ] **运行系统**：ubuntu
> > * [x ] **问题分类**： 模型训练与精调
> > * [x ] **模型正确性检查**：已检查
> > * [x ] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
> > * [x ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
> > * [x ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
> 
> 我建议放在一起训练会更好点，如果分开训练，比如先训练中文，后训练英文，后来的训练会修改之前的权重，反而会让模型遗忘之前的能力，还有一点就是模型的泛化性还是不够好。需要多样化的数据来一起训练。我也遇到了你提到的问题，我是把8个任务放一起训练

感谢您的回复！
您遇到我提到的状况了吗？
您有什么处理方案吗？
谢谢！

**Comment by moseshu** [comment]
> > > 感谢项目发起者、各位贡献者、爱好者一直以来的指导！ 在做垂直行业数据预训练的过程中，有大量的中英文数据，英文预计10GB，中文预计：5GB，训练过程如下： 1、LLAMA-HF与chinese_llama_plus_lora_7b合并得到[A] 2、在[A]的基础上进行数据训练，数据包括纯中文数据、纯英文数据，去掉embed_tokens、lm_head（时间太长，需要近7000小时，4张3090），同时采用多轮方式进行训练，去掉步长参数，大概接近2周的时间，得到[B] 补充：在训练结束时，loss：0.5-0.8，learning-rate：0.0002「在后面的一天多时间里，learning-rate一直是这个数值」 3、基于[A]将[B]与chinese_alpaca_plus_lora_7b进行合并，得到[C] 4、基于[C]运行llama.cpp进行问答 按照上述步骤，对最终模型使用，出现以下情况： 1、目前回答问题有中英文混答的情况，一段中文后，后面跟中文，或者直接英文回答 2、回答顺序颠倒，如训练数据中，优先级：A：初级、B：中级、C：高级，答案给的是倒序的，优先级：C：初级、B：中级、A：高级； 3、同样的数据，存在两个问题的阐述，一个问题完全正确，另一个问题无法回答或者部分错误； 4、这个训练过程不知道是不是适合我的场景，我之前用一个关键词做的中文数据，29篇文章，341K，采用上述步骤，问题及答案在ChatGPT中评分为90分，专业人士评估训练后的答案甚至比ChatGPT更为准确，只是回答措辞些许不准确，这可能跟使用7B有关，使用未训练的模型给出的答案ChatGPT只给出了10分。 请教一下，上述情况是不是与中英文混合训练有关系？采用中英文分开训练是不是能够解决上述问题？ 另外，我的训练过程是否适合我的需求场景？
> > > 
> > > * [x ] **基础模型**：LLaMA-Plus  / Alpaca-Plus 7B
> > > * [x ] **运行系统**：ubuntu
> > > * [x ] **问题分类**： 模型训练与精调
> > > * [x ] **模型正确性检查**：已检查
> > > * [x ] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
> > > * [x ] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
> > > * [x ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
> > 
> > 
> > 我建议放在一起训练会更好点，如果分开训练，比如先训练中文，后训练英文，后来的训练会修改之前的权重，反而会让模型遗忘之前的能力，还有一点就是模型的泛化性还是不够好。需要多样化的数据来一起训练。我也遇到了你提到的问题，我是把8个任务放一起训练
> 
> 感谢您的回复！ 您遇到我提到的状况了吗？ 您有什么处理方案吗？ 谢谢！

我现在是把所有的数据放在一起训练，尽量扩大数据量以及数据的多样化，提高泛化能力
