### ISSUE TITLE
目前更多有名的模型都是从Vicuna一派过来，你们这里会继续出这条模型路线吗？

### ISSUE THREAD

**Issue by apachemycat** [ymcui/Chinese-LLaMA-Alpaca#537]
前些天，佰克利大学发布的开源模型排行榜，vicuna-13B排名第一，相关衍生模型很多，效果也确实不错。
本月，一位Youtube主播对Stable Vicuna进行了实测，Stable Vicuna在每一次测试中，都击败了前任王者Vicuna。所以这位Youtuber激动地喊出：Stable Vicuna就是目前最强大的 13B LLM模型，是当之无愧的LLM模型之王！
请问你们这里也会出这条路线的模型吗？

**Comment by moseshu** [comment]
> 前些天，佰克利大学发布的开源模型排行榜，vicuna-13B排名第一，相关衍生模型很多，效果也确实不错。 本月，一位Youtube主播对Stable Vicuna进行了实测，Stable Vicuna在每一次测试中，都击败了前任王者Vicuna。所以这位Youtuber激动地喊出：Stable Vicuna就是目前最强大的 13B LLM模型，是当之无愧的LLM模型之王！ 请问你们这里也会出这条路线的模型吗？

我觉得这个任务不冲突吧，可以使用这里的模型做vicuna训练的，词表都扩展好了

**Comment by irasin** [comment]
llama，alpaca，vicuna的模型结构都是一样的，仅仅式换一下数据，词表而已，感觉没有太过纠结模型路线的区别的必要性，重点还是数据

**Comment by skepsun** [comment]
其实主要是用不用sharegpt这样的多轮对话数据吧

**Comment by LiemLin** [comment]
> 前些天，佰克利大学发布的开源模型排行榜，vicuna-13B排名第一，相关衍生模型很多，效果也确实不错。
> 本月，一位Youtube主播对Stable Vicuna进行了实测，Stable Vicuna在每一次测试中，都击败了前任王者Vicuna。所以这位Youtuber激动地喊出：Stable Vicuna就是目前最强大的 13B LLM模型，是当之无愧的LLM模型之王！
> 请问你们这里也会出这条路线的模型吗？
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/b33f2a64-63fc-4caf-ba0d-6994b424701b)
你说的这个不是普通爱好者能玩的，带着功利性质的，其实也没什么错，只是与这里对比起来，格局小了，这里作为开源的社区已经非常不错了，惠及广大爱好者，真正推动中文AI的普及
