### ISSUE TITLE
合并33B的模型报错

### ISSUE THREAD

**Issue by zhouyanggang** [ymcui/Chinese-LLaMA-Alpaca#539]
### 详细描述问题
合并33B的模型，出现如下报错：

**Comment by zhouyanggang** [comment]
Merging with merge_and_unload...
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data01/zhouyg/Chinese-LLaMA-Alpaca-new/merge_llama_with_chinese_lora.py:327 in <module>         │
│                                                                                                  │
│   324 │   │   │   │   assert base_model_sd[original_key].dtype == torch.float16                  │
│   325 │   │                                                                                      │
│   326 │   │   # did we do anything?                                                              │
│ ❱ 327 │   │   assert not torch.allclose(first_weight_old, first_weight)                          │
│   328 │                                                                                          │
│   329 │   tokenizer.save_pretrained(output_dir)                                                  │
│   330                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError

**Comment by airaria** [comment]
信息太少。请按中文提问模板提供更多信息。

**Comment by zhouyanggang** [comment]
(torch2.0.0) [root@localhost Chinese-LLaMA-Alpaca-new]# python merge_llama_with_chinese_lora.py

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /root/anaconda3/envs/torch2.0.0/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/root/anaconda3/envs/torch2.0.0/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /root/anaconda3/envs/torch2.0.0 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 120
CUDA SETUP: Loading binary /root/anaconda3/envs/torch2.0.0/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120.so...
Base model: /data01/zhouyg/llama-33b-hf
LoRA model(s) ['chinese-llama-lora-33b', 'chinese-alpaca-lora-33b']:
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 61/61 [02:07<00:00,  2.08s/it]
Peft version: 0.3.0
Loading LoRA for 33B model
Loading LoRA chinese-llama-lora-33b...
base_model vocab size: 32000
tokenizer vocab size: 49953
Extended vocabulary size to 49953
Loading LoRA weights
Merging with merge_and_unload...
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data01/zhouyg/Chinese-LLaMA-Alpaca-new/merge_llama_with_chinese_lora.py:327 in <module>         │
│                                                                                                  │
│   324 │   │   │   │   assert base_model_sd[original_key].dtype == torch.float16                  │
│   325 │   │                                                                                      │
│   326 │   │   # did we do anything?                                                              │
│ ❱ 327 │   │   assert not torch.allclose(first_weight_old, first_weight)                          │
│   328 │                                                                                          │
│   329 │   tokenizer.save_pretrained(output_dir)                                                  │
│   330                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError



环境配置： torch==2.0.0 transformers==4.30.0.dev   peft==0.3.0 python 3.8
我在使用的时候，出现了assert错误，看了代码，想请问一下您，这个assert not torch.allclose的含义是什么？

**Comment by zhouyanggang** [comment]
我在把assert代码注掉的情况下，合并，是没有问题的，会生成合并后的模型，想问下这个合并后的模型可以用不？

**Comment by zhangfan-algo** [comment]
我刚刚都已经按照原来的逻辑合并成功了 两个33B的都没问题

**Comment by zhouyanggang** [comment]
不好意思，我搞错了，合并的时候按照plus方式合并，写了2个lora模型，感谢解答
