### ISSUE TITLE
tokenizer的special token和原版的区别

### ISSUE THREAD

**Issue by Porraio** [ymcui/Chinese-LLaMA-Alpaca#54]
你好，请问训练过程中用的special token是怎么样的呢。我看alpaca里，pad,bos,eos,unk都是\</s\>，你们训练的时候是用的\<unk\>,\<s\>,\</s\>,\<unk\>吗。感谢。

**Comment by airaria** [comment]
用到了<s>, <\s>和[PAD]三个special token
