### ISSUE TITLE
从checkpoint进行测试

### ISSUE THREAD

**Issue by Aida-yy** [ymcui/Chinese-LLaMA-Alpaca#541]
请问如何使用训练过程中某个checkpoint，单独拿出来做一些推理测试？

**Comment by airaria** [comment]
找到对应的ckpt文件（pytorch_model.bin)，然后按照[这里的说明](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/指令精调脚本#训练后文件整理)手动操作即可
