### ISSUE TITLE
关于客观效果评测的C-EVAL benchmark的LLaMA-13B的效果

### ISSUE THREAD

**Issue by caihaunqai** [ymcui/Chinese-LLaMA-Alpaca#543]
作者您好，感谢您的工作，我看到有关于C-EVAL benchmark的客观评测，请问有无原始LLaMA-13B的效果呢，希望看看是否有明确提升。谢谢！

**Comment by ymcui** [comment]
近期会更新相关技术报告，届时会更新完整结果和相关解读。
初步评测结果是Chinese-LLaMA相比原版英文LLaMA有提升但幅度不大，Chinese-Alpaca会显著提升该数据集上的效果。

**Comment by caihaunqai** [comment]
> 近期会更新相关技术报告，届时会更新完整结果和相关解读。 初步评测结果是Chinese-LLaMA相比原版英文LLaMA有提升但幅度不大，Chinese-Alpaca会显著提升该数据集上的效果。

谢谢，这是不是代表finetune后性能下降，但是增量预训练是有效的？

**Comment by ymcui** [comment]
没太明白你说的finetune后性能下降指代的是什么情况。
在原版llama上增量预训练肯定是有效的，要不然现在也不会有这么多在bloom、llama上增量训练的项目。

**Comment by caihaunqai** [comment]
> 没太明白你说的finetune后性能下降指代的是什么情况。 在原版llama上增量预训练肯定是有效的，要不然现在也不会有这么多在bloom、llama上增量训练的项目。

抱歉，表述有误。Chinese-LLaMA相对原本有提升但幅度不大，说明增量训练是有效的，但是有限；Chinese-Alpaca是有指令微调的，说明指令微调让模型在这个benchmark上有了更好的提升。

**Comment by ymcui** [comment]
> > 没太明白你说的finetune后性能下降指代的是什么情况。 在原版llama上增量预训练肯定是有效的，要不然现在也不会有这么多在bloom、llama上增量训练的项目。
> 
> 抱歉，表述有误。Chinese-LLaMA相对原本有提升但幅度不大，说明增量训练是有效的，但是有限；Chinese-Alpaca是有指令微调的，说明指令微调让模型在这个benchmark上有了更好的提升。

是的，我们目前初步的观察结果是这样的。可能也和该数据集是NLU类型（非生成类）任务有一定关系。届时我们会把原版LLaMA和我们推出的所有模型（基础版、Plus版）进行综合对比，这样就能更好地了解在该数据集上的性能提升来源了。

但需要注意的是，该数据集也只能评测大模型的某些特定能力，所以相关结论能否推广到大模型其他能力上还有待探讨。

**Comment by caihaunqai** [comment]
谢谢～

**Comment by caihaunqai** [comment]
> 没太明白你说的finetune后性能下降指代的是什么情况。 在原版llama上增量预训练肯定是有效的，要不然现在也不会有这么多在bloom、llama上增量训练的项目。

请问还有什么中文增强预训练的项目吗？方便分享几个吗？
