### ISSUE TITLE
请问在Windows上部署的模型，我该怎么去调用本地模型的api？

### ISSUE THREAD

**Issue by 1anglesmith1** [ymcui/Chinese-LLaMA-Alpaca#544]
### 详细描述问题
萌新，刚学习大模型，目前可以在window的power shell成功运行 Chinese-llama-alpaca-7b，但是只能在命令行进行提问，请问有方法可以调用这个模型的api吗？

**Comment by iMountTai** [comment]
可以通过外部UI[使用text generation webui搭建界面](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E4%BD%BF%E7%94%A8text-generation-webui%E6%90%AD%E5%BB%BA%E7%95%8C%E9%9D%A2)

**Comment by 1anglesmith1** [comment]
> 可以通过外部UI[使用text generation webui搭建界面](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E4%BD%BF%E7%94%A8text-generation-webui%E6%90%AD%E5%BB%BA%E7%95%8C%E9%9D%A2)

他这个也是多了个界面，能获取到模型回答的数据并返回吗？

**Comment by airaria** [comment]
因为模型结构与原版LLaMA相同，可以参考其他基于LLaMA或类似LLM模型的部署项目，或者参考这个还未merge的PR：https://github.com/ymcui/Chinese-LLaMA-Alpaca/pull/530
