### ISSUE TITLE
训练之后保存文件时提示报错，说output/pytorch_model.bin 不存在

### ISSUE THREAD

**Issue by icowan** [ymcui/Chinese-LLaMA-Alpaca#546]
### 详细描述问题

训练之后保存文件时提示报错，说output/pytorch_model.bin 不存在，但实际文件是存在的

<img width="762" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/6229526/517ca191-bb60-4e10-bd20-66c3594fea4f">

训练命令

```
wandb disabled
lr=2e-4
lora_rank=64
lora_alpha=128
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/data/llama/7B
#pretrained_model=/data/output/chinese-llama-alpaca-7b-lora
chinese_tokenizer_path=/data/chinese-llama-plus-lora-7b
#chinese_tokenizer_path=/data/output/chinese-llama-alpaca-7b-lora
dataset_dir=/data/pt_data/
data_cache=/data/temp_data_cache_dir/
per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=100
gradient_accumulation_steps=1
output_dir=/data/output/chinese-llama-lora-7b-0609-v1.1

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 2 run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --seed $RANDOM \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 100 \
    --save_steps 1200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --block_size 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False
```

### 参考信息

CPU 64核
内存 256G
显卡 两张A30

#### 依赖情况（代码类问题务必提供）

```
transformers             4.28.1
peft                     0.3.0
torch                    2.0.1
deepspeed                0.9.2
```

#### 运行日志或截图

<img width="1257" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/6229526/2502bd86-76d8-4181-b9b9-933267e35969">

### 必查项目

*将[ ]中填入x，表示打对钩。提问时删除这行。 前三项请按自己的问题类型保留符合的选项。*

- [x] **基础模型**：LLaMA-Plus  7B
- [x] **运行系统**：Linux 
- [x] **问题分类**：模型训练与精调
- [x] **模型正确性检查**：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行。
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by tomjamescn** [comment]
deepspeed使用的哪个版本了？

**Comment by icowan** [comment]
> 

deepspeed                0.9.2

**Comment by libigfat** [comment]
我也出现了这个问题，用的是zero3策略，保存的pytorch_model.bin是13G，保存速度缓慢，导致复制文件时，pytorch_model.bin还没有生成出来。
我注释了复制文件这三行，然后自行复制的pytorch_model.bin。

**Comment by LiemLin** [comment]
这个我也遇到过，应该最新版的BUG，修改了脚本再执行就好了
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/19672287-035b-4411-a5e0-66a8959a8d7b)

**Comment by iMountTai** [comment]
可以试试 #555

**Comment by extrame** [comment]
> 这个我也遇到过，应该最新版的BUG，修改了脚本run_clm_sft_with_peft.py再执行就好了 ![image](https://user-images.githubusercontent.com/16920347/244628177-19672287-035b-4411-a5e0-66a8959a8d7b.png) @ymcui @airaria 建议博主修复下

这个我也遇到了，看了下生成目录，直接在上层目录生成了adapter_model.bin，而不是pytorch_model.bin

**Comment by airaria** [comment]
#555 中修复了此问题。
