### ISSUE TITLE
采用第二阶段run_pt.sh预训练，有提示None of the inputs have requires_grad=True. Gradients will be Non，报错RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn，是哪里有问题呢？

### ISSUE THREAD

**Issue by sarahyongq** [ymcui/Chinese-LLaMA-Alpaca#547]
启动脚本部分命令如下：
CUDA_VISIBLE_DEVICES=0
lr=2e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

#pretrained_model=/data/chinese_llama_merge_7b/chinese_llama_merge_7b
#chinese_tokenizer_path=/data/chinese_llama_merge_7b/chinese_llama_merge_7b
pretrained_model=/data/chinese_llama_7b
chinese_tokenizer_path=/data/chinese_llama_7b
dataset_dir=/data/de_community
data_cache=temp_de_data_cache
per_device_train_batch_size=128
per_device_eval_batch_size=4
training_steps=10000000
gradient_accumulation_steps=1000
RANDOM=1234
output_dir=/data/Chinese-LLaMA-Alpaca/scripts/chinese_llama_dewu_lora_7b/

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --master_port 12345 --nnodes 1 --nproc_per_node 1 run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \

报错如下：
/data/lalpaca/lib/python3.7/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
Traceback (most recent call last):
  File "run_clm_pt_with_peft.py", line 632, in <module>
    main()
  File "run_clm_pt_with_peft.py", line 597, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/data/lalpaca/lib/python3.7/site-packages/transformers/trainer.py", line 1666, in train
    ignore_keys_for_eval=ignore_keys_for_eval,
  File "/data/lalpaca/lib/python3.7/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data/lalpaca/lib/python3.7/site-packages/transformers/trainer.py", line 2715, in training_step
    loss = self.deepspeed.backward(loss)
  File "/data/lalpaca/lib/python3.7/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/data/lalpaca/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1796, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/data/lalpaca/lib/python3.7/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1890, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/data/lalpaca/lib/python3.7/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 62, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/data/lalpaca/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward
    self, gradient, retain_graph, create_graph, inputs=inputs
  File "/data/lalpaca/lib/python3.7/site-packages/torch/autograd/__init__.py", line 199, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by moseshu** [comment]
> 启动脚本部分命令如下： CUDA_VISIBLE_DEVICES=0 lr=2e-4 lora_rank=8 lora_alpha=32 lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj" modules_to_save="embed_tokens,lm_head" lora_dropout=0.05
> 
> #pretrained_model=/data/chinese_llama_merge_7b/chinese_llama_merge_7b #chinese_tokenizer_path=/data/chinese_llama_merge_7b/chinese_llama_merge_7b pretrained_model=/data/chinese_llama_7b chinese_tokenizer_path=/data/chinese_llama_7b dataset_dir=/data/de_community data_cache=temp_de_data_cache per_device_train_batch_size=128 per_device_eval_batch_size=4 training_steps=10000000 gradient_accumulation_steps=1000 RANDOM=1234 output_dir=/data/Chinese-LLaMA-Alpaca/scripts/chinese_llama_dewu_lora_7b/
> 
> deepspeed_config_file=ds_zero2_no_offload.json
> 
> torchrun --master_port 12345 --nnodes 1 --nproc_per_node 1 run_clm_pt_with_peft.py --deepspeed ${deepspeed_config_file} --model_name_or_path ${pretrained_model} --tokenizer_name_or_path ${chinese_tokenizer_path} \
> 
> 报错如下： /data/lalpaca/lib/python3.7/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None warnings.warn("None of the inputs have requires_grad=True. Gradients will be None") Traceback (most recent call last): File "run_clm_pt_with_peft.py", line 632, in main() File "run_clm_pt_with_peft.py", line 597, in main train_result = trainer.train(resume_from_checkpoint=checkpoint) File "/data/lalpaca/lib/python3.7/site-packages/transformers/trainer.py", line 1666, in train ignore_keys_for_eval=ignore_keys_for_eval, File "/data/lalpaca/lib/python3.7/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop tr_loss_step = self.training_step(model, inputs) File "/data/lalpaca/lib/python3.7/site-packages/transformers/trainer.py", line 2715, in training_step loss = self.deepspeed.backward(loss) File "/data/lalpaca/lib/python3.7/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn ret_val = func(*args, **kwargs) File "/data/lalpaca/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1796, in backward self.optimizer.backward(loss, retain_graph=retain_graph) File "/data/lalpaca/lib/python3.7/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1890, in backward self.loss_scaler.backward(loss.float(), retain_graph=retain_graph) File "/data/lalpaca/lib/python3.7/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 62, in backward scaled_loss.backward(retain_graph=retain_graph) File "/data/lalpaca/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward self, gradient, retain_graph, create_graph, inputs=inputs File "/data/lalpaca/lib/python3.7/site-packages/torch/autograd/**init**.py", line 199, in backward allow_unreachable=True, accumulate_grad=True) # Calls into the C++ engine to run the backward pass RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

PeftModel.from_pretrained(model,f"{model_args.peft_path}",is_trainable=True) 设置一下is_trainable=True 试试看

**Comment by sarahyongq** [comment]
> > 启动脚本部分命令如下： CUDA_VISIBLE_DEVICES=0 lr=2e-4 lora_rank=8 lora_alpha=32 lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj" modules_to_save="embed_tokens,lm_head" lora_dropout=0.05
> > #pretrained_model=/data/chinese_llama_merge_7b/chinese_llama_merge_7b #chinese_tokenizer_path=/data/chinese_llama_merge_7b/chinese_llama_merge_7b pretrained_model=/data/chinese_llama_7b chinese_tokenizer_path=/data/chinese_llama_7b dataset_dir=/data/de_community data_cache=temp_de_data_cache per_device_train_batch_size=128 per_device_eval_batch_size=4 training_steps=10000000 gradient_accumulation_steps=1000 RANDOM=1234 output_dir=/data/Chinese-LLaMA-Alpaca/scripts/chinese_llama_dewu_lora_7b/
> > deepspeed_config_file=ds_zero2_no_offload.json
> > torchrun --master_port 12345 --nnodes 1 --nproc_per_node 1 run_clm_pt_with_peft.py --deepspeed ${deepspeed_config_file} --model_name_or_path ${pretrained_model} --tokenizer_name_or_path ${chinese_tokenizer_path} \
> > 报错如下： /data/lalpaca/lib/python3.7/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None warnings.warn("None of the inputs have requires_grad=True. Gradients will be None") Traceback (most recent call last): File "run_clm_pt_with_peft.py", line 632, in main() File "run_clm_pt_with_peft.py", line 597, in main train_result = trainer.train(resume_from_checkpoint=checkpoint) File "/data/lalpaca/lib/python3.7/site-packages/transformers/trainer.py", line 1666, in train ignore_keys_for_eval=ignore_keys_for_eval, File "/data/lalpaca/lib/python3.7/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop tr_loss_step = self.training_step(model, inputs) File "/data/lalpaca/lib/python3.7/site-packages/transformers/trainer.py", line 2715, in training_step loss = self.deepspeed.backward(loss) File "/data/lalpaca/lib/python3.7/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn ret_val = func(*args, **kwargs) File "/data/lalpaca/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1796, in backward self.optimizer.backward(loss, retain_graph=retain_graph) File "/data/lalpaca/lib/python3.7/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1890, in backward self.loss_scaler.backward(loss.float(), retain_graph=retain_graph) File "/data/lalpaca/lib/python3.7/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 62, in backward scaled_loss.backward(retain_graph=retain_graph) File "/data/lalpaca/lib/python3.7/site-packages/torch/_tensor.py", line 489, in backward self, gradient, retain_graph, create_graph, inputs=inputs File "/data/lalpaca/lib/python3.7/site-packages/torch/autograd/**init**.py", line 199, in backward allow_unreachable=True, accumulate_grad=True) # Calls into the C++ engine to run the backward pass RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
> 
> PeftModel.from_pretrained(model,f"{model_args.peft_path}",is_trainable=True) 设置一下is_trainable=True 试试看

我的training_args.peft_path 是none，所以是调用了model = get_peft_model(model, peft_config)，不能这样设置呢

**Comment by moseshu** [comment]
> RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

把这个参数gradient_checkpoint 设置为False 试试？你是在v100上运行的还是A100上跑的？
