### ISSUE TITLE
训练模型合并报错，但并没在输出什么错误信息

### ISSUE THREAD

**Issue by icowan** [ymcui/Chinese-LLaMA-Alpaca#548]
### 详细描述问题

1. 对模型进行训练，以下是训练代码

```
wandb disabled
lr=2e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/data/llama/7B
#pretrained_model=/data/output/chinese-llama-alpaca-7b-lora
chinese_tokenizer_path=/data/chinese-llama-plus-lora-7b
#chinese_tokenizer_path=/data/output/chinese-llama-alpaca-7b-lora
dataset_dir=/data/pt_data/
data_cache=/data/temp_data_cache_dir/
per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=100
gradient_accumulation_steps=4096
output_dir=/data/output/chinese-llama-lora-7b-0609-v1.2

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 2 run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --seed $RANDOM \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 100 \
    --save_steps 1200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --block_size 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --ddp_find_unused_parameters False
```

2. 对训练模型进行合并

```
python3 scripts/merge_llama_with_chinese_lora.py \
  --base_model /data/llama/7B \
  --lora_model /data/chinese-llama-plus-lora-7b/,/data/output/chinese-llama-lora-7b-0609-v1.2/pt_lora_model \
  --output_type huggingface \
  --output_dir /data/output/merge-chinese-llama-lora-7b-0609-v1.1
```

### 参考信息

CPU 64核
内存 256G
显卡 两张A30

#### 依赖情况（代码类问题务必提供）

```
transformers             4.28.1
peft                     0.3.0
torch                    2.0.1
deepspeed                0.9.2
```

#### 运行日志或截图

Base model: /data/llama/7B
LoRA model(s) ['/data/chinese-llama-plus-lora-7b/', '/data/output/chinese-llama-lora-7b-0609-v1.2/pt_lora_model']:
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.07s/it]
Peft version: 0.3.0
Loading LoRA for 7B model
Loading LoRA /data/chinese-llama-plus-lora-7b/...
base_model vocab size: 32000
tokenizer vocab size: 49953
Extended vocabulary size to 49953
Loading LoRA weights
Merging with merge_and_unload...

<img width="738" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/6229526/cce78cfd-b3e5-44bf-8f4f-b0f97211aeb9">

### 必查项目

- [x] **基础模型**：LLaMA-7B
- [x] **运行系统**：Windows / MacOS / Linux 
- [x] **问题分类**：模型转换和合并
- [x] **模型正确性检查**：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行。
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [ ] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by airaria** [comment]
训练用的基模型是原版llama还是与chinese-llama-plus-lora-7b合并后的模型？

**Comment by icowan** [comment]
> 训练用的基模型是原版llama还是与chinese-llama-plus-lora-7b合并后的模型？

@airaria 经过反复的 训练，合并，我大概难定位到问题在哪了，我现在不知道 `chinese-llama-7b-plus-lora` 训练时 `gradient_accumulation_steps` 参数是多少，不确实有没有关系。

当我 

```
per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=1
```

训练完合并是可以成功的，当 `gradient_accumulation_steps=1024` 或 `gradient_accumulation_steps=2048` 或更多时，就会出现这个错误。

我再跑几遍验证一下。

**Comment by iMountTai** [comment]
`/data/llama/7B`是原版模型还是合并`chinese-llama-plus-lora-7b`后的模型？

**Comment by icowan** [comment]
> `/data/llama/7B`是原版模型还是合并`chinese-llama-plus-lora-7b`后的模型？

不是 合并`chinese-llama-plus-lora-7b` 后的模型。
`/data/llama/7B` 就是 原始模型转换后的 huggingface 格式的原始模型

**Comment by icowan** [comment]
> 所以合并时只需要合并`/data/output/chinese-llama-lora-7b-0609-v1.2/pt_lora_model`,你这不算chinese-llama上的二次预训练，要么先合并`chinese-llama-plus-lora-7b`进行训练，要么在训练脚本中添加`peft_path=chinese-llama-plus-lora-7b`。建议仔细阅读[训练细节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E8%AE%AD%E7%BB%83%E7%BB%86%E8%8A%82)

了解了，我试试 ，感谢解答！！
