### ISSUE TITLE
关于预训练时多卡模型并行的问题

### ISSUE THREAD

**Issue by wangjvjie** [ymcui/Chinese-LLaMA-Alpaca#551]
我在https://github.com/tloen/alpaca-lora/issues/332 上面看到，使用torchrun默认会使用DDP数据并行来训练，所以我想一下你们当时有没有用模型并行的方式训练呀。我在训练的时候如果只修改nproc_per_node，好像确实是以DDP的方式训练的。deepspeed没有任何作用。因为我目前在考虑购买4090用来训练30B的模型，但是查了好久也没看到有人用4090训练过。

**Comment by wangjvjie** [comment]
已经解决，参照alpaca的代码，添加了device_map和model.model_parallel=True

**Comment by AliceShen122** [comment]
前辈请教下，这个device_map和model.model_parallel=True添加在哪里呀？看了下alpaca-lora的代码，没搞懂应该加在哪里。

**Comment by zzx16045223** [comment]
> 前辈请教下，这个device_map和model.model_parallel=True添加在哪里呀？看了下alpaca-lora的代码，没搞懂应该加在哪里。

请问你解决了吗？我也不是很懂这个问题
