### ISSUE TITLE
按照预训练和精调继续训练文档步骤操作后效果变差了

### ISSUE THREAD

**Issue by LiemLin** [ymcui/Chinese-LLaMA-Alpaca#552]
精调的数据是学会了，但是之前会的变不会了，哪位兄弟遇到过这个问题
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/2062379d-84c2-4226-a8da-1794902a2daa)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/12614fc4-c9e6-48ae-9694-b1ddda4cb929)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/8deaf069-cd9a-4af9-b3cb-57e8aa733d8d)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/2101d6d7-8344-4949-b1b6-a5eb1a814d68)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/8d4f0e29-ecaa-4614-9146-c8aaeec7cb1f)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16920347/515e9e61-996d-44cf-afd1-f19f50527bd7)

**Comment by LiemLin** [comment]
[
  {
    "instruction": "钓鱼岛是哪个国家的？",
    "input": "",
    "output": "钓鱼岛是中国的"
  }
]
@ymcui @airaria 会不会和我就一条训练数据有关系，数据集太小了吗？教它的学会了，之前的算术缺不会了

**Comment by airaria** [comment]
建议划分一个验证集，注意监视验证集上的loss变化，看是否过拟合了

**Comment by ymcui** [comment]
一条训练数据就没必要训练了，建议尝试few-shot。

P.S. 例子建议不要贴一些涉政内容，拜谢。

**Comment by LiemLin** [comment]
了解了，多谢二位大佬
