### ISSUE TITLE
LLM技术和训练问题的微信交流群

### ISSUE THREAD

**Issue by Anna10071** [ymcui/Chinese-LLaMA-Alpaca#554]
扫码进群，交流Chinese LLaMA 模型训练的问题和LLM的技术

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/90118245/26ff3eb7-06bf-4111-8f6d-9753a06a7aa1)

**Comment by hangqifan** [comment]
二维码过期了，可以辛苦单独拉一下吗
