### ISSUE TITLE
扩充中文tokenizer后是不是一定要训练embed_tokens和lm_head？

### ISSUE THREAD

**Issue by guijuzhejiang** [ymcui/Chinese-LLaMA-Alpaca#557]
扩充中文tokenizer后，tokenizer size的变化会导致embed_tokens和lm_head层shape的变化，直觉合并中英文tokenizer后的第一次预训练要训练embed_tokens和lm_head层才行，所以modules_to_save里设置了embed_tokens和lm_head，预训练后的模型因为对合并后的tokenizer已经更新了embed_tokens和lm_head层的weihts，所以后面的微调可以删除modules_to_save，不知道这样理解对不对？

**Comment by iMountTai** [comment]
✓
