### ISSUE TITLE
合并Lora时报错NotImplementedError

### ISSUE THREAD

**Issue by wuxiulike** [ymcui/Chinese-LLaMA-Alpaca#558]
chinese-alpaca-plus-lora-13b  
chinese-llama-plus-lora-13b
chinese-llama-plus-lora-7b

执行单LoRA权重合并时候，报错NotImplementedError

(fastchat) root@estar-ESC8000-G4:~# pip list \| grep*
Package             Version
------------------- ------------
accelerate          0.19.0
aiofiles            23.1.0
aiohttp             3.8.4
aiosignal           1.3.1
altair              5.0.1
anyio               3.6.2
appdirs             1.4.4
async-timeout       4.0.2
attrs               23.1.0
certifi             2023.5.7
charset-normalizer  3.1.0
click               8.1.3
contourpy           1.0.7
cycler              0.11.0
docker-pycreds      0.4.0
fastapi             0.95.1
ffmpy               0.3.0
filelock            3.12.0
fonttools           4.39.4
frozenlist          1.3.3
fschat              0.2.9
fsspec              2023.5.0
gitdb               4.0.10
GitPython           3.1.31
gradio              3.23.0
h11                 0.14.0
httpcore            0.17.0
httpx               0.24.0
huggingface-hub     0.14.1
idna                3.4
importlib-resources 5.12.0
Jinja2              3.1.2
jsonschema          4.17.3
kiwisolver          1.4.4
linkify-it-py       2.0.2
markdown-it-py      2.2.0
markdown2           2.4.8
MarkupSafe          2.1.2
matplotlib          3.7.1
mdit-py-plugins     0.3.3
mdurl               0.1.2
multidict           6.0.4
nh3                 0.2.11
numpy               1.24.3
orjson              3.8.12
packaging           23.1
pandas              2.0.1
pathtools           0.1.2
peft                0.3.0
Pillow              9.5.0
pip                 23.1.2
prompt-toolkit      3.0.38
protobuf            3.19.0
psutil              5.9.5
pydantic            1.10.7
pydub               0.25.1
Pygments            2.15.1
pyparsing           3.0.9
pyrsistent          0.19.3
python-dateutil     2.8.2
python-multipart    0.0.6
pytz                2023.3
PyYAML              6.0
regex               2023.5.5
requests            2.30.0
rich                13.3.5
semantic-version    2.10.0
sentencepiece       0.1.97
sentry-sdk          1.23.1
setproctitle        1.3.2
setuptools          67.7.2
shortuuid           1.0.11
six                 1.16.0
smmap               5.0.0
sniffio             1.3.0
starlette           0.26.1
svgwrite            1.4.3
tokenizers          0.13.3
toolz               0.12.0
torch               1.13.1+cu117
torchaudio          0.13.1+cu117
torchvision         0.14.1+cu117
tqdm                4.65.0
transformers        4.28.1
typing_extensions   4.5.0
tzdata              2023.3
uc-micro-py         1.0.2
urllib3             1.26.15
uvicorn             0.22.0
wandb               0.15.3
wavedrom            2.0.3.post3
wcwidth             0.2.6
websockets          11.0.3
wheel               0.40.0
yarl                1.9.2
zipp                3.15.0

*请提供文本log、运行截图*
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/38093815/9e805532-a6ad-4bf8-9cc6-8ec6e5a1c03a)

- [x] **基础模型**： LLaMA-Plus 13B/33B
- [x] **运行系统**：Linux 
- [x] **问题分类**：模型转换和合并
- [x] **模型正确性检查**：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行。
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by ymcui** [comment]
你截图中的命令比较迷惑，alpaca-plus需要两个lora权重，而你的输出目录又是命名为llama。
如果你要合并alpaca-plus：https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/手动模型合并与转换#多lora权重合并适用于chinese-alpaca-plus

**Comment by wuxiulike** [comment]
> 

抱歉，可能我目录起名不太规范，但只是路径的命名有点重复，实际并不是相同的目录，而是三个不同的目录。
/root/model/transformer_model_13b   是LLaMA转换格式以后的目录
/root/chinese-alpaca-plus-lora-13b     是要合并的权重
/root/code/model/Chinese-llama-13b   是未创建的输出目录

目前的报错原因是跟目录名无关的。

**Comment by wuxiulike** [comment]
> 你截图中的命比迷惑，alpaca-plus需要两个lora权，而你的输出目录又是命名为llama。如果你要合并 alpaca-plus：[https://github.com/ymcui/Chinese-LLaMA- Alpaca/wiki/手动模型合与转换#多lora权重合适用于chinese-alpaca-plus](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E6%89%8B%E5%8A%A8%E6%A8%A1%E5%9E%8B%E5%90%88%E5%B9%B6%E4%B8%8E%E8%BD%AC%E6%8D%A2#%E5%A4%9Alora%E6%9D%83%E9%87%8D%E5%90%88%E5%B9%B6%E9%80%82%E7%94%A8%E4%BA%8Echinese-alpaca-plus)

抱紧，可能我的目录起名不太规范，但只是路径的名称有点重现，实际上并不是相同的目录，而是三个不同的目录。 /root/model/transformer_model _13b是LLaMA转换格式以后的目录
/
root/chinese -alpaca-plus-lora-13b 是要合并的权重
/root/code/model/Chinese-llama-13b 是未创建的输出目录

目前的报错原因是跟目录名无关的。

**Comment by ymcui** [comment]
1）LLaMA是否是原版？比对过SHA256吗？
2）lora权重是否是从我们项目中下载的原版？

**Comment by airaria** [comment]
截图里合并的是13B模型吗？
从报错位置上看很奇怪，因为13B模型的num_shards是2，而截图中走到了num_shards==1的分支。
同上建议pull最新代码，并检查模型和各目录内容。

**Comment by wuxiulike** [comment]
> 0）git pull最新的代码了没有？ 1）LLaMA是否是原版？比对过SHA256吗？ 2）lora权重是否是从我们项目中下载的原版？ 3）贴完整运行命令（最好不要截图，而是文字版），--lora_model请指定为llama-plus而不是alpaca-plus，`ls`贴一下你说的那三个目录。

搞清楚了，我git pull最新的代码再执行就搞定了。多谢
