### ISSUE TITLE
最后一步执行报错是什么原因？

### ISSUE THREAD

**Issue by lizakk** [ymcui/Chinese-LLaMA-Alpaca#56]
llama_model_load: loading tensors from 'zh-models/7B/ggml-model-q4_0.bin'
llama_model_load: tensor 'tok_embeddings.weight' has wrong size in model file
llama_init_from_file: failed to load model
main: error: failed to load model 'zh-models/7B/ggml-model-q4_0.bin'

**Comment by ymcui** [comment]
看似是转换出来模型的词表对不上。需要注意的是，将`.pth`模型转换为FP16-ggml时，tokenizer.model要用我们模型压缩包中提供的。另外，alpaca/llama的词表不能混用。麻烦再仔细对照流程检查一下。
也推荐你看一下在线的notebook，对照查看哪一步有出入：https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/notebooks/convert_and_quantize_chinese_llama.ipynb
