### ISSUE TITLE
关于两种训练中文LLM的方法

### ISSUE THREAD

**Issue by guijuzhejiang** [ymcui/Chinese-LLaMA-Alpaca#560]
下面两种训练LLM模型的方法，请教下哪种效果更好？
1，用中文数据，参照transformers的run_clm.py，直接fine tuning原始LLAMA模型
2，用中文数据，合并tokenizer后，训练LLAMA模型的lora，embed_tokens和lm_head层
直觉上第一种传统训练方式没问题，但比较贵。
第二种训练lora的方式便宜很多，但原始LLAMA模型没训练过中文语料，这时的base model的作用很有限，这样能否把所有中文数据的表征只用lora学好？
请问这方面有实验对比吗？

**Comment by ymcui** [comment]
无。github上也有全量预训练的模型，不过语料的来源和规模都不一样，不一定直接可比。
