### ISSUE TITLE
C-Eval 效果评测

### ISSUE THREAD

**Issue by Ricardokevins** [ymcui/Chinese-LLaMA-Alpaca#561]
### 详细描述问题
很惊喜的看到在C-eval上惊人的效果，Chinese-Alpaca的效果很好，基于这个模型我在自己的领域上也进行了微调，想问问会放出评测的脚本吗，可以很方便的比较微调带来的影响。

*将[ ]中填入x，表示打对钩。提问时删除这行。 前三项请按自己的问题类型保留符合的选项。*

- [Alpaca-Plus ] **基础模型**：LLaMA / Alpaca / LLaMA-Plus / Alpaca-Plus（同时说明模型大小：7B/13B/33B）
- [Linux ] **运行系统**：Windows / MacOS / Linux 
- [ 模型推理问题] **问题分类**：下载问题 / 模型转换和合并 / 模型训练与精调 / 模型推理问题（🤗 transformers） / 模型量化和部署问题（llama.cpp、text-generation-webui、LlamaChat） / 效果问题 / 其他问题
- [x] **模型正确性检查**：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行。
- [x] （必选）由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [x] （必选）我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] （必选）第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案

**Comment by ymcui** [comment]
是的，c-eval解码代码近期会开放给大家。

**Comment by Ricardokevins** [comment]
> 是的，c-eval解码代码近期会开放给大家。

wow，非常感谢。期待您的工作。
