### ISSUE TITLE
微调llama 33B的模型显存溢出

### ISSUE THREAD

**Issue by zhangatao** [ymcui/Chinese-LLaMA-Alpaca#564]
### 详细描述问题

*请尽量具体地描述您遇到的问题，**必要时给出运行命令**。这将有助于我们更快速地定位问题所在。*

#### 依赖情况（代码类问题务必提供）

*请提供transformers, peft, torch等常规依赖库的版本：pip list \| grep*

#### 运行日志或截图

*请提供文本log、运行截图*

### 必查项目

*将[ ]中填入x，表示打对钩。提问时删除这行。 前三项请按自己的问题类型保留符合的选项。*

- [x] **基础模型**：LLaMA / Alpaca（同时说明模型大小：7B/13B/33B）
- [x] **运行系统**：Linux 
- [x] **问题分类**：模型训练与精调

我在针对llama 33B的模型进行微调的时候，显存溢出，当前配置 8 * a100 (80G)，batch_size，用的是官方提供的例子，请问这种情况应该怎么解决呢

**Comment by xuexidi** [comment]
用deepspeed stage2 offload可以，显存占用大约70G
