### ISSUE TITLE
原版LLaMA模型

### ISSUE THREAD

**Issue by Alexzhang369** [ymcui/Chinese-LLaMA-Alpaca#566]
重构需要原版LLaMA模型，[去LLaMA项目申请使用](https://github.com/facebookresearch/llama)或参考这个[PR]

这个需要怎么申请呢，有没有下载链接

**Comment by ymcui** [comment]
正规渠道就是上面链接里申请（LLaMA项目README第一句话里的google form）。
其他包括huggingface上有一些第三方的（合法性自己权衡），请自行查找。
