### ISSUE TITLE
支持模型搭配OpenLLaMA模型使用

### ISSUE THREAD

**Issue by DanaAcock** [ymcui/Chinese-LLaMA-Alpaca#569]
### 详细描述问题

*Facebook官方发布的[LLaMA](https://github.com/facebookresearch/llama)模型并未很好的开源与商业化支持。

OpenLM Research 由加州大学伯克利分校创建，旨在促进开源语言模型研究。
OpenLM Research正在发布 OpenLLaMA 的公开预览版，这是在 RedPajama 数据集上训练的 Meta AI 的 LLaMA 7B 和 13B 的许可开源复制品。OpenLM Research的模型权重可以作为现有实现中 LLaMA 的替代品。OpenLM Research还提供 LLaMA 模型的较小 3B 变体。

详见：https://github.com/openlm-research/open_llama

请研发支持搭配OpenLLaMA模型使用的——Chinese-OpenLLaMA-Alpaca

*

### 参考信息

[OpenAlpaca](https://github.com/yxuansu/OpenAlpaca)：

This is the repo for the OpenAlpaca project, which aims to build and share an instruction-following model based on [OpenLLaMA](https://github.com/openlm-research/open_llama). We note that, following OpenLLaMA, OpenAlpaca is permissively licensed under [the Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0). We also highlight that the training of OpenAlpaca only takes around 30 minutes on 8xA100 GPUs.

This repo contains

The [weights](https://github.com/yxuansu/OpenAlpaca#weights) for the fine-tuned model.
The [data](https://github.com/yxuansu/OpenAlpaca#data) used for fine-tuning the model.
The [example usage](https://github.com/yxuansu/OpenAlpaca#example_usage) of OpenAlpaca.
The [code](https://github.com/yxuansu/OpenAlpaca#code) for fine-tuning the model.
Usage and License Notices: OpenAlpaca follows the distribution permission of [OpenLLaMA](https://github.com/openlm-research/open_llama), i.e. the Apache 2.0 license, which means OpenAlpaca can be used in any academic or commercial purposes for free.

### 必查项目

*将[ ]中填入x，表示打对钩。提问时删除这行。 前三项请按自己的问题类型保留符合的选项。*

- [x] **基础模型**：LLaMA / Alpaca / LLaMA-Plus / Alpaca-Plus（同时说明模型大小：7B/13B/33B）
- [x] **运行系统**：Windows / MacOS / Linux 
- [x] **问题分类**：模型转换和合并 / 其他问题

**Comment by ymcui** [comment]
谢谢建议
