### ISSUE TITLE
多轮对话训练的语料的问题

### ISSUE THREAD

**Issue by ZenXir** [ymcui/Chinese-LLaMA-Alpaca#57]
训练多轮对话时，提供的语料是这样的：
User:xxx 和 GPT:xxx 的对话
User:xxx 和 ChatGPT:xxx 的对话
User:xxx 和 Assistant:xxx 的对话
Human:xxx 和  Assistant:xxx 的对话

角色设定不统一，这样会对对多轮训练产生影响吗？需要统一角色 设定不？
如果不需要统一， 是不是 只要是多轮对话语料，保证格式对 就可以直接合在一起了？

**Comment by ymcui** [comment]
抱歉。我们没有用到多轮对话数据，所以也不是很清楚应该如何处理数据。
