### ISSUE TITLE
关于H100的GPU下训练的支持

### ISSUE THREAD

**Issue by leonunix** [ymcui/Chinese-LLaMA-Alpaca#570]
### 详细描述问题

大佬们，问一下你们有使用h100GPU的经验吗。我在h100 gpu下卡在如下步骤。在这个步骤cpu占用率100%，但是gpu上没有发现process。然后就一直停在这样输出了。相同的一套东西，在L40下没任何问题。就在H100下跑不起来。

[INFO|configuration_utils.py:575] 2023-06-12 05:04:14,144 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 0,
  "eos_token_id": 0,
  "transformers_version": "4.28.1"
}

06/12/2023 05:04:55 - INFO - __main__ - Init new peft model
06/12/2023 05:04:55 - INFO - __main__ - target_modules: ['q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj']
06/12/2023 05:04:55 - INFO - __main__ - lora_rank: 8
trainable params: 2097152 || all params: 6872244224 || trainable%: 0.030516261233500656

**Comment by ymcui** [comment]
没有H100……
