### ISSUE TITLE
请教一下中文词表训练的细节问题

### ISSUE THREAD

**Issue by fssqawj** [ymcui/Chinese-LLaMA-Alpaca#571]
### 详细描述问题

查看了您这个项目使用的中文词表，感观上非常好！绝大部分都是有实义的中文词/短语。

在技术报告中您提到了是在通用的中文语料，使用 sentencepiece 训练得到，我这边想具体了解一些细节问题：

1. 通用中文语料的整体大小，来源 以及 大概比例
2. sentencepiece 训练的具体参数（看词表格式应该是 BPE），有无预先分词之类的操作

再次感谢~

**Comment by ymcui** [comment]
1、词表训练数据与非plus版模型的训练数据相同，大约20G，由维基百科、新闻数据、其他百科数据、问答数据构成，与我们的中文BERT/RoBERTa/ELECTRA/MacBERT等系列数据一致。
2、词表训练参数方面并没有太多调整，只需要指定输出词表大小，未提前经过分词工具处理。

**Comment by acadaiaca** [comment]
> 

请问预训练的stage 1怎么实现？目前的run_clm_pt_with_peft.py如何实现冻结其它层，只训练embedding层？
https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/training/run_clm_pt_with_peft.py

**Comment by acadaiaca** [comment]
> 1、词表训练数据与非plus版模型的训练数据相同，大约20G，由维基百科、新闻数据、其他百科数据、问答数据构成，与我们的中文BERT/RoBERTa/ELECTRA/MacBERT等系列数据一致。 2、词表训练参数方面并没有太多调整，只需要指定输出词表大小，未提前经过分词工具处理。

请问预训练的stage 1怎么实现？目前的run_clm_pt_with_peft.py如何实现冻结其它层，只训练embedding层？
https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/training/run_clm_pt_with_peft.py
