### ISSUE TITLE
Code for chinese_sp.model file 

### ISSUE THREAD

**Issue by Shreyans92** [ymcui/Chinese-LLaMA-Alpaca#573]
Hi...

Thanks for the awesome repo. I want to understand how u generated chinese_sp.model file. Is there any code available for that also?

Thanks,
Shreyans

**Comment by airaria** [comment]
We train it with [sentencepiece](https://github.com/google/sentencepiece). You can refer to the [instructions](https://github.com/google/sentencepiece#train-sentencepiece-model) there.

**Comment by glide-the** [comment]
Thanks, I also have the same question

**Comment by Shreyans92** [comment]
@airaria Thanks for the answer, have a quick doubt how did u decided the vocab size for your tokenizer that you trained?
