### ISSUE TITLE
tokenizer_config.json与config.json中pad_token不统一的问题

### ISSUE THREAD

**Issue by zipzou** [ymcui/Chinese-LLaMA-Alpaca#576]
### 详细描述问题

在使用alpaca-plus-13b时，合并完参数后，得到了`config.json`与`tokenzier_config.json`，但是两个配置文件对于`pad_token_id`的配置不一致。

在`LlamaForCausalLM.from_pretrained`初始化模型时，会加载`config.json`读取模型配置，此时设定的`pad_token_id`是0；
但是在初始化`tokenizer`使用`LlamaTokenizer.from_pretrained`时，由于加载的`tokenizer_config `中的`pad_token`设为了null，导致在`tokenizer.pad_token_id`获取到的id为49953，但是`model.model.padding_idx`为0，这个是不一致的。

#### 运行日志或截图

以下为分别打印`tokenizer.pad_token_id`与`model.model.padding_idx`的值：
<img width="226" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/13446458/0c135c1f-2832-4402-924e-ec759376a1d2">

请问这个结果是符合预期的吗？应该是有问题的吧。

**Comment by airaria** [comment]
感谢指出问题🙏
不过检查后发现`model.model.padding_idx`仅影响pad的初始化，所以不会对Alpaca模型产生实际影响。
这里改不改成49953区别不大。
