### ISSUE TITLE
为什么需要基于llama以及lora adapter之后的Chinese-Alpaca模型基础之上，在进行pretrain？

### ISSUE THREAD

**Issue by JustinZou1** [ymcui/Chinese-LLaMA-Alpaca#577]
既然已经有了llama基础模型，在这上进行指令微调，就能适应下游任务。为啥，这里还需要基于llama以及lora adapter之后的模型基础之上，在进行pretrain？

**Comment by ymcui** [comment]
因为LLaMA对中文的支持有限，毕竟指令数据的数量远小于自由文本。
你也可以去参考其他只做指令精调的项目。

**Comment by JustinZou1** [comment]
谢谢老师的快速回复，还有如下3个问题：
1.pretrain和sft的区别是什么？pretrain阶段，是不是可以理解更好地理解中文。而sft是更好地适应下游特定任务，比如对话功能。他们的侧重点不同？
2.这个pretrain的数据集有什么要求吗？需要多大的数据量去训练？
3.看这个项目的pretrain也是基于lora，那这一步骤可以不基于lora去pretrain，用全参数fine-tune，可以吗？这样是不是会修改原始参数，对中文理解会不会更好些？

**Comment by airaria** [comment]
1. 现在大家的理解基本是这样的
2. 通用领域数据，越大越好
3. 可以全量，但训练速度慢。没有比较过效果区别，你可以自行实验尝试

**Comment by zeng9t** [comment]
请问全参数finetune基于chinese alpaca，load合并后的base model后需要额外设置什么吗？

**Comment by airaria** [comment]
> @airaria @ymcui 谢谢老师的回复。还有一个问题：中文LLaMA（Chinese-LLaMA）是基于pretrain（scripts/training/run_clm_pt_with_peft.py）训练的模型对吗？而中文Alpaca（Chinese-Alpaca）是基于sft（scripts/training/run_clm_sft_with_peft.py）在中文LLaMA基础之上微调的模型，对吗？

是的

**Comment by airaria** [comment]
> 请问全参数finetune基于chinese alpaca，load合并后的base model后需要额外设置什么吗？

没太看明白意思；你可以开一个新issue详细描述你的问题

**Comment by xupengrun** [comment]
@ymcui 老师请教个问题，chinese-alpaca-lora-33b测试效果挺好的，这个模型是只在原版llama模型基础上做了中文指令微调得到的吗？还是在Chinese-LLaMA-33B 20G中文语料预训练之后的基座模型再使用中文指令微调得到的？

**Comment by ymcui** [comment]
> @ymcui 老师请教个问题，chinese-alpaca-lora-33b测试效果挺好的，这个模型是只在原版llama模型基础上做了中文指令微调得到的吗？还是在Chinese-LLaMA-33B 20G中文语料预训练之后的基座模型再使用中文指令微调得到的？

我们发布的所有中文Alpaca模型均由对应的中文LLaMA模型之上进行指令精调训练，也就是说Chinese-Alpaca-33B是由Chinese-LLaMA-33B之上训练所得。

依赖关系：`原版LLaMA` -> `中文LLaMA（含Plus）` -> `中文Alpaca（含Plus）`

感兴趣的话可以看一下我们的技术报告，里面有相应的介绍。https://arxiv.org/abs/2304.08177
<img width="923" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/16095339/d9083b2f-d9bc-4e68-8e08-8efca560fc42">
