### ISSUE TITLE
有没有能运行在手机上的大模型呢

### ISSUE THREAD

**Issue by Alexzhang369** [ymcui/Chinese-LLaMA-Alpaca#578]
请问大佬有没有能运行在手机上的大模型呢
Google I/O大会，可以运行在智能手机上的大语言模型：Gecko（壁虎）

另外，我在mac pro上运行起来了 chinese-alpaca-plus-7b-merged模型，可以进行中文问答了。
https://huggingface.co/minlik/chinese-alpaca-plus-7b-merged

使用的代码如下：
import torch
import transformers
from transformers import LlamaTokenizer, LlamaForCausalLM

def generate_prompt(text):
    return f"""Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
{text}

### Response:"""

tokenizer = LlamaTokenizer.from_pretrained('./chinese-alpaca-plus-7b-merged')
model = LlamaForCausalLM.from_pretrained('./chinese-alpaca-plus-7b-merged')
model.eval()

text = '第一个登上月球的人是谁？'
prompt = generate_prompt(text)
input_ids = tokenizer.encode(prompt, return_tensors='pt')

with torch.no_grad():
    output_ids = model.generate(
        input_ids=input_ids,
        max_new_tokens=128,
        temperature=1,
        top_k=40,
        top_p=0.9,
        repetition_penalty=1.15
    )
output = tokenizer.decode(output_ids[0], skip_special_tokens=True)
print(output.replace('text', '').strip())

**Comment by ymcui** [comment]
你可以研究一下，
1）MLC-LLM：https://github.com/mlc-ai/mlc-llm
2）llama.cpp也支持在安卓手机上部署：https://github.com/ggerganov/llama.cpp#android
