### ISSUE TITLE
请教合并模型merge_llama_with_chinese_lora.py的原理和中文LLaMA训练细节源码

### ISSUE THREAD

**Issue by jiangliqin** [ymcui/Chinese-LLaMA-Alpaca#58]
你好，阅读了merge_llama_with_chinese_lora可是不太明白translate_state_dict_key背后的原理
以及请教中文LLaMA过程中词表扩充-预训练-指令精调的源代码学习学习，感谢~

**Comment by airaria** [comment]
将HF模型和原版模型的state_dict的key一一匹配即可。
训练代码可参考公开的Transformers中的run_clm.py和Stanford Alpaca代码。

**Comment by heyboy905** [comment]
merge_llama_with_chinese_lora脚本在哪呀
