### ISSUE TITLE
请问下大佬多机多卡训练，data cache的路径不能一样吧，发现设置一样会报错 ，另外多机多卡该怎么保存模型 以及使用保存的模型 和LoRA合并呀？

### ISSUE THREAD

**Issue by sixgold993** [ymcui/Chinese-LLaMA-Alpaca#580]
### 提交前必须检查以下项目

- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

请问下大佬多机多卡训练，data cache的路径不能一样吧，发现设置一样会报错 ，另外多机多卡该怎么保存模型 以及使用保存的模型 和LoRA合并呀？

### 运行日志或截图

![Uploading image.png…]()

**Comment by iMountTai** [comment]
图片挂了

**Comment by sixgold993** [comment]
> 图片挂了
比如2个机器 每个8个gpu，一共16个gpu。 我需要把训练数据拆分为两份吗？
