### ISSUE TITLE
请问在模型预训练的时候，训了几个epoch，1个吗 还是2-3个？

### ISSUE THREAD

**Issue by Zombiessss** [ymcui/Chinese-LLaMA-Alpaca#581]
### 提交前必须检查以下项目

- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

 请问在模型预训练的时候，训了几个epoch，1个吗 还是2-3个？

### 依赖情况（代码类问题务必提供）

 请问在模型预训练的时候，训了几个epoch，1个吗 还是2-3个？

### 运行日志或截图

 请问在模型预训练的时候，训了几个epoch，1个吗 还是2-3个？

**Comment by Zombiessss** [comment]
以及增量预训练输出的ckpt是否可以直接调用用于推理？还是需要拿pt_lora_model和base_model合并后再推理？
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/25706482/3b53833f-0814-4e77-9d44-6214f85a64ee)

**Comment by iMountTai** [comment]
1. 关于训练的详细细节，近期我们的论文会有所更新，敬请关注
2. 增量预训练保存的ckpt不能直接用于推理，这只是lora权重，需要pt_lora_model和base_model合并使用(base_model应该是已经合并了lora权重的模型，因为你说的是增量预训练)

**Comment by Antiman-cmyk** [comment]
@iMountTai wiki给的脚本里只训练100steps，如果是这样的话，这么大的预训练语料只会用到很少的一部分吧？但是在实验中增加训练了14000steps的checkpoint用来合并后测试，发现效果特别差，原本llama的对话能力严重下降，是不是和训练有关呢？llama的SHA256检查没问题
