### ISSUE TITLE
'LoraConfig' object is not subscriptable

### ISSUE THREAD

**Issue by liyu19980601** [ymcui/Chinese-LLaMA-Alpaca#582]
### 提交前必须检查以下项目

- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

我在运行bash run_pt.sh的时候，出现错误：
<img width="1681" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/44581509/733b5958-46fe-4440-8b18-d0b2ebb52d16">
我查看了之前的问题，我的peft版本确实是0.3.0
<img width="1116" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/44581509/04dc979e-96f2-4ae5-97f8-95a48660c9b2">

**Comment by airaria** [comment]
快速的解决办法参见https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/474

另外请pull最新代码，已解决此问题
