### ISSUE TITLE
保存的模型大小不一致

### ISSUE THREAD

**Issue by sixgold993** [ymcui/Chinese-LLaMA-Alpaca#585]
### 提交前必须检查以下项目

- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型转换和合并

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

<img width="1057" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/38970047/71bed3aa-db8d-443b-bd17-3f6356c2e679">

保存的模型发现output_dir下面的pytorch_model.bin 和pt_lora_model目录下的adapter_model.bin 大小差距非常大。pytorch_model.bin要大很多 ，按理来说这两个应该是一样的吧，这个请问该怎么解决呀？

**Comment by iMountTai** [comment]
1. 代码是pull最新的吗？
2. 运行命令呢？
3. 文件不一样大，具体怎么不一样大？

**Comment by zhousicheng123** [comment]
原来的adapter.bin是858477867，我保存的大概是这个一倍大，我看主要保存了：名称 大小 requires_grad
base_model.model.model.embed_tokens.original_module.weight 204607488 True
base_model.model.model.embed_tokens.modules_to_save.default.weight 204607488 True
base_model.model.lm_head.original_module.weight 204607488 True
base_model.model.lm_head.modules_to_save.default.weight 204607488 True
其他的都是中间的lora参数

**Comment by airaria** [comment]
数据格式是不是float32？发布的7B模型adapter_model.bin的格式是float16

**Comment by zhousicheng123** [comment]
有可能，但我看我训练的参数感觉也有问题，是不是应该只训练modules_to_save的lm_head和embed_tokens，original_module不训练。如果训练了original_module 而且没有保存下来 后面merge回去会有问题吧

**Comment by iMountTai** [comment]
保存后的模型权重的key打印出来看看，不要在训练中打印，并且看看保存权重的dtype
另外你安装的是新版的peft，这个版本的peft会把modules_to_save复制一份,不确定保存后的权重包含原始权重还是只有modules_to_save的权重，检查一下吧
