### ISSUE TITLE
使用Transformers推理的api接口交互

### ISSUE THREAD

**Issue by haoyu-lab** [ymcui/Chinese-LLaMA-Alpaca#587]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型推理

### 基础模型

LLaMA-Plus-7B

### 操作系统

Linux

### 详细描述问题

请问能否提供一份使用Transformers推理的api接口交互方式

**Comment by airaria** [comment]
api接口交互方式是指？部署成服务，还是指python程序里调用？

**Comment by 1anglesmith1** [comment]
> 

我也是，本地模型合并部署后，想在python程序中调用，

**Comment by haoyu-lab** [comment]
> api接口交互方式是指？部分服务，还是指python程序里调用？
我想要在我的程序中调用

**Comment by 1anglesmith1** [comment]
> 

如何给部署的模型提供一个可供调用的api，方便在程序中使用

**Comment by airaria** [comment]
> api接口交互方式是指？部分服务，还是指python程序里调用？
> 我想要在我的程序中调用

可以按这个PR里方式部署成服务，程序通过request请求去调用
https://github.com/ymcui/Chinese-LLaMA-Alpaca/pull/530
