### ISSUE TITLE
请教如何利用此系列模型做SequenceClassification

### ISSUE THREAD

**Issue by Arthassssss** [ymcui/Chinese-LLaMA-Alpaca#588]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

效果问题

### 基础模型

None

### 操作系统

None

### 详细描述问题

transformers里面针对llama模型的LlamaForSequenceClassification的方案，使用的是last token作为整句向量
LlamaForSequenceClassification uses the last token in order to do the classification 
请教：针对在当前系列模型中，针对整句的向量是否有测试和考虑，或者尤其思路，谢谢。

**Comment by iMountTai** [comment]
合并后的模型(llama/alpaca)与原版llama的使用方式其实并没有区别，您可以跑一下相关实验对比相应的效果是否有差别，也欢迎您分享相关实验结果与结论
