### ISSUE TITLE
使用llama-Ziya与原始llama进行合并，使用llama.cpp进行量化部署时出现的问题

### ISSUE THREAD

**Issue by xjDUAN184** [ymcui/Chinese-LLaMA-Alpaca#591]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型转换和合并

### 基础模型

LLaMA-13B

### 操作系统

Linux

### 详细描述问题

有没有大佬尝试过用其他的llama相关大模型与llama基础模型进行合并？
我这里尝试的是Ziya-LLaMA-13B-v1这个模型与原始llama模型进行合并，Ziya在huggingface上的说明中，有自己的模型合并脚本，首先将Ziya-LLaMA-13B-v1的delta权重(将近28G)以及原始LLaMA权重(40G左右)转换合并，合并结果为：
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/a62b3240-df02-444c-b219-22d410918c54)
然后我将合并后的模型使用convert.py脚本转换为ggml-model-f16.bin模型文件，这时候出现问题了。无论是将ggml-model-f16.bin模型量化为int4版本还是直接用这个模型去跑，在load model这一步都会出问题，load不进去，而且内存消耗极大（大概120G左右），想问一下大家有没有相同的问题，怎么解决的？或者有没有其他的方式能用其他模型使用llama.cpp进行量化部署？

### 依赖情况（代码类问题务必提供）

    'transformers >= 4.17.0',
    'datasets >= 2.0.0',
    'pytorch_lightning >= 1.5.10',
    'deepspeed >= 0.5.10',
    'jieba-fast >= 0.53',
    'jieba >= 0.40.0',
    torch为2.0版本

### 运行日志或截图

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/73686733/a62b3240-df02-444c-b219-22d410918c54)

**Comment by ymcui** [comment]
大概看了一下你的问题，llama.cpp的输入是pth权重，不是bin格式权重。你可以去模型对应的github问一下。
由于issue中并不是本项目的模型，这个问题就先关闭了。
