### ISSUE TITLE
merge_llama_with_chinese_lora.py模型合并报错

### ISSUE THREAD

**Issue by haoyu-lab** [ymcui/Chinese-LLaMA-Alpaca#592]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型转换和合并

### 基础模型

Alpaca-Plus-7B

### 操作系统

Linux

### 详细描述问题

**base_model**： llama模型合并Chinese-LLaMA-Plus-LoRA和Chinese-Alpaca-Plus-LoRA后获得的新模型作为base_model
**lora_model**：运行bash run_pt.sh训练获得的adapter_model.bin 以及chinese_llama_plus_lora_7b下的adapter_config.json和token文件所在的目录

报如下错误：
`(llamapython) root@autodl-container-a8e51198ae-295498a1:~/autodl-fs/Chinese-LLaMA-Alpaca# python scripts/merge_llama_with_chinese_lora.py --base_model /root/autodl-fs/Chinese-LLaMA-Alpaca/model/firstmergemodels --lora_model /root/autodl-fs/Chinese-LLaMA-Alpaca/model/pt_output/pt_lora_model/lora_model --output_type huggingface --output_dir /root/autodl-fs/Chinese-LLaMA-Alpaca/model/ptmerge_model
Base model: /root/autodl-fs/Chinese-LLaMA-Alpaca/model/firstmergemodels
LoRA model(s) ['/root/autodl-fs/Chinese-LLaMA-Alpaca/model/pt_output/pt_lora_model/lora_model']:
Loading checkpoint shards: 100%|██████████████████████████████████████████████| 2/2 [01:22<00:00, 41.38s/it]
Peft version: 0.3.0.dev0
Loading LoRA for 7B model
Loading LoRA /root/autodl-fs/Chinese-LLaMA-Alpaca/model/pt_output/pt_lora_model/lora_model...
base_model vocab size: 49954
tokenizer vocab size: 49953
Traceback (most recent call last):
  File "/root/autodl-fs/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py", line 262, in <module>
    assert len(tokenizer) >= model_vocab_size, \
AssertionError: The vocab size of the tokenizer 49953 is smaller than the vocab size of the base model 49954`
我该如何才能解决它，拜托大家了

### 运行日志或截图

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/63897264/b7402445-3aba-437f-b461-1fc9f21af512)

**Comment by ymcui** [comment]
因为你的base model已经是词表大小为49954的alpaca模型了，lora对应的tokenizer换成alpaca的试一下？

**Comment by haoyu-lab** [comment]
是否是因为我增量训练的时候，执行的run_pt.sh中chinese_tokenizer_path使用了chinese_llama_plus_lora_7b的目录

![ab475f225dbf5341d1fec44364ca3fc0](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/63897264/b48bd83a-f046-4701-8c24-be294f397b30)

**Comment by haoyu-lab** [comment]
base_model：llama模型合并Chinese-LLaMA-Plus-LoRA和Chinese-Alpaca-Plus-LoRA后获得的新模型，文件如下：
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/63897264/481929b5-f5c8-44da-a02d-5115c944cd90)
，请大家帮我看下，问题出在哪儿了，感谢！

**Comment by ymcui** [comment]
最开始训练的地方就错了，应该传入的是alpaca模型的tokenizer，因为你的基模型也是alpaca。这样训出来的模型会导致base模型和lora模型的大小就不一致，后面就没办法合并了。

**Comment by haoyu-lab** [comment]
感谢，我试试

**Comment by haoyu-lab** [comment]
> 最开始训练的地方就错了，应该传入的是alpaca模型的tokenizer，因为你的基模型也是alpaca。这样训出来的模型会导致base模型和lora模型的大小就不一致，后面就没办法合并了。

感谢，我试试

**Comment by airaria** [comment]
因为你训练的基模型是Alpaca模型，而错误搭配了LLaMA模型的tokenizer
你试试把merge_llama_with_chinese_lora.py中262-264行注释掉再合并；tokenizer还用llama tokenizer

**Comment by haoyu-lab** [comment]
> 因为你训练的基模型是Alpaca模型，而错误搭配了LLaMA模型的tokenizer 你试试把merge_llama_with_chinese_lora.py中262-264行注释掉再合并；tokenizer还用llama tokenizer

感谢您，确实是如此，采纳您的回答后解决了
