### ISSUE TITLE
请问plus模型支持的句子长度是多少？

### ISSUE THREAD

**Issue by xyfZzz** [ymcui/Chinese-LLaMA-Alpaca#593]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

其他问题

### 基础模型

LLaMA-13B

### 操作系统

Linux

### 详细描述问题

请问plus模型支持的句子长度是多少？

**Comment by airaria** [comment]
训练时使用的长度为512。
理论上实际使用时可以更长（最长不超过2048），但超过512效果可能会下降。

**Comment by ymcui** [comment]
是，你看一下技术报告吧，里面有写。

**Comment by xyfZzz** [comment]
> 是，你看一下技术报告吧，里面有写。

好的，谢谢哈

**Comment by rDearApple** [comment]
> > 训练时使用的长度为512。 理论上实际使用时可以更长（最长不超过2048），但超过512效果可能会下降。
> 
> 另外，请问下，你们的llama模型在增量预训练的时候是用lora训练的吗？



> 训练时使用的长度为512。 理论上实际使用时可以更长（最长不超过2048），但超过512效果可能会下降。

请问 512 指的单位是什么 谢谢

**Comment by machine981** [comment]
> > > 训练时使用的长度为512。 理论上实际使用时可以更长（最长不超过2048），但超过512效果可能会下降。
> > 
> > 
> > 另外，请问下，你们的llama模型在增量预训练的时候是用lora训练的吗？
> 
> > 训练时使用的长度为512。 理论上实际使用时可以更长（最长不超过2048），但超过512效果可能会下降。
> 
> 请问 512 指的单位是什么 谢谢

指的送入的token数目
