### ISSUE TITLE
chinese-alpaca-plus-13b在merge原始llama以及lora后产生了3个文件，与SHA256.md页面的内容不一致

### ISSUE THREAD

**Issue by xyfZzz** [ymcui/Chinese-LLaMA-Alpaca#598]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型转换和合并

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

chinese-alpaca-plus-13b在merge原始llama以及lora后产生了3个文件，与SHA256.md页面的内容不一致，SHA256.md页面只有2个SHA256值，而我这产生了3个bin文件，对应的3个SHA256值是：
a12f9de4bcbeceef1e54a69dcd278f0b329827781241ed9649b1bd49ea526bb1
0c98817fa2438f238024689637bce8f8d681c3942e9592fc2ad3ba18d02be5c6
e5d955cdd69b573a7998218c17e018eea4e30e5f3a35369456170dfbc289f4de
请问这是否正常？以及这3个SHA256值是否正确？

**Comment by ymcui** [comment]
贴命令和生成文件列表？

**Comment by xyfZzz** [comment]
> 

哦哦好吧，那好像没找到合并后HF格式的SHA256值

**Comment by ymcui** [comment]
你是否检查过合并前基模型和lora模型的SHA256？

**Comment by ymcui** [comment]
专门为你提的这个case手动转了一遍，你报告的SHA256没问题。
```
a12f9de4bcbeceef1e54a69dcd278f0b329827781241ed9649b1bd49ea526bb1  ../models/alpaca-plus-13b-merged/pytorch_model-00001-of-00003.bin
0c98817fa2438f238024689637bce8f8d681c3942e9592fc2ad3ba18d02be5c6  ../models/alpaca-plus-13b-merged/pytorch_model-00002-of-00003.bin
e5d955cdd69b573a7998218c17e018eea4e30e5f3a35369456170dfbc289f4de  ../models/alpaca-plus-13b-merged/pytorch_model-00003-of-00003.bin
```

**Comment by xyfZzz** [comment]
> 你是否检查过合并前基模型和lora模型的SHA256？

都检查过的

**Comment by xyfZzz** [comment]
> 专门为你提的这个case手动转了一遍，你报告的SHA256没问题。
> 
> ```
> a12f9de4bcbeceef1e54a69dcd278f0b329827781241ed9649b1bd49ea526bb1  ../models/alpaca-plus-13b-merged/pytorch_model-00001-of-00003.bin
> 0c98817fa2438f238024689637bce8f8d681c3942e9592fc2ad3ba18d02be5c6  ../models/alpaca-plus-13b-merged/pytorch_model-00002-of-00003.bin
> e5d955cdd69b573a7998218c17e018eea4e30e5f3a35369456170dfbc289f4de  ../models/alpaca-plus-13b-merged/pytorch_model-00003-of-00003.bin
> ```

感谢感谢，辛苦了
