### ISSUE TITLE
Original work hardware 

### ISSUE THREAD

**Issue by noamKayzer** [ymcui/Chinese-LLaMA-Alpaca#599]
### Check before submitting issues

- [X] Make sure to pull the latest code, as some issues and bugs have been fixed.
- [X] Due to frequent dependency updates, please ensure you have followed the steps in our [Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)
- [X] I have read the [FAQ section](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/FAQ) AND searched for similar issues and did not find a similar problem or solution
- [X] Third-party plugin issues - e.g., [llama.cpp](https://github.com/ggerganov/llama.cpp), [text-generation-webui](https://github.com/oobabooga/text-generation-webui), [LlamaChat](https://github.com/alexrozanski/LlamaChat), we recommend checking the corresponding project for solutions
- [X] Model validity check - Be sure to check the model's [SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md). If the model is incorrect, we cannot guarantee its performance

### Type of Issue

Other issues

### Base Model

None

### Operating System

Linux

### Describe your issue in detail

Thank you for your astonishing work, I want to use the concepts suggested in the paper for adapting LlaMa for new language.
For assessing the computing costs, it will be really helpful if you could share the the hardware use for training (how much GPU? What kind? How many days of training?)
Thank you!

**Comment by ymcui** [comment]
We are using NVIDIA A40 for most of our experiments, taking up to 48 GPUs, depending on the model sizes. 
Unfortunately, it is really hard to tell an exact training time for each model, as we are optimizing our training strategies from time to time. 
A rough estimate on our latest Chinese LLaMA-33B is that iterating over 20G raw text data roughly takes 10-14 days, depending on various training factors, such as training stability, inter-machine communication speed, etc.
Hope these information helps.

**Comment by noamKayzer** [comment]
Thank you for your reply!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

‫בתאריך יום ה׳, 15 ביוני 2023 ב-9:21 מאת ‪Yiming Cui‬‏ <‪
***@***.***‬‏>:‬
