### ISSUE TITLE
抱歉占用公共资源

### ISSUE THREAD

**Issue by Evani300** [ymcui/Chinese-LLaMA-Alpaca#6]
我是Evan，关注人工智能，计算机视觉，AI4Science和AIGC等领域。在我浏览Github的时候意外看到了您的项目：“ 中文LLaMA&Alpaca英语语言模型  ”， 在原版LLaMA的基础上扩充了中文词表并使用了中文数据进行二次预训练，进一步提升了中文基础语义理解能力。  在过去我们也一直在关注人工智能等加速领域的创新和骆驼(Luotuo): Chinese-alpaca-lora、BELLE团队和Openchatkit团队保持长期交流。在开源领域需要你们这样的开源布道者共同去追赶国内外大模型的性能差距，在查看了您在科大讯飞的工作经历以及您的个人主页之后，我们表示非常激动且想与您共同探讨任何潜在的商业化落地的可能性！这是我的微信：c13559870609 希望与您取得联系，已经给您发邮件了，很抱歉占用了issue资源希望得到您的谅解！

**Comment by ymcui** [comment]
感谢您对我们项目的关注。由于相关内容不属于issue，暂时关闭，感谢理解。

**Comment by Evani300** [comment]
一鸣，谢谢你的回复，希望您可以抽空浏览一下邮件~
