### ISSUE TITLE
transformer 推理，未使用GPU

### ISSUE THREAD

**Issue by suwief** [ymcui/Chinese-LLaMA-Alpaca#602]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型推理

### 基础模型

LLaMA-Plus-7B

### 操作系统

Linux

### 详细描述问题

按照 wiki  使用Transformers推理  Web图形界面交互形式  文档，使用命令行启动，命令如下：
python gradio_demo.py --base_model /home/dxl/ai/models/7B_full_model/ --gpus 0
启动后，发现在对话过程中使用CPU计算进行推理的，没使用到显卡，
服务器配置一张 华为atlas 300i pro 显卡，24G显存

### 运行日志或截图

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/39562884/1cc3a85c-1615-4834-ad47-45b073085939)

**Comment by suwief** [comment]
不知道是不是 --gpus 是怎么获取GPU信息的

计算时CPU使用情况
![914cf8d8fe5bf504570dac154e60964](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/39562884/09e81b01-c10d-4c51-ad96-0f6ff207c4bd)

NPU使用情况
![1686819589303](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/39562884/cfc79ff0-fed9-4bf7-911a-dcc205651f87)

**Comment by airaria** [comment]
目前代码仅支持由CUDA驱动的NVIDIA的显卡
其他系列的显卡需要你自己根据官方提供的指南进行适配

**Comment by suwief** [comment]
> 目前代码仅支持由CUDA驱动的NVIDIA的显卡 其他系列的显卡我们未测试过，大概率需要你自己根据官方提供的指南进行适配

谢谢，我们联系一下
