### ISSUE TITLE
全量pretrain脚本

### ISSUE THREAD

**Issue by cristianoc20** [ymcui/Chinese-LLaMA-Alpaca#606]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

你好 请问是否可以提供你们全量预训练的脚本（非lora、peft版本） 十分感谢！

**Comment by iMountTai** [comment]
我们本身就是基于lora高效精调的，没有全量预训练

**Comment by airaria** [comment]
将预训练中关于lora的部分删掉就可以了，数据处理等其他流程都一样，修改起来没什么太大难度。

**Comment by cristianoc20** [comment]
好的 其他的都不用改是吗 谢谢！
