### ISSUE TITLE
LLM技术和训练问题的微信交流群

### ISSUE THREAD

**Issue by Anna10071** [ymcui/Chinese-LLaMA-Alpaca#609]
### LLM技术和训练问题的微信交流群

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/90118245/7c4fc111-29e4-4c6e-a614-bb4507143edf)

**Comment by ymcui** [comment]
请勿重复新开贴，之前已经删过一次了，感谢理解。
你可以发在讨论区，但也只允许发一次。
