### ISSUE TITLE
请务必支持RWKV world模型

### ISSUE THREAD

**Issue by xiaol** [ymcui/Chinese-LLaMA-Alpaca#610]
目前RWKV world 7B 可以在linux,window,mac上运行，支持100+语言, 非常适合微调后做中文任务
可以测试下 RWKV runner https://github.com/josStorer/RWKV-Runner

**Comment by ymcui** [comment]
没看明白你说的**支持**是什么意思？
这个项目提供的是基于LLaMA的模型，和RWKV是完全不同的模型结构。
如果你说的是llama.cpp量化支持或者其他第三方方面的事情，建议你去对应的repo发起倡议，我们也只是应用相应的工具。

**Comment by xiaol** [comment]
rwkv.cpp已经支持了，可以接入，作为一个选择？
