### ISSUE TITLE
TypeError: smart_tokenizer_and_embedding_resize() missing 1 required positional argument: 'model'

### ISSUE THREAD

**Issue by zhaomeng0113** [ymcui/Chinese-LLaMA-Alpaca#616]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-7B

### 操作系统

Linux

### 详细描述问题

执行./run_sft.sh 时，报错：
tokenization_utils_base.py:1043] 2023-06-16 15:29:51,765 >> Using pad_token, but it is not set yet.
[ERROR|tokenization_utils_base.py:1043] 2023-06-16 15:29:51,796 >> Using pad_token, but it is not set yet.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py:462 in <module>      │
│                                                                                                  │
│   459                                                                                            │
│   460                                                                                            │
│   461 if __name__ == "__main__":                                                                 │
│ ❱ 462 │   main()                                                                                 │
│   463                                                                                            │
│                                                                                                  │
│ /home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py:311 in main          │
│                                                                                                  │
│   308 │   │   raise ValueError(f"The vocab size of the tokenizer must be 49954, but found {len   │
│   309 │   │   │   │   │   │    "Please use Chinese Alpaca tokenizer!")                           │
│   310 │   if tokenizer.pad_token is None:                                                        │
│ ❱ 311 │   │   num_new_tokens = smart_tokenizer_and_embedding_resize(                             │
│   312 │   │   │   special_tokens_dict=dict(pad_token=DEFAULT_PAD_TOKEN),                         │
│   313 │   │   │   tokenizer=tokenizer)                                                           │
│   314                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: smart_tokenizer_and_embedding_resize() missing 1 required positional argument: 'model'

### 依赖情况（代码类问题务必提供）

peft                     0.3.0.dev0
transformers             4.29.2
torch                    2.0.1

### 运行日志或截图

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/15041776/e4e7354f-0802-44f0-9b17-98983ae43077)

**Comment by zhaomeng0113** [comment]
pretrained_model=/home/ubuntu/zh-7b-plus-hf
chinese_tokenizer_path=/home/ubuntu/llama.cpp/zh-models/tokenizer.model
dataset_dir=/home/ubuntu/workspace/data
per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=100
gradient_accumulation_steps=1
output_dir=/home/ubuntu/workspace/output_sft
peft_model=/home/ubuntu/zh-7b-weight
validation_file=/home/ubuntu/workspace/data/infer.json

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 4 run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed $RANDOM \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 250 \
    --save_steps 500 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --peft_path ${peft_model} \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False

**Comment by airaria** [comment]
代码有bug，把`run_clm_sft_with_peft.py`的452行删掉
