### ISSUE TITLE
模型合并SHA256不一致

### ISSUE THREAD

**Issue by ZhangYi1212** [ymcui/Chinese-LLaMA-Alpaca#617]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型转换和合并

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

你好，我试着merge Chinese-Alpaca-Plus-13B 版本，最后检查了SHA256.md, 除了最后一步Merged files (consolidated.*.pth) 不一致，SHA256.md中其余的都一致，确认了是多lora权重合并，并未报错，tokeniser.model 的SHA256也一致，这是什么原因呢？
最终的chinese_alpaca_13B_plus_full_pth 中值为：
07e846d6d6f89a32c271c7f0b269f6a48633a2927438660de328cbe43f53b302  consolidated.00.pth
fc0b5fe1d1b2565b58d9d9d62d9e0e799cfe481bc017fee2d0b715d2b894ae29  consolidated.01.pth

您提供的文件中是：
1834558214c1dddc0d8b2826ece086908b9d2293241d0e12cecb48a035ec561b
bf70001600ce166f6ca4ef59df5510f0582cdc119fb74e27d9cf3e4c7b142015

**Comment by ymcui** [comment]
你用的是哪个脚本呢？用新脚本试一下？另外环境也报一下。
新脚本：https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_llama_with_chinese_lora_low_mem.py

**Comment by ZhangYi1212** [comment]
我用的确实是新脚本：
python ../scripts/merge_llama_with_chinese_lora_low_mem.py \
--base_model llama_13B_hf \
--lora_model chinese_llama_13B_plus_lora,chinese_alpaca_13B_plus_lora \
--output_type pth \
--output_dir chinese_alpaca_13B_plus_full_pth

测试：llama_13B_hf；chinese_llama_13B_plus_lora；chinese_llama_13B_plus_lora 的SHA256正确，跟您的文件保持一致
环境情况：
torch 2.0.1
transformers 4.28.1
peft 0.3.0
Python 3.10.11



在 2023-06-16 17:26:32，"Yiming Cui" ***@***.***> 写道：

你用的是哪个脚本呢？用新脚本试一下？另外环境也报一下。
新脚本：https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_llama_with_chinese_lora_low_mem.py

**Comment by ymcui** [comment]
方便的话可以继续用llama.cpp转为GGML格式的文件，如果还是不一致的话可能会存在一些机器特定的计算误差（之前我们也出现过，但误差在可接受范围内）。因为你已经确认原始模型的PTH文件以及我们LoRA文件的SHA256一致的话，那么一般来说不会有太大问题。

以下是Alpaca-Plus-13B转为F16格式的GGML文件SHA256：
```
807d0b55456efef8420b44e478f18ddfbbd98cbe718a95f769c1174da519a5f6  zh-alpaca-models/P13B/ggml-model-f16.bin
````

**Comment by ZhangYi1212** [comment]
好的，了解了，我试试，谢谢您的回复！！
