### ISSUE TITLE
对Alpaca-13B-plus微调后，合并模型时报size mismatch

### ISSUE THREAD

**Issue by Dusangrm** [ymcui/Chinese-LLaMA-Alpaca#618]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型转换和合并

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

首先按照Wiki中的步骤down了原llama-13b-hf、chinese-llama-plus-13b-lora、chinese-alpaca-plus-13b-lora，并执行了
python scripts/merge_llama_with_chinese_lora.py \
    --base_model path_to_original_llama_hf_dir \
    --lora_model path_to_chinese_llama_plus_lora,path_to_chinese_alpaca_plus_lora \
    --output_type [pth|huggingface] \
    --output_dir path_to_output_dir 
得到了完整的Chinese-alpaca-13B-plus模型，然后在此模型的基础上用自己的数据做指令微调，微调脚本如下：
lr=3e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/home/finchina/Chinese-LLaMA-Alpaca/model/Chinese-llama-alpaca-plus
chinese_tokenizer_path=/home/finchina/Chinese-LLaMA-Alpaca/model/Chinese-llama-alpaca-plus
dataset_dir=/home/finchina/chatglm-ft/摘要数据/train
per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=1485
gradient_accumulation_steps=8
output_dir=/home/finchina/Chinese-LLaMA-Alpaca/model/output1
peft_model=/home/finchina/chinese-alpaca-plus-lora-13b
validation_file=/home/finchina/chatglm-ft/摘要数据/alpaca_dev_belle.json

deepspeed_config_file=/home/finchina/Chinese-LLaMA-Alpaca/scripts/ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 4 scripts/run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed $RANDOM \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 5 \
    --evaluation_strategy steps \
    --eval_steps 297 \
    --save_steps 297 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length 2048 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --peft_path ${peft_model} \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False

微调成功结束后。按照
mv output/checkpoint-1188/pytorch_model.bin output/alpaca-plus-4epoch/adapter_model.bin
cp chinese-alpaca-plus-lora-13b/*token* output/alpaca-plus-4epoch
cp chinese-alpaca-plus-lora-13b/adapter_config.json output/alpaca-plus-4epoch
的命令得到微调后的lora文件。

这里因为接下来要做推理，plus模型说是只支持合并后的完整权重做推理。所以下面尝试合并微调后的13b-plus模型。

这里首先有个不明白的地方，微调后的alpaca-plus模型合并需要几个模型文件，脚本：
python scripts/merge_llama_with_chinese_lora.py \
    --base_model llama-13b-hf-transformers-4.29\
    --lora_model chinese-llama-plus-lora-13b,chinese-alpaca-plus-lora-13b,output/alpaca-plus-4epoch \
    --output_type huggingface \
    --output_dir Chinese-ft-alpaca-plus

这里的base model就是llama-13b-hf模型，lora模型分别是chinese-llama-plus-lora-13b、chinese-alpaca-plus-lora-13b、以及我微调过以后的lora文件（output/alpaca-plus-4epoch ），不管是lora_model是这三个还是去掉chinese-alpaca-plus-lora-13b，都会报同样一个错误：RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
	size mismatch for base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).

后来尝试过把base-model改成微调之前的完整的Chinese-alpaca-13B-plus模型，lora-model设成output/alpaca-plus-4epoch 。还是会报上面那个错，看了很多issues，都没能解决。

就是不明白微调plus模型以后合并完整模型该用到哪些模型文件。

### 依赖情况（代码类问题务必提供）

transformers：4.28.1
peft                  0.3.0 
pytorch           1.13.1

### 运行日志或截图

Setting ds_accelerator to cuda (auto detect)
Base model: /home/finchina/llama-13b-hf-transformers-4.29
LoRA model(s) ['/home/finchina/chinese-llama-plus-lora-13b', '/home/finchina/Chinese-LLaMA-Alpaca/model/output/alpaca-plus-4epoch']:
Loading checkpoint shards: 100%|██████████████████| 3/3 [00:10<00:00,  3.50s/it]
Peft version: 0.3.0
Loading LoRA for 13B model
Loading LoRA /home/finchina/chinese-llama-plus-lora-13b...
base_model vocab size: 32000
tokenizer vocab size: 49953
Extended vocabulary size to 49953
Loading LoRA weights
Merging with merge_and_unload...
Loading LoRA /home/finchina/Chinese-LLaMA-Alpaca/model/output/alpaca-plus-4epoch...
base_model vocab size: 49953
tokenizer vocab size: 49954
Extended vocabulary size to 49954
Loading LoRA weights
Traceback (most recent call last):
  File "/home/finchina/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py", line 268, in <module>
    raise e
  File "/home/finchina/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py", line 257, in <module>
    lora_model = PeftModel.from_pretrained(
  File "/home/finchina/anaconda3/envs/chinesealpaca/lib/python3.10/site-packages/peft/peft_model.py", line 181, in from_pretrained
    model.load_adapter(model_id, adapter_name, **kwargs)
  File "/home/finchina/anaconda3/envs/chinesealpaca/lib/python3.10/site-packages/peft/peft_model.py", line 376, in load_adapter
    set_peft_model_state_dict(self, adapters_weights, adapter_name=adapter_name)
  File "/home/finchina/anaconda3/envs/chinesealpaca/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 123, in set_peft_model_state_dict
    model.load_state_dict(peft_model_state_dict, strict=False)
  File "/home/finchina/anaconda3/envs/chinesealpaca/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
	size mismatch for base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.0.self_attn.q_proj.lora_B.default.weight: copying a param with shape torch.Size([5120, 64]) from checkpoint, the shape in current model is torch.Size([5120, 8]).
	size mismatch for base_model.model.model.layers.0.self_attn.k_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.0.self_attn.k_proj.lora_B.default.weight: copying a param with shape torch.Size([5120, 64]) from checkpoint, the shape in current model is torch.Size([5120, 8]).
	size mismatch for base_model.model.model.layers.0.self_attn.v_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.0.self_attn.v_proj.lora_B.default.weight: copying a param with shape torch.Size([5120, 64]) from checkpoint, the shape in current model is torch.Size([5120, 8]).
	size mismatch for base_model.model.model.layers.0.self_attn.o_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.0.self_attn.o_proj.lora_B.default.weight: copying a param with shape torch.Size([5120, 64]) from checkpoint, the shape in current model is torch.Size([5120, 8]).
	size mismatch for base_model.model.model.layers.0.mlp.gate_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.0.mlp.gate_proj.lora_B.default.weight: copying a param with shape torch.Size([13824, 64]) from checkpoint, the shape in current model is torch.Size([13824, 8]).
	size mismatch for base_model.model.model.layers.0.mlp.down_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 13824]) from checkpoint, the shape in current model is torch.Size([8, 13824]).
	size mismatch for base_model.model.model.layers.0.mlp.down_proj.lora_B.default.weight: copying a param with shape torch.Size([5120, 64]) from checkpoint, the shape in current model is torch.Size([5120, 8]).
	size mismatch for base_model.model.model.layers.0.mlp.up_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.0.mlp.up_proj.lora_B.default.weight: copying a param with shape torch.Size([13824, 64]) from checkpoint, the shape in current model is torch.Size([13824, 8]).
	size mismatch for base_model.model.model.layers.1.self_attn.q_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.1.self_attn.q_proj.lora_B.default.weight: copying a param with shape torch.Size([5120, 64]) from checkpoint, the shape in current model is torch.Size([5120, 8]).
	size mismatch for base_model.model.model.layers.1.self_attn.k_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.1.self_attn.k_proj.lora_B.default.weight: copying a param with shape torch.Size([5120, 64]) from checkpoint, the shape in current model is torch.Size([5120, 8]).
	size mismatch for base_model.model.model.layers.1.self_attn.v_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.1.self_attn.v_proj.lora_B.default.weight: copying a param with shape torch.Size([5120, 64]) from checkpoint, the shape in current model is torch.Size([5120, 8]).
	size mismatch for base_model.model.model.layers.1.self_attn.o_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.1.self_attn.o_proj.lora_B.default.weight: copying a param with shape torch.Size([5120, 64]) from checkpoint, the shape in current model is torch.Size([5120, 8]).
	size mismatch for base_model.model.model.layers.1.mlp.gate_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.1.mlp.gate_proj.lora_B.default.weight: copying a param with shape torch.Size([13824, 64]) from checkpoint, the shape in current model is torch.Size([13824, 8]).
	size mismatch for base_model.model.model.layers.1.mlp.down_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 13824]) from checkpoint, the shape in current model is torch.Size([8, 13824]).
	size mismatch for base_model.model.model.layers.1.mlp.down_proj.lora_B.default.weight: copying a param with shape torch.Size([5120, 64]) from checkpoint, the shape in current model is torch.Size([5120, 8]).
	size mismatch for base_model.model.model.layers.1.mlp.up_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.1.mlp.up_proj.lora_B.default.weight: copying a param with shape torch.Size([13824, 64]) from checkpoint, the shape in current model is torch.Size([13824, 8]).
	size mismatch for base_model.model.model.layers.2.self_attn.q_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.2.self_attn.q_proj.lora_B.default.weight: copying a param with shape torch.Size([5120, 64]) from checkpoint, the shape in current model is torch.Size([5120, 8]).
	size mismatch for base_model.model.model.layers.2.self_attn.k_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.2.self_attn.k_proj.lora_B.default.weight: copying a param with shape torch.Size([5120, 64]) from checkpoint, the shape in current model is torch.Size([5120, 8]).
	size mismatch for base_model.model.model.layers.2.self_attn.v_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	.....

**Comment by ymcui** [comment]
粗略看了一下，可能是你的config不对，你看一下训出来的模型对应config里lora_rank有没有修改为8（因为你训练脚本里指定的是8）？原版alpaca-plus是64。

**Comment by Dusangrm** [comment]
> 因为你已经合并过alpaca-plus-13b并基于它再做训练了，所以你在合并时，base_model可以指向你合并的alpaca-plus-13b,lora-model设成output/alpaca-plus-4epoch，到这里没有问题。
> 
> 从报错看，你的adapter_config.json和adapter_model.bin不匹配。alpaca-plus-4epoch/adapter_config.json里的rank和alpha是多少？是否与你的训练配置一致？

这是adapter_config.json的内容：
{
  "bias": "none",
  "enable_lora": null,
  "fan_in_fan_out": false,
  "inference_mode": true,
  "lora_alpha": 32,
  "lora_dropout": 0.05,
  "merge_weights": false,
  "modules_to_save": [
    "embed_tokens",
    "lm_head"
  ],
  "peft_type": "LORA",
  "r": 8,
  "target_modules": [
    "q_proj",
    "v_proj",
    "k_proj",
    "o_proj",
    "gate_proj",
    "down_proj",
    "up_proj"
  ],
  "task_type": "CAUSAL_LM"
}
lora_alpha和rank我都是修改过的。

**Comment by Dusangrm** [comment]
我不理解了，我重新微调了一次，这次训练脚本自动生成了chekpoint下的sft_lora_model，里面除了adapter_model.bin大小不正常外其他该有的文件都有了。我重新把正常大小的pytorch_model.bin移进来sft_lora_model里并且修改为adapter_model.bin后，其他文件都没有动，此时的adapter_config.json内容是：{
  "base_model_name_or_path": "/home/finchina/Chinese-LLaMA-Alpaca/model/Chinese-llama-alpaca-plus",
  "bias": "none",
  "fan_in_fan_out": false,
  "inference_mode": true,
  "init_lora_weights": true,
  "lora_alpha": 128,
  "lora_dropout": 0.05,
  "modules_to_save": [
    "embed_tokens",
    "lm_head"
  ],
  "peft_type": "LORA",
  "r": 64,
  "target_modules": [
    "q_proj",
    "v_proj",
    "k_proj",
    "o_proj",
    "gate_proj",
    "down_proj",
    "up_proj"
  ],
  "task_type": "CAUSAL_LM"
}
而我的训练脚本参数没变，lora_alpha和rank还是32和8。我没有做改动直接
python scripts/merge_llama_with_chinese_lora.py \
    --base_model /home/finchina/Chinese-LLaMA-Alpaca/model/Chinese-llama-alpaca-plus \
    --lora_model /home/finchina/Chinese-LLaMA-Alpaca/model/output1/checkpoint-1485/sft_lora_model \
    --output_type huggingface \
    --output_dir /home/finchina/Chinese-LLaMA-Alpaca/model/Chinese-ft-alpaca-plus
进行合并，这次就合并成功了。

对比两次用到的adapter_config.json，我原以为是其他内容不同造成的，遂把lora_alpha和rank改成了32和8再次合并，结果又报错：Base model: /home/finchina/Chinese-LLaMA-Alpaca/model/Chinese-llama-alpaca-plus
LoRA model(s) ['/home/finchina/Chinese-LLaMA-Alpaca/model/output1/checkpoint-1485/sft_lora_model']:
Loading checkpoint shards: 100%|██████████████████| 3/3 [00:10<00:00,  3.50s/it]
Peft version: 0.3.0
Loading LoRA for 13B model
Loading LoRA /home/finchina/Chinese-LLaMA-Alpaca/model/output1/checkpoint-1485/sft_lora_model...
base_model vocab size: 49954
tokenizer vocab size: 49954
Loading LoRA weights
Traceback (most recent call last):
  File "/home/finchina/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py", line 268, in <module>
    raise e
  File "/home/finchina/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py", line 257, in <module>
    lora_model = PeftModel.from_pretrained(
  File "/home/finchina/anaconda3/envs/chinesealpaca/lib/python3.10/site-packages/peft/peft_model.py", line 181, in from_pretrained
    model.load_adapter(model_id, adapter_name, **kwargs)
  File "/home/finchina/anaconda3/envs/chinesealpaca/lib/python3.10/site-packages/peft/peft_model.py", line 376, in load_adapter
    set_peft_model_state_dict(self, adapters_weights, adapter_name=adapter_name)
  File "/home/finchina/anaconda3/envs/chinesealpaca/lib/python3.10/site-packages/peft/utils/save_and_load.py", line 123, in set_peft_model_state_dict
    model.load_state_dict(peft_model_state_dict, strict=False)
  File "/home/finchina/anaconda3/envs/chinesealpaca/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
	size mismatch for base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight: copying a param with shape torch.Size([64, 5120]) from checkpoint, the shape in current model is torch.Size([8, 5120]).
	size mismatch for base_model.model.model.layers.0.self_attn.q_proj.lora_B.default.weight: copying a param with shape torch.Size([5120, 64]) from checkpoint, the shape in current model is torch.Size([5120, 8]).
	siz........

**Comment by airaria** [comment]
又仔细看了一下你的微调脚本，发现是同时提供了lora相关参数(lora_alpha, lora_rank等）和peft_path，这种情况下优先加载peft_path中的lora模型，而不是以提供的lora相关参数初始化新模型，所以实际上仍然是按lora_rank=64, lora_alpha=128训练。

wiki中有说明，--peft_path和lora相关参数不需要同时指定。

**Comment by Dusangrm** [comment]
好的明白了，感谢回答。
