### ISSUE TITLE
微调时遇到内存不足问题，但需要微调的参数只有很少，是否可以只加载需要微调的参数到 GPU 里？

### ISSUE THREAD

**Issue by LCG22** [ymcui/Chinese-LLaMA-Alpaca#622]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-7B

### 操作系统

Linux

### 详细描述问题

剩下的参数则加载到 CPU 里，然后在计算梯度时，再将 CPU 里所需的参数加载到 GPU 里。不知这个方法是否可行？以及是否有人已经尝试过了？

我问过 new bing ，它说：我觉得你的想法可能需要一些底层的操作，比如使用 torch.nn.Module 的 state_dict() 和 load_state_dict() 方法来获取和设置模型的参数，然后根据你的需求将部分参数转换为 GPU 张量，再重新加载到模型中。但是这样做可能会很复杂，而且可能会影响模型的性能和正确性。我不确定这样做是否可行，也没有找到一个具体的例子。

**Comment by airaria** [comment]
使用deepspeed的话有相关的优化选项，可以参考deepspeed中的offload策略和activation checkpointing策略
