### ISSUE TITLE
对于基于CLA进行pt和sft对硬件的需求

### ISSUE THREAD

**Issue by HeisenbergSu** [ymcui/Chinese-LLaMA-Alpaca#623]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-Plus-7B

### 操作系统

Linux

### 详细描述问题

请问对7bplus和13bplus针对下游任务进行pt或者sft，对GPU硬件需求大概有多大，消费级显卡单张（3090,4090 24G）足够吗？训练时间大概有多久呢，数据量有一万多条。

**Comment by airaria** [comment]
如果输入长度减小至256，24G显存可以训7B模型；
此外可以参考低精度量化等方法训练（网上很多教程，可以自行搜索），会进一步降低显存消耗
