### ISSUE TITLE
合并代码里面少了state_dict=deloreanized_sd

### ISSUE THREAD

**Issue by apachemycat** [ymcui/Chinese-LLaMA-Alpaca#624]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型转换和合并

### 基础模型

LLaMA-Plus-13B

### 操作系统

Linux

### 详细描述问题

合并代码里面少了state_dict=deloreanized_sd,的计算，我看参考的源码中有这部分
去掉这个会不会有问题？
另外，合并后的模型如何区分跟Base的差距，从尺寸大小和其他方面看，基本看不到差别。。。
lora_model_sd = lora_model.state_dict()
deloreanized_sd = {
    k.replace("base_model.model.", ""): v
    for k, v in lora_model_sd.items()
    if "lora" not in k
}

LlamaForCausalLM.save_pretrained(
    base_model, "./hf_ckpt", state_dict=deloreanized_sd, max_shard_size="400MB"
)

### 依赖情况（代码类问题务必提供）

合并代码里面少了state_dict=deloreanized_sd

### 运行日志或截图

合并代码里面少了state_dict=deloreanized_sd

**Comment by airaria** [comment]
1. 合并过程可以有多种实现；我们目前的合并代码经过测试是能正确合并模型；如果合并结果的确有问题，我们会进行修复。
2. 合并后的模型会稍微大一点（embedding变大了），除此之外模型结构上没有变化；所以在合并时要仔细检查输入的基模型和lora的正确性，以及对比SHA256，确保结果正确。

**Comment by apachemycat** [comment]
**lora_model.train(False)**

# did we do anything?
assert not torch.allclose(first_weight_old, first_weight)

lora_model_sd = lora_model.state_dict()
deloreanized_sd = {
    k.replace("base_model.model.", ""): v
    for k, v in lora_model_sd.items()
    if "lora" not in k
}

LlamaForCausalLM.save_pretrained(
    base_model, "./hf_ckpt", **state_dict=deloreanized_sd**, max_shard_size="400MB"
)
他的代码中多了两个调用，你们代码中没有，这两个地方调用去掉是否有问题？？
https://github.com/tloen/alpaca-lora/blob/main/export_hf_checkpoint.py

**Comment by ymcui** [comment]
没什么问题，转出来的SHA256是一样的。
