### ISSUE TITLE
sft精调epoch设置问题

### ISSUE THREAD

**Issue by yangxingrui** [ymcui/Chinese-LLaMA-Alpaca#625]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-7B

### 操作系统

Linux

### 详细描述问题

sft.sh成功运行，但我始终没找到epoch数目的设置位置，我的精调数据集大小是3000，epoch在0.03时停止，我调整了精调数据集数据量发现epoch数量也会变化，精调数据集大小是12000时，epoch在0.01时停止，这是否意味着epoch是动态变化的？这又是由哪个设置项决定的呢？

### 运行日志或截图

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/95137682/e30ca6dc-8461-44d8-8aa2-6937b1029ed6)

**Comment by yangxingrui** [comment]
另外，精调之后的模型大小是39M，这是否合理呢？
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/95137682/798894d8-2ee3-4e81-8828-3e1abda69304)

**Comment by iMountTai** [comment]
可以参考[TrainingArguments](https://huggingface.co/docs/transformers/v4.30.0/en/main_classes/trainer#transformers.TrainingArguments)中的参数设置epoch。至于模型大小是否合理，可以打印权重看看设置的可训练参数是否有都正常保存了。

**Comment by TClan8023** [comment]
我理解应该是由training_steps控制的，每次都固定训练N步，你的数据集量越大，对应训练完成的epoch数值越小。
