### ISSUE TITLE
使用metal版llama运行时全是乱码

### ISSUE THREAD

**Issue by Mabbs** [ymcui/Chinese-LLaMA-Alpaca#626]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

效果问题

### 基础模型

Alpaca-Plus-7B

### 操作系统

macOS

### 详细描述问题

使用最新版llama.cpp使用metal方式编译的版本在使用4k量化时全是乱码
（8g内存）

### 依赖情况（代码类问题务必提供）

无

### 运行日志或截图

-> % ./main -m models/ggml-model-q4_K.bin --color -f ./prompts/alpaca.txt -ins -ngl 1                                
main: build = 702 (b241649)
main: seed  = 1687030559
llama.cpp: loading model from models/ggml-model-q4_K.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 49954
llama_model_load_internal: n_ctx      = 512
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 15 (mostly Q4_K - Medium)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.07 MB
llama_model_load_internal: mem required  = 5780.29 MB (+ 1026.00 MB per state)
................................................................................................
llama_init_from_file: kv self size  =  256.00 MB
ggml_metal_init: allocating
ggml_metal_init: using MPS
ggml_metal_init: loading '/Users/mayx/llama.cpp/ggml-metal.metal'
ggml_metal_init: loaded kernel_add                            0x11ff08ba0
ggml_metal_init: loaded kernel_mul                            0x11ff09120
ggml_metal_init: loaded kernel_mul_row                        0x11ff09640
ggml_metal_init: loaded kernel_scale                          0x11ff09b60
ggml_metal_init: loaded kernel_silu                           0x11ff0a080
ggml_metal_init: loaded kernel_relu                           0x11ff0a5a0
ggml_metal_init: loaded kernel_gelu                           0x11ff0aac0
ggml_metal_init: loaded kernel_soft_max                       0x11ff0b170
ggml_metal_init: loaded kernel_diag_mask_inf                  0x11ff0b7d0
ggml_metal_init: loaded kernel_get_rows_f16                   0x11ff0be50
ggml_metal_init: loaded kernel_get_rows_q4_0                  0x11ff0c4d0
ggml_metal_init: loaded kernel_get_rows_q4_1                  0x11ff0ccc0
ggml_metal_init: loaded kernel_get_rows_q2_k                  0x11ff0d340
ggml_metal_init: loaded kernel_get_rows_q3_k                  0x11ff0d9c0
ggml_metal_init: loaded kernel_get_rows_q4_k                  0x11ff0e040
ggml_metal_init: loaded kernel_get_rows_q5_k                  0x11ff0e6c0
ggml_metal_init: loaded kernel_get_rows_q6_k                  0x11ff0ed40
ggml_metal_init: loaded kernel_rms_norm                       0x11ff0f3f0
ggml_metal_init: loaded kernel_norm                           0x11ff0faa0
ggml_metal_init: loaded kernel_mul_mat_f16_f32                0x11fe05de0
ggml_metal_init: loaded kernel_mul_mat_q4_0_f32               0x11fe065e0
ggml_metal_init: loaded kernel_mul_mat_q4_1_f32               0x11fe06cc0
ggml_metal_init: loaded kernel_mul_mat_q2_k_f32               0x11fe073a0
ggml_metal_init: loaded kernel_mul_mat_q3_k_f32               0x11ff10490
ggml_metal_init: loaded kernel_mul_mat_q4_k_f32               0x11ff10b70
ggml_metal_init: loaded kernel_mul_mat_q5_k_f32               0x11ff11250
ggml_metal_init: loaded kernel_mul_mat_q6_k_f32               0x11ff11930
ggml_metal_init: loaded kernel_rope                           0x11ff12420
ggml_metal_init: loaded kernel_alibi_f32                      0x11ff12ce0
ggml_metal_init: loaded kernel_cpy_f32_f16                    0x11fe07b10
ggml_metal_init: loaded kernel_cpy_f32_f32                    0x11fe084c0
ggml_metal_init: loaded kernel_cpy_f16_f16                    0x11fe08d50
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  3988.89 MB
ggml_metal_add_buffer: allocated 'eval            ' buffer, size =   768.00 MB
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =   258.00 MB
ggml_metal_add_buffer: allocated 'scr0            ' buffer, size =   512.00 MB
ggml_metal_add_buffer: allocated 'scr1            ' buffer, size =   512.00 MB

system_info: n_threads = 4 / 8 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 | 
main: interactive mode on.
Reverse prompt: '### Instruction:

'
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.800000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 512, n_batch = 512, n_predict = -1, n_keep = 21

== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.

 Below is an instruction that describes a task. Write a response that appropriately completes the request.
> 你是谁？
我是H标签anansaAiiA-三3提示余AIACAIPIPIPERPIOTOTOTPIPIPIAITCHPITオΘSPIOT訓T緊オOTTERPISE布里OTTTHTTIALALSDEPRオ？OTOTSEPI訓療EROTAPT將US療ALTTDERUSEWSFTSTオ緊TP謝LET使用オSE緊ALS訓SS訓再次IFSTF療佩O提供SS這些SSES產[S緊SESSSSTERUTC人工SWSESWS在USTERS療WS
> 

llama_print_timings:        load time =  3300.70 ms
llama_print_timings:      sample time =   253.91 ms /   140 runs   (    1.81 ms per token)
llama_print_timings: prompt eval time =  6323.23 ms /    43 tokens (  147.05 ms per token)
llama_print_timings:        eval time = 19523.73 ms /   140 runs   (  139.46 ms per token)
llama_print_timings:       total time = 39165.70 ms

**Comment by ymcui** [comment]
我刚刚试了一下没有问题。
你可以排查：
1）`-ngl 0`解码是否正常？
2）回退到其他版本解码是否正常？

测试log：
```
+ ./main -m zh-alpaca-models/P7b/ggml-model-q4_k.bin --color -f ./prompts/zh-alpaca.txt -ins -b 24 -c 2048 -t 8 --temp 0.5 --top_k 40 --top_p 0.9 --repeat_penalty 1.1 -ngl 1
main: build = 702 (b241649)
main: seed  = 1687047478
llama.cpp: loading model from zh-alpaca-models/P7b/ggml-model-q4_k.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 49954
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 15 (mostly Q4_K - Medium)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.07 MB
llama_model_load_internal: mem required  = 5780.29 MB (+ 1026.00 MB per state)
................................................................................................
llama_init_from_file: kv self size  = 1024.00 MB
ggml_metal_init: allocating
ggml_metal_init: using MPS
ggml_metal_init: loading '/llama.cpp/ggml-metal.metal'
ggml_metal_init: loaded kernel_add                            0x129706e00
ggml_metal_init: loaded kernel_mul                            0x129707840
ggml_metal_init: loaded kernel_mul_row                        0x129708110
ggml_metal_init: loaded kernel_scale                          0x129708970
ggml_metal_init: loaded kernel_silu                           0x129709140
ggml_metal_init: loaded kernel_relu                           0x129709910
ggml_metal_init: loaded kernel_gelu                           0x12970a0e0
ggml_metal_init: loaded kernel_soft_max                       0x12970a630
ggml_metal_init: loaded kernel_diag_mask_inf                  0x12970ab80
ggml_metal_init: loaded kernel_get_rows_f16                   0x100f06520
ggml_metal_init: loaded kernel_get_rows_q4_0                  0x100f06be0
ggml_metal_init: loaded kernel_get_rows_q4_1                  0x100f072a0
ggml_metal_init: loaded kernel_get_rows_q2_k                  0x100f077f0
ggml_metal_init: loaded kernel_get_rows_q3_k                  0x1010042b0
ggml_metal_init: loaded kernel_get_rows_q4_k                  0x101004970
ggml_metal_init: loaded kernel_get_rows_q5_k                  0x101004ec0
ggml_metal_init: loaded kernel_get_rows_q6_k                  0x101005410
ggml_metal_init: loaded kernel_rms_norm                       0x101005960
ggml_metal_init: loaded kernel_norm                           0x101005eb0
ggml_metal_init: loaded kernel_mul_mat_f16_f32                0x1010066f0
ggml_metal_init: loaded kernel_mul_mat_q4_0_f32               0x100f07c20
ggml_metal_init: loaded kernel_mul_mat_q4_1_f32               0x100f081d0
ggml_metal_init: loaded kernel_mul_mat_q2_k_f32               0x100f08720
ggml_metal_init: loaded kernel_mul_mat_q3_k_f32               0x100f08df0
ggml_metal_init: loaded kernel_mul_mat_q4_k_f32               0x100f09340
ggml_metal_init: loaded kernel_mul_mat_q5_k_f32               0x100f09890
ggml_metal_init: loaded kernel_mul_mat_q6_k_f32               0x100f09de0
ggml_metal_init: loaded kernel_rope                           0x100f0a530
ggml_metal_init: loaded kernel_alibi_f32                      0x100f0aa80
ggml_metal_init: loaded kernel_cpy_f32_f16                    0x100f0afd0
ggml_metal_init: loaded kernel_cpy_f32_f32                    0x100f0b520
ggml_metal_init: loaded kernel_cpy_f16_f16                    0x100f0ba70
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  3988.89 MB
ggml_metal_add_buffer: allocated 'eval            ' buffer, size =   768.00 MB
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  1026.00 MB
ggml_metal_add_buffer: allocated 'scr0            ' buffer, size =   512.00 MB
ggml_metal_add_buffer: allocated 'scr1            ' buffer, size =   512.00 MB

system_info: n_threads = 8 / 10 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 |
main: interactive mode on.
Reverse prompt: '### Instruction:

'
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.900000, typical_p = 1.000000, temp = 0.500000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 2048, n_batch = 24, n_predict = -1, n_keep = 23


== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.

 Below is an instruction that describes a task. Write a detailed response that appropriately completes the request.
> 你是谁
我是 ChatGPT，一个由 OpenAI 训练的大型语言模型。
> 那你能做什么
作为一个大型语言模型，我可以回答各种问题、提供建议和帮助解决问题。我也可以通过文本生成来创作新的内容，例如故事或文章。此外，我还可以用于自然语言处理任务，如语音识别和机器翻译等。
>

llama_print_timings:        load time =  4850.55 ms
llama_print_timings:      sample time =   101.88 ms /    68 runs   (    1.50 ms per token)
llama_print_timings: prompt eval time =  2067.64 ms /    66 tokens (   31.33 ms per token)
llama_print_timings:        eval time =  2229.05 ms /    68 runs   (   32.78 ms per token)
llama_print_timings:       total time = 20899.86 ms
```

**Comment by Mabbs** [comment]
> 我刚刚试了一下没有问题。 你可以排查： 1）`-ngl 0`解码是否正常？ 2）回退到其他版本解码是否正常？
> 
> 测试log：
> 
> ```
> + ./main -m zh-alpaca-models/P7b/ggml-model-q4_k.bin --color -f ./prompts/zh-alpaca.txt -ins -b 24 -c 2048 -t 8 --temp 0.5 --top_k 40 --top_p 0.9 --repeat_penalty 1.1 -ngl 1
> main: build = 702 (b241649)
> main: seed  = 1687047478
> llama.cpp: loading model from zh-alpaca-models/P7b/ggml-model-q4_k.bin
> llama_model_load_internal: format     = ggjt v3 (latest)
> llama_model_load_internal: n_vocab    = 49954
> llama_model_load_internal: n_ctx      = 2048
> llama_model_load_internal: n_embd     = 4096
> llama_model_load_internal: n_mult     = 256
> llama_model_load_internal: n_head     = 32
> llama_model_load_internal: n_layer    = 32
> llama_model_load_internal: n_rot      = 128
> llama_model_load_internal: ftype      = 15 (mostly Q4_K - Medium)
> llama_model_load_internal: n_ff       = 11008
> llama_model_load_internal: n_parts    = 1
> llama_model_load_internal: model size = 7B
> llama_model_load_internal: ggml ctx size =    0.07 MB
> llama_model_load_internal: mem required  = 5780.29 MB (+ 1026.00 MB per state)
> ................................................................................................
> llama_init_from_file: kv self size  = 1024.00 MB
> ggml_metal_init: allocating
> ggml_metal_init: using MPS
> ggml_metal_init: loading '/llama.cpp/ggml-metal.metal'
> ggml_metal_init: loaded kernel_add                            0x129706e00
> ggml_metal_init: loaded kernel_mul                            0x129707840
> ggml_metal_init: loaded kernel_mul_row                        0x129708110
> ggml_metal_init: loaded kernel_scale                          0x129708970
> ggml_metal_init: loaded kernel_silu                           0x129709140
> ggml_metal_init: loaded kernel_relu                           0x129709910
> ggml_metal_init: loaded kernel_gelu                           0x12970a0e0
> ggml_metal_init: loaded kernel_soft_max                       0x12970a630
> ggml_metal_init: loaded kernel_diag_mask_inf                  0x12970ab80
> ggml_metal_init: loaded kernel_get_rows_f16                   0x100f06520
> ggml_metal_init: loaded kernel_get_rows_q4_0                  0x100f06be0
> ggml_metal_init: loaded kernel_get_rows_q4_1                  0x100f072a0
> ggml_metal_init: loaded kernel_get_rows_q2_k                  0x100f077f0
> ggml_metal_init: loaded kernel_get_rows_q3_k                  0x1010042b0
> ggml_metal_init: loaded kernel_get_rows_q4_k                  0x101004970
> ggml_metal_init: loaded kernel_get_rows_q5_k                  0x101004ec0
> ggml_metal_init: loaded kernel_get_rows_q6_k                  0x101005410
> ggml_metal_init: loaded kernel_rms_norm                       0x101005960
> ggml_metal_init: loaded kernel_norm                           0x101005eb0
> ggml_metal_init: loaded kernel_mul_mat_f16_f32                0x1010066f0
> ggml_metal_init: loaded kernel_mul_mat_q4_0_f32               0x100f07c20
> ggml_metal_init: loaded kernel_mul_mat_q4_1_f32               0x100f081d0
> ggml_metal_init: loaded kernel_mul_mat_q2_k_f32               0x100f08720
> ggml_metal_init: loaded kernel_mul_mat_q3_k_f32               0x100f08df0
> ggml_metal_init: loaded kernel_mul_mat_q4_k_f32               0x100f09340
> ggml_metal_init: loaded kernel_mul_mat_q5_k_f32               0x100f09890
> ggml_metal_init: loaded kernel_mul_mat_q6_k_f32               0x100f09de0
> ggml_metal_init: loaded kernel_rope                           0x100f0a530
> ggml_metal_init: loaded kernel_alibi_f32                      0x100f0aa80
> ggml_metal_init: loaded kernel_cpy_f32_f16                    0x100f0afd0
> ggml_metal_init: loaded kernel_cpy_f32_f32                    0x100f0b520
> ggml_metal_init: loaded kernel_cpy_f16_f16                    0x100f0ba70
> ggml_metal_add_buffer: allocated 'data            ' buffer, size =  3988.89 MB
> ggml_metal_add_buffer: allocated 'eval            ' buffer, size =   768.00 MB
> ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  1026.00 MB
> ggml_metal_add_buffer: allocated 'scr0            ' buffer, size =   512.00 MB
> ggml_metal_add_buffer: allocated 'scr1            ' buffer, size =   512.00 MB
> 
> system_info: n_threads = 8 / 10 | AVX = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | VSX = 0 |
> main: interactive mode on.
> Reverse prompt: '### Instruction:
> 
> '
> sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.900000, typical_p = 1.000000, temp = 0.500000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
> generate: n_ctx = 2048, n_batch = 24, n_predict = -1, n_keep = 23
> 
> 
> == Running in interactive mode. ==
>  - Press Ctrl+C to interject at any time.
>  - Press Return to return control to LLaMa.
>  - To return control without starting a new line, end your input with '/'.
>  - If you want to submit another line, end your input with '\'.
> 
>  Below is an instruction that describes a task. Write a detailed response that appropriately completes the request.
> > 你是谁
> 我是 ChatGPT，一个由 OpenAI 训练的大型语言模型。
> > 那你能做什么
> 作为一个大型语言模型，我可以回答各种问题、提供建议和帮助解决问题。我也可以通过文本生成来创作新的内容，例如故事或文章。此外，我还可以用于自然语言处理任务，如语音识别和机器翻译等。
> >
> 
> llama_print_timings:        load time =  4850.55 ms
> llama_print_timings:      sample time =   101.88 ms /    68 runs   (    1.50 ms per token)
> llama_print_timings: prompt eval time =  2067.64 ms /    66 tokens (   31.33 ms per token)
> llama_print_timings:        eval time =  2229.05 ms /    68 runs   (   32.78 ms per token)
> llama_print_timings:       total time = 20899.86 ms
> ```

应该是单纯爆内存了，我刚刚试了一下3k量化的可以正常运行
