### ISSUE TITLE
一机多卡微调

### ISSUE THREAD

**Issue by zzx16045223** [ymcui/Chinese-LLaMA-Alpaca#627]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

lr=2e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/zzx/Chinese-LLaMA-Alpaca/model/merge_chinese_alpaca_plus_13b
chinese_tokenizer_path=/zzx/Chinese-LLaMA-Alpaca/model/merge_chinese_alpaca_plus_13b
dataset_dir=/zzx/Chinese-LLaMA-Alpaca/data
data_cache=/zzx/Chinese-LLaMA-Alpaca/data/data_tmp
per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=10  # 默认100
gradient_accumulation_steps=1
output_dir=/zzx/Chinese-LLaMA-Alpaca/output

deepspeed_config_file=ds_zero2_no_offload.json

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nnodes 1 --nproc_per_node 8 run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --seed $RANDOM \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 500 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --block_size 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --ddp_find_unused_parameters False

### 依赖情况（代码类问题务必提供）

peft                        0.3.0
torch                       2.0.1
transformers                4.28.1

### 运行日志或截图

![8734467d1cf6f6ca040bacf37d504d5](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/46176408/e0c610c0-bc2b-401c-a69c-05eb7ce3c860)

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26670 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26671 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26672 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26674 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26675 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26676 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26677 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 3 (pid: 26673) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
run_clm_pt_with_peft.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-18_13:49:36
  host      : 5ea5c16a9c40
  rank      : 3 (local_rank: 3)
  exitcode  : -9 (pid: 26673)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 26673
======================================================

**Comment by wuxiulike** [comment]
torch版本貌似应该是
torch                    2.0.0+cu118
torchaudio               2.0.1+cu118
torchvision              0.15.1+cu118

试下这个安装
pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118

**Comment by wuxiulike** [comment]
另外：你的peft版本也不对
pip install git+https://github.com/huggingface/peft.git@13e53fc
（很重要，否则报错）

**Comment by zzx16045223** [comment]
我重新pip了一下，还是同样的问题
一机八卡是这样跑的吗？
![2a7323dac4e4d11d6d07196bd437753](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/46176408/15b8a1f3-9dbc-48a3-8e7a-91bbb60117b2)

**Comment by wuxiulike** [comment]
你pip list看看，是否更新，如果还是这两个版本，应该跑不通
peft 0.3.0
torch 2.0.1
------------------------
需要更新到：
peft 0.3.0.dev0
torch 2.0.0+cu118


> 我重新pip了一下，还是同样的问题 一机八卡是这样跑的吗？ ![2a7323dac4e4d11d6d07196bd437753](https://user-images.githubusercontent.com/46176408/246651627-15b8a1f3-9dbc-48a3-8e7a-91bbb60117b2.png)

我试过，多卡就是改后面那个8

**Comment by zzx16045223** [comment]
> ## 你pip list看看，是否更新，如果还是这两个版本，应该跑不通
> peft 0.3.0
> torch 2.0.1
> 需要更新到： peft 0.3.0.dev0 torch 2.0.0+cu118
> 
> > 我重新pip了一下，还是同样的问题 一机八卡是这样跑的吗？ ![2a7323dac4e4d11d6d07196bd437753](https://user-images.githubusercontent.com/46176408/246651627-15b8a1f3-9dbc-48a3-8e7a-91bbb60117b2.png)
> 
> 我试过，多卡就是改后面那个8

已经更新过来了，可以方便加个微信请教你一下吗，我手机号13607068804
![b2d2e474c517f1fcc317c3f82157e2e](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/46176408/1fceba1e-b0f4-4d5c-a45b-0b60c456d564)

![44be7e693510352422c2782bb7037e5](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/46176408/5c1eee7f-d384-4572-8ec8-2620ef478ff8)

**Comment by iMountTai** [comment]
机器内存多少？不是显存

**Comment by zzx16045223** [comment]
> 机器内存多少？不是显存
还有很大内存
![a2c00757157dfe21990163b6c94ceee](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/46176408/847259e6-ed78-48a5-81f4-fdd3471bb3b1)

**Comment by iMountTai** [comment]
free也就193G，运行中查看一下内存是否够用
