### ISSUE TITLE
AttributeError: 'list' object has no attribute 'keys'  ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 35959) of binary: 

### ISSUE THREAD

**Issue by zzx16045223** [ymcui/Chinese-LLaMA-Alpaca#629]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

运行脚本
lr=1e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/zzx/Chinese-LLaMA-Alpaca/model/merge_chinese_alpaca_7b
chinese_tokenizer_path=/zzx/Chinese-LLaMA-Alpaca/model/merge_chinese_alpaca_7b
dataset_dir=/zzx/Chinese-LLaMA-Alpaca/data/alpaca_data
per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=100
gradient_accumulation_steps=1
output_dir=/zzx/Chinese-LLaMA-Alpaca/output/sft
peft_model=/zzx/Chinese-LLaMA-Alpaca/model/Chinese-Alpaca-7B
validation_file=/zzx/Chinese-LLaMA-Alpaca/output/sft

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 1 run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed $RANDOM \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 250 \
    --save_steps 500 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --peft_path ${peft_model} \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False

### 依赖情况（代码类问题务必提供）

absl-py                     1.4.0
accelerate                  0.20.3
aiofiles                    23.1.0
aiohttp                     3.8.4
aiosignal                   1.3.1
altair                      5.0.1
antlr4-python3-runtime      4.9.3
anyio                       3.7.0
appdirs                     1.4.4
asttokens                   2.0.5
astunparse                  1.6.3
async-timeout               4.0.2
attrs                       23.1.0
automaton                   3.1.0
Babel                       2.12.1
backcall                    0.2.0
bce-python-sdk              0.8.83
beautifulsoup4              4.12.2
blinker                     1.6.2
boltons                     23.0.0
boto3                       1.21.42
botocore                    1.24.46
brotlipy                    0.7.0
bs4                         0.0.1
cachetools                  5.3.1
certifi                     2023.5.7
cffi                        1.15.1
chardet                     4.0.0
charset-normalizer          2.0.4
click                       8.1.3
cmake                       3.25.0
cobble                      0.1.3
colorama                    0.4.6
colorlog                    6.7.0
conda                       23.3.1
conda-build                 3.24.0
conda-content-trust         0.1.3
conda-package-handling      2.0.2
conda_package_streaming     0.7.0
contourpy                   1.0.7
cryptography                39.0.1
cycler                      0.11.0
datasets                    2.0.0
debtcollector               2.5.0
decorator                   5.1.1
deepspeed                   0.9.4
diffusers                   0.7.2
dill                        0.3.4
dnspython                   2.3.0
docker-pycreds              0.4.0
docx                        0.2.4
docx2txt                    0.8
einops                      0.3.0
exceptiongroup              1.1.1
executing                   0.8.3
expecttest                  0.1.4
fastapi                     0.97.0
fasteners                   0.18
ffmpy                       0.3.0
filelock                    3.9.0
flagai                      1.7.2
Flask                       2.3.2
Flask-Babel                 2.0.0
fonttools                   4.40.0
frozenlist                  1.3.3
fschat                      0.2.13       /zzx/FastChat
fsspec                      2023.6.0
ftfy                        6.1.1
future                      0.18.3
futurist                    2.4.1
gitdb                       4.0.10
GitPython                   3.1.31
glob2                       0.7
gmpy2                       2.1.2
google-auth                 2.20.0
google-auth-oauthlib        0.4.6
gradio                      3.23.0
grpcio                      1.54.2
h11                         0.14.0
hjson                       3.1.0
httpcore                    0.17.2
httpx                       0.24.1
huggingface-hub             0.15.1
hypothesis                  6.75.2
idna                        3.4
importlib-metadata          6.6.0
ipython                     8.12.0
iso8601                     2.0.0
itsdangerous                2.1.2
jedi                        0.18.1
jieba                       0.42.1
Jinja2                      3.1.2
jmespath                    1.0.1
joblib                      1.2.0
jsonpatch                   1.32
jsonpointer                 2.1
jsonschema                  4.17.3
kiwisolver                  1.4.4
libarchive-c                2.9
linkify-it-py               2.0.2
lit                         15.0.7
lxml                        4.9.2
mammoth                     1.6.0
Markdown                    3.4.3
markdown-it-py              2.2.0
markdown2                   2.4.8
MarkupSafe                  2.1.1
matplotlib                  3.7.1
matplotlib-inline           0.1.6
mdit-py-plugins             0.3.3
mdurl                       0.1.2
mkl-fft                     1.3.6
mkl-random                  1.2.2
mkl-service                 2.4.0
mpmath                      1.3.0
msgpack                     1.0.5
multidict                   6.0.4
multiprocess                0.70.12.2
netaddr                     0.8.0
netifaces                   0.11.0
networkx                    2.8.4
nh3                         0.2.13
ninja                       1.11.1
nltk                        3.6.7
numpy                       1.24.3
oauthlib                    3.2.2
omegaconf                   2.3.0
orjson                      3.9.1
oslo.i18n                   6.0.0
oslo.serialization          5.1.1
oslo.utils                  6.1.0
packaging                   23.0
paddle2onnx                 1.0.6
paddlefsl                   1.1.0
paddlenlp                   2.5.2
pandas                      1.3.5
parso                       0.8.3
pathtools                   0.1.2
pbr                         5.11.1
peft                        0.3.0.dev0
pexpect                     4.8.0
pickleshare                 0.7.5
Pillow                      9.4.0
pip                         23.1.2
pkginfo                     1.9.6
pluggy                      1.0.0
portalocker                 2.7.0
prettytable                 3.8.0
prompt-toolkit              3.0.36
protobuf                    3.19.6
psutil                      5.9.0
ptyprocess                  0.7.0
pure-eval                   0.2.2
py-cpuinfo                  9.0.0
pyarrow                     12.0.1
pyasn1                      0.5.0
pyasn1-modules              0.3.0
pycosat                     0.6.4
pycparser                   2.21
pycryptodome                3.18.0
pydantic                    1.10.9
pyDeprecate                 0.3.2
pydot                       1.4.2
pydub                       0.25.1
Pygments                    2.15.1
pyOpenSSL                   23.0.0
pyparsing                   3.0.9
pyrsistent                  0.19.3
PySocks                     1.7.1
python-dateutil             2.8.2
python-docx                 0.8.11
python-etcd                 0.4.5
python-multipart            0.0.6
pytorch-lightning           1.6.5
pytz                        2022.7
PyYAML                      6.0
regex                       2023.6.3
requests                    2.29.0
requests-oauthlib           1.3.1
responses                   0.18.0
rich                        13.4.2
rouge-score                 0.1.2
rsa                         4.9
ruamel.yaml                 0.17.21
ruamel.yaml.clib            0.2.6
s3transfer                  0.5.2
sacrebleu                   2.3.1
scikit-learn                1.0.2
scipy                       1.10.1
semantic-version            2.10.0
sentencepiece               0.1.97
sentry-sdk                  1.25.1
seqeval                     1.2.2
setproctitle                1.3.2
setuptools                  59.5.0
shortuuid                   1.0.11
six                         1.16.0
smmap                       5.0.0
sniffio                     1.3.0
sortedcontainers            2.4.0
soupsieve                   2.4
stack-data                  0.2.0
starlette                   0.27.0
stevedore                   5.1.0
svgwrite                    1.4.3
sympy                       1.11.1
tabulate                    0.9.0
taming-transformers-rom1504 0.0.6
taskflow                    5.2.0
tenacity                    8.2.2
tensorboard                 2.9.0
tensorboard-data-server     0.6.1
tensorboard-plugin-wit      1.8.1
threadpoolctl               3.1.0
tiktoken                    0.4.0
tokenizers                  0.12.1
tomli                       2.0.1
toolz                       0.12.0
torch                       2.0.0+cu118
torchaudio                  2.0.1+cu118
torchdata                   0.6.1
torchelastic                0.2.2
torchmetrics                0.11.4
torchtext                   0.15.2
torchvision                 0.15.1+cu118
tqdm                        4.65.0
traitlets                   5.7.1
transformers                4.28.1
triton                      2.0.0
typer                       0.9.0
types-dataclasses           0.6.6
typing_extensions           4.5.0
tzdata                      2023.3
uc-micro-py                 1.0.2
urllib3                     1.26.15
uvicorn                     0.22.0
visualdl                    2.4.2
wandb                       0.15.4
wavedrom                    2.0.3.post3
wcwidth                     0.2.5
websockets                  11.0.3
Werkzeug                    2.3.6
wheel                       0.38.4
wrapt                       1.15.0
xxhash                      3.2.0
yarl                        1.9.2
zipp                        3.15.0
zstandard                   0.19.0

### 运行日志或截图

![1687086834195](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/46176408/31f40c1d-012b-4dd4-83e7-844b1b399e5a)

**Comment by iMountTai** [comment]
`validation_file`是json文件，不是文件夹，运行脚本前应该先仔细阅读wiki[指令精调脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E6%8C%87%E4%BB%A4%E7%B2%BE%E8%B0%83%E8%84%9A%E6%9C%AC)。

**Comment by zzx16045223** [comment]
> `validation_file`是json文件，不是文件夹，运行脚本前应该先仔细阅读wiki[指令精调脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E6%8C%87%E4%BB%A4%E7%B2%BE%E8%B0%83%E8%84%9A%E6%9C%AC)。 ![image](https://user-images.githubusercontent.com/35353688/246662239-8a842088-f674-4181-ad4d-f33b0bbc55a8.png)

是json文件，只不过我用的是一样的
![1baabaab06a485922859700f5fa3606](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/46176408/527d39d4-1eff-49cf-be53-a830c4f7f962)

**Comment by iMountTai** [comment]
可是你前面贴出来的命令`validation_file=/zzx/Chinese-LLaMA-Alpaca/output/sft`。现在还是报相同的错误吗？

**Comment by zzx16045223** [comment]
> 可是你前面贴出来的命令`validation_file=/zzx/Chinese-LLaMA-Alpaca/output/sft`。现在还是报相同的错误吗？

是的，我刚开始没注意，后面我改过来了，还是同样的错误

**Comment by zzx16045223** [comment]
![86300a75d87a02d4082d2146eb8e964](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/46176408/41ac508e-6d0e-4f4a-8584-2c282e2a4f8d)
你可以看一下

**Comment by zzx16045223** [comment]
> 删除cache目录然后重新运行代码，再发一下`data`目录下的文件结构

![47b889ae7767f9639b7b7c3f1d34ece](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/46176408/e5a1a5f9-6b88-4861-a357-2fc968045db5)
还有这

**Comment by iMountTai** [comment]
pull的是最新代码及数据吗？我重新运行相关代码，未复现您的问题。

**Comment by Gavingx** [comment]
> 删除cache目录然后重新运行代码，再发一下`data`目录下的文件结构

我也遇到了同样的问题，想请问下，命令行参数中没有指定cache路径，默认路径在哪里？

**Comment by airaria** [comment]
> > 删除cache目录然后重新运行代码，再发一下`data`目录下的文件结构
> 
> 我也遇到了同样的问题，想请问下，命令行参数中没有指定cache路径，默认路径在哪里？

cache位于训练数据文件的的同名目录下

**Comment by Gavingx** [comment]
> > > 删除cache目录然后重新运行代码，再发一下`data`目录下的文件结构
> > 
> > 
> > 我也遇到了同样的问题，想请问下，命令行参数中没有指定cache路径，默认路径在哪里？
> 
> cache位于训练数据文件的的同名目录下

你是说data的cache吗？ 我试着删除了，但还是报这个错误。

**Comment by airaria** [comment]
把validation_file放到其他文件夹（不要放到训练数据的文件夹dataset_dir）试试

**Comment by Gavingx** [comment]
> 把validation_file放到其他文件夹（不要放到训练数据的文件夹dataset_dir）试试
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/43789460/7f146757-59b1-4bf4-b0d1-b21b45ad4ac3)
validation_file跟训练数据不是一个文件夹下，如图，你的意思是还要将validation.json再往上移一个目录吗
