### ISSUE TITLE
lora不和基础模型合并，单独使用PeftModel加载可以吗，两者有区别吗

### ISSUE THREAD

**Issue by yuandongbo-1** [ymcui/Chinese-LLaMA-Alpaca#632]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型转换和合并

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

我看lora介绍是单独加载一下，而我看到本项目是需要将lora和原模型进行合并后才能使用，这两者有什么区别吗

### 依赖情况（代码类问题务必提供）

无

### 运行日志或截图

无

**Comment by airaria** [comment]
合并主要是为了后续用llama.cpp进行量化，以及配合其他脚本或生态（如langchain）使用起来更方便。
如果可以直接在运行时加载lora（plus模型需要加载两个lora），那也可以不单独进行合并的操作
