### ISSUE TITLE
繁體中文支持?

### ISSUE THREAD

**Issue by cyc00518** [ymcui/Chinese-LLaMA-Alpaca#634]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

效果问题

### 基础模型

None

### 操作系统

None

### 详细描述问题

謝謝大佬開源程式碼, 以下兩個問題請教 :

1. 推理時若直接使用繁體中文提問, 推理結果是否與簡體中文一致?
2. sft階段, 若直接使用繁體中文資料訓練, 是否會造成模型效果下降? 還是推薦一律使用簡體中文資料訓練?

謝謝您!

**Comment by ymcui** [comment]
1、可以用繁体中文提问，但大多数情况下回复可能是简体中文的。性能方面可能会比简体中文略差一些，但考虑到都是中文，所以应该不会有太大偏差。之前试过一些繁体中文的例子，回复的都还可以，可以参考：https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/296
2、如果你要训练一个繁体中文的系统，完全可以使用繁体中文数据进行SFT，因为大多数简体和繁体token是共享的，意思也没有太大的偏差。

**Comment by cyc00518** [comment]
好的, 謝謝您
謝謝您耐心回覆!

**Comment by yelban** [comment]
請教訓練繁體中文的系統，是否只要準備繁體中文的語料庫進行 SFT，模型回答的內容就可以更多是繁體字？
如果是要微調出特定的知識，例如「蘋果公司的現任CEO是誰？」(提姆庫克)，也是只要把這段問答放入語料庫 進行 SFT 後，模型就能回答諸如 「Apple 公司的執行長叫什麼名字？」等問題？

**Comment by airaria** [comment]
> 请教训练繁体中文的系统，是否只要准备繁体中文的语料库进行 SFT，模型回答的内容就可以更多是繁体字？
> 如果是要微调出特定的知识，例如「苹果公司的现任CEO是谁？」(提姆库克)，也是只要把这段问答放入语料库 进行 SFT 后，模型就能回答诸如 「Apple 公司的执行长叫什么名字？」等问题？

是的。不过更建议使用我们的二期模型：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2
中文词表更完整，可以覆盖更多的繁体字
