### ISSUE TITLE
请问一下，预训练的block大小为什么不设置成2048，和llama保持一致，设置成512会不会对上下文理解产生很大影响？

### ISSUE THREAD

**Issue by zhouyanggang** [ymcui/Chinese-LLaMA-Alpaca#635]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

其他问题

### 基础模型

LLaMA-33B

### 操作系统

Linux

### 详细描述问题

请问一下，预训练的block大小为什么不设置成2048，和llama保持一致，设置成512会不会对上下文理解产生很大影响？

**Comment by ymcui** [comment]
1）综合权衡训练时间的结果。
2）超过512长度会有影响，但会影响多少需要自行测试。实际上不是说训练长度是512就只能理解512这么长的context。

**Comment by zhouyanggang** [comment]
冒昧问一下，预训练的时候，您是使用的大概是1个epoch，将所有的语料都过一遍对吧，那么训练的loss会下降么？只过了一遍的话，感觉loss很难下降

**Comment by ymcui** [comment]
训练loss当然会下降，不知道你为什么会认为loss不会下降。

**Comment by zhouyanggang** [comment]
那可能是我的数据loss下降的慢，loss一直在3左右波动中，只有一点点下降，也可能是学习率设置的问题，多谢解答

**Comment by ymcui** [comment]
> 那可能是我的数据loss下降的慢，loss一直在3左右波动中，只有一点点下降，也可能是学习率设置的问题，多谢解答

当然，迭代更多时间loss还会继续下降，如同前面所说这也是tradeoff，有足够多机器的话我们也希望能训到更低的loss。
至于你说的情况，如果你是基于我们的模型继续训练，那也很正常，因为除了我们最开始训练的时候能看到显著loss降低，后面基本都是很小范围内的loss变动了，但这并不代表模型没有学进去东西。建议你不仅看train，也要看valid loss变化。

**Comment by zhouyanggang** [comment]
好的，多谢您的耐心解答
