### ISSUE TITLE
怎样单机多卡模型并行训练，以及多卡报错

### ISSUE THREAD

**Issue by MIkumikumi0116** [ymcui/Chinese-LLaMA-Alpaca#636]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

请问训练时如何使用多gpu模型并行，手头的几张gpu单卡显存不够放不下，多卡倒是可以。

另外尝试torchrun --nnodes 1 --nproc_per_node 8 run_clm_sft_with_peft.py \使用多GPU时报错：
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1269, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
Cuda failure 'API call is not supported in the installed CUDA driver'

似乎是cuda驱动的问题，不知道怎么修复，谷歌百度都找不到相关的内容

### 依赖情况（代码类问题务必提供）

NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0

python3.9

Package                  Version
------------------------ ----------
accelerate               0.20.3
aiohttp                  3.8.4
aiosignal                1.3.1
async-timeout            4.0.2
attrs                    23.1.0
certifi                  2023.5.7
charset-normalizer       3.1.0
datasets                 2.13.0
deepspeed                0.9.4
dill                     0.3.6
filelock                 3.12.2
frozenlist               1.3.3
fsspec                   2023.6.0
hjson                    3.1.0
huggingface-hub          0.15.1
idna                     3.4
multidict                6.0.4
multiprocess             0.70.14
ninja                    1.11.1
numpy                    1.25.0
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
packaging                23.1
pandas                   2.0.2
peft                     0.3.0.dev0
pip                      23.1.2
psutil                   5.9.5
py-cpuinfo               9.0.0
pyarrow                  12.0.1
pydantic                 1.10.9
python-dateutil          2.8.2
pytz                     2023.3
PyYAML                   6.0
regex                    2023.6.3
requests                 2.31.0
safetensors              0.3.1
sentencepiece            0.1.97
setuptools               67.8.0
six                      1.16.0
tokenizers               0.13.3
torch                    1.13.1
tqdm                     4.65.0
transformers             4.28.1
typing_extensions        4.6.3
tzdata                   2023.3
urllib3                  2.0.3
wheel                    0.38.4
xxhash                   3.2.0
yarl                     1.9.2

### 运行日志或截图

[log.txt](https://github.com/ymcui/Chinese-LLaMA-Alpaca/files/11784733/log.txt)

**Comment by airaria** [comment]
具体显存多少？

把cuda升级到11.7试试，并安装与之适配的torch版本
```python
torch.__version__ =='1.13.1+cu117'
```

**Comment by MIkumikumi0116** [comment]
显存8*16G，cuda版本因为是公用服务器，不好升级

**Comment by JadeUnicorn51** [comment]
请问跑起来了吗，我也想知道多台小显存的能不能训练13B的

**Comment by MIkumikumi0116** [comment]
scripts/training/ds_zero2_no_offload.json里，加一个"zero_force_ds_cpu_optimizer": false，zero_optimization改成下面
"zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device":"cpu",
            "pin_memory": true
        },
        "offload_param":{
            "device":"cpu",
            "pin_memory": true
        }
    },
    可以在小显卡上跑起来，这不是模型并行或者tensor并行，只是把显存放不下的参数放在内存上，而且没用deepspeed自己的优化器，训练起来挺慢的，但是起码能在小显卡上跑了。
有多张卡的话，可以run_sft.sh里，nproc_per_node改成显卡的数量，可以用多张卡数据并行

**Comment by AllYoung** [comment]
> 请问跑起来了吗，我也想知道多台小显存的能不能训练13B的

@JadeUnicorn51 大佬，成功了么，请问多张小显卡能否训练？模型并行或者tensor并行的方案是什么样的？
