### ISSUE TITLE
推理时声称“为OpenAI的产品”

### ISSUE THREAD

**Issue by PJ-568** [ymcui/Chinese-LLaMA-Alpaca#638]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

效果问题

### 基础模型

Alpaca-Plus-13B

### 操作系统

Windows

### 详细描述问题

在推理时注意到 Alpaca-Plus-7B 模型和 Alpaca-Plus-13B 模型在拒绝回答和表达所属时声称其 `是 OpenAI 公司研发的产品， 名为 ChatGPT` ，这是错误的，或许会带来不必要的麻烦。可否通过使用更清洁的数据或特殊精调来解决或抑制问题？

### 依赖情况（代码类问题务必提供）

N/A

### 运行日志或截图

* * *

* 我没有刻意引导，以下皆为首次或第二次提问。

## 完全使用中文

![由OpenAI创建](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/63788100/79e4e56d-3a4a-4f71-8793-d07dfad9e0d7)

![我叫ChatGPT，是一个基于人工智能的语言模型。](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/63788100/9acc4dad-10b6-4bea-8133-7fcd8b45b795)

## 完全使用英文

![created by OpenAI](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/63788100/b0becc79-2dba-4145-a59a-5ade583a2b7f)

* 有时它能规避名字问题，但有时候不能。

![有时它能规避名字问题，但有时候不能](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/63788100/b91ae3e5-9e51-4c30-a69f-e96677ea2d26)

* 甚至说自己是 GPT-2 ？

![甚至说自己是 GPT-2 ？](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/63788100/f231fa5f-5fd7-473b-8bed-7d237fe97440)

**Comment by ymcui** [comment]
正常，因为大部分指令数据来自ChatGPT。我们在训练的时候并没有刻意编造一些身份特定的指令数据。
如果你希望给他起个特定的名字，你可以自己造一些类似你提问的问答数据进行精调。
