### ISSUE TITLE
关于lora 精调 Alpaca-7B-Plus模型时为何不需要设置Lora参数的疑惑

### ISSUE THREAD

**Issue by jjyu-ustc** [ymcui/Chinese-LLaMA-Alpaca#642]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-7B

### 操作系统

Linux

### 详细描述问题

<img width="700" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/108610753/8ddc7cb5-9ae1-4ffb-a5e3-69f6ac9d7432">
一、我用您提供的指令训练了Chinese-Alpaca-7B-Plus的模型, 然而一部分较长的语句精调后能记住，而另一部分句子，则会发生遗忘。网上给出的建议是增加cut_off_length和增加lora权重，但是在您的指南里说精调Chinese-Alpaca-7B-Plus不需要设置Lora权重，请问这是为什么？

二、训练过程中我使用两张A5000（24GB），训练过程中计算loss函数的时候提示deepspeed OverFlow。但是测试训练结果的时候仍然比较令人满意，请问这里计算loss的时候的OverFlow是否可以直接忽略？

三、训练测试结果发现，lora算法，对于某些比较长的回答语句，会存在选择性记忆的情况，有些问题的回答可以做到与训练集一模一样，但有些问题的回答则是明显删减过的。请问这种情况下应当如何解决？我希望是回答得越精准越好，最好和我的训练集的答案一模一样。

非常感谢您的项目以及指南，对于我的工作有非常大的帮助！

**Comment by airaria** [comment]
1. 不指定Lora参数是因为已经指定了peft_path，加载peft_path中的lora权重继续训练；如果你自己重新训练一个套新的lora权重，那就需要制定
2.  Deepspeed会自动调整loss scale，正常
3. 训练方法需要尝试，没有一个通用的一定work的方法，不过你可以试试增加训练轮数使模型倾向于过拟合；另外调整解码参数；解码参数对模型输出也有很大影响
