### ISSUE TITLE
预训练模型，使用--do_eval参数验证时报错

### ISSUE THREAD

**Issue by xiaozhu1106** [ymcui/Chinese-LLaMA-Alpaca#643]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型推理

### 基础模型

LLaMA-Plus-13B

### 操作系统

Linux

### 详细描述问题

1.预训练模型，使用--do_eval验证模型时报错，报错信息如下：
ValueError: ZeRO inference only makes sense with ZeRO Stage 3 - please adjust your config
╭─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─  Traceback (most recent call last) ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ╮
│  /workspace/llama/Chinese-LLaMA-Alpaca/scripts/training/run_clm_pt_with_peft. │ 
│  py:646 in <module>                                                           │ 
│                                                                               │ 
│    643                                                                        │ 
│    644                                                                        │ 
│    645 if __name__ == "__main__":                                             │ 
│  ❱ 646 │    main()                                                             │ 
│    647                                                                        │ 
│                                                                               │ 
│  /workspace/llama/Chinese-LLaMA-Alpaca/scripts/training/run_clm_pt_with_peft. │ 
│  py:631 in main                                                               │ 
│                                                                               │ 
│    628 │    if training_args.do_eval:                                          │ 
│    629 │    │    logger.info("*** Evaluate ***")                                │ 
│    630 │    │                                                                   │ 
│  ❱ 631 │    │    metrics = trainer.evaluate()                                   │ 
│    632 │    │                                                                   │ 
│    633 │    │    max_eval_samples = data_args.max_eval_samples if data_args.max │ 
│    634 │    │    metrics["eval_samples"] = min(max_eval_samples, len(eval_datas │ 
│                                                                               │ 
│  /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:2993 in      │ 
│  evaluate                                                                     │ 
│                                                                               │ 
│    2990 │    │    start_time = time.time()                                      │ 
│    2991 │    │                                                                  │ 
│    2992 │    │    eval_loop = self.prediction_loop if self.args.use_legacy_pred │ 
│  ❱ 2993 │    │    output = eval_loop(                                           │ 
│    2994 │    │    │    eval_dataloader,                                          │ 
│    2995 │    │    │    description="Evaluation",                                 │ 
│    2996 │    │    │    # No point gathering the predictions if there are no metr │ 
│                                                                               │ 
│  /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:3110 in      │ 
│  evaluation_loop                                                              │ 
│                                                                               │ 
│    3107 │    │    if args.deepspeed and not self.deepspeed:                     │ 
│    3108 │    │    │    # XXX: eval doesn't have `resume_from_checkpoint` arg but │ 
│    3109 │    │    │    # from the checkpoint eventually                          │ 
│  ❱ 3110 │    │    │    deepspeed_engine, _, _ = deepspeed_init(                  │ 
│    3111 │    │    │    │    self, num_training_steps=0, resume_from_checkpoint=No │ 
│    3112 │    │    │    )                                                         │ 
│    3113 │    │    │    self.model = deepspeed_engine.module                      │ 
│                                                                               │ 
│  /opt/conda/lib/python3.10/site-packages/transformers/deepspeed.py:355 in     │ 
│  deepspeed_init                                                               │ 
│                                                                               │ 
│    352 │    if inference:                                                      │ 
│    353 │    │    # only Z3 makes sense for the inference                        │ 
│    354 │    │    if not hf_deepspeed_config.is_zero3():                         │ 
│  ❱ 355 │    │    │    raise ValueError("ZeRO inference only makes sense with ZeR │ 
│    356 │    │                                                                   │ 
│    357 │    │    # in case the training config is re-used for inference         │ 
│    358 │    │    hf_deepspeed_config.del_config_sub_tree("optimizer")           │ 
╰─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ╯

2.根据报错提示，尝试使用zero3后，又报新的错误：
ValueError: The combination of base model (size: 0) and tokenizer (size: 49953)
is not a valid configuration. Please check our project wiki for further
information.
Valid configurations (base model / tokenizer):
- Continue pre-training original LLaMA: 32000 / 32000
- Pre-training Chinese LLaMA based on original LLaMA: 32000 / 49953
- Continue pre-training Chinese LLaMA: 49953 / 49953
- Continue pre-training Chinese Alpaca: 49954 / 49954

**Comment by airaria** [comment]
提供一下完整的提交脚本？

**Comment by xiaozhu1106** [comment]
> 提供一下完整的提交脚本？

lr=2e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=xxxxxx
chinese_tokenizer_path=xxxxxx
dataset_dir=pt_eval_data
data_cache=temp_data_cache_dir
per_device_train_batch_size=3
per_device_eval_batch_size=3
training_steps=400000
gradient_accumulation_steps=4
output_dir=result_eval

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 4 run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_eval \
    --seed $RANDOM \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 5000 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --block_size 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --ddp_find_unused_parameters False
    #--modules_to_save ${modules_to_save} \
    #--gradient_checkpointing \

**Comment by airaria** [comment]
是只测试不训练？把`--deepspeed ${deepspeed_config_file} `删掉试试？

**Comment by feifei05** [comment]
> > 提供一下完整的提交脚本？
> 
> export CUDA_VISIBLE_DEVICES=0,1,2,3 lr=2e-4 lora_rank=8 lora_alpha=32 lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj" modules_to_save="embed_tokens,lm_head" lora_dropout=0.05
> 
> pretrained_model=xxxxxx chinese_tokenizer_path=xxxxxx dataset_dir=pt_eval_data data_cache=temp_data_cache_dir per_device_train_batch_size=3 per_device_eval_batch_size=3 training_steps=400000 gradient_accumulation_steps=4 output_dir=result_eval
> 
> deepspeed_config_file=ds_zero2_no_offload.json
> 
> torchrun --nnodes 1 --nproc_per_node 4 run_clm_pt_with_peft.py --deepspeed ${deepspeed_config_file} --model_name_or_path ${pretrained_model} --tokenizer_name_or_path ${chinese_tokenizer_path} --dataset_dir ${dataset_dir} --data_cache_dir ${data_cache} --validation_split_percentage 0.001 --per_device_train_batch_size ${per_device_train_batch_size} --per_device_eval_batch_size ${per_device_eval_batch_size} --do_eval --seed $RANDOM --fp16 --max_steps ${training_steps} --lr_scheduler_type cosine --learning_rate ${lr} --warmup_ratio 0.05 --weight_decay 0.01 --logging_strategy steps --logging_steps 10 --save_strategy steps --save_total_limit 3 --save_steps 5000 --gradient_accumulation_steps ${gradient_accumulation_steps} --preprocessing_num_workers 8 --block_size 512 --output_dir ${output_dir} --overwrite_output_dir --ddp_timeout 30000 --logging_first_step True --lora_rank ${lora_rank} --lora_alpha ${lora_alpha} --trainable ${lora_trainable} --lora_dropout ${lora_dropout} --torch_dtype float16 --ddp_find_unused_parameters False #--modules_to_save ${modules_to_save} #--gradient_checkpointing \

大佬，ValueError: ZeRO inference only makes sense with ZeRO Stage 3 - please adjust your config请问这个问题后面是如何解决的？
