### ISSUE TITLE
Chinese LLaMA 7B预测时回复内容答非所问，产出很多不相关回复

### ISSUE THREAD

**Issue by dazhaxie0526** [ymcui/Chinese-LLaMA-Alpaca#644]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

效果问题

### 基础模型

LLaMA-7B

### 操作系统

None

### 详细描述问题

我直接加载的Chinese LLaMA 7B的模型，没有做微调，在预测时经常出现前一两句是相关的，后面大量无意义的内容。这种回复是正常吗？请问怎么解决？谢谢！

### 运行日志或截图

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/5484115/d03d1542-8161-475f-bdbf-1fb43b199b77)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/5484115/53ed59fa-755b-4944-8eca-509445dc6b91)

**Comment by ymcui** [comment]
首先确保已经阅读：https://github.com/ymcui/Chinese-LLaMA-Alpaca#我应该选什么模型
另外，非Plus版本已经不推荐了，没有特殊情况建议你用Plus系列版本模型。

**Comment by dazhaxie0526** [comment]
好的，那我试试Plus系列，谢谢了

**Comment by dazhaxie0526** [comment]
我已经更换成Chinese LLaMA 7B Plus，使用下载的模型未做微调处理，预测结果还是相关性比较差，存在大量不相关的内容，这个是否正常。
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/5484115/f0b373f0-5c52-47fe-9120-ebd408ccedc6)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/5484115/2565e460-b3b7-495e-a3b8-0cf712bf20cc)

**Comment by airaria** [comment]
请换成Alpaca Plus。LLaMA模型未经过指令精调，不适合用于对话

**Comment by quanpinjie** [comment]
我也遇到了这种情况，楼主换成Alpaca Plus是否有改进

**Comment by dazhaxie0526** [comment]
> 



> 我也遇到了这种情况，楼主换成Alpaca Plus是否有改进

Alpaca Plus使用数据集做过指令微调，效果会比LLaMA效果要好。
