### ISSUE TITLE
微调chinese_alpaca_plus_lora_13b，输出的alpaca lora模型的embed_tokens.weight是空tensor

### ISSUE THREAD

**Issue by MIkumikumi0116** [ymcui/Chinese-LLaMA-Alpaca#645]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

微调chinese_alpaca_plus_lora_13b后，和llama-13b-hf、chinese_llama_plus_lora_13b合并时报错
Traceback (most recent call last):
  File "/data/user/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora_low_mem.py", line 249, in <module>
    assert lora_vocab_size==len(tokenizer), \
AssertionError: The vocab size of the tokenizer 49954 does not match the vocab size of the LoRA weight 0.
Make sure that you use LLaMA tokenizer with the LLaMA-LoRA weight and Alpaca tokenizer with the Alpaca-LoRA weight!

查看torch.load(os.path.join(lora_model_path,'adapter_model.bin'),map_location='cpu')得到的字典，base_model.model.model.embed_tokens.weight字段是tensor([])

微调前合并了原版llama_hf和chinese_llama_plus_lora_13b，合并脚本这么写的
python merge_llama_with_chinese_lora.py \
    --base_model /data/user/Chinese-LLaMA-Alpaca/model/llama-13b-hf \
    --lora_model /data/user/Chinese-LLaMA-Alpaca/model/chinese_llama_plus_lora_13b \
    --output_type huggingface \
    --output_dir /data/user/Chinese-LLaMA-Alpaca/model/chinese_llama_plus_lora_13b_combined

微调脚本是这样，用上面合并得到llama_plus做base_model，alpaca_plus做peft_model
lr=1e-6
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

per_device_train_batch_size=1
per_device_eval_batch_size=1
training_steps=10
gradient_accumulation_steps=10
pretrained_model=/data/user/Chinese-LLaMA-Alpaca/model/chinese_llama_plus_lora_13b_combined
peft_model=/data/user/Chinese-LLaMA-Alpaca/model/chinese_alpaca_plus_lora_13b
output_dir=/data/user/Chinese-LLaMA-Alpaca/model/chinese_alpaca_plus_lora_13b_finetuned

chinese_tokenizer_path=/data/user/Chinese-LLaMA-Alpaca/model/chinese_alpaca_plus_lora_13b

dataset_dir=/data/user/train_dataset
validation_file=/data/user/valid_dataset/valid_set_converted.json

deepspeed_config_file=/data/user/Chinese-LLaMA-Alpaca/scripts/training/ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 8 run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed $RANDOM \
    --fp16 \
    --max_steps ${training_steps} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 250 \
    --save_steps 500 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --peft_path ${peft_model} \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False

微调之后，合并原版llama、chinese_llama_plus_lora_13b、微调后的chinese_alpaca_plus_lora_13b命令是这样
python merge_llama_with_chinese_lora_low_mem.py \
    --base_model /data/user/Chinese-LLaMA-Alpaca/model/llama-13b-hf \
    --lora_model /data/user/Chinese-LLaMA-Alpaca/model/chinese_llama_plus_lora_13b,/data/user/Chinese-LLaMA-Alpaca/model/chinese_alpaca_plus_lora_13b_finetuned/sft_lora_model \
    --output_type huggingface \
    --output_dir /data/user/Chinese-LLaMA-Alpaca/model/chinese_alpaca_plus_lora_13b_finetuned_combined

### 依赖情况（代码类问题务必提供）

NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8

python3.9

accelerate               0.20.3
aiohttp                  3.8.4
aiosignal                1.3.1
async-timeout            4.0.2
attrs                    23.1.0
certifi                  2023.5.7
charset-normalizer       3.1.0
cmake                    3.25.0
contourpy                1.1.0
cycler                   0.11.0
datasets                 2.13.0
deepspeed                0.9.4
dill                     0.3.6
filelock                 3.12.2
fonttools                4.40.0
frozenlist               1.3.3
fsspec                   2023.6.0
hjson                    3.1.0
huggingface-hub          0.15.1
idna                     3.4
importlib-resources      5.12.0
Jinja2                   3.1.2
joblib                   1.2.0
kiwisolver               1.4.4
lit                      15.0.7
MarkupSafe               2.1.2
matplotlib               3.7.1
mpmath                   1.2.1
multidict                6.0.4
multiprocess             0.70.14
networkx                 3.0
ninja                    1.11.1
numpy                    1.25.0
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
packaging                23.1
pandas                   2.0.2
peft                     0.3.0.dev0
Pillow                   9.5.0
pip                      23.1.2
psutil                   5.9.5
py-cpuinfo               9.0.0
pyarrow                  12.0.1
pydantic                 1.10.9
pyparsing                3.1.0
python-dateutil          2.8.2
pytz                     2023.3
PyYAML                   6.0
regex                    2023.6.3
requests                 2.31.0
safetensors              0.3.1
scikit-learn             1.2.2
scipy                    1.10.1
sentencepiece            0.1.97
setuptools               67.8.0
six                      1.16.0
sklearn                  0.0.post5
sympy                    1.11.1
threadpoolctl            3.1.0
tokenizers               0.13.3
torch                    2.0.1+cu118
torchaudio               2.0.2+cu118
torchvision              0.15.2+cu118
tqdm                     4.65.0
transformers             4.28.1
triton                   2.0.0
typing_extensions        4.6.3
tzdata                   2023.3
urllib3                  2.0.3
wheel                    0.38.4
xxhash                   3.2.0
yarl                     1.9.2
zipp                     3.15.0

### 运行日志或截图

合并微调后alpaca_plus的命令和报错

python merge_llama_with_chinese_lora_low_mem.py \
    --base_model /data/user/Chinese-LLaMA-Alpaca/model/llama-13b-hf \
    --lora_model /data/user/Chinese-LLaMA-Alpaca/model/chinese_llama_plus_lora_13b,/data/user/Chinese-LLaMA-Alpaca/model/chinese_alpaca_plus_lora_13b_finetuned/sft_lora_model \
    --output_type huggingface --output_dir \
    /data/user/Chinese-LLaMA-Alpaca/model/chinese_alpaca_plus_lora_13b_finetuned_combined

[2023-06-20 16:45:32,300] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Base model: /data/user/Chinese-LLaMA-Alpaca/model/llama-13b-hf
LoRA model(s) ['/data/user/Chinese-LLaMA-Alpaca/model/chinese_llama_plus_lora_13b', '/data/user/Chinese-LLaMA-Alpaca/model/chinese_alpaca_plus_lora_13b_finetuned/sft_lora_model']:
Loading /data/user/Chinese-LLaMA-Alpaca/model/chinese_llama_plus_lora_13b
Loading /data/user/Chinese-LLaMA-Alpaca/model/chinese_alpaca_plus_lora_13b_finetuned/sft_lora_model
Traceback (most recent call last):
  File "/data/user/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora_low_mem.py", line 249, in <module>
    assert lora_vocab_size==len(tokenizer), \
AssertionError: The vocab size of the tokenizer 49954 does not match the vocab size of the LoRA weight 0.
Make sure that you use LLaMA tokenizer with the LLaMA-LoRA weight and Alpaca tokenizer with the Alpaca-LoRA weight!

**Comment by MIkumikumi0116** [comment]
补充下，训练出来的adapter_model.bin只有几百k，是哪里设置错了吗

**Comment by MIkumikumi0116** [comment]
改过ds_zero2_no_offload.json，用的stage3

{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 100,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1e-10
    },

    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device":"cpu",
            "pin_memory": true
        },
        "offload_param":{
            "device":"cpu",
            "pin_memory": true
        }
    },

    "zero_force_ds_cpu_optimizer": false,

    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}

**Comment by MIkumikumi0116** [comment]
改过ds_zero2_no_offload.json，用的stage3


    {
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 100,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1e-10
    },

    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device":"cpu",
            "pin_memory": true
        },
        "offload_param":{
            "device":"cpu",
            "pin_memory": true
        }
    },

    "zero_force_ds_cpu_optimizer": false,

    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
    }

**Comment by iMountTai** [comment]
1. 你应该基于llama_plus和alpaca-plus-lora、sft_lora_model合并得到你的模型
2. 既然微调时输入了`peft_model`,则embed_tokens/lm_head也是可训练参数，最终得到的模型大小应该是和alpaca-plus-lora(float16)大小是一致的(或是两倍大，float32)，不排除是zero3的问题。

**Comment by MIkumikumi0116** [comment]
看了下sft_lora_model，不光是embed_tokens.weight，所有的层的tensor都是空的，请问有什么排查思路吗

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/57623431/53bd428b-fac5-40fb-a0a5-f13a4b3f8c01)

**Comment by iMountTai** [comment]
没有使用zero3微调lora的经验。两个建议：
1. 基于我们的代码微调，严格按照我们的要求安装依赖，仔细阅读相关[wiki指令精调](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E6%8C%87%E4%BB%A4%E7%B2%BE%E8%B0%83%E8%84%9A%E6%9C%AC)，然后在7B基础上跑通代码后再魔改
2. 还是我们的代码，但是直接安装最新版本的peft、transformers、deepspeed等，试试是否能解决相关问题。
炼丹不易，且行且珍惜。
