### ISSUE TITLE
LoRA后合并成huggingface模型格式，能否再用该模型文件继续做全参数微调或继续全参数预训练？

### ISSUE THREAD

**Issue by zeng9t** [ymcui/Chinese-LLaMA-Alpaca#648]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

LoRA后合并成huggingface模型格式，能否再用该模型文件继续做全参数微调或继续全参数预训练？

**Comment by airaria** [comment]
合并后的模型结构上和原版LLaMA就没什么区别了，怎么训练（全参数微调/预训练）都可以

**Comment by zeng9t** [comment]
> 合并后的模型结构上和原版LLaMA就没什么区别了，怎么训练（全参数微调/预训练）都可以

全参数微调，一开始loss有8/9的样子正常么？

**Comment by zeng9t** [comment]
> > 合并后的模型结构上和原版LLaMA就没什么区别了，怎么训练（全参数微调/预训练）都可以
> 
> 全参数微调，一开始loss有8/9的样子正常么？

我看别的issue里大家反馈loss一开始可能2左右比较正常，但是似乎也是LoRA训得，动的参数只是一部分；感觉全参数微调一开始就是loss会大一些？

**Comment by airaria** [comment]
> > 合并后的模型结构上和原版LLaMA就没什么区别了，怎么训练（全参数微调/预训练）都可以
> 
> 全参数微调，一开始loss有8/9的样子正常么？

不太正常。8或9的话和从原版llama开始训差不多

**Comment by zeng9t** [comment]
> > > 合并后的模型结构上和原版LLaMA就没什么区别了，怎么训练（全参数微调/预训练）都可以
> > 
> > 
> > 全参数微调，一开始loss有8/9的样子正常么？
> 
> 不太正常。8或9的话和从原版llama开始训差不多

如果继续预训练，可以基于chinese alpaca做吗？还是要基于chinese llama做更好？

**Comment by airaria** [comment]
> > > > 合并后的模型结构上和原版LLaMA就没什么区别了，怎么训练（全参数微调/预训练）都可以
> > > 
> > > 
> > > 全参数微调，一开始loss有8/9的样子正常么？
> > 
> > 
> > 不太正常。8或9的话和从原版llama开始训差不多
> 
> 如果继续预训练，可以基于chinese alpaca做吗？还是要基于chinese llama做更好？

比较标准的做法是基于Chinese-LLaMA做。当然基于Chinese-Alpaca的方式你也可以尝试

**Comment by zeng9t** [comment]
另外还有个问题请教一下，如果把alpaca格式数据的input字段为空，问题内容都放到instruction字段，会影响模型sft的效果吗？

**Comment by airaria** [comment]
> 另外还有个问题请教一下，如果把alpaca格式数据的input字段为空，问题内容都放到instruction字段，会影响模型sft的效果吗？

我们的代码里就是这么做的。从输入内容上看和原版区别不大。
