### ISSUE TITLE
DeepSpeed和Lora的结合

### ISSUE THREAD

**Issue by Porraio** [ymcui/Chinese-LLaMA-Alpaca#65]
您好，看到你们是用了DeepSpeed Zero-2和Lora的，请问是基于alpaca-lora的脚本结peft里的peft_lora_clm_accelerate_ds_zero3_offload.py 改写的吗。似乎不能直接把zero-2的配置加在trainer的TrainingArguments里。感谢。

**Comment by airaria** [comment]
> 您好，看到你们是用了DeepSpeed Zero-2和Lora的，请问是基于alpaca-lora的脚本结peft里的peft_lora_clm_accelerate_ds_zero3_offload.py 改写的吗。似乎不能直接把zero-2的配置加在trainer的TrainingArguments里。感谢。

没有太明白“不能直接把zero-2的配置加在trainer的TrainingArguments里“是什么意思
我们是用--deepspeed 参数指定zero-2配置文件的方式使用的。

**Comment by Porraio** [comment]
> > 您好，看到你们是用了DeepSpeed Zero-2和Lora的，请问是基于alpaca-lora的脚本结peft里的peft_lora_clm_accelerate_ds_zero3_offload.py 改写的吗。似乎不能直接把zero-2的配置加在trainer的TrainingArguments里。感谢。
> 
> 没有太明白“不能直接把zero-2的配置加在trainer的TrainingArguments里“是什么意思 我们是用--deepspeed 参数指定zero-2配置文件的方式使用的。

不需要对alpaca-lora的代码做更改吗？那deepspeed是怎么初始化的呢

**Comment by airaria** [comment]
> > > 您好，看到你们是用了DeepSpeed Zero-2和Lora的，请问是基于alpaca-lora的脚本结peft里的peft_lora_clm_accelerate_ds_zero3_offload.py 改写的吗。似乎不能直接把zero-2的配置加在trainer的TrainingArguments里。感谢。
> > 
> > 
> > 没有太明白“不能直接把zero-2的配置加在trainer的TrainingArguments里“是什么意思 我们是用--deepspeed 参数指定zero-2配置文件的方式使用的。
> 
> 不需要对alpaca-lora的代码做更改吗？那deepspeed是怎么初始化的呢

主要是参考[run_clm.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py)实现的，使用了Trainer，提供 --deepspeed的参数后自动初始化。

**Comment by Porraio** [comment]
> > > > 您好，看到你们是用了DeepSpeed Zero-2和Lora的，请问是基于alpaca-lora的脚本结peft里的peft_lora_clm_accelerate_ds_zero3_offload.py 改写的吗。似乎不能直接把zero-2的配置加在trainer的TrainingArguments里。感谢。
> > > 
> > > 
> > > 没有太明白“不能直接把zero-2的配置加在trainer的TrainingArguments里“是什么意思 我们是用--deepspeed 参数指定zero-2配置文件的方式使用的。
> > 
> > 
> > 不需要对alpaca-lora的代码做更改吗？那deepspeed是怎么初始化的呢
> 
> 主要是参考[run_clm.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py)实现的，使用了Trainer，提供 --deepspeed的参数后自动初始化。

我看了下，--deepspeed参数初始化一个hf_deepspeed_config然后加到TrainingArguments。相当于Trainer的training_args里就会有deepspeed的配置信息了，感谢啦。
