### ISSUE TITLE
训练出来的Lora权重没有效果

### ISSUE THREAD

**Issue by tcluoct** [ymcui/Chinese-LLaMA-Alpaca#653]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-Plus-7B

### 操作系统

Linux

### 详细描述问题

用txt文件在PLUS-7B的模型上继续预训练，因为训练数据很小，用了100个epoch。
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/4354899/9c5242b9-b6f2-4947-a49e-1e736e8b75c3)
在outputDir/pt_lora_model里的bin文件很小，看起来有问题，所以用的是最新的checkpoint里的pt_lora_model。
loss非常低了，应该问训练文本的问题是很好的，但实际情况完全没用到训练数据集里的数据。
请问下可能的问题是什么？

**Comment by tcluoct** [comment]
是因为在outputDir没产生model的原因吗？按照文档， 应该是在这个目录下产生bin文件的，但pretrain完以后，发现这个bin文件没更新，所以用的是CheckPoint里的Bin文件。

**Comment by ycpan** [comment]
我也遇到了pt_lora_model里的bin文件很小的问题。
使用版本为：Chinese-LLaMA-Alpaca-4.1
相关环境为:
accelerate==0.19.0
aiohttp==3.8.4
aiosignal==1.3.1
async-timeout==4.0.2
attrs==23.1.0
certifi==2023.5.7
charset-normalizer==3.1.0
cmake==3.26.3
datasets==2.12.0
deepspeed==0.9.2
dill==0.3.6
filelock==3.12.0
frozenlist==1.3.3
fsspec==2023.5.0
hjson==3.1.0
huggingface-hub==0.14.1
idna==3.4
Jinja2==3.1.2
joblib==1.2.0
lit==16.0.5
MarkupSafe==2.1.2
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.14
networkx==3.1
ninja==1.11.1
numpy==1.24.3
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
packaging==23.1
pandas==2.0.1
peft @ git+https://github.com/huggingface/peft.git@016722addd2c18ec899d2431da54199a12d41736
psutil==5.9.5
py-cpuinfo==9.0.0
pyarrow==12.0.0
pydantic==1.10.7
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
regex==2023.5.5
requests==2.30.0
responses==0.18.0
safetensors==0.3.1
scikit-learn==1.2.2
scipy==1.10.1
sentencepiece==0.1.97
six==1.16.0
sympy==1.12
threadpoolctl==3.1.0
tokenizers==0.13.3
torch==2.0.1
tqdm==4.65.0
transformers==4.28.1
triton==2.0.0
typing_extensions==4.5.0
tzdata==2023.3
urllib3==2.0.2
xxhash==3.2.0
yarl==1.9.2

**Comment by airaria** [comment]
请说明一下环境依赖，以及列一下outputDir及其子文件夹下各文件 @tcluoct

**Comment by tcluoct** [comment]
我试了2次，
第一次用了3个文档训练里20个epoch，在checkpoint里生产了pt_lora_model文件夹，在output_dir里的pt_lora_model里的文件不到4M。但checkpoint里的pt_lora_mode文件夹里的model能正常工作。
第二次用的txt文件很多， 训练里3个epoch，在checkpoint里没生成pt_lora_model文件夹，目前还没跑完， 这个是要等完全跑完才会在output_dir里生成pt_lora_mode文件夹？但在训练过程中的checkpoint里应该也有pt_lora_mode文件夹用于测试才对吧？
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/4354899/920f7b74-979b-465e-a3ea-ddab753945ba)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/4354899/4fa4e7a3-e5d5-4609-bc2a-03fa21f316dc)
代码在开始训练的时候是最新的，谢谢！

**Comment by YukinoWan** [comment]
我是10天前开始训练到今天的，应该就不是最新的版本的代码，那这种情况下要怎么利用checkpoint的权重文件呢。
这是我的output_dir
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/66019831/48d313fc-c8f5-4a58-8246-b2eca7d9f77a)

我的pt_lora_model文件下的adapter.bin文件大小非常小，在和原始llama合并的时候会报错。这是我的pt_lora_model文件夹
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/66019831/3e5b6104-a158-4b8f-b7a9-14b8fc39fcb3)
