### ISSUE TITLE
微调数据集大小

### ISSUE THREAD

**Issue by yangxingrui** [ymcui/Chinese-LLaMA-Alpaca#655]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-7B

### 操作系统

Linux

### 详细描述问题

我使用自己的数据集中3k条数据做微调（训练集有200w条数据），steps为20000 时间15h 指标比较差，我想知道微调数据集大小多少比较合适？

**Comment by airaria** [comment]
3k数据可能有点少，50k左右的训练数据（Stanford Alpaca数据大小）是可以看出效果的，但尚不清楚数据下限数量；
另外，微调效果和多个因素有关系，数据质量、分布、超参等，不好一概而论或都归结于数据集大小
