### ISSUE TITLE
「基于中文LLaMA继续预训练LLaMA/LLaMA-Plus」和「基于中文Alpaca继续预训练」

### ISSUE THREAD

**Issue by SoftFeta** [ymcui/Chinese-LLaMA-Alpaca#656]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

我用的是Alpaca-Plus。请问 [预训练脚本 wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E9%A2%84%E8%AE%AD%E7%BB%83%E8%84%9A%E6%9C%AC) 中「基于中文LLaMA继续预训练LLaMA/LLaMA-Plus」和「基于中文Alpaca继续预训练」有什么不同？用 Alpaca-Plus 的话，可以只「基于中文Alpaca继续预训练」，而不「基于中文LLaMA继续预训练LLaMA/LLaMA-Plus」吗？还是可以只「基于中文LLaMA继续预训练LLaMA/LLaMA-Plus」，而不「基于中文Alpaca继续预训练」吗？

### 运行日志或截图

/

**Comment by airaria** [comment]
基于某个模型预训练，就是用那个模型初始化。
具体是「基于中文Alpaca继续预训练」还是「基于中文LLaMA继续预训练LLaMA/LLaMA-Plus」，逻辑上都可以。
一般来说较正统的方式是「基于中文LLaMA继续预训练LLaMA/LLaMA-Plus」，然后在训出来的模型上SFT

**Comment by SoftFeta** [comment]
感谢回复。两者都进行预训练是否更好？

**Comment by SoftFeta** [comment]
谢谢你的回复。两者训练的权重是否相同？两者都进行预是否没有作用，因为会盖过之前的权重？

**Comment by iMountTai** [comment]
还请阅读[我应该选择什么模型](https://github.com/ymcui/Chinese-LLaMA-Alpaca#%E6%88%91%E5%BA%94%E8%AF%A5%E9%80%89%E4%BB%80%E4%B9%88%E6%A8%A1%E5%9E%8B)了解llama和alpaca的不同，然后选择合适的模型继续训练，理论上不管是llama还是alpaca都可以继续进行预训练或者精调，但是效果如何则需要实验验证，欢迎分享您的实验结果。

**Comment by SoftFeta** [comment]
谢谢回复。我的意思是，
```
Chinese-Alpaca-Plus需要提供两个LoRA权重，分别为Chinese-LLaMA-Plus-LoRA和Chinese-Alpaca-Plus-LoRA。
```
两个LoRA权重都预训练可以吗？

**Comment by SoftFeta** [comment]
谢谢回复。我的意思是，合并时
```
Chinese-Alpaca-Plus需要提供两个LoRA权重，分别为Chinese-LLaMA-Plus-LoRA和Chinese-Alpaca-Plus-LoRA。
```
预训练LLaMA Plus -> 预训练Alpaca Plus -> 合并 可以吗？会否盖过之前的权重？
