### ISSUE TITLE
合并chinese alpaca plus模型出错

### ISSUE THREAD

**Issue by icoderzqliu** [ymcui/Chinese-LLaMA-Alpaca#658]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型转换和合并

### 基础模型

LLaMA-7B

### 操作系统

None

### 详细描述问题

python ./Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora_low_mem.py \
    --base_model 'elinas/llama-7b-hf-transformers-4.29' \
    --lora_model 'ziqingyang/chinese-llama-plus-lora-7b', 'ziqingyang/chinese-alpaca-plus-lora-7b' \
    --output_type pth \
    --output_dir alpaca-combined
报错：
usage: merge_llama_with_chinese_lora_low_mem.py
       [-h]
       --base_model
       BASE_MODEL
       --lora_model
       LORA_MODEL
       [--output_type {pth,huggingface}]
       [--output_dir OUTPUT_DIR]
       [--verbose]
merge_llama_with_chinese_lora_low_mem.py: error: unrecognized arguments: ziqingyang/chinese-alpaca-plus-lora-7b

### 依赖情况（代码类问题务必提供）

pip install torch==1.13.1
pip install transformers==4.30.2
pip install peft==0.3.0
pip install sentencepiece

**Comment by ymcui** [comment]
```
--lora_model ziqingyang/chinese-llama-plus-lora-7b,ziqingyang/chinese-alpaca-plus-lora-7b
```
