### ISSUE TITLE
Resume from model's stats dict is not a correct way, should be from last_checkpoint ?!?

### ISSUE THREAD

**Issue by thusinh1969** [ymcui/Chinese-LLaMA-Alpaca#665]
### Check before submitting issues

- [X] Make sure to pull the latest code, as some issues and bugs have been fixed.
- [X] Due to frequent dependency updates, please ensure you have followed the steps in our [Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)
- [X] I have read the [FAQ section](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/FAQ) AND searched for similar issues and did not find a similar problem or solution
- [X] Third-party plugin issues - e.g., [llama.cpp](https://github.com/ggerganov/llama.cpp), [text-generation-webui](https://github.com/oobabooga/text-generation-webui), [LlamaChat](https://github.com/alexrozanski/LlamaChat), we recommend checking the corresponding project for solutions
- [X] Model validity check - Be sure to check the model's [SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md). If the model is incorrect, we cannot guarantee its performance

### Type of Issue

Model training and fine-tuning

### Base Model

LLaMA-7B

### Operating System

Linux

### Describe your issue in detail

I found that the repo once reloading checkpoint use the "model checkpoint state dict which is may not be correct". I changed as follow to load from last-checkpoint stat-dict:

```
if last_checkpoint is not None:
        checkpoint_STATE_DICT = last_checkpoint+"/pytorch_model.bin"
        checkpoint_STATE_DICT = torch.load(checkpoint_STATE_DICT, map_location="cpu")    
        set_peft_model_state_dict(model, checkpoint_STATE_DICT)
```

Please give your thought, it works as the losses are continue where last checkpoint left off. I am not using DeepSpeed.
Steve

### Dependencies (must be provided for code-related issues)

As in the requirements.txt
I am not using deepspeed at all as it has bug from loading LoRA checkpoint still.

### Execution logs or screenshots

The losses from repo-way off loading almost come back to the beginning.

**Comment by iMountTai** [comment]
1. We set `resume_from_checkpoint` and `overwrite_output_dir`  to continue training；
2. You can try to remove `overwrite_output_dir` and the code will automatically resume training from the last_checkpoint.

**Comment by thusinh1969** [comment]
> * We set `resume_from_checkpoint` and `overwrite_output_dir`  to continue training；
> * You can try to remove `overwrite_output_dir` and the code will automatically resume training from the last_checkpoint.

Thanks. Would my code changes posed any error in loading state then !?

**Comment by iMountTai** [comment]
It feels like the optimizer state is not loaded
