### ISSUE TITLE
合并模型的时候报错

### ISSUE THREAD

**Issue by Log4J-Ops** [ymcui/Chinese-LLaMA-Alpaca#67]
![image](https://user-images.githubusercontent.com/59152764/230393872-3ca9def1-7465-4275-ab4a-3980a98f6a5b.png)
![image](https://user-images.githubusercontent.com/59152764/230393957-15d1586d-1cd7-4062-9358-ef2038a3b353.png)
请问在合并模型的时候报错ValueError: weight is on the meta device, we need a `value` to put in on cpu如何解决

**Comment by Log4J-Ops** [comment]
您好，accelerate已安装，请问这种情况是否可能是原模型参数中有指定？或者可能跟操作系统为Windows有关？因为在merge_llama_with_chinese_lora.py的参数里加载模型之前并未指定权重的位置

**Comment by airaria** [comment]
from_pretrained 中加上参数`device_map="auto"`试试呢

**Comment by sheerfish999** [comment]
同样有该错，谁解决了请提供解决办法

**Comment by Log4J-Ops** [comment]
> 同样有该错，谁解决了请提供解决办法

请问你是使用Windows系统运行的吗，或者是使用了huggingface上的开源llama模型，我猜遇到问题可能是这两个原因中的一个，后续有空我会去验证一下

**Comment by quanzhang2020** [comment]
同样的问题
