### ISSUE TITLE
7B/ggml-model-f16结果优化问题

### ISSUE THREAD

**Issue by quanpinjie** [ymcui/Chinese-LLaMA-Alpaca#670]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

效果问题

### 基础模型

LLaMA-Plus-7B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```
启动运行
llama.cpp$ ./main -m zh-models/7B/ggml-model-f16.bin  --color -f ./prompts/alpaca.txt -ins   -b 24 -c 2048 -n 512 -t 6   --temp 0.2 --top_k 40 --top_p 0.9   --repeat_penalty 1.3
main: build = 740 (447ccbe)
main: seed  = 1687757977
llama.cpp: loading model from zh-models/7B/ggml-model-f16.bin
llama_model_load_internal: format     = ggjt v1 (pre #1405)
llama_model_load_internal: n_vocab    = 49953
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 1 (mostly F16)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.07 MB
llama_model_load_internal: mem required  = 14925.60 MB (+ 1026.00 MB per state)
llama_new_context_with_model: kv self size  = 1024.00 MB

system_info: n_threads = 6 / 16 | AVX = 1 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
main: interactive mode on.
Reverse prompt: '### Instruction:

'
sampling: repeat_last_n = 64, repeat_penalty = 1.300000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.900000, typical_p = 1.000000, temp = 0.200000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 2048, n_batch = 24, n_predict = 512, n_keep = 21

== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```
peft                     0.3.0
pytorch-lightning        1.9.4
sentence-transformers    2.2.2
torch                    1.13.1
torchaudio               0.13.1
torchmetrics             0.11.3
torchvision              0.14.1
transformers             4.30.2

### 运行日志或截图

```
```
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/2564119/4796382d-48b1-4cc5-91cb-868a67988c6d)
请问有人遇到这种情况吗

Below is an instruction that describes a task. Write a response that appropriately completes the request.
> 我能用lightning数据线给安卓手机充电吗？
可以，但是需要一个适配器。Lighting到USB转换器的售价在20元左右吧！ （注意：这个回答是针对iPhone 6s Plus） 《大话西游》是由中国电影集团公司、北京东方飞云国际影视投资有限公司出品的电影作品之一，由徐克执导并编剧，周星驰吴孟达张敏等主演。该片讲述了唐僧师徒在取经路上遭遇妖魔的一系列故事，最终战胜了种种困难的故事。1993年1月18日上映后取得巨大成功，票房收入高达1.3亿人民币（约6000万美元），成为中国电影史上第一部突破亿元大关的电影作品之一。1995年5月10日在香港首映时创下港产片单场票房纪录的3550万港元；1997年3月在台湾公映时打破了华语影坛上“百日破百万”记录的大陆影片《阿飞正传》，成为第一部突破千万元大关的电影作品。1998年12月25日在中国大陆上映后取得巨大成功，最终在中国大陆地区票房收入达2亿人民币（约1亿美元）；1999年3月在台湾公映时创下了华语影坛上“百日破百万”的纪录的大陆影片《阿飞正传》，成为第一部突破千万元大关的电影作品。2001年5月20日在中国大陆上映后取得巨大成功，最终在中国大陆地区票房收入达2亿人民币（约1亿美元）；2003年3月在台湾公映时创下了华语影坛上“百日破百万”的纪录的大陆影片《阿飞正传》，成为第一部突破千万元大关的电影作品。2004年5月20日在中国大陆上映后取得巨大成功，最终在中国大陆地区票房收入达2亿人民币（约1亿美元）；2006年3月在台湾公映时创下了华语影坛上“百日破百万”的纪录的大陆影片《阿飞正传》，成为第一部突破千万元大关的电影作品。2010年5月20日在中国大陆上映后取得巨大成功，最终在中国大陆地区票房收入达2亿人民币（约1亿美元）；2012年3月在台湾公映时创下了华语影坛上“百日破百万”的纪录的大陆影片《阿飞正传》，成为第一部突破千万元大关的电影作品。2013年5月20日在
>

llama_print_timings:        load time =  1319.22 ms
llama_print_timings:      sample time =   358.77 ms /   499 runs   (    0.72 ms per token,  1390.87 tokens per second)
llama_print_timings: prompt eval time =  4473.93 ms /    52 tokens (   86.04 ms per token,    11.62 tokens per second)
llama_print_timings:        eval time = 121541.97 ms /   499 runs   (  243.57 ms per token,     4.11 tokens per second)
llama_print_timings:       total time = 264248.26 ms

**Comment by ymcui** [comment]
看来你并没有看：https://github.com/ymcui/Chinese-LLaMA-Alpaca#我应该选什么模型
对话交互需要用Alpaca模型，不是LLaMA模型（基座模型）。

**Comment by quanpinjie** [comment]
d

> 看来你并没有看：[https://github.com/ymcui/Chinese-LLaMA-Alpaca#我应该选什么模型](https://github.com/ymcui/Chinese-LLaMA-Alpaca#%E6%88%91%E5%BA%94%E8%AF%A5%E9%80%89%E4%BB%80%E4%B9%88%E6%A8%A1%E5%9E%8B) 对话交互需要用Alpaca模型，不是LLaMA模型（基座模型）。

多谢，已解决
