### ISSUE TITLE
预训练模型选择

### ISSUE THREAD

**Issue by wuhuanon** [ymcui/Chinese-LLaMA-Alpaca#676]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-7B

### 操作系统

Windows

### 详细描述问题

我想在现有的Alpaca-Plus-7B上继续预训练，我看介绍上说
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/44658755/98df5efb-0caa-4bc9-a618-e039ad3792fa)
这个HF格式的中文Alpaca/Alpaca-Plus和中文Alpaca的tokenizer（49954）指的是chinese-alpaca-plus-lora-13b和chinese-alpaca-lora-7b吗

**Comment by airaria** [comment]
指的是合并后的chinese-alpaca-plus 7b或者13b模型

**Comment by wuhuanon** [comment]
是合并chinese-llama-plus-lora-7b与chinese-alpaca-plus-lora-7后的模型吗

**Comment by airaria** [comment]
> 是合并chinese-llama-plus-lora-7b与chinese-alpaca-plus-lora-7后的模型吗

是指，在原版LLaMA基础上，合并
chinese-alpaca-lora-7b（非plus版本）
或者
chinese-llama-plus-lora-7b与chinese-alpaca-plus-lora-7b（plus版本）
得到的模型
