### ISSUE TITLE
指令精调后的模型合并问题

### ISSUE THREAD

**Issue by xytian899** [ymcui/Chinese-LLaMA-Alpaca#678]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型转换和合并

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

```
如果想继续训练Chinese-Alpaca模型的LoRA权重：

--model_name_or_path: 原版HF格式LLaMA模型（如果继续训练非Plus Alpaca模型）或合并Chinese-LLaMA-Plus-LoRA后的Chinese-LLaMA模型（如果继续训练Plus模型）
--peft_path: Chinese-Alpaca的LoRA权重目录
无需指定--lora_rank、--lora_alpha、--lora_dropout、--trainable和--modules_to_save参数
如果想基于中文Chinese-LLaMA训练全新的指令精调LoRA权重：

--model_name_or_path: 合并对应Chinese-LLaMA-LoRA后的HF格式Chinese-LLaMA模型（无论是否是Plus模型）
--peft_path: 勿提供此参数，并且从脚本中删除 --peft_path
需指定--lora_rank、--lora_alpha、--lora_dropout、--trainable和--modules_to_save参数
```

对于以上内容，我想请教一下上述两种情况在微调得到自己的lora后，要将哪些模型进行合并从而来进行推理？
例如我想继续训练Chinese-Alpaca模型的LoRA权重，训练非Plus Alpaca模型，那么得到自己的lora后要与原版HF llama合并吗？还是要与Chinese-Alpaca合并？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by airaria** [comment]
合并时的base_model对应训练时`--model_name_or_path`提供的模型。

你说的情况里，是与原版HF llama合并
