### ISSUE TITLE
Traning perfectly OK, but generate just HANG, gradio demo spinning and GPU bouncing around forever.

### ISSUE THREAD

**Issue by thusinh1969** [ymcui/Chinese-LLaMA-Alpaca#679]
### Check before submitting issues

- [X] Make sure to pull the latest code, as some issues and bugs have been fixed.
- [X] Due to frequent dependency updates, please ensure you have followed the steps in our [Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)
- [X] I have read the [FAQ section](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/FAQ) AND searched for similar issues and did not find a similar problem or solution
- [X] Third-party plugin issues - e.g., [llama.cpp](https://github.com/ggerganov/llama.cpp), [text-generation-webui](https://github.com/oobabooga/text-generation-webui), [LlamaChat](https://github.com/alexrozanski/LlamaChat), we recommend checking the corresponding project for solutions
- [X] Model validity check - Be sure to check the model's [SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md). If the model is incorrect, we cannot guarantee its performance

### Type of Issue

Model inference

### Base Model

LLaMA-7B

### Operating System

Linux

### Describe your issue in detail

python gradio_demo.py \
--base_model /data/VN-vocab-model/PRE_TRAINING/HOME-1G/VN-LLaMA-Lora/VN-LLaMA-Lora-V1.0-PreTrain/merged_hf \
--tokenizer_path /data/VN-vocab-model/VN-LLama-tokenizer_20k_sp/7B/VN-LLama-tokenizer_hf \
--gpus 1

### Dependencies (must be provided for code-related issues)

Training was perfectly OK, saved OK, loaded OK with gradio_demo.py
But the model does NOT generate any thing, no error, just spinning and GPU bouncing around forever.

CUDa 11.8/CUDNN 8.6
Torch 1.13.1
bitsandbytes 0.37.2
peft git+https://github.com/huggingface/peft.git@3714aa2fff158fdfa637b2b65952580801d890b2 (0.4.0.dev0)
transformers pip install git+https://github.com/huggingface/transformers@de9255de27abfcae4a1f816b904915f0b1e23cd9

max_new_tokens=1024,
top_p=0.75,
temperature=0.5,
top_k=40,
num_beams=1,
repetition_penalty=1.0, #1.0,
max_memory=1024,

Any hint would be highly appreciated.
Thanks
Steve

### Execution logs or screenshots

Nothing. No error. Just spinning (queue 1/1....)

**Comment by thusinh1969** [comment]
I got it. Fixed by:
pip install bitsandbytes==0.37.2
pip install transformers==4.28.1

**Comment by Lathashree01** [comment]
But as per the requirements file, aren't you supposed to have `transformers==4.30.0`

Commenting here, since I have a similar problem.

I am facing a similar problem running: 
```
python scripts/inference/inference_hf.py \
    --base_model path_to_original_llama_hf_dir \
    --lora_model Check_point_lora_location \
    --with_prompt 
```

I finished my training, and I am trying to use the model from a checkpoint location - **checkpoint-5800/pt_lora_model/** 

I get logs as below, but no specific error :

The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|██████████| 2/2 [00:17<00:00,  8.85s/it]
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

Any help would be greatly appreciated.

**Comment by airaria** [comment]
> The model weights are not tied. Please use the tie_weights method before using the infer_auto_device function.
> Loading checkpoint shards: 100%|██████████| 2/2 [00:17<00:00, 8.85s/it]
> Setting pad_token_id to eos_token_id:2 for open-end generation.

Did your script keep HANGing?
These messages can be safely ignored If the model works normally

**Comment by Lathashree01** [comment]
Yes, even after an hour, it did not generate anything. No logs, no errors.

Below is another version of the startup command that I tried:

python src/inference/inference_hf.py \
    --base_model /home/llama-hf/ \
    --lora_model /home/git_repos/thesis/output_dir/checkpoint-5800/pt_lora_model \
    --predictions_file ./predictions_checkpoint-5800_lora.json \
    --data_file /home/git_repos/thesis/datasets/ \
    --with_prompt \
    --only_cpu

Did not get any error or output.

Kindly help me with this
