### ISSUE TITLE
make编译llama.cpp的时候提示：找不到文件make: *** [Makefile:263: ggml.o] Error 2

### ISSUE THREAD

**Issue by TCHSDUFH** [ymcui/Chinese-LLaMA-Alpaca#680]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型量化和部署

### 基础模型

Alpaca-Plus-7B

### 操作系统

Windows

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```
在llama.cpp里面make的时候提示该错误，该怎么解决
![屏幕截图 2023-06-27 230009](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/58661545/e1b72bfb-0d9d-4e72-af89-0c370dd99e41)

**Comment by ymcui** [comment]
1.  使用最新llama.cpp看看能不能解决
2. windows下比较容易出现各种编译问题，可以考虑使用其他编译方式比如[Cmake](https://github.com/ggerganov/llama.cpp#build)，或者使用WSL

**Comment by TCHSDUFH** [comment]
> 1. 使用最新llama.cpp看看能不能解决
> 2. windows下比较容易出现各种编译问题，可以考虑使用其他编译方式比如[Cmake](https://github.com/ggerganov/llama.cpp#build)，或者使用WSL

多谢回复，还需要请教您一个问题。
我在bash run_sft.sh的时候，会提示`NOTE: Redirects are currently not supported in Windows or MacOs.`以及随后会报错`ImportError: cannot import name 'Module' from '_pytest.doctest'`、`ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1)`以及`run_clm_sft_with_peft.py FAILED`。
这是不是意味着只能在Linux环境下运行呀。
截图如下
![1](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/58661545/4050fded-34b0-4855-aa44-784bfcd9d9f1)
![2](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/58661545/79639616-2fd3-4dce-b38b-f426ed900355)
![3](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/58661545/5d7a2fef-3ab1-4d8e-b594-7a71b72b6acf)

**Comment by ymcui** [comment]
> > 1. 使用最新llama.cpp看看能不能解决
> > 2. windows下比较容易出现各种编译问题，可以考虑使用其他编译方式比如[Cmake](https://github.com/ggerganov/llama.cpp#build)，或者使用WSL
> 
> 多谢回复，还需要请教您一个问题。 我在bash run_sft.sh的时候，会提示`NOTE: Redirects are currently not supported in Windows or MacOs.`以及随后会报错`ImportError: cannot import name 'Module' from '_pytest.doctest'`、`ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1)`以及`run_clm_sft_with_peft.py FAILED`。 这是不是意味着只能在Linux环境下运行呀。 截图如下 ![1](https://user-images.githubusercontent.com/58661545/249777518-4050fded-34b0-4855-aa44-784bfcd9d9f1.png) ![2](https://user-images.githubusercontent.com/58661545/249777543-79639616-2fd3-4dce-b38b-f426ed900355.png) ![3](https://user-images.githubusercontent.com/58661545/249777562-5d7a2fef-3ab1-4d8e-b594-7a71b72b6acf.png)

参考：https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/603
