### ISSUE TITLE
FP 16精度问题

### ISSUE THREAD

**Issue by wangjvjie** [ymcui/Chinese-LLaMA-Alpaca#685]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-13B

### 操作系统

Linux

### 详细描述问题
我使用原始的LLaMA模型不会出现FP16精度问题，但使用和13B plus merge了的模型之后，就会下面的错误
Traceback (most recent call last):
  File "/home/h3c/pythonProject/GPT-social-engineering-main/SE-GPT/pretrain.py", line 650, in <module>
    main()
  File "/home/h3c/pythonProject/GPT-social-engineering-main/SE-GPT/pretrain.py", line 634, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/h3c/anaconda3/envs/pytorch/lib/python3.9/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/home/h3c/anaconda3/envs/pytorch/lib/python3.9/site-packages/transformers/trainer.py", line 1987, in _inner_training_loop
    self.accelerator.clip_grad_norm_(
  File "/home/h3c/anaconda3/envs/pytorch/lib/python3.9/site-packages/accelerate/accelerator.py", line 1893, in clip_grad_norm_
    self.unscale_gradients()
  File "/home/h3c/anaconda3/envs/pytorch/lib/python3.9/site-packages/accelerate/accelerator.py", line 1856, in unscale_gradients
    self.scaler.unscale_(opt)
  File "/home/h3c/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "/home/h3c/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/cuda/amp/grad_scaler.py", line 212, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.

### 依赖情况（代码类问题务必提供）
我修改了部分的代码，使用模型并行进行训练，然后训练脚本如下，主要就是使用模型并行，将torchrun改成了正常的python启动，然后在代码中将device map修改了一下：
lr=1.5e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/home/h3c/pythonProject/GPT-social-engineering-main/merged_llama_model/13B-hf
chinese_tokenizer_path=./merged_tokenizer_hf
dataset_dir=../data/
data_cache=../data_cache_dir
per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=1
output_dir=./out_Lora

deepspeed_config_file=ds_zero2_no_offload.json
export CUDA_VISIBLE_DEVICES=0,1,2,3
python pretrain.py \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --seed 284 \
    --fp16 False\
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 1 \
    --save_steps 200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --block_size 1024 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float32 \
    --gradient_checkpointing \

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by Lathashree01** [comment]
Hi, I am facing a similar issue.

I am getting an error : ValueError: Attempting to unscale FP16 gradients.

If I turn off fp16, I am running out of memory and training is not starting.

My startup command:

python src/models/run_clm_pt_with_peft.py
--deepspeed /home/git_repos/thesis/src/models/ds_zero2_no_offload.json
--model_name_or_path /home/llama-hf
--tokenizer_name_or_path /home/llama-hf
--dataset_dir /home/git_repos/thesis/datasets/mlm_data/
--data_cache_dir temp_data_cache_dir
--validation_split_percentage 0.001
--per_device_train_batch_size 1
--per_device_eval_batch_size 1
--do_train
--seed 25
--fp16
--num_train_epochs 1
--lr_scheduler_type cosine
--learning_rate 2e-4
--warmup_ratio 0.05
--weight_decay 0.01
--logging_strategy steps
--logging_steps 10
--save_strategy steps
--save_total_limit 3
--save_steps 200
--gradient_accumulation_steps 8
--preprocessing_num_workers 8
--block_size 512
--output_dir output_dir
--overwrite_output_dir
--ddp_timeout 30000
--logging_first_step True
--lora_rank 8
--lora_alpha 32
--trainable "q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
--modules_to_save "embed_tokens,lm_head"
--lora_dropout 0.05
--torch_dtype float16
--ddp_find_unused_parameters False

Please provide suggestions as to how to resolve this.

**Comment by wangjvjie** [comment]
> Hi, I am facing a similar issue.
> 
> I am getting an error : ValueError: Attempting to unscale FP16 gradients.
> 
> If I turn off fp16, I am running out of memory and training is not starting.
> 
> My startup command:
> 
> python src/models/run_clm_pt_with_peft.py --deepspeed /home/git_repos/thesis/src/models/ds_zero2_no_offload.json --model_name_or_path /home/llama-hf --tokenizer_name_or_path /home/llama-hf --dataset_dir /home/git_repos/thesis/datasets/mlm_data/ --data_cache_dir temp_data_cache_dir --validation_split_percentage 0.001 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --do_train --seed 25 --fp16 --num_train_epochs 1 --lr_scheduler_type cosine --learning_rate 2e-4 --warmup_ratio 0.05 --weight_decay 0.01 --logging_strategy steps --logging_steps 10 --save_strategy steps --save_total_limit 3 --save_steps 200 --gradient_accumulation_steps 8 --preprocessing_num_workers 8 --block_size 512 --output_dir output_dir --overwrite_output_dir --ddp_timeout 30000 --logging_first_step True --lora_rank 8 --lora_alpha 32 --trainable "q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj" --modules_to_save "embed_tokens,lm_head" --lora_dropout 0.05 --torch_dtype float16 --ddp_find_unused_parameters False
> 
> Please provide suggestions as to how to resolve this.

I think is the bug of the script merge_lora_with_llama_low_mem.py, because when i use the origin llama-hf model, it won't appear these questions, and while i'm using merged model, the error apear. i'm finding the bug in the script now.

**Comment by wangjvjie** [comment]
> Hi, I am facing a similar issue.
> 
> I am getting an error : ValueError: Attempting to unscale FP16 gradients.
> 
> If I turn off fp16, I am running out of memory and training is not starting.
> 
> My startup command:
> 
> python src/models/run_clm_pt_with_peft.py --deepspeed /home/git_repos/thesis/src/models/ds_zero2_no_offload.json --model_name_or_path /home/llama-hf --tokenizer_name_or_path /home/llama-hf --dataset_dir /home/git_repos/thesis/datasets/mlm_data/ --data_cache_dir temp_data_cache_dir --validation_split_percentage 0.001 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --do_train --seed 25 --fp16 --num_train_epochs 1 --lr_scheduler_type cosine --learning_rate 2e-4 --warmup_ratio 0.05 --weight_decay 0.01 --logging_strategy steps --logging_steps 10 --save_strategy steps --save_total_limit 3 --save_steps 200 --gradient_accumulation_steps 8 --preprocessing_num_workers 8 --block_size 512 --output_dir output_dir --overwrite_output_dir --ddp_timeout 30000 --logging_first_step True --lora_rank 8 --lora_alpha 32 --trainable "q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj" --modules_to_save "embed_tokens,lm_head" --lora_dropout 0.05 --torch_dtype float16 --ddp_find_unused_parameters False
> 
> Please provide suggestions as to how to resolve this.

can you try to add float() in unpermute and permute function? i'm training a model on my server, so i'm currently not able to test my thoughts. 
`def unpermute(w):
    return (
        w.view(n_heads, 2, dim // n_heads // 2, dim).transpose(1, 2).reshape(dim, dim).float()
    )
`

**Comment by airaria** [comment]
We previous found that it might be related to `fp16`, `gradient_checkpointing` and deepspeed. Can you please try different configuration of `fp16` and gradient_checkpointing? such as set `fp16` to `True` and set `gradient_checkpointing` to `True` or `False`?

**Comment by Lathashree01** [comment]
> > Hi, I am facing a similar issue.
> > I am getting an error : ValueError: Attempting to unscale FP16 gradients.
> > If I turn off fp16, I am running out of memory and training is not starting.
> > My startup command:
> > python src/models/run_clm_pt_with_peft.py --deepspeed /home/git_repos/thesis/src/models/ds_zero2_no_offload.json --model_name_or_path /home/llama-hf --tokenizer_name_or_path /home/llama-hf --dataset_dir /home/git_repos/thesis/datasets/mlm_data/ --data_cache_dir temp_data_cache_dir --validation_split_percentage 0.001 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --do_train --seed 25 --fp16 --num_train_epochs 1 --lr_scheduler_type cosine --learning_rate 2e-4 --warmup_ratio 0.05 --weight_decay 0.01 --logging_strategy steps --logging_steps 10 --save_strategy steps --save_total_limit 3 --save_steps 200 --gradient_accumulation_steps 8 --preprocessing_num_workers 8 --block_size 512 --output_dir output_dir --overwrite_output_dir --ddp_timeout 30000 --logging_first_step True --lora_rank 8 --lora_alpha 32 --trainable "q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj" --modules_to_save "embed_tokens,lm_head" --lora_dropout 0.05 --torch_dtype float16 --ddp_find_unused_parameters False
> > Please provide suggestions as to how to resolve this.
> 
> can you try to add float() in unpermute and permute function? i'm training a model on my server, so i'm currently not able to test my thoughts. `def unpermute(w): return ( w.view(n_heads, 2, dim // n_heads // 2, dim).transpose(1, 2).reshape(dim, dim).float() ) `



> > Hi, I am facing a similar issue.
> > I am getting an error : ValueError: Attempting to unscale FP16 gradients.
> > If I turn off fp16, I am running out of memory and training is not starting.
> > My startup command:
> > python src/models/run_clm_pt_with_peft.py --deepspeed /home/git_repos/thesis/src/models/ds_zero2_no_offload.json --model_name_or_path /home/llama-hf --tokenizer_name_or_path /home/llama-hf --dataset_dir /home/git_repos/thesis/datasets/mlm_data/ --data_cache_dir temp_data_cache_dir --validation_split_percentage 0.001 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --do_train --seed 25 --fp16 --num_train_epochs 1 --lr_scheduler_type cosine --learning_rate 2e-4 --warmup_ratio 0.05 --weight_decay 0.01 --logging_strategy steps --logging_steps 10 --save_strategy steps --save_total_limit 3 --save_steps 200 --gradient_accumulation_steps 8 --preprocessing_num_workers 8 --block_size 512 --output_dir output_dir --overwrite_output_dir --ddp_timeout 30000 --logging_first_step True --lora_rank 8 --lora_alpha 32 --trainable "q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj" --modules_to_save "embed_tokens,lm_head" --lora_dropout 0.05 --torch_dtype float16 --ddp_find_unused_parameters False
> > Please provide suggestions as to how to resolve this.
> 
> I think is the bug of the script merge_lora_with_llama_low_mem.py, because when i use the origin llama-hf model, it won't appear these questions, and while i'm using merged model, the error apear. i'm finding the bug in the script now.


I am not using any other file that run_clm_with_peft,py. So guess this is not the problem with me.

**Comment by Lathashree01** [comment]
> We previous found that it might be related to `fp16`, `gradient_checkpointing` and deepspeed. Can you please try different configuration of `fp16` and gradient_checkpointing? such as set `fp16` to `True` and set `gradient_checkpointing` to `True` or `False`?

I think the issue was because of deepspeed and something with bitsandbytes, it said incompatible installation without GPU support. I created a new environment and tried running it, looks fine for now.

Thanks for the help.
