### ISSUE TITLE
如果在中文LLaMa进行sft训练，想问下词表的路径 是选择LLaMa的还是选择alpaca的？两者差一个pad。

### ISSUE THREAD

**Issue by sixgold993** [ymcui/Chinese-LLaMA-Alpaca#688]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

None

### 基础模型

None

### 操作系统

None

**Comment by TCHSDUFH** [comment]
那看你想微调哪一个吧，wiki也写了不能混用

**Comment by ymcui** [comment]
再仔细看看文档：https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/指令精调脚本
```
--tokenizer_name_or_path: Chinese-Alpaca tokenizer所在的目录。⚠️ 注意此处只能传入Alpaca词表（49954），其余会报错。
```
