### ISSUE TITLE
模型合并完转hf后在text-generation-webui上如何在回答的时候输出中文

### ISSUE THREAD

**Issue by SpenserCai** [ymcui/Chinese-LLaMA-Alpaca#69]
模型合并完转hf后在text-generation-webui上如何在回答的时候输出中文。
不是用中文模型是无法理解中文的，是用合并后的中文模型，能理解中文了但是回答还是英文。

**Comment by DumoeDss** [comment]
很迷，我一般会在开头问一句
“白日依山尽”的下一句是什么？
回答是中文的话之后就都是中文了。

**Comment by SpenserCai** [comment]
要用in-context learning 的方法让他是说中文，然后中文模型的in-context learning如果从context内容多的话就不行了
