### ISSUE TITLE
預訓練的一些疑問

### ISSUE THREAD

**Issue by cyc00518** [ymcui/Chinese-LLaMA-Alpaca#693]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-Plus-13B

### 操作系统

Linux

### 详细描述问题

您好,
我已成功利用指令精調alpaca-13b,但因顯存實在吃緊,改用了zero3的配置,訓練5000steps後,已確認精調有效果,但果然指令精調的方式還是不能學習到新知識,所以想利用預訓練增加模型知識。

想請教以下問題:
1. 若基於合併後的llama-13b-plus精調,為了有問答的效果,若將預訓練後的lora權重與alpaca-13b-plus一起合併,是否會擁有新知識也有問答能力呢？

2. 同樣是llama-13b,自己一樣設置同樣的lora參數,一樣不訓練embed_tokens,lm_head,參可以訓練的量只有不到1%多,甚至可以在單張3090上訓練,但您們的卻明顯多出很多可訓練參數量,是因為你們有擴充詞表的關係嗎？

3. 我看您有說過預訓練資料就是一般的文本,想請教文本中若有換行之類的會有關係嗎？以及最多字數是否有限制呢？

謝謝您耐心回覆！

**Comment by airaria** [comment]
1. 没有看太明白。总之，合并的模型要保持直系关系（lora是基于A模型训练的，就和A模型合并）
2. 增加的可训练参数量来自embed_tokens和lm_head，是为了训练新增的token
3. 换行符保不保留都可以训练，你可以采取你自己认为合理的方式处理数据；最多字数是指什么？总的训练字数没有限制，每条样本的最大长度是512，[技术报告](https://arxiv.org/abs/2304.08177)中有说明。

**Comment by cyc00518** [comment]
@airaria 謝謝您的回覆,
關於1補充如下, 想問的是step4的可行性?
1.  
step1 合併成plus模型: llama-13b原版 + llama-13b-plus-lora權重 -> llama-13b-plus模型
step2 plus模型再預訓練 : llama-13b-plus模型 ＋ 預訓練 - > 產生llama-13b-plus-pt-lora權重
step3 合併成plus-pt模型: llama-13b-plus模型 +  llama-13b-plus-pt-lora權重 ->  llama-13b-plus-pt模型 
目前step3模型仍不具備對答能力, 想問的是可否直接進行以下的step4?
還是說一定要再自己做過指令精調?
step4.  llama-13b-plus-pt模型 +  您們的alpaca-13b-plus-lora權重 - > 擁有alpaca-13b-plus-lora對答能力的llama-13b-plus-pt模型

**Comment by iMountTai** [comment]
step4不可行，需要基于step3的模型继续指令精调。lora只能与训练时的基底模型合并。
