### ISSUE TITLE
13B模型输出问题

### ISSUE THREAD

**Issue by quanpinjie** [ymcui/Chinese-LLaMA-Alpaca#694]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型推理

### 基础模型

Alpaca-Plus-7B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```
./llama.cpp/main -m c13b/13B/ggml-model-f16.bin  --color  -ins -c 8192 --temp 0.2-n 40960 --repeat_penalty 1.1 -b 16 -t 32 -ngl 30
main: warning: model does not support context sizes greater than 2048 tokens (8192 specified);expect poor results
main: build = 740 (447ccbe)
main: seed  = 1688056098
ggml_init_cublas: found 2 CUDA devices:
  Device 0: NVIDIA A2
  Device 1: NVIDIA A2
llama.cpp: loading model from c13b/13B/ggml-model-f16.bin
llama_model_load_internal: format     = ggjt v1 (pre #1405)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 8192
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 1 (mostly F16)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: using CUDA for GPU acceleration
ggml_cuda_set_main_device: using device 0 (NVIDIA A2) as main device
llama_model_load_internal: mem required  = 8723.50 MB (+ 1608.00 MB per state)
llama_model_load_internal: allocating batch_size x 1 MB = 16 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 30 repeating layers to GPU
llama_model_load_internal: offloaded 30/43 layers to GPU
llama_model_load_internal: total VRAM used: 18168 MB
llama_new_context_with_model: kv self size  = 6400.00 MB

system_info: n_threads = 32 / 48 | AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
main: interactive mode on.
Reverse prompt: '### Instruction:

'
sampling: repeat_last_n = 64, repeat_penalty = 1.100000, presence_penalty = 0.000000, frequency_penalty = 0.000000, top_k = 40, tfs_z = 1.000000, top_p = 0.950000, typical_p = 1.000000, temp = 0.200000, mirostat = 0, mirostat_lr = 0.100000, mirostat_ent = 5.000000
generate: n_ctx = 8192, n_batch = 16, n_predict = 40960, n_keep = 2

== Running in interactive mode. ==
 - Press Ctrl+C to interject at any time.
 - Press Return to return control to LLaMa.
 - To return control without starting a new line, end your input with '/'.
 - If you want to submit another line, end your input with '\'.

> 帮我介绍一下北京

### 依赖情况（代码类问题务必提供）

```
torch                         1.12.1
transformers                  4.24.0
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/2564119/090c348a-8e7f-41ee-a338-f3542cce9b5e)

**Comment by ymcui** [comment]
所以你的问题是llama.cpp不输出？
1. Alpaca模型需要`-f`指定指令模板
2. `-c`开太大，LLaMA系列最长也就是2048，超过2.5K以上之后PPL会显著上升
3. 你命令里`--temp 0.2-n 40960`粘一起了？ 另外`-n`也开太大了

**Comment by quanpinjie** [comment]
我改变了参数，13B模型的输出效果从我的测试中似乎没有7b好，不知哪里不对
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/2564119/9d0e74d3-745b-445b-a162-1b06b916f938)
y


> 所以你的问题是llama.cpp不输出？
> 
> 1. Alpaca模型需要`-f`指定指令模板
> 2. `-c`开太大，LLaMA系列最长也就是2048，超过2.5K以上之后PPL会显著上升
> 3. 你命令里`--temp 0.2-n 40960`粘一起了？ 另外`-n`也开太大了

**Comment by quanpinjie** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/2564119/c2689398-881d-4bb9-b784-629c03bf7ed9)

**Comment by ymcui** [comment]
你提问的时候就没讲清楚，所以很混乱，
1）你应该说清楚用的是具体哪一个模型，Alpaca-13B？Alpaca-Plus-13B？
2）你核对过合并文件的SHA256吗？
3）从log里看，llama.cpp版本太老了，模型文件也不是最新格式的。

**Comment by quanpinjie** [comment]
> 你提问的时候就没讲清楚，所以很混乱， 1）你应该说清楚用的是具体哪一个模型，Alpaca-13B？Alpaca-Plus-13B？ 2）你核对过合并文件的SHA256吗？ 3）从log里看，llama.cpp版本太老了，模型文件也不是最新格式的。

使用的是 Alpaca Plus 13B, 核对过sha256
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/2564119/0cdc8302-0115-41ec-8653-d8a3bfb60893)

<img width="926" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/2564119/9756c71d-5167-4c22-8096-25755f9cc85e">

**Comment by ymcui** [comment]
如果模型正确且使用的是新版llama.cpp的话，你就去example目录看一下plus-13b的输出把，如果能得到类似结果就说明是正常的。
