### ISSUE TITLE
Finetune时添加的prompts还是原版的英文的吗？

### ISSUE THREAD

**Issue by Porraio** [ymcui/Chinese-LLaMA-Alpaca#7]
请问fine-tune中文语料的时候，还是用的原版的alpaca.json里的prompts吗，比如：
Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n### Response:\n
目前写信、写文章那还没复现，其他的似乎没问题。
所以预测也是这样加上去的？
十分感谢回答！

**Comment by airaria** [comment]
是的，精调以及预测时用的都是原版不带input的模版。

**Comment by Porraio** [comment]
> 是的，精调以及预测时用的都是原版不带input的模版。

那有input的数据是怎么处理的呢？

**Comment by airaria** [comment]
> > 是的，精调以及预测时用的都是原版不带input的模版。
> 
> 那有input的数据是怎么处理的呢？

用`f"{instruction}+\n+{input}"`这种方式拼接在一起，原版的针对input的模版就不用了。
