### ISSUE TITLE
在合并模型的时候出现 Killed 输出

### ISSUE THREAD

**Issue by Lufffya** [ymcui/Chinese-LLaMA-Alpaca#70]
![image](https://user-images.githubusercontent.com/49063302/230572261-758c1431-a73b-4963-b761-a3ea3f21a73e.png)

合并 llama 和 lora 模型的时候，加载模型过程中就断开了，这是什么问题，是我的显存不够吗？（3090）

**Comment by airaria** [comment]
大概率是内存不足。
可以尝试用优化了内存占用的最新的合并脚本[merge_llama_with_chinese_lora.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_llama_with_chinese_lora.py)并指定--offload_dir
