### ISSUE TITLE
请教训练过程中验证集上loss的计算方式

### ISSUE THREAD

**Issue by dazhaxie0526** [ymcui/Chinese-LLaMA-Alpaca#700]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [x] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

训练过程中如果添加了验证集，会输出验证集上的loss，想请教一下验证集上的loss是如何计算的，损失函数是怎样的？是否有相关知识介绍，谢谢！
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/5484115/8fc2fcca-a6b6-48ae-93cd-85e86d9044ae)

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by airaria** [comment]
和训练的loss计算是一样的

**Comment by dazhaxie0526** [comment]
> 和训练的loss计算是一样的

请教一下，训练集上怎么计算loss的？有相关介绍文档可以看一下吗？

**Comment by TCHSDUFH** [comment]
你好，请问你用的多大的验证集呀？

**Comment by dazhaxie0526** [comment]
这个也没有固定的比例，根据自己的情况吧，我的训练集和验证集设置的比例为9:1.
