### ISSUE TITLE
预训练后的模型早合并时报错

### ISSUE THREAD

**Issue by hanwenbo6619** [ymcui/Chinese-LLaMA-Alpaca#701]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

cd Chinese-LLaMA-Alpaca && python scripts/merge_llama_with_chinese_lora.py \
    --base_model /llama/llama-dl/original_llama_hf \
    --lora_model /llama/chinese-llama-lora-7b \
    --output_type huggingface \
    --output_dir Chinese-LLaMA-Alpaca/output-pt/pt_lora_model
```


### 依赖情况（代码类问题务必提供）

```
!pip install torch==1.13.1
!pip install transformers==4.28.1
!pip install sentencepiece==0.1.97
!pip install peft==0.3.0
```

### 运行日志或截图

Base model: /home/hanwb/llama/llama-dl/original_llama_hf
LoRA model(s) ['/home/hanwb/llama/Chinese-LLaMA-Alpaca/output-pt/pt_lora_model']:
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.08s/it]
Peft version: 0.3.0
Loading LoRA for 7B model
Loading LoRA /home/hanwb/llama/Chinese-LLaMA-Alpaca/output-pt/pt_lora_model...
base_model vocab size: 32000
tokenizer vocab size: 49953
Extended vocabulary size to 49953
Loading LoRA weights
Merging with merge_and_unload...
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/hanwb/llama/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora.py:327 in <module>  │
│                                                                                                  │
│   324 │   │   │   │   assert base_model_sd[original_key].dtype == torch.float16                  │
│   325 │   │                                                                                      │
│   326 │   │   # did we do anything?                                                              │
│ ❱ 327 │   │   assert not torch.allclose(first_weight_old, first_weight)                          │
│   328 │                                                                                          │
│   329 │   tokenizer.save_pretrained(output_dir)                                                  │
│   330                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError

**Comment by airaria** [comment]
用的是发布的模型和原版权重？我运行并没有问题。

**Comment by HouYueJie** [comment]
@hanwenbo6619 请问这个问题解决了么？我现在也是这个问题，预训练的adapter_model.bin只有几百k
