### ISSUE TITLE
请教一个自定义Llama模型的预训练问题

### ISSUE THREAD

**Issue by SiriusWy** [ymcui/Chinese-LLaMA-Alpaca#702]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

我只有一块A100 80G的卡，所以想做一个简单的实验，快速训练一个小的基座llama模型：
1. 使用transformers库的run_clm.py脚本，自定义了一个2亿参数规模的“小”llama模型，模型结构对应参数为“--config_overrides="num_attention_heads=8,num_hidden_layers=8,hidden_size=1024,intermediate_size=3072,vocab_size=49953"”
2. 感谢本项目的大佬提供的中文扩展词表，我用的本项目中分词模型tokenizer.model，其他分词器配置文件我看了一下好像和原版llama没有差别。
3. 训练数据采用2GB的中文语料(beyond/chinese_clean_passages_80m)，训练了20个小时，4~5个epoch，train_loss从8.x多降到3.x越来越缓慢。
4. 模型效果很差。表现为：
 （1）生成的语句前言不搭后语
 （2）生成语句没法自动停止，这个我看issues中也有人提到过这种问题。
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/9431785/4314c346-eca6-472e-b4d8-1fe0bb289867)

求教一下各位大佬这种可能是什么原因呢？是分词器我没有配置对吗，还是数据和训练问题呢？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by airaria** [comment]
如果只有与训练而没有做指令精调，instruction-following的能力自然不太好

**Comment by SiriusWy** [comment]
> 

可能是我提问的截图有点误导性，我只是想让模型能有续写出通顺的句子，再放个截图
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/9431785/81efaf4b-e0f5-4a69-9d51-98e4d3884dda)
但是模型似乎不能完成

**Comment by SiriusWy** [comment]
> 如果只有与训练而没有做指令精调，instruction-following的能力自然不太好

可能是我提问的截图有点误导性，我只是想让模型能有续写出通顺的句子，再放个截图。模型似乎没有这个能力。
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/9431785/19cd9b61-d463-4ac6-a68b-7cc8c45777a6)

**Comment by SiriusWy** [comment]
@airaria 麻烦您再看下我的问题，感谢！
如果不需要对transformers库的run_clm.py脚本做什么特别的处理的话，我采用的2GB的中文数据在2亿参数的超小模型上训练有可能是哪里不对呢？

**Comment by wuhuanon** [comment]
你运行的命令是什么

**Comment by upwindflys** [comment]
我也遇到这个问题了，就是一句完整的话也说不对，楼主有解决这个问题么
