### ISSUE TITLE
关于第一阶段预训练

### ISSUE THREAD

**Issue by xxr11** [ymcui/Chinese-LLaMA-Alpaca#71]
您好，是否可以请教两个小问题

第一阶段预训练的描述为“仅训练embedding，在尽量不干扰原模型的情况下适配新增的中文词向量”，查看网络参数可以看到预训练的参数有embedding和lora两部分，所以说这里也训练了lora部分？第二阶段训练加载这部分lora参数了吗？

另外想请教一下第一阶段chinese_llama_lora_7b模型已经通过大量中文进行预训练，为什么测试中文问题得到的更多的还是英文答案？

**Comment by airaria** [comment]
> 您好，是否可以请教两个小问题
> 
> 第一阶段预训练的描述为“仅训练embedding，在尽量不干扰原模型的情况下适配新增的中文词向量”，查看网络参数可以看到预训练的参数有embedding和lora两部分，所以说这里也训练了lora部分？第二阶段训练加载这部分lora参数了吗？
> 
> 另外想请教一下第一阶段chinese_llama_lora_7b模型已经通过大量中文进行预训练，为什么测试中文问题得到的更多的还是英文答案？

第一个问题：
预训练第一阶段仅训练了embedding，没有lora
预训练第二阶段的lora是新添加的。第二阶段训练了embedding，Lora和lm_head
放出的权重是第二阶段结束后相对于预训练未开始时有差异部分的权重。

第二个问题：
1. 虽然我们用了约20G的中文语料，但与LLaMA本身预训练阶段用的数据量比还是很少（仅有原版预训练语料大小的0.5%），所以可能还是远没训练充分。
2. LLaMA未经过指令训练，不能很好地对齐输入的指令。如用Chinese-Alpaca模型，模型的输出基本都是中文了。

**Comment by ehion** [comment]
@airaria 想问下用20G中文语料预训练后，预训练模型对英文语料的回答效果怎么样？
