### ISSUE TITLE
chinese_sp.model是如何训练的，是否能给出详细步骤及代码实现

### ISSUE THREAD

**Issue by zemu121** [ymcui/Chinese-LLaMA-Alpaca#713]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by airaria** [comment]
https://github.com/google/sentencepiece#usage-instructions

**Comment by zemu121** [comment]
1. sentencepiece的model_type中没有bbpe，直接选择bpe吗
2. 如果有一些垂直领域的专业词汇，但词汇比较长，需要添加自定义词典吗

**Comment by iMountTai** [comment]
训练参数未做过多调整，基本上指定生成词表大小即可，具体任务还请参考sentencepiece文档。

**Comment by zemu121** [comment]
请问chinese-llama扩充的20k词表 是在多大的中文语料上进行扩充的
