### ISSUE TITLE
关于gradio_demo里prompt格式问题

### ISSUE THREAD

**Issue by zeng9t** [ymcui/Chinese-LLaMA-Alpaca#716]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型推理

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

请问gradio_demo.py里当有history时，我理解即多轮对话在进行了，例如对于history为("请记住你是awesome机器人", "好的，我是awesome机器人"), ("Who are you?", "我是awesome机器人")，当前用户问题为"再说一次你是谁？"
prompt进模型的格式是：

请记住你是awesome机器人

\### Response: 好的，我是awesome机器人

\### Instruction:
Who are you?

\### Response: 我是awesome机器人

\### Instruction:
再说一次你是谁？

请问这里第一个\### Instruction为什么要去掉呢？（对应代码是input = input[len("### Instruction:\n"):]

**Comment by sunyuhan19981208** [comment]
我刚刚做了一次测试，并没有出现您所提到的结果
实际输入到模型中的prompt如下：
```
Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
请记住你是awesome机器人

### Response: 😊 谢谢您的夸奖！作为一个 AI 助手，我一直致力于帮助您解决问题和提供服务。如果您需要任何帮助或有任何疑问，请随时与我联系。 我会尽力为您提供最好的答案和服务。 ??? 💻??? 📲???

### Instruction:
Who are you?

### Response: 
 

Below is an instruction that describes a task. Write a response that appropriately completes the request.
model designed to assist and engage in natural conversations with users. My purpose is to help make communication easier, more efficient, and more enjoyable for both humans and machines. 💬 😁 🔴 🥀️ 🚫 🙈 👋 👀 🎉 👌 👗 ���

### Instruction:
再说一次你是谁？

### Response:
```
具体generate prompt的代码在`gradio_demo.py: 255-264行` :
``` python
history[-1][1] = ""
if len(history) != 0:
    input = "".join(["### Instruction:\n" +
                     i[0] +
                     "\n\n" +
                     "### Response: " +
                     i[1] +
                     ("\n\n" if i[1] != "" else "") for i in history])
    if len(input) > max_memory:
        input = input[-max_memory:]
prompt = generate_prompt(input)
```

**Comment by zeng9t** [comment]
> 超过max memory的部分被clip掉了，您可以在启动选项通过设置`--max_memory 4096`增大memory长度
> 
> 具体generate prompt的代码在`gradio_demo.py: 255-264行` :
> 
> ```python
> history[-1][1] = ""
> if len(history) != 0:
>     input = "".join(["### Instruction:\n" +
>                      i[0] +
>                      "\n\n" +
>                      "### Response: " +
>                      i[1] +
>                      ("\n\n" if i[1] != "" else "") for i in history])
>     if len(input) > max_memory:
>         input = input[-max_memory:]
> prompt = generate_prompt(input)
> ```

这个memory的设置有什么限制么？

**Comment by sunyuhan19981208** [comment]
> > 超过max memory的部分被clip掉了，您可以在启动选项通过设置`--max_memory 4096`增大memory长度
> > 具体generate prompt的代码在`gradio_demo.py: 255-264行` :
> > ```python
> > history[-1][1] = ""
> > if len(history) != 0:
> >     input = "".join(["### Instruction:\n" +
> >                      i[0] +
> >                      "\n\n" +
> >                      "### Response: " +
> >                      i[1] +
> >                      ("\n\n" if i[1] != "" else "") for i in history])
> >     if len(input) > max_memory:
> >         input = input[-max_memory:]
> > prompt = generate_prompt(input)
> > ```
> 
> 这个memory的设置有什么限制么？

没有限制，你设置的越大，history就越长，越长的前缀推理越慢
