### ISSUE TITLE
继续预训练loss训飞

### ISSUE THREAD

**Issue by HalcyonLiang** [ymcui/Chinese-LLaMA-Alpaca#727]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 基础模型
llama-13B
### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```
transformers==4.29.1
deepspeed==0.9.4

### 运行日志或截图

```
# 请在此处粘贴运行日志
```
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/20160375/a422044d-9a31-4c97-9a58-55c709b8928b)

13B-llama 全参数继续预训练，
试过在前面保存step重启，每次训飞的step都不太一样，数据是wudao，应该不是数据问题
bf16, deepspeed zero2 的配置， learing-rate 1e-4
有大佬遇到过同样问题吗？

**Comment by LiuChen19960902** [comment]
> ### 提交前必须检查以下项目
> * [x]  请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
> * [x]  由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
> * [x]  我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
> * [x]  第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
> * [x]  模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行
> 
> ### 问题类型
> None
> 
> ### 基础模型
> None
> 
> ### 操作系统
> None
> 
> ### 详细描述问题
> ```
> # 请在此处粘贴运行代码（如没有可删除该代码块）
> ```
> 
> ### 依赖情况（代码类问题务必提供）
> ```
> # 请在此处粘贴依赖情况
> ```
> 
> transformers==4.29.1 deepspeed==0.9.4
> 
> ### 运行日志或截图
> ```
> # 请在此处粘贴运行日志
> ```
> 
> ![image](https://user-images.githubusercontent.com/20160375/251673342-a422044d-9a31-4c97-9a58-55c709b8928b.png)
> 
> 13B-llama 全参数继续预训练， 试过在前面保存step重启，每次训飞的step都不太一样，数据是wudao，应该不是数据问题 bf16, deepspeed zero2 的配置， learing-rate 1e-4 有大佬遇到过同样问题吗？

有没有可能是学习率的问题，我这几天也在做预训练，并没有出现这个现象。

**Comment by HalcyonLiang** [comment]
> > ### 提交前必须检查以下项目
> > 
> > * [x]   请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
> > * [x]   由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
> > * [x]   我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
> > * [x]   第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
> > * [x]   模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行
> > 
> > ### 问题类型
> > None
> > ### 基础模型
> > None
> > ### 操作系统
> > None
> > ### 详细描述问题
> > ```
> > # 请在此处粘贴运行代码（如没有可删除该代码块）
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### 依赖情况（代码类问题务必提供）
> > ```
> > # 请在此处粘贴依赖情况
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > transformers==4.29.1 deepspeed==0.9.4
> > ### 运行日志或截图
> > ```
> > # 请在此处粘贴运行日志
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/20160375/251673342-a422044d-9a31-4c97-9a58-55c709b8928b.png)
> > 13B-llama 全参数继续预训练， 试过在前面保存step重启，每次训飞的step都不太一样，数据是wudao，应该不是数据问题 bf16, deepspeed zero2 的配置， learing-rate 1e-4 有大佬遇到过同样问题吗？
> 
> 有没有可能是学习率的问题，我这几天也在做预训练，并没有出现这个现象。

我试过3e-5,2e-5,前面降的会慢一些，但也出现过一次这个情况，大佬也是13B以上的吗？我7B的模型没有遇到这个问题过。
另外，如果是resume之后直接降低学习率，这个可行吗？

**Comment by LiuChen19960902** [comment]
我7和13都尝试过，都没有loss飞掉的情况。之前全参数fintune chatglm的时候出现过这种情况，当时是因为学习率的问题。
俺也不是大佬啦，我也是在各种尝试，hh。

另外想问问你的wudao数据集是哪里下载的呀，我在https://data.baai.ac.cn/details/WuDaoCorporaText下载，速度特别慢

**Comment by HalcyonLiang** [comment]
> 我7和13都尝试过，都没有loss飞掉的情况。之前全参数fintune chatglm的时候出现过这种情况，当时是因为学习率的问题。 俺也不是大佬啦，我也是在各种尝试，hh。
> 
> 另外想问问你的wudao数据集是哪里下载的呀，我在[https://data.baai.ac.cn/details/WuDaoCorporaText下载，速度特别慢](https://data.baai.ac.cn/details/WuDaoCorporaText%E4%B8%8B%E8%BD%BD%EF%BC%8C%E9%80%9F%E5%BA%A6%E7%89%B9%E5%88%AB%E6%85%A2)

wudao数据很早之前下载的了，也是这个路径

**Comment by yuemengrui** [comment]
大佬，你好，问个问题，你是用的run_clm_pt_with_peft.py去掉peft相关部分来全量预训练吗？训练速度怎么样？我全量预训练block_size=2048, batch_size=1152. 训练一步需要1800s，好慢的感觉

**Comment by xixy** [comment]
请问问题解决了吗？我用6e-5，13B，也会有loss飞的问题
