### ISSUE TITLE
什么意思，这个图我真的绷不住了

### ISSUE THREAD

**Issue by CXLiang123** [ymcui/Chinese-LLaMA-Alpaca#729]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

效果问题

### 基础模型

Alpaca-7B

### 操作系统

Windows

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/129077921/c8b0bdde-11cf-4efd-8887-5ff22fb54dd2)

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/129077921/2aa771e2-b8fb-49be-9505-b08eaddc9843)

**Comment by ymcui** [comment]
有什么奇怪的？用了ChatGPT爬取的数据，自然就是会按统计规律得到这种回复。我们并没有单独加入一些身份类的训练数据。

**Comment by CXLiang123** [comment]
> 有什么奇怪的？用了ChatGPT爬取的数据，自然就是会按统计规律得到这种回复。我们并没有单独加入一些身份类的训练数据。

原来如此，没想到大佬居然会看问题，我微调试试效果~
