### ISSUE TITLE
继续训练Chinese-Alpaca模型的LoRA权重，新的lora与哪个模型合并呢

### ISSUE THREAD

**Issue by Agreewithu** [ymcui/Chinese-LLaMA-Alpaca#731]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-7B

### 操作系统

Linux

### 详细描述问题

```
r=1e-4
lora_rank=8
lora_alpha=32
# lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
lora_trainable="q_proj,v_proj"
# modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/mnt/data.common/Agreewithu/DRX/llm/Chinese-Alpaca-Plus-7B_full_model_hf
chinese_tokenizer_path=/mnt/data.common/Agreewithu/DRX/llm/chinese_alpaca_plus_lora_7b/tokenizer.model
dataset_dir=/mnt/data.common/Agreewithu/DRX/datasets/dietFeedback/normal/train
per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=8
output_dir=/mnt/data.common/Agreewithu/DRX/llm/sft_output/normal
peft_model=/mnt/data.common/Agreewithu/DRX/llm/chinese_alpaca_plus_lora_7b
validation_file=/mnt/data.common/Agreewithu/DRX/datasets/dietFeedback/normal/eval/cla_normal_format.json

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 1 run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed $RANDOM \
    --fp16 \
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 100 \
    --save_steps 200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --peft_path ${peft_model} \
    --ddp_find_unused_parameters False
```
您好，上面的脚本代码是按照Wiki指南修改后的run_sft.sh的代码，我的目标是继续训练Chinese-Alpaca模型的LoRA权重，我的pretrained_model使用的是llama(转化为hf格式)+chinese_llama_plus_lora_7b+chinese_alpaca_plus_lora_7b，完成训练后，我得到了新的lora模型，请问合并时，我需要按照llama(转化为hf格式)+chinese_llama_plus_lora_7b+新的lora模型，还是用于训练的pretrained_model+新的lora模型呢，新的lora模型的adapter_config如下：
```json
{
  "base_model_name_or_path": "/mnt/data.common/Agreewithu/DRX/llm/Chinese-Alpaca-Plus-7B_full_model_hf",
  "bias": "none",
  "enable_lora": null,
  "fan_in_fan_out": false,
  "inference_mode": true,
  "lora_alpha": 128,
  "lora_dropout": 0.05,
  "merge_weights": false,
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 64,
  "target_modules": [
    "q_proj",
    "v_proj",
    "k_proj",
    "o_proj",
    "gate_proj",
    "down_proj",
    "up_proj"
  ],
  "task_type": "CAUSAL_LM"
}
```
ps：我已经尝试了llama(转化为hf格式)+chinese_llama_plus_lora_7b+新的lora模型这种合并方式，效果比较差

**Comment by iMountTai** [comment]
wiki还是没有仔细阅读啊
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/35353688/4b6804b4-0c80-49e1-a2e3-78273c5ac859)
你的pretrained_model应该是是*llama(转化为hf格式)+chinese_llama_plus_lora_7b*,完成训练后，得到的lora和你的pretrained_model合并。
指出一个问题：你既然加载了peft_model,则`modules_to_save`应该是有参数的["embed_tokens", "lm_head"],可是adapter_config里的参数为null,建议确认一下依赖版本，不一定哪里出了问题

**Comment by Agreewithu** [comment]
谢谢回复，我当时读wiki的时候也非常纠结这个问题，我本来也是想pretrained_model使用llama(转化为hf格式)+chinese_llama_plus_lora_7b的，但是我参考了一个[教程视频](https://www.bilibili.com/video/BV1Qu411t7ML/?spm_id_from=333.880.my_history.page.click&vd_source=2c35e0e673c5927bb84df6ccd60d2896)，教程视频中是使用llama(转化为hf格式)+chinese_llama_plus_lora_7b+chinese_alpaca_plus_lora_7b的，所以我改用了后者。

**Comment by Agreewithu** [comment]
后来，我将新训练出来的lora与llama(转化为hf格式)+chinese_llama_plus_lora_7b+chinese_alpaca_plus_lora_7b模型合并了，发现问答的效果还行。不过我仍然不知道这两种做法是不是一样的，我要按照wiki上做吗？

----

然后就是``modules_to_save``的问题，我是参考了wiki上的这一步，对chinese_alpaca_plus_lora_7b有所改动的，这样做是可以的吗？
![1688901753926](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/86297268/5467dd22-4b09-4e53-a73e-e9e169bf2a59)

**Comment by iMountTai** [comment]
以wiki为准。

**Comment by Agreewithu** [comment]
> 以wiki为准。

请问后一个问题，``modules_to_save``我按照wiki上说明的这样改动是可以的吗
