### ISSUE TITLE
使用Transformers推理，最新的Transformers已经没有scripts/inference_hf.py脚本

### ISSUE THREAD

**Issue by aawuj** [ymcui/Chinese-LLaMA-Alpaca#736]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型量化和部署

### 基础模型

LLaMA-33B

### 操作系统

Linux

### 详细描述问题

上月还有，最近Transformers有更新。

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by airaria** [comment]
放到inference目录下了：
https://github.com/ymcui/Chinese-LLaMA-Alpaca/tree/main/scripts/inference

**Comment by aawuj** [comment]
好的，我以为是使用官网的脚本。thx




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ymcui/Chinese-LLaMA-Alpaca"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月11日(星期二) 下午3:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ymcui/Chinese-LLaMA-Alpaca] 使用Transformers推理，最新的Transformers已经没有scripts/inference_hf.py脚本 (Issue #736)





 
放到inference目录下了：
 https://github.com/ymcui/Chinese-LLaMA-Alpaca/tree/main/scripts/inference
