### ISSUE TITLE
chinese_llama_plus_lora_7b中的tokenizer, vocab size不正确。

### ISSUE THREAD

**Issue by yeli7068** [ymcui/Chinese-LLaMA-Alpaca#748]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

下载问题

### 基础模型

LLaMA-7B

### 操作系统

Windows

### 详细描述问题

```
python scripts\merge_llama_with_chinese_lora_low_mem.py \
--base_model F:\LLaMA\models\elinas--llama-7b-hf-transformers-4.29 \
--lora_model F:\LLaMA\LLaMA7b\chinese_alpaca_plus_lora_7b,F:\LLaMA\LLaMA7b\chinese_llama_plus_lora_7b \
--output_dir F:\LLaMA\LLaMA7b\LLmMA_7B_chinese_lora_merged
```

您好，

当加载chinese_llama_plus_lora_7b时，提示
```
AssertionError: The vocab size of the first tokenizer is 49954
```

根据提问规则，我更新了代码库，也确认了chinese_alpaca_plus_lora_7b和chinese_llama_plus_lora_7b的sha256值是对的。

### 依赖情况（代码类问题务必提供）

```
peft               0.3.0
torch              2.0.1
transformers       4.30.2
```
按照手动模型合并与转换的建议，我尝试安装torch=1.3.1，目前处于安装阶段。但查看源码，这里的报错和torch版本应该没直接关系。所以故此来寻求帮助。

### 运行日志或截图

```
Base model: F:\LLaMA\models\elinas--llama-7b-hf-transformers-4.29
LoRA model(s) ['F:\\LLaMA\\LLaMA7b\\chinese_alpaca_plus_lora_7b', 'F:\\LLaMA\\LLaMA7b\\chinese_llama_plus_lora_7b']:
Loading F:\LLaMA\LLaMA7b\chinese_alpaca_plus_lora_7b
Loading F:\LLaMA\LLaMA7b\chinese_llama_plus_lora_7b
Traceback (most recent call last):
  File "F:\LLaMA\Chinese-LLaMA-Alpaca-4.2\Chinese-LLaMA-Alpaca-4.2\scripts\merge_llama_with_chinese_lora_low_mem.py", line 263, in <module>
    assert t1_vocab_size<=t2_vocab_size, \
AssertionError: The vocab size of the first tokenizer is 49954
The vocab size of the second tokenizer is 49953, found to be smaller than 49954
This is not the intended use. Please check your model and tokenizer.
```

**Comment by ymcui** [comment]
```
--lora_model F:\LLaMA\LLaMA7b\chinese_alpaca_plus_lora_7b,F:\LLaMA\LLaMA7b\chinese_llama_plus_lora_7b \
```

你调换一下顺序，改成先写llama再写alpaca。
另外提醒一下，这样合并出来的模型是Chinese-Alpaca-Plus-7B。

**Comment by yeli7068** [comment]
确实可以了！谢谢解答！
