### ISSUE TITLE
关于33B的plus版

### ISSUE THREAD

**Issue by nuoma** [ymcui/Chinese-LLaMA-Alpaca#757]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-33B

### 操作系统

Linux

### 详细描述问题

你好，我看到您的33B基座模型。如果我想弄一个33B plus版本（假设有足够的计算资源），使用您的Lora继续预训练方法（rank=8），加上另两个小参数量的100GB中文语料，就可以做到。我这么理解是正确的吗？谢谢

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by ymcui** [comment]
是的，不过我们很快就要发布plus-33b了。😅

**Comment by nuoma** [comment]
谢谢解答，只是想确认一下我的理解是否正确。

**Comment by nuoma** [comment]
谢谢解答，只是想确认一下我的理解是否正确。issue closed
