### ISSUE TITLE
教程有误

### ISSUE THREAD

**Issue by xiaoxixiao** [ymcui/Chinese-LLaMA-Alpaca#76]
python scripts/merge_llama_with_chinese_lora.py \
    --base_model path_to_original_llama_hf_dir \
    --lora_model path_to_chinese_llama_or_alpaca_lora \
    --model_type 7B \
    --output_dir path_to_output_dir
    
    该段model_type应该传递的是model_size

**Comment by ymcui** [comment]
谢谢，昨晚已经修复这个问题了
