### ISSUE TITLE
微调模型数据填充问题

### ISSUE THREAD

**Issue by xzqxnet0990** [ymcui/Chinese-LLaMA-Alpaca#768]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-7B

### 操作系统

Linux

### 详细描述问题

Alpaca格式sft数据
```
"instruction": "自定义算子类型",
"input": "",
"output": "自定义算子类型 用户可以自定义的算子类型如下： 
|算子类型 |描述|示例|计算方式| |:--:|:--:|:--:|:--:| |流式命令|对搜索返回的事件数据逐个应用SPL命令进行处理|eval,fields,rex,rename,replace,where,search
|集中式/分布式| |转换统计命令|将搜索返回的事件转换为用于统计目的的数值|chart,stats,rare,timechart,top|集中式/分布式| |搜索导出|将搜索分析结果导出到第三方平台|export
|集中式/分布式|[PAD][PAD][PAD][PAD][PAD][PAD]
```
问题一：我看到chinese-alpaca-lora中special_tokens_map的 "pad_token": "[PAD]",  所以使用[PAD]将output填充至2048长度，
这种方式训练后获得的推理长度会比较长，但是结果中会出现[PAD]。我不知道我的做法是否正确？
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/51184271/8964b08a-fb0e-4359-981a-b08df336a129)
问题二：我先将上步骤中output内的数据整合，第一步是pre_training到模型中，然后再使用pre_training的结果，使用alpaca格式指令精调pre_training文件，两个步骤均训练了25000步，结果部分准确但是混杂了不准确的内容。
损失函数在pt过程中比较正常，但是在sft过程中梯度几乎消失。
<img width="404" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/51184271/192b05ff-b3a8-47b4-b023-c6913fb407c0">

### 依赖情况（代码类问题务必提供）

```
peft                          0.3.0.dev0
torch                         2.0.1
transformers                  4.30.2
transformers-stream-generator 0.0.4
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/51184271/ba24f286-e543-464b-b19e-f4d86d7a71d7)

**Comment by bigcash** [comment]
是不是第一步和第二步的微调中数据用的是一样的，只不过一个是按无监督，一个是按有监督来做的微调啊
