### ISSUE TITLE
plus和pro模型的区别在什么地方呢？

### ISSUE THREAD

**Issue by minlik** [ymcui/Chinese-LLaMA-Alpaca#769]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

效果问题

### 基础模型

None

### 操作系统

None

### 详细描述问题

根据项目wiki描述，plus模型的回复相对较短，pro模型的回复相对较长。
请问下是通过SFT数据的input/output长度调整的吗？还是有其他实现思路？后续如果要在现有模型的基础上，继续进行SFT的话，是推荐plus模型，还是pro模型呢？二者的区别大不大？
感谢🙏

**Comment by ymcui** [comment]
如果要继续做SFT的话，推荐在Pro系列模型上做。
如果是为了刷榜（NLU类任务）的话推荐Plus系列，因为Pro版效果会略低一些（比如C-Eval在一个点以内）。

**Comment by minlik** [comment]
> 如果要继续做SFT的话，推荐在Pro系列模型上做。 如果是为了刷榜（NLU类任务）的话推荐Plus系列，因为Pro版效果会略低一些（比如C-Eval在一个点以内）。

再请教一下，二者训练时的主要区别在什么地方呢？

**Comment by HouYueJie** [comment]
@ymcui 请教一下，如果做垂直领域预训练的话，Pro是不是更好？

**Comment by bigcash** [comment]
我看了一下，plus是基座模型，可以做续写任务。pro是指令微调，可以聊天对话。不知道说的对不对。
也就是你有一堆无监督数据，就用plus，如果你只有一些指令数据（有监督），那就用pro

**Comment by HouYueJie** [comment]
@bigcash 多谢回复。我试过plus的llama_lora上面进行预训练，然后在与alpaca_lora结合。效果不好，llama_lora的继续预训练会崩.

**Comment by X-Buring** [comment]
> 

alpaca也有plus版本的，pro我理解是作者在alpaca-plus上又做了一些改动、产生的最新版本。如果你愿意的话，也可以用alpaca-plus版本为基础，继续进行sft
