### ISSUE TITLE
请教模型大小和gpu显存之间的关系

### ISSUE THREAD

**Issue by TCHSDUFH** [ymcui/Chinese-LLaMA-Alpaca#774]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

这方面的新手，之前一直玩的是7b版本的，所以手上的显卡够用。但是如果我想再继续训练33B的模型，大小有60G，这是不是意味着手上的显卡的显存一定要大于60g才可以？如果这样这个成本有点高啊。尤其现在的llama2 70B的，我下载完模型大小有250多g。不是很明白模型大小和gpu显存之间的关系，请教。

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```
。

### 运行日志或截图

```
# 请在此处粘贴运行日志
```
。

**Comment by ymcui** [comment]
你可以看这个表：https://github.com/ymcui/Chinese-LLaMA-Alpaca#合并模型
33B在FP16下是60G，但你可以尝试用8bit或者4bit训练，这样显存占用就会有所降低。
实际训练时还要考虑优化器状态、梯度等的存储，所以上面的表格只是模型能装载进去的基本要求。

**Comment by TCHSDUFH** [comment]
readme我都认真研究过。还是有些疑问，在训练的时候就需要把模型全部加载到显存中吗？我查了下nvlink也不能叠加显存，那对于这些特别大的模型就只能用8/4bit来训练吗。譬如最新的llama2，模型大小几乎都翻番了，如果用4bit来的话，精度损失会不会比较大。

**Comment by ymcui** [comment]
现在说的这些都是高效训练的方法，精度方面需要做权衡。
超大规模模型训练方面建议你了解一下deepspeed, megatron-lm这类工具。
