### ISSUE TITLE
lora训练LLAMA PLUS的时候，爆显存，我现在是4张A10，一共是90G.怎么量化，或者能否微调

### ISSUE THREAD

**Issue by DRZJ1** [ymcui/Chinese-LLaMA-Alpaca#782]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```

lr=1e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/home/ubuntu/llama-plus
chinese_tokenizer_path=/home/ubuntu/chinese-alpaca-plus-lora-13b
dataset_dir=/home/ubuntu/Chinese-LLaMA-Alpaca/data
per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=8
output_dir=output_dir_alpaca
peft_model=/home/ubuntu/chinese-alpaca-plus-lora-13b
validation_file=/home/ubuntu/Chinese-LLaMA-Alpaca/data/alpaca_data_zh_51k.json

deepspeed_config_file=/home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 4 /home/ubuntu/Chinese-LLaMA-Alpaca/scripts/training/run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed $RANDOM \
    --fp16 \
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 100 \
    --save_steps 200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length 512 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --peft_path ${peft_model} \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False
显存暴了，能否量化，90GB不够吗？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```
库没问题

### 运行日志或截图

```
# 请在此处粘贴运行日志
```torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 22.19 GiB total capacity; 21.25 GiB already allocated; 4.50 MiB free; 21.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by iMountTai** [comment]
模型训练不是按照总显存估计训练可行性的，建议尝试zero3/int8/qlora等训练方式。

**Comment by DRZJ1** [comment]
请问现在怎么在您提供的代码基础上QLORA

**Comment by DRZJ1** [comment]
或者请问怎么能够量化一下

**Comment by iMountTai** [comment]
可以搜一下github上关于qlora的实现

**Comment by iMountTai** [comment]
transformers目前支持load_in_8bit(或者4bit)，可以参考实现
