### ISSUE TITLE
预训练最大长度扩展到5k

### ISSUE THREAD

**Issue by chensongcan** [ymcui/Chinese-LLaMA-Alpaca#789]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

请教一个问题：llama是2048的最大长度，如果我想训练更长的输入长度，理论直接吧最大长度外扩就行，比如改为5120，这样子直接训用小一点的数据可以训动，但是一旦上了大的语料数据loss就训不动，从2e-5到3e-4都试过，都训不动

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by kukupigs** [comment]
可否引入llama.c的方式提升模型性能

**Comment by chensongcan** [comment]
> 

这个应该是sft阶段的一些长度扩展，我目前是直接想在预训练阶段扩展

**Comment by bigcash** [comment]
请问预训练的loss训不动，是指loss一直不下降？词表扩中文词表了吗？loss值一直在多少徘徊？大的语料数据有多少token啊

**Comment by chensongcan** [comment]
> 请问预训练的loss训不动，是指loss一直不下降？词表扩中文词表了吗？loss值一直在多少徘徊？大的语料数据有多少token啊
用了中文词表，loss在9不动，目前是5btoken
