### ISSUE TITLE
为什么Alpaca新增一个pad token

### ISSUE THREAD

**Issue by caihaunqai** [ymcui/Chinese-LLaMA-Alpaca#795]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

您好，感谢您的工作。请问为什么Alpaca新增一个pad token，这样的好处是微调精度更高吗？还是有什么额外的原因？有劳解答下，感谢。

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by airaria** [comment]
对样本paddding到相同长度，为了让一个batch可以装下不同长度的样本。

**Comment by caihaunqai** [comment]
> 对样本paddding到相同长度，为了让一个batch可以装下不同长度的样本。

原本的LlaMA就有pad token，为什么需要继续定义一个呢？

**Comment by airaria** [comment]
我们参考的是alpaca官方实现：https://github.com/tatsu-lab/stanford_alpaca/blob/main/train.py
如果加载llama tokenizer，tokenizer.pad_token是None的
