### ISSUE TITLE
</s>为什么在预训练阶段没有使用？

### ISSUE THREAD

**Issue by weilx2267** [ymcui/Chinese-LLaMA-Alpaca#796]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

其他问题

### 基础模型

LLaMA-Plus-7B

### 操作系统

Linux

### 详细描述问题

你好，问一下为什么在预训练阶段没有使用</s>标识？用不用这个标识影响大吗？

### 运行日志或截图

```
07/28/2023 12:07:12 - INFO - __main__ - Num train_samples  6906
07/28/2023 12:07:12 - INFO - __main__ - training example:
07/28/2023 12:07:12 - INFO - __main__ -  ick Riordan)的《波西·杰克逊》系列<s> -罗尔德·达尔(Roald Dahl)的《玛蒂尔达》<s> -C·S·刘易斯(C.S. Lewis)的《纳尼亚传奇》<s> -莫里斯·森达克(Maurice Sendak)的《野兽之地》<s> 编写Python脚本以解析大型表格数据文件。"""<s> 编写Python脚本以解析大型表格数据文件。<s> """<s><s> import pandas as pd<s><s> def parse_datafile(file_name):<s>     df = pd.read_csv(file_name, sep='\t', engine='python')<s>     return df<s><s> if __name__ == '__main__':<s>     print(parse_datafile("data.txt"))<s> 设计一个3D游戏关卡。我使用各种3D建模软件设计了一个3D游戏关卡。我创建了一个大型开放区域，具有草地地形和各种障碍物。我添加了树木、岩石和水体，以提供更多的视觉吸引力和不同的高度。我还添加了建筑和其他结构，以提供更多的探索机会和目标。最后，我添加了敌人和NPC，为关卡提供一些挑战，提供沉浸式体验。<s> 将以下短语从小写键盘转换为大写I love to learnI LOVE TO LEARN<s> 将以下文本分成三段Alice打开门，发现自己身处一个没有墙壁的小屋子里，屋子中央有一张桌子。桌子周围有七张小椅子，旁边还有一个小脚凳。<s><s> 桌子上有一盘淡蓝色的蛋糕和一把刀子。空气中弥漫着香草和糖的味道，并且在桌子的两端摆放着两碟冰淇淋。<s><s> Alice从未见过如此奇妙的事情，几乎激动得无法坐下。Alice打开门，发现自己身处一个没有墙壁的小屋子里，屋子中央有一张桌子。桌子周围有七张小椅子，旁边还有一个小脚凳。<s><s> 桌子上有一盘淡蓝色的蛋糕和一把刀子。空气中弥漫着香草和糖的味道，并且在桌子的两端摆放着两碟冰淇淋。<s><s> Alice从未见过如此奇妙的事情，几乎激动得无法坐下。<s> 寻找与“fleeting”意思相同的单词短暂的。<s>将以下
```

**Comment by sfrozha** [comment]
一般情况下预训练不需要加eos token的吧，语言模型期望是能无限生成；可以在下游任务finetune的数据中加入eos来针对性地停止生成。我是这样理解的
