### ISSUE TITLE
请问Alpaca词表（49954）是怎么生成的？详细步骤是什么？

### ISSUE THREAD

**Issue by jackielyc** [ymcui/Chinese-LLaMA-Alpaca#805]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by airaria** [comment]
参见[wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/训练细节#准备工作词表扩充)

**Comment by jackielyc** [comment]
> 参见[wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E8%AE%AD%E7%BB%83%E7%BB%86%E8%8A%82#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C%E8%AF%8D%E8%A1%A8%E6%89%A9%E5%85%85)

49953 我会了，请问49954怎么生成的？那个pad token如何添加上去。目前我是通过改源码人为添加了一个pad token。文档里面没有写49954是怎么生成的。

**Comment by airaria** [comment]
> > 参见[wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E8%AE%AD%E7%BB%83%E7%BB%86%E8%8A%82#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C%E8%AF%8D%E8%A1%A8%E6%89%A9%E5%85%85)
> 
> 49953 我会了，请问49954怎么生成的？那个pad token如何添加上去。目前我是通过改源码人为添加了一个pad token。文档里面没有写49954是怎么生成的。

我们也是手动添加的。
