### ISSUE TITLE
关于本项目33B模型使用Deepspeed ZeRO3进行训练的求助

### ISSUE THREAD

**Issue by xuexidi** [ymcui/Chinese-LLaMA-Alpaca#812]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-33B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```
您好，再次感谢您的开源。
对于本项目的PT和SFT模式+deepspeed stage2 offload模式我已经跑通了，单张显卡显存占用大概在70G左右。
现在我想尝试基于deepspeed stage3 offload模式进行训练，但是启动训练的时候发现了一些报错。
**第一次报错：**
Error: DeepSpeed Zero-3 is not compatible with `low_cpu_mem_usage=True` or with passing a `device_map`.
于是我把scripts/training/run_clm_pt_with_peft.py里line: 538里的 `low_cpu_mem_usage=True` 修改为 `low_cpu_mem_usage=True`。
**第二次报错：**
### 看日志是正常加载了模型，但是在模型的 `model_vocab_size = model.get_output_embeddings().weight.size(0)`数值为 `0`，因此程序报错。但是我不知道为什么会报错，期望得到您的帮助，非常感谢！
报错摘要：
ValueError: The combination of base model (size: 0) and tokenizer (size: 49953) is not a valid configuration. Please check our project wiki for further information.

报错详情：
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:52<00:00,  7.44s/it]
[INFO|modeling_utils.py:3295] 2023-08-03 19:23:34,164 >> All model checkpoint weights were used when initializing LlamaForCausalLM.

[INFO|modeling_utils.py:3303] 2023-08-03 19:23:34,164 >> All the weights of LlamaForCausalLM were initialized from the model checkpoint at /home/xue/codes/Chinese-LLaMA-Alpaca-main/scripts/training/merged_models/Chinese-llama_33B_merge_HF.
If your task is similar to the task the model of the checkpoint was trained on, you can already use LlamaForCausalLM for predictions without further training.
[INFO|configuration_utils.py:537] 2023-08-03 19:23:34,169 >> loading configuration file /home/xue/codes/Chinese-LLaMA-Alpaca-main/scripts/training/merged_models/Chinese-llama_33B_merge_HF/generation_config.json
[INFO|configuration_utils.py:577] 2023-08-03 19:23:34,170 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "pad_token_id": 0,
  "transformers_version": "4.30.0"
}

Traceback (most recent call last):
  File "/home/xue/codes/Chinese-LLaMA-Alpaca-main/scripts/training/run_clm_pt_ds3_with_peft.py", line 642, in <module>
    main()
  File "/home/xue/codes/Chinese-LLaMA-Alpaca-main/scripts/training/run_clm_pt_ds3_with_peft.py", line 552, in main
    raise ValueError(
### ValueError: The combination of base model (size: 0) and tokenizer (size: 49953) is not a valid configuration. Please check our project wiki for further information.
Valid configurations (base model / tokenizer):
- Continue pre-training original LLaMA: 32000 / 32000
- Pre-training Chinese LLaMA based on original LLaMA: 32000 / 49953
- Continue pre-training Chinese LLaMA: 49953 / 49953
- Continue pre-training Chinese Alpaca: 49954 / 49954

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by xuexidi** [comment]
补充：我的deepspeed配置如下：
`{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 100,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1e-10
    },

    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": true
        },
        "sub_group_size": 1e9,
        "allgather_partitions": true,
        "allgather_bucket_size": 1e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 1e8,
        "contiguous_gradients": true,
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_fp16_weights_on_model_save": true
    },

    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}
`

**Comment by xuexidi** [comment]
反馈：我把 `model_vocab_size = model.get_output_embeddings().weight.size(0)`相关的校验代码删掉就可以正常进行deepspeed ZeRO3进行训练了。

**Comment by Zhou-Zoey** [comment]
> 反馈：我把 `model_vocab_size = model.get_output_embeddings().weight.size(0)`相关的校验代码删掉就可以正常进行deepspeed ZeRO3进行训练了。

请问这样的训练结果也是正常的吗？那为什么会出现这样的情况呢

**Comment by XuJianzhi** [comment]
哥，求助：
从哪里下载 LLAMA_PLUS_33B ？？

我想用 chinese_alpaca_plus_lora_33b，加压模型后，发现 有个文件 YOU_MUST_ALSO_DOWNLOAD_LLAMA_PLUS_33B.md

然后我从llama申请那里是只有llama2，没有llama1的；huggingface上也只有 pinkmanlove/llama-33b-hf，也没有plus。

下载能从哪里下载 llama_plus_33b 原版模型？？？
