### ISSUE TITLE
预训练从1000 steps断点处加载模型参数报错

### ISSUE THREAD

**Issue by zzzhaoguziji** [ymcui/Chinese-LLaMA-Alpaca#814]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```
涉及代码主要为 run_clm_pt_with_peft.py 中的内容。
注释
    old_state_dict = model.state_dict
    model.state_dict = (
        lambda self, *_, **__: get_peft_model_state_dict(self, old_state_dict())
    ).__get__(model, type(model))
后仍然不行。

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```
<img width="635" alt="llama2报错" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/38344228/74971760-6b0b-47ff-ad05-074d19612d4b">

**Comment by Qmymy** [comment]
同样的问题

**Comment by Qmymy** [comment]
已经找到了解决方法https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/464#issuecomment-1568328617

**Comment by zzzhaoguziji** [comment]
> 已经找到了解决方法[#464 (comment)](https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/464#issuecomment-1568328617)

感谢
