### ISSUE TITLE
模型合并之后sha256值不对；使用Transformers推理时，回答完问题之后，重复

### ISSUE THREAD

**Issue by Zxlan** [ymcui/Chinese-LLaMA-Alpaca#816]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型转换和合并

### 基础模型

LLaMA-7B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```
基模型：7B
sha256：
![图片](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/24890392/2b697180-2d6c-405f-a48b-8dfc072c8b2c)

lora模型：Chinese-LLaMA-Plus-7B
sha256：
![图片](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/24890392/9e6a6766-9b9a-424e-8905-3a673da6a26c)

模型合并完的sha256：
![图片](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/24890392/0619b859-b3d9-4418-a726-20818975309f)

使用Transformers推理结果：
![图片](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/24890392/f4144c45-0e13-4c05-a065-cd11e5670e75)

请问是选用的基和lora不匹配吗？该怎么解决这个问题呢？

**Comment by ymcui** [comment]
llama模型不是拿来对话用的，对话请选用alpaca系列模型。
另外，我们的二代模型已经发布了，更推荐使用（网络带宽充足的话可以直接下载完整模型，无需合并步骤），
二代项目地址：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2

**Comment by Zxlan** [comment]
> llama模型不是拿来对话用的，对话请选用alpaca系列模型。 另外，我们的二代模型已经发布了，更推荐使用（网络带宽充足的话可以直接下载完整模型，无需合并步骤）， 二代项目地址：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2

感谢感谢，那我去试用一下
