### ISSUE TITLE
when I do sft using run_clm_sft_with_peft.py, the eval loss is always Nan, can anyone fine a solution ?

### ISSUE THREAD

**Issue by trannhatquy** [ymcui/Chinese-LLaMA-Alpaca#823]
### Check before submitting issues

- [X] Make sure to pull the latest code, as some issues and bugs have been fixed.
- [X] Due to frequent dependency updates, please ensure you have followed the steps in our [Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)
- [X] I have read the [FAQ section](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/FAQ) AND searched for similar issues and did not find a similar problem or solution
- [X] Third-party plugin issues - e.g., [llama.cpp](https://github.com/ggerganov/llama.cpp), [text-generation-webui](https://github.com/oobabooga/text-generation-webui), [LlamaChat](https://github.com/alexrozanski/LlamaChat), we recommend checking the corresponding project for solutions
- [X] Model validity check - Be sure to check the model's [SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md). If the model is incorrect, we cannot guarantee its performance

### Type of Issue

Model training and fine-tuning

### Base Model

LLaMA-13B

### Operating System

Linux

### Dependencies (must be provided for code-related issues)

```
# Please copy-and-paste your dependencies here.
```

### Execution logs or screenshots

{'eval_loss': nan, 'eval_runtime': 236.5281, 'eval_samples_per_second': 8.202, 'eval_steps_per_second': 8.202, 'epoch': 0.03}

**Comment by zzx16045223** [comment]
> ### Check before submitting issues
> * [x]  Make sure to pull the latest code, as some issues and bugs have been fixed.
> * [x]  Due to frequent dependency updates, please ensure you have followed the steps in our [Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)
> * [x]  I have read the [FAQ section](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/FAQ) AND searched for similar issues and did not find a similar problem or solution
> * [x]  Third-party plugin issues - e.g., [llama.cpp](https://github.com/ggerganov/llama.cpp), [text-generation-webui](https://github.com/oobabooga/text-generation-webui), [LlamaChat](https://github.com/alexrozanski/LlamaChat), we recommend checking the corresponding project for solutions
> * [x]  Model validity check - Be sure to check the model's [SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md). If the model is incorrect, we cannot guarantee its performance
> 
> ### Type of Issue
> Model training and fine-tuning
> 
> ### Base Model
> LLaMA-13B
> 
> ### Operating System
> Linux
> 
> ### Describe your issue in detail
> _No response_
> 
> ### Dependencies (must be provided for code-related issues)
> ```
> # Please copy-and-paste your dependencies here.
> ```
> 
> ### Execution logs or screenshots
> {'eval_loss': nan, 'eval_runtime': 236.5281, 'eval_samples_per_second': 8.202, 'eval_steps_per_second': 8.202, 'epoch': 0.03}
你好，请问这个问题你解决了吗？我现在也有这个问题
