### ISSUE TITLE
请问如何指定哪一张卡去做推理？

### ISSUE THREAD

**Issue by bigmover** [ymcui/Chinese-LLaMA-Alpaca#826]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

请问linux 如何指定哪一张卡做推理？CUDA_VISIBLE_DEVICE? @iMountTai

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by iMountTai** [comment]
`CUDA_VISIBLE_DEVICE=gpu_id`或者参数中指明`--gpus gpu_id`

**Comment by bigmover** [comment]
> `CUDA_VISIBLE_DEVICE=gpu_id`或者参数中指明`--gpus gpu_id`

谢谢大佬指教！因为./main -h 没发现--gpus 没看到响应参数，我 使用命令CUDA_VISIBLE_DEVICES=7 ./main -m llama_model/7B/ggml-model-q4.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.3 去测试了一下速度。
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/26063296/a3cd941a-e760-4177-8355-64b2cd556587)
发现速度又点慢，是本身对GPU的支持就很差吗？

**Comment by ymcui** [comment]
> > `CUDA_VISIBLE_DEVICE=gpu_id`或者参数中指明`--gpus gpu_id`
> 
> 谢谢大佬指教！因为./main -h 没发现--gpus 没看到响应参数，我 使用命令CUDA_VISIBLE_DEVICES=7 ./main -m llama_model/7B/ggml-model-q4.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.3 去测试了一下速度。 ![image](https://user-images.githubusercontent.com/26063296/261189376-a3cd941a-e760-4177-8355-64b2cd556587.png) 发现速度又点慢，是本身对GPU的支持就很差吗？

-----


建议你还是认真填写我们的issue模板，你全填的None。实际你这个是llama.cpp相关的问题。
上面的回复给出的是基于huggingface的inference脚本使用方法。
你的命令：
```
CUDA_VISIBLE_DEVICES=7 ./main -m llama_model/7B/ggml-model-q4.bin --color -f prompts/alpaca.txt -ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.3
```
并没有使用GPU。llama.cpp中需要先和cuBLAS一起编译，然后通过`-ngl`参数指定offload到GPU的模型层数。

**Comment by ymcui** [comment]
另外，你的模型路径似乎是llama模型。需要注意的是llama模型不能和alpaca模板（命令中`-f prompts/alpaca.txt`）一起使用。如果要使用llama.cpp聊天交互，请用Alpaca模型。

**Comment by bigmover** [comment]
> 另外，你的模型路径似乎是llama模型。需要注意的是llama模型不能和alpaca模板（命令中`-f prompts/alpaca.txt`）一起使用。如果要使用llama.cpp聊天交互，请用Alpaca模型。
不好意思！我回去研究一下。感谢大佬的指正！谢谢

**Comment by bigmover** [comment]
> 另外，你的模型路径似乎是llama模型。需要注意的是llama模型不能和alpaca模板（命令中`-f prompts/alpaca.txt`）一起使用。如果要使用llama.cpp聊天交互，请用Alpaca模型。

不好意思！我回去研究一下。感谢大佬指正！谢谢
