### ISSUE TITLE
合并lora_13b时出错

### ISSUE THREAD

**Issue by zlht812** [ymcui/Chinese-LLaMA-Alpaca#83]
错误如下：
[root@ai-model-test LLaMA]# python scripts/merge_llama_with_chinese_lora.py \
>     --base_model ../../LLaMA/output/chinese_base_llama_13b_hf \
>     --lora_model ../../LLaMA/chineseLLM/chinese_alpaca_lora_13b \
>     --output_dir ../../LLaMA/output/chinese_alpaca_all_13b
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████| 3/3 [00:36<00:00, 12.02s/it]
Extended vocabulary size: 49954
Traceback (most recent call last):
  File "../../LLaMA/scripts/merge_llama_with_chinese_lora.py", line 146, in <module>
    new_state_dict[new_k] = unpermute(v)
  File "../../LLaMA/scripts/merge_llama_with_chinese_lora.py", line 99, in unpermute
    w.view(n_heads, 2, dim // n_heads // 2, dim).transpose(1, 2).reshape(dim, dim)
RuntimeError: shape '[32, 2, 64, 4096]' is invalid for input of size 26214400

chinese_alpaca_lora_13b.zip sha256校验正确。
用的13B原模型与7B一起下载，7B合并没有问题，可正常运行。

**Comment by ymcui** [comment]
不知道你用的是不是main branch最新代码，转换13B需要指定`--model_size 13B`。

**Comment by dunzic** [comment]
我同样遇到了一样的问题，llama 13B 和chinese-llama-lora-13b 合并

 RuntimeError: shape '[32, 2, 64, 4096]' is invalid for input of size 26214400

**Comment by airaria** [comment]
> 我同样遇到了一样的问题，llama 13B 和chinese-llama-lora-13b 合并
> 
> RuntimeError: shape '[32, 2, 64, 4096]' is invalid for input of size 26214400

拉取使用最新的代码，合并13B需要指定`--model_size 13B`。

**Comment by zlht812** [comment]
> 不知道你用的是不是main branch最新代码，转换13B需要指定`--model_size 13B`。
已经更新了，问题解决🙏。

**Comment by zlht812** [comment]
> 
感谢🙏，解决了我的问题。

**Comment by shmily91** [comment]
> > 
> 
> 感谢🙏，解决了我的问题。

我要到这个问题了，你怎么解决的

**Comment by zlht812** [comment]
> 

感谢，解决了我的问题🙏

**Comment by zlht812** [comment]
> > 我同样遇到了一样的问题，llama 13B 和chinese-llama-lora-13b 合并
> > RuntimeError: shape '[32, 2, 64, 4096]' is invalid for input of size 26214400
> 
> 拉取最新的代码，合并13B需要指定`--model_size 13B`。

是这样做的，问题解决了，🙏

**Comment by zlht812** [comment]
> > 
> > 感谢🙏，解决了我的问题。
> 
> 我要到这个问题了，你怎么解决的

**Comment by zlht812** [comment]
> 

解决方案：
1.使用最新的merge_llama_with_chinese_lora.py 
2.合并命令时，增加--model_size 13B

**Comment by shmily91** [comment]
> > 
> 
> 解决方案： 1.使用最新的merge_llama_with_chinese_lora.py 2.合并命令时，增加--model_size 13B

感谢你，我的问题也解决了

**Comment by hcl242** [comment]
感谢🙏，问题解决。
