### ISSUE TITLE
Error `TypeError: not a string` while merging lora

### ISSUE THREAD

**Issue by Naozumi520** [ymcui/Chinese-LLaMA-Alpaca#837]
### Check before submitting issues

- [X] Make sure to pull the latest code, as some issues and bugs have been fixed.
- [X] Due to frequent dependency updates, please ensure you have followed the steps in our [Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)
- [X] I have read the [FAQ section](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/FAQ) AND searched for similar issues and did not find a similar problem or solution
- [X] Third-party plugin issues - e.g., [llama.cpp](https://github.com/ggerganov/llama.cpp), [text-generation-webui](https://github.com/oobabooga/text-generation-webui), [LlamaChat](https://github.com/alexrozanski/LlamaChat), we recommend checking the corresponding project for solutions
- [X] Model validity check - Be sure to check the model's [SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md). If the model is incorrect, we cannot guarantee its performance

### Type of Issue

Model conversion and merging

### Base Model

LLaMA-7B

### Operating System

macOS

### Describe your issue in detail

With following the instruction in [here](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/手动模型合并与转换), I got the error  `TypeError: not a string` from sentencepiece.

### Execution logs or screenshots

```
naozumi@Naozumis-MacBook-Pro Chinese-LLaMA-Alpaca % python3.10 /Users/naozumi/Downloads/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora_low_mem.py \
    --base_model meta-llama/Llama-2-7b-chat-hf \
    --lora_model Naozumi/llama2-qlora-finetunined-cantonese \
    --output_type pth \
    --output_dir /Users/naozumi/Downloads/cantoneseModel
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
Base model: meta-llama/Llama-2-7b-chat-hf
LoRA model(s) ['Naozumi/llama2-qlora-finetunined-cantonese']:
Loading Naozumi/llama2-qlora-finetunined-cantonese
Cannot find lora model on the disk. Downloading lora model from hub...
Fetching 7 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 57456.22it/s]
Traceback (most recent call last):
  File "/Users/naozumi/Downloads/Chinese-LLaMA-Alpaca/scripts/merge_llama_with_chinese_lora_low_mem.py", line 246, in <module>
    tokenizer = LlamaTokenizer.from_pretrained(lora_model_path)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 96, in __init__
    self.sp_model.Load(vocab_file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string
naozumi@Naozumis-MacBook-Pro Chinese-LLaMA-Alpaca % 
```

**Comment by Naozumi520** [comment]
I've tried using both model name and the path of the local folder, still no luck.

**Comment by airaria** [comment]
Can you list the files in `Naozumi/llama2-qlora-finetunined-cantonese`? 
It looks like the problem is related to the tokenizer.

**Comment by ymcui** [comment]
```
Cannot find lora model on the disk. Downloading lora model from hub...
```
This tells you that the lora model `Naozumi/llama2-qlora-finetunined-cantonese` cannot be found. 
You should specify either a local folder or a huggingface identifier for `--lora_model`.
In this context, you need to check what files are there in `Naozumi/llama2-qlora-finetunined-cantonese` folder.

**Comment by Naozumi520** [comment]
README.md		adapter_config.json	adapter_model.bin	gitattributes.txt	special_tokens_map.json	tokenizer.json		tokenizer_config.json

These are the files in my lora folder.

**Comment by Naozumi520** [comment]
Maybe it was the problem of the Colab notebook. I was fine tuned using the `Llama_2_Fine_Tuning_using_QLora-2.ipynb` I could search on web. But it doesn't seemed to be saving the tokenizer so I added a line `tokenizer.push_to_hub("my-awesome-model")`.

**Comment by ymcui** [comment]
The merging script was intended for the models in this project, and thus we did not test the compatiblity of other models.
You might need to save your tokenizer into `tokenizer.model` first, and try to merge your model again. Also check `adapter_model.bin` is with a proper file size (at least several MB).
Refer to our Chinese-LLaMA-LoRA-7B: https://huggingface.co/ziqingyang/chinese-llama-lora-7b/tree/main and check what file was missing.

**Comment by Naozumi520** [comment]
<img width="679" alt="Screenshot 2023-08-31 at 8 52 15 AM" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/52615455/ca93eb43-c4d5-423b-9e00-431272cc26ec">

I've checked the `Llama_2_Fine_Tuning_using_QLora-2.ipynb` once again and it seems this notebook I used takes the tokenizer from the base model. This explained why the generated file `tokenizer.json` didn't contain any Chinese characters. 

The fact is what I'm trying to do is to fine-tune the model with my Cantonese datasets in JSON format (instruction, input and output). But I couldn't find one online notebook with capability to generate a tokenizer. What am I supposed to do?

**Comment by ymcui** [comment]
If you are going to do further instruction fine-tuning on Llama-2 series, refer to https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/sft_scripts_en

**Comment by Naozumi520** [comment]
I'm at the step setting value `chinese_tokenizer_path` in `run_sft.sh`. Do I have to use the tokenizer in this repo? It's not a problem tho, I'm just worrying the language branches I'm fine tuning in Cantonese.

**Comment by airaria** [comment]
> I'm at the step setting value `chinese_tokenizer_path` in `run_sft.sh`. Do I have to use the tokenizer in this repo? It's not a problem tho, I'm just worrying the language branches I'm fine tuning in Cantonese.

You must use the corresponding tokenizer released together with the model weights in order to fine-tune the model correctly.
