### ISSUE TITLE
X86 Linux服务器 运行非常缓慢

### ISSUE THREAD

**Issue by Yiyi-philosophy** [ymcui/Chinese-LLaMA-Alpaca#84]
![image](https://user-images.githubusercontent.com/86668817/230717373-ce9f4060-b914-4840-8d71-5b257f6d7eaf.png)
![image](https://user-images.githubusercontent.com/86668817/230717381-3483de0e-69eb-4745-8dde-da4dc01fef13.png)

7B 4int 量化模型，运行非常缓慢，10分钟只出现2行回答
```shell
./main \
    -m zh-models/7B/ggml-model-q4_0.bin \
        --color \
        -f ./prompts/alpaca.txt \
        -ins -c 100 \
        --temp 0.5 \
        -n 50 \
        --repeat_penalty 1.3
```

**Comment by ymcui** [comment]
`-t`可以增加线程数量，可以试试。
另外可以去llama.cpp官方目录里看看有没有解决方案。

**Comment by Yiyi-philosophy** [comment]
好的，谢谢您

**Comment by yi** [comment]
llama.cpp 的速度貌似受dimm内存速度的影响非常显著。试试看超频内存，回答速度可能明显提高。
