### ISSUE TITLE
how to continue  model training?

### ISSUE THREAD

**Issue by phamkhactu** [ymcui/Chinese-LLaMA-Alpaca#848]
### Check before submitting issues

- [X] Make sure to pull the latest code, as some issues and bugs have been fixed.
- [X] Due to frequent dependency updates, please ensure you have followed the steps in our [Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)
- [X] I have read the [FAQ section](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/FAQ) AND searched for similar issues and did not find a similar problem or solution
- [X] Third-party plugin issues - e.g., [llama.cpp](https://github.com/ggerganov/llama.cpp), [text-generation-webui](https://github.com/oobabooga/text-generation-webui), [LlamaChat](https://github.com/alexrozanski/LlamaChat), we recommend checking the corresponding project for solutions
- [X] Model validity check - Be sure to check the model's [SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md). If the model is incorrect, we cannot guarantee its performance

### Type of Issue

Model training and fine-tuning

### Base Model

LLaMA-7B

### Operating System

Linux

### Describe your issue in detail

I train model using ```run_clm_pt_with_peft.py ```, but my machine shutdown suddenly, model had trained some step. Now I want to resume from checkpoint lora to continue training. I've read the readme, I not found anything.

Many thanks for your help.

**Comment by GokulNC-Sarvam** [comment]
Hi @phamkhactu, how did you solve the problem?

**Comment by phamkhactu** [comment]
> Hi @phamkhactu, how did you solve the problem?

Hi @GokulNC-Sarvam, I use trainer and I resume from checkpoint
```
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)

```
