### ISSUE TITLE
最新版的transformers修改了LlamaTokenizer，使用最新的transformers转换合并的模型无法正常生成eos

### ISSUE THREAD

**Issue by sgsdxzy** [ymcui/Chinese-LLaMA-Alpaca#85]
新的LlamaTokenizer和原来的并不完全兼容，转换后的模型生成的内容看起来不太对，并且直到达到max length前无法自行结束。

**Comment by cnbeining** [comment]
https://github.com/huggingface/transformers/issues/22642 ?

意思是应该自己转换权重 或者用其他人的转换 别用 [decapoda-research/llama-7b-hf](https://huggingface.co/decapoda-research/llama-7b-hf) ？

**Comment by airaria** [comment]
> 新的LlamaTokenizer和原来的并不完全兼容，转换后的模型生成的内容看起来不太对，并且直到达到max length前无法自行结束。

这个问题的影响可能比较大，目前还不确定。可否发一份测试代码或测试样例？

目前如果有问题，那暂时只能用 huggingface/transformers#22642 之前的代码，比如
https://github.com/huggingface/transformers/tree/9eae4aa57650c1dbe1becd4e0979f6ad1e572ac0

**Comment by sgsdxzy** [comment]
@airaria 我好像也没有代码可以提供，我也没法上传我得到的权重，只是跑了一遍流程，：
1. 使用最新的transformers转换原始Llama权重为hf版本；
2. 使用此项目中的[merge_llama_with_chinese_lora.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_llama_with_chinese_lora.py)得到融合后的原始格式权重；
3. 使用最新的transformers转换融合后权重为hf版本；
4. 在任何一个前端或者脚本中进行推理（比如[text-generation-webui](https://github.com/oobabooga/text-generation-webui )），会发生以下问题：
  4.1 在纯英文的提问下，回答中偶尔突然出现中文；
  4.2 在中文提问下，回答了一部分内容后，开始出现无意义的中文内容；
  4.3 只会在达到max length后停下，不会因为eos token停下。

**Comment by airaria** [comment]
> @airaria 我好像也没有代码可以提供，我也没法上传我得到的权重，只是跑了一遍流程，：
> 
> 1. 使用最新的transformers转换原始Llama权重为hf版本；
> 2. 使用此项目中的[merge_llama_with_chinese_lora.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_llama_with_chinese_lora.py)得到融合后的原始格式权重；
> 3. 使用最新的transformers转换融合后权重为hf版本；
> 4. 在任何一个前端或者脚本中进行推理（比如[text-generation-webui](https://github.com/oobabooga/text-generation-webui)），会发生以下问题：
>    4.1 在纯英文的提问下，回答中偶尔突然出现中文；
>    4.2 在中文提问下，回答了一部分内容后，开始出现无意义的中文内容；
>    4.3 只会在达到max length后停下，不会因为eos token停下。

好的，我会检查一下流程。另外可否麻烦告知用llama.cpp推理是否正常？

**Comment by sgsdxzy** [comment]
> > @airaria 我好像也没有代码可以提供，我也没法上传我得到的权重，只是跑了一遍流程，：
> > 
> > 1. 使用最新的transformers转换原始Llama权重为hf版本；
> > 2. 使用此项目中的[merge_llama_with_chinese_lora.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_llama_with_chinese_lora.py)得到融合后的原始格式权重；
> > 3. 使用最新的transformers转换融合后权重为hf版本；
> > 4. 在任何一个前端或者脚本中进行推理（比如[text-generation-webui](https://github.com/oobabooga/text-generation-webui)），会发生以下问题：
> >    4.1 在纯英文的提问下，回答中偶尔突然出现中文；
> >    4.2 在中文提问下，回答了一部分内容后，开始出现无意义的中文内容；
> >    4.3 只会在达到max length后停下，不会因为eos token停下。
> 
> 好的，我会检查一下流程。另外可否麻烦告知用llama.cpp推理是否正常？

抱歉没有用过llama.cpp，我是用显卡跑的，最简单地话这样就能运行起来
```
import argparse
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

parser = argparse.ArgumentParser()
parser.add_argument('--model', type=str)
parser.add_argument('--int8', action='store_true')
args = parser.parse_args()

tokenizer = AutoTokenizer.from_pretrained(args.model, use_fast=False)  # fast版LlamaTokenizer载入非常慢，测试建议用slow的就好
model = AutoModelForCausalLM.from_pretrained(args.model, torch_dtype=torch.half, load_in_8bit=args.int8, device_map="balanced")
batch = tokenizer(
   """Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
你好！
### Response:
""",
    return_tensors="pt"
)
batch = {k: v.cuda() for k, v in batch.items()}
with torch.inference_mode(), torch.cuda.amp.autocast():
    print("Start")
    t0 = time.time()
    generated = model.generate(batch["input_ids"], attention_mask=batch["attention_mask"], max_length=200)
    t1 = time.time()
    print(f"Output generated in {(t1-t0):.2f} seconds")
    print(tokenizer.decode(generated[0]))
```

**Comment by airaria** [comment]
> 



> > > @airaria 我好像也没有代码可以提供，我也没法上传我得到的权重，只是跑了一遍流程，：
> > > 
> > > 1. 使用最新的transformers转换原始Llama权重为hf版本；
> > > 2. 使用此项目中的[merge_llama_with_chinese_lora.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_llama_with_chinese_lora.py)得到融合后的原始格式权重；
> > > 3. 使用最新的transformers转换融合后权重为hf版本；
> > > 4. 在任何一个前端或者脚本中进行推理（比如[text-generation-webui](https://github.com/oobabooga/text-generation-webui)），会发生以下问题：
> > >    4.1 在纯英文的提问下，回答中偶尔突然出现中文；
> > >    4.2 在中文提问下，回答了一部分内容后，开始出现无意义的中文内容；
> > >    4.3 只会在达到max length后停下，不会因为eos token停下。
> > 
> > 
> > 好的，我会检查一下流程。另外可否麻烦告知用llama.cpp推理是否正常？
> 
> 抱歉没有用过llama.cpp，我是用显卡跑的，最简单地话这样就能运行起来（这个可能看不出来4.3 eos问题，但是能看出4.2胡言乱语问题）
> 
> ```
> import argparse
> import torch
> from transformers import AutoModelForCausalLM, AutoTokenizer
> 
> parser = argparse.ArgumentParser()
> parser.add_argument('--model', type=str)
> parser.add_argument('--int8', action='store_true')
> args = parser.parse_args()
> 
> tokenizer = AutoTokenizer.from_pretrained(args.model, use_fast=False)  # fast版LlamaTokenizer载入非常慢，测试建议用slow的就好
> model = AutoModelForCausalLM.from_pretrained(args.model, torch_dtype=torch.half, load_in_8bit=args.int8, device_map="balanced")
> batch = tokenizer(
>    """Below is an instruction that describes a task. Write a response that appropriately completes the request.
> ### Instruction:
> 你好！
> ### Response:
> """,
>     return_tensors="pt"
> )
> batch = {k: v.cuda() for k, v in batch.items()}
> with torch.inference_mode(), torch.cuda.amp.autocast():
>     print("Start")
>     t0 = time.time()
>     generated = model.generate(batch["input_ids"], attention_mask=batch["attention_mask"], max_length=200)
>     t1 = time.time()
>     print(f"Output generated in {(t1-t0):.2f} seconds")
>     print(tokenizer.decode(generated[0]))
> ```

好的，我会尝试复现一下看看。

**Comment by airaria** [comment]
我在将Transformers更新到最新commit([656e869](https://github.com/huggingface/transformers/commit/656e869a4523f6a0ce90b3aacbb05cc8fb5794bb))后，使用merge_llama_with_chinese_lora.py融合权重，使用llama.cpp部署，暂时没有发现异常。

**Comment by airaria** [comment]
> [huggingface/transformers#22642](https://github.com/huggingface/transformers/issues/22642) ?
> 
> 意思是应该自己转换权重 或者用其他人的转换 别用 [decapoda-research/llama-7b-hf](https://huggingface.co/decapoda-research/llama-7b-hf) ？

对模型权重似乎没有影响。convert_llama_weights_to_hf.py中设计模型权重的部分几乎没有变动。

**Comment by cnbeining** [comment]
我从原版LLaMA转换的权重，供参考：

https://huggingface.co/cnbeining/Chinese-Alpaca-7B-Merged

16bit和4bit，给LLaMA.cpp用：

https://huggingface.co/cnbeining/Chinese-Alpaca-7B-Merged-16bit-4bit

**Comment by airaria** [comment]
> 

你测的是自己合并后又转回HF格式的7B模型吗？我用下面的代码没有问题。
如果不行，注意下用发布权重中的tokenizer相关文件（special_token_map.json, tokenizer_config.json)替换转回HF格式后自动生成的tokenizer相关文件试试

```python
import time
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer


tokenizer = LlamaTokenizer.from_pretrained('./')
model = LlamaForCausalLM.from_pretrained('./') #, torch_dtype=torch.half)
batch = tokenizer(
   """Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
你好！
### Response:
""",
    return_tensors="pt"
)
batch = {k: v for k, v in batch.items()}
with torch.inference_mode():
    print("Start")
    t0 = time.time()
    generated = model.generate(batch["input_ids"], attention_mask=batch["attention_mask"], max_length=200)
    t1 = time.time()
    print(f"Output generated in {(t1-t0):.2f} seconds")
    print(tokenizer.decode(generated[0]))
```

**Comment by airaria** [comment]
> 

> 

你测的是自己合并后又转回HF格式的7B模型吗？我用下面的代码没有问题。
如果不行，注意下用发布权重中的tokenizer相关文件（special_token_map.json, tokenizer_config.json)替换转回HF格式后自动生成的tokenizer相关文件试试

```python
import time
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer


tokenizer = LlamaTokenizer.from_pretrained('./')
model = LlamaForCausalLM.from_pretrained('./') #, torch_dtype=torch.half)
batch = tokenizer(
   """Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
你好！
### Response:
""",
    return_tensors="pt"
)
batch = {k: v for k, v in batch.items()}
with torch.inference_mode():
    print("Start")
    t0 = time.time()
    generated = model.generate(batch["input_ids"], attention_mask=batch["attention_mask"], max_length=200)
    t1 = time.time()
    print(f"Output generated in {(t1-t0):.2f} seconds")
    print(tokenizer.decode(generated[0]))
```

**Comment by sgsdxzy** [comment]
@airaria 我之前测的是13B，我重新测了一下7B，设置为
```
params = {
    "temperature": 0.7,
    "top_p": 0.1,
    "top_k": 40,
    "repetition_penalty": 1.18
}
```
这是本项目的输出（无论用不用lora里的tokenizer及配置文件替换都是一样的）
```
Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
如何健身？
### Response:
抱歉，但我能做这。请问我来学。 对了，那还行。好啊！太棒了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了
```

这是原版的llama-7b（不是alpaca）：
```
Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
如何健身？
### Response:
1) 你可以去跑步。
2) 或者做一些练习，比如拍手球、排球等。
3) 还有很多的其他方法。
4) 我们会在下面分析更多的方法。
5) 现在就来看一下这些方法：
6) 第一个是去跑步。
7) 第二个是做一些练习。
8) 第三个是抽水。
9) 第四个是喝茶。
```

我感觉明显是有问题的。

根据https://github.com/oobabooga/text-generation-webui/issues/931 https://www.reddit.com/r/Oobabooga/comments/12ez276/3060_vs_3090_same_model_and_presets_but_very/
好像这个问题只在部分显卡上存在，我是2080Ti 22G x 4（虽然跑本项目只需要用一个）

**Comment by airaria** [comment]
> @airaria 我之前测的是13B，我重新测了一下7B，设置为
> 
> ```
> params = {
>     "temperature": 0.7,
>     "top_p": 0.1,
>     "top_k": 40,
>     "repetition_penalty": 1.18
> }
> ```
> 
> 这是本项目的输出（无论用不用lora里的tokenizer及配置文件替换都是一样的）
> 
> ```
> Below is an instruction that describes a task. Write a response that appropriately completes the request.
> ### Instruction:
> 如何健身？
> ### Response:
> 抱歉，但我能做这。请问我来学。 对了，那还行。好啊！太棒了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了。太好了
> ```
> 
> 这是原版的llama-7b（不是alpaca）：
> 
> ```
> Below is an instruction that describes a task. Write a response that appropriately completes the request.
> ### Instruction:
> 如何健身？
> ### Response:
> 1) 你可以去跑步。
> 2) 或者做一些练习，比如拍手球、排球等。
> 3) 还有很多的其他方法。
> 4) 我们会在下面分析更多的方法。
> 5) 现在就来看一下这些方法：
> 6) 第一个是去跑步。
> 7) 第二个是做一些练习。
> 8) 第三个是抽水。
> 9) 第四个是喝茶。
> ```
> 
> 我感觉明显是有问题的。
> 
> 根据[oobabooga/text-generation-webui#931](https://github.com/oobabooga/text-generation-webui/issues/931) https://www.reddit.com/r/Oobabooga/comments/12ez276/3060_vs_3090_same_model_and_presets_but_very/ 好像这个问题只在部分显卡上存在，我是2080Ti 22G x 4（虽然跑本项目只需要用一个）

只用CPU正常吗？手边没有20系列和30系列显卡，如果是与特定显卡有关，有助于帮我们进一步定位问题。
l

**Comment by sgsdxzy** [comment]
@airaria 
我用pytorch+cpu的结果是这样的
```
Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
如何健身？
### Response:
抱歉，但我能做这。请问我来学。 很乐意教你。 我会给您一个好样的建议。 请求得有正向心！ 太长了，要少些。请求得有正向心！ 太长了，要少些。请求得有正向心！ 太长了，要少些。 请求得有正向心！ 太长了，要少些。 请求得有正向心！ 太长了，要少些。 请求得有正向心！ 太长了，要少些。 请求得有正向心！ 太长了，要少些。 请求得有正向心！ 太长了，要
```
还是不对。ggml的我没试，你需要我测一下吗？

**Comment by sgsdxzy** [comment]
其实别的有类似问题的比如gpt4-x-alpaca换成最新转换的llama tokenizer就可以了，偏偏这个项目的重点就是修改了原版的tokenizer……

**Comment by airaria** [comment]
我用下面的代码测试没问题：
```python
import time
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer


tokenizer = LlamaTokenizer.from_pretrained('./')
model = LlamaForCausalLM.from_pretrained('./') #, torch_dtype=torch.half)

single_inputs="""Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
如何健身？
### Response:
"""

batch = tokenizer(single_inputs,return_tensors="pt",padding=True)
batch = {k: v for k, v in batch.items()}
with torch.inference_mode():
    print("Start")
    t0 = time.time()
    generated = model.generate(batch["input_ids"], attention_mask=batch["attention_mask"], max_length=200,temperature=0.7,top_p=0.1,top_k=40,do_sample=True,num_beams=1)
    t1 = time.time()
    print(f"Output generated in {(t1-t0):.2f} seconds")
    for g in generated:
        print(tokenizer.decode(g))
```
输出：
```
<s> Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
如何健身？
### Response:
健身需要有计划和目标，可以从有氧运动、力量训练、瑜伽等多个方面入手，建议根据自身情况选择适合的运动方式和强度。</s>
```
`./`目录里有如下模型文件：
```
config.json
generation_config.json
PyTorch_model-00001-of-00002.bin
PyTorch_model-00002-of-00002.bin
pytorch_model.bin.index.json
special_tokens_map.json
 tokenizer.model
tokenizer_config.json
```

special_tokens_map.json的内容为：
```json
{
  "bos_token": "<s>",
  "eos_token": "</s>",
  "unk_token": "<unk>",
  "pad_token": "[PAD]"
}
```
tokenizer_config.json内容为：
```json
{
  "bos_token": "<s>",
  "eos_token": "</s>",
  "model_max_length": 1000000000000000019884624838656,
  "tokenizer_class": "LlamaTokenizer",
  "unk_token": "<unk>"
}
```

建议再检查一下模型，比对一下[shm256码](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md),

**Comment by sgsdxzy** [comment]
> 我用下面的代码测试没问题：
> 
> ```python
> import time
> import torch
> from transformers import LlamaForCausalLM, LlamaTokenizer
> 
> 
> tokenizer = LlamaTokenizer.from_pretrained('./')
> model = LlamaForCausalLM.from_pretrained('./') #, torch_dtype=torch.half)
> 
> single_inputs="""Below is an instruction that describes a task. Write a response that appropriately completes the request.
> ### Instruction:
> 如何健身？
> ### Response:
> """
> 
> batch = tokenizer(single_inputs,return_tensors="pt",padding=True)
> batch = {k: v for k, v in batch.items()}
> with torch.inference_mode():
>     print("Start")
>     t0 = time.time()
>     generated = model.generate(batch["input_ids"], attention_mask=batch["attention_mask"], max_length=200,temperature=0.7,top_p=0.1,top_k=40,do_sample=True,num_beams=1)
>     t1 = time.time()
>     print(f"Output generated in {(t1-t0):.2f} seconds")
>     for g in generated:
>         print(tokenizer.decode(g))
> ```
> 
> 输出：
> 
> ```
> <s> Below is an instruction that describes a task. Write a response that appropriately completes the request.
> ### Instruction:
> 如何健身？
> ### Response:
> 健身需要有计划和目标，可以从有氧运动、力量训练、瑜伽等多个方面入手，建议根据自身情况选择适合的运动方式和强度。</s>
> ```
> 
> `./`目录里有如下模型文件：
> 
> ```
> config.json
> generation_config.json
> PyTorch_model-00001-of-00002.bin
> PyTorch_model-00002-of-00002.bin
> pytorch_model.bin.index.json
> special_tokens_map.json
>  tokenizer.model
> tokenizer_config.json
> ```
> 
> special_tokens_map.json的内容为：
> 
> ```json
> {
>   "bos_token": "<s>",
>   "eos_token": "</s>",
>   "unk_token": "<unk>",
>   "pad_token": "[PAD]"
> }
> ```
> 
> tokenizer_config.json内容为：
> 
> ```json
> {
>   "bos_token": "<s>",
>   "eos_token": "</s>",
>   "model_max_length": 1000000000000000019884624838656,
>   "tokenizer_class": "LlamaTokenizer",
>   "unk_token": "<unk>"
> }
> ```
> 
> 建议再检查一下模型，比对一下[shm256码](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md),

我用的[hf上的lora](https://huggingface.co/ziqingyang/chinese-alpaca-lora-7b/tree/main)，原始Llama权重和lora的sha256是对的，合成出来的`consolidated.00.pth`的sha256不一样
看起来似乎没什么办法了

**Comment by airaria** [comment]
> 我用的[hf上的lora](https://huggingface.co/ziqingyang/chinese-alpaca-lora-7b/tree/main)，原始Llama权重和lora的sha256是对的，合成出来的`consolidated.00.pth`的sha256不一样 看起来似乎没什么办法了

那似乎应该不是tokenizer导致的问题？
我用最新的merge_llama_with_chinese_lora.py和Transformers(656e869a4)合并一遍6B模型，sha256还是一致的。

**Comment by sgsdxzy** [comment]
@airaria 
我的原始权重 
```
700df0d3013b703a806d2ae7f1bfb8e59814e3d06ae78be0c66368a50059f33d LLaMA/7B/consolidated.00.pth
```

转换后的HF权重
```
0087155d6df07106c1d910bfeb6aab1be8e612dfbf2b56ddfb4ccbde7dbd50d0  llama-7b/pytorch_model-00001-of-00002.bin
461bc5e50200db7813ff99cc0b9316c48ccbd6aaaa31bf8cf7bee0b64bc3eda3  llama-7b/pytorch_model-00002-of-00002.bin
```

lora
```
0d9b6ed8e4a7d1ae590a16c89a452a488d66ff07e45487972f61c2b6e46e36de  loras/ziqingyang_chinese-alpaca-lora-7b/adapter_model.bin
```

合成后的权重
```
466b85635f266fee7e08476c34593431210588fd9caee5c7d1ec56dc17ef9239  Chinese-Alpaca/7B/consolidated.00.pth
```

是不是从转换后的HF权重开始就不一样了

**Comment by airaria** [comment]
> @airaria 我的原始权重
> 
> ```
> 700df0d3013b703a806d2ae7f1bfb8e59814e3d06ae78be0c66368a50059f33d LLaMA/7B/consolidated.00.pth
> ```
> 
> 转换后的HF权重
> 
> ```
> 0087155d6df07106c1d910bfeb6aab1be8e612dfbf2b56ddfb4ccbde7dbd50d0  llama-7b/pytorch_model-00001-of-00002.bin
> 461bc5e50200db7813ff99cc0b9316c48ccbd6aaaa31bf8cf7bee0b64bc3eda3  llama-7b/pytorch_model-00002-of-00002.bin
> ```
> 
> lora
> 
> ```
> 0d9b6ed8e4a7d1ae590a16c89a452a488d66ff07e45487972f61c2b6e46e36de  loras/ziqingyang_chinese-alpaca-lora-7b/adapter_model.bin
> ```
> 
> 合成后的权重
> 
> ```
> 466b85635f266fee7e08476c34593431210588fd9caee5c7d1ec56dc17ef9239  Chinese-Alpaca/7B/consolidated.00.pth
> ```
> 
> 是不是从转换后的HF权重开始就不一样了

只有合并后的权重不一样，前面都是一样的。

**Comment by sgsdxzy** [comment]
@airaria 我找到问题了，是peft的问题，我用的main branch，用0.2.0以后就正常了。
问题虽然暂时解决了，我觉得以后会是个隐患……

**Comment by sgsdxzy** [comment]
@airaria 我找到了新版的合并方法，并提交了一个pr，可以支持直接导出到hf格式

**Comment by cokuehuang** [comment]
@airaria 我测试的chinese-alpaca-13B的模型，使用最新主线transformer合并后的模型，使用llama.cpp部署测试和demo很接近，但是用合并后的文件再转成hf格式，使用上面的测试代码报错：
`RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
        size mismatch for model.embed_tokens.weight: copying a param with shape torch.Size([49954, 5120]) from checkpoint, the shape in current model is torch.Size([32000, 5120]).
        size mismatch for lm_head.weight: copying a param with shape torch.Size([49954, 5120]) from checkpoint, the shape in current model is torch.Size([32000, 5120]).
`

**Comment by airaria** [comment]
> @airaria 我测试的chinese-alpaca-13B的模型，使用最新主线transformer合并后的模型，使用llama.cpp部署测试和demo很接近，但是用合并后的文件再转成hf格式，使用上面的测试代码报错：
> `RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM: size mismatch for model.embed_tokens.weight: copying a param with shape torch.Size([49954, 5120]) from checkpoint, the shape in current model is torch.Size([32000, 5120]). size mismatch for lm_head.weight: copying a param with shape torch.Size([49954, 5120]) from checkpoint, the shape in current model is torch.Size([32000, 5120]). `

修改合并后模型的config.json的vocab_size为49954

**Comment by cokuehuang** [comment]
@airaria 感谢！可以了。

**Comment by firslov** [comment]
请问上面你给出的demo中是自动将模型放到gpu中吗，还是需要在load时配置device_map？

**Comment by firslov** [comment]
@sgsdxzy 请问上面你给出的demo中是自动将模型放到gpu中吗，还是需要在load时配置device_map？

**Comment by sgsdxzy** [comment]
@firslov `device_map="balanced"`会自动把模型均匀切分到所有显卡，只要总显存够。单显卡也能正常工作。

**Comment by sgsdxzy** [comment]
@firslov 我是从我的测试脚本里抄来的，这一段是测试onnx/tensorrt之类的加速框架的，和这个问题无关

**Comment by firslov** [comment]
@sgsdxzy 好的明白啦，感谢解答。

**Comment by zixiliuUSC** [comment]
直接用merge_llama_with_chinese_lora_to_hf.py合并权重之后的shm256码是多少？

**Comment by sgsdxzy** [comment]
> 直接用merge_llama_with_chinese_lora_to_hf.py合并权重之后的shm256码是多少？

13B的llama和alpaca

```
1a452d4c671ac6afd6954968cb59151b42f1091f39bedab4b99b78a7b7cbeac7  models/chinese-llama-13b/pytorch_model-00001-of-00003.bin
ac9472043d18f9714a6cf38c29fd23b3d87b8b0c96aa2ab55d5c7f8303380adb  models/chinese-llama-13b/pytorch_model-00002-of-00003.bin
560ea30f47fdd413de86dd7a7f873d1b1f91f8ac6d3fc4bbdf8fce872c83b709  models/chinese-llama-13b/pytorch_model-00003-of-00003.bin

1a452d4c671ac6afd6954968cb59151b42f1091f39bedab4b99b78a7b7cbeac7  models/chinese-alpaca-13b/pytorch_model-00001-of-00003.bin
ac9472043d18f9714a6cf38c29fd23b3d87b8b0c96aa2ab55d5c7f8303380adb  models/chinese-alpaca-13b/pytorch_model-00002-of-00003.bin
560ea30f47fdd413de86dd7a7f873d1b1f91f8ac6d3fc4bbdf8fce872c83b709  models/chinese-alpaca-13b/pytorch_model-00003-of-00003.bin
```

**Comment by sgsdxzy** [comment]
> 

抱歉这里发错了，llama-13B的sha256sum是
```
3cc39932e6778aca8432560afe2c87f04f060fe562a3fa90f51f2929a84bbcd9  models/chinese-llama-13b/pytorch_model-00001-of-00003.bin
b89400cb92c9c4ea810a385f36c2b19cc789b8d46d493c839fdc18cbfec3d194  models/chinese-llama-13b/pytorch_model-00002-of-00003.bin
952b6e84941b5b471c3760144ed4d17fe0499739f343b66056e008a12d9b3bf9  models/chinese-llama-13b/pytorch_model-00003-of-00003.bin
```

**Comment by sunyafei01** [comment]
> > 直接用merge_llama_with_chinese_lora_to_hf.py合并权重之后的shm256码是多少？
> 
> 13B的llama和alpaca
> 
> ```
> 1a452d4c671ac6afd6954968cb59151b42f1091f39bedab4b99b78a7b7cbeac7  models/chinese-llama-13b/pytorch_model-00001-of-00003.bin
> ac9472043d18f9714a6cf38c29fd23b3d87b8b0c96aa2ab55d5c7f8303380adb  models/chinese-llama-13b/pytorch_model-00002-of-00003.bin
> 560ea30f47fdd413de86dd7a7f873d1b1f91f8ac6d3fc4bbdf8fce872c83b709  models/chinese-llama-13b/pytorch_model-00003-of-00003.bin
> 
> 1a452d4c671ac6afd6954968cb59151b42f1091f39bedab4b99b78a7b7cbeac7  models/chinese-alpaca-13b/pytorch_model-00001-of-00003.bin
> ac9472043d18f9714a6cf38c29fd23b3d87b8b0c96aa2ab55d5c7f8303380adb  models/chinese-alpaca-13b/pytorch_model-00002-of-00003.bin
> 560ea30f47fdd413de86dd7a7f873d1b1f91f8ac6d3fc4bbdf8fce872c83b709  models/chinese-alpaca-13b/pytorch_model-00003-of-00003.bin
> ```

你好，我计算出bin文件的sha256值和这些相同，可是正如您所说它们是错误的权重，确实使用这些权重的生成效果也非常差（经常只会回答<\s>）。请问我该如何正确地生成权重呢？
