### ISSUE TITLE
llama.cpp编译失败

### ISSUE THREAD

**Issue by controZheng** [ymcui/Chinese-LLaMA-Alpaca#86]
![image](https://user-images.githubusercontent.com/42229960/230727706-e5735177-7b89-44e5-a3e7-31b8d26cf66e.png)
编译失败是为什么啊？centos  
还有可以直接用GPU启动模型吗？

**Comment by ymcui** [comment]
llama.cpp的问题还请去对应repo查找一下解决方案，或者把最后几条丢到搜索引擎里找找。

**Comment by controZheng** [comment]
不用 llama 用其他方式可以部署吗

**Comment by controZheng** [comment]
> llama.cpp的问题还请去对应repo查询一下解决方案，或者把最后几条丢到搜索引擎里找。

不使用 llama 使用其他方式可以部署吗

**Comment by controZheng** [comment]
不使用 llama 使用其他方式可以部分设置吗

> llama.cpp的问题还请去对应repo查询一下解决方案，或者把最后几条丢到搜索引引擎里找。

不使用 llama 使用其他方式可以部署吗

**Comment by wl1320310292** [comment]
> 

你好，请问你解决这个问题了吗？我也遇到这个问题了

**Comment by wl1320310292** [comment]
你好，我也遇到这个问题了，请问你解决了吗？

**Comment by Sped0n** [comment]
实在不行用cmake试试？

**Comment by controZheng** [comment]
> 你好，我也遇到这个问题了，请问你解决了吗？

gcc版本不对 升级下版本就好了  只不过我是centos升级比较麻烦 目前测试的gcc 8可以编译
如果有GPU的话也可以用transformers 启动

**Comment by yyqin1991** [comment]
> 

用transformers是如何启动的？

**Comment by airaria** [comment]
> 用transformers是如何启动的？

参看这个https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/85#issuecomment-1501115241
