### ISSUE TITLE
扩充词表后加载

### ISSUE THREAD

**Issue by wzg-zhuo** [ymcui/Chinese-LLaMA-Alpaca#862]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

扩充词表后得到merge_hf，替换原来llama2的tokenizer文件，使用llama.cpp量化可以成功，但是加载模型时候报错

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```
llama.cpp

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = mostly Q5_0
llm_load_print_meta: model params     = 6.74 B
llm_load_print_meta: model size       = 4.33 GiB (5.52 BPW) 
llm_load_print_meta: general.name   = LLaMA v2
llm_load_print_meta: BOS token = 1 '<s>'
llm_load_print_meta: EOS token = 2 '</s>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: PAD token = 0 '<unk>'
llm_load_print_meta: LF token  = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.09 MB
error loading model: create_tensor: tensor 'token_embd.weight' has wrong shape; expected  4096, 49953, got  4096, 32000,     1,     1
llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "/home/aiproject/aiqa.py", line 2, in <module>
    from llm_file import llm,answer_func
  File "/home/aiproject/llm_file.py", line 24, in <module>
    llm=llm_init()
  File "/home/aiproject/llm_file.py", line 18, in llm_init
    llm = Llama(model_path=model_path, n_ctx=n_ctx, n_batch=n_batch, n_threads=N_THREADS)
  File "/home/miniconda3/lib/python3.10/site-packages/llama_cpp/llama.py", line 365, in __init__
    assert self.model is not None
AssertionError

**Comment by ymcui** [comment]
看错误信息中的这条
```
error loading model: create_tensor: tensor 'token_embd.weight' has wrong shape; expected 4096, 49953, got 4096, 32000, 1, 1
```

说明词向量矩阵还是32000（原版词表大小）。你应该检查一下量化前模型的词向量矩阵shape。
