### ISSUE TITLE
全量模型size mismatch 49954 vs. 32000? RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:

### ISSUE THREAD

**Issue by mikeda100** [ymcui/Chinese-LLaMA-Alpaca#87]
RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
	size mismatch for model.embed_tokens.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([32000, 4096]).
	size mismatch for lm_head.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([32000, 4096]).

代码如下：

from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig

model_path = "Chinese-LLaMA-Alpaca/merged_models/chinese_alpaca_merged_7b-hf/"
     
tokenizer = LlamaTokenizer.from_pretrained(model_path)
model = LlamaForCausalLM.from_pretrained(model_path)

--------------------------------------
merged-model的config.json文件：

{
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 2048,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "pad_token_id": 0,
  "rms_norm_eps": 1e-06,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.28.0.dev0",
  "use_cache": true,
  "vocab_size": 32000
}

--------------------------------
具体参考的是这里（也就是把第1步中的转化为hf格式的步骤，在得到merged-model之后，再做一遍）： 
https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/12

其中调用model是参考如下文字：

参考调用方法

https://github.com/LC1332/Chinese-alpaca-lora/blob/main/notebook/evaluation_code.ipynb
不需要lora合并 PeftModel.from_pretrained 这一步，直接加载使用就行了。

**Comment by airaria** [comment]
config.json中的vocab_size是49954吗？不是的话修改后再试试

**Comment by DumoeDss** [comment]
修改成49954会报一样错

**Comment by DumoeDss** [comment]
text generation提供了功能可以分别加载model与lora。用原版hf的llama配合Chinese-alpaca-lora是没有问题的，但是加载本项目的lora就会报上述错误。如果能够解决的话，就可以省去将lora和原模型融合这一步了。

**Comment by airaria** [comment]
从报错信息看模型的checkpoint的大小是正确的（49954），但初始化的模型embedding是32000，所以 加载不进去，问题应该只在config.json上。
能显示一下修改vocab_size后的Chinese-LLaMA-Alpaca/merged_models/chinese_alpaca_merged_7b-hf/config.json的内容吗

**Comment by mikeda100** [comment]
> 从报错信息看模型的checkpoint的大小是正确的（49954），但初始化的模型embedding是32000，所以 加载不进去，问题应该只在config.json上。 能显示一下修改vocab_size后的Chinese-LLaMA-Alpaca/merged_models/chinese_alpaca_merged_7b-hf/config.json的内容吗

补充在上面问题里啦。多谢！

**Comment by mikeda100** [comment]
> config.json中的vocab_size是49954吗？不是的话修改后再试试

改成49954就过了。可以这样改吗？这样改的依据是什么呢？
（背景：我是昨天才git clone的代码, 也就是说用的是最新的）

**Comment by mikeda100** [comment]
File [~/anaconda3/envs/env_flagai_copy3_Chinese_LLaMA/lib/python3.10/site-packages/transformers/generation/utils.py:1524](https://file+.vscode-resource.vscode-cdn.net/run/media/root/893767f0-0daa-4e5b-a599-4216c16d7878/DownloadedSoftwares/Chinese-LLaMA-Alpaca_ymcui/Chinese-LLaMA-Alpaca/merged_models/chinese_alpaca_merged_7b-hf/~/anaconda3/envs/env_flagai_copy3_Chinese_LLaMA/lib/python3.10/site-packages/transformers/generation/utils.py:1524), in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, streamer, **kwargs)
...
   2208     # remove once script supports set_grad_enabled
   2209     _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 2210 return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

-----------------------------------------------------------------------------

还是用的这里的调用方法：

其中调用model是参考如下文字：

参考调用方法

https://github.com/LC1332/Chinese-alpaca-lora/blob/main/notebook/evaluation_code.ipynb
不需要lora合并 PeftModel.from_pretrained 这一步，直接加载使用就行了。

--------------------------------------------------------------------------------

代码如下：


from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig

model_path = "Chinese-LLaMA-Alpaca/merged_models/chinese_alpaca_merged_7b-hf/"
     
tokenizer = LlamaTokenizer.from_pretrained(model_path)
model = LlamaForCausalLM.from_pretrained(model_path)
     

def generate_prompt(instruction, input=None):
    if input:
        return f"""Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{instruction}

### Input:
{input}

### Response:"""
    else:
        return f"""Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
{instruction}

### Response:"""
generation_config = GenerationConfig(
    temperature=0.1,
    top_p=0.75,
    num_beams=4,
)

def evaluate(instruction, input=None):
    prompt = generate_prompt(instruction, input)
    inputs = tokenizer(prompt, return_tensors="pt")
    input_ids = inputs["input_ids"].cuda()
    generation_output = model.generate(
        input_ids=input_ids,
        generation_config=generation_config,
        return_dict_in_generate=True,
        output_scores=True,
        max_new_tokens=256
    )
    for s in generation_output.sequences:
        output = tokenizer.decode(s)
        print("Response:", output.split("### Response:")[1].strip())
     


evaluate(input("Instruction: "))

**Comment by airaria** [comment]
> 为什么接下来这里又出错了呢？
> 
> File [~/anaconda3/envs/env_Chinese_LLaMA/lib/python3.10/site-packages/transformers/generation/utils.py:1524](https://file+.vscode-resource.vscode-cdn.net/Chinese-LLaMA-Alpaca/merged_models/chinese_alpaca_merged_7b-hf/~/anaconda3/envs/env_Chinese_LLaMA/lib/python3.10/site-packages/transformers/generation/utils.py:1524), in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, streamer, **kwargs) ... 2208 # remove once script supports set_grad_enabled 2209 _no_grad_embedding_renorm_(weight, input, max_norm, norm_type) -> 2210 return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
> 
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
> 
> 还是用的这里的调用方法：
> 
> 其中调用model是参考如下文字：
> 
> 参考调用方法
> 
> https://github.com/LC1332/Chinese-alpaca-lora/blob/main/notebook/evaluation_code.ipynb 不需要lora合并 PeftModel.from_pretrained 这一步，直接加载使用就行了。
> 
> 代码如下：
> 
> from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig
> 
> model_path = "Chinese-LLaMA-Alpaca/merged_models/chinese_alpaca_merged_7b-hf/"
> 
> tokenizer = LlamaTokenizer.from_pretrained(model_path) model = LlamaForCausalLM.from_pretrained(model_path)
> 
> def generate_prompt(instruction, input=None): if input: return f"""Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
> 
> ### Instruction:
> {instruction}
> 
> ### Input:
> {input}
> 
> ### Response:"""
> ```
> else:
>     return f"""Below is an instruction that describes a task. Write a response that appropriately completes the request.
> ```
> 
> ### Instruction:
> {instruction}
> 
> ### Response:"""
> generation_config = GenerationConfig( temperature=0.1, top_p=0.75, num_beams=4, )
> 
> def evaluate(instruction, input=None): prompt = generate_prompt(instruction, input) inputs = tokenizer(prompt, return_tensors="pt") input_ids = inputs["input_ids"].cuda() generation_output = model.generate( input_ids=input_ids, generation_config=generation_config, return_dict_in_generate=True, output_scores=True, max_new_tokens=256 ) for s in generation_output.sequences: output = tokenizer.decode(s) print("Response:", output.split("### Response:")[1].strip())
> 
> evaluate(input("Instruction: "))

先只用CPU试试。

**Comment by mikeda100** [comment]
evaluate("你推荐我买最新款的iphone吗？")

不返回任何结果是怎么会事呢？

**Comment by DumoeDss** [comment]
> 从报错信息看模型的checkpoint的大小是正确的（49954），但初始化的模型embedding是32000，所以 加载不进去，问题应该只在config.json上。 能显示一下修改vocab_size后的Chinese-LLaMA-Alpaca/merged_models/chinese_alpaca_merged_7b-hf/config.json的内容吗

我使用text-generation-webui报错如下：
` raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
        size mismatch for base_model.model.model.embed_tokens.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([32000, 4096]).
        size mismatch for base_model.model.lm_head.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([32000, 4096]).`

原hf模型修改vocab_size如下：
`{
    "architectures": ["LlamaForCausalLM"],
    "bos_token_id": 0,
    "eos_token_id": 1,
    "hidden_act": "silu",
    "hidden_size": 4096,
    "intermediate_size": 11008,
    "initializer_range": 0.02,
    "max_sequence_length": 2048,
    "model_type": "llama",
    "num_attention_heads": 32,
    "num_hidden_layers": 32,
    "pad_token_id": -1,
    "rms_norm_eps": 1e-06,
    "torch_dtype": "float16",
    "transformers_version": "4.27.0.dev0",
    "use_cache": true,
    "vocab_size": 49954
}
`

**Comment by iMountTai** [comment]
@DumoeDss 目前的text-generation-webui中lora加载的是原始llama的tokenizer，即32000，但是lora的tokenizer长度是49954，合并权重时会出现冲突，因此在合并前，需将原本模型的权重通过`resize_token_embeddings`方法进行修改。

**Comment by kongbohu** [comment]
> @DumoeDss 目前的text-generation-webui中lora加载的是原始llama的tokenizer，即32000，但是lora的tokenizer长度是49954，合并权重时会出现冲突，因此在合并前，需将原本模型的权重通过`resize_token_embeddings`方法进行修改。
请教一下，我已经在LLAMA基础上进行了自收集的英文语料的finetue，如果直接合并贵项目的中文lora，恐会对整体权重造成混乱。如果只想使用扩充的中文词表及tokenizer是否可行？
我猜测的步骤是这样：

**Comment by kongbohu** [comment]
> > @DumoeDss 目前的text-generation-webui中lora加载的是原始llama的tokenizer，即32000，但是lora的tokenizer长度是49954，合并权重时会出现冲突，因此在合并前，需将原本模型的权重通过`resize_token_embeddings`方法进行修改。
> 
> 请教一下，目前我已经在LLAMA基础上进行了自收集的英文语料的finetue，如果直接合并贵项目的中文lora，恐会对整体权重造成混乱。如果只想使用扩充的中文词表及tokenizer是否可行？ 我猜测的步骤是这样：
> 
>     1. 通过model = transformers.AutoModelForCausalLM.from_pretrained 加载英文finetune后的整体模型权重
> 
>     2. 执行model.resize_token_embeddings(49954)
> 
>     3. 将全量模型存储在新模型目录
> 
>     4. 将中文扩充后的tokenizer.model拷贝入新模型目录，并修改config.json中的vocab_size
> 
>     5. 载入此新模型后，就可以使用扩充的中文tokenizer进行中文finetune了
>        请指教是否可行 @iMountTai

seems work :)

**Comment by shibing624** [comment]
download https://huggingface.co/minlik/chinese-alpaca-plus-7b-merged/tree/main and update config.json vocab_size = 49954, it work and can finetune.

**Comment by iMountTai** [comment]
> 

:smiley:
