### ISSUE TITLE
13b所有步骤完成后，推理报错。tensor 'tok_embeddings.weight' has wrong size in model file

### ISSUE THREAD

**Issue by shmily91** [ymcui/Chinese-LLaMA-Alpaca#88]
~/桌面/llama.cpp$ ./main -m ./zh-models/13B/ggml-model-q4_0.bin --color -f ./prompts/alpaca.txt -p "详细介绍一下北京的名胜古迹：" -n 512
main: seed = 1680978958
llama_model_load: loading model from './zh-models/13B/ggml-model-q4_0.bin' - please wait ...
llama_model_load: n_vocab = 49954
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 5120
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 40
llama_model_load: n_layer = 40
llama_model_load: n_rot   = 128
llama_model_load: f16     = 2
llama_model_load: n_ff    = 13824
llama_model_load: n_parts = 2
llama_model_load: type    = 2
llama_model_load: ggml map size = 7869.63 MB
llama_model_load: ggml ctx size = 101.25 KB
llama_model_load: mem required  = 9917.73 MB (+ 1608.00 MB per state)
llama_model_load: loading tensors from './zh-models/13B/ggml-model-q4_0.bin'
llama_model_load: tensor 'tok_embeddings.weight' has wrong size in model file
llama_init_from_file: failed to load model
main: error: failed to load model './zh-models/13B/ggml-model-q4_0.bin'

请问我是那个步骤出错了？

**Comment by ymcui** [comment]
你先校验一下ggml-model-q4_0.bin的SHA256：
```
d0e1b9279bd9be606073acf2fb204e616d2f7e4e833b7ff60620ebdfb8fa4e73  ggml-model-q4_
```

**Comment by airaria** [comment]
以及检查一下在转ggml那一步，使用的tokenizer.model是否正确。

**Comment by shmily91** [comment]
> 你先校验一下ggml-model-q4_0.bin的SHA256：
> 
> ```
> d0e1b9279bd9be606073acf2fb204e616d2f7e4e833b7ff60620ebdfb8fa4e73  ggml-model-q4_0.bin
> ```

好的，谢谢，已经解决了。是你们说的问题，我文件太乱了用错了模型
