### ISSUE TITLE
请教全量模型merged model不生成任何回复是怎么会事呢？

### ISSUE THREAD

**Issue by mikeda100** [ymcui/Chinese-LLaMA-Alpaca#89]
具体问题在这里（我想可能还是新开一个不同的issue比较好）：
https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/87#issuecomment-1501024062

症状表现：

evaluate("你推荐我买最新款的iphone吗？")

不返回任何结果是怎么会事呢？

输出为：

Response: <[/s]

**Comment by mikeda100** [comment]
如果用另外一个示例里面的代码：
跑是能跑，但是结果只回答非常简短的一句话：

```
Start
Output generated in 4.43 seconds
<s> Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
你推荐我买最新款的iphone吗？
### Response:
根据您的需求和预算，我建议您考虑购买最新款的iPhone。</s>

```
源代码如下：

```
import time
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer

model_path = "Chinese-LLaMA-Alpaca/merged_models/chinese_alpaca_merged_7b-hf/"

tokenizer = LlamaTokenizer.from_pretrained(model_path)
model = LlamaForCausalLM.from_pretrained(model_path) #, torch_dtype=torch.half)

batch = tokenizer(
   """Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
你推荐我买最新款的iphone吗？
### Response:
""",
    return_tensors="pt"
)
batch = {k: v for k, v in batch.items()}
with torch.inference_mode():
    print("Start")
    t0 = time.time()
    generated = model.generate(batch["input_ids"], attention_mask=batch["attention_mask"], max_length=1024)
    t1 = time.time()
    print(f"Output generated in {(t1-t0):.2f} seconds")
    print(tokenizer.decode(generated[0]))
    
```

**Comment by airaria** [comment]
> 如果用另外一个示例里面的代码： 跑是能跑，但是结果只回答非常简短的一句话：
> 
> ```
> Start
> Output generated in 4.43 seconds
> <s> Below is an instruction that describes a task. Write a response that appropriately completes the request.
> ### Instruction:
> 你推荐我买最新款的iphone吗？
> ### Response:
> 根据您的需求和预算，我建议您考虑购买最新款的iPhone。</s>
> ```
> 
> 源代码如下：
> 
> ```
> import time
> import torch
> from transformers import LlamaForCausalLM, LlamaTokenizer
> 
> model_path = "Chinese-LLaMA-Alpaca/merged_models/chinese_alpaca_merged_7b-hf/"
> 
> tokenizer = LlamaTokenizer.from_pretrained(model_path)
> model = LlamaForCausalLM.from_pretrained(model_path) #, torch_dtype=torch.half)
> 
> batch = tokenizer(
>    """Below is an instruction that describes a task. Write a response that appropriately completes the request.
> ### Instruction:
> 你推荐我买最新款的iphone吗？
> ### Response:
> """,
>     return_tensors="pt"
> )
> batch = {k: v for k, v in batch.items()}
> with torch.inference_mode():
>     print("Start")
>     t0 = time.time()
>     generated = model.generate(batch["input_ids"], attention_mask=batch["attention_mask"], max_length=1024)
>     t1 = time.time()
>     print(f"Output generated in {(t1-t0):.2f} seconds")
>     print(tokenizer.decode(generated[0]))
>     
> ```

这个结果是正常的。
一方面解码结果有随机性，多试几次可能每次结果都不同；
另一方面解码参数有非常大影响，比你可以尝试用不同的temperature、top_p等参数等进行解码。
展示的例子是用llama.cpp配合它的解码策略解码得到的；用Transformers的话，如果想得到类似的效果，参数需要重新调整。

**Comment by airaria** [comment]
`model.generate(batch["input_ids"], attention_mask=batch["attention_mask"], max_length=200,temperature=0.7,top_p=0.95,do_sample=True,num_beams=1)`生成的结果：

```
### Instruction:
你推荐我买最新款的iphone吗？
### Response:
当然可以，但是如果您有旧的iphone可以再使用，那么建议先考虑旧iphone的使用情况再考虑是否需要买新的iphone。</s>
```

**Comment by mikeda100** [comment]
还是非常简短：
```
Start
Output generated in 18.63 seconds
<s> Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
我想让你做一名记者。您将报道突发新闻，撰写专题报道和评论文章，验证信息，发现来源，遵守新闻道德，并使用您自己独特的风格提供准确的报道。我的第一个请求是“我需要帮助写一篇关于世界主要城市空气污染的文章。
### Response:
好的，我可以帮助您写一篇关于世界主要城市空气污染的文章。请告诉我您需要什么样的信息，以及您对该主题的看法。</s>

```

**Comment by airaria** [comment]
> 我想让你做一名记者。您将报道突发新闻，撰写专题报道和评论文章，验证信息，发现来源，遵守新闻道德，并使用您自己独特的风格提供准确的报道。我的第一个请求是“我需要帮助写一篇关于世界主要城市空气污染的文章。

我用如下参数运行llama.cpp:，7B模型的班精度版本
```bash
./main -m zh-models-alpaca/7B/ggml-model-f16.bin --color -f ./prompts/alpaca.txt -ins -c 2048 --temp 0.2 -n 512 --repeat_penalty 1.3
```
生成如下：
```
> 我需要帮助写一篇关于世界主要城市空气污染的文章
全球各地的城市都面临着严重的空气污染问题。以下是一些有关于这些问题的关键信息：

1. 大气污染物是导致城市空气质量恶化的主要原因之一，包括汽车尾气、工业废物和燃煤等。
2. 根据世界卫生组织的数据显示，超过70％的全球人口生活在受过严重环境影响的城市中。
3. 在许多大城市，PM2.5浓度已经超过了安全标准，这可能对健康造成威胁。
4. 空气污染不仅会影响人类的身体健康，还会导致气候变化和自然灾害等负面后果。
5. 为了解决城市空气质量问题，需要采取多种措施，包括加强环保法规的执行、推广清洁能源技术以及鼓励人们采用公共交通工具等等。
```

**Comment by mikeda100** [comment]
大家有没有在全量和非量化裁剪的情况下，找到最优的参数组合？

**Comment by mikeda100** [comment]
是上述程序有问题，还是参数有问题？

**Comment by iMountTai** [comment]
@mikeda100 目前[hf推理代码](https://github.com/ymcui/Chinese-LLaMA-Alpaca#%E4%BD%BF%E7%94%A8transformers%E6%8E%A8%E7%90%86)已更新，以下是生成结果，因为参数设置具有随机性，供参考
![image](https://user-images.githubusercontent.com/35353688/231667130-2f4c0067-d807-4a58-aafd-346a0a9c3296.png)

**Comment by ykk648** [comment]
13B结果：
![2023-04-13 15-11-25 的屏幕截图](https://user-images.githubusercontent.com/19514053/231683057-4d5a7e6c-301c-4590-875c-d732e374a2c7.png)
7B结果：
![2023-04-13 15-16-03 的屏幕截图](https://user-images.githubusercontent.com/19514053/231683075-c45565ee-b08b-477e-858f-bcd68cb516e7.png)

**Comment by airaria** [comment]
> 13B结果：
> ![2023-04-13 15-11-25 的屏幕截图](https://user-images.githubusercontent.com/19514053/231683057-4d5a7e6c-301c-4590-875c-d732e374a2c7.png)
> 7B结果：
> ![2023-04-13 15-16-03 的屏幕截图](https://user-images.githubusercontent.com/19514053/231683075-c45565ee-b08b-477e-858f-bcd68cb516e7.png)

有些随机性，而且因为框架解码策略不同，也很难做到transformers的推理效果和llama.cpp一致；
可以试着调高温度，生成结果会多样一些

**Comment by airaria** [comment]
另外也可以通过往prompt_input的结尾添加'\n'的方式，改变模型的输出倾向：
![image](https://user-images.githubusercontent.com/4355449/231689116-69fe356c-468f-40e5-ada2-5fac76b9b528.png)
