### ISSUE TITLE
请问在哪下载您33B模型的全部权重，并且有无quick start？

### ISSUE THREAD

**Issue by 141forever** [ymcui/Chinese-LLaMA-Alpaca#899]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

下载问题

### 基础模型

Alpaca-33B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by ymcui** [comment]
https://github.com/ymcui/Chinese-LLaMA-Alpaca?tab=readme-ov-file#推荐模型下载 
其中，原版的llama-33b需要自行获取，meta不允许二次分发。

现在llama已经升级到3代了，建议使用最新版：https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/

**Comment by 141forever** [comment]
https://huggingface.co/minlik/chinese-alpaca-33b-merged这个请问是您们的模型吗

**Comment by ymcui** [comment]
> https://huggingface.co/minlik/chinese-alpaca-33b-merged 这个请问是您们的模型吗

这是第三方合并的模型。LoRA用的是我们的，但不是plus/pro版。基模型用的不是meta官方的。不保证合并后的模型是正确的。

**Comment by 141forever** [comment]
> > https://huggingface.co/minlik/chinese-alpaca-33b-merged 这个请问是您们的模型吗
> 
> 这是第三方合并的模型。LoRA用的是我们的，但不是plus/pro版。基模型用的不是meta官方的。不保证合并后的模型是正确的。

明白了，非常感谢！
