### ISSUE TITLE
找不到params.json 文件，模型文件里面也没有这个文件呀

### ISSUE THREAD

**Issue by Song367** [ymcui/Chinese-LLaMA-Alpaca#90]
FileNotFoundError: [Errno 2] No such file or directory: 
'/content/drive/MyDrive/model/7B/params.json'

**Comment by ymcui** [comment]
不知道你说的模型文件指的是什么。`params.json`是原版llama自带的，你自己按下面的信息写一个吧。
7B：
```
{"dim": 4096, "multiple_of": 256, "n_heads": 32, "n_layers": 32, "norm_eps": 1e-06, "vocab_size": -1}
```

13B：
```
{"dim": 5120, "multiple_of": 256, "n_heads": 40, "n_layers": 40, "norm_eps": 1e-06, "vocab_size": -1}
```

**Comment by ymcui** [comment]
> 跑”手动模型合并与转换“这一步时候遇到这个问题，确实非常迷惑人，建议把这个文件和怎么填放文档里👉🏻https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/%E6%89%8B%E5%8A%A8%E6%A8%A1%E5%9E%8B%E5%90%88%E5%B9%B6%E4%B8%8E%E8%BD%AC%E6%8D%A2

@portfoliomgrzdt 不清楚为什么会迷惑。原版llama自带的params.json文件。如果不是facebook官方渠道获取的自己按上面写一份就行了。

**Comment by g2zr004** [comment]
> 

这个params是不是v1.5的和前面的不一样了
