### ISSUE TITLE
Size([49952, 5120]) from checkpoint V.S. Size([49953, 5120]). from model

### ISSUE THREAD

**Issue by cArlIcon** [ymcui/Chinese-LLaMA-Alpaca#91]
when I load Chiness-LLaMA-13B model (hugging face format) an error raise
raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}") RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM: 	size mismatch for lm_head.weight: copying a param with shape torch.Size([49952, 5120]) from checkpoint, the shape in current model is torch.Size([49953, 5120]).

I have combined with original LLaMA-13B and convert to hugging face format
config.json
{
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 5120,
  "initializer_range": 0.02,
  "intermediate_size": 13824,
  "max_position_embeddings": 2048,
  "model_type": "llama",
  "num_attention_heads": 40,
  "num_hidden_layers": 40,
  "pad_token_id": 0,
  "rms_norm_eps": 1e-06,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.28.0.dev0",
  "use_cache": true,
  "vocab_size": 49953
}

**Comment by airaria** [comment]
That's weird. The vocab size of the Chinese-Llama-13B-LoRA is 49953, but where does the 49952 come from?
Can you provide more information, such as your loading script？

**Comment by cArlIcon** [comment]
Just use stanford alpaca  train.py and Chinese-Alpaca-13B, Chiness-LLaMA-7B, Chiness-Alpaca-7B can be loaded normally

transformers.AutoModelForCausalLM.from_pretrained

env: A100 * 8
torchrun --nproc_per_node=8  train.py \
  --model_name_or_path /xxxx \
  --data_path /xxxx \
  --bf16 True \
  --output_dir /xxxx \
  --num_train_epochs 3 \
  --per_device_train_batch_size 1 \
  --per_device_eval_batch_size 1 \
  --gradient_accumulation_steps 8 \
  --evaluation_strategy "no" \
  --save_strategy "steps" \
  --save_steps 2000 \
  --save_total_limit 1 \
  --learning_rate 2e-5 \
  --weight_decay 0. \
  --warmup_ratio 0.03 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --fsdp "full_shard auto_wrap" \
  --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
  --tf32 True

**Comment by cArlIcon** [comment]
> That's weird. The vocab size of the Chinese-Llama-13B-LoRA is 49953, but where does the 49952 come from? Can you provide more information, such as your loading script？

Just use stanford alpaca train.py and Chinese-Alpaca-13B, Chiness-LLaMA-7B, Chiness-Alpaca-7B can be loaded normally

transformers.AutoModelForCausalLM.from_pretrained

env: A100 * 8
torchrun --nproc_per_node=8 train.py
--model_name_or_path /xxxx
--data_path /xxxx
--bf16 True
--output_dir /xxxx
--num_train_epochs 3
--per_device_train_batch_size 1
--per_device_eval_batch_size 1
--gradient_accumulation_steps 8
--evaluation_strategy "no"
--save_strategy "steps"
--save_steps 2000
--save_total_limit 1
--learning_rate 2e-5
--weight_decay 0.
--warmup_ratio 0.03
--lr_scheduler_type "cosine"
--logging_steps 1
--fsdp "full_shard auto_wrap"
--fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer'
--tf32 True
