### ISSUE TITLE
本地部署可以做那种类似GPT4all的release吗？

### ISSUE THREAD

**Issue by Gong1suwu** [ymcui/Chinese-LLaMA-Alpaca#94]
可以做那种类似GPT4all的release吗？
只需要将bin文件放在一个路径里，运行命令行即可，实现快速本地部署体验

**Comment by airaria** [comment]
之所以选择现在这种部署方式，一方面，是出于遵守LLaMA模型的开源协议的要求，尽量避免潜在的风险；另一方面，该项目由个人维护，精力有限，难以跟进各种部署方式。
不过还是谢谢你的建议，我们会调研和评估其他部署方式的可能性。

**Comment by Gong1suwu** [comment]
> 之所以选择现在这种部署方式，一方面，是出于遵守LLaMA模型的开源协议的要求，尽量避免潜在的风险；另一方面，该项目由项目成员业余时间维护，精力有限，难以跟进各种部署方式。 不过还是谢谢你的建议，我们会调研和评估其他部署方式的可能性。

感谢，包括https://github.com/antimatter15/alpaca.cpp这里，都实现了快速部署，比较简单、直接

**Comment by ymcui** [comment]
> > 之所以选择现在这种部署方式，一方面，是出于遵守LLaMA模型的开源协议的要求，尽量避免潜在的风险；另一方面，该项目由项目成员业余时间维护，精力有限，难以跟进各种部署方式。 不过还是谢谢你的建议，我们会调研和评估其他部署方式的可能性。
> 
> 感谢，包括[https://github.com/antimatter15/alpaca.cpp这里，都实现了快速部署，比较简单、直接](https://github.com/antimatter15/alpaca.cpp%E8%BF%99%E9%87%8C%EF%BC%8C%E9%83%BD%E5%AE%9E%E7%8E%B0%E4%BA%86%E5%BF%AB%E9%80%9F%E9%83%A8%E7%BD%B2%EF%BC%8C%E6%AF%94%E8%BE%83%E7%AE%80%E5%8D%95%E3%80%81%E7%9B%B4%E6%8E%A5)

github上已经有一些第三方将我们的权重转换成bin文件的分流项目了，具体麻烦自己找一下吧。LLaMA版权问题这一点我们没法做出妥协，请谅解。
