### ISSUE TITLE
CPU有点慢，有什么办法能在GPU上运行吗?

### ISSUE THREAD

**Issue by Lufffya** [ymcui/Chinese-LLaMA-Alpaca#99]

**Comment by BensonBlack** [comment]
同问

**Comment by airaria** [comment]
我们会近期给出一个inference的简单脚本供参考。

**Comment by airaria** [comment]
已更新[Transformers原生推理脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/inference_hf.py)和[使用说明](https://github.com/ymcui/Chinese-LLaMA-Alpaca#使用transformers推理)，欢迎参考
